### ISSUE TITLE
Device targets and antenna_gain

### ISSUE THREAD

**Issue by ghost** [openwrt/luci#1010]
With LEDE providing individual compilation targets for devices, the use of the option antenna_gain would make sense.

E.g. a TP-Link TL-WR842NDv1 has the target tl-wr842n-v1. The antennas shipped have 5dBi. With these antennas attached the maximum EIRP for the ETSI domain would be 20dBi. The maximum effective txpower would be 15dBi. In case you replace the antennas by ones with a higher relative gain you risk to exceed the legal EIRP.

The same applies to 5GHz outdoor devices such as UBNT's Airgrid, Powerbeam, Nanobrigde etc, where an identical feed can be mounted to different reflectors.

The current settings of LuCI are limited to txpower only. Txpower is limited by the country domain only. The antenna's relative gain will be ignored.

While uci supports antenna_gain, LuCI does not offer to set that option.

It would therefore request to add the setting in UCI first and to initialize devices according to their respective profile on the long term.

**Comment by jow-** [comment]
This needs to happen on the OpenWrt side
