### ISSUE TITLE
Luci :Apply and save does not work

### ISSUE THREAD

**Issue by vic1126** [openwrt/luci#1029]
Hi
I add serial config using cbi,It displays correct, but when I input new content,  use save button, it does not work, any help? I am at LuCI 15.05-149-g0d8bbd2 Release.

local sys   = require "luci.sys"
local fs    = require "nixio.fs"
require("luci.config")

local m, s, o
m = Map("s2t", translate("Serial Server"), translate("Configure Serial Server"))
m:chain("luci")
s = m:section(TypedSection, "Serial_Server",translate("Serial Server"))
s.addremove = false
s.anonymous = true
s:tab("general",  translate("General Settings"))
o = s:taboption("general", Value, "comm_port", translate("Comm Port"))
function o.write(self, section, value)
   m.uci:set("s2t", "Serial_Server", "comm_port", "TEST")
end

return m

**Comment by psyborg55** [comment]
i've noticed this also, tried once again and it applied the changes

**Comment by bnelson61** [comment]
Did you try and add this to /etc/config/ucitrack?

**Comment by jow-** [comment]
No response and no official LuCI code.
