### ISSUE TITLE
relayd changing settings does not reload relayd daemon

### ISSUE THREAD

**Issue by finasfinas** [openwrt/luci#1049]
When changing a setting on the bridge interface and saving, the setting is not applied, but the configuration setting is properly configured.

for instance, changing he "host expiracy timeout" doesn't do anything until relayd is manually restarted or the device rebooted.

**Comment by feckert** [comment]
This issue is quite old and no other has reported such a problem. Also, the version information is missing! If the problem persists in the master then feel free to reopen.
