### ISSUE TITLE
wifi signal strength indication icon problem

### ISSUE THREAD

**Issue by psyborg55** [openwrt/luci#1060]
if you check signal strength icon in luci it is quite obvious the second bar from the left is thinner than rest of these. have you got a blind graphic developer when it was made?

**Comment by ProtoFoo** [comment]
That is some sharp eye catching this.
![image](https://cloud.githubusercontent.com/assets/2453666/23916722/74a7181a-08ed-11e7-9788-b9308ee024e7.png)

**Comment by jow-** [comment]
Feel free to provider better icons.
