### ISSUE TITLE
luci-theme-material: there is no style for .cbi-input-invalid.

### ISSUE THREAD

**Issue by aa65535** [openwrt/luci#1070]
When the input data is invalid, it will be added class `.cbi-input-invalid`, but the theme did not give the corresponding style as a hint.

**Comment by djhamzas** [comment]
sorry  i am a new in luci I want to start developing LUCI ,  How can i Get started , is there an editor for that 
what tools

**Comment by djhamzas** [comment]
Any Help

**Comment by hnyman** [comment]
> sorry i am a new in luci I want to start developing LUCI , How can i Get started , is there an editor for that
what tools

Luci source code is just text files. You can edit those with any text editor (gedit, nano, emacs, whatever...)
And there is no visual integrated development environment or anything like that. So the learning curve is pretty high.

(and please, ask this kind of questions in the Openwrt / LEDE forums, as your questin has nothing to do with this isue that you hijacked)
