### ISSUE TITLE
In login page,how can change the password?

### ISSUE THREAD

**Issue by daxiongz** [openwrt/luci#1078]
I want to change my login password,how can i do?
![image](https://cloud.githubusercontent.com/assets/19296863/24320207/93536094-116b-11e7-97be-e40642d097c9.png)
System change password like this.where dose "luci.sys.user.setpasswd" statement store the password?

**Comment by hnyman** [comment]
Openwrt / LEDE is just a normal Linux.  You change password from ssh console with "passwd" and the password gets stored in /etc/passwd and /etc/shadow

Luci makes the change using the same passwd command, which it calls from: 
https://github.com/openwrt/luci/blob/master/modules/luci-base/luasrc/sys.lua#L593
