### ISSUE TITLE
[PATCH] Some strings are escaped twice in XHTML ("'" is displayed as "&#39;")

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#112]
**Reported by reporter on 16 Mar 2010 15:03 UTC**
The problem is probably best illustrated by the two attached files. This is all on SVN trunk, I did not test any other version.

Basically, strings containing the "'" (apostrophe) character are, in some fields (like the navigation bar and some titles), converted to "&amp;!#39;" instead of "&#39;".

As I said, this doesn't happen everywhere on a page (I attached two examples so you can see where it happens exactly). Some "'" (apostrophe) are not escaped at all and displayed correctly, some are converted to "&#39;" and displayed correctly, some are converted to "&amp;!#39;" and displayed as "&#39;" in the browser.

'''Note:''' The two attached files show the Status?Interfaces and System?System pages respectively, using the French locale. I modified the translation string for "System" to "L'Systme" in order to have more apostrophes on the page.
## 

Benot Knecht

**Comment by pjuhen** [comment]
I have still the same issue. Pages are displayed with <meta charset="utf-8">.
In the lmo file, the single quote is in utf-8 (0x27), but displayed as &#39; Doesn't seem to be translate function. It's somewhere in uhttpd...

**Comment by pjuhen** [comment]
Pages are displayed with \&#39;
