### ISSUE TITLE
luci-app-adblock (adblock-2.6.1) - xml parsing error (theme openwrt)

### ISSUE THREAD

**Issue by build000** [openwrt/luci#1127]
@dibdot
system/luci version: LEDE Reboot SNAPSHOT r4042-e5bbead / LuCI Master (git-17.116.42736-415b99d)
theme: openwrt (only to this theme - bootstrap and material working fain)
page: https://"address"/cgi-bin/luci/admin/services
error:
```
XML Parsing Error: not well-formed Location: https://"address"/cgi-bin/luci/admin/services Line Number 1033, Column 84:
				Enable memory intense overall sort / duplicate removal on low memory devices (< 64 MB RAM)
---------------------------------------------------------------------------------------------------------------^
```

**Comment by hnyman** [comment]
@dibdot 

Openwrt theme has the flags for strict XML/HTML formatting. I guess that the "<" in unquoted format is against that.

**Comment by build000** [comment]
@dibdot 
confirm:
this PR https://github.com/openwrt/luci/pull/1128 fixing problem.
