### ISSUE TITLE
Firewall-General: Use more clear generic Router descriptions instead of iptables descriptions

### ISSUE THREAD

**Issue by LipkeGu** [openwrt/luci#1129]
When creating Zones, we have the ability to create Zones and specify MSS-Fix and Masquerade, we should use more clear generic Router descriptions instead of iptables descriptions. Something like:

Masquerade -> NAT (Tooltip: "Enable Network Address Translation" for this Zone")
MSS-Fix -> MTU Discovery ("Adjust the Maximum Sequence Size for this Zone")

Newcomers, so i "spotted" them asked me where they can enable NAT for the Interface :/ and i sayed
check the box at Masquerade for Zone wlan.

**Comment by jow-** [comment]
MSS-Fix is the opposite of MTU Discovery, it is enforcing the interface MTU on packets instead of relying on possible broken pMTU detection.

**Comment by feckert** [comment]
related pull request was closed because of inactivity of the pull request creator.
