### ISSUE TITLE
luci-app-hd-idle: the menu item does not match the other menus

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#1138]
I will make this change, but wanted to ask for feedback first. Currently the menu item lives under "Services" and is all lower case: "hd-idle". That makes the drop-down menu look not particularly pretty (all other menu items have each word upper-cased and dashes are not being used anywhere else as I can see):

```
Services
 Adblock
 Dynamic DNS
 hd-idle    -->  rename to HDD Idle
 Network Shares
```
I want to rename that single menu to "HDD Idle". I will also change all translation files like below

```
msgid "hd-idle"
msgstr "hd-idle" or ""
```
to
```
msgid "HDD Idle"
msgstr "HDD Idle" or ""
```
Unless of course, that menu item had already been translated into other languages: those will remain unchanged.

Are there other things I missed that I need to consider? Guidelines?

**Comment by hnyman** [comment]
Sounds good to me.

* in controller you need to change the translatable menu item `_("hd-idle")`
* in CBI you could add the translate function like in https://github.com/openwrt/luci/blob/master/applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua#L13 
* in translations you should be able to use sed to large extent (all instances of ` "hi-idle" ` (including quotes) to ` "HDD Idle" `. Quotes needed for preventing changing the ust be careful that you donät change

And check & polish.
