### ISSUE TITLE
How does the information from CGI translate other language?

### ISSUE THREAD

**Issue by daxiongz** [openwrt/luci#1152]
In the html view, I use format as "<%: translate information%>" to come true traanslation.Below is code about it.
![image](https://cloud.githubusercontent.com/assets/19296863/25737737/f10a40f8-31ab-11e7-843e-39a8e95273b6.png)
But, how does the information from CGI translate other language?Previous function is useless.
I need to translate English into Chinese.
![image](https://cloud.githubusercontent.com/assets/19296863/25737862/95acd2ec-31ac-11e7-8eee-99b6220cad4f.png)
Thanks!

**Comment by musashino205** [comment]
See [documentation/Templates.md](https://github.com/openwrt/luci/blob/master/documentation/Templates.md).

You can use `translate("Text to translate")`. If variables are included in string, use `translatef("Text to translate with variables %s", var)` instead of `translate("Text to translate") `.

**Comment by daxiongz** [comment]
How does the outisde javascript file of luci view page translate other lanuage?Luci self format can't realize.

**Comment by musashino205** [comment]
Hmm... I do not know about how to realize with javascript, sorry...

**Comment by jow-** [comment]
It seems you attempt to translate code written in C++? The standard solution for that is https://www.gnu.org/software/gettext/, it is also what LuCI's `translate()` was modelled after.
