### ISSUE TITLE
Luci fails on LEDE-lighttpd

### ISSUE THREAD

**Issue by bluewavenet** [openwrt/luci#1156]
Configuring on LEDE 17.01.1 and  Lighttpd I get the following error on starting luci:

/usr/lib/lua/luci/dispatcher.lua:536: attempt to index local 'f' (a nil value)
stack traceback:
	/usr/lib/lua/luci/dispatcher.lua:536: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:544: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:220: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

Is this a configuration issue?

**Comment by feckert** [comment]
@bluewavenet is this still an issue if not then please reoben the issue or upgrade to new stable. Because lede 17.01 is EOL
