### ISSUE TITLE
mwan3 no longer detects wan connections

### ISSUE THREAD

**Issue by ezplanet** [openwrt/luci#1166]
Something happened between r4041 and r4116.
mwan3 fails to detect wan connections

It appears this might be due to the relocation of /usr/bin/ip to /sbin/ip
Perhaps "/usr/bin/ip" full path is hardcoded inside mwan3 scripts and if that is the case it needs to be updated (possibly using the PATH variable instead)

**Comment by feckert** [comment]
i think we could close this issue?

**Comment by feckert** [comment]
@hnyman ping
