### ISSUE TITLE
main index page Active Connections CPU load is very heavy

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/luci#1170]
http://xxxx/cgi-bin/luci/;stok=xxxx/admin/status/

> Active Connections 

```
wc -l /proc/net/nf_conntrack # CPU load is very heavy
cat /proc/sys/net/netfilter/nf_conntrack_count #Please use this cmd. 
```

> Source code

```
modules/luci-base/luasrc/sys.lua|321 col 46| local ok, nfct = pcall(io.lines, "/proc/net/nf_conntrack")
modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm|41 col 41| fs.readfile("/proc/sys/net/netfilter/nf_conntrack_count")) or 0
modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm|44 col 30| luci.sys.exec("sysctl net.nf_conntrack_max") or
modules/luci-mod-admin-full/src/luci-bwc.c|428 col 36| const char *ipc = stat("/proc/net/nf_conntrack", &s)
modules/luci-mod-admin-full/src/luci-bwc.c|429 col 43| ? "/proc/net/ip_conntrack" : "/proc/net/nf_conntrack"; 
```

**Comment by hnyman** [comment]
Do you have an example where that code `wc -l /proc/net/nf_conntrack `is currently used in the LuCI master?

That line was recently replaced in master and 17.01 with `/proc/sys/net/netfilter/nf_conntrack_count` by https://github.com/openwrt/luci/commit/7ae244a26ef516511a5e476dd14ec033501a1d8d , so I am not sure where you run into that code in the current LuCI. (naturally it can still be found in some ancient branches)

**Comment by peterwillcn** [comment]
Great.
 15.05.1  LuCI (git-16.018.33482-3201903) have this issue
