### ISSUE TITLE
uhttpd allows using WAN IPv6 address from LAN despite RFC1918 protection setting

### ISSUE THREAD

**Issue by neheb** [openwrt/luci#1176]
If you type http://WANIP (IPv4) from within the LAN, LuCI complains about RFC1918.

If you type http://WANIP (IPv6) from within the LAN, LuCI allows the connection.

edit: actually this has to do with uhttpd.

**Comment by hnyman** [comment]
The reason is likely a simplistic rfc1918 evaluation in uhttpd source code:

https://git.lede-project.org/?p=project/uhttpd.git;a=blob;f=utils.c;hb=HEAD#l238

The rfc1918 validation function only evaluates three private IPv4 address areas:
10.x.x.x
172.(16-31).x.x
192.168.x.x

**Comment by jow-** [comment]
That kind of filter is not applicable to IPv6.
