### ISSUE TITLE
luci-app-ushare multiple content directories aren't possible

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#118]
**Reported by reporter on 3 Apr 2010 18:15 UTC**
it's because ushare -c hanles only one directory. If more directories are needed then additional -c should be added i.e ushare -c /dir1/ -c /dir2 -c /dir3 and so on.

The ushare luci page should be formatted the same way as luci samba page i.g there shall be a button to add a content dir.

This is actually an enhancement because there is a workaround for this problem so I'm marking this one as minor

**Comment by hnyman** [comment]
luci-app-ushare is @BROKEN since https://github.com/openwrt/luci/commit/99d4d5e4545ac1b26d0d175c9a0fdf95a45a5af7.
