### ISSUE TITLE
access violation luci dispatcher

### ISSUE THREAD

**Issue by jkimmel** [openwrt/luci#1192]
lime/lede 17.01.2 on wr841 v8
message:
/usr/lib/lua/luci/dispatcher.lua:327: Access Violation
The page at 'admin/system/admin/' has no parent node so the access to this location has been denied.
This is a software bug, please report this message at https://github.com/openwrt/luci/issues
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:327: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

**Comment by jow-** [comment]
Please attach the output if `opkg list_installed`, `cat /etc/board.json` and `fibd /overlay`

**Comment by jkimmel** [comment]
root@LiMe-16d948:~# opkg list_installed
alfred - 2017.1-1
base-files - 173-r3435-65eec8bd5f
batctl - 2017.1-0
bmx6 - r2017032301-5
bmx6-auto-gw-mode - 2016-11-07-1478542738
bmx6-json - r2017032301-5
bmx6-sms - r2017032301-5
bmx6-table - r2017032301-5
bmx6-uci-config - r2017032301-5
busybox - 1.25.1-4
bwm-ng - 0.6.1-1
dnsmasq-dhcpv6 - 2.77-1
dnsmasq-distributed-hosts - 2016-09-08-1473363333
dnsmasq-lease-share - 2016-09-08-1473363333
dropbear - 2017.75-1
ebtables - 2015-10-28-4c3e5cd3-1
ethtool - 4.8-1
firewall - 2017-05-27-a4d98aea-1
fstools - 2016-12-04-84b530a7-2
fwtool - 1
hostapd-common - 2016-12-19-ad02e79d-3
ip-tiny - 4.4.0-9
ip6tables - 1.4.21-2
iptables - 1.4.21-2
iputils-ping - 20101006-1
iputils-ping6 - 20101006-1
iw - 4.9-1
iwinfo - 2016-09-21-fd9e17be-1
jshn - 2017-02-24-96305a3c-1
jsonfilter - 2016-07-02-dea067ad-1
kernel - 4.4.71-1-e19b9950ed08c60448d97dc11fbd6537
kmod-batman-adv - 4.4.71+2016.5-4
kmod-br-netfilter - 4.4.71-1
kmod-bridge - 4.4.71-1
kmod-cfg80211 - 4.4.71+2017-01-31-2
kmod-crypto-crc32c - 4.4.71-1
kmod-crypto-hash - 4.4.71-1
kmod-dummy - 4.4.71-1
kmod-ebtables - 4.4.71-1
kmod-eeprom-93cx6 - 4.4.71-1
kmod-gpio-button-hotplug - 4.4.71-2
kmod-ip6-tunnel - 4.4.71-1
kmod-ip6tables - 4.4.71-1
kmod-ipt-conntrack - 4.4.71-1
kmod-ipt-core - 4.4.71-1
kmod-ipt-nat - 4.4.71-1
kmod-iptunnel6 - 4.4.71-1
kmod-leds-gpio - 4.4.71-1
kmod-lib-crc-ccitt - 4.4.71-1
kmod-lib-crc-itu-t - 4.4.71-1
kmod-lib-crc16 - 4.4.71-1
kmod-lib-crc32c - 4.4.71-1
kmod-llc - 4.4.71-1
kmod-mac80211 - 4.4.71+2017-01-31-2
kmod-macvlan - 4.4.71-1
kmod-mt76 - 4.4.71+2017-01-31-3c8caafc-2
kmod-mt76-core - 4.4.71+2017-01-31-3c8caafc-2
kmod-mt7603 - 4.4.71+2017-01-31-3c8caafc-2
kmod-mt76x2 - 4.4.71+2017-01-31-3c8caafc-2
kmod-nf-conntrack - 4.4.71-1
kmod-nf-conntrack6 - 4.4.71-1
kmod-nf-ipt - 4.4.71-1
kmod-nf-ipt6 - 4.4.71-1
kmod-nf-nat - 4.4.71-1
kmod-ppp - 4.4.71-1
kmod-pppoe - 4.4.71-1
kmod-pppox - 4.4.71-1
kmod-rt2800-lib - 4.4.71+2017-01-31-2
kmod-rt2800-mmio - 4.4.71+2017-01-31-2
kmod-rt2800-pci - 4.4.71+2017-01-31-2
kmod-rt2800-soc - 4.4.71+2017-01-31-2
kmod-rt2x00-lib - 4.4.71+2017-01-31-2
kmod-rt2x00-mmio - 4.4.71+2017-01-31-2
kmod-rt2x00-pci - 4.4.71+2017-01-31-2
kmod-slhc - 4.4.71-1
kmod-stp - 4.4.71-1
kmod-tun - 4.4.71-1
lede-keyring - 2017-01-20-a50b7529-1
libblobmsg-json - 2017-02-24-96305a3c-1
libc - 1.1.16-1
libgcc - 5.4.0-1
libip4tc - 1.4.21-2
libip6tc - 1.4.21-2
libiwinfo - 2016-09-21-fd9e17be-1
libiwinfo-lua - 2016-09-21-fd9e17be-1
libjson-c - 0.12.1-1
libjson-script - 2017-02-24-96305a3c-1
liblua - 5.1.5-1
libncurses - 6.0-1
libnl-tiny - 0.1-5
libpcap - 1.8.1-1
libpthread - 1.1.16-1
libremap-agent - 0.1.9
librt - 1.1.16-1
libubox - 2017-02-24-96305a3c-1
libubus - 2017-02-18-34c6e818-1
libubus-lua - 2017-02-18-34c6e818-1
libuci - 2016-07-04-e1bf4356-1
libuci-lua - 2016-07-04-e1bf4356-1
libuclient - 2016-12-09-52d955fd-1
libxtables - 1.4.21-2
lime-basic - 2017-05-28-1496002984
lime-debug - 2017-05-16-1494930361
lime-docs - 2017-06-02-1496355330
lime-docs-minimal - 2017-06-02-1496355330
lime-full - 2017-05-28-1496002984
lime-hwd-ground-routing - 2017-03-27-1490653265
lime-hwd-openwrt-wan - 2017-05-26-1495791288
lime-map-agent - 2016-09-08-1473363333
lime-proto-anygw - 2017-03-27-1490660712
lime-proto-batadv - 2017-03-20-1490035038
lime-proto-bmx6 - 2017-04-26-1493209061
lime-proto-wan - 2017-05-11-1494511176
lime-system - 2017-05-26-1495794013
lime-webui - 2017-06-06-1496752366
logd - 2017-03-10-16f7e161-1
lua - 5.1.5-1
luci-app-batman-adv - 2017-04-06-1491520653
luci-app-bmx6 - 5
luci-app-lime-location - 2017-03-18-1489789785
luci-base - git-17.161.67166-8eadde5-1
luci-i18n-base-en - git-17.161.67166-8eadde5-1
luci-i18n-base-es - git-17.161.67166-8eadde5-1
luci-lib-dracula - 5
luci-lib-httpclient - git-17.161.67166-8eadde5-1
luci-lib-ip - git-17.161.67166-8eadde5-1
luci-lib-jquery-1-4 - 5
luci-lib-jquery-flot-0-8 - 0.8.1-1
luci-lib-json - git-17.161.67166-8eadde5-1
luci-lib-jsonc - git-17.161.67166-8eadde5-1
luci-lib-libremap - 0.1.9
luci-lib-libremap-bmx6 - 0.1.9
luci-lib-libremap-location - 0.1.9
luci-lib-libremap-system - 0.1.9
luci-lib-libremap-wireless - 0.1.9
luci-lib-nixio - git-17.161.67166-8eadde5-1
luci-mod-admin-full - git-17.161.67166-8eadde5-1
luci-mod-status - 2017-03-25-1490473366
luci-theme-bootstrap - git-17.161.67166-8eadde5-1
mtd - 21
mtr - 0.85+newdns-dd2b75080bc5406ba0b438953b36b72204ba114b-2
netifd - 2017-01-25-650758b1-1
netperf - 2.7.0-1
odhcp6c - 2017-01-30-c13b6a05-1
odhcpd - 2017-04-28-9268ca65-1
opkg - 2017-03-23-1d0263bb-1
ppp - 2.4.7-11
ppp-mod-pppoe - 2.4.7-11
procd - 2017-02-15-5f912410-1
pv - 1.5.3-1
rpcd - 2016-12-03-0577cfc1-1
rt2800-pci-firmware - 2016-09-21-42ad5367-1
safe-reboot - 2017-03-27-1490665244
sprunge - 2014-07-29-1406652934
swconfig - 11
tcpdump-mini - 4.9.0-1
terminfo - 6.0-1
ubox - 2017-03-10-16f7e161-1
ubus - 2017-02-18-34c6e818-1
ubusd - 2017-02-18-34c6e818-1
uci - 2016-07-04-e1bf4356-1
uclient-fetch - 2016-12-09-52d955fd-1
uhttpd - 2016-10-25-1628fa4b-1
usign - 2015-07-04-ef641914-1
watchping - 2017-02-22-1487729116
wpad-mini - 2016-12-19-ad02e79d-3
root@LiMe-16d948:~#


root@LiMe-16d948:~# cat /etc/board.json
{
        "model": {
                "id": "zbt-ape522ii",
                "name": "ZBT-APE522II"
        },
        "led": {
                "wlan2g4": {
                        "name": "wlan1-link",
                        "type": "netdev",
                        "sysfs": "zbt-ape522ii:green:wlan2g4",
                        "device": "wlan1",
                        "mode": "link tx rx"
                },
                "sys1": {
                        "name": "wlan1",
                        "type": "netdev",
                        "sysfs": "zbt-ape522ii:green:sys1",
                        "device": "wlan1",
                        "mode": "tx rx"
                },
                "sys2": {
                        "name": "wlan0",
                        "type": "netdev",
                        "sysfs": "zbt-ape522ii:green:sys2",
                        "device": "wlan0",
                        "mode": "tx rx"
                }
        },
        "switch": {
                "switch0": {
                        "enable": true,
                        "reset": true,
                        "ports": [
                                {
                                        "num": 0,
                                        "role": "lan"
                                },
                                {
                                        "num": 1,
                                        "role": "lan"
                                },
                                {
                                        "num": 2,
                                        "role": "lan"
                                },
                                {
                                        "num": 3,
                                        "role": "lan"
                                },
                                {
                                        "num": 4,
                                        "role": "wan"
                                },
                                {
                                        "num": 6,
                                        "device": "eth0",
                                        "need_tag": false,
                                        "want_untag": false
                                }
                        ],
                        "roles": [
                                {
                                        "role": "lan",
                                        "ports": "0 1 2 3 6t",
                                        "device": "eth0.1"
                                },
                                {
                                        "role": "wan",
                                        "ports": "4 6t",
                                        "device": "eth0.2"
                                }
                        ]
                }
        },
        "network": {
                "lan": {
                        "ifname": "eth0.1",
                        "protocol": "static",
                        "macaddr": "78:a3:51:16:d9:48"
                },
                "wan": {
                        "ifname": "eth0.2",
                        "protocol": "dhcp",
                        "macaddr": "78:a3:51:16:d9:49"
                }
        }
}


root@LiMe-16d948:~# find /overlay/
/overlay/
/overlay/.fs_state
/overlay/work
/overlay/work/work
/overlay/upper
/overlay/upper/etc
/overlay/upper/etc/dnsmasq.d
/overlay/upper/etc/dnsmasq.d/lime-proto-anygw-20-ipv6.conf
/overlay/upper/etc/rc.d
/overlay/upper/etc/rc.d/S35odhcpd
/overlay/upper/etc/rc.d/S50cron
/overlay/upper/etc/rc.d/K85odhcpd
/overlay/upper/etc/rc.d/S19dnsmasq
/overlay/upper/etc/lime-config-firstboot
/overlay/upper/etc/lime-config-firstboot/bmx6
/overlay/upper/etc/lime-config-firstboot/dhcp
/overlay/upper/etc/lime-config-firstboot/lime
/overlay/upper/etc/lime-config-firstboot/luci
/overlay/upper/etc/lime-config-firstboot/rpcd
/overlay/upper/etc/lime-config-firstboot/lime-defaults
/overlay/upper/etc/lime-config-firstboot/firewall
/overlay/upper/etc/lime-config-firstboot/dropbear
/overlay/upper/etc/lime-config-firstboot/lime-example
/overlay/upper/etc/lime-config-firstboot/batman-adv
/overlay/upper/etc/lime-config-firstboot/luci-bmx6
/overlay/upper/etc/lime-config-firstboot/alfred
/overlay/upper/etc/lime-config-firstboot/network
/overlay/upper/etc/lime-config-firstboot/ucitrack
/overlay/upper/etc/lime-config-firstboot/system
/overlay/upper/etc/lime-config-firstboot/uhttpd
/overlay/upper/etc/lime-config-firstboot/wireless
/overlay/upper/etc/lime-config-firstboot/libremap
/overlay/upper/etc/uci-defaults
/overlay/upper/etc/uci-defaults/11_migrate-sysctl
/overlay/upper/etc/uci-defaults/odhcpd.defaults
/overlay/upper/etc/uci-defaults/10_migrate-shadow
/overlay/upper/etc/uci-defaults/09_fix-seama-header
/overlay/upper/etc/uci-defaults/80_libremap-agent
/overlay/upper/etc/uci-defaults/20_migrate-feeds
/overlay/upper/etc/uci-defaults/90_dnsmasq-lease-share
/overlay/upper/etc/uci-defaults/13_fix_group_user
/overlay/upper/etc/uci-defaults/80-lime_set_11s.sh
/overlay/upper/etc/uci-defaults/90_watchping
/overlay/upper/etc/uci-defaults/12_network-generate-ula
/overlay/upper/etc/uci-defaults/inject-luci-notify-lime-env.sh
/overlay/upper/etc/uci-defaults/90_lime-banner
/overlay/upper/etc/uci-defaults/91_lime-config
/overlay/upper/etc/uci-defaults/luci-i18n-base-en
/overlay/upper/etc/uci-defaults/luci-i18n-base-es
/overlay/upper/etc/uci-defaults/85-add-bmx6-addresses-to-hosts
/overlay/upper/etc/uci-defaults/90_dnsmasq-distributed-hosts
/overlay/upper/etc/uci-defaults/30_luci-theme-bootstrap
/overlay/upper/etc/uci-defaults/90_lime-customize-profile
/overlay/upper/etc/uci-defaults/50_luci-mod-admin-full
/overlay/upper/etc/dropbear
/overlay/upper/etc/dropbear/dropbear_rsa_host_key
/overlay/upper/etc/sysctl.conf
/overlay/upper/etc/crontabs
/overlay/upper/etc/crontabs/root
/overlay/upper/etc/board.json
/overlay/upper/etc/urandom.seed
/overlay/upper/etc/bat-hosts
/overlay/upper/etc/banner
/overlay/upper/etc/config
/overlay/upper/etc/config/bmx6
/overlay/upper/etc/config/dhcp
/overlay/upper/etc/config/lime
/overlay/upper/etc/config/luci
/overlay/upper/etc/config/rpcd
/overlay/upper/etc/config/lime-defaults
/overlay/upper/etc/config/firewall
/overlay/upper/etc/config/dropbear
/overlay/upper/etc/config/lime-example
/overlay/upper/etc/config/batman-adv
/overlay/upper/etc/config/luci-bmx6
/overlay/upper/etc/config/alfred
/overlay/upper/etc/config/6relayd
/overlay/upper/etc/config/network
/overlay/upper/etc/config/ucitrack
/overlay/upper/etc/config/system
/overlay/upper/etc/config/uhttpd
/overlay/upper/etc/config/wireless
/overlay/upper/etc/config/libremap
/overlay/upper/etc/ethers
/overlay/upper/etc/dnsmasq.conf
/overlay/upper/etc/firewall.lime.d
/overlay/upper/etc/firewall.lime.d/20-anygw-ebtables
/overlay/upper/etc/profile
/overlay/upper/usr
/overlay/upper/usr/lib
/overlay/upper/usr/lib/lua
/overlay/upper/usr/lib/lua/luci
/overlay/upper/usr/lib/lua/luci/view
/overlay/upper/usr/lib/lua/luci/view/footer.htm

**Comment by jkimmel** [comment]
closed by error

**Comment by jow-** [comment]
Can you reproduce the problem without LiMe specific packages?

**Comment by jkimmel** [comment]
Ich forgot to mention:
Message appears when running  lime-config

**Comment by antoineclaval** [comment]
I have the same issue when setting a password on an fresh install. I'm using LiMe-mini, based on Lede 17.01.2, r3435-65eec8bd5f.

opkg is not available there by default. 

I cannot set a password thought the interface, I guess I can do it from the file system or CLI+SSH. but that would be nice to understand what's up.

Thanks

--------- error on http://thisnode.info/cgi-bin/luci/admin/system/admin -------------
/usr/lib/lua/luci/dispatcher.lua:327: Access Violation
The page at 'admin/system/admin/' has no parent node so the access to this location has been denied.
This is a software bug, please report this message at https://github.com/openwrt/luci/issues
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:327: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

-----------------/etc/board.json---------------------

root@LiMe-c1df1f:~# cat /etc/board.json
{
	"model": {
		"id": "tl-wr741nd-v4",
		"name": "TP-Link TL-WR740N\/ND v5"
	},
	"led": {
		"wan": {
			"name": "WAN",
			"type": "netdev",
			"sysfs": "tp-link:green:wan",
			"device": "eth1",
			"mode": "link tx rx"
		},
		"lan1": {
			"name": "LAN1",
			"type": "switch",
			"sysfs": "tp-link:green:lan1",
			"trigger": "switch0",
			"port_mask": "0x04",
			"speed_mask": ""
		},
		"lan2": {
			"name": "LAN2",
			"type": "switch",
			"sysfs": "tp-link:green:lan2",
			"trigger": "switch0",
			"port_mask": "0x08",
			"speed_mask": ""
		},
		"lan3": {
			"name": "LAN3",
			"type": "switch",
			"sysfs": "tp-link:green:lan3",
			"trigger": "switch0",
			"port_mask": "0x10",
			"speed_mask": ""
		},
		"lan4": {
			"name": "LAN4",
			"type": "switch",
			"sysfs": "tp-link:green:lan4",
			"trigger": "switch0",
			"port_mask": "0x02",
			"speed_mask": ""
		},
		"wlan": {
			"name": "WLAN",
			"type": "trigger",
			"sysfs": "tp-link:green:wlan",
			"trigger": "phy0tpt"
		}
	},
	"network": {
		"lan": {
			"ifname": "eth0",
			"protocol": "static"
		},
		"wan": {
			"ifname": "eth1",
			"protocol": "dhcp"
		}
	},
	"switch": {
		"switch0": {
			"enable": true,
			"reset": true,
			"ports": [
				{
					"num": 0,
					"device": "eth0",
					"need_tag": false,
					"want_untag": false
				},
				{
					"num": 1,
					"role": "lan",
					"index": 4
				},
				{
					"num": 2,
					"role": "lan",
					"index": 3
				},
				{
					"num": 3,
					"role": "lan",
					"index": 2
				},
				{
					"num": 4,
					"role": "lan",
					"index": 1
				}
			],
			"roles": [
				{
					"role": "lan",
					"ports": "1 2 3 4 0",
					"device": "eth0"
				}
			]
		}
	}
}
------- /overlay -------------------------------
root@LiMe-c1df1f:~# find /overlay/
/overlay/
/overlay/.fs_state
/overlay/work
/overlay/work/work
/overlay/upper
/overlay/upper/etc
/overlay/upper/etc/dnsmasq.d
/overlay/upper/etc/dnsmasq.d/lime-proto-anygw-20-ipv6.conf
/overlay/upper/etc/rc.d
/overlay/upper/etc/rc.d/S50cron
/overlay/upper/etc/rc.d/S19dnsmasq
/overlay/upper/etc/lime-config-firstboot
/overlay/upper/etc/lime-config-firstboot/bmx6
/overlay/upper/etc/lime-config-firstboot/dhcp
/overlay/upper/etc/lime-config-firstboot/lime
/overlay/upper/etc/lime-config-firstboot/luci
/overlay/upper/etc/lime-config-firstboot/rpcd
/overlay/upper/etc/lime-config-firstboot/lime-defaults
/overlay/upper/etc/lime-config-firstboot/dropbear
/overlay/upper/etc/lime-config-firstboot/batman-adv
/overlay/upper/etc/lime-config-firstboot/luci-bmx6
/overlay/upper/etc/lime-config-firstboot/alfred
/overlay/upper/etc/lime-config-firstboot/ubootenv
/overlay/upper/etc/lime-config-firstboot/network
/overlay/upper/etc/lime-config-firstboot/ucitrack
/overlay/upper/etc/lime-config-firstboot/system
/overlay/upper/etc/lime-config-firstboot/uhttpd
/overlay/upper/etc/lime-config-firstboot/wireless
/overlay/upper/etc/uci-defaults
/overlay/upper/etc/uci-defaults/11_migrate-sysctl
/overlay/upper/etc/uci-defaults/09_fix-checksum
/overlay/upper/etc/uci-defaults/04_led_migration
/overlay/upper/etc/uci-defaults/10_migrate-shadow
/overlay/upper/etc/uci-defaults/09_fix-seama-header
/overlay/upper/etc/uci-defaults/03_network-switchX-migration
/overlay/upper/etc/uci-defaults/03_network-vlan-migration
/overlay/upper/etc/uci-defaults/90_dnsmasq-lease-share
/overlay/upper/etc/uci-defaults/13_fix_group_user
/overlay/upper/etc/uci-defaults/90_watchping
/overlay/upper/etc/uci-defaults/12_network-generate-ula
/overlay/upper/etc/uci-defaults/inject-luci-notify-lime-env.sh
/overlay/upper/etc/uci-defaults/90_lime-banner
/overlay/upper/etc/uci-defaults/30_uboot-envtools
/overlay/upper/etc/uci-defaults/91_lime-config
/overlay/upper/etc/uci-defaults/luci-i18n-base-en
/overlay/upper/etc/uci-defaults/luci-i18n-base-es
/overlay/upper/etc/uci-defaults/85-add-bmx6-addresses-to-hosts
/overlay/upper/etc/uci-defaults/90_dnsmasq-distributed-hosts
/overlay/upper/etc/uci-defaults/30_luci-theme-bootstrap
/overlay/upper/etc/uci-defaults/90_lime-customize-profile
/overlay/upper/etc/dropbear
/overlay/upper/etc/dropbear/dropbear_rsa_host_key
/overlay/upper/etc/sysctl.conf
/overlay/upper/etc/crontabs
/overlay/upper/etc/crontabs/root
/overlay/upper/etc/board.json
/overlay/upper/etc/urandom.seed
/overlay/upper/etc/bat-hosts
/overlay/upper/etc/banner
/overlay/upper/etc/config
/overlay/upper/etc/config/bmx6
/overlay/upper/etc/config/dhcp
/overlay/upper/etc/config/lime
/overlay/upper/etc/config/luci
/overlay/upper/etc/config/rpcd
/overlay/upper/etc/config/lime-defaults
/overlay/upper/etc/config/dropbear
/overlay/upper/etc/config/batman-adv
/overlay/upper/etc/config/luci-bmx6
/overlay/upper/etc/config/alfred
/overlay/upper/etc/config/ubootenv
/overlay/upper/etc/config/6relayd
/overlay/upper/etc/config/network
/overlay/upper/etc/config/ucitrack
/overlay/upper/etc/config/system
/overlay/upper/etc/config/uhttpd
/overlay/upper/etc/config/wireless
/overlay/upper/etc/config/libremap
/overlay/upper/etc/ethers
/overlay/upper/etc/dnsmasq.conf
/overlay/upper/etc/firewall.lime.d
/overlay/upper/etc/firewall.lime.d/20-bmxtun-mtu_fix
/overlay/upper/etc/firewall.lime.d/20-wan-out-masquerade
/overlay/upper/etc/firewall.lime.d/20-bmx-not-over-bat0-ebtables
/overlay/upper/etc/firewall.lime.d/20-anygw-ebtables
/overlay/upper/etc/profile
/overlay/upper/usr
/overlay/upper/usr/lib
/overlay/upper/usr/lib/lua
/overlay/upper/usr/lib/lua/luci
/overlay/upper/usr/lib/lua/luci/view
/overlay/upper/usr/lib/lua/luci/view/footer.htm
----------------------------

**Comment by rontab68** [comment]
Same problem with a Dlink 615D router
cat /etc/board.json

{

        "model": {

                "id": "dir-615-d",

                "name": "D-Link DIR-615 D"

        },

        "led": {

                "status": {

                        "name": "Status LED (amber)",

                        "sysfs": "dir-615-d:amber:status",

                        "default": "0"

                },

                "wifi_led": {

                        "name": "wifi",

                        "type": "netdev",

                        "sysfs": "rt2800pci-phy0::radio",

                        "device": "wlan0",

                        "mode": "link tx rx"

                }

        },

        "switch": {

                "rt305x": {

                        "enable": true,

                        "reset": true,

                        "ports": [

                                {

                                        "num": 0,

                                        "role": "lan"

                                },

                                {

                                        "num": 1,

                                        "role": "lan"

                                },

                                {

                                        "num": 2,

                                        "role": "lan"

                                },

                                {

                                        "num": 3,

                                        "role": "lan"

                                },

                                {

                                        "num": 5,

                                        "role": "lan"

                                },

                                {

                                        "num": 4,

                                        "role": "wan"

                                },

                                {

                                        "num": 6,

                                        "device": "eth0",

                                        "need_tag": true,

                                        "want_untag": false

                                }

                        ],

                        "roles": [

                                {

                                        "role": "lan",

                                        "ports": "0 1 2 3 5 6t",

                                        "device": "eth0.1"

                                },

                                {

                                        "role": "wan",

                                        "ports": "4 6t",

                                        "device": "eth0.2"

                                }

                        ]

                }

        },

        "network": {

                "lan": {

                        "ifname": "eth0.1",

                        "protocol": "static",

                        "macaddr": "fe:05:a8:88:92:02"

                },

                "wan": {

                        "ifname": "eth0.2",

                        "protocol": "dhcp",

                        "macaddr": "fe:05:a8:88:92:03"

                }

        }

}


------------------------------/overlay---------------------------------------


/overlay/

/overlay/.fs_state

/overlay/work

/overlay/work/work

/overlay/upper

/overlay/upper/etc

/overlay/upper/etc/ppp

/overlay/upper/etc/ppp/filter

/overlay/upper/etc/ppp/options

/overlay/upper/etc/ppp/chap-secrets

/overlay/upper/etc/dnsmasq.d

/overlay/upper/etc/dnsmasq.d/lime-proto-anygw-20-ipv6.conf

/overlay/upper/etc/opkg

/overlay/upper/etc/opkg/keys

/overlay/upper/etc/opkg/keys/53bad1233d4c98c5

/overlay/upper/etc/opkg/keys/a71b3c8285abd28b

/overlay/upper/etc/opkg/keys/de98a2dd1d0f8a07

/overlay/upper/etc/opkg/customfeeds.conf

/overlay/upper/etc/opkg/limefeeds.conf

/overlay/upper/etc/rc.d

/overlay/upper/etc/rc.d/S50cron

/overlay/upper/etc/rc.d/S19dnsmasq

/overlay/upper/etc/firewall.user

/overlay/upper/etc/group

/overlay/upper/etc/hosts

/overlay/upper/etc/lime-config-firstboot

/overlay/upper/etc/lime-config-firstboot/bmx6

/overlay/upper/etc/lime-config-firstboot/dhcp

/overlay/upper/etc/lime-config-firstboot/lime

/overlay/upper/etc/lime-config-firstboot/luci

/overlay/upper/etc/lime-config-firstboot/rpcd

/overlay/upper/etc/lime-config-firstboot/lime-defaults

/overlay/upper/etc/lime-config-firstboot/firewall

/overlay/upper/etc/lime-config-firstboot/dropbear

/overlay/upper/etc/lime-config-firstboot/batman-adv

/overlay/upper/etc/lime-config-firstboot/luci-bmx6

/overlay/upper/etc/lime-config-firstboot/alfred

/overlay/upper/etc/lime-config-firstboot/network

/overlay/upper/etc/lime-config-firstboot/ucitrack

/overlay/upper/etc/lime-config-firstboot/system

/overlay/upper/etc/lime-config-firstboot/uhttpd

/overlay/upper/etc/lime-config-firstboot/wireless

/overlay/upper/etc/openwrt_release

/overlay/upper/etc/uci-defaults

/overlay/upper/etc/uci-defaults/11_migrate-sysctl

/overlay/upper/etc/uci-defaults/10_migrate-shadow

/overlay/upper/etc/uci-defaults/09_fix-seama-header

/overlay/upper/etc/uci-defaults/90_dnsmasq-lease-share

/overlay/upper/etc/uci-defaults/13_fix_group_user

/overlay/upper/etc/uci-defaults/90_watchping

/overlay/upper/etc/uci-defaults/12_network-generate-ula

/overlay/upper/etc/uci-defaults/inject-luci-notify-lime-env.sh

/overlay/upper/etc/uci-defaults/90_lime-banner

/overlay/upper/etc/uci-defaults/89_lime-release

/overlay/upper/etc/uci-defaults/91_lime-config

/overlay/upper/etc/uci-defaults/luci-i18n-base-en

/overlay/upper/etc/uci-defaults/luci-i18n-base-es

/overlay/upper/etc/uci-defaults/85-add-bmx6-addresses-to-hosts

/overlay/upper/etc/uci-defaults/90_dnsmasq-distributed-hosts

/overlay/upper/etc/uci-defaults/30_luci-theme-bootstrap

/overlay/upper/etc/uci-defaults/90_lime-customize-profile

/overlay/upper/etc/uci-defaults/92_add-lime-repos

/overlay/upper/etc/dropbear

/overlay/upper/etc/dropbear/dropbear_dss_host_key

/overlay/upper/etc/dropbear/dropbear_rsa_host_key

/overlay/upper/etc/sysctl.conf

/overlay/upper/etc/services

/overlay/upper/etc/inittab

/overlay/upper/etc/crontabs

/overlay/upper/etc/crontabs/root

/overlay/upper/etc/sysupgrade.conf

/overlay/upper/etc/board.json

/overlay/upper/etc/urandom.seed

/overlay/upper/etc/opkg.conf

/overlay/upper/etc/bat-hosts

/overlay/upper/etc/banner

/overlay/upper/etc/config

/overlay/upper/etc/config/bmx6

/overlay/upper/etc/config/dhcp

/overlay/upper/etc/config/lime

/overlay/upper/etc/config/luci

/overlay/upper/etc/config/rpcd

/overlay/upper/etc/config/lime-defaults

/overlay/upper/etc/config/firewall

/overlay/upper/etc/config/dropbear

/overlay/upper/etc/config/batman-adv

/overlay/upper/etc/config/luci-bmx6

/overlay/upper/etc/config/alfred

/overlay/upper/etc/config/6relayd

/overlay/upper/etc/config/network

/overlay/upper/etc/config/ucitrack

/overlay/upper/etc/config/system

/overlay/upper/etc/config/uhttpd

/overlay/upper/etc/config/wireless

/overlay/upper/etc/ethers

/overlay/upper/etc/passwd

/overlay/upper/etc/shadow

/overlay/upper/etc/shells

/overlay/upper/etc/dnsmasq.conf

/overlay/upper/etc/protocols

/overlay/upper/etc/rc.local

/overlay/upper/etc/firewall.lime.d

/overlay/upper/etc/firewall.lime.d/20-allow-all-fe80-traffic-over-wan

/overlay/upper/etc/firewall.lime.d/20-bmx-not-over-bat0-ebtables

/overlay/upper/etc/firewall.lime.d/20-anygw-ebtables

/overlay/upper/etc/profile

/overlay/upper/usr

/overlay/upper/usr/lib

/overlay/upper/usr/lib/lua

/overlay/upper/usr/lib/lua/luci

/overlay/upper/usr/lib/lua/luci/view

/overlay/upper/usr/lib/lua/luci/view/footer.htm

/overlay/upper/www

/overlay/upper/www/cgi-bin

/overlay/upper/www/cgi-bin/luci

**Comment by Powersource** [comment]
Getting the exact same error, running `lede-17.01.2-lime-mini-ar71xx-generic-tl-mr3020-v1-squashfs-factory.bin`

**Comment by cshoredaniel** [comment]
Probably LiME has not been updated to the new split luci-mod-admin-full ... this looks like luci-base is missing the bits from master from the split and reorganisation.  Since LiME is downstream and I was not even aware of it, it wasn't part of that PR.

**Comment by jow-** [comment]
The dispatching logic has been completely rewritten in master.
