### ISSUE TITLE
Dynamic DNS on the status overview page shows "Config error" under Network.

### ISSUE THREAD

**Issue by jebrossard** [openwrt/luci#1193]
LuCI lede-17.01 branch (git-17.152.82987-7f6fc16) / LEDE Reboot 17.01.2 r3435-65eec8bd5f

After ADDING a ddns service in LuCI the ddns updating works just fine, but shows "Config error" under Network column on status overview. This is because these options are missing from the newly added service's config:

    option interface
    option ip_source
    option ip_network

Once those options are manually added to the new ddns service's configuration the "config error" goes away. Please see the attached document.  (See issue 1117.)

[config ddns error.docx](https://github.com/openwrt/luci/files/1068218/config.ddns.error.docx)

**Comment by jow-** [comment]
@chris5560

**Comment by jow-** [comment]
@chris5560 - sorry, you already fixed this issue, it just hasn't been backported to luci-17.01 yet.
