### ISSUE TITLE
I need help configuring my router

### ISSUE THREAD

**Issue by NXLinny** [openwrt/luci#1202]
Hello everyone.

Im a total noob about router configuration, so I would like to receive some help on putting a limit on the download and upload speed of some wi-fi users that are using my internet service. Im new on using OpenWrt so I don´t know how to use the interface too.

Thank you very much! :>

**Comment by thess** [comment]
This is not the correct place to post requests for general help. 
I think you will find more help if you post in the LEDE and/or the OpenWrt forums.

https://forum.lede-project.org/
https://forum.openwrt.org/
