### ISSUE TITLE
Port forwards don't work

### ISSUE THREAD

**Issue by tro69** [openwrt/luci#1217]
If I try to add a new port forward, it isn't added.
I have to add manually the new port forward editing /etc/config/firewall file.
Test:
```
config redirect
    option src 'wan'
    option src_dport '777'
    option dest 'lan'
    option dest_ip '192.168.0.3'
    option name 'testportforward'
    option proto 'tcp'
    option dest_port '777'
```

> Model: BT Home Hub 5A
Firmware Version: LEDE Reboot SNAPSHOT r4426-80d9ec5 / LuCI Master (git-17.174.41033-de2e92a)
Kernel Version	4.4.71

**Comment by jow-** [comment]
Make sure to use the add button next to the input field row.
