### ISSUE TITLE
TPLink Archer C7 (v2) and one wifi issue

### ISSUE THREAD

**Issue by dominbdg** [openwrt/luci#1224]
hi,
I have both network devices in my AC1750,
one - 5GHz working very good and is displayed as Qualcomm Atheros QCA9880 802.11nac (radio0)
second - 2,4 Ghz don't work fine, when I'm trying to connect to my laptop with wifiN, it starts from 114MBps, and after 5 second connection speed is 54MBits,

secondary wifi is displaying as Generic MAC80211 802.11bgn (radio1)

Maybe I need some additional drivers for this wifi 2,4 ?

**Comment by jow-** [comment]
This is not a LuCI web interface problem.
