### ISSUE TITLE
[luci-app-openvpn] Can't stop OpenVPN service. It restarts automatically after delay.

### ISSUE THREAD

**Issue by Scvairy** [openwrt/luci#1241]
Powered by LuCI lede-17.01 branch (git-17.152.82987-7f6fc16) / LEDE Reboot 17.01.2 r3435-65eec8bd5f
luci-app-openvpn | git-17.194.52964-580f012-1
![image](https://user-images.githubusercontent.com/8327460/28443757-90e0ef94-6dd1-11e7-9a60-e415c973a241.png)

**Comment by cugnonr** [comment]
Same problem on linksys WRT 3200 ACM 
LuCI lede-17.01 branch (git-17.152.82987-7f6fc16) / LEDE Reboot 17.01.2 r3435-65eec8bd5f

**Comment by Scvairy** [comment]
I temporary solved the problem by disabling openvpn in init section. I think, it causes automatic restart of the service.

**Comment by hnyman** [comment]
What makes you to think that this is a LuCI GUI problem? (instead of a problem in the package itself)

**Comment by Wedmer** [comment]
All start/stop functionality is made by using service init script. When you stop service it could take some time to finish as it can have some unfinished tasks.

**Comment by Weishaupt** [comment]
I'm running LEDE 17.01.4 and I expericence the same behaviour. Stopping via `/etc/init.d/openvpn stop` will actually disconnect OpenVPN. When I use the luci app and try to disconnect, it will start a new process shortly after tearing down the old one.

**Comment by Wedmer** [comment]
`/etc/init.d/openvpn stop` stops all openvpn instances.
Please check if `/etc/init.d/openvpn stop name_of_the_instance` stops only one instance.

**Comment by Weishaupt** [comment]
There is no such command. `/etc/init.d/openvpn stop name_of_the_instance` gives me 
> Command failed: Not found

The service description also doesn't mention starting / stopping just an instance

> Syntax: /etc/init.d/openvpn [command]
>
> 
> Available commands:
>         start   Start the service
>         stop    Stop the service
>         restart Restart the service
>         reload  Reload configuration files (or restart if that fails)
>         enable  Enable service autostart
>         disable Disable service autostart
>

**Comment by blamaz** [comment]
I'm running Davidc502 fork snapshot r5422 and have the exact same behaviour.

**Comment by Wedmer** [comment]
There're no support for stopping/starting single instance in current openvpn init script. When I have more free time I'll look for workaround.

**Comment by dibdot** [comment]
Not a LuCI issue at all.
