### ISSUE TITLE
How can I install the libsodium in the openwrt

### ISSUE THREAD

**Issue by XinyuAzu** [openwrt/luci#1243]
Recently I've just installed the shadowsocks, and I need to install the libsodium in the openwrt now due to the fact that there is not the "chacha20" for me to use the VPN; however, I do not how to install the libsodium or to make the chacha20 usable directly. Hope you guys can help me. Thanks.

**Comment by kuoruan** [comment]
opkg update && opkg install libsodium

**Comment by hnyman** [comment]
Nothing to do with LuCI GUI. 
closing.
