### ISSUE TITLE
daemon.err uhttpd[2685]: Unsupported authenticator configured

### ISSUE THREAD

**Issue by riodda** [openwrt/luci#1246]
Hi, i'0ve recentrly build a nightly from lede source and im haveing some errored on the log and on the luci interface.
the behaviour is that the config files are modifyed but not reloaded and the error message as per the title in the system log is 

daemon.err uhttpd[2685]: Unsupported authenticator configured

Unsupported authenticator configured
Is showed on the luci frontend as well.

**Comment by jow-** [comment]
This has been fixed long ago
