### ISSUE TITLE
Package removal might fool luci in believing package is still installed

### ISSUE THREAD

**Issue by ffries** [openwrt/luci#1247]
Dear all,

This is probably an old issue, but please review this bug proposal:

When removing a package, configuration is kept in /etc/config. This might fool luci in believing package is still active. Furthermore, when reinstalling a package previously deleted ... uci retains the old configuration file and discards the new file.

To reproduce:
Remove dnsmasq (if you don't need a DNS local resolver). /etc/config/dhcp is still present. As a result, luci believes that dnsmasq is still active and user may try to configure dnsmasq without success. Then reinstall dnsmasq. The old configuration is retained and the new one is discarded. Therefore, if your configuration was wrong somewhere, there is no chance to update it using luci.

A workaround would be to rename an old uci configuration file with extension "bak" upon removal and/or reinstallation. This is how it is done in Debian (correct me if I am wrong).

IMHO, this is quite a simple but severe issue, as I could notice it several times. Other packages impacted are (at least): luci_statistics, luci_addblock, etc ... In those cases, you cannot remove addblock without removing luci_addblock and might believe that this is enough. Still, upon reinstallation, the old configuration file remains. This is clearly a flaw in design.

Kind regards,
French Fries

**Comment by jow-** [comment]
Master reworked feature detection
