### ISSUE TITLE
SAMBA give partial sharing...

### ISSUE THREAD

**Issue by Skyfinder84** [openwrt/luci#1269]
Device: Zidoo-X8
LUCI VERSION Powered by LuCI QA160627-nuplayer_Kylin_2017-05-11_SQA_Dailybuild_NAS Release (git-17.130.47916-3e80cb1) / OpenWrt Chaos Calmer 15.05.1
Zidoo Android ambient is updated
Kodi 17 Kripton installed...

SAMBA IS ACTIVATED ON:
Openwrt options
Device advanced options...
Kodi options...

STRUCTURE:
- WD 4TB linked via USB 3.0 to the Device.
- The device on lan via ethernet...
- Asus Modem / Router... no bullshits about port forwarding, ip... all auto...
- Desktop: Win10 machine all regular, no crack..on in LAN.

The Workgroup is the same for everyone.

THE ISSUE:
When i connect via WIN10 to the HDD...i can see everything.  BUT ONLY ONE DIRECTORY SEEMS TO BE BLOCKED, i can't rename, rewrite, paste... say:
"You need the permission by ZIDOO-X8/nobody"

The directory is the largest, with the biggest number and dimension of files...

Tried hard reset from android and from openwrt...nothing... WHAT THE HELL????

**Comment by Skyfinder84** [comment]
WHY NO ONE TRIES TO HELP???

**Comment by LipkeGu** [comment]
Samba share acl depends on underlaying filesystem acls, so you should ```chmod``` the folder via ssh... and restart samba.

**Comment by feckert** [comment]
That issue is for 15.05 which is EOL. And I think this is not a LuCI related issue.
