### ISSUE TITLE
Hang when saveing changes on Mount Points

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#127]
**Reported by reporter on 3 May 2010 06:24 UTC**
Hello,

First of all some information:

Luci version: 0.9.0
OpenWRT version: 10.03
Hardware model: TPLINK WR1043ND

Bug:
When I change some records on Mount Point screen and then clik Save or Save & Apply Luci hangs. I could kill uhttpd or reboot the router but there is no thing to do from Luci GUI. When I try to see what is going on from console (by "ps" command") I can see that there is one process which point to luci and fstab changes and I think this is the reason of Luci hangs.

BTW: Luc hangs but all information to fstab are saved correct...

I will be very grateful if some one could help.

Best regards,
MivncM

**Comment by hnyman** [comment]
ancient
