### ISSUE TITLE
Use travis ci to check package quality

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#1272]
[openwrt/packages](https://github.com/openwrt/packages/) uses travis to check the pull requests, couldn't that be useful for the luci-apps as well?

All needed would likely be the following:
* https://github.com/openwrt/packages/blob/master/.travis.yml
* https://github.com/openwrt/packages/blob/master/.travis_do.sh

maybe @champtar or @lynxis could comment on this?

**Comment by jow-** [comment]
No comments and no PR, closing this.
