### ISSUE TITLE
Persistent login

### ISSUE THREAD

**Issue by hoesman** [openwrt/luci#1274]
Hello, I am wondering why isnt it possible to have persistent login, say I got to ROUTER/cgi-bin/luci, log in and browse around, and if I then open the same address (bookmark) again I have to login again..

Seems like the stok session variable breaks everything, I also cant make a direct bookmark to say graphs at admin/status/realtime

**Comment by hnyman** [comment]
session tokens are not used in the current LuCI master versions. It was dropped already for Openwrt trunk and LEDE master in favor of session cookies (that enable bookmarking chart pages etc.).

Fixed in master.
