### ISSUE TITLE
httpclient does not always return full http body

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#128]
**Reported by reporter on 19 May 2010 20:15 UTC**
When issuing http[s] requests with the request_raw function in luci/libs/httpclient, the body of the http response is sometimes truncated. I could trace this down to this return statement:

```
return response.code, response, linesrc(true), sock
```

The linesrc(true) causes the UnifiedIO:linesource iterator to flush its internal buffer. If this buffer does not contain the entire http response body, a truncated body will be returned by request_raw.

A patch against trunk has been attached.

Cheers,
Bart.

**Comment by cshoredaniel** [comment]
ancient report, attachment not here; closing
