### ISSUE TITLE
problem can upgrade

### ISSUE THREAD

**Issue by build000** [openwrt/luci#1303]
@jow- or other
```
/usr/lib/lua/luci/dispatcher.lua:578: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	/usr/lib/lua/luci/dispatcher.lua:578: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:247: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
```
dom@machina:~/Pulpit/Projekty/WNDR4700-LEDE-REBOOT$ scripts/getver.sh
r4696-df3295f
LuCI is actual date time and update from old LuCI Master (git-17.225.68218-09e0519) - saved configuration.
EDIT: 2 restart (disable some daemons/program: transmission, netserver, hd-idle, pptpd, openvpn, relayd from init) and...work properly - I don't understand.

**Comment by hnyman** [comment]
You have likely bad or missing config for some LuCI app, e.g. luci statistics.

A faulty app config can prevent LuCI from loading, if the app creates the menu items on the fly depending on the installed/enabled submodules (like luci statistics)
