### ISSUE TITLE
luci-app-ntpc 0.9.0-1 doesn't apply new settings

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#132]
**Reported by reporter on 22 Jun 2010 16:39 UTC**
With luci-app-ntpc 0.9.0-1, on OpenWRT 10.3 running on a Netgear WNDR3700, Luci seems to apply new settings (example: Time Interval or changing time servers) but does not reload them when they're changed.

ntpclient continues running with old settings and is only starts to run with new configuration if:

root@OpenWrt:~# killall nptclient
root@OpenWrt:~# chmod +x /etc/hotplug.d/iface/20-ntpclient
root@OpenWrt:~# /etc/hotplug.d/iface/20-ntpclient start_ntpclient

I don't know if this the expected behavior. I think it's not?

I've also discussed on #openwrt on freenode that if luci-app-ntpc is installed and running, rdate (System -> Sytem) should be disabled or existing servers deleted to avoid conflicts?

**Comment by hnyman** [comment]
works ok in the current Luci trunk
