### ISSUE TITLE
Is it possible to implement a line topology with 3 routers using mesh 802.11s protocol?

### ISSUE THREAD

**Issue by RaminnimaR** [openwrt/luci#1326]
Hey all

I have 3 routers and I want to implement the mesh setup in such way that the second router become the next hop for the first router and the third router become the next hop for the second router .

The reason for this setup is that I want to configure the first router as a dhcp router, the second one as a BOOTP dhcp relay and the third one as a DHCP client and dont want them all to see each other.

That would be greatly appreciated if any one can guid me through this

**Comment by hnyman** [comment]
Not a LuCI bug. Nothing to do with the user interface.

You should ask help in the forums:
https://forum.lede-project.org
https://forum.openwrt.org
