### ISSUE TITLE
interface management does not work

### ISSUE THREAD

**Issue by psyborg55** [openwrt/luci#1327]
trying to delete WAN6 interface results in nothing. trying to delete WAN interface disconnects both WAN and WAN6 interfaces but does not delete them.
traffic counter counts IPv4 traffic in WAN6 statistics.

using OpenWrt theme with LEDE Reboot SNAPSHOT r4721-0168ba2

**Comment by jow-** [comment]
wan6 is usually a simple IP alias to wan, the traffic counter is reporting stats of the underlying netdev. It is impossible for LuCI to differentiate traffic there.

**Comment by 0xFEEDC0DE64** [comment]
I could solve this by changing the device of WAN6 to one of the wifi interfaces and deleting it afterwards... still strange but it works!

**Comment by psyborg55** [comment]
i think that's not needed, this bug is chrome-specific, it works fine in firefox. maybe just some netifd script tweaking

**Comment by jow-** [comment]
Assuming that this has been fixed now.
