### ISSUE TITLE
[luci-app-openvpn] Several OpenVPN parameters missing from GUI

### ISSUE THREAD

**Issue by h3298** [openwrt/luci#1340]
**1.**
```
resolv-retry infinite
mssfix 'n'
```

(in /**usr/share/openvpn/openvpn.options** these are listed as supported, but dont seem to be in the GUI)
____________
**2.**  There is no GUI control to **enable log** and review it for connection errors (**option log '/etc/openvpn/log'**)

**Comment by nwf** [comment]
`tls-crypt`, the `tls-auth`-on-steroids option, also appears to be missing from the UI (or I just missed it).

**Comment by Wedmer** [comment]
I'll check this soon.

**Comment by Wedmer** [comment]
resolv_retry exists for client mode.
mssfix exists for udp proto.
tls-crypt is not supported by OpenWrt init script. If you need this option, then open issue for main OpenWrt project. Anyway it will be added.

There're no options for log file except verbosity as all OpenVPN instances use syslog.
