### ISSUE TITLE
XSS-related HTTP headers

### ISSUE THREAD

**Issue by leonyu** [openwrt/luci#1343]
LuCI does not appear to produce XSS-related HTTP headers that are designed to prevent some basic browser-side attacks. ([Clickjacking](https://en.wikipedia.org/wiki/Clickjacking), [XSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery))?

ref: 
* https://www.owasp.org/index.php/Security_Headers
* https://securityheaders.io/

**Comment by jow-** [comment]
Yes.

**Comment by leonyu** [comment]
Is it already implemented? Or a package I can install?
