### ISSUE TITLE
[design concept] New GUI for OpenVPN with easy configuration (drag & drop OVPN)

### ISSUE THREAD

**Issue by h3298** [openwrt/luci#1346]
**Screenshots**
https://www.gl-inet.com/docs/openwrt/openvpn/

**Repos**
https://github.com/domino-team

**Comment by Wedmer** [comment]
I suspect that uploading OVPN files will be incompatible with UCI.
Some more information can be found at #829

**Comment by dibdot** [comment]
no feedback, links broken - stale ticket.
