### ISSUE TITLE
Default LCP request setting is ignored

### ISSUE THREAD

**Issue by mastum** [openwrt/luci#1357]
Hi, 
not setting the value LCP request should not be send but that is not so, requests are still sent!
"Presume peer to be dead after given amount of LCP echo failures, use 0 to ignore failures" is ignored.

It's a very old bug present also on openwrt 15.05.1
https://dev.openwrt.org/ticket/11776

Is possible add the lcp-adaptive option?
https://forum.lede-project.org/t/frequent-wan-disconnects-wrt3200acm/802/2

Thanks

**Comment by jow-** [comment]
This has been fixed on the OpenWrt side
