### ISSUE TITLE
Add sortable tables - especially when handling static DNS entries

### ISSUE THREAD

**Issue by kisenberg** [openwrt/luci#1370]
If one IP is entered twice in the static DNS config-table, there is no check in the gui. So, there will be a duplicate IP-address saved in dnsmasq.conf.cfg and dnsmasq will fail to start up.

I suggest a duplicate-check when modifying the static DNS-table. Also the table should be sortable to have a faster overview - should be implemented for all tables.

**Comment by jow-** [comment]
Fixed via #5696
