### ISSUE TITLE
dhcp static lease on specific device doesnt stick?!

### ISSUE THREAD

**Issue by ghost** [openwrt/luci#1383]
Suddenly out the blue, one of my PC's in the network after any reboot keeps getting the first available IP that the dhcp is dishing out even though i have set it to a static one in the settings.

I have rebooted the PC a few times. Sometimes it grabs the IP its supposed to have but MOST times it doesnt.
Ive also noticed under "Active DHCP Leases"  right after the PC reboots, it gets the IP it was assigned, but then after a few seconds it changes back to the first available IP that the router dished out.

Im using: LEDE Reboot 17.01.2 r3435-65eec8bd5f

Please help?? whats going on here.. is it the Ubuntu PC? i doubt it..

**Comment by feckert** [comment]
17.01 is EOL and no other use reported such an issue.
