### ISSUE TITLE
installing luci on ubuntu

### ISSUE THREAD

**Issue by fanxiangqiang** [openwrt/luci#1388]
i am so sorry for a question.i want to install luci on ubunu for instantly programming and debugging ,and i download luci source code into my folder, next i  cd luci ,tap "make runuhttpd",then the trouble shows! im so sorry! because  of svn service stopping,but some code is needed to be downloaded from svn,i am upset. im thankful who knowns the solution!

make[1]: Leaving directory `/home/fanxiangqiang/luci/luci-luci-0.12/contrib/uci'
make[1]: Entering directory `/home/fanxiangqiang/luci/luci-luci-0.12/contrib/uhttpd'
svn co svn://svn.openwrt.org/openwrt/branches/backfire/package/uhttpd/src uhttpd-src
svn: E000111: Unable to connect to a repository at URL 'svn://svn.openwrt.org/openwrt/branches/backfire/package/uhttpd/src'
svn: E000111: Can't connect to host 'svn.openwrt.org': Connection refused
make[1]: *** [uhttpd-src/Makefile] Error 1
make[1]: Leaving directory `/home/fanxiangqiang/luci/luci-luci-0.12/contrib/uhttpd'
*** Compilation of contrib/uhttpd failed!

**Comment by fanxiangqiang** [comment]
![eee](https://user-images.githubusercontent.com/32658952/31366840-e3822682-ada5-11e7-80f1-111b1cef7b4a.png)

**Comment by hnyman** [comment]
You are looking at old ancient unsupported version of Luci (luci-0.12). there is no more svn server etc.

I am not sure if that kind of separate installation is supported, any more.

**Comment by fanxiangqiang** [comment]
Dose it mean  i cannot install    luci  on my ubuntu! ......,i will try it once more

**Comment by Wedmer** [comment]
Luci needs OpenWrt uci. There're no bindings for uci in ubuntu.

**Comment by kdm6389** [comment]
You can work with LEDE + LuCI on VirtualBox, I guess.

**Comment by hnyman** [comment]
I close this, as basically LuCI is not meant to be run outside the Openwrt/LEDE environment. It is tightly tied to that.

**Comment by syedumerbukhari** [comment]
> i am so sorry for a question.i want to install luci on ubunu for instantly programming and debugging ,and i download luci source code into my folder, next i cd luci ,tap "make runuhttpd",then the trouble shows! im so sorry! because of svn service stopping,but some code is needed to be downloaded from svn,i am upset. im thankful who knowns the solution!
> 
> make[1]: Leaving directory `/home/fanxiangqiang/luci/luci-luci-0.12/contrib/uci' make[1]: Entering directory `/home/fanxiangqiang/luci/luci-luci-0.12/contrib/uhttpd'
> svn co svn://svn.openwrt.org/openwrt/branches/backfire/package/uhttpd/src uhttpd-src
> svn: E000111: Unable to connect to a repository at URL 'svn://svn.openwrt.org/openwrt/branches/backfire/package/uhttpd/src'
> svn: E000111: Can't connect to host 'svn.openwrt.org': Connection refused
> make[1]: *** [uhttpd-src/Makefile] Error 1
> make[1]: Leaving directory `/home/fanxiangqiang/luci/luci-luci-0.12/contrib/uhttpd'
> *** Compilation of contrib/uhttpd failed!

brother did you found the solution on this issue?
