### ISSUE TITLE
Apostrophe (UTF-8: &#39;) shows as code instead of character in luci using french translation

### ISSUE THREAD

**Issue by blamaz** [openwrt/luci#1410]
(Overview) translated to: (Vue d&#39ensemble) 
(Hosts names) translated to (Noms d&#39hôtes)
I've remove the trailing ; after d&#39 to prevent renaming.

Tried the following with same results:
Chrome and IE on 2 differents computers,
Lede 17.0.4 stable branch and Davidc502 fork,
Forced Chrome to use UTF-8 instead of automatic detection.

Thank for your work

**Comment by kyle30312** [comment]
This problem occurs with Bootstrap and Material themes.  It does not occur with Freifunk_Generic and OpenWrt themes.

![luci-1410-screenshot1](https://user-images.githubusercontent.com/7157021/46167764-ad9bff00-c264-11e8-92a2-fab5deec4f0b.png)

![luci-1410-screenshot2](https://user-images.githubusercontent.com/7157021/46167777-b55ba380-c264-11e8-97f1-3a1cb1909c3f.png)

![luci-1410-screenshot3](https://user-images.githubusercontent.com/7157021/46167786-bab8ee00-c264-11e8-96c8-75b7d9a7cca5.png)

![luci-1410-screenshot4](https://user-images.githubusercontent.com/7157021/46167791-bdb3de80-c264-11e8-8b3e-53409ae30bf1.png)

**Comment by viking76** [comment]
We have the same problem with 18.06.2, why it is Closed issue. Thanks for french users :)

**Comment by kyle30312** [comment]
@jow- Perhaps fixes to bootstrap and material themes need to be merged from master to openwrt-18.06 branch?

**Comment by viking76** [comment]
@jow excuse for my wrong information (last snapshot tested), as kyle i think it can be pushed to openwrt-18.06,X, i have tested all theme all theme just rose-theme have  problem. thanks this snapshot really stable (more than 6 month).
