### ISSUE TITLE
Improve public perception LEDE in Luci

### ISSUE THREAD

**Issue by mray** [openwrt/luci#1415]
I'm not sure where and how to bring this up best, but I think LEDE would benefit from a logo that is usable in the luci UI:

![image](https://user-images.githubusercontent.com/164785/32028461-fec866fe-b9ee-11e7-9871-4ec19312e8b0.png)

---

![image](https://user-images.githubusercontent.com/164785/32028520-576cee7e-b9ef-11e7-9e86-7acf28012b41.png)

I'll provide license & source as requested.

**Comment by hnyman** [comment]
Sorry, LuCI is common to both Openwrt and LEDE, and these projects are planned to merge again as new Openwrt, so there will be no need for a separate LEDE logo in LucI
