### ISSUE TITLE
VLAN can be deleted even though working in an interface

### ISSUE THREAD

**Issue by HenryGiraldo** [openwrt/luci#1419]
It's not really a bug, but it would be helpful to use poka-yoke here.

It can leave you without access to the device and be forced to do factory reset or have to use the serial port to recover the device.

**Comment by jow-** [comment]
Yeah but in general there's many way to lock yourself out. You can also disable dropbear, delete lan, break the firewall rules, ...

**Comment by HenryGiraldo** [comment]
Yes, that's true, but I think it's a good practice to check if something is in use before you can delete it. 

In the case of dropbear you already know that as direct implication you will lose access through ssh, in this case you are destroying an interface configuration as collateral damage.

**Comment by metronidazole** [comment]
Is this still an issue with that feature that automatically reverts configuration changes that break your browser's access to LuCi?

**Comment by HenryGiraldo** [comment]
You could have access through the lan interface and not through the selected vlan. I don't think it's so much a problem related to the access itself, but to the robust of the system. It's a potential improvement, it's not really a "failure".
