### ISSUE TITLE
When an interface is deleted, it continues appearing in network tab

### ISSUE THREAD

**Issue by HenryGiraldo** [openwrt/luci#1420]
Initial state:
![1](https://user-images.githubusercontent.com/15778456/32162461-5afe3274-bd59-11e7-8acd-23555090c8dd.png)
Creating the interface:
![2](https://user-images.githubusercontent.com/15778456/32162462-5d3928e6-bd59-11e7-9900-68a2eb0456b1.png)
Interface working:
![3](https://user-images.githubusercontent.com/15778456/32162468-5eab8f7a-bd59-11e7-8532-e458b7a477bf.png)
After pressing the delete button:
![4](https://user-images.githubusercontent.com/15778456/32162472-60626ed8-bd59-11e7-8a57-aa81999d4979.png)

**Comment by woutput** [comment]
I ran into the same issue.
Note that in my case, deleting an interface
- works correctly when using Firefox on laptop
- does not work correctly when using Chrome on Android smartphone

So this may be browser related(?)

**Comment by woutput** [comment]
Solved? If so, in which commit/release?
Thanks

**Comment by HenryGiraldo** [comment]
I don't know. It's been too long, I don't find any reason to keep the ticket open.
