### ISSUE TITLE
uhttpd-mod-ubus.postinst errors

### ISSUE THREAD

**Issue by xosevp** [openwrt/luci#1421]
After install luci and luci-ssl in LEDE-snapshot for ar71xx(wzr-hp-g300nh2):

[...]
Configuring luci-theme-bootstrap.
Configuring luci-app-firewall.
Configuring libpcap.
Configuring tcpdump.
Configuring lua.
Configuring uhttpd.
Configuring uhttpd-mod-ubus.
//usr/lib/opkg/info/uhttpd-mod-ubus.postinst: .: line 130: 00_uhttpd_ubus: not found
Configuring luci-lib-nixio.
Configuring luci-lib-jsonc.
Configuring luci-base.
Configuring luci-mod-admin-full.
Configuring luci-proto-ppp.
[...]

**Comment by jow-** [comment]
Upstream issue fixed in LEDE https://github.com/lede-project/source/commit/73c745f64f17a0326c53e614aa0dd125b47053ec
