### ISSUE TITLE
Numerical interface names breaks dnsmasq

### ISSUE THREAD

**Issue by keaneokelley** [openwrt/luci#1429]
If an interface is created with the name '123' and DHCP is enabled, the resulting dnsmasq config file will look like:
```
dhcp-range=123,192.168.1.10,192.168.1.100,24h
```

The number in the first argument to `dhcp-range` silently prevents dnsmasq from loading with the error "Invalid range at line x". Could be fixed with some validation.

**Comment by jow-** [comment]
Cannot reproduce it. Current OpenWrt/LEDE seems to handle it fine.
