### ISSUE TITLE
luci-app-openvpn - Option to upload a .ovpn configuration file

### ISSUE THREAD

**Issue by artioni81** [openwrt/luci#1430]
is it possible to integrate the possibility to upload a .ovpn configuration file just as per ca/cert/key. This way it would be very simple to create client vpn connections: just give the connection a name and upload the appropriate ovpn file. 

in the shell using uci this is done with just three commands, after uploading through sftp the ovpn file in /etc/openvpn/:

uci set openvpn.vpnname='openvpn'
uci set openvpn.vpnname.enabled='1'
uci set openvpn.vpnname.config='/etc/openvpn/your_vpn_conf.ovpn'

**Comment by GabrielTK** [comment]
+1

**Comment by ktaragorn** [comment]
Linked to https://github.com/openwrt/luci/issues/829

**Comment by dibdot** [comment]
now in trunk with 0b04912
