### ISSUE TITLE
See connected device

### ISSUE THREAD

**Issue by xifi-kif** [openwrt/luci#1441]
I can't find a way to see a list of all connected devices in Luci, where is it?
I just see active dhcp leases.
There should also be the possibility to check wifi-only connected devices, imho.

**Comment by jow-** [comment]
Wifi clients are listed in the main status page as well in the wireless settings overview page.

**Comment by xifi-kif** [comment]
what about cable connected clients?

**Comment by jow-** [comment]
You can find this information in the ARP table.
