### ISSUE TITLE
Luci-ssl or Luci-openssl on IPQ806X is not working  properly under 17.01.4

### ISSUE THREAD

**Issue by oso21** [openwrt/luci#1443]
LEDE 17.01.4
Kernel 4.9.60
Router: Netgear R7500V2
Packages: Up to Date (2017-11-15)
LuCI works great if Luci-ssl or Luci-openssl is not installed.Once Luci-ssl or Luci-openssl installed with https configuration ,LuCI gets stuck every now and then ,and you`ll have to refresh .When using Firefox ,web crashes and come up with  SSL Error: ssl_error_bad_mac_read. Dont know if there is bug in ssl libaries .

**Comment by jow-** [comment]
This is an issue with the `ustream-ssl` library in LEDE then. Please report an issue at http://bugs.lede-project.org/
