### ISSUE TITLE
Button properties like title, inputtitle and so...

### ISSUE THREAD

**Issue by ondonadas** [openwrt/luci#1448]
Sorry for such basical question, but I'm .
Please, someone could recommend me a good LUCI source of documentation? Especially talking about object properties like Button. Recently I've been aware that it supports properties like:
- title
- inputitle
- inputstyle (apply, reload, rename, save, reset, cancel something more?)
I've look at https://github.com/openwrt/luci/wiki/Documentation but I can't find anything about it.
Regards

**Comment by jow-** [comment]
You need to take a look at the templates in https://github.com/openwrt/luci/tree/master/modules/luci-base/luasrc/view/cbi to learn about supported properties.
