### ISSUE TITLE
Use "stop/commit/start" rather than "commit/reload"

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#145]
**Reported by reporter on 22 Oct 2010 03:33 UTC**
I have just been wrestling with the problem of not knowing what the original configuration was for a service.  The problem is that "Save&Apply" commits the changes before calling "restart" on the init-script.  So the init-script no longer knows the original configuration to tear down cleanly.

I would suggest that calling "stop" on the init-script before committing the new configuration, This would provide confidence that the configuration is still the same that was used when the service was initially started (ie: we can trust this is the original configuration).  Then commit the new configuration and run "start".

**Comment by cshoredaniel** [comment]
Is this still and issue with procd services?  If not then I think this should be avoid because reload vs. stop/start may have dangerous side effects (like stopping services that should never be stopped, e.g fstab or uhttpd, but only reloaded).

**Comment by jow-** [comment]
Modern procd-enabled services should care of dispatching the proper command sequences.
