### ISSUE TITLE
Print Server Nexx wt3020

### ISSUE THREAD

**Issue by afteixei** [openwrt/luci#1472]
Hi all.

Is it possible use the router nexx wt3020 like a print server? i have a old HP printer with usb port and i want connect in nexx wt3020 connected wi-fi. I see a little tutorial http://www.fischl.de/ql_printserver/ but i cannot finish the installation.

Many thanks,.

**Comment by karlp** [comment]
You're probably better off trying to ask this in a user support forum for openwrt, not the bug tracker for one particular user interface.
