### ISSUE TITLE
uci incorrectly showing host with DHCP lease, but luci correctly omits it

### ISSUE THREAD

**Issue by Human** [openwrt/luci#1474]
On LEDE 17.01.4, a particular host I have properly disappears from the luci web UI when it leaves the network, but it remains in the output of 'uci show dhcp'

What debugging info could I provide to narrow this down? Is there a uci-specific forum where I should post this instead?

**Comment by jow-** [comment]
"uci show dhcp" just dumps the configured static leases in /etc/config/dhcp. It is not supposed to dynamically change when hosts join or leave the network.
