### ISSUE TITLE
LuCI interface overview shows wrong IPv6 address when UCI option ip6hostid is set to 'eui64'

### ISSUE THREAD

**Issue by silentcreek** [openwrt/luci#1484]
Note: I think this issue is related to issue #1483 .

When I set ip6hostid for my LAN interface to ‘eui64’, LuCI will not show the correct/actual IPv6 addresses in the overview under “Network” → “Interfaces”. The addresses are still shown as “[Assigned Prefix] + ::1/64” (e.g.: 2a09:7657:fee0:12f0::1/64), while in fact the interface is correctly assigned an IPv6 address in the form of “[Assigned Prefix] + [eui64]”. Over SSH I can verify that the command ‘ip addr’ will show the correct IPv6 address, but not any IPv6 address that ends in ::1. The output of ‘ubus call network.interface.lan status’ will also show the eui64-derived IPv6 address and not the default one ending in ::1.

Based on my findings described in #1483 , I assume that the same issue will occur when ip6hostid is set to ‘random’, but I have not tested this.

I observed this on LEDE 17.01.4.

**Comment by andrewsil1** [comment]
I can also reproduce this just by setting the suffix to a static value such as "::110".  The LUCI interface UI will still show that the address has been assigned as ::1 even though ifconfig shows only the correctly requested xxx::110 address.
