### ISSUE TITLE
wirless无线概况  加密: -

### ISSUE THREAD

**Issue by superliurui** [openwrt/luci#1487]
无线概况

	Generic Mediatek/Ralink 802.11bgn (mt7615e2)
信道: 1 (2.412 GHz) | 传输速率: 300 Mbit/s	 搜索  添加
100%	SSID: k2p-2.4g | 模式: Master
BSSID: 76:7D:24:70:9C:B0 | 加密: -	(此处已经使用WPA加密)

	Generic Mediatek/Ralink 802.11bgnac (mt7615e5)
信道: 149 (5.745 GHz) | 传输速率: 866 Mbit/s	 搜索  添加
100%	SSID: k2p-5g | 模式: Master
BSSID: 74:7D:24:60:9C:B0 | 加密: -	(此处已经使用WPA加密)

**Comment by yousong** [comment]
Invalid report
