### ISSUE TITLE
luci-base: column sorting

### ISSUE THREAD

**Issue by ketefoy** [openwrt/luci#1491]
Hello,
Thanks for your work, I have gotten my colleagues to use LuCI, but we have so many static leases that we would like to sort the columns by their IP addresses.

**Comment by sophana** [comment]
I think this should be done browser side in javascript, also with a javascript search form.
The same for firewall port forwards.
Will have a look one day.

**Comment by feckert** [comment]
https://github.com/openwrt/luci/pull/2623

**Comment by 5p0ng3b0b** [comment]
The Network/Hostnames page already has the ability to move entries up and down to change the order of the list. Would it not be a simple affair to add this function to the Static Leases page as well?

**Comment by jow-** [comment]
Dupe of #1370
