### ISSUE TITLE
Problem installing luci (probably easy solve)

### ISSUE THREAD

**Issue by tjip1234** [openwrt/luci#1496]
I had an error installing luci  it is probably easy to fix ( I am new here)
![img-20180103-wa0000](https://user-images.githubusercontent.com/35073307/34529671-155b6638-f0ad-11e7-81e3-175a273abd5a.jpeg)

**Comment by jow-** [comment]
You need to wait until an updated `libuci-lua` becomes available withi nthe next 24 hours. There is nothing we can do right now. You can do an `opkg --force-depends install luci-ssl` but some wireless status reporting will likely be broken.
