### ISSUE TITLE
Latest Snapshot Dependency Error (libuci-lua)

### ISSUE THREAD

**Issue by tylermeuse** [openwrt/luci#1498]
Trying to install/upgrade LuCI with today's package results in a dependency requirement for a package that does not exist yet:

    Downloading http://downloads.lede-project.org/snapshots/packages/mips_24kc/luci/luci_git-  18.003.32380-b121f95-1_all.ipk
    Collected errors:
     * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
     * libuci-lua (>= 2018-01-01) * 

LuCI will install, but accessing settings such as System > Wireless results in:

    /usr/lib/lua/luci/dispatcher.lua:478: Failed to execute arcombine dispatcher target for entry '/admin/network/wireless'.
    The called action terminated with an exception:
    /usr/lib/lua/luci/template.lua:97: Failed to execute template 'admin_network/wifi_overview'.
    A runtime error occured: [string "/usr/lib/lua/luci/view/admin_network/wifi_o..."]:90: table index is nil
    stack traceback:
	    [C]: in function 'assert'
	    /usr/lib/lua/luci/dispatcher.lua:478: in function 'dispatch'
	    /usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by jow-** [comment]
Yes, you need to wait until the dependency becomes available or compile yourself.
