### ISSUE TITLE
FirmwareFlash zeigt keinen Status mehr

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#150]
**Reported by reporter on 2 Nov 2010 16:34 UTC**
Seit LuCI 0.10 (bei r6379 aufgefallen) wird der Status des Upgrade-Prozesses im Statusfenster nicht mehr angezeigt. Das Upgrade funktioniert hingegen richtig.

JoeSemler, 0xFF-Vienna

**Comment by hnyman** [comment]
Related to old versions.
Worksforme.
Completed upgrade process leads currently to the Luci login page after the router has booted after the flash. Works both in CC15.05 and in DD trunk.
