### ISSUE TITLE
DNS servers on Status Overview page

### ISSUE THREAD

**Issue by patricktokeeffe** [openwrt/luci#1507]
> Powered by LuCI (git-15.248.30277-3836b45) / OpenWrt Chaos Calmer 15.0

I changed my DNS servers to use Google addresses (8.8.8.8, 8.8.4.4) but the server addresses displayed on the Status > Overview page still reflect my ISPs servers:

![actual-dns](https://user-images.githubusercontent.com/1348834/34652240-735f70ae-f390-11e7-80bf-dddccc7ac1c4.png)

I'm pretty certain that Google's servers are actually being used: I get errors for non-existent domains instead of an ISP search page, and the ISP addresses don't show up in `dig` traces. 

Since this is a "status" page, I expect the actual, not advertised, DNS servers be listed here

**Comment by jow-** [comment]
HOw did you change them?

**Comment by patricktokeeffe** [comment]
I set them under *Network* > *DHCP and DNS*. Is there another place they can be configured?

**Comment by jow-** [comment]
Yes. Admin -> Network -> Interface -> wan -> Advanced Settings.
Uncheck `Use DNS servers advertised by peer` and fill in one or more addresses into `Use custom DNS servers`

**Comment by patricktokeeffe** [comment]
> Uncheck `Use DNS servers advertised by peer`

priceless 💪 thank you @jow-
