### ISSUE TITLE
Status page: shows wrong wan status interface (static ip configured)

### ISSUE THREAD

**Issue by avintis** [openwrt/luci#1520]
If the wan ip is static configured (not dhcp) the status page (overview) shows the wrong interface. In my case the "br-lan40" instead eth0 (see screenshot):
![image](https://user-images.githubusercontent.com/20594353/34768751-18b73286-f5fc-11e7-89e6-3a0597e0fc8d.png)

Versions used:
- Powered by LuCI Master (git-17.360.63400-902b292) / OpenWrt SNAPSHOT r5629-23bba9c
- OpenWrt SNAPSHOT r5629-23bba9c / LuCI Master (git-17.360.63400-902b292)
- Router TP-Link Archer C7 v2

**Comment by jow-** [comment]
This is due to the fact that you wrongly configured a gateway option on your lan interface. Remove it.

**Comment by avintis** [comment]
Thanks, what is wrong?



* ++ improve your information liquidity!*
*:: **Alfred Berger*, CEO
*:: *Avintis SA
*:: *route du Tir-Fédéral 10 *:: *CH-1762 Givisiez
*:: *tel: +41 26 469 71 11 *:: *fax: +41 26 469 71 10
*:: *mobil: +41 79 455 20 62
*:: *a.berger@avintis.com *:: *www.avintis.com

2018-01-10 11:57 GMT+01:00 Jo-Philipp Wich <notifications@github.com>:
