### ISSUE TITLE
admin-status-overview: show used RAM Memory

### ISSUE THREAD

**Issue by FreifunkUFO** [openwrt/luci#1533]
on the status-page there is some information about RAM Memory usage (all free, free, buffered). but the most important value "used Mem" is missing.
please add that value.
maybe these all four values should be resorted?

**Comment by FreifunkUFO** [comment]
![luci-status-ram](https://user-images.githubusercontent.com/2579265/34890441-387c5a06-f7d2-11e7-9b4c-f1659e71fcc1.png)

**Comment by user7887** [comment]
Support :)

**Comment by LipkeGu** [comment]
Sorry when im wrong but it is inaccurate, because used ram is depending on what modules you have loaded. Like ```zram``` and ```zramswap```

**Comment by jow-** [comment]
Used ram is the inversion of "free".
