### ISSUE TITLE
Have to click everything twice

### ISSUE THREAD

**Issue by baberb** [openwrt/luci#1543]
The web interface has seemed excruciatingly slow for me, until I noticed that I have to click the links twice for it to work - to do anything, navigate anywhere: have to do it twice.  It wasn't really that slow, just have to give it a couple seconds and on the second click it works.  This sucks for any links that change page, because of the js the page goes blank but the url stays the same (didn't hit it twice!), with wheels spinning waiting for a page that never comes (and wasn't even asked for!).  Have to open in new tab, then either click the button again on the new tab or F5 to refresh and actually load it.  After much struggling, I was able to restore a backup and now everything seems to be working normally...

**Comment by jow-** [comment]
Not much to work with here, I assume some misconfiguration or browser / LuCI interaction quirk.
