### ISSUE TITLE
Duplicate associated clients in Wifi Associated clients list

### ISSUE THREAD

**Issue by sklerotraficon** [openwrt/luci#1545]
Under LuCI lede-17.01 branch (git-17.290.79498-d3f0685) on my Linksys WRT1900ACS

With multiple Wifi networks (3x 5GHz - 1 of 3 is disabled, 1x 2.4GHz), that in the Associated Clients List (https://[router-ip]/cgi-bin/luci/admin/network/wireless): 

All clients and their respective details (SSID, MAC-Address, Host, SNR,RX-/TX-Rate) in one (and only in one) of the 5Ghz Wifi Network are listed twice.

This might be related to: [this issue](https://github.com/openwrt/luci/issues/1179)

**Comment by jow-** [comment]
Fixed in master with f9b8d7ff7bbd3c82f9889b65af07a28d94d9fed7
