### ISSUE TITLE
luci-app-noddos 2 need to fix

### ISSUE THREAD

**Issue by user7887** [openwrt/luci#1556]
Thanks to the author, great app! but..
1) Link together with the word:
![bag5](https://user-images.githubusercontent.com/28679841/34998712-e02e5a76-faf0-11e7-8586-4f138f83b15e.png)
2) Maybe just IP-addresses :):
![nod2-1](https://user-images.githubusercontent.com/28679841/34998766-0851a38c-faf1-11e7-87c2-6aa55de01b37.png)
If you need help let me know:)
I could prepare and make corrections myself, but maybe you have responsibilities, and my intervention will break them. Thank you!

**Comment by stangri** [comment]
You will most likely need to fix this file: https://github.com/openwrt/luci/blob/master/applications/luci-app-noddos/po/ru/noddos.po and then create a Pull Request to have the correct version merged.

**Comment by stangri** [comment]
There are to issues:
1. The space between localizable resource and the programmatic output is part of the localizable resource. If it's moved out of it, that should fix the problem.
2. IPv4 used as a header for the table where IPv6 addresses also present.

@feckert -- I can fix this if you want me to.

**Comment by Strykar** [comment]
Upstream project is dead, this should be closed - https://github.com/noddos/noddos/issues/55#issuecomment-747105165

**Comment by hnyman** [comment]
The package is to be removed.
