### ISSUE TITLE
openvpn-app does not show multiple openvpn servers

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#156]
**Reported by reporter on 12 Nov 2010 09:16 UTC**
After entering more than one openvpn server the list will be added to the openvpn config file (/etc/config/openvpn) and will also be used to generate the openvpn commandline parameters (--remote ...).

But it is impossible to modify the list of "remote servers" using the web frontend - only the first list entry will be shown.
If you try to remove the first entry '''all entries will be removed'''!

The bug was seen on backfire 10.03 (brcm47xx and brcm-2.4) and backfire-trunk (ramips).

**Comment by hnyman** [comment]
Based on evidence from Wedmer, closing this ancient report (imported from the old bug tracker)
