### ISSUE TITLE
Firewall - Port forward: NAT Loopback not working for other than LAN Zone

### ISSUE THREAD

**Issue by bbogey** [openwrt/luci#1560]
I have multiple LAN zones. NAT loopback works only from LAN, not from other zones.
Please add an option to select from which zones NAT loopback should be working.

**Comment by feckert** [comment]
@bbogey could you explain more where to add this?

**Comment by jow-** [comment]
That would need to be implemented in OpenWrt/LEDE's firewall3 first before such an option could be added to LuCI.

**Comment by micw** [comment]
Hello,
it's 2 years ago since this was reported. Has the state changed? I have the same issue with 19.07.1.

**Comment by GrimKriegor** [comment]
@micw Here is [the link](https://bugs.openwrt.org/index.php?do=details&task_id=1645&dev=4) for this issue in the OpenWRT bugtracker.

**Comment by heapxor** [comment]
so everyone ignores such a important issue?

**Comment by jmou** [comment]
For anyone else searching for a solution, this appears to have been implemented with the `reflection_zone` option in `/etc/config/firewall`. I don't think it is configurable through LuCI yet. For an example see https://github.com/openwrt/openwrt/issues/8868#issuecomment-1229441623
