### ISSUE TITLE
improve 802.11s support in lede-17.01-branch (cherry-pick from master)

### ISSUE THREAD

**Issue by SvenRoederer** [openwrt/luci#1577]
can you cherry-pick :
* 267bf83db020295179fad88c6859e50e3406665a (PR https://github.com/openwrt/luci/pull/1363)
* 63255ec38b2f5849fec9e54d3f3e2aa7ef76bd72 (PR https://github.com/openwrt/luci/pull/1513)

from master into lede-17.01 branch, to enable config of 802.11s via LuCI?

**Comment by hnyman** [comment]
I cherry-picked those as it looked like a reasonable request.
Hopefully nothing breaks.
