### ISSUE TITLE
Incorrect MAC=00:00:00:00:00:00 on TL-WR740N/ND v4 interface WAN

### ISSUE THREAD

**Issue by matroot** [openwrt/luci#1584]
Version of LEDE and LuCI:
LEDE Reboot 17.01.4 r3560-79f57e422d / LuCI lede-17.01 branch (git-17.290.79498-d3f0685)

LuCI is showing the mac address "00:00:00:00:00:00" at WAN interface. The WAN6 interface is correct and is showing the same ifconfig mac.

**Comment by LipkeGu** [comment]
We need more details what is WAN on your side? (pppoe ????)

**Comment by jow-** [comment]
This can happen in cases where the wan interface is not an ethernet device.
