### ISSUE TITLE
error says "Package libiwinfo required!The libiwinfo-lua package is not installed." but installed indeed

### ISSUE THREAD

**Issue by tingjhenjiang** [openwrt/luci#1594]
I built my own openwrt image in ar71xx, generic-glibc, snapshot image "OpenWrt SNAPSHOT, r5933-a9ffe9f" (2018-01-24).

In Network -> Wireless it says in a yellow box:
Package libiwinfo required!
The libiwinfo-lua package is not installed. You must install this component for working wireless configuration!

opkg info libiwinfo

> Package: libiwinfo
> Version: 2018-01-16-5a5e21b1-1
> Depends: libc, libssp, librt, libpthread, libnl-tiny, libuci
> Status: install user installed
> Section: libs
> Architecture: mips_24kc
> Size: 22283
> Filename: libiwinfo_2018-01-16-5a5e21b1-1_mips_24kc.ipk
> Description: Wireless information library with consistent interface for proprietary Broadcom,
>  nl80211 and wext driver interfaces.
> Installed-Time: 1516704405

opkg info libiwinfo-lua

> Package: libiwinfo-lua
> Version: 2018-01-16-5a5e21b1-1
> Depends: libc, libiwinfo, liblua
> Status: install user installed
> Section: lang
> Architecture: mips_24kc
> Size: 6774
> Filename: libiwinfo-lua_2018-01-16-5a5e21b1-1_mips_24kc.ipk
> Description: This is the Lua binding for the iwinfo library. It provides access to all enabled
>  backends.
> Installed-Time: 1516852650

ldd /usr/lib/lua/iwinfo.so

> Segmentation fault

lua -l iwinfo

> lua: error loading module 'iwinfo' from file '/usr/lib/lua/iwinfo.so':
>         libc.so: cannot open shared object file: No such file or directory
> stack traceback:
>         [C]: ?
>         [C]: ?
>         [C]: ?

cat /etc/os-release

> NAME="OpenWrt"
> VERSION="SNAPSHOT"
> ID="openwrt"
> ID_LIKE="lede openwrt"
> PRETTY_NAME="OpenWrt SNAPSHOT"
> VERSION_ID="snapshot"
> HOME_URL="http://lede-project.org/"
> BUG_URL="http://bugs.lede-project.org/"
> SUPPORT_URL="http://forum.lede-project.org/"
> BUILD_ID="r5933-a9ffe9f"
> LEDE_BOARD="ramips/mt7621"
> LEDE_ARCH="mipsel_24kc"
> LEDE_TAINTS=""
> LEDE_DEVICE_MANUFACTURER="OpenWrt"
> LEDE_DEVICE_MANUFACTURER_URL="http://lede-project.org/"
> LEDE_DEVICE_PRODUCT="Generic"
> LEDE_DEVICE_REVISION="v0"
> LEDE_RELEASE="OpenWrt SNAPSHOT r5933-a9ffe9f"

**Comment by jow-** [comment]
This is not a problem with LuCI.

This error suggests that you installed a package that was built for another libc:

```
lua: error loading module 'iwinfo' from file '/usr/lib/lua/iwinfo.so':
libc.so: cannot open shared object file: No such file or directory
```
