### ISSUE TITLE
Infinite loop bug 

### ISSUE THREAD

**Issue by guhongyeying** [openwrt/luci#1595]
in the OpenWrt-luci-theme-material ，when you log in。base on OpenWrt Chaos Calmer 15.05.1 r49610

**Comment by hnyman** [comment]
> OpenWrt-luci-theme-material ，when you log in。base on OpenWrt Chaos Calmer 15.05.1 r49610

There is no luci-theme-material on for-15.05 branch.
Material theme has not been adapted to the old 15.05 that is slightly different in LuCI.
https://github.com/openwrt/luci/tree/for-15.05/themes

You are on your own in adapting that.

**Comment by guhongyeying** [comment]
i konw ，I copied it directly into the source code and Compile

**Comment by guhongyeying** [comment]
i add some ,luci-theme-material  it works,base on OpenWrt Chaos Calmer 15.05.1 r49610
