### ISSUE TITLE
Mount Points discrepancy

### ISSUE THREAD

**Issue by user7887** [openwrt/luci#1599]
Hello all :)
Menu 'Mount Points' is designed for mounting partitions of hard and flash drives.
Let's clarify the wording:
sda, sdb - flash or hard drive
sda1, sda2, sdb3 - flash or hard drive partitions
ext2, ext4, ntfs - flash or hard drive filesystems
/mnt/sda1, /mnt/sdb3 - mount points

Here, I propose the following changes:
https://github.com/openwrt/luci/pull/1598
See the screenshots how it will look:
![1](https://user-images.githubusercontent.com/28679841/35472391-5a7493f4-037f-11e8-9f20-1220cc3f2ac4.png)
![2](https://user-images.githubusercontent.com/28679841/35472393-5d205eda-037f-11e8-9960-dfe3b69018f0.png)
![3](https://user-images.githubusercontent.com/28679841/35472395-5f573584-037f-11e8-8ebc-68880dfe7c3c.png)
![4](https://user-images.githubusercontent.com/28679841/35472396-634fb80a-037f-11e8-9eb7-a114a74dae97.png)
![5](https://user-images.githubusercontent.com/28679841/35472397-65cf7660-037f-11e8-9286-d75c68103722.png)
![6](https://user-images.githubusercontent.com/28679841/35472398-676d1a54-037f-11e8-9ac4-66f74448a1cc.png)
![7](https://user-images.githubusercontent.com/28679841/35472399-69b01d70-037f-11e8-873d-acdd3aac24ce.png)

Thanks!

**Comment by user7887** [comment]
Now there:
![z1](https://user-images.githubusercontent.com/28679841/35473143-c614cec8-038c-11e8-9599-d3248c002cc5.png)
![z2](https://user-images.githubusercontent.com/28679841/35473144-c88699e8-038c-11e8-967e-2088a37573e0.png)
![z3](https://user-images.githubusercontent.com/28679841/35473145-ca9bd2b6-038c-11e8-86a8-41c81647536b.png)
![z4](https://user-images.githubusercontent.com/28679841/35473146-cccf93d8-038c-11e8-91f8-95fe40ee164f.png)
![z5](https://user-images.githubusercontent.com/28679841/35473148-d084004a-038c-11e8-837c-8a9591e517b5.png)
![z6](https://user-images.githubusercontent.com/28679841/35473149-d3b2193c-038c-11e8-902c-760f7e608ef4.png)
![z7](https://user-images.githubusercontent.com/28679841/35473150-d69d24b6-038c-11e8-83d2-8817cd34b294.png)

**Comment by feckert** [comment]
@user7887 
From my point of view the changes make sense.
Open a PR if some one don't like it you will get a comment on this :-)
