### ISSUE TITLE
luci-app-wireguard: connection refused, ports not opened

### ISSUE THREAD

**Issue by neographikal** [openwrt/luci#1602]
Tried to get the wireguard extension working, installed on two LEDE routers (LEDE Reboot 17.01.4 r3560-79f57e422d) followed the guide on https://danrl.com/blog/2017/luci-proto-wireguard/ and https://www.wireguard.com/quickstart/ but the daemon does not seem to listen to the configured ports.

On both hosts:
![wireguard](https://user-images.githubusercontent.com/2643715/35481677-60af8928-0428-11e8-9c93-30f2cfcb82ef.PNG)

![wireguard](https://user-images.githubusercontent.com/2643715/35481671-2ea28f7a-0428-11e8-879b-6588083a9f7a.PNG)

At first I thought I made a configuration error with the keys or something, but with the ports closed it's not strange that it won't connect.

**Comment by yousong** [comment]
telnet won't work here because wireguard is udp based

**Comment by neographikal** [comment]
Well that was stupid, you're right ofcourse. It does start though, from syslog:

```
Sun Jan 28 12:21:14 2018 kern.info kernel: [    9.529782] nf_conntrack version 0.5.0 (1963 buckets, 7852 max)
Sun Jan 28 12:21:14 2018 kern.info kernel: [    9.633645] wireguard: WireGuard 0.0.20171017 loaded. See www.wireguard.com for information.
Sun Jan 28 12:21:14 2018 kern.info kernel: [    9.642274] wireguard: Copyright (C) 2015-2017 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
```

**Comment by neographikal** [comment]
okay that was weird, switched to a port high in the 50000's and now suddenly it connects.

**Comment by yousong** [comment]
The nmap result indicates that wireguard is actually there waiting for traffic, but I also have no idea why netstat shows nothing

**Comment by yousong** [comment]
Ha! it comes to my mind that port 500 is some well-known port related to ipsec.  `netstat -ap` will convert it into the named form and `grep 500` will show nothing!
