### ISSUE TITLE
UX: luci-proto-wireguard UI suggests default listening port where there is none

### ISSUE THREAD

**Issue by squarewf** [openwrt/luci#1609]
This should be quite straightforward: luci-proto-wireguard, when editing the interface details, has "51820" as placeholder in the "listen port" input field:

![image](https://user-images.githubusercontent.com/30551458/35541262-3300ff74-055a-11e8-9416-b8f52c028f44.png)

This suggests that the default listen port is 51820. In fact, there is no default port, when undefined WireGuard uses a random ephemeral port.

I suggest changing the placeholder string to either something like "random", or maybe even better, remove the placeholder entirely and add a notice about random ports to the remark below.

**Comment by yousong** [comment]
ping luci-app-wireguard's current maintainer @danrl  ;)

**Comment by danrl** [comment]
If you think this is an improvement, I am fine with a pull request changing this. Unless @zx2c4 does not object.

**Comment by squarewf** [comment]
I'd happily submit a pull request, but I don't want to decide what to do about it:
a) rephrase the placeholder
b) remove the placeholder, and possibly amend the remark below
or maybe even
c) change /lib/netifd/proto/wireguard.sh to default to port 51820

I just know the status quo is confusing. Because, and I'm not ashamed to admit, it confused me and sent me on a chase debugging my setup.

**Comment by zx2c4** [comment]
Perhaps change the placeholder to `random` and mention in the text below that the suggested non-random port is 51820? Or vice-versa.

**Comment by danrl** [comment]
I opt for changing the placeholder to "random". It describes the behavior if left empty, and this is what the placeholder is for IMHO.

Nice catch, btw, @squarewf
