### ISSUE TITLE
luci-app-commands: does not support pipes

### ISSUE THREAD

**Issue by badfiles** [openwrt/luci#1622]
The pipe symbol `|` is somehow turned into `"|"`, so the piped commands fail.
exmample:
instead of `opkg list-upgradable | cut -f 1 -d " "`
gets executed and fails `opkg list-upgradable "|" cut -f 1 -d " "`

**Comment by tchabaud** [comment]
Same problem for redirections : > is escaped to ">"

**Comment by feckert** [comment]
A workaround for this is to write a script and call this with luci-app-commands. I think this is not a bug. Maybe we should update the info that not use | and > <
