### ISSUE TITLE
No statistic information of interfaces...

### ISSUE THREAD

**Issue by itProfi** [openwrt/luci#1631]
I compile openwrt 17-02-2018..
![18-02-2018 160008](https://user-images.githubusercontent.com/6728198/36352119-3ed1fcb6-14c5-11e8-825a-a3ba04fae9ae.jpg)
In this picture no valid information about statistic for each interface....Is it bug o i make somthing wrong?

**Comment by christoph00** [comment]
I had the same issue. cbi.js in /www/luci-static/resources had wrong permissions. Fixed it with chmod 644 cbi.js

**Comment by itProfi** [comment]
Ok, thanks!
