### ISSUE TITLE
LEDE 17.01.4 - USB LED Does not blink when device accessed

### ISSUE THREAD

**Issue by dr431** [openwrt/luci#1632]
The light is on but does not blink when the device is accessed. This used to work in Openwrt ChaosCalmer 15.05, and in in the version of ChaosCalmer before that there was a kernel driver kmod-use-. There used to be a kernel driver kmod-ledtrig-usbdev that provided this functionality. I've extended the file system onto a USB disk, and since the USB port is in the rear on the router, you can't tell if there is any activity on the USB device.

**Comment by dibdot** [comment]
Wrong repo again! Please read my comment in package repo, sounds like a configuration issue - maybe you should ask in LEDE/Openwrt forum first.
