### ISSUE TITLE
luci-app-firewall: cannot use multiple ports for the same rule

### ISSUE THREAD

**Issue by luizluca** [openwrt/luci#1637]
On LEDE 17.01.4:

UCI and fw3 accepts rules like:

```
config rule
        option enabled '1'
        option target 'ACCEPT'
        option proto 'tcp'
        option name 'adm open'
        option src 'lan'
        option src_ip '10.1.1.0/24'
        list dest_port '80'
        list dest_port '22'
```

LuCI even already shows it nicely in "Traffic rules" tables as "To any router IP at ports 80, 22 on this device"

However, the "Edit Rule" view only allows one port. It simply shows the first port (in case, 80). If I change port 80 to 81, LuCI changes the port entries from "list" to "option", remove all existing port references and use only the new port (81).

**Comment by luizluca** [comment]
The same goes for src_ip.

**Comment by EricLuehrsen** [comment]
Either "_port" option can be entered as a space separated lists. That is one work around at least. The "_ip" options do not work this way though.

**Comment by jow-** [comment]
Will take care of it soon (tm) - I promise. The main hurdle here is the lack of suitable widgets. The rule detail forms are a huge mess already and I need to think about a way to structure them better.
