### ISSUE TITLE
luci does not work with lighttpd on 17.01.4

### ISSUE THREAD

**Issue by laoshaw** [openwrt/luci#1639]
17.01.4 just added 4 patches for lighttpd to make it work with luci, however that is not working, I could not even see the login page at all. I can show my testing static html files and also run testing cgi-bin/my.cgi scripts just fine when luci is not involved. the problem is now with, in fact the luci login page never showed up.

my lighttpd.conf for cgi:

`
cgi.local-redir = "enable" cgi.assign = ( "cgi-bin/luci" => "", ".cgi" => "" )
`

error message is below, might be caused by no authentication page shown thus the error is about "sysauth", and root cause might be that login page did not show up at all.

usr/lib/lua/luci/dispatcher.lua:460: Failed to execute function dispatcher target for entry '/'. The called action terminated with an exception: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'. A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'. A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/bootstrap/header'. A runtime error occured: [string "/usr/lib/lua/luci/view/themes/bootstrap/hea..."]:150: attempt to index local 'boardinfo' (a nil value) stack traceback: [C]: in function 'assert' /usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

I tried disable the four patches for lighttpd 1.4.45 in 17.01.4, and tried to change http.lua as described in #922, no luck. Something is badly broken.

**Comment by jow-** [comment]
You beed to execute lighttpd as root for LuCI to function
