### ISSUE TITLE
freifunk-wizard isn't creating dhcp-range for wifi-device when told to do so

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#165]
**Reported by reporter on 25 Nov 2010 08:58 UTC**
I'm working with luci-trunk revision 6548.

When I activate the option "WLAN DHCP anbiete" (offer wifi dhcp) in the "Freifunkassistent" (freifunk-wizard) and apply the settings, the dhcp-server is still deactivated under the specific wifi network device ...

**Comment by cshoredaniel** [comment]
Ancient bug report with little information; closing.
