### ISSUE TITLE
Luci Bug on Trunk /usr/lib/lua/luci/model/network.lua:1005

### ISSUE THREAD

**Issue by linuxonlinehelp** [openwrt/luci#1657]
Update today cause ath9k drop issues after 12hours:

System:
OpenWrt SNAPSHOT r6349-9046e92 / LuCI Master (git-18.060.68662-3e17668) 
TP-Link 3600
Log:

Fri Mar  2 14:19:50 2018 daemon.err uhttpd[2409]: The called action terminated with an exception:
Fri Mar  2 14:19:50 2018 daemon.err uhttpd[2409]: /usr/lib/lua/luci/model/network.lua:1005: bad argument #2 to '?' (no value)
Fri Mar  2 14:19:50 2018 daemon.err uhttpd[2409]: stack traceback:
Fri Mar  2 14:19:50 2018 daemon.err uhttpd[2409]:       [C]: in function 'assert'
Fri Mar  2 14:19:50 2018 daemon.err uhttpd[2409]:       /usr/lib/lua/luci/dispatcher.lua:487: in function 'dispatch'
Fri Mar  2 14:19:50 2018 daemon.err uhttpd[2409]:       /usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

Error seen on NETWORK-> INTERFACES  Echo "Collecting ..."

Howto fix?
Thanks

**Comment by jow-** [comment]
Please provide the following SSH command output:
`ubus call network.interface dump`

**Comment by jow-** [comment]
Nevermind, fix pushed.

**Comment by linuxonlinehelp** [comment]
Fri Mar  2 14:53:53 2018 daemon.err uhttpd[2548]: The called action terminated with an exception:
Fri Mar  2 14:53:53 2018 daemon.err uhttpd[2548]: /usr/lib/lua/luci/model/network.lua:1005: bad argument #2 to '?' (no value)
Fri Mar  2 14:53:53 2018 daemon.err uhttpd[2548]: stack traceback:
Fri Mar  2 14:53:53 2018 daemon.err uhttpd[2548]:       [C]: in function 'assert'
Fri Mar  2 14:53:53 2018 daemon.err uhttpd[2548]:       /usr/lib/lua/luci/dispatcher.lua:487: in function 'dispatch'
Fri Mar  2 14:53:53 2018 daemon.err uhttpd[2548]:       /usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

burned latested sysupgrade .. same
OpenWrt SNAPSHOT r6350-175b262328 / LuCI Master (git-18.060.68662-3e17668) 

my mistake?
