### ISSUE TITLE
OpenVPN build with --enable-pkcs11 fails

### ISSUE THREAD

**Issue by Telefonorosso** [openwrt/luci#1663]
## Problem Description
On Lede image builder under Debian i686 with 4.9.0 kernel, if I edit package/network/services/openvpn/Makefile and change

> --disable-pkcs11 to --enable-pkcs11

build fails. The configure script cannot find pkcs11-helper dependency.

## Proposed Resolution
Add the pkcs11-helper software in Lede

## Steps to reproduce
nano [BUILD_DIR]/package/network/services/openvpn/Makefile
make package/openvpn/compile

**Comment by hnyman** [comment]
Wrong repo.
That openvpn package is in the main Openwrt/LEDE sources, not here in the LuCI repo for GUI.

**Comment by Telefonorosso** [comment]
Ok thanks.
Can you provide me the link?
THX

**Comment by hnyman** [comment]
https://bugs.openwrt.org
