### ISSUE TITLE
DHCP Forwarding is not working on all routers

### ISSUE THREAD

**Issue by Richigeht** [openwrt/luci#1665]
Hello!
I have bought four Routers (MiWiFi Router 3) and I installed LibreMesh on them, which basically is LuCi:
Powered by LuCI Master (git-17.350.54625-05c522e) / LiMe develop development (develop rev. 10b4c37 20171216_1829)

Now I have the following two issues:

a) only one Router does provide DHCP forward (=WiFi works) even though all of them have a similar setup
 * disabled DHCP
* connected to LAN not WAN port
* made static routes

b) Mesh is not working?! But that could be a side effect of a)

I am using the following:
10.7.2.11x as addresses for the router
10.7.1.1 is the gateway (and DHCP Server)
Net mask 255.255.0.0

I have setup this on the "Br-lan" /Lan Interface.

I disabled dnsmasq and the firewall but still, only one router gives me proper DHCP and the clients do work.

Any ideas? 
What type of log files should I attach for additional help? Thank you in advance!

**Comment by jow-** [comment]
Please refer to forum.openwrt.org / forum.lede-project.org for configuration questions, this is no LuCI specific issue.
