### ISSUE TITLE
luci-theme-material Firewall label.zonebadge misaligned

### ISSUE THREAD

**Issue by zakaszewski** [openwrt/luci#1667]
Hi all,

first of all I hope that this is the right place to raise an issue regarding the material theme, if not, please let me know where would be appropriate.

I've noticed a little "odd" behaviour of the theme whenever firewall zones are displayed in a selection list:

![image](https://user-images.githubusercontent.com/37077241/37085886-7f88823c-21f6-11e8-8476-9e2912e26159.png)

As You can see the alignment of the "zone background" is slightly off, which appears in both
- network > firewall > [any rule] / [any port forward] and
- network > interfaces > [any interface] > firewall settings.

Other themes (e.g. bootstrap) do not seem to have the same issue, as far as I know.

By the way, I've seen the same behavior on all browsers:
Chrome 65.0.3325.146
Firefox 58.0.2
Internet Explorer 11.0.9600.18920

I know it's a minor issue but it would be much appreciated if it could be fixed.

Best regards,

Piotr

**Comment by dibdot** [comment]
Did you mean like that?

![span_2](https://user-images.githubusercontent.com/8061346/37176089-9b161b60-231b-11e8-80a6-155b0b8f83d4.png)
![span_1](https://user-images.githubusercontent.com/8061346/37176090-9b348dd4-231b-11e8-8964-1c84b5b961eb.png)

**Comment by zakaszewski** [comment]
That would be consistent with how Firewall General settings looks :-)

**Comment by dibdot** [comment]
Patch applied, should be fixed now in trunk.
