### ISSUE TITLE
luci-app-attendedsysupgrade: restart rpcd after installation

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#1668]
when installing the luci app and opening it for the first time the webinterface shows an error as some freshly installed rpcd calls are not yet available. A restart or `rpcd` fixes the problem but causes a user logout. 

Should a `rpcd` restart be added to the `uci-defaults` or is there another way to fix that issue?

**Comment by jow-** [comment]
You can issue a `kill -HUP $(pidof rpcd)` or `/etc/init.d/rpcd reload` to force it to load newly added plugins.

**Comment by aparcar** [comment]
perfect, thank you
