### ISSUE TITLE
Presence of wifi-iface "monitor" removes channel information from wireless page

### ISSUE THREAD

**Issue by jeffsf** [openwrt/luci#1673]
If a monitor wifi-iface is created, the /luci/admin/network/wireless no longer shows the channel for the radio.

With
```
config wifi-iface
	option device 'radio0'
	option mode 'monitor'
	option ifname 'mon24'
```
![image](https://user-images.githubusercontent.com/1946364/37185060-54d960c6-22f3-11e8-88a1-6b51b14eaba7.png)

Without
![image](https://user-images.githubusercontent.com/1946364/37185073-6d5e1ba0-22f3-11e8-9be4-4166eb45ddab.png)

**Comment by jeffsf** [comment]
This is potentially due to or related to what `iw dev` returns when configured with a monitor interface
```
phy#1
[...]
	Interface wlan1-1
		ifindex 29
		wdev 0x100000003
		addr <redacted>
		ssid <redacted>
		type AP
		channel 6 (2437 MHz), width: 20 MHz, center1: 2437 MHz
		txpower 25.00 dBm
	Interface mon24
		ifindex 28
		wdev 0x100000002
		addr <redacted>
		type monitor
		txpower 25.00 dBm
phy#0
	Interface wlan0
[...]
```
There is no "wlan1" and if the monitor interface had not been renamed, it still would have carried no channel information.

Archer C7, LEDE 17.01 branch, Powered by LuCI lede-17.01 branch (git-18.039.58469-1c94003)

**Comment by jow-** [comment]
This is already fixed in master.
