### ISSUE TITLE
How to build luci?

### ISSUE THREAD

**Issue by stokito** [openwrt/luci#1677]
I'm new to this project and README page doesn't contains any instructions about how to build luci, wiki doesn't have it too.
I found some instructions here https://wiki.openwrt.org/doc/howto/build but it looks outdated and complicated for me.
Also I found some instruction here https://github.com/openwrt/luci/wiki/DevelopmentEnvironmentHowTo but they are more about HTML and Lua coding, while I want to build a package.
It would be great if you can update and improve Luci documentation about this aspect.

**Comment by hnyman** [comment]
Luci is the GUI for Openwrt and gets built during the Openwrt build process. It is not meant to be an independent program.
