### ISSUE TITLE
new IP address source [IPv4]

### ISSUE THREAD

**Issue by powergt** [openwrt/luci#1678]
it can be useful add a new IP address source that get my external ip from dns query of myip.opendns.com to opendns server (208.67.222.222)
why?
if wan ip is a private IP i can get my external ip only with request to http://checkip.dyndns.com/
but some time it don't respond.

alternatively 

you could even just add a checkbox that skip the control you're ip my ip is different from that of the ddns

ddns-scripts | 2.7.6-13
luci-app-ddns | 2.4.8-2
luci-i18n-ddns-it | 2.4.8-2

**Comment by jow-** [comment]
@chris5560 ?

**Comment by powergt** [comment]
old request. in the new version there are additional features that solve the problem
