### ISSUE TITLE
assert fail in luci function "dispatch", in dispatcher.lua

### ISSUE THREAD

**Issue by Menion2k** [openwrt/luci#1679]
Hi all
Starting from one LEDE snapshot in February I started to get an assert failure when trying to show my interfaces
The problem is:

`Sun Mar 11 13:02:15 2018 daemon.err uhttpd[2058]: /usr/lib/lua/luci/dispatcher.lua:487: Failed to execute call dispatcher target for entry '/admin/network/iface_status/WAN6,lan,stabridge,tun0,tun1,wwan'.
Sun Mar 11 13:02:15 2018 daemon.err uhttpd[2058]: The called action terminated with an exception:
Sun Mar 11 13:02:15 2018 daemon.err uhttpd[2058]: /usr/lib/lua/luci/model/network.lua:1005: bad argument #2 to '?' (no value)
Sun Mar 11 13:02:15 2018 daemon.err uhttpd[2058]: stack traceback:
Sun Mar 11 13:02:15 2018 daemon.err uhttpd[2058]: 	[C]: in function 'assert'
Sun Mar 11 13:02:15 2018 daemon.err uhttpd[2058]: 	/usr/lib/lua/luci/dispatcher.lua:487: in function 'dispatch'
Sun Mar 11 13:02:15 2018 daemon.err uhttpd[2058]: 	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
`

The network config, which was working perfectly up to LEDE 17.04.4 is:

`config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd73:e37b:9296::/48'

config interface 'lan'
        option type 'bridge'
        option ifname 'eth0'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option ipv6 '0'
        option ipaddr '192.168.183.1'
        option gateway '192.168.182.1'
        option broadcast '192.168.182.255'
        option dns '192.168.182.1'

config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '0 1 2 3 4 5'
        option vid '1'

config interface 'tun0'
        option proto 'none'
        option ifname 'tun0'

config interface 'tun1'
        option proto 'none'
        option ifname 'tun1'

config interface 'wwan'
        option proto 'dhcp'

config interface 'stabridge'
        option proto 'relay'
        option ipaddr '192.168.182.135'
        list network 'lan'
        list network 'wwan'

config interface 'WAN6'
        option proto 'dhcpv6'
        option reqaddress 'try'
        option reqprefix 'auto'
`

Luci version is: git-18.068.60872-bf04031-1

**Comment by jow-** [comment]
This might have been caused by gcc 7 bugs with the MIPS architecture, which caused random Lua failures. If so, it should've been solved since https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=16cec7ae67d9a1e88cb30b45f45596ba753b2afa

Please reopen if you still see this, in this case please attach the output of `ubus call network.interface dump` as well.
