### ISSUE TITLE
luci-app-sqm

### ISSUE THREAD

**Issue by josinaldobarbosa** [openwrt/luci#1739]
the order is reversed

download speed == upload speed
upload speed == download speed

I tested it and found it.

**Comment by hnyman** [comment]
> the order is reversed

No, it is not reversed. 
But you might have selected to wrong interface in your router.

**Comment by josinaldobarbosa** [comment]
interface I know is not wrong because I change the values and they match the set values

**Comment by hnyman** [comment]
they look reversed if you mix wan and lan (and apply SQM to the lan interface)
