### ISSUE TITLE
luci-app-mwan3

### ISSUE THREAD

**Issue by CTRNJH** [openwrt/luci#1740]
Environment: (4.14.32 (git-18.099.19168-b1b5723) / OpenWrt SNAPSHOT r6652-31aaa67)

Clear install
Luci -> Network -> Load Balancing -> Edit\Add interface
Metrik : **500 Internal Server Error**
Sorry, the server encountered an unexpected error.
> /usr/lib/lua/luci/dispatcher.lua:494: Failed to execute arcombine dispatcher target for entry '/admin/network/mwan/interface/wan'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/nsection'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/ucisection'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/dvalue'.
A runtime error occured: /usr/lib/lua/luci/model/cbi/mwan/interfaceconfig.lua:174: attempt to index global 'uci' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:494: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function

**Comment by hnyman** [comment]
@feckert
