### ISSUE TITLE
luci-app-mwan3 №2

### ISSUE THREAD

**Issue by CTRNJH** [openwrt/luci#1743]
Environment: (4.14.32 (git-18.099.52401-edd1fab) / OpenWrt SNAPSHOT r6655-3612d90)
Clear install
~~1) Luci -> Network -> Load Balancing -> Member -> Add (not work)~~
2) Status -> Load Balancing -> Interface
**MWAN Interfaces
No MWAN interfaces found**
~~3) Status -> Load Balancing -> Diagnostics -> ping interface
_/usr/lib/lua/luci/dispatcher.lua:494: Failed to execute call dispatcher target for entry '/admin/status/mwan/diagnostics_display/wan/ping_gateway'.
The called action terminated with an exception:
/usr/lib/lua/luci/controller/mwan3.lua:88: attempt to index global 'uci' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:494: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>_~~

**Comment by dibdot** [comment]
all issues has been addressed in luci master and in package repo with this commit: openwrt/packages#5904
