### ISSUE TITLE
omap platform Flash new firmware image is fail  and not support 

### ISSUE THREAD

**Issue by guhongyeying** [openwrt/luci#1745]
1：i can find  “openwrt/target/linux/x86/base-files/lib/upgrade/platform.sh” and  platform Flash new firmware image is success
2：but  linux omap not find  “openwrt/target/linux/x86/base-files/lib/upgrade/platform.sh” and error"Sorry, there is no sysupgrade support present; a new firmware image must be flashed manually. Please refer to the OpenWrt wiki for device specific install instructions."
3： who can tell me How to do it。

**Comment by dibdot** [comment]
This has nothing to do with LuCI GUI - please check the wiki and/or ask in the forum (https://forum.lede-project.org) for support.

**Comment by guhongyeying** [comment]
1：i can find   linux x86 “openwrt/target/linux/x86/base-files/lib/upgrade/platform.sh” and platform Flash new firmware image is success
2：but linux omap not find “openwrt/target/linux/omap/base-files/lib/upgrade/platform.sh” and error"Sorry, there is no sysupgrade support present; a new firmware image must be flashed manually. Please refer to the OpenWrt wiki for device specific install instructions."
3:why?

**Comment by guhongyeying** [comment]
1 : linux x86   platform Flash new firmware image is success
2 : but linux omap platform Flash new firmware image is fail

**Comment by guhongyeying** [comment]
thanks you @dibdot
