### ISSUE TITLE
Sysupgrade not allowed

### ISSUE THREAD

**Issue by HeadLessHUN** [openwrt/luci#1754]
Today i built an image whit the new luci package and it says that i can't upgrade the image bacause of wrong image type. But i can test and flash via shell sysupgrade command and it is working. So it must be a LuCI issue.

openWRT version: r6719-a656ea0
LuCI version: git-18.108.53693-fc8f825
Router version: xiaomi mi router 3G
`sysupgrade -v /tmp/path-to-sysupgrade-image.tar`

**Comment by jow-** [comment]
Confirmed, this is caused by upload data corruption. Will address this shortly.
