### ISSUE TITLE
updates freifunk-profiles in lede-17.01 branch (cherry-pick from master)

### ISSUE THREAD

**Issue by SvenRoederer** [openwrt/luci#1760]
in 0c30ee07ce70073df639148b48daa08682f3e1d0 an offline DNS-Server was removed from the profiles based on issue  https://github.com/openwrt/luci/issues/1757.
please cherry-pick for lede-17.01 too as it applies cleanly.

**Comment by hnyman** [comment]
backported with 09ae638
