### ISSUE TITLE
Lower Case MAC Addr in Static Leases (luci/admin/network/dhcp)

### ISSUE THREAD

**Issue by VindicatorDS** [openwrt/luci#1772]
Hosts present in /etc/config/dhcp with upper case mac addresses and option name are correctly shown by Luci in luci/admin/network/dhcp under static leases, with the "MAC-Address" column with the format "MAC-Addr (hostname.localdomain)", e.g., "00:26:BF:37:50:76 (switch.mydomain)".

For hosts configured with lower case mac addresses (or a mix of lower and upper case letters), Luci only shows the mac-addr under static leases (MAC-Address column), this is, the (hostname.localdomain) is not shown, e.g., "00:26:bf:37:50:76".

upper-case MAC
![upper-case](https://user-images.githubusercontent.com/37559019/39405051-7deee7c2-4b95-11e8-9998-b2b0efcb5275.png)

lower-case MAC
![lower-case](https://user-images.githubusercontent.com/37559019/39405050-7dc9d86a-4b95-11e8-8e33-c56b043c47e0.png)

I'm using luci git-18.118.21533-00d2429. I don't know if this is a new or an old issue (or a no issue if by design...).

**Comment by jow-** [comment]
There is no commit `00d2429` in the LuCI repository. Where did you obtain your packages from?

**Comment by VindicatorDS** [comment]
Tnx for the fix.

luci git-18.118.21533-00d2429 (https://github.com/openwrt/luci/commit/00d242918f7de007f2a05f102a9660074013293f) was obtained from buildbot build #1188 (https://phase2.builds.lede-project.org/builders/arm_cortex-a9_vfpv3/builds/1188). It accompanied OpenWRT r6775.
