### ISSUE TITLE
Get the response "Bad Gateway" while accessing web server

### ISSUE THREAD

**Issue by garywangcn** [openwrt/luci#1784]
I compiled Openwrt with the latest luci code, the configuration for LUCI module is below:

> CONFIG_PACKAGE_liblucihttp=y
> CONFIG_PACKAGE_liblucihttp-lua=y
> CONFIG_PACKAGE_luci=y
> CONFIG_PACKAGE_luci-ssl-openssl=y
> CONFIG_PACKAGE_luci-base=y
> CONFIG_PACKAGE_luci-mod-admin-full=y
> CONFIG_PACKAGE_luci-app-ddns=y
> CONFIG_PACKAGE_luci-app-firewall=y
> CONFIG_PACKAGE_luci-app-lxc=y
> CONFIG_PACKAGE_luci-app-qos=y
> CONFIG_PACKAGE_luci-theme-bootstrap=y
> CONFIG_PACKAGE_luci-theme-openwrt=y
> CONFIG_PACKAGE_luci-proto-ipv6=y
> CONFIG_PACKAGE_luci-proto-ppp=y
> CONFIG_PACKAGE_luci-lib-httpclient=y
> CONFIG_PACKAGE_luci-lib-httpprotoutils=y
> CONFIG_PACKAGE_luci-lib-ip=y
> CONFIG_PACKAGE_luci-lib-jsonc=y
> CONFIG_PACKAGE_luci-lib-nixio=y
> 

But when I program image to target and access it via chrome(https://192.168.1.1/cgi-bin/luci), get the follow information:
    Bad Gateway
    The process did not produce any response

Does someone encounter this issue? Is there a way to see what problem happens?

**Comment by cdbierl** [comment]
Yeah I have the same behavior. I see nothing in the logs to explain why though.

**Comment by garywangcn** [comment]
Please see this link https://github.com/jow-/lucihttp/issues/1  to get more information.
