### ISSUE TITLE
Clarification on luci.http.write in 'Teaching your new child (Actions)'

### ISSUE THREAD

**Issue by iggirex** [openwrt/luci#1788]
The first example for writing a module is working for me as far as the machine rebooting when the url <node_ip_address>/click/here/now.

However in this module there is a command I find confusing:
` luci.http.write("Haha, rebooting now...")`

I don't see this message being printed out anywhere. I kindof expected it to be on the browser, or inspector tools console, or even on the terminal that is SSH'd into the node. I can't find this message anywhere though, and the documentation for luci.http.write says:

"Send a chunk of content data to the client. This function is as a valid LTN12 sink. If the content chunk is nil this function will automatically invoke close."

This part of documentation I find confusing, I'm not sure if the client is the browser or SSH connection, either way I'm not seeing this message anywhere. Maybe it would be good to make a mention of where to find this?

**Comment by dibdot** [comment]
Not a LuCI issue at all, please contact the forum - best with a meaningful code snippet.
