### ISSUE TITLE
luci-mod-admin-mini - someone to fix it for "tiny" flash routers 4MB flahs?

### ISSUE THREAD

**Issue by tcolov** [openwrt/luci#1790]
Hi,

Can someone fine luci-mod-admin-mini to work on 4MB "tiny" flash routers?
The mod-admin-full cannot be installed on 4MB flash routers and they are the most popular and cheapest :(

Br,
Todor Colov

**Comment by tcolov** [comment]
It is putty, because the original firmwares has WEB interface. 
For the stripped down mini version - network & wifi config are enough ( for dummy wifi users ). 
The hope came when I downloaded recently the Luci sources - luci-mod-admin-mini is there but "broken" and in the past openwrt versions it was working, hoped someone can fix it. ( a lot of devices have 4MB flash and they are the cheapest )

May be some of the LUCI libraries for basic wifi & network functionality are not needed and can be modularized to be optional.

**Comment by kofec** [comment]
You just need to compile the image for you router by yourself.  There is a lot about on wiki and forum. 
e.g:
https://openwrt.org/docs/guide-user/additional-software/imagebuilder
https://forum.lede-project.org/t/minimum-lite-firmware-for-tplink-mr1xu-mr3xxx-wa7xx-wa8xx-wa901nd-wa7x10n-wr7xxn-wr8xxn-wr9xxnd-wr1041n-netgear-wnr612-wnr1000-wnr2000-wpn824n-4m-flash-only/11018/2
