### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by junland** [openwrt/luci#1799]
Looks like Bootstrap 3 is no longer [maintained](https://github.com/twbs/bootstrap/issues/20631) is there any chance that `luci` will move to Bootstrap 4 anytime soon?

**Comment by jow-** [comment]
Given that the current boostrap theme does not exactly use a vanilla Bootstrap 3 either, I'd say the chances are rather slim for the moment. At least no immediate switch to Bootstrap 4 is planned.
