### ISSUE TITLE
Help with uwsgi

### ISSUE THREAD

**Issue by Ansuel** [openwrt/luci#1807]
Hello i'm trying to make luci work with uwsgi... I'm very close to make it work as it does load all pages, does login, logout...

Only problem, it doesn't load dynamic page...

All the json request gives data
(for example /?hosts=1&_=0.12960415287504623 )  but the overview page doesn't update

Strangely in the overview page only the ddns part receive the data... others part stay in Collecting data...

So the problem it's just in the Collecting data... process as all other things work....

@jow-  sorry if I ask again, but do you know what can cause this?

**Comment by jow-** [comment]
I don't have any idea, sorry. Check the chrome debugger and see if XHR requests work properly, return the correct headers etc.

**Comment by jow-** [comment]
In particular ensure that the JSON data responses return with `Content-Type: application/json`

**Comment by Ansuel** [comment]
it's strange as ddns goes and others doesn't....

**Comment by Ansuel** [comment]
ok looks like the request got cancelled...  some timeout?

**Comment by jow-** [comment]
I don't know, sorry. Maybe your fcgi wrapper is not terminating connections

**Comment by Ansuel** [comment]
request end in exactly 5 seconds.... do you know any timeout present in luci script? (that is more in ddns script?)

**Comment by jow-** [comment]
5s just happens to be the default poll interval. If the next poll is due and the previous XHR did not return yet, it is cancelled. This leads me to believe that your uwsgi handler is not properly closing the HTTP connection, causing the XHR request to never complete. The DDNS status uses a larger poll interval of 15s, maybe this works because the connection timed out in the meanwhile.

**Comment by Ansuel** [comment]
actually uwsgi is pretty slow to take data (for now i need to see what is causing this slowness...) 

he needs at least 10000 ms to process data... so increase the poll intervall is the solution to see if all is working

**Comment by Ansuel** [comment]
yes, by increasing the pool to 15 second the page gets the right data... thx a lot for the hint...

now i need to underestand why he needs 10 second to process the cgi script...
