### ISSUE TITLE
Configuration not saved after reboot

### ISSUE THREAD

**Issue by rbncha** [openwrt/luci#1812]
Hi,

I installed OpenWrt on NanoStation Loco M2. The configuration is not saved after the device is rebooted or powered off and on again.

I will be very thankful to you if anyone can suggest me what to do.

Thank you

**Comment by juppin** [comment]
Did you installed wirh a initram image?
And probably have you also flashed the initram image?

If both questions are true... -> do a sysupgrade with a image named XXX-sysupgrade.bin

**Comment by jow-** [comment]
Either wrong image flashed or out of space on rootfs, nothing that can be fixed in LuCI.
