### ISSUE TITLE
luci-app-openvpn - kicks proto var

### ISSUE THREAD

**Issue by ThomasCr** [openwrt/luci#1842]
Hi,

I tested the current 18.06-SNAPSHOT, r6917-8948a78 build. I noticed painfully, that when I save something on the WebGUI for OpenVPN, that it kicks out my “proto”-Var.

**Comment by dibdot** [comment]
I don't understand your issue. Could you please explain your problem in detail? Thanks.

**Comment by dibdot** [comment]
No more feedback - close this for now.
