### ISSUE TITLE
500 error when i update luci  (libuci-lua, uci)

### ISSUE THREAD

**Issue by reusu** [openwrt/luci#1848]
i build a service name test
and after i update luci to release
the page show 500 error like this:

Failed to execute cbi dispatcher target for entry '/admin/services/test'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:889: attempt to call method 'rollback_pending' (a nil value)
stack traceback:
	/usr/lib/lua/luci/dispatcher.lua:889: in function 

in file /usr/lib/lua/luci/model/cbi/test.lua 
i require a module name testex
>local testex= require("testex")

then in file /usr/lib/lua/testex.lua
if i delete this line
>local uci		= require("uci")

there's no error but i can't use uci get config value
if i use 
>local uci		= require("luci.model.uci")

there's another error like this:

Failed to execute cbi dispatcher target for entry '/admin/services/test'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/uci.lua:284: attempt to call method 'get_all' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/uci.lua:284: in function </usr/lib/lua/luci/model/uci.lua:266>
	(tail call): ?
	/usr/lib/lua/test.lua:18: in function 'tconf'
	/usr/lib/lua/test.lua:28: in function 'info'
	/usr/lib/lua/luci/model/cbi/test.lua:60: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:831: in function </usr/lib/lua/luci/dispatcher.lua:825>

>--Function
function tconf(name)
	local tval = uci.get("test","config", name)
	if tval ~= nil then
		return tval
	else
		return ""
	end
end

i was use require uci.so and work fine in old version luci
>local uci		= require("uci")

so what can i do to fix this problem

**Comment by reusu** [comment]
i will also run this testex.lua separately, so
>--Require
local io        = require("io")
local table     = require("table")
local split     = require("split")
local string    = require("string")
local cjson     = require("cjson")
local uci		= require("uci")
local luci      = {}
luci.sys        = require("luci.sys")
local tonumber, ipairs, pairs, pcall, type, next, setmetatable, require, select, tostring=
	tonumber, ipairs, pairs, pcall, type, next, setmetatable, require, select, tostring

**Comment by reusu** [comment]
why cant use libuci-lua now?
I use it for the time being

>local ucis		= require("luci.model.uci").cursor()
--Function
function tconf(name)
	local tval = ucis:get("test","config", name)
	if tval ~= nil then
		return tval
	else
		return ""
	end
end

**Comment by hnyman** [comment]
> i build a service name test
> and after i update luci to release
> the page show 500 error like this:

What release?
You forgot to tell which version of LuCI you are talking about. There are currently differences between 17.01, 18.06 and master. Based on some error messages, you are likely using master, right?

> why cant use libuci-lua now?

Based on recent commits, @jow- has been making changes to remove/decrease the usage of libuci-lua as it will likely be removed at some point.

See the commits and read the comments in them:
https://github.com/openwrt/luci/search?q=libuci-lua&type=Commits

**Comment by jow-** [comment]
You need to use colon notation when interfacing with luci.model.uci nowadays, the dot notation is not supported anymore, so instead of `uci.get("test","config", name)` use `uci:get("test","config", name)`.
