### ISSUE TITLE
Dummy wireless interface is created by clicking on ADD button without saving it.

### ISSUE THREAD

**Issue by vsaichandra** [openwrt/luci#1869]
HI,

In NETWORK -> WIFI, Clicking on ADD button is creating a dummy wireless interface when it is not saved.

Steps:
1. Click on ADD button.
2. go back to the earlier screen by clicking on WIFI option again.
3. You can see the dummy wireless interface.

Thank you!

**Comment by jow-** [comment]
Yes, this has always been the case and solving that is not trivial. The simplest mitigation is to simply not do it :)

**Comment by vsaichandra** [comment]
Can i get any support on this ?

Thanks.

**Comment by jow-** [comment]
At the moment, no. Solving this requires some extensive rework of how section creations are handled in cbi.

**Comment by jow-** [comment]
Not happening anymore in 19.07 / master
