### ISSUE TITLE
libiwinfo-lua package is not installed

### ISSUE THREAD

**Issue by hadig** [openwrt/luci#1890]
Hi,
im on ASUS RT-n56u, istalled latest snapshot but i cant find libiwinfo-lua package anywhere. without it my wifi is not working.

packages for my device(but no libiwinfo-lua)
https://downloads.lede-project.org/releases/packages-18.06/mipsel_74kc/

![unbenannt](https://user-images.githubusercontent.com/4592275/41511693-2b5e83ec-727c-11e8-9ae7-0d348662d8f3.PNG)

**Comment by jow-** [comment]
https://downloads.lede-project.org/snapshots/targets/ramips/rt3883/packages/libiwinfo-lua_2018-05-18-e59f9253-1_mipsel_74kc.ipk
