### ISSUE TITLE
ds-wan6_4 gets created and used by default while native IPv4 is available

### ISSUE THREAD

**Issue by TheB1gG** [openwrt/luci#1898]
Version: Powered by LuCI 526a8767846acbe57c521912b35feb4d97354db6 branch (git-18.145.30016-526a876) / OpenWrt omnia 15.05 r47055

Device: Turris Omnia

The Router is connected to a modem from which it gets a /56 via prefix delegation and a IPv4 address. Even though native IPv4 is available it creates than the ds-wan6_4 interface, which is fine for me but my problem is that you can't reach any device behind the router via the native IPv4 in this constellation which is a problem in non dual stack enviroments from which you try to reach a service hosted behind the turris omnia.

You can reproduce it with a KabelBW Dual-Stack internet connection and a TC4400 as modem and a default openwrt installation with the ds-lite package installed.

As workaround i have to connect to the turris omnia and click on the native IPv4 connection on reconnect so it gets the default gateway.

If you need logs or anything else please discribe or link me a info how i get the information you need and i will provide it.

Thank you for looking at this

**Comment by jow-** [comment]
This is not a LuCI issue. Please report it at https://bugs.openwrt.org/
