### ISSUE TITLE
package sizes in packagemanagement

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#19]
**Reported by kloschi on 2 Jan 2009 17:42 UTC**
would be great to see the download size of the packages and the estimated install size. 

additionally would be great to see free space and have limitation or warning when reaching available amount of space.

**Comment by ngbatnicdotmil** [comment]
:+1:

**Comment by hnyman** [comment]
I got interested in this and filed a patch for opkg to optionally display the package size (of *.ipk):
https://lists.openwrt.org/pipermail/openwrt-devel/2015-August/035480.html
https://patchwork.ozlabs.org/patch/512231/

**Comment by hnyman** [comment]
I have pushed locally a patch (https://github.com/hnyman/luci/commit/f5ba1e6bbcb1920774195fb0eec366499a267c6e) to show the package size in Luci. If my patch to Openwrt opkg gets accepted, I may push this also to Luci.

Below is a screenshot of the package size data in Luci:

![opkg-size](https://cloud.githubusercontent.com/assets/7926856/9581673/757b920a-5009-11e5-8aa3-2f88864436d5.PNG)

**Comment by thess** [comment]
@hnyman - this is something I always wished was there. Super job!

**Comment by hnyman** [comment]
This has been implemented for the download size information
 in trunk 'opkg' by https://dev.openwrt.org/changeset/46980 and
 in Luci by https://github.com/openwrt/luci/commit/3288fe76ab3d2269abcf902d0df6f847c6200e8e

There is no possibility of getting information on the estimated install size.

**Comment by hnyman** [comment]
This is also available in CC15.05 since today:
in Openwrt: https://dev.openwrt.org/changeset/47196
in Luci: https://github.com/openwrt/luci/commit/ce5c787989701eb406162fa467e43f034cbbf292
