### ISSUE TITLE
luci-app-ddns utilizes Old Wiki Links

### ISSUE THREAD

**Issue by lleachii** [openwrt/luci#1903]
Reported by : OxR463 on forum.lede-project.org

https://forum.lede-project.org/t/applications-luci-app-ddns-opennic-integration/15867

`
applications/luci-app-ddns.`

> Also, that package has several references to the old wiki.
> It would be nice to get those updated to the new site.

Old Wiki links appear:
```

Dynamic DNS allows that your router can be reached with a fixed hostname while having a dynamically changing IP address.
OpenWrt Wiki: DDNS Client Documentation --- DDNS Client Configuration
```
Links to:

http://wiki.openwrt.org/doc/howto/ddns.client
and
http://wiki.openwrt.org/doc/uci/ddns

Change to:

https://openwrt.org/docs/guide-user/services/ddns/client (FYI, there is also a "to merge" page that exists on the new WIki)
and
https://openwrt.org/docs/guide-user/base-system/ddns

**Comment by Ansuel** [comment]
Fixed the referenced pr

**Comment by oxr463** [comment]
Looks like we can close this, (Yes, I created a GitHub account).
