### ISSUE TITLE
Incorrect average calculation in luci/view/admin_status/bandwidth.htm

### ISSUE THREAD

**Issue by mgalyean** [openwrt/luci#1908]
The calculation of the bandwidth average incorrectly weights the current value as 1/2 the average instead of 1/Nth the average.  The average should be calculated by adding all values in the 3 minute window, then at end of loop dividing by the number of values

[bandwidth.htm.diff.txt](https://github.com/openwrt/luci/files/2131428/bandwidth.htm.diff.txt)

**Comment by jow-** [comment]
Merged, thanks!
