### ISSUE TITLE
Failed with lucihttp newest luci

### ISSUE THREAD

**Issue by quachhung94** [openwrt/luci#1909]
I build newest luci with make package/luci/{clean,prepare,compile} V=s then had this error message

make[2]: Leaving directory `/opt/build/iap_qsdk5.3/qsdk/qca/feeds/luci/libs/luci-lib-jsonc'
make[2]: Entering directory `/opt/build/iap_qsdk5.3/qsdk/qca/feeds/luci/libs/luci-lib-nixio'
if [ -f /opt/build/iap_qsdk5.3/qsdk/staging_dir/target-arm_cortex-a7_musl-1.1.9_eabi/pkginfo/luci-lib-nixio.default.install.clean ]; then rm -f /opt/build/iap_qsdk5.3/qsdk/staging_dir/target-arm_cortex-a7_musl-1.1.9_eabi/pkginfo/luci-lib-nixio.default.install /opt/build/iap_qsdk5.3/qsdk/staging_dir/target-arm_cortex-a7_musl-1.1.9_eabi/pkginfo/luci-lib-nixio.default.install.clean; fi; echo "luci-lib-nixio" >> /opt/build/iap_qsdk5.3/qsdk/staging_dir/target-arm_cortex-a7_musl-1.1.9_eabi/pkginfo/luci-lib-nixio.default.install
make[2]: Leaving directory `/opt/build/iap_qsdk5.3/qsdk/qca/feeds/luci/libs/luci-lib-nixio'
make[2]: Entering directory `/opt/build/iap_qsdk5.3/qsdk/qca/feeds/luci/contrib/package/lucihttp'
Makefile:53: *** Download/default is missing the FILE field..  Stop.
make[2]: Leaving directory `/opt/build/iap_qsdk5.3/qsdk/qca/feeds/luci/contrib/package/lucihttp'
make[1]: *** [package/feeds/luci/lucihttp/compile] Error 2
make[1]: Leaving directory `/opt/build/iap_qsdk5.3/qsdk'
make: *** [package/luci/compile] Error 2

Can anyone help ?
Thanks in advance ...

**Comment by jow-** [comment]
This is a QSDK specific problem, maybe you forgot to install the lucihttp package.
