### ISSUE TITLE
is it feasable to make it run for regular linux distro?

### ISSUE THREAD

**Issue by mailinglists35** [openwrt/luci#1911]
sorry for abusing the issue tracker to ask a question: is it possible to build luci on a regular distro, like ubuntu or fedora? 
I'd like to use it solely as a web frontend for dnsmasq + /etc/ethers + /etc/hosts
thank you

**Comment by jow-** [comment]
This is not really feasible. LuCI heavily relies on OpenWrt specific userland services to function. A standard Linux distro will not offer the APIs required for that.
