### ISSUE TITLE
luci-app-ddns: does not correctly determine that bind-host is installed et al

### ISSUE THREAD

**Issue by pleasantone** [openwrt/luci#1914]
https://github.com/openwrt/luci/blob/660e4f5504b91a7b5c51a6abb80d52c65b8528d2/applications/luci-app-ddns/luasrc/tools/ddns.lua#L116

Line 116 has a typo -- "type" not "tyep"

@Ansuel

**Comment by Ansuel** [comment]
will fix this and another problem when anothe pr gets merged

**Comment by pleasantone** [comment]
Pull request #1928

**Comment by yangfl** [comment]
fixed in #2029

**Comment by feckert** [comment]
Should be fixed
