### ISSUE TITLE
changing ip of lan interface does not work

### ISSUE THREAD

**Issue by juppin** [openwrt/luci#1916]
Hello devs,

two users reported that if they change there ip address of the lan interface, it does not work due to a timeout of the web interface.
After that, a connection to the web interface or over ssh isn´t possible until they restart the router.
After a restart the router is reachable over his previous configured ip.
The issue was reported on [lede-project forum](https://forum.lede-project.org/t/ath79-fully-working-builds-with-all-kmod-packages-through-opkg-flow-offloading/15897/31)

I think it has something to do with the new auto revert feature if something went wrong and that the web interface did not redirect to the new ip.

Sorry for my bad english :-)

**Comment by jow-** [comment]
The web interface never did redirect to the new IP, users need to reopen it at the new IP themselves. This didn't change with the auto revert.
