### ISSUE TITLE
luci-app-mwan3: incorrect warnings with ipv6 wan interfaces

### ISSUE THREAD

**Issue by pleasantone** [openwrt/luci#1917]
If you configure interface arises like wan6 and wanb6 per the standard convention (so we can run both udhcpc and odhcpc), we get warnings about duplicate interfaces and metrics.

@feckert

**Comment by pleasantone** [comment]
![e8eca7a5-5ed2-48a3-b07b-3c22df78caa6](https://user-images.githubusercontent.com/5339793/42061554-783ceb0c-7adf-11e8-9557-1a02c61e152e.png)

**Comment by pleasantone** [comment]
@feckert

**Comment by pleasantone** [comment]
```
config interface 'wan_cc'
        option ifname 'eth0.10'
        option proto 'dhcp'
        option metric '120'

config interface 'wan_cc6'
        option ifname '@wan_cc'
        option proto 'dhcpv6'
        option reqaddress 'try'
        option metric '120'
        option reqprefix '60'

config interface 'wan_mb'
        option ifname 'eth0.11'
        option proto 'dhcp'
        option metric '110'

config interface 'wan_mb6'
        option ifname '@wan_mb'
        option proto 'dhcpv6'
        option reqaddress 'try'
        option metric '110'
        option reqprefix 'auto'
```

**Comment by feckert** [comment]
@pleasantone 
Yes i have not known that the ifname could also be related with the *@* option. In the source i am iterating over the interfaces and if i found an equal metric luci-app-mwan3 shows the warning.
I have no hotfix for this now. I have to think about how to solve this problem.

**Comment by feckert** [comment]
Duplicate https://github.com/openwrt/luci/issues/4603
