### ISSUE TITLE
DNS and Route gets deleted after save and apply is pressed in luci-app-ocserv

### ISSUE THREAD

**Issue by Boysa22** [openwrt/luci#1922]
OpenWrt 18.06.0-rc1 r7090-d2aa3a1b62
LuCI openwrt-18.06 branch (git-18.163.60998-c379f00) 

Installed ocserv and luci-app-ocserv. After the configuration I pressed the button "Save and Apply". The fields with DNS and Routes get empty after that. If I enter some data and press again "Save and Apply" the new data is not taken, the fields stay empty. The DNS and Routes data is also deleted from /etc/config/ocserv which breaks the OpenConnect functionality.

**Comment by dibdot** [comment]
Probably related to #1904

**Comment by jow-** [comment]
Fixed by https://github.com/openwrt/luci/commit/80cb4fef8c7db0dadc373fef122d7abb092a7191
