### ISSUE TITLE
If user forget the luci password, how can he login ?

### ISSUE THREAD

**Issue by vsaichandra** [openwrt/luci#1926]
Hi,

In LUCI login page, user is not given "forgot password" option.

If the user forgets the password, what is the solution for him to recover the password?

Thank you.

**Comment by yousong** [comment]
I am not aware of the existence of such an entry in the web page.  It's possible that he can reset the password in failsafe mode, which requires physical access to the device.

**Comment by jow-** [comment]
The user needs to utilize OpenWrt's various failsafe mechanisms to recover. Either failsafe shell access or press reset for 30s. Please direct such questions to the OpenWrt/LEDE forum, this issue tracker is no support channel.
