### ISSUE TITLE
Query on firmware flashing

### ISSUE THREAD

**Issue by joewander** [openwrt/luci#1927]
Hi,

I am new to LUCI and first time working on Lua and MVC architecture.

I am trying to understand the firmware flashing procedure.
- I wanted to enable/disable a button in backup/flash (flashops.htm) page, depending on the response in a boolean variable in Lua file. (system.lua)

Any ideas to do it?

Thank you.

**Comment by jow-** [comment]
Template context variables are passed through a dictionary as 2nd argument to `luci.template.render()`. See the existing examples in `system.lua`.
