### ISSUE TITLE
cbi/tblsection with luci-theme-material: headline will be repeated for every "table" entry

### ISSUE THREAD

**Issue by dibdot** [openwrt/luci#1934]
@jow- just noticed this oddity with material theme, maybe this is a known issue ...

View with bootstrap & openwrt theme:
![tblsection_openwrt](https://user-images.githubusercontent.com/8061346/42268550-1a5cb03e-7f7c-11e8-801f-eee1e1ca30d9.png)

Same view with material theme:
![tblsection_material](https://user-images.githubusercontent.com/8061346/42268621-47e30864-7f7c-11e8-9629-7ce69cb14435.png)

**Comment by jow-** [comment]
Should be fixed with 9651be295355acf1c22157b00c86a7d5680eb2a5
