### ISSUE TITLE
Nanostation PoE passthrough

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#194]
**Reported by reporter on 11 Feb 2011 21:21 UTC**
Hi guys,
## i've successfully tested the PoE-passthrough function on NS M2 from UBNT with following commands:

echo 8 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio8/direction
echo 1 > /sys/class/gpio/gpio8/value # PoE on secondary port = on
echo 0 > /sys/class/gpio/gpio8/value # PoE on secondary port = off

Would be great when we could implement it in LuCI. My Opp. is, that it would fit to the System-Settings.

Tnx
JoeSemler, 0xFF-Vienna

**Comment by hnyman** [comment]
closing this 6-year old feature request
