### ISSUE TITLE
Adding a hostname does not restart dnsmasq

### ISSUE THREAD

**Issue by austinbutler** [openwrt/luci#1943]
I found https://github.com/openwrt/luci/issues/453, but it was closed saying it should be resolved.

This still happens for me on `LuCI lede-17.01 branch (git-17.315.61305-a9bddc4)`, I have to go in and restart manually with `/etc/init.d/dnsmasq restart`.

**Comment by dibdot** [comment]
Works for me. Please re-test with current snapshots or at least with 18.06 branch. In any case this is not a LuCI issue.

**Comment by austinbutler** [comment]
@dibdot would you mind letting me know which project would be responsible if I test and find the same issue with 18.06?

**Comment by dibdot** [comment]
dnsmasq is an openwrt core package and the issue tracker is here: https://bugs.openwrt.org

Quickly checked the gitlog of and found the relevant commit ;-)

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=4f02285d8b4a66359a8fa46f22a3efde391b5419

So, this will be fixed in 18.06.
