### ISSUE TITLE
Luci Interface Status showing incorrect ipv6 subnet size, 18.06.0-rc1

### ISSUE THREAD

**Issue by grandeviking** [openwrt/luci#1947]
In Openwrt 18.06.0-rc1 (WNDR3800 and Generic x86-64 images) in the interface status, the prefix size for ip addresses delegated to LAN interfaces is incorrect. It shows /64 even when they've been delegated a /60 prefix. This can be confirmed with ifconfig and prefixes can be delegated to LAN clients, which shouldn't be possible if the LAN interface only has a /64.

I did not observe this behaviour on 17.01.4, it correctly the shows /60 prefixes.

![wndr3800-1](https://user-images.githubusercontent.com/41167431/42702644-59141e18-8687-11e8-9491-e82f0fd9af52.PNG)
![wndr3800-2](https://user-images.githubusercontent.com/41167431/42702645-592c49ca-8687-11e8-8a42-0c5e00f955f0.PNG)
![x86-64-1](https://user-images.githubusercontent.com/41167431/42702646-593ff628-8687-11e8-98b9-64b41e0ffe09.PNG)
![x86-64-2](https://user-images.githubusercontent.com/41167431/42702647-59530f60-8687-11e8-87e8-2e0fcf72d827.PNG)
![x86-64-3](https://user-images.githubusercontent.com/41167431/42702648-5966cb90-8687-11e8-9716-1f942807bf60.PNG)

**Comment by jow-** [comment]
Please provide the output `ubus call network.interface dump`

**Comment by grandeviking** [comment]
# ubus call network.interface dump
{
        "interface": [
                {
                        "interface": "lan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 66,
                        "l3_device": "br-lan",
                        "proto": "static",
                        "device": "br-lan",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "172.21.1.1",
                                        "mask": 24
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [
                                {
                                        "address": "2604:3d09:7680:400::",
                                        "mask": 56,
                                        "preferred": 3469,
                                        "valid": 3469,
                                        "local-address": {
                                                "address": "2604:3d09:7680:400::",
                                                "mask": 64
                                        }
                                },
                                {
                                        "address": "fc15::",
                                        "mask": 56,
                                        "local-address": {
                                                "address": "fc15::",
                                                "mask": 64
                                        }
                                }
                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "loopback",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 66,
                        "l3_device": "lo",
                        "proto": "static",
                        "device": "lo",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "127.0.0.1",
                                        "mask": 8
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "wan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 63,
                        "l3_device": "eth1",
                        "proto": "dhcp",
                        "device": "eth1",
                        "updated": [
                                "addresses",
                                "routes",
                                "data"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "68.149.58.245",
                                        "mask": 22
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [
                                {
                                        "target": "0.0.0.0",
                                        "mask": 0,
                                        "nexthop": "68.149.56.1",
                                        "source": "68.149.58.245\/32"
                                }
                        ],
                        "dns-server": [
                                "64.59.184.17",
                                "64.59.191.229"
                        ],
                        "dns-search": [
                                "ed.shawcable.net"
                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {
                                "hostname": "S01062cb05d9c78f3",
                                "leasetime": 3476
                        }
                },
                {
                        "interface": "wan6",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 61,
                        "l3_device": "eth1",
                        "proto": "dhcpv6",
                        "device": "eth1",
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [

                        ],
                        "ipv6-address": [
                                {
                                        "address": "2604:3d08:3:16:c829:9e6c:d8f:344f",
                                        "mask": 128,
                                        "preferred": 3469,
                                        "valid": 3469
                                }
                        ],
                        "ipv6-prefix": [
                                {
                                        "address": "2604:3d09:7680:400::",
                                        "mask": 56,
                                        "preferred": 3469,
                                        "valid": 3469,
                                        "class": "wan6",
                                        "assigned": {
                                                "lan": {
                                                        "address": "2604:3d09:7680:400::",
                                                        "mask": 56
                                                }
                                        }
                                }
                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [
                                {
                                        "target": "::",
                                        "mask": 0,
                                        "nexthop": "fe80::201:5cff:fe89:ce46",
                                        "metric": 512,
                                        "valid": 1790,
                                        "source": "2604:3d09:7680:400::\/56"
                                },
                                {
                                        "target": "::",
                                        "mask": 0,
                                        "nexthop": "fe80::201:5cff:fe89:ce46",
                                        "metric": 512,
                                        "valid": 1790,
                                        "source": "2604:3d08:3:16:c829:9e6c:d8f:344f\/128"
                                }
                        ],
                        "dns-server": [
                                "2001:4e8:0:4004::11",
                                "2001:4e8:0:4005::11"
                        ],
                        "dns-search": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ]
                        },
                        "data": {
                                "passthru": "00170020200104e8000040040000000000000011200104e8000040050000000000000011"
                        }
                }
        ]
}

**Comment by jow-** [comment]
Note that LuCI reports the "local-address" attribute of the downstream interfaces as "IPv6", it does not report the actually delegated portion of the available PD pool.

Apparently the information in ubus does not match the configuration performed by netifd, this is a bu that needs to be fixed on the OpenWrt side.

**Comment by jow-** [comment]
This has been fixed on the OpenWrt side within netifd.
