### ISSUE TITLE
NGINX File dependency error

### ISSUE THREAD

**Issue by fuqiang03** [openwrt/luci#1948]
![qq 20180714132914](https://user-images.githubusercontent.com/26851715/42721252-3dc96ea4-876a-11e8-8463-1ada419e2bc5.png)
![qq 20180714132933](https://user-images.githubusercontent.com/26851715/42721253-42a81286-876a-11e8-9a85-06e0b74cadd7.png)

**Comment by build000** [comment]
@hnyman

**Comment by Ansuel** [comment]
are you sure you have updated the package feeds?

**Comment by build000** [comment]
Situation to openwrt-18.06...no master.
Yes - updated feeds

**Comment by Ansuel** [comment]
openwrt-18.06 doesn't have the new changes to nginx... think that's the problem...
instead luci have the new package....

(so i think luci package should be dropped or nginx changes should be pushed upstream)

**Comment by build000** [comment]
... well ... there is no change for 18.06...

**Comment by jow-** [comment]
https://github.com/openwrt/luci/commit/14c73faf313a85f9a70b21b1afd84a47e28a93c0

**Comment by rossiniscarface** [comment]
Looks like in the 18.06-snapshots there are still luci-nginx and luck-nginx-ssl packages built.
https://downloads.openwrt.org/releases/18.06-SNAPSHOT/packages/arm_cortex-a5_neon-vfpv4/luci/luci-nginx_git-18.201.34715-c813598-1_all.ipk

**Comment by hnyman** [comment]
> Looks like in the 18.06-snapshots there are still luci-nginx and luck-nginx-ssl packages built.

They are not built any more, but the old binaries have not been deleted.
@jow-
