### ISSUE TITLE
Consider adding IPv6 tunnel info to the new Status page

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#196]
**Reported by reporter on 12 Feb 2011 08:57 UTC**
The new Status front page looks nice. Thanks.

You might consider including 6in4 or 6to4 tunnel info in the IPv6 Wan section info. Currently it does not seem to count 6in4 tunnels as proper Wan interfaces, so info about them is not shown in the status page. IPv4 Wan info is shown correctly, but IPv6 is just shown as "Not connected".

For most users, the various tunnels will probably be the main IPv6 Wan connection form in the next few months. So, info about them would be nice.

**Comment by zagosch** [comment]
I've recently updated from Attitude Adjustment to BarrierBreaker. I use an sixxs ipv6 tunnel to access IPv6 networks. But my WAN IPv6 Status gives the status "Not connected", in Attitude Adjustment I didn't have this problem.

**Comment by hnyman** [comment]
I have originally reported this in 2011, and I feel that it has been fixed already. to large enough extent
