### ISSUE TITLE
Lede logo on the new 18.06-rc2 firmware

### ISSUE THREAD

**Issue by skipik** [openwrt/luci#1960]
Hey guys!

Just made a sysupgrade from lede-17.01 to openwrt-18.06. Noticed that LuCI still shows "Lede" instead of "OpenWRT". Is it due to sysupgrade and may be I should make a clean installation without "keep conf files" option? Or is it by design and will be fixed in future?

http://jpegshare.net/79/ff/79ff0fe760b235155ce57f1b94776c69.png.html

Thanks!

**Comment by hnyman** [comment]
That is not logo, but the name of the router that you have set in /etc/config/system
That config file has been kept in sysupgrade, so it shows the previous default.
