### ISSUE TITLE
17.01.5 - network.dsl.ds_snr_offset

### ISSUE THREAD

**Issue by bill888uk** [openwrt/luci#1963]
LEDE 17.01.5 includes these two commits:

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=dea8979a81d72eac79321f1f3bf72fb5244275b6

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=541a1a7ff5ce9ef7a5660e483635ecd0892137dc

Would it be possible to update LuCI so it can manage the 'Downstream SNR offset' in 17.01.5 ?
(This can be managed with LuCI in snapshots and 18.06.0-xx)

**Comment by jow-** [comment]
Backported with 87a74eedc, 46b9d83d9, 6d349c5f7 and 7bf036750
