### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by mochou90** [openwrt/luci#1966]
Access Violation
The page at 'admin/network/network/' has no parent node so the access to this location has been denied.
This is a software bug, please report this message at https://github.com/openwrt/luci/issues
stack traceback:
	[C]: in function 'assert'
	?: in function 'dispatch'
	?: in function <?:140>

**Comment by jow-** [comment]
Can you please tell me the version of OpenWrt and LuCI installed (`cat /etc/openwrt-release`; `opkg list_installed luci`) and the model of the router this occurs on?

**Comment by jow-** [comment]
Inactivity timeout
