### ISSUE TITLE
adblock: can't save empty whitelist

### ISSUE THREAD

**Issue by skath** [openwrt/luci#1977]
adblock - 3.4.3-1
luci-app-adblock - git-18.180.55366-b78664c-1

In /luci/admin/services/adblock/advanced/whitelist, add some domains to the whitelist and save. 

Then, try deleting the entries and replacing it with an empty whitelist. Every time you click 'save' the previous whitelist replaces the desired empty whitelist. 

As a workaround I had to add a comment line to the file to remove all whitelisted domains since an empty one can't be saved.

**Comment by dibdot** [comment]
Delete your whitelist entries, hit "Enter" and click save ...  and you're done.

**Comment by jow-** [comment]
@dibdot - Might be a case of `.write()` vs. `.remove()` in cbi, see e.g. 0251603f0aa064109138d40d06aa892f49e7abc7
