### ISSUE TITLE
18.06.0-rc2 rebooting leads to default settings ramips/rt305x issue?

### ISSUE THREAD

**Issue by francisuk1989** [openwrt/luci#1984]
D-Link DIR-615 D but using a D2 version
18.06.0-rc2 but 17.01.5 is working fine!
LuCI openwrt-18.06 branch (git-18.196.56128-9112198) / OpenWrt 18.06.0-rc2 r7141-e4d0ee5af5
Reported here just incase is a ramips/rt305x issue https://bugs.openwrt.org/index.php?do=details&task_id=1684 but will close if it is.

I have a issue with Luci or maybe is issue with ramips/rt305x device but when i go to apply settings and reboot my d-link it goes back to the default openwrt settings however 17.01.5 is working fine no issue here.

Just to be clear when save and apply is ok...but once rebooted it dosnt save any info this resloves into a default settings.

**Comment by jow-** [comment]
Sounds like there is too little flash space available on your router. Check `dmesg` or System -> Kernel Log. If you see a line like `jffs2: Too few erase blocks (4)` then there is not enough flash space left to format a persistent overlay, which means that OpenWrt will operate with some kind of emergency ramdisk which is lost after a reboot.

This sadly is nothing we can fix on the LuCI side. As OpenWrt's components continue to grow, more and more models will become too small to run a stock image with LuCI.

You can try to learn about using the ImageBuilder to generate yourself an image without components like `ppp` which should give you more flash space to work with.

**Comment by francisuk1989** [comment]
Yeah i understand with the device been like 2012-2013 but will check out later when the kids are sleep and off there device (haha) :+1:
