### ISSUE TITLE
luci/openwrt ddns-script maintaining...

### ISSUE THREAD

**Issue by tojestzart** [openwrt/luci#1991]
flashing remotley (wanted to test RC2) , or removing luci-app-qos, causinig hang for remote, since ddns-scipts is obsolete (or not updating ??)
solution?
remove power cord 2000 km away from u

**Comment by jow-** [comment]
Please reopen with a clearer description.

**Comment by tojestzart** [comment]
ddns-script doesnt refresh ip, even if timelimit has hit. this happens when, 1a) upgraded image from cc to 18.06-rc2
b) remove luci-app-qos then software reboot (button under UI, or from shell) will cause no IP refresh 
c) someone can prove?
