### ISSUE TITLE
Time for Moscow...

### ISSUE THREAD

**Issue by Vitaliy86** [openwrt/luci#1998]
If set time Europe/Moscow, time up 1 hour's from real time.

**Comment by jow-** [comment]
You didn't mention your LuCI and/or OpenWrt version. The timezone for Moscow was updated in november 2014 for master with 36357529a0bfc5073987563e17a1d0cc62eac958 and for lede-17.01 with 3737637a654c9f1f35cd7097035664853767f9d0 - beyond that we can't do anything in LuCI.
