### ISSUE TITLE
Error: Unknown error (INVALID_PROTO) RELAYD

### ISSUE THREAD

**Issue by DittelHome** [openwrt/luci#1999]
Using this version:
Powered by LuCI Master (git-18.207.66253-ddf4c2b) / OpenWrt SNAPSHOT r7561-7316515 

Problem:
RELAYD / Router is working, but luci says "Error: Unknown error (INVALID_PROTO)"

Installed Packages:
relayd 2016-02-07-ad0b25ad-2
luci-proto-relay  git-18.207.66253-ddf4c2b-1

![unbenannt](https://user-images.githubusercontent.com/14176684/43312973-0c081ed6-918f-11e8-85ce-b003bce90b5a.PNG)

**Comment by jow-** [comment]
Try a reboot, this error is reported by `netifd` and cannot be fixed in LuCI.
