### ISSUE TITLE
Removed all Ipv6, but the interface did not delete the values.

### ISSUE THREAD

**Issue by LESHIY-ODESSA** [openwrt/luci#2002]
I completely removed the support for IPv6, but I still see artifacts in the interface. Removed before compiling into .config 
luci-proto-ipv6 and other packages.
LuCI openwrt-18.06 branch (git-18.197.56107-4da137e)

cgi-bin/luci/admin/network/firewall/rules/cfg0192bd
![ ](https://i.imgur.com/mJl0lNb.png)

Look at ➜  «**Use builtin IPv6-management**».

![ ](https://imgur.com/3YXNuKe.png)

Was still in — Status ➜  Overview  ➜ «Active DHCP**v6** Leases».
/cgi-bin/luci/admin/status/overview

![ ](https://i.imgur.com/rEhwqNw.png)

cgi-bin/luci/admin/network/network/lan

![ ](https://i.imgur.com/gIBc4mo.png)

**Comment by jow-** [comment]
LuCI will show some IPv6 artifacts on systems with removed IPv6 capabilities, I do not plan to spend resources on supporting this.
