### ISSUE TITLE
LuCI ddns module automatically selects ddns-scripts but some users might prefer yaddns

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#201]
**Reported by fercerpav@gmail.com on 21 Feb 2011 10:58 UTC**
Some users might prefer yaddns because it has a much lower footprint
and properly handles the case when ddns update is unsuccessful;
probably there're other important reasons.

Currently LuCI ddns support will automatically select ddns-scripts
which would conflict with yaddns.

**Comment by hnyman** [comment]
yaddns is in oldpackages.
closing this.
