### ISSUE TITLE
Error compiling package 'luajit'

### ISSUE THREAD

**Issue by 3xtrah3rb** [openwrt/luci#2034]
Hello,

I currently try to compile openwrt for a EasyBox 904 xDSL.
When it comes to the 'luajit' package, it throws an error:

Package luajit is missing dependencies for the following libraries:
libc.so.6
libdl.so.2
libm.so.6
Makefile:92: recipe for target '/mnt/Easybox-904-XDSL/bin/packages/mips_24kc/packages/luajit_2017-01-17-71ff7ef-1_mips_24kc.ipk' failed
make[3]: *** [/mnt/Easybox-904-XDSL/bin/packages/mips_24kc/packages/luajit_2017-01-17-71ff7ef-1_mips_24kc.ipk] Error 1
make[3]: Leaving directory '/mnt/Easybox-904-XDSL/feeds/packages/lang/luajit'
Command exited with non-zero status 2
time: package/feeds/packages/luajit/compile#0.25#0.14#0.39
package/Makefile:107: recipe for target 'package/feeds/packages/luajit/compile' failed
make[2]: *** [package/feeds/packages/luajit/compile] Error 2
make[2]: Leaving directory '/mnt/Easybox-904-XDSL'
package/Makefile:103: recipe for target '/mnt/Easybox-904-XDSL/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/mnt/Easybox-904-XDSL/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/mnt/Easybox-904-XDSL'
/mnt/Easybox-904-XDSL/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

The build machine is running Ubuntu and packages for glibc etc. are installed an the filed are existing.

Linux 31c31144b45f 4.17.11.a-1-hardened #1 SMP PREEMPT Mon Jul 30 00:47:33 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
(Non-Ubuntu Kernel because it is running in Docker on top of Arch-Linux)

maker@31c31144b45f:/mnt/Easybox-904-XDSL$ find /usr/lib -name "libc.so.6"
/usr/lib/x86_64-linux-gnu/libc.so.6
maker@31c31144b45f:/mnt/Easybox-904-XDSL$ find /usr/lib -name "libdl.so.2"
/usr/lib/x86_64-linux-gnu/libdl.so.2
maker@31c31144b45f:/mnt/Easybox-904-XDSL$ find /usr/lib -name "libm.so.6"
/usr/lib/x86_64-linux-gnu/libm.so.6

I hope that this is the right place to ask.
If not, please tell me where to ask for help.

Thanks in advance!

**Comment by yousong** [comment]
luajit resides in the packages repository (https://github.com/openwrt/packages/tree/master/lang/luajit).  Please open an issue there.
