### ISSUE TITLE
"connect" button in interface enables bring up on boot

### ISSUE THREAD

**Issue by widewing** [openwrt/luci#2046]
Expected behavior: just bring up the interface once, should not alter config and make the interface auto connect. 

The button is confusing. People can always set "bring up on boot" in advance tab. Someone like me just want to bring interface up once and don't want it keep retrying, and don't want it connect on boot.

**Comment by jow-** [comment]
Thanks, will change it to enable/disable when I find the time.

**Comment by jow-** [comment]
Reconnect will be made available despite `auto=0` and Connect / Stop will be renamed to Enable/Disable. Due to the lack of a proper `enabled` uci option in netifd this is the only way to realize this functionality by the means of uci changes in conjunction with apply/rollback.

**Comment by widewing** [comment]
Ok.. maybe just add an third button, that become "reconnect" | "connect"/"disconnect" | "enable"/"disable"

**Comment by feckert** [comment]
This is not an issue its a feature request to add an additional button reconnect. So please open a feature request issue for this feature
