### ISSUE TITLE
SimpleForm results in nested form elements

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#205]
**Reported by kevin@kevinlocke.name on 9 Mar 2011 20:26 UTC**
When CBI is not configured with "noheader" and SimpleForm does not have "embedded" set to true, both the header.htm view and the simpleform.htm view output HTML form elements resulting in nested forms.  This is invalid markup (see [http://www.w3.org/TR/xhtml1/#prohibitions]), breaks JavaScript validation (by not triggering the JavaScript events), and breaks file uploads (by changing the form encoding).

I can't find any reason not to remove the form element from simpleform.htm, although I don't know when/how the "noheader" configuration is used (it seems as though this would break all CBI widgets outside of a SimpleForm)...  If it is used, perhaps the output of the form element could be conditional on "noheader"?

**Comment by cshoredaniel** [comment]
ancient report, much rewriting since thing, can be reopened if the bug shows up again.
