### ISSUE TITLE
DHCP Static Lease: Request Entity too large

### ISSUE THREAD

**Issue by Stono** [openwrt/luci#2051]
Hi, 
Trying to add a new DHCP lease via the LUCI gui results in "Request Entity Too Large".
![capture](https://user-images.githubusercontent.com/1486729/43923790-a20a0378-9c1a-11e8-8650-523da5333160.PNG)

I already have 8 items:

![capture](https://user-images.githubusercontent.com/1486729/43923740-84f19814-9c1a-11e8-8a75-73266f53c055.PNG)

This is a fresh install of the release version of openwrt + luci.

Model	TP-Link Archer C2600
Architecture	ARMv7 Processor rev 0 (v7l)
Firmware Version	OpenWrt 18.06.0 r7188-b0b5c64c22 / LuCI openwrt-18.06 branch (git-18.210.69179-6df9a57)
Kernel Version	4.14.54
Local Time	Thu Aug 9 22:21:52 2018
Uptime	0h 15m 19s
Load Average	0.32, 0.23, 0.13

**Comment by jow-** [comment]
Interesting. Do you run LuCI under uhttpd or another web server?

**Comment by jow-** [comment]
The error is thrown when the request headers sent by the browser are too big. Could you try to reproduce the issue while the chrome developer console (F12) is open, then paste the header contents of the offending request?

![debug](https://user-images.githubusercontent.com/2528802/43953739-3d0a5dd0-9c9a-11e8-9227-09a4f6ec5848.png)

Should look like this:
```
POST /cgi-bin/luci/admin/network/dhcp HTTP/1.1
Host: 192.168.1.1
Connection: keep-alive
Content-Length: 14537
Pragma: no-cache
Cache-Control: no-cache
Origin: https://192.168.1.1
Upgrade-Insecure-Requests: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarySFpB1boOCms3UVvT
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: https://jj/cgi-bin/luci/admin/network/dhcp
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: sysauth=9772b440029e67bbdac10297d7ea994e
Request Payload

```

**Comment by Stono** [comment]
Sure thing.

Will do when I get home from work

**Comment by jow-** [comment]
@Stono - did you had any chance to obtain the data?

**Comment by Stono** [comment]
@jow- really sorry, had a manic weekend and totally forgot.  I'm in work now but will grab this info for you tonight.

**Comment by jow-** [comment]
@Stono - any update?

**Comment by Stono** [comment]
@jow apologies for the delay, it's been a crazy few weeks.
I can't get it to do it now!  I've tried on both my laptop and my pc and haven't managed to recreate the problem.

I'm wondering if it's a product of going from 0 to 8, basically I added 8 entries, and then the 9th kept doing that.  I've come back today to do the 9th with a fresh browser session and it's gone on fine.

**Comment by fryfrog** [comment]
I'm seeing it :/

**Comment by hunterzero99** [comment]
I was having this issue as well when trying to log in.  LuCi gave this error before loading the login screen.  I cleared my cookies for the site and it went away.

I am using HTTPS to connect, no idea if that makes a difference.  If I ever reproduce the issue I'll try to report back.

**Comment by codewithpassion** [comment]
Just had the same issue on a Teltonika RUT950.
I went into a Incognito Tab and the issue went away.

**Comment by justinzhu2019** [comment]
发自我的iPhone

在 2019年11月13日，08:27，Dominik Fretz <notifications@github.com> 写道：

﻿

Just had the same issue on a Teltonika RUT950.
I went into a Incognito Tab and the issue went away.

**Comment by jow-** [comment]
Master / 19.07 do not rely on HTTP form submissions anymore

**Comment by nkljajic** [comment]
Content-Length: 20480
is a multiple of 4096
bug in uhttpd
