### ISSUE TITLE
luci-app-ddns failed to execute cbi dispatcher

### ISSUE THREAD

**Issue by finasfinas** [openwrt/luci#2057]
I can't access the luci page for ddns on my custom build C7 image since a couple of months ago. Yesterday I created a custom build for R7800 and the exact same problem happens. removing ddns file from config dir does not solve the issue. this is the error:

```
Failed to execute cbi dispatcher target for entry '/admin/services/ddns'.
The called action terminated with an exception:
/usr/lib/lua/luci/controller/ddns.lua:84: attempt to index field '?' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/ddns.lua:84: in function 'service_version'
	/usr/lib/lua/luci/controller/ddns.lua:91: in function 'service_ok'
	/usr/lib/lua/luci/model/cbi/ddns/overview.lua:16: in function 'e'
	/usr/lib/lua/luci/cbi.lua:48: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:672: in function </usr/lib/lua/luci/dispatcher.lua:667>
```

**Comment by dibdot** [comment]
Which ddns version did you use? Did you try to install/reproduce this issue with official/buildbot generated packages?

What's the output of:
`/usr/lib/ddns/dynamic_dns_lucihelper.sh -V`

Maintainer: @Ansuel

**Comment by Ansuel** [comment]
ummm ddns doesn't use the lucihelper script anymore to obtain the version if LuCI IPKG utility is found... Can you post the content of the file? ( /usr/lib/lua/luci/controller/ddns.lua )

**Comment by hnyman** [comment]
Removal of opkg might be the reason, if I combine Ansuel's comments and you explanation:

>     **remove opkg**
>     **Remove ipkg/opkg status data files in final images is not enabled ( it is as default )**

vs.

> ddns doesn't use the lucihelper script anymore to obtain the version if LuCI IPKG utility is found.


You have rather non-standard options (gcc, binutils, minify, opkg removal) ...
So no wonder that something happens. opkg and opkg data are used in LuCI (and Openwrt) by various package scripts. Removing them will mean that some things will not work ok, and as opkg is pretty much assumed to be present in the build, not all scripts have fallback for that case. I haven't checked ddns sources closely, so this is pure hunch.

**Comment by finasfinas** [comment]
indeed, installing opkg resolves the issue.
thanks for narrowing down this for me.
I'm closing the issue.
