### ISSUE TITLE
Rename 'Open ports on router’ to something more appropriate

### ISSUE THREAD

**Issue by shoulders** [openwrt/luci#2059]
'Open ports on router’ implies just opening ports but this option does more than opening ports. should it be called something like 'Add Traffic Rule'. Also after you add a new rule it is added under 'Traffic Rules'.

(Network --> Firewall --> Traffic Rules)

![open ports on router](https://user-images.githubusercontent.com/319997/44018784-c67d593c-9ed4-11e8-8269-d3834cbc4371.png)

Also do you actually need the 'protocol' and 'destination zone' boxes. I find them confusing because after you click 'Add' you are presented to add all of these details again. Most people would expect the name to be prepopulated because this is the norm.

**My Setup**

- Firmare version = OpenWrt 18.06.0 r7188-b0b5c64c22 / LuCI openwrt-18.06 branch (git-18.210.69179-6df9a57) - (18.06 Stable)
- Router = BT Home Hub 5A (it is actually a Plusnet one)
- if my configuration is of note I can supply that aswell

**Comment by jow-** [comment]
It is just a shortcut for the most common usecase.
