### ISSUE TITLE
LuCI is not corr. working with IE8

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#206]
**Reported by josef.semler@gmail.com on 9 Mar 2011 20:26 UTC**
Today we found out, that changements (tested with wireless) will not take place with IE8.
We tryed to change Country and channel on a Nanostation 5. After changement and "save % apply", IE8 shows the timeout-window. After reconnection, the old settings are still present.

Reconfiguration with Firefox is working well.

JoeSemlerm 0xFF-Vienna

**Comment by sh2d** [comment]
Internet Explorer 8 reached end of support in January 2016 on most platforms.  To quote from https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer

_Beginning January 12, 2016, only the most current version of Internet Explorer available for a supported operating system will receive technical support and security updates, as shown in the table below:_

According to the table mentioned, IE8 support is discontinued for Windows desktop and Windows server platforms.  Support remains for some Windows embedded platforms, though.

**Comment by hnyman** [comment]
IE8 is deprecated. 
Closing this.
