### ISSUE TITLE
luci-app-fwknopd: Invalid UCI config keytype and hkeytype

### ISSUE THREAD

**Issue by roimvargas** [openwrt/luci#2062]
Using luci-app-fwknopd (git-18.219.52706-a49e4e4-1) with fwknopd (2.6.9-4) and it generates invalid entries to UCI configuration that is not recognized by fwknopd (**keytype** and **hkeytype**) as shown below:
```
config access
        option SOURCE 'ANY'
        option KEY_BASE64 '<KEY_VALUE>'
        option keytype 'Base 64 key'
        option HMAC_KEY_BASE64 '<HMAC_KEY_VALUE>'
        option hkeytype 'Base 64 key'
        option FW_ACCESS_TIMEOUT '60'
```

It generates some warnings from fwknopd as shown below:
```
Mon Aug 13 11:49:25 2018 daemon.err fwknopd[7586]: [*] Ignoring unknown access parameter: 'keytype' in /var/etc/access.conf
Mon Aug 13 11:49:25 2018 daemon.err fwknopd[7586]: [*] Ignoring unknown access parameter: 'hkeytype' in /var/etc/access.conf
```

This issue doesn't block fwknopd to function correctly.

**Comment by jp-bennett** [comment]
These are hints for the luci interface.  Fwknop warns, but otherwise ignores this info.  I don't consider it a bug.
