### ISSUE TITLE
While adding a client interface using SCAN option, the client interface is not enabling.

### ISSUE THREAD

**Issue by joewander** [openwrt/luci#2072]
HI,

I am trying to add a client interface to 2.4Ghz wireless network using SCAN and selecting a network to join. Then after joining the client interface is not enabling, its showing "Wireless is disabled or not associated" status only.

Steps followed:
1. In Network -> Wifi -> Click on SCAN -> JOin any network.
2. After joining, the client interface is showing "Wireless is disabled or not associated" status.

Can you help me to understand why this is happening and how to solve this ?

Thank you..!

**Comment by dibdot** [comment]
15.05 is no longer actively supported, please update to 18.06.
