### ISSUE TITLE
Native IPv6 support

### ISSUE THREAD

**Issue by vk496** [openwrt/luci#2105]
Hello,

I have Netgear R6220 with OpenWrt **18.06.0** r7188-b0b5c64c22 / LuCI openwrt-18.06 branch (git-18.210.69179-6df9a57) and native IPv6 support from my ISP.

I had problems to delegate a subnet to my LAN. My router was getting a IPv6 address but the subnet was not propagating. After some hours, I discovered that LuCI shows all the options related to IPv6 but they are not propagated due to dnsmasq.

OpenWrt comes by default with `dnsmasq`, but for IPv6 it should come as minimum with `dnsmasq-dhcpv6`.

Salu2

**Comment by jow-** [comment]
OpenWrt uses odhcpd for prefix delegations, not dnsmasq. It is also not a LuCI problem
