### ISSUE TITLE
root password

### ISSUE THREAD

**Issue by energizer32** [openwrt/luci#2107]
Loaded the openwrt-18.06.1 and the root password that suppose to be blank doesn't work. I tried "password" , "admin" and "root". No luck please help, can't login to load a different image. Tried to power switch 3 times to reset to 1st partition reload. No luck either.

**Comment by jow-** [comment]
Please make sure that the `rpcd` process is running.

**Comment by energizer32** [comment]
I can't make sure it's running because I can't even CLI to the router

**Comment by jow-** [comment]
Then this issue does not appear to be LuCI related. Please follow the generic failsafe / debrick instructions for OpenWrt.
