### ISSUE TITLE
The latest user interface is ugly！！

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/luci#2108]
The latest luci user interface is ugly, and the aesthetic is getting more and more backward.

Not as beautiful as Tomato Firmware UI amateur interface. ![tomato's](http://www.polarcloud.com/img/ssbwm100.png) 
![](https://upload.wikimedia.org/wikipedia/commons/0/0c/Tomato_Firmware_-_Bandwidth_Real_Time.PNG)

**Comment by jow-** [comment]
Nothing actioable about this ticket.
