### ISSUE TITLE
Status overview: IPv6 WAN Status should show all interfaces with default routes

### ISSUE THREAD

**Issue by mikma** [openwrt/luci#2115]
Default IPv6 routes are configured as source-address dependent routes on OpenWrt. This allows you to configure multi-homed networks with multiple exit points for IPv6 without cooperation from the ISP. Currently only one IPv6 WAN interface is shown on the status overview page. This can be an interface configured with gateway in the settings or it can be an interface which has received a default IPv6 route from other sources such as the routing daemon babeld (which supports source-address dependend routes). I think all interfaces which has one or more default IPv6 route should be shown on the page as "IPv6 WAN".

**Comment by jow-** [comment]
Fixed by a13748d4145edd3edc70e462714a115f7c99470e
