### ISSUE TITLE
luci-app-statistics: Wrong Totals for Iptables Matching Rules

### ISSUE THREAD

**Issue by ahmar20** [openwrt/luci#2116]
I am here to submit an issue where in `luci-app-statistics` under `firewall` category/tab the `iptables` matching rules for counting up/down internet traffic produce wrong totals. The `1-hour` figures seem to be okay but if you change the time span to more lengthy period the totals get distorted a lot.

![iptables1](https://user-images.githubusercontent.com/18096216/44661783-2e2ccd00-aa25-11e8-95a4-b770edd5fee4.png)

The above picture is from 1-day time period. As I have a 6mb ADSL connection, I only get around 750+ kb/s download speeds and at this rate I can never download almost 78 GBs data in just 6-8 hours as the picture shows (just talking about one device labeled as `ahmar-lap-in` but I am sure other figures are incorrect too). Now changing the time period to 1-week and we have:

![iptables2](https://user-images.githubusercontent.com/18096216/44662030-f70aeb80-aa25-11e8-8b3b-da0c43ff6b88.png)

Now it shows usage about in `TBs` in just one week which is not possible on my connection. I am not quite sure if the problem is with `collectd` or with the actual package but if you manually calculate the totals with average value of kb/s in the graph the figures seem reasonable to believe. So maybe a bug somewhere in the code. Please correct the issue ASAP. Thanks for continued support.

P.S. I am not sure who to ask for help directly but I think @jow- and @hnyman are relevant guys here.

**Comment by jow-** [comment]
Doe not seem like a LuCI issue to me

**Comment by ahmar20** [comment]
Well the issue still relates to displaying total figure, so I guess maybe `rrd-tool` is the culprit here. But in any case you'll have a more thorough knowledge. Please tell me where to report the issue then.

**Comment by jow-** [comment]
Please provide the output of `rrdtool dump /tmp/rrd/*/iptables-*/ipt_bytes-*.rrd `

**Comment by ahmar20** [comment]
Here is the dump you requested: https://pastebin.com/4ishR4y3

**Comment by feckert** [comment]
@ahmar20 Did you tried the master or openwrt-19.07 relaese?
There was a version update on collectd.

**Comment by ahmar20** [comment]
I am not using collectd and the issue is too old. I think it's best if we close the issue for now. If in the future it happens again, I'll just reopen it. Thank you
