### ISSUE TITLE
csrf token in response headers when authenticating with POST to /cgi-bin/luci/

### ISSUE THREAD

**Issue by remusmp** [openwrt/luci#2118]
Hello luci developers,

I'm experimenting with user authentication. I'm logging in a user doing a POST request as follows:
- request to /cgi-bin/luci
- Content-Type: application/x-www-form-urlencoded
- body 'luci_username=username&luci_password=password'
- withCredentials: true
- responseType: 'text'

I'm getting the following response:
HTTP/1.1 302 Found
Connection: close
Transfer-Encoding: chunked
Set-Cookie: sysauth=1eea17b4a82f7801d6903bfdf2852064; path=/cgi-bin/luci/
Location: /cgi-bin/luci/
And a rendered html page which I don't actually need.

However I'm not able to do any POST requests afterwards to backend API without a CSRF token. The CSRF token would have been rendered in static html pages with <%=token%>.

1. Is it possible to include the CSRF token in the response headers from my initial POST request to /cgi-bin/luci when I authenticate the user?
2. Is it possible to disable the rendering of any page since I'm not using any server-side templating? I'm mainly referring to rendering of the index.html.

My workaround now is to create a template.htm for index.html just with <%=token%> (nothing else) but I'm hoping that I could get the token in the response headers by setting something.

Many thanks in advance!
Remus.

**Comment by jow-** [comment]
If you write your own code anyway then just set the required headers yourself. Or implement an alternative authentication endpoint which returns the data as needed. Maybe take a look at the `luci-mod-rpc` controllers for ideas.
