### ISSUE TITLE
luci-app-openvpn is incompatible with recent versions of the openwrt openvpn package

### ISSUE THREAD

**Issue by rogerjames99** [openwrt/luci#2135]
luci-app-openvpn is incompatible with the openwrt openvpn package after this patch https://github.com/openwrt/openwrt/commit/89b8ba96b404d2e412d5573e25348287255671dd#diff-37e75a0201711d64802dc863bc6019f5

The removes a number of deprecated options.

**Comment by dibdot** [comment]
fixed with c2656a7
