### ISSUE TITLE
:depends not working with ".template = "cbi/tblsection"

### ISSUE THREAD

**Issue by Andy2244** [openwrt/luci#2141]
I cant get the `:depends` feature to work with a section using the template `cbi/tblsection`? 
I would like to reduce the settings clutter and display size, with `value `fields that depend on `flag` fields, is there a way to get this working?

PS: It seems `.size` is also not working and the field size depends on the `description` size.

**Comment by jow-** [comment]
Nope, this is not supported for tblsection templates as you cannot simply omit cells from a grid.
