### ISSUE TITLE
DHCP6 static leases: LuCI “Save and Apply” does not reload odhcpd when DUID fields are changed

### ISSUE THREAD

**Issue by Yuubari** [openwrt/luci#2143]
OpenWrt 18.06, Netgear WNDR3800.

Changing the DUID field in static leases section and clicking Save and Apply did not result in the client getting the specified v6 suffix. Restarting odhcpd with `service odhcpd restart` helps.

It seems like this only applies to the DUID field: I was able to bind a suffix to a printer that uses a MAC-based DUID-LL without specifying the DUID. This time I was configuring a Windows machine which requires specifying the Windows-generated DUID-LLT. I am guessing LuCI does not trigger odhcpd configuration reload on DUID field change.

**Comment by jow-** [comment]
This is a bug in the OpenWrt odhcpd service, nothing we can fix on the LuCI side.
