### ISSUE TITLE
No units for Realtime Load

### ISSUE THREAD

**Issue by keith24** [openwrt/luci#2153]
![Realtime Load graph without units](https://ipfs.io/ipfs/QmaZLLL7WBT98kbM62PDQfcseuciwgoDT7Ccmq59aFEnLi)

I just want to know what's the "load"?  CPU?  There's no units.

**Comment by hnyman** [comment]
> I just want to know what's the "load"?

https://en.wikipedia.org/wiki/Load_(computing)
http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html
http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages
