### ISSUE TITLE
Possible security issue: 1q2w3.website

### ISSUE THREAD

**Issue by zepperdude** [openwrt/luci#2155]
I installed LuCI openwrt-18.06 branch (git-18.228.31946-f64b152) / OpenWrt 18.06.1 r7258-5eb055306f and my firewall shows an outbound connection from the LuCI device to 1q2w3.website, From what I have googled it is not a good site to be reaching out to. Anyone else see this?

**Comment by jow-** [comment]
There is no reference to "1q2w3.website" in the entire LuCI repo and your report is too vague to act upon. Please consider using the OpenWrt Forums for general help and debugging assistance and only open an issue if you clearly identified a bug in LuCI.

**Comment by zepperdude** [comment]
Will discuss in forum.
