### ISSUE TITLE
WRT610N V2 not detected by initial network configuration script

### ISSUE THREAD

**Issue by radicale** [openwrt/luci#2171]
My WRT610N V2 is not detected by the initial network configuration script.  The switch remains unconfigured and wlan/lan vlans are not created.  The issue seems to be in:

`openwrt/target/linux/brcm47xx/base-files/etc/board.d/01_network`

as it does not have a case for this model.  Here's the model string from the live system:

`root@OpenWrt:~# cat /tmp/sysinfo/model`
`Linksys WRT610N V2`

The actual configuration is identical to the Linksys E3000 V1 and the switch is correctly configured if the above string is added to the same case.

My firmware version:

`OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch (git-18.228.31946-f64b152)`

Board name if needed:

`root@OpenWrt:~# cat /tmp/sysinfo/board_name`
`0x04cf:42`

Thanks,
radicale

**Comment by dibdot** [comment]
This has nothing todo with LuCI frontend, please use the main project bug tracker, https://bugs.openwrt.org/
