### ISSUE TITLE
wireguard UI should provide QR code for setup

### ISSUE THREAD

**Issue by nerdoc** [openwrt/luci#2180]
The setup of an wireguard interface is a bit uneasy, as copying a public key from the cellphone is not that easy for most people, or manually typing it is error-prone. I hate doing either of it. There would be an easy way to add an Android setup, if LuCi would provide the user with a QR code that the Android App could easily scan.

**Comment by TrashCanMan** [comment]
Or at the very least a .conf file generator of sort so we can download a conf file from the router and use it on the android client without the need to manually type the keys wich is prone to errors with 0 and O (zero and cap o) and l and I (lower L, cap i) etc...the file format can be seen here https://git.zx2c4.com/WireGuard/about/src/tools/man/wg.8
Also the command to generate the code can be seen here:
https://wiki.debian.org/Wireguard#A3._Import_by_reading_a_QR_code_.28most_secure_method.29
but im pretty sure that is going to require an extra package, on the other side the conf file AFAIK dont need anything extra...

**Comment by yousong** [comment]
Ping luci-app-wireguard's current maintainer @danrl  ;)

If you just open LuCI in cellphone browser, the copy should be easy in both direction.  I can also think of many ways to transfer such info from desktop browser to cellphone, online qrcode generator, copy and send to IM.  There are also existing luci apps such as travelmate, fwknopd using qrencode to generate and embed svg qrcode.

But I cannot think of a better way to transfer public key from cellphone to desktop browser ;)  Usually I just send these literal strings, qrcode, encoded urls to IM then receive and use them in desktop system ;)

**Comment by danrl** [comment]
Sounds like a nice idea. I am open to pull requests implementing the functionality. It's open source, get involved :)

**Comment by TrashCanMan** [comment]
Im smart and good at googling but i know literally zero about coding, i posted the links to help the best i can with my """skills""" :D

**Comment by nerdoc** [comment]
I think it's not about only the key. It's also the IP address. I always have troubles finding the right settings, only after trying a bunch of netmasks.
\<dream>I would be so a killer feature to just "hold" the phone camera onto the screen and *have a working wireguard connection*.\</dream>

**Comment by dibdot** [comment]
@danrl Should the QR code added to the wg status page?

**Comment by danrl** [comment]
Depending on what is in the QR code. I understand we can have one per peer (maybe not that helpful) and/or one per interface. It should appear on the right level, so that it is clear what the qr code is about. Please keep in mind that people are running crazy setups, not everyone has the road warrior setup. So we should not optimize for a single use case.

I am not so sure I like the idea of pulling in all the dependencies that go into generating QR codes, but I can see the demand for that feature. Minimalists might not like it too much. Can we make it an extra package maybe?

**Comment by dibdot** [comment]
@danrl please see #2195 for QR code support

**Comment by dibdot** [comment]
QR Code feature is now in master.
