### ISSUE TITLE
GUI not redirect to DHCP IP

### ISSUE THREAD

**Issue by khareanudeep** [openwrt/luci#2182]
Description 1:  
1-open the GUI in one domain (192.168.1.1)
2-Go to network -> interface -> Edit 
3- change Protocol From Static to DHCP 
After changing to DHCP GUI getting Hang we want it will redirect to DHCP IP.
user don't have console so he did not know the DHCP IP.
Is there any package for that?
i also tried with avahi daemon ,suppose i have 100 AP's but the host name is same for all the 100 AP's in same network it is creating problem.
please provide some solution of that.

**Comment by jow-** [comment]
This is impossible to solve since the gui cannot know the DHCP IP in advance. Once a new DHCP IP is received, the browser already lost contact to the gui.

**Comment by khareanudeep** [comment]
thanks for your Reply jow ..
is there any other way to do this ? any solution ?
