### ISSUE TITLE
not able to run command fw_printenv and fw_setenv in platform.sh while doing firmware upgrade.

### ISSUE THREAD

**Issue by khareanudeep** [openwrt/luci#2205]
Hi,
I have 2 partitions on our board. while we do the firmware upgrade from OpenWRT GUI, it will upgrade default partition. But according to my requirements, we have to upgrade alternate partition and then boot the board from the alternate partition.
I am running the fw_printenv command in the platform.sh file and fw_setenv command in common.sh file but these 2 commands are not run successfully giving the below error:

 fw_printenv
ash: fw_printenv: not found

Or is there any other way to do firmware upgrade while having 2 partitions in the board?

Please give me the solution.

**Comment by hnyman** [comment]
Sounds like nothing to do with the LuCI user interface, so I will close this.

Have you installed the uboot-envtools package? It contains the fw_printenv and fw_setenv commands.
Look example from w.g. mvebu target.
