### ISSUE TITLE
refrence case: 2205: not able to run fw_printenv in platform.sh and fw_setenv in common.sh

### ISSUE THREAD

**Issue by khareanudeep** [openwrt/luci#2206]
Hi,

We have already installed the uboot-envtools package and those commands(fw_printenv and fw_setenv) are working directly on the board. but when I add these command in platform.sh and common.sh file which is running while doing the firmware upgrade from OpenWRT GUI only then it is not working.
My use case is when we are doing the firmware upgrade from GUI then secondary partition should upgrade and also boot from the secondary partition and vice versa.

Case no. #2205 
Hi,
I have 2 partitions on our board. while we do the firmware upgrade from OpenWRT GUI, it will upgrade default partition. But according to my requirements, we have to upgrade alternate partition and then boot the board from the alternate partition.
I am running the fw_printenv command in the platform.sh file and fw_setenv command in common.sh file but these 2 commands are not run successfully giving the below error:

fw_printenv
ash: fw_printenv: not found

Or is there any other way to do firmware upgrade while having 2 partitions in the board?

Please give me the solution

**Comment by thess** [comment]
@khareanudeep - I think you will get better help if you posted your problem with your _custom_ sysupgrade on our forum (https://forum.openwrt.org). This is not a problem with LuCI itself, but an issue with a customization of system procedures done by you. Additionally, if you describe what you are actually trying to do inside platform.sh and custom.sh folks on the forum are more likely to offer suggestions.
