### ISSUE TITLE
Too long zonename in interface firewall settings break firewall

### ISSUE THREAD

**Issue by kubco2** [openwrt/luci#2211]
In interface firewall configuration new zone is not limited to 11 chars[1] and after saving changes for interface, firewall will stop work if newzone has too long name.

[1] https://wiki.openwrt.org/doc/uci/firewall#zones

OpenWrt 18.06-SNAPSHOT r7324-05606de / LuCI openwrt-18.06 branch (git-18.247.71242-9541751) and it is present also in LEDE 17.01

**Comment by kubco2** [comment]
Hello, I think this wont work. I tried it without data-optional. This only add visual style, do not force to 11chars and allow save and apply.
I tried also fix it in ifaces.lua, but I didnt managed how to propagate nice error message to webif. It only print "something is inccorect" but user do not see red inputbox, like in LEDE17.01, because it is hidden in select box.
This is why I left it without PR.
Another idea was adding maxlength attribute on input box, but this will be not same as on other places.

**Comment by jow-** [comment]
It works, I tested it.

**Comment by kubco2** [comment]
You are right, thanks. Will test it.

**Comment by kubco2** [comment]
It works. Good job.
