### ISSUE TITLE
luci-i18n-adblock-zh-cn XML Parsing ERROR in Theme openwrt

### ISSUE THREAD

**Issue by quanmqiu** [openwrt/luci#2214]
OpenWRT Verison 18.06.1 and git master branch

LUCI Theme openwrt, Chinese Language

adblock web page ERROR:

XML 解析错误：非配对的标签。预期：`</a>`。 
位置：cgi-bin/luci/admin/services/adblock 行 104，列 176：
`<div class="cbi-map-descr">Adblock 配置工具，通过 DNS 来拦截广告和阻止域名。进一步信息<a href="https://github.com/openwrt/packages/blob/master/net/adblock/files/README.md" target="_blank">请访问在线文档</div>`
----^

Because:
luci/applications/luci-app-adblock/po/zh-cn/adblock.po line146-148
did NOT match
luci/applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua line11-13

**Comment by jow-** [comment]
This has already been fixed with 9711120e0610ba18750fd3dc61d48fb02bd1e11c in master and 4f4b28b789f1c82bf56957f680661f95022063c8 in openwrt-18.06
