### ISSUE TITLE
http://192.168.1.1/cgi-bin/luci/admin/network/syncdial

### ISSUE THREAD

**Issue by TonyYule** [openwrt/luci#2218]
`/usr/lib/lua/luci/dispatcher.lua:487: Failed to execute cbi dispatcher target for entry '/admin/network/syncdial'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/syncdial.lua:20: attempt to index field 'webadmin' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:487: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>`

**Comment by jow-** [comment]
These files are not part of the official LuCI repository.
