### ISSUE TITLE
lucihttp build error

### ISSUE THREAD

**Issue by ymkyu** [openwrt/luci#2244]
make[3]: Leaving directory '/root/openwrt-ci40-v1.1.0/feeds/luci/libs/luci-lib-nixio'
make[3]: Entering directory '/root/openwrt-ci40-v1.1.0/feeds/luci/contrib/package/lucihttp'
Makefile:53: *** Download/default is missing the FILE field..  Stop.
make[3]: Leaving directory '/root/openwrt-ci40-v1.1.0/feeds/luci/contrib/package/lucihttp'
package/Makefile:196: recipe for target 'package/feeds/luci/lucihttp/compile' failed
make[2]: *** [package/feeds/luci/lucihttp/compile] Error 2
make[2]: Leaving directory '/root/openwrt-ci40-v1.1.0'
package/Makefile:193: recipe for target '/root/openwrt-ci40-v1.1.0/staging_dir/target-mipsel_mips32r2_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/root/openwrt-ci40-v1.1.0/staging_dir/target-mipsel_mips32r2_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/root/openwrt-ci40-v1.1.0'
/root/openwrt-ci40-v1.1.0/include/toplevel.mk:193: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by jow-** [comment]
Looks like you use a nonstandard OpenWrt version. Please reopen if you can reproduce it with current OpenWrt master.
