### ISSUE TITLE
Error upgrading via opkg install

### ISSUE THREAD

**Issue by chris5560** [openwrt/luci#225]
When trying to update a package compiled from git over existing package compiled from svn you get
Error: "Not downgrading package luci-app-... on root from svn-r10180-1 to git-d0fd58a-1"

**Comment by hnyman** [comment]
It has now been almost a year since jow fixed things by https://github.com/openwrt/luci/commit/0856030c79f3febdafa627511cf1be4c72edf09b.
The fix is in 0.12, for-15.05 and trunk.
Let's close the issue as the svn-->git transition was so long ago.
