### ISSUE TITLE
Display problems (Material theme, IE)

### ISSUE THREAD

**Issue by olimpiumarius** [openwrt/luci#2258]
Hello,
I want to show you possible display problems that persists on the Internet Explorer version of windows 10.
The problem persists in several submenus design Material, only on the Internet Explorer browser!
![openwrt3](https://user-images.githubusercontent.com/34411358/48148982-b4864a80-e2c3-11e8-9266-959ccda22a5f.PNG)

![openwrt](https://user-images.githubusercontent.com/34411358/48148601-d9c68900-e2c2-11e8-8f3d-61922b1ddeaf.PNG)
![openwrt1](https://user-images.githubusercontent.com/34411358/48148602-d9c68900-e2c2-11e8-85bb-d421fc98be0e.PNG)

**Comment by jow-** [comment]
ping @LuttyYang

**Comment by olimpiumarius** [comment]
done!

**Comment by jow-** [comment]
I guess this is fixed now.
