### ISSUE TITLE
Regression: can't customize value entries any longer

### ISSUE THREAD

**Issue by dibdot** [openwrt/luci#2261]
Hi @jow,

I haven't tracked this down (maybe changes in cbi.js?!), but with current snapshots I can't customize existing values any longer, e.g. a click on "-- custom --" don't pre-load the value for further customization.
This seems to be independent from browsers or themes.

![2018-11-09 06_47_02-clipboard](https://user-images.githubusercontent.com/8061346/48245585-dbd83700-e3eb-11e8-9581-214d1875025c.png)

**Comment by jow-** [comment]
Did you try to enter a new value and press enter?

**Comment by dibdot** [comment]
No, in the past I could select/pre-load e.g. the first entry and than click on "-- custom --" to edit/further customize the pre-loaded values and that doesn't work now.

**Comment by dibdot** [comment]
OK, I'll try to change the app behaviour accordingly - thanks for clarification.

**Comment by jow-** [comment]
Ok, sorry for the trouble. Let me know when I can help
