### ISSUE TITLE
 luci-theme-Rosy 

### ISSUE THREAD

**Issue by olimpiumarius** [openwrt/luci#2270]
In the Rosywrt theme in the Firewall menu - Port Forwards, do not let you choose Internal IP address!
![rosi1](https://user-images.githubusercontent.com/34411358/48328204-bd707680-e64b-11e8-8f7a-18aa75a17a73.PNG)
![capture](https://user-images.githubusercontent.com/34411358/48328214-c3feee00-e64b-11e8-9469-8e813b6d26cd.PNG)

**Comment by jow-** [comment]
ping @rosysong

**Comment by olimpiumarius** [comment]
done!

**Comment by panda-mute** [comment]
![screenshot from 2018-11-19 23-32-03](https://user-images.githubusercontent.com/23204415/48716953-6f630080-ec53-11e8-871f-aaa2dfbae30b.png)
![screenshot from 2018-11-19 23-32-35](https://user-images.githubusercontent.com/23204415/48716959-71c55a80-ec53-11e8-8eb4-ddc9ebe1c38f.png)

**Comment by panda-mute** [comment]
@rosysong

**Comment by olimpiumarius** [comment]
Problem solved in Kernel Version 4.14.87 SNAPSHOT r8392+292-3dba852547 / LuCI Master (git-18.344.63700-36f2265) , this ticket can be closed!
