### ISSUE TITLE
luci-app-olsr: cosmetic changes needed on the status pages

### ISSUE THREAD

**Issue by pmelange** [openwrt/luci#2288]
The status pages for luci-app-olsr have a cosmetic issue.  On some of the pages (neighbors, routes, hna, and smartgw), the table header and associated columns do not align.

**Comment by pmelange** [comment]
neighbors
![neighbors](https://user-images.githubusercontent.com/20710446/48550996-7b0d9a80-e8d4-11e8-8ea4-50ac7828beff.png)

routes
![routes](https://user-images.githubusercontent.com/20710446/48551001-7f39b800-e8d4-11e8-9a8b-7792d12d0fe7.png)

hna
![hna](https://user-images.githubusercontent.com/20710446/48551006-8234a880-e8d4-11e8-8e8f-1fb8a2bf8aa2.png)

smartgw
![smartgw](https://user-images.githubusercontent.com/20710446/48551012-84970280-e8d4-11e8-9b53-07b57cc44a64.png)

**Comment by jow-** [comment]
Can you arrange me with access (http://mein.io/id_rsa.pub) so that I can take a look? I've no access to any OLSR setup nearby.

**Comment by pmelange** [comment]
@jow- I have set up a test network for you to take a look at.  ssh access only, on port 2222, hostname newolsr.hopto.org

There are 4 nodes in the network.  On the first node that you reach, there is a info in /root/info.txt

**Comment by pmelange** [comment]
The PR is #2294

**Comment by pmelange** [comment]
@jow- Are you done with the test network?  I would like to use the routers to test some new code in the next couple days.

**Comment by jow-** [comment]
@pmelange - I cannot find the access information in my mailbox :(

**Comment by jow-** [comment]
@pmelange - I saved the jsoninfo output to do some mocks locally, so feel free to remove the test setup. These OLSR status pages require a larger rework.

**Comment by pmelange** [comment]
@jow- I can also provide you json files from the Berliner Backbone. There are a lot more nodes to process.

One of the problems on the backbone is that the pages routes, topology, mid and hna require so much preprocessing on the router that in the end the user gets a 'bad gateway'. I assume it would be better to do all or most of the processing on the browser.

I'm absolutely not a web developer, but if there is anything I can do to support you, please let me know.

P. S. Is there any chance of getting the cosmetic changes committed before the rewrite?

**Comment by pmelange** [comment]
Has been merged with commit 84b6e20f04c4dc14aa34660250b8a48f4ba86f4e.  Thanks for your support
