### ISSUE TITLE
firewall: No add button

### ISSUE THREAD

**Issue by kroeckx** [openwrt/luci#2300]
There doesn't appear to be a button to add new rules to the firewall. I can edit and delete rules, but it would be nice that there was some way to just add a rule without having to either edit the file or use the custom rules.

**Comment by jow-** [comment]
Use either „open port router“ or „new forward rule“ and customize further on the subsequent screen

**Comment by kroeckx** [comment]
That looks very counter intuitive, since what I want to do is
neither of that.
