### ISSUE TITLE
luci-app-openvpn: FileUpload fields not shown

### ISSUE THREAD

**Issue by mwarning** [openwrt/luci#2305]
In the OpenVPN LuCI interface, an instance created from a template has many FileUpload fields that are not shown despite being present in the uci config object (e.g. `dh` or `ca`).
They can be added explicitly so that they appear. But removal does not seem to be possible.

**Comment by dibdot** [comment]
@jow- I could fix that with the "unsafeupload" property but it looks like some css magic is needed (at least in bootstrap theme):
OpenWrt theme:
![upload1](https://user-images.githubusercontent.com/8061346/48710655-5b92ac80-ec09-11e8-8752-cbc06576bc0b.png)

Bootstrap theme:
![upload2](https://user-images.githubusercontent.com/8061346/48710671-677e6e80-ec09-11e8-8c10-714bdfd106fd.png)

Thanks!

**Comment by mwarning** [comment]
Would that help? I think this fixes some things.
```
--- a/applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
+++ b/applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
@@ -247,6 +247,10 @@ for _, option in ipairs(params) do
 
 		o.optional = true
 
+		if option[1] == FileUpload then
+			o.datatype = "file"
+		end
```

**Comment by dibdot** [comment]
@mwarning No, that will already checked by the used FileUpload function. Appropriate changes for your issue are in #2307

**Comment by mwarning** [comment]
As a heads up, I applied the changes from #2307 to the current nightly build of OpenWrt and it did not seem to work yet.

**Comment by dibdot** [comment]
@mwarning maybe you could elaborate what "did not seem to work" mean? 
#2307 add the opportunity to remove existing entries ... it doesn't change the (desired) FileUpload behaviour that only valid file handles are shown.

**Comment by dibdot** [comment]
That's a feature, not a bug. The FileUpload types are only visible if they reference a valid file (typically uploaded by the user in /etc/luci-uploads/....)

**Comment by mwarning** [comment]
I tried to set `secret` and thought that would work. But OpenVPN did not start because the `ca` field etc. contains a dummy file path. But since I do not see that field, I do not know that I have to add (to make it visible) and then remove that field.

**Comment by mwarning** [comment]
@dibdot looks good. I can see all fields that are set now. When I clear the `dh` filed and hit "Save & Apply", the field is removed. (But hitting the "Save" button doe not remove an empty field - is that intentional?)

**Comment by dibdot** [comment]
Yes, that's the usual behaviour - only "apply" will finally update/commit the changes to the uci file itself.

**Comment by mwarning** [comment]
Alright. And is it intentional that luci-app-openvpn does not depend on package openvpn?

**Comment by dibdot** [comment]
yep - I will merge #2307 now. Thanks for your input & testing efforts.

**Comment by mwarning** [comment]
ok, thanks for your efforts.
