### ISSUE TITLE
Status page: "Cached" RAM should be counted as "Total Available" RAM

### ISSUE THREAD

**Issue by LGA1150** [openwrt/luci#2318]
LuCI status page does not show `Cached` RAM, and miscalculates `Total Available` RAM by only adding `Buffered` RAM to `Free` RAM.
Available RAM should be `free + buffer + cache`

**Comment by jow-** [comment]
Cached RAM information is not available via the APIs used by LuCI.

**Comment by LGA1150** [comment]
Is it possible to modify the APIs?
