### ISSUE TITLE
luci-app-wireguard: html improvement 1

### ISSUE THREAD

**Issue by nerdoc** [openwrt/luci#2321]
In the `luci/admin/status/wireguard` page, there is some kind of "double" border in each peer line:
![grafik](https://user-images.githubusercontent.com/2955584/48872471-7754a900-ede9-11e8-87fb-d7319896704c.png)

Look on the 2 Lines above "Public Key" - this seems a bit silly. Maybe it could be removed.

**Comment by dibdot** [comment]
That has been already fixed in latest snapshot.
