### ISSUE TITLE
luci-app-wireguard: html improvement 2

### ISSUE THREAD

**Issue by nerdoc** [openwrt/luci#2322]
On `luci/admin/network/network`, edit the wireguard interface "wg" - here URL `luci/admin/network/network/wg`.
There is no visible landmark that divides the peers from each other. So the "Add" button of one peer (to add additional fields) belongs to the upper peer, the "Delete" button on the right seems to  belong to the peer below (which is not really clear) - a hover on it greys out the peer below a bit so you can think that they belong together.

![grafik](https://user-images.githubusercontent.com/2955584/48872631-3dd06d80-edea-11e8-9db8-23471d8805c4.png)

Here, there should be a &lt;hr&gt; tag. or similar. Maybe put it into a frame (=div with border etc.)

On the bottom of the page, it is similar. 
![grafik](https://user-images.githubusercontent.com/2955584/48872666-7112fc80-edea-11e8-9a08-99d6474c0f45.png)
What does the "Add" key do? That's not obvious. Please rename it to "Add peer", and it will be clearer.

**Comment by dibdot** [comment]
wireguard uses the "tsection" standard template to render the peers section. If you need a more structured layout with clear visual boundaries just use the OpenWrt theme
