### ISSUE TITLE
Add new package luci-app-shadowsocksr

### ISSUE THREAD

**Issue by OneHappyForever** [openwrt/luci#2326]
Hi!

I know that the shadowsocks-libev version is already on, but it doesn’t support SSR obfuscations and it doesn’t support bulk adding servers (major flaw).

There is a module that already exists for SSR, but you have to compile it yourself from the command line.

I’d like to add it in, but am not a coder. Could someone help me do so? The repo is already complete with makefile and everything and works fine when compiled from source. So it would just be creating a pull request and adding it.

Here’s the repo: 
https://github.com/Hill-98/luci-app-shadowsocksr

Josh

**Comment by yousong** [comment]
One month passed without response.  But please do not feel taken aback by it, it's expected.  Better way of doing it asking directly current maintainers of that repo whether they want to prepare and upstream then maintain their code here.  If they do not have such a plan, there is no point maintaining another fork.
