### ISSUE TITLE
A few hiccups with latest 6a0c1d1 snapshot

### ISSUE THREAD

**Issue by dibdot** [openwrt/luci#2327]
@jow- 
Just two things I've noticed with latest snapshot:
- Trying to flash a new image ends up in a "Bad Gateway" response
- Clicking on Reveal/Hide password initiate a post request and the page get's reloaded

**Comment by jow-** [comment]
On which page?

**Comment by dibdot** [comment]
Network => Wireless => Security ... and in Travelmate ... ;-)

**Comment by dibdot** [comment]
@jow- works again - thanks. Regarding the latest rpcd changes a small init change proposal that works with defaults even without the new rpcd config section:

`procd_set_param command "$PROG" -s "${socket:-/var/run/ubus.sock}" -t "${timeout:-30}"`

**Comment by jow-** [comment]
There was an underlying logic bug. Fixed with https://git.openwrt.org/?p=project/rpcd.git;a=commitdiff;h=c79ef222858abf65a7d6fc5f869ec45385dd9021
