### ISSUE TITLE
Freifunk Wizard: password revealed when not using mouse to go to "next" page

### ISSUE THREAD

**Issue by pmelange** [openwrt/luci#2332]
With a fresh install of the Freifunk firmware, the wizard comes up and promts the user at the first step to enter a password.  

Without using the mouse, entering the password in the first field, hitting Tab (twice since the UI tweaks), then entering the password again and then hitting Enter causes the password in the first field to be revealed.  The password is the second field remains hidden.

When using a mouse, this does not happen.

**Comment by jow-** [comment]
Which LuCI package do I need to install to find this wizard?

**Comment by pmelange** [comment]
The package luci-app-ffwizard-berlin resides in https://github.com/freifunk-berlin/firmware-packages

The changePassword code is https://github.com/freifunk-berlin/firmware-packages/blob/master/utils/luci-app-ffwizard-berlin/luasrc/model/cbi/freifunk/assistent/changePassword.lua

It may be easier to just use one of our development images.  Here are links to a few different architectures
https://buildbot.berlin.freifunk.net/buildbot/unstable/ar71xx-generic/1003/default
https://buildbot.berlin.freifunk.net/buildbot/unstable/x86-generic/926/default
https://buildbot.berlin.freifunk.net/buildbot/unstable/ramips-mt7621/916/default

If you want to test with a different arch, just let me know which one.

**Comment by feckert** [comment]
This an issue from this LuCI package repository. Please open an issue on their project page.
https://github.com/freifunk-berlin/firmware-packages
