### ISSUE TITLE
Firmware upgrade by tar.gz

### ISSUE THREAD

**Issue by khareanudeep** [openwrt/luci#2352]
![firmware](https://user-images.githubusercontent.com/37998500/49494630-4911a780-f886-11e8-8519-9ff5ce5bf56f.png)

Hi Team,
I want to upgrade new firmware in my Board by Single Image its working fine But our Requirment is Upgrade by tar.gz. Please Help me on this i also attached screenshot. please reply ASAP.
thanks.

**Comment by khareanudeep** [comment]
Hi Openwrt Team ,
please help on this .

**Comment by hnyman** [comment]
There is no magic in the file format being .tar.gz or not.
There is a target-specific check, if the image is in the expected format. You have not told any details about the target (ar71xx, ipq806x, ... etc.) or about the expectd format vs. your format.

You will likely need to modify the logic for the expected file format for your target in the source code.
 

But this is not a LuCI GUI issue. It simply uses the half-way target-dependent sysupgrade scripts to check the image and to flash it.

**Comment by khareanudeep** [comment]
Hi hnyman thanks for reply,
yes my target is ipq806x , and i want to upgrade vai tar insidethe  tar my image is present.
suggest some solution.
