### ISSUE TITLE
wpa3 support

### ISSUE THREAD

**Issue by stokito** [openwrt/luci#2356]
`wpa3` and `sae` support was recently added to netifd (`/scripts/netifd-wireless.sh`)
Now could someone add the option to UI? 
It looks like just few changes into `luci/applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua`

https://gist.github.com/est31/d92d17acbb4ea152296f9b38764cd791

**Comment by macromorgan** [comment]
I think the changes go into luci/modules/luci-mod-admin-mini/luasrc/model/cbi/mini/wifi.lua and luci/modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua.  I'll take a stab at it myself but I know almost nothing of lua.

**Comment by stokito** [comment]
I currently lack of time that’s why created the ticket instead of PR. but I know the Lua a little bit so @macromorgan if you need any help or review just ask me.

**Comment by pkgadd** [comment]
https://github.com/SibrenVasse/luci/commit/31e193d09a19ee9f63a30f9bf09c75dc8f007be9 is missing the equivalent conditionals for ap-wds and sta-wds, the following patch mirrors your checks for ap/ sta - very, very initial testing looks rather positive. Please feel free to fold the patch into your changes.

http://paste.debian.net/download/1061825 (on top of your changes).

**Comment by SibrenVasse** [comment]
@pkgadd: Thanks, I incorporated your changes in my branch.

**Comment by SibrenVasse** [comment]
@stokito: for mac80211 in luci-mod-network all options should be implemented now. There are some sections regarding broadcom [wifi.lua:737](https://github.com/SibrenVasse/luci/blob/6c54c881381db22b1eb342f8c57d8bd4d1f74db4/modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua#L737) where I'm unsure what to do and cannot test myself.

I haven't made any changes to luci-mod-admin-mini yet, but changes should be very similar.

What is currently working:
- You can configure an AP to use WPA3 / SAE / OWE.

What is not working:
- All AP status sections are still displaying incorrect data. For example, my wpa3-mixed APs still display as `Encryption: WPA2 PSK (CCMP)`.
As far as I can tell, fixing this requires no changes in luci, as the info is directly taken from iwinfo (which also still shows WPA2)

So if you want to test: the easiest would be to drop wifi.lua into the correct directory on your router, disable luci ccache and try configuring a network.

**Comment by pkgadd** [comment]
Given the age of the proprietary Broadcom drivers (and those are the ones that need the broadcom backend) I would be very surprised if those would support PMF (IEEE 802.11w) and SAE as needed by WPA3.

**Comment by stokito** [comment]
Hi, any update on this?

**Comment by hnyman** [comment]
Some wpa3 changes were merged into LuCI master two months ago.
Discussed in #2537

**Comment by jow-** [comment]
WPA3 should be feature complete in LuCI now.
