### ISSUE TITLE
Changing date format on Status page

### ISSUE THREAD

**Issue by larry2311** [openwrt/luci#2376]
Just starting out with OpenWrt, so thought I might learn by doing a few things.

So, can anyone advise on the best way to change the date format in the Status page i.e. 
   /usr/lib/lua/luci/view/admin_status/index.htm
How would I go about re formatting the info.localtime [element|array|record, whatever the case may be] ?

**Comment by jow-** [comment]
Modify the `os.date()` call of `/usr/lib/lua/luci/view/admin_status/index.htm`
