### ISSUE TITLE
luci-app-lxc missing vital dependcies for basic operations

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#2379]
@dibdot @ryu0 

such as `kmod-veth` `lxc-start` `lxc-stop` `lxc-attach`

also the `PKG_MAINTAINER:=Petar Koretic <petar.koretic@sartura.hr>` does not appear to be active on GitHub or the repo?

**Comment by ryu0** [comment]
It depends on lxc-attach already. lxc-start/lxc-stop appears to be irrelevant, as the LUCI code makes calls to ubus when it is asked to start/stop a container. Why would it need them?

**Comment by n8v8R** [comment]
> lxc-start/lxc-stop appears to be irrelevant, as the LUCI code makes calls to ubus when it is asked to start/stop a container.

Wasn't aware of it.

---
> It depends on lxc-attach already

That I apparently missed.

---
leaves `kmod-veth`. Without it the bridge with the host cannot get connected.

**Comment by dibdot** [comment]
'kmod-veth' is optional, lxc containers & the luci app does not need this dependency. Anyway, the luci app informs the user about this requirement for network connectivity.
