### ISSUE TITLE
dhcp redirecting client to tftpd running on other machine in lan

### ISSUE THREAD

**Issue by mistepien** [openwrt/luci#2405]
> config  dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	list dhcp_option 'option:mtu, 9000'
	list dhcp-option '66,"192.168.1.8'
	list dhcp_option 'option:bootfile-name, `pxelinux.0'

if I put it into /etc/config/dhcp then luci related to dhcp goes south.
It would be great to have ability to configure it via luci.

**Comment by cshoredaniel** [comment]
@mistepien You have an extraneous quote (") in ``list dhcp-option '66,"192.168.1.8'``

**Comment by jow-** [comment]
Not LuCI related.

**Comment by mistepien** [comment]
``config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	list dhcp_option 'option:mtu, 9000'
	list dhcp-option '66,192.168.1.11'
	list dhcp_option 'option:bootfile-name, pxelinux.0'

**Comment by mistepien** [comment]
ok, you were right.
this is a cli solution:
`uci add_list dhcp.@dnsmasq[0].dhcp_boot='pxelinux.0,<name of external tftp pxe server>,<IP of external tftp pxe server'`
