### ISSUE TITLE
Checking "Enabling logging for this zone" without effect in luci firewall settings for fw3

### ISSUE THREAD

**Issue by sigma74** [openwrt/luci#2407]
The per firewall zone logging of rejected packets (see [#1286](https://github.com/openwrt/luci/issues/1286)) does not seem to be effective, there is neither output in "Status > System log" nor in logread on the console (tested with telnet attempts to port 25 of the openwrt box). Ticking the box "Enable logging on this zone" in luci via "Network > Firewall > Zone Settings > Advanced Settings" does not seem to cause any logging rules to be added to iptables by fw3, as "iptables -L | grep LOG" is empty and no corresponding entry is found in "Status > Firewall" either.

**Comment by jow-** [comment]
Cannot reproduce it on a recent master build.
