### ISSUE TITLE
Submit in scheduled tasks is confusing (can erase crontab)

### ISSUE THREAD

**Issue by foxsam21** [openwrt/luci#2419]
It is too easy to erase the crontab file. The text box in Scheduled tasks does not change after pressing submit and there is no real confirmation that it saved. The trouble with this is that if you press submit again without changing the text in the textbox it will erase what was in the crontab file previously. This results in very easy accidentaly erasing your crontab file.
Maybe pressing submit again should just overwrite the file.

**Comment by jow-** [comment]
Cannot reproduce this on LuCI master. Pressing `Save` twice without altering the contents does not erase the contents.

**Comment by foxsam21** [comment]
I am running openwrt-18.06 branch (git-18.228.31946-f64b152) and tried it
on 2 sperate routers both have same problem. I confirmed it's not just
missing in the text box by ssh in and crontab -l.

**Comment by jow-** [comment]
Retried in an x86 VM using https://downloads.openwrt.org/releases/18.06.1/targets/x86/64/openwrt-18.06.1-x86-64-combined-ext4.img.gz - still not able to reproduce the issue:
http://luci.subsignal.org/~jow/crontab.mp4

**Comment by foxsam21** [comment]
Its also a basically fresh install. I will try tomorrow a fresh install on a different router and a different browser it could be a browser problem. Currently I am using Google chrome for Android and Linux. I can video it if you like. Am I the only one seeing this problem?

**Comment by jow-** [comment]
Maybe you could do a packet dump on the router side  (`tcpdump -w /tmp/http.pcap -ni br-lan tcp port 80`), open the resulting `http.pcap` file in wireshark, right click the HTTP request, select "Follow TCP stream" and paste the resulting HTTP log here. Make sure to redact potentially sensitive content.

**Comment by foxsam21** [comment]
Befor I try this over the weekend I see the difference of my issue and how you enter it. I didn't leave a newline after my entry your entry had a newline. I tried it and with a newline there is no trouble but without it there is.
