### ISSUE TITLE
Need Seprate Radio Configration  and  Wireless Configuration Page.

### ISSUE THREAD

**Issue by khareanudeep** [openwrt/luci#2429]
Suppose we have 3 three SSID ,So if we are going to change(Edit) any wifi configuration Radio config(like channel ,htmode,TX power) also show .
Please Help on this.

**Comment by dibdot** [comment]
What's your problem actually?

**Comment by khareanudeep** [comment]
just we want seprate page only ,  for Radio and ssid configuration in GUI.

**Comment by jow-** [comment]
This is not possible.
