### ISSUE TITLE
Cannot change anything through luci-app-rp-pppoe-server

### ISSUE THREAD

**Issue by heychirag** [openwrt/luci#2431]
No options are visible on PPPoE Server config page in luci.

![screenshot 2019-01-05 at 9 13 15 pm](https://user-images.githubusercontent.com/13611666/50726174-5644df00-112f-11e9-9b66-258a3fcefa08.png)

**Comment by dibdot** [comment]
This was already answered in the forum.

**Comment by heychirag** [comment]
drop the link, please. Even Google is unable to find it.

**Comment by dibdot** [comment]
It's probably your own crosspost in the forum ... https://forum.openwrt.org/t/rp-pppoe-server-not-found-even-after-a-package-list-update/28311/6

**Comment by cshoredaniel** [comment]
Ah, without SSH you can't fix it -- I think that's a valid point -- I'll do an update so that the necessary sections can be created from within LuCI.  @dibdot could you reopen and assign to me so I can track it?

**Comment by dibdot** [comment]
@cshoredaniel re-opened as requested.

**Comment by cshoredaniel** [comment]
@heychirag should work in master now.
