### ISSUE TITLE
ddns error 

### ISSUE THREAD

**Issue by zero13th** [openwrt/luci#244]
Dynamic DNS >> advanced settings >> DNS-Server
I accidentally input wrong character (ex: input ! @ # $ % ^ & * ( ) < . [ ] { } \ |)
I get this error instead of a red box warning:

/usr/lib/lua/luci/dispatcher.lua:448: Failed to execute cbi dispatcher target for entry '/admin/services/ddns/detail/FreeDNS'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/ddns/detail.lua:920: attempt to concatenate global 'err' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:448: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:195: in function </usr/lib/lua/luci/dispatcher.lua:194>

**Comment by chris5560** [comment]
@zero13th 
could we close this ?

**Comment by zero13th** [comment]
thanks Chris
