### ISSUE TITLE
luci-app-commands Wrong View Page in Material Theme for Mobile

### ISSUE THREAD

**Issue by ahmar20** [openwrt/luci#2467]
![screenshot_20190119-052210](https://user-images.githubusercontent.com/18096216/51419229-a0f03d80-1baa-11e9-89a2-f7df91c31356.png)
The above screenshot shows the exact behavior of luci-app-commands page when using Mobile and accessing the LuCI through Material theme in v18.06.1. I'm not sure if Rosy theme has the same issue. Only tested with Material theme on different phones. It should be consistent with list view technique used in all the views for LuCI. Please fix it. Thanks

**Comment by shunjou** [comment]
This is what the material custom commands page currently looks like on mobile with the master branch:

![screenshot_20190119-134638_chrome](https://user-images.githubusercontent.com/16366798/51431054-c05e8900-1bf1-11e9-94f9-60c266a77c16.png)

Issues you need to resolve:
1) Update to the latest material theme from the master branch.
2) Always include versions of what you're running when submitting an issue for anything anywhere.
3) Spell check is your friend.

**Comment by ahmar20** [comment]
I am sorry for the issues. I always try to provide proper and complete information but I am not sure how did I miss that. Your points have been noted but I am not running master snapshot version on my router so cant update to the master version yet. But hopefully these fixes will be available in the upcoming releases. Thank you for the info.

**Comment by shunjou** [comment]
Sorry for the really late reply since I have notifications turned off. Thanks for the issue report regardless. You should be able to grab a [snapshot build](https://downloads.openwrt.org/snapshots/packages/x86_64/luci/) of the material theme package and run it on your router that's using the stable branch.

Example:
```
cd /tmp
wget https://downloads.openwrt.org/snapshots/packages/x86_64/luci/luci-theme-material_git-19.102.20369-4409bc2-1_all.ipk
opkg install luci-theme-material_git-19.102.20369-4409bc2-1_all.ipk
```
