### ISSUE TITLE
[RFC] luci-mod-admin-base vs luci-mod-admin-full

### ISSUE THREAD

**Issue by cshoredaniel** [openwrt/luci#2468]
I've been looking a little at what is the minimum set of functions that make sense with current luci and/or where it might make sense to shift 'ownership' of some things around so that users can reduce unnecessary components without introducing new packages (and hence packaging waste).

Obviously this isn't a do all at once, nor in priority order, and is for post-release.

My thoughts on changes:
* Shift the 'firewall' page in Status to be owned by app-firewall (although still appearing in Status; this is okay because Status is created by luci-base)
* Shift 'routes in Status to be owned by mod-network
* Shift 'System Log', 'Kernel Log', and 'Processes' to mod-system
* Shift 'Overview' to luci-base (it's rather core I think).
So what's left in mod-status is 'Realtime Graphs' which could be renamed to luci-app-realtime-graphs and put under applications? (I personally don't think this is a core functionality to keep on minimal space devices where the package overhead is an issue for separating it out).
* Also perhaps a new menu section 'Graphs' for app-statistics app-realtime-graphs app-nlbwmon and app-vnstat to live under in terms of UI?  (Currently these are a bit inconsistent menuwise IMO).  For realtime graphs maybe move the connections list under it's own 'Status' menu or have a more static connections page that doesn't need the realtime graphs luci-bwc thing in that spot and keep the realtime connection with the associated graph.

* Break out the fstab ('Mount Points'(?)) thing into a luci-app-storage and have it's own menu call 'Storage' (which is made available by luci-base but doesn't show up unless something is in it) -- it doesn't display unless block-mount is installed (well really /etc/config/fstab which is owned by block-mount) as it is, and it's another case of if you're adding a storage device then the packaging overhead is less likely to be concern on the device.  Also it could gain some more NAS type stuff that there are hints for packages what will activate menus for managing storage (partitioning, formatting, lvm, RAID, etc).

* I'd like to spit out the DNSMasq related stuff into luci-app-dnsmasq -- while it's the default, with IB it's not too hard to build an unbound + odhcpd version of OpenWrt, and there are other options that could be made available, if they were reasonably pluggable (e.g. via PROVIDES (for dhcp, recursive dns, and 
authoritative dns)).  opkg seems to be able to handle that now.

* In networking I'd like to split out wireless into luci-mod-wireless -- it's a big chunk that about half the time I don't actually use it (I only need so many AP-mode devices, and I like wired over wireless given a choice).

* Someday I'd like expanded diagnostics as a separate luci-mod-diagnostics with it's own section.

* luci-mod-admin-full would continue to be a metapackage that gets you all the current base + status + system + network stuff but there could be a luci-mod-admin-base that has the above luci-base +  luci-mod-system + luci-mod-network (no wireless), and luci-light that is luci-mod-admin-base + luci-mod-wireless + luci-app-dnsmasq + uhttpd +... minimal wireless luci system (replacement for luci-mod-admin-mini + uhttpd etc).

I also want to do this as I think it will make it easier for my plot to gradually transition luci to ubus + rpc + S (that is the ongoing effort, so far seemingly stalled, to ditch CGI + Lua version.  I have noticed some things I was looking at working on already have been, so the biggest thing left is to be able to build some hybrid nodes and get things moving incrementally (unless a big code dump comes and solves the transition all at once, but the lack of visible development on luci-ng is concerning).

**Comment by cshoredaniel** [comment]
So, I finally took a look at package sizes -- rather than splitting packages I think what's more important is to avoid pulling in unwanted dependencies -- the lua itself isn't the issue for size, so that means it's more a matter of how to organize groups of packages (like monitoring) so that they only display if

a) dependencies needed are present (and make sure there is a 'tips' or somesuch page so user knows that if they install package(s) x, y, z they get features a, b, c enabled in luci).
b) apps/modules/protos are not marked as disabled or somesuch that prevents them  from affecting the luci instance, unless they are enabled (perhaps by a setting in /etc/config/luci, with build time defaults possible so that SDK/IB can make images that default to what the builder actually wants to see on the system; and for SDK / buildroot builds pulling in the dependencies only for enabled apps/modules/protos).

I sill would like check the size difference with splitting network up (wireless and dnsmasq probably take up a lot of the package size).

On the other side with enable/disable I'd actually like to move luci-app-uhttpd and luci-app-wol (with the above mentioned ability to disable especial dependencies for wol) into mod-network since they are quite small on their own.  Maybe watchcat into system too.

In any event enable/disable from affecting the luci instance seems more they primary issue too worry about combined with some reorganization of 'ownership' of pages.

**Comment by jow-** [comment]
Closing this as it never gained traction
