### ISSUE TITLE
Remove last LEDE references from luci

### ISSUE THREAD

**Issue by xosevp** [openwrt/luci#2471]
"git grep LEDE" still shows some LEDE references.

Thanks.

**Comment by hnyman** [comment]
fixed with d99831e9d01

**Comment by xosevp** [comment]
Should this be removed too?

modules/luci-mod-network/root/etc/uci-defaults/50_luci-mod-admin-full:          host="${HOME_URL:-${BUG_URL:-$LEDE_DEVICE_MANUFACTURER_URL}}"

**Comment by hnyman** [comment]
> Should this be removed too?

No.
The variable is still defined in OpenWrt itself.

https://github.com/openwrt/openwrt/blob/0efd0308a0927e446e1f8535c1e244e5ed3193b3/package/base-files/files/usr/lib/os-release
