### ISSUE TITLE
Install luci error

### ISSUE THREAD

**Issue by 9000000** [openwrt/luci#2479]
root@OpenTest:~# opkg install luci                                        Installing luci (git-19.022.57088-61b9f7a-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/luci_git-19.022.57088-61b9f7a-1_all.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 * liblua5.1.5
 * opkg_install_cmd: Cannot install package luci.
root@OpenTest:~#

**Comment by jow-** [comment]
You need to update your firmware to the latest version. Alternatively use `opkg install --force-overwrite install liblua5.1.5`.In any case this issue is not LuCI related.

**Comment by 9000000** [comment]
Luci got it wrong File name liblua5.1.5 
Its right --> liblua-5.1.5

**Comment by jow-** [comment]
LuCI does not depend on `liblua` at all, it only depends on `lua` which in turn depends on `liblua5.1.5`. The `lua` package is part of OpenWrt base, not LuCI.
