### ISSUE TITLE
dhcp redirecting client to tftpd running on other machine in lan

### ISSUE THREAD

**Issue by mistepien** [openwrt/luci#2502]
Hi,
now luci supports only using tftp server using dnsmadq running on openwrt itself.

However there is an uci solution:
`uci add_list dhcp.@dnsmasq[0].dhcp_boot='pxelinux.0,<name of external tftp pxe server>,<IP of external tftp pxe server'`

But if you change something in dhpc via luci above dirty-hack solution is overwritten.

**Comment by jow-** [comment]
Just put `pxelinux.0,<name of external tftp pxe server>,<IP of external tftp pxe server` into the `Network boot image` field in Network -> DHCP and DNS -> TFTP Settings.
