### ISSUE TITLE
Wireguard adds endpoint host to routing list without need.

### ISSUE THREAD

**Issue by EUA** [openwrt/luci#2510]
I tried to setup router as WG client for a while. But it doesn't work on my setup.
After research, I realized that licu-wireguard application adds a static route somehow.
After removal of non needed record of endpoint from routing table (51.x.x.x in my setup), Wireguard starts working proper.

```
root@MainRouter:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.2.1     0.0.0.0         UG    0      0        0 eth0.2
10.0.2.0        *               255.255.255.0   U     0      0        0 wg0
51.x.x.x        MainRouter.lan  255.255.255.255 UGH   0      0        0 br-lan
192.168.1.0     *               255.255.255.0   U     0      0        0 br-lan
192.168.2.0     *               255.255.255.0   U     0      0        0 eth0.2

```
PS: MainRouter.lan is name of the router. (192.168.1.1)

**Comment by jow-** [comment]
Please report this against the OpenWrt wireguard package. LuCI is only the ui frontend to it.
