### ISSUE TITLE
luci-theme-Rosy left bar menu not showing on mobile

### ISSUE THREAD

**Issue by Keltere** [openwrt/luci#2523]
Hi, as the title i can't open the left menù on mobile. I've tried with all browser (firefox, chrome etc) and even on desktop shrinking the width of the window.
With material and bootstap theme no problem, just with rosy.
![cattura](https://user-images.githubusercontent.com/8084245/52541461-a39f1680-2d95-11e9-89ac-37a2d568abe9.JPG)

**Comment by imi2003** [comment]
Hi, I can confirm the same issue with 2 different android phones Moto G6 play and Lenovo P2

**Comment by Keltere** [comment]
#2539 resolved this issue.
