### ISSUE TITLE
iptables.js regex does not match single src / des ip addresses

### ISSUE THREAD

**Issue by Bourne1d** [openwrt/luci#2530]
Hi,

I was missing some of my iptables entries in the overview provided in the luci -> status-> firewall overview.
Debugging this i figured out that all iptables entries that did not have a cidr prefix were excluded from the page.

**_1 0 0 all -- * * 192.168.0.1 0.0.0.0/0_**  -> excluded
**_2 0 0 all -- * * 192.168.0.0/24 0.0.0.0/0_** -> works 

Looking at the iptables.js regular expression the cidr notation is marked as required.
`^(\d+) +(\d+) +(\d+) +(.*?) +(\S+) +(\S*) +(\S+) +(\S+) +([a-f0-9:.]+\/\d+) +([a-f0-9:.]+\/\d+) +(.+)$`

As a current workaround i changed it to this which works okay for me:
`^(\d+) +(\d+) +(\d+) +(.*?) +(\S+) +(\S*) +(\S+) +(\S+) +([a-f0-9:.]+\/*\d*) +([a-f0-9:.]+\/*\d*) +(.+)$`

I did not check if this works with all other entries or ipv6.

**Comment by jow-** [comment]
Fixed with 83df3eb
