### ISSUE TITLE
luci-mod-network: DHCP allow define gateway and dns in static leases

### ISSUE THREAD

**Issue by rexzhang** [openwrt/luci#2531]
sometime, have different gateway and dns server in the one network

**Comment by feckert** [comment]
Please add more info what you expect for this feature

**Comment by rexzhang** [comment]
maybe we can define/edit gateway and dns  at page `/cgi-bin/luci/admin/network/dhcp`  as hostaname/mac-address/ipv4-address

**Comment by jow-** [comment]
Closing this since its not supported by `/etc/config/dhcp`
