### ISSUE TITLE
Loading Port Forwards takes two minutes

### ISSUE THREAD

**Issue by Sanqui** [openwrt/luci#2532]
Loading the page `/cgi-bin/luci/admin/network/firewall/forwards` takes two minutes or more every time.  Here's a network log from Firefox:

![image](https://user-images.githubusercontent.com/289437/52635667-c7b04400-2eca-11e9-9031-e348e4d4e1e2.png)

We are running `LuCI 96366054565006474c39e02dca00c9d45dcb9e15 branch (git-18.328.59464-9636605) / OpenWrt omnia 15.05 r47055`

Please advise on diagnosing this issue.

**Comment by jow-** [comment]
Make sure that the router itself can properly resolve DNS.
