### ISSUE TITLE
Luci system startup tab lists dropbear is disabled, though it isn't

### ISSUE THREAD

**Issue by Pferdebockwurst** [openwrt/luci#2536]
The title pretty much says everything. I'm using OpenWRT 18.06.1 and luci states that the dropbear service is disabled at startup, though it isn't: there's a symlink in /etc./rc.d/ that points to /etc/init.d/dropbear.

**Comment by jow-** [comment]
Canont reproduce this using https://downloads.openwrt.org/releases/18.06.2/targets/x86/64/openwrt-18.06.2-x86-64-combined-ext4.img.gz in Qemu:

![init](https://user-images.githubusercontent.com/2528802/57627210-d7a5f580-7597-11e9-9ff9-dcb2e16b7cd4.png)
