### ISSUE TITLE
PPPoE client over Bridge interface: problem with the ifname

### ISSUE THREAD

**Issue by lars18th** [openwrt/luci#2541]
Hi,

When you like to configure one PPPoE Client connection with LUCI, the UI doesn't work if your physical interface for the PPPoE connection is a Bridge.

Here some part of my current "/etc/config/network":
```
config interface 'eth-pppoe'
        option type 'bridge'
        option bridge_empty '1'
        option ifname ' '
        option proto 'static'

config interface 'test'
        option proto 'pppoe'
        option password '******'
        option username 'user****'
        option ifname 'br-eth-pppoe'
```

So, when using `option ifname 'br-eth-pppoe'` that's the name of the bridge (note the "br-") it works. However, the UI of LUCI always try to use the physical interface of the bridge; and it adds to the configuration only the name, like `option ifname 'eth-pppoe'`. This is true even when the brdige is empty, or when using a dummy interface on it. And then the client connection fails.

I request to remove this limitation and support bridge interfaces for PPPoE Client connections.

Regards.

**Comment by jow-** [comment]
Should work fine in master, arbitrary ifnames may be specified
