### ISSUE TITLE
applications: postinst not copied/executed into final package

### ISSUE THREAD

**Issue by chris5560** [openwrt/luci#255]
Inside application directory are the folowing directories defined:
luasrc/\* - will be copied to /usr/lib/lua/luci/*
root/\* - will be copied to /*
ipkg/\* - used to for postinst/postrm/preinst/prerm normaly defined inside makefile for a default openwrt package.
With the new default postinst / postrm functionality inside openwrt build, files inside ipkg/\* are no longer copied into the final package file. So they cannot be executed during installation.

**Comment by cshoredaniel** [comment]
@chris5560 Has this been resolved with current LuCI?

**Comment by chris5560** [comment]
No longer relevant
