### ISSUE TITLE
Password input rendered wrong when embedded in table cell

### ISSUE THREAD

**Issue by yousong** [openwrt/luci#2624]
The issue was originally reported as a followup in issue https://github.com/openwrt/luci/issues/2398#issuecomment-450495221.  but it got ignored there after the original issue got resolved and closed.

The issue is still present in current luci master.

Below is a copy of the original report

> I understand.  Previously browser autocomplete can indeed cause trouble.  But it seems when embedded in a table, the added input element will be visible, despite the css code `left: -1000px`
> 
> ![screen shot 2018-12-29 at 9 56 39 pm](https://user-images.githubusercontent.com/4948057/50539045-ac0c0b00-0bb4-11e9-875e-7e7a187cb0ba.png)
> 
> Another minor undesirable change is that previously the `Reveal/hide password` button stick to the input element on the same row, not wrapping to the next line.
> 
> ![screen shot 2018-12-29 at 10 00 55 pm](https://user-images.githubusercontent.com/4948057/50539089-43715e00-0bb5-11e9-8f89-b2bedeccc083.png)

**Comment by shNanChen** [comment]
This problem still exists. :flushed:

**Comment by jow-** [comment]
Wasn't able to reprioduce this in Firefox.

**Comment by yousong** [comment]
I can confirm that it's still reproducible with a recent version of Chrome and Safari.  Sorry that I am still not certain when I can allocate time for this.  I will update here when I am on it.

**Comment by yousong** [comment]
I just opened a pull request for this.  After the change, the result will be like the following

![image](https://user-images.githubusercontent.com/4948057/60355943-459c6400-9a02-11e9-88ce-28d9e1d9644c.png)
