### ISSUE TITLE
luci-app-wifischedule - Save & Apply not working properly

### ISSUE THREAD

**Issue by CaboBeach** [openwrt/luci#2631]
Save & Apply usually has to be clicked two or more times in Services > Wifi schedule > Schedule for settings to take affect.

**Comment by dibdot** [comment]
Please test attached PR - thanks!

**Comment by CaboBeach** [comment]
Thanks dibdot, sorry to ask, but could you please let me know the path to `/applications`? Documentation says `luci-path/applications`, but I'm not sure what `luci-path/` should be unfortunately.

**Comment by dibdot** [comment]
You should find the file on your router under `/usr/lib/lua/luci/model/cbi/wifischedule/...`

**Comment by CaboBeach** [comment]
Thanks again dibdot, unfortunately the settings don't seem to be getting applied after the change, they no longer show in cron and wifi stays up, here's the relevant section of my `/wifi_schedule.lua` just to make sure I made the correct change - 


```
-- BEGIN Map
m = Map("wifi_schedule", translate("Wifi Schedule"), translate("Defines a schedule when to turn on and off wifi."))
function m.on_apply(self)
    sys.exec("/usr/bin/wifi_schedule.sh cron")
end
-- END Map
```

**Comment by dibdot** [comment]
Sorry, I forgot to set the 'apply_on_parse' attribute on this map instance. I've updated the PR - should work now.

**Comment by CaboBeach** [comment]
That got it, it's working perfect now, many thanks as always for your hard work dibdot.

**Comment by dibdot** [comment]
Thanks for testing, will merge!
