### ISSUE TITLE
How to go from OpenWRT back to Factory firmware on Linksys EA6350v3 ?

### ISSUE THREAD

**Issue by cheneylaw** [openwrt/luci#2638]
How to go from OpenWRT back to Factory firmware on Linksys EA6350v3 ?

root@OpenWrt:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00040000 00010000 "SBL1"
mtd1: 00020000 00010000 "MIBIB"
mtd2: 00060000 00010000 "QSEE"
mtd3: 00010000 00010000 "CDT"
mtd4: 00010000 00010000 "APPSBLENV"
mtd5: 00080000 00010000 "APPSBL"
mtd6: 00010000 00010000 "ART"
mtd7: 00020000 00010000 "u_env"
mtd8: 00020000 00010000 "s_env"
mtd9: 00010000 00010000 "devinfo"
mtd10: 02800000 00020000 "kernel"
mtd11: 02500000 00020000 "rootfs"
mtd12: 02800000 00020000 "alt_kernel"
mtd13: 02500000 00020000 "alt_rootfs"
mtd14: 00100000 00020000 "sysdiag"
mtd15: 02f00000 00020000 "syscfg"
root@OpenWrt:~# 

-----------------------------------------------------

Advanced Reboot

Linksys EA6350v3 Partitions
Partition
Status
Firmware/OS (Kernel)
Action
1
Current
OpenWrt (Linux 4.14.106)
Reboot to current partition
2
Alternative
OpenWrt (Linux 4.14.91)
Reboot to alternative partition...**

**Comment by hnyman** [comment]
Nothing to do with LuCI user interface.
Please search the OpenWrt forum and ask there.
