### ISSUE TITLE
Request for commit access

### ISSUE THREAD

**Issue by feckert** [openwrt/luci#2666]
As mentioned in the ticket https://github.com/openwrt/packages/issues/8469#issuecomment-476710091 I would also like to request commit access for me (@feckert) to the LuCI repository.

**Comment by hnyman** [comment]
Fine with me. Florian has been active with many LuCI packages lately.

**Comment by blogic** [comment]
fine with me.

**Comment by jow-** [comment]
Should be done.

**Comment by feckert** [comment]
thanks
