### ISSUE TITLE
luci-app-adblock commands hang

### ISSUE THREAD

**Issue by evasil** [openwrt/luci#2668]
Hello,

I have found that when I operate adblock from luci-app-adblock, then all commands hang excepting actual start of /etc/init.d/adblock

Luci fires adblock command with "/bin/sh /etc/rc.common" before the actual command.

Examples:
Luci: I choose "Refresh Report" in "DNS Query Report" page.
2 processes appear:
```
11519 root      1328 S    /bin/sh /etc/rc.common /etc/init.d/adblock report + 50 false false
11526 root      1456 S    /bin/sh /usr/bin/adblock.sh report + 50 false false
```
end they never stop.

Manual: I run
`/usr/bin/adblock.sh report + 50 false false`
it starts end finishes properly.

The same with other commands from Luci, like "reload" or so.

I am not sure but while actual file /etc/init.d/adblock already has the init line inside as: 
`#!/bin/sh /etc/rc.common`
maybe Luci also should run those commands without:
`/bin/sh /etc/rc.common`
in front, the same way when I run them manually?

**Comment by dibdot** [comment]
Which router model? Which adblock version? Which luci version? Please provide the output of `/etc/init.d/adblock status`. Thanks!

**Comment by dibdot** [comment]
No feedback & not reproducible - close this by now.
