### ISSUE TITLE
luci-app-shadowsocks-libev cannot save from "Redir Rules"

### ISSUE THREAD

**Issue by jackcctse** [openwrt/luci#2671]
Have been getting this error for quiet some snapshot builds. 

1. Reproducing the error: just click save on "Redir Rules" screen, with or without editing makes no difference.
2. The error: failed to save anything, below error message appears.
`Failed to execute cbi dispatcher target for entry '/admin/services/shadowsocks-libev/rules'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:165: Datatype error, bad token "cidr"
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/cbi.lua:165: in function 'compile_datatype'
	/usr/lib/lua/luci/cbi.lua:177: in function 'compile_datatype'
	/usr/lib/lua/luci/cbi.lua:189: in function 'verify_datatype'
	/usr/lib/lua/luci/cbi.lua:1493: in function 'validate'
	/usr/lib/lua/luci/cbi.lua:1414: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:248: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:1111: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:248: in function 'parse'
	/usr/lib/lua/luci/cbi.lua:387: in function 'parse'
	/usr/lib/lua/luci/dispatcher.lua:881: in function </usr/lib/lua/luci/dispatcher.lua:860>`

Workaround: edit /etc/config/shadowsocks-libev with text editor

Lastest version tested

> OpenWrt SNAPSHOT r9782-09fe18f042 / LuCI Master (git-19.093.68468-d679b93) 
> luci-app-shadowsocks-libev git-19.093.68468-d679b93-1

**Comment by dobetter** [comment]
The same here!
