### ISSUE TITLE
v2ray for openwrt - 2.3.6 设置gfwlist 模式却无法访问Google

### ISSUE THREAD

**Issue by deepfish** [openwrt/luci#2675]
你好，我在使用 v2ray for openwrt - 2.3.6 版本的插件。设置访问控制时，设备为GFWLIST 模式时却无法访问Google，YouTube 等网站，感觉没有生效。但是设置成大陆白名单后却正常访问了，现在不知道是不是我操作有问题呢？

**Comment by dibdot** [comment]
English please.

**Comment by wildjeff** [comment]
> English please.
Hello,i am using v2ray for openwrt - 2.3.6.when i visit www.google.com(or www.google.com/ncr),it blocked ,but visit www.google.co.jp & youtube sucessfully,in this case i set GFWLITS blacklist;when i switch to  whitelist mode the problem are gone.

**Comment by yousong** [comment]
v2ray is not maintained in this repo.  You will have to report the issue to upstream project whatever it is.
