### ISSUE TITLE
LuCi hangs

### ISSUE THREAD

**Issue by davidc502** [openwrt/luci#2680]
I've experienced this for myself but am also getting reports from users experiencing the same thing --- LuCi will hang randomly.  Which theme used does not matter. Nothing in the System or Kernel logs to indicate an issue.

The symptom is when trying to log in (but not always), or clicking on any of the links (but not always), LuCi will sit and spin like screenshot below.  Eventually, it will either log in or the page will load, but sometime can take minutes for that to happen.

Reported hardware: 
Linksys 3200acm
Linksys 32x
Linksys 1900acs

![Screenshot from 2019-04-21 19-46-06](https://user-images.githubusercontent.com/14110206/56477777-da1ca000-646e-11e9-9a48-8a4d7262e655.png)

**Comment by solidus1983** [comment]
I can also confirm this as well using David's build on WRT32x, Hangs not only during use after login but also at the login stage takes me a few spams of the button before it logs me in.

**Comment by davidc502** [comment]
@solidus1983 
Are you also using dnscrypt-proxy version 2?

**Comment by ErikBAndersen** [comment]
I also see these UI hangs.  Wrt3200acm, latest davidc builds.
I am not using dnscrypt-proxy version 2, but I am using the
older/stock dnscrypt-proxy v1.9 version.

**Comment by jow-** [comment]
Please see if https://git.openwrt.org/f00a4ae6e0 helps.

**Comment by solidus1983** [comment]
I changed two settings with dnscrypt on.

to
	option max_connections '50'
	option max_requests '10'
from
	option max_connections '500'
	option max_requests '1'

**Comment by davidc502** [comment]
Thanks for testing... various users not using dnscrypt-proxy 2 have reported LuCi hanging, so this isn't dnscrypt-proxy related.

**Comment by davidc502** [comment]
Will test the 2 HTTP(s) options this evening and ask others to test as well.

**Comment by pmelange** [comment]
This is related to https://github.com/openwrt/luci/issues/2560

thanks @jow- for reverting to the previous settings

**Comment by davidc502** [comment]
Closing this issue --

**Comment by camelcamro** [comment]
hmm, still having same issue with newest trunk :(
should be that really fixed ?
pls reopen

**Comment by jpdribbler** [comment]
same issue here :(

**Comment by hnyman** [comment]
> same issue here :(

And you have modified your /etc/config/uhttpd as suggested above in 

> > Please see if https://git.openwrt.org/f00a4ae6e0 helps:
    
      option max_requests 3

**Comment by jpdribbler** [comment]
> > same issue here :(
> 
> And you have modified your /etc/config/uhttpd as suggested above in
> 
> > > Please see if https://git.openwrt.org/f00a4ae6e0 helps:
> 
> ```
>   option max_requests 3
> ```

I just checked but it is already set to:

config uhttpd 'main'
	option max_requests '3'

**Comment by facboy** [comment]
i have this problem too, mine is currently set to

```
option max_connections '50'
option max_requests '10'
```

**Comment by dreary-ennui** [comment]
Having same problem, latest build, with connections set to 50 and requests set to 10.

**Comment by teapethu** [comment]
I hit the same issue while the default config is already 3
`option max_requests '3'`

**Comment by teapethu** [comment]
Fixed the issue by setting uhttpd configuration http_keepalive to '0'
