### ISSUE TITLE
Armvirt's max connection problem

### ISSUE THREAD

**Issue by SuzukiHonoka** [openwrt/luci#2685]
I have imported the openwrt 18.06 armvirt rootfs from the "https://downloads.openwrt.org/releases/18.06.2/targets/armvirt/64/openwrt-18.06.2-armvirt-64-default-rootfs.tar.gz" to the docker.
Basic functions works great!
But the max connection limits are only 4096.
Please help!!

**Comment by hnyman** [comment]
Nothing to do with LuCI user interface.
