### ISSUE TITLE
Openc2x overview not work

### ISSUE THREAD

**Issue by lucar91** [openwrt/luci#2692]
Hi, I don't know if in this section I will get a solution, but I want to try anyway. 

I have installed   Openc2x.ipk in my lede 17.01.6 system. In the overview section, I can't see the information. I attached my screenshot. Does someone know a solution for this problem?
 
![Screenshot_2019-05-07 ARDUINO-10 - Overview - LuCI](https://user-images.githubusercontent.com/16464135/57290500-cfdce180-70bd-11e9-9c4c-ea2ae0d8c21a.png)

**Comment by jow-** [comment]
Please report the issue here: https://github.com/florianklingler/OpenC2X-feed
