### ISSUE TITLE
aiccu interfaces not supported by LuCI

### ISSUE THREAD

**Issue by l9i** [openwrt/luci#270]
LuCi does not support aiccu interfaces — shows _Unsupported protocol type_ in the interface view.

**Comment by dachande** [comment]
I have made an experimental implementation für AICCU in LuCi which is available through the OpenWrt Forums at https://forum.openwrt.org/viewtopic.php?id=55056

**Comment by hnyman** [comment]
This should be closed, as #315 added support for aiccu.
