### ISSUE TITLE
luci: wifi: error: iw.hwmodelist is nil

### ISSUE THREAD

**Issue by erdoukki** [openwrt/luci#272]
at line 187 in  luci/modules/admin-full/luasrc/model/cbi/admin_network/wifi.lua ; what if iw..hwmodelist is nil ?
[code]
    m:formvalue(self:cbid(section) .. ".band") or (iw.hwmodelist.g and "11g" or "11a"),
[/code]

**Comment by cshoredaniel** [comment]
Appears to be a bug from an old version; can you verify the same issue occurs with current version (which versions of luci and openwrt)?

**Comment by cshoredaniel** [comment]
Old, bug, no response for month; closing; can be reopened if still and issue
