### ISSUE TITLE
How do i install this theme

### ISSUE THREAD

**Issue by iki789** [openwrt/luci#2721]
I already have LuCI theme openwrt-bootstrap theme installed but i would like to install rosy-theme.

I tried adding src-git luci https://github.com/rosywrt/luci.git to my customfeeds but after updating package list it shows invalid link.

**Comment by dibdot** [comment]
This theme is not in stable tree yet. Just download & install it from latest snapshot, e.g. https://downloads.openwrt.org/snapshots/packages/x86_64/luci/

**Comment by iki789** [comment]
Thank you 👍
