### ISSUE TITLE
luci-app-watchcat does not accept multiple hosts

### ISSUE THREAD

**Issue by PieBru** [openwrt/luci#2727]
Hi,
while uci and watchcat.sh seems to accept a list as "pinghosts", Luci doesn't.
My intended usage is to reboot the border/dmz router if an external OR a dmz ping fails, i.e.:
uci set system.@watchcat[0].pinghosts="8.8.8.8 hassio.local"

Thanks,
Piero

**Comment by PieBru** [comment]
Edit: while it remains technically correct, I realized the issue above is silly because lucy-app-watchcat offers to add multiple "rules", so the problem I exposed is easily circumvented.
I leave up to you to close the issue.
Thanks for all,
Piero

**Comment by feckert** [comment]
I don't think that's relevant anymore.
