### ISSUE TITLE
Randomly lose data when saving SimpleForm field

### ISSUE THREAD

**Issue by osdu** [openwrt/luci#2737]
Randomly lose data when saving SimpleForm field 

https://downloads.openwrt.org/releases/18.06.2/targets/x86/64/openwrt-18.06.2-x86-64-combined-ext4.img.gz

![s](https://user-images.githubusercontent.com/2067880/58688813-0acdee80-83b8-11e9-9b5a-a48c5658452a.gif)

**Comment by dibdot** [comment]
not reproducible with current master, press "enter" to finish your input and submit afterwards.

**Comment by osdu** [comment]
@dibdot 

![s](https://user-images.githubusercontent.com/2067880/58929123-1dfe0700-8788-11e9-917f-6a7f2a92e79b.gif)


Click submit multiple times to randomly lose data
