### ISSUE TITLE
luci-app-statistics - only 30secs minimum step

### ISSUE THREAD

**Issue by BlueMax** [openwrt/luci#2741]
I'm trying to get more steps per minute. Currently the x-resolution is 4 values per minute. I already set 'Data collection interval' and 'RRD step interval' to 10secs but nothing changes.
Any idea what's wrong?

![sensors](https://user-images.githubusercontent.com/1403092/58755705-75cb1280-84e9-11e9-9b1b-4be0f73452a1.png)

**Comment by feckert** [comment]
I have found this hint in the collectd docu:

> Sets a plugin-specific interval for collecting metrics. This overrides the global Interval setting. If a plugin provides its own support for specifying an interval, that setting will take precedence.

I have also seen in the docu of collectd that if you change the global interval config, then you have to delete the rrd files.

> 
>     Configures the interval in which to query the read plugins. Obviously smaller values lead to a higher system load produced by collectd, while higher values lead to more coarse statistics.
> 
>     Warning: You should set this once and then never touch it again. If you do, you will have to delete all your RRD files or know some serious RRDtool magic! (Assuming you're using the RRDtool or RRDCacheD plugin.)

Independently I think that this is not a problem of the luci-app-statistics but is more related to the collectd configuration.
