### ISSUE TITLE
luci does not support qmi modems

### ISSUE THREAD

**Issue by luizluca** [openwrt/luci#275]
These modems are getting popular:

http://wiki.openwrt.org/doc/recipes/3gdongle#devices_using_qmi_and_mbim_protocol

**Comment by wschlich** [comment]
I'd also love to have uqmi proto support in luci.

Currently, I have to use uci to configure qmi devices:

uci set network.wdm0=interface
uci set network.wdm0.proto='qmi'
uci set network.wdm0.device='/dev/cdc-wdm0'
uci set network.wdm0.pin='0000'
uci set network.wdm0.apn='internet.telekom'
uci set network.wdm0.username='t-mobile'
uci set network.wdm0.password='tm'
uci set network.wdm0.auth='pap'
uci set network.wdm0.modes='all'
uci set network.wdm0.delay='10'

uci set network.wwan=interface
uci set network.wwan.proto='dhcp'
uci set network.wwan.ifname='wwan0'

**Comment by cron410** [comment]
The problem is not all modems respond to QMI commands the same way. I currently have a "Netgear" Sierra/Qualcomm 341u that responds to the QMI Disconnect command with "No Effect" and cannot be switched to 802.3 mode unless the modem is in a Disconnected state.

**Comment by cshoredaniel** [comment]
@luizluca @cron410  @wschlich Can you help by testing PR#840

**Comment by cron410** [comment]
Would I have to compile an image? Never been successful with that. I'm running openwrt x86.

**Comment by luizluca** [comment]
@cshoredaniel  I'll try todo it on monday as I don't have a modem with me.
@cron410 , compiling luci would be enough but it's easier to just build it all. Not only compile luci, you would need to use this PR source as it is not merged yet.

**Comment by cron410** [comment]
Yea probably won't have time this weekend for that. I'm terrible at
compiling things and adding source patches. More of a sysadmin making my
baby steps into dev.

**Comment by cshoredaniel** [comment]
Hey no worries any time you have is good; I'm when I can too, although that is more than usual right now!

**Comment by cshoredaniel** [comment]
QMI added with merge of https://github.com/openwrt/luci/pull/840
