### ISSUE TITLE
TL-WR941ND v5  No Access Admin

### ISSUE THREAD

**Issue by ezaul** [openwrt/luci#2750]
https://repo.libremesh.org/releases/18.06.1/targets/ar71xx/generic/tl-wr941nd-v5/lime_mini/
lede-17.01.2-lime-mini-ar71xx-generic-tl-wr941nd-v5-squashfs-factory.bin

No password set!
There is no password set on this router. Please configure a root password to protect the web interface and enable SSH.
Go to password configuration...

http://192.168.10.107/cgi-bin/luci/admin/system/admin

usr/lib/lua/luci/dispatcher.lua:327: Access Violation
The page at 'admin/system/admin/' has no parent node so the access to this location has been denied.
This is a software bug, please report this message at https://github.com/openwrt/luci/issues
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:327: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

**Comment by jow-** [comment]
Please report this issue to the LIME developers. Admin access works as epxected on vanilla OpenWrt images.
