### ISSUE TITLE
luci does not show 3g-xxx devices on realtime traffic

### ISSUE THREAD

**Issue by luizluca** [openwrt/luci#276]
Hello,

When I connect using a acm modem, I get a 3g-nameofmyinterface device.
However, luci realtime graphs does not list it. Using a qmi modem, which creates a wwan0 interface, I have no problem.

**Comment by luizluca** [comment]
I'm using Luci shipped with bb.

**Comment by Wedmer** [comment]
As I have some time I'll investigate this problem.

**Comment by cshoredaniel** [comment]
BB is not longer being updated; please reopen if this issue occurs in current LuCI
