### ISSUE TITLE
Issue in LuCI System → Startup 

### ISSUE THREAD

**Issue by 1Jeff1** [openwrt/luci#2760]
After commit https://github.com/openwrt/luci/commit/1c09ee5e42550d6339bffa58d4cba3461948e19c using any of the web buttons in LuCI System → Startup erase all the content in /etc/rc.local
![Screenshot_20190612_032803](https://user-images.githubusercontent.com/46228800/59332143-95b9bd80-8cc3-11e9-816f-4e083c865761.png)

**Comment by frtz13** [comment]
found the issue in the 18.06.4 stable release, in a Meraki MR33 and a Zyxel NBG6616.

NB: first time posting here. not sure about the "closed" status of the issue, and if this is the right place.

**Comment by henok400** [comment]
I have got the same issue I put my script in startup then save but one app make stop in the list of startup the rc.local captain script erase and become empty. This happen openwrt 18.06.4 
Please Developer fix bugs issue
