### ISSUE TITLE
Add definition of "CBI" to wiki page

### ISSUE THREAD

**Issue by POTSandSTOP** [openwrt/luci#2765]
I'm interested in learning more about LuCI and when I went to [CBI · openwrt/luci Wiki](https://github.com/openwrt/luci/wiki/CBI) I couldn't find a definition of CBI. Could someone add one to this Wiki page?

**Comment by feckert** [comment]
I think this is managed in https://github.com/openwrt/luci/blob/master/documentation/CBI.md
