### ISSUE TITLE
troubleshooting commands does not redirect to login page on session end

### ISSUE THREAD

**Issue by luizluca** [openwrt/luci#277]
Hello,

troubleshooting commands page allow ping, traceroute and nslookup. However, when session ends (timeout or reboot), if I issue any of the commands, I get the login page html source inside the command output area. It would be better to check the command result and redirect the page to login on session end.

I'm using Luci shipped with bb.

**Comment by cshoredaniel** [comment]
BB is no longer being updated.  Please reopen if the issue occurs with current LuCI
