### ISSUE TITLE
How can i comment footer section in EDIT page of wireless networks

### ISSUE THREAD

**Issue by joewander** [openwrt/luci#2777]
Hello,

I need a small help. I have less experience working on LUCI.
I wanted to comment on the footer section in Network -> Wifi -> Click on EDIT  button of any wireless network.
- In the EDIT page, I wanted to remove the **save&apply, revert, save** options at the bottom of this webpage.
Can anyone help me how (or) in which file can I comment this section?

Thanking you in advance..!

**Comment by dibdot** [comment]
CBI map buttons can be controlled through the "flow" property of a map. This value is not set in the model, but in the controller entry for that page.

The options are: skip, autoapply, hidesavebtn, hideresetbtn, and hideapplybtn - just search for these options in the luci source to get example implementations. For further questions please join the OpenWrt forum - this is a ticket system not an additional support channel.

Thanks!
