### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 9000000** [openwrt/luci#2780]
/usr/lib/lua/luci/dispatcher.lua:247: /etc/config/luci seems to be corrupt, unable to find section 'main'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:247: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:144: in function </usr/lib/lua/luci/dispatcher.lua:143>

**Comment by dibdot** [comment]
Make sure that your rpcd daemon is running (/etc/init.d/rpcd restart).

**Comment by alexshalex** [comment]
OpenWrt SNAPSHOT, r10293-a8f0c02f80 on Xiaomi Mi Router 3G same mistake
