### ISSUE TITLE
[bug]  uci: Parse error (too many arguments) at line 42, byte 36

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#2782]
- 19.07 
- LuCI git-19.172.06594-1afa6c4-1.0
- luci-theme-material git-19.171.44055-835d4b3-1.0
___

recent updates seems to have introduced a regression of sorts:

> src/lib/subprocess.c:107 (subprocloc):Running subprocess: /usr/lib/opkg/info//luci-theme-material.postinst configure
> uci: Parse error (too many arguments) at line 42, byte 36

`cat /usr/lib/opkg/info//luci-theme-material.postinst`

>     #!/bin/sh
>     [ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
>     [ -x ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
>     . ${IPKG_INSTROOT}/lib/functions.sh
>     default_postinst $0 $@
____

`luci-theme-material` is just one example, there are other packages exhibiting the same issue - printing the same output.

I cannot figure out where the stanza that is being parsed `at line 42, byte 36` is supposedly located.

**Comment by jow-** [comment]
One of your uci files in `/etc/config/` is broken. Use something like `for x in /etc/config/*; do uci show "${x##*/}" >/dev/null || echo "$x is broken"; done` to figure out which file.
