### ISSUE TITLE
package that is not installed showing in LuCI as installed/updatable

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#2786]
* 19.07
* `luci `git-19.174.85707-a5f0e14-1.0
* `luci-app-opkg` git-19.174.85707-a5f0e14-1.0
* `luci-base` f138fc93-1.15
___

Observed this curious case of a package that is not installed showing in LuCI as installed/updatable however

`opkg -V2 info ntpd`
> opkg_conf_parse_file: Loading conf file /etc/opkg.conf.   
> opkg_conf_parse_file: Loading conf file /etc/opkg/customfeeds.conf.   
> opkg_conf_parse_file: Loading conf file /etc/opkg/distfeeds.conf.   
> pkg_hash_load_feeds:   
> pkg_hash_load_status_files:   
> Package: ntpd   
> Version: 4.2.8p13-1.36   
> Depends: libc, libopenssl, libpthread, libcap, ntp-utils   
> **Status**: unknown ok **not-installed**   
> Section: net   
> Architecture: arm_cortex-a9_vfpv3   
> Size: 258445   
> Filename: ntpd_4.2.8p13-1_arm_cortex-a9_vfpv3.ipk   
> Description: The ISC ntp suite is a collection of tools used to synchronize the   
>  system clock with remote NTP time servers and run/monitor local NTP   
>  servers.   
>  .   
>  This package contains the ntpd server.   
> 
> Package: ntpd   
> Version: 4.2.8p11-1.13   
> Depends: libc, libopenssl, libpthread, libcap, ntp-utils   
> **Status**: install user **not-installed**   
> Architecture: arm_cortex-a9_vfpv3 
 
_versus_

![luci_package](https://user-images.githubusercontent.com/13611490/59998541-ff40b100-965f-11e9-8116-7c1623aad4c3.png)

**Comment by jow-** [comment]
16df8c93f
