### ISSUE TITLE
transition to nftables - likely to break LuCI?

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#2790]
* 19.07
___
preparing to transit the node from `ip(6)tables` to `nftables` and due diligence done with

* `opkg whatdepends firewall`  
* `opkg whatdepends iptables`  
* `opkg whatdepends ip6tables`  
* `opkg whatdepends ipset`

shows that

* > luci-app-firewall git-19.176.45126-8f3cf8a-1.0  depends on firewall

* > luci git-19.176.45126-8f3cf8a-1.0       depends on luci-app-firewall

`luci-app-firewall` is comprehended/logical but `luci`'s dependency in turn on `luci-app-firewall` not so much.

Will this cause a causality train with the transition to `nftables` and LuCI becoming inaccessible?

**Comment by jow-** [comment]
`luci` is an empty meta package to select commonly used components. If you want a LuCI installation without `luci-app-firewall` simply install the required components (`uhttpd, luci-mod-admin-full, luci-theme-bootstrap, luci-app-opkg, luci-proto-ppp, libiwinfo-lua, luci-proto-ipv6, rpcd-mod-rrdns`) manually without using the `luci` meta package.
