### ISSUE TITLE
IPv6 prefix from the VPN server side

### ISSUE THREAD

**Issue by Bernd145** [openwrt/luci#2813]
Hello.

I have this script:

> opkg update
> opkg install kmod-ipt-nat6
> cat << EOF > /etc/firewall.nat6
> iptables-save --table="nat" \
> | sed -e "/\s[DS]NAT\s/d" \
> | ip6tables-restore --table="nat"
> EOF
> uci -q delete firewall.nat6
> uci set firewall.nat6="include"
> uci set firewall.nat6.path="/etc/firewall.nat6"
> uci set firewall.nat6.reload="1"
> uci commit firewall
> service firewall Restart
> 

from [here.](https://openwrt.org/docs/guide-user/services/vpn/openvpn/extra#dual-stack_gateway)

This script requests a public IPv6 prefix on the VPN server side. The problem is, it only works with one OpenVPN client.

If I create multiple OpenVPN clients, then it requests wrong public IPv6 prefixes from the VPN server.

Consequence:
- Routing is not correct then
- Packages like VPN Policy Routing do not work

An extension of this script would not be bad.

**Comment by jow-** [comment]
Does not seem to be LuCI related.
