### ISSUE TITLE
(luci-app-wol) iOS Safari, MAC address input text doesn't displayed properly.

### ISSUE THREAD

**Issue by intdev32** [openwrt/luci#2819]
(luci-app-wol)

Browser: iOS Safari. (iOS 12)

Services > Wake on LAN

Host to wakeup: choose "custom" (bottom of list)

And type MAC address. But cannot see text.

Texts cutted out almost area.

Here is screenshot:
![1](https://user-images.githubusercontent.com/46291948/60632833-c9ab7d00-9e42-11e9-98bc-68263d92d7ae.png)

**Comment by feckert** [comment]
Which theme do you use and which openwrt version to you have master 19.07 18.06 or 15.05

**Comment by feckert** [comment]
No reaction from issue creator
