### ISSUE TITLE
COMPILE ERROR: luci-lib-luaneightb - No rule to make target `install'.

### ISSUE THREAD

**Issue by thuehn** [openwrt/luci#282]
After the last luci commits from yesterday (8.Jan 2015) I get the following compile error on luci-lib-luaneightb in Openwrt trunk:

touch /home/thomas/BB-evernet/staging_dir/target-i386_i486_uClibc-0.9.33.2/root-x86/stamp/.luci-app-ddns_installed
make[3]: Leaving directory `/home/thomas/BB-evernet/feeds/luci/applications/luci-app-ddns'
make[3]: Entering directory `/home/thomas/BB-evernet/feeds/luci/libs/luci-lib-luaneightbl'
mkdir -p /home/thomas/BB-evernet/bin/x86/packages /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-x86/luci-lib-luaneightbl/CONTROL /home/thomas/BB-evernet/staging_dir/target-i386_i486_uClibc-0.9
.33.2/pkginfo
if [ -d /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/luasrc ]; then install -d -m0755 /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-x86/luci-lib-luan
eightbl/usr/lib/lua/luci; cp -pR /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/luasrc/* /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-x86/luci-lib-lua
neightbl/usr/lib/lua/luci/; true; else true; fi
if [ -d /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/htdocs ]; then install -d -m0755 /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-x86/luci-lib-luan
eightbl/www; cp -pR /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/htdocs/* /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-x86/luci-lib-luaneightbl/www/
; else true; fi
if [ -d /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/root ]; then install -d -m0755 /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-x86/luci-lib-luanei
ghtbl/; cp -pR /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/root/* /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-x86/luci-lib-luaneightbl/; else true
; fi
if [ -d /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/src ]; then     CFLAGS="-O2 -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -I/home/thomas/BB-evernet/st
aging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/thomas/BB-evernet/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/thomas/BB-evernet/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/h
ome/thomas/BB-evernet/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include " CXXFLAGS="-O2 -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -I/home/thomas/BB-evernet/staging_dir/targe
t-i386_i486_uClibc-0.9.33.2/usr/include -I/home/thomas/BB-evernet/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/thomas/BB-evernet/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/thomas/BB-e
vernet/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/thomas/BB-evernet/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib -L/home/thomas/BB-evernet/staging_dir/target-i386_i486_uClibc-0.9.33.2/
lib -L/home/thomas/BB-evernet/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/thomas/BB-evernet/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/lib " make -C /home/thomas/BB-evernet/build_dir/t
arget-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/. AR="i486-openwrt-linux-uclibc-gcc-ar" AS="i486-openwrt-linux-uclibc-gcc -c -O2 -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable" LD=i486-openwrt-li
nux-uclibc-ld NM="i486-openwrt-linux-uclibc-gcc-nm" CC="i486-openwrt-linux-uclibc-gcc" GCC="i486-openwrt-linux-uclibc-gcc" CXX="i486-openwrt-linux-uclibc-g++" RANLIB="i486-openwrt-linux-uclibc-gcc-ranlib" STRIP=i486-openwrt-linux-uclibc-st
rip OBJCOPY=i486-openwrt-linux-uclibc-objcopy OBJDUMP=i486-openwrt-linux-uclibc-objdump SIZE=i486-openwrt-linux-uclibc-size CROSS="i486-openwrt-linux-uclibc-" ARCH="i386" DESTDIR="/home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0
.9.33.2/luci-lib-luaneightbl/ipkg-install"  install; cp -fpR /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-install/* /home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib
-luaneightbl/ipkg-x86/luci-lib-luaneightbl/; else true; fi
make[4]: Entering directory `/home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl'
make[4]: *** No rule to make target `install'.  Stop.
make[4]: Leaving directory `/home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl'
cp: cannot stat '/home/thomas/BB-evernet/build_dir/target-i386_i486_uClibc-0.9.33.2/luci-lib-luaneightbl/ipkg-install/*': No such file or directory
make[3]: *** [/home/thomas/BB-evernet/bin/x86/packages/luci/luci-lib-luaneightbl_git-15.008.57171-b348413-1_x86.ipk] Error 1
make[3]: Leaving directory `/home/thomas/BB-evernet/feeds/luci/libs/luci-lib-luaneightbl'
make[2]: *** [package/feeds/luci/luci-lib-luaneightbl/compile] Error 2
make[2]: Leaving directory `/home/thomas/BB-evernet'
make[1]: *** [/home/thomas/BB-evernet/staging_dir/target-i386_i486_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/thomas/BB-evernet'
make: *** [world] Error 2

Something missing in the Makefile or rule.mk ?

Greetings Thomas

**Comment by jow-** [comment]
Should be fixed with 3c6d03d
