### ISSUE TITLE
"Collections" has not been selectable on trunk buildroot.

### ISSUE THREAD

**Issue by KazukiShimada** [openwrt/luci#284]
Hi.
On trunk buildroot, this has not been selectable.
make menuconfig -> luci -> Collections

**Comment by chris5560** [comment]
Am 10.01.2015 um 04:28 schrieb KazukiShimada:
> Hi.
> On trunk buildroot, this has not been selectable.
> make menuconfig -> luci -> Collections
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/openwrt/luci/issues/284>.
> 
Select Language->lua first then it is selectable

Change needed in feeds/luci/modules/luci-base/Makefile
	LUCI_DEPENDS:=+lua
There must be a "+" in front of "lua"
