### ISSUE TITLE
[potential bug] luci-proto-ppp requesting package that is not available

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#2847]
* 19.07
* luci-proto-ppp  git-19.190.43457-7728bf3-1.0
* kmod-pppoa Version: 4.14.131-1.0 (is installed)
____
that package is not available from the feed stream (and does not seem required by luci-proto-ppp)

![Annotation 2019-07-09 202742](https://user-images.githubusercontent.com/13611490/60913629-1dc1c180-a288-11e9-9831-2e236c283231.png)
___
![Annotation 2019-07-09 203948](https://user-images.githubusercontent.com/13611490/60914440-d63c3500-a289-11e9-9220-f02f619b56c2.png)

**Comment by jow-** [comment]
https://downloads.openwrt.org/releases/packages-18.06/x86_64/base/ppp-mod-pppoa_2.4.7-12_x86_64.ipk

**Comment by n8v8R** [comment]
Testing 19.07 and that is where it happens. Thought to let you know at least.

**Comment by jow-** [comment]
There are no 19.07 binaries yet at all on the download server - this is maybe the reason.
