### ISSUE TITLE
[precautionary suggestion] firewall - display flow offloading options only for working/intended target(s)

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#2848]
https://forum.openwrt.org/t/flow-offloading-1-is-broken-on-latest-snapshot-4-19-issue/40392/8

Leaving it enabled for all/any target(s) may confuse the user and could lead to unintended consequences.

Though it clearly states

> Experimental feature

that is what users might actually be tempted to do...

**Comment by jow-** [comment]
This is impossible to mplement in LuCI since there is no programmatic way to query the support state - it needs to be solved in OpenWrt.
