### ISSUE TITLE
Firewall configuration cannot be saved from Luci 

### ISSUE THREAD

**Issue by rankaiyx** [openwrt/luci#2852]
Firewall configuration cannot be saved from Luci 
openwrt version: 19.07 20190710
Hardware:CPU MT7620N   ROM 8MBytes   RAM 64MBytes
Can be changed from config file:  /etc/config/firewall
config zone
        option name 'lan'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option network 'lan'

**Comment by jow-** [comment]
Please elaborate - what means "cannot be saved" ? Do you get an error?

**Comment by rankaiyx** [comment]
> Please elaborate - what means "cannot be saved" ? Do you get an error?
1 select "ACCEPT" or "reject"
2 click "save and apply" 
3 "ACCEPT" or "reject" will become "please choose"
 After modifying the configuration file,  can see the changes from LUCI.
There's no information because that's the GUI, but it feels like it stops running for about 10 seconds.

**Comment by rankaiyx** [comment]
![无标题](https://user-images.githubusercontent.com/39045067/61030849-e6225900-a3f0-11e9-9c9a-18b2883ec5b5.jpg)

**Comment by rankaiyx** [comment]
There's no information about that in system log

**Comment by jow-** [comment]
Please provide the exact version number reported at the index page.

**Comment by rankaiyx** [comment]
> Please provide the exact version number reported at the index page.

MediaTek MT7620N ver:2 eco:3
OpenWrt SNAPSHOT r10459-1174b94bc9 / LuCI Master (git-19.190.57021-ffdafd4)
4.14.132

**Comment by fishxz** [comment]
still unable to apply firewall changes

OpenWrt SNAPSHOT r10495-ba5878f056 / LuCI Master (git-19.193.31361-7c9d845)

**Comment by rankaiyx** [comment]
I modified the UI. JS file to follow JOW's new code, but the bug still exists.
Although there are two UI.JS files, one of which is under the /ROM directory and cannot be modified, its priority is lower than that of the file that can be modified. It should be possible not to modify this file.
