### ISSUE TITLE
luci-mod-network: doesn't show the correct status of temporarily enabled wireless iface

### ISSUE THREAD

**Issue by hanipouspilot** [openwrt/luci#2855]
I previously asked about almost the same issue and you said that now Luci ignores global UCI temps, that looks good for me. But there is still an issue.

I have 'guest' interface in addition to a normal one that is disabled by default.
It can be enabled by a script (uci command without a commit). And the iface is disabled by a cron script not to forget to turn it off.

When guest interface is enabled, Luci keeps showing it as disabled. But associatied stations are shown correctly with guest SSID. That doesn't look correct.

Luci should show real status of all interfaces no matter if they are permanently or temporarily enabled.

**Comment by jow-** [comment]
This will not be fixed since LuCI uses isolated uci states, it is not able to see uncommitted system uci changes.
