### ISSUE TITLE
Showing HTML code of single quote character instead of symbol in Disconnect button

### ISSUE THREAD

**Issue by YuriPet** [openwrt/luci#2856]
In Bootstrap and OpenWrt themes showing HTML code of single quote character instead of symbol in "Disconnect" button.
![000](https://user-images.githubusercontent.com/11704993/61128165-e89cb580-a4b9-11e9-828b-ecdef4ffb42b.png)
![111](https://user-images.githubusercontent.com/11704993/61128439-81333580-a4ba-11e9-825d-dbbc51335662.png)

**Comment by YuriPet** [comment]
Obviously, nobody is interested in correcting this error.
So I went bypass – instead "Single quote" or "Apostrophe" (U+0027), I used the "Modifier letter apostrophe" (U+02BC).

![222](https://user-images.githubusercontent.com/11704993/61331093-e9bb4300-a829-11e9-9eac-993aa03f710f.png)

Closed!

**Comment by jow-** [comment]
> Obviously, nobody is interested in correcting this error.

I am, but didn't find time yet to look into it. As in interim solution, the use of another unicode character looks good to me :+1:

**Comment by YuriPet** [comment]
But still this is a "temporary" solution.
I believe that it is still necessary to make corrections in the corresponding code.

**Comment by jow-** [comment]
Of course, I just need to carefully review the code to not accidentally open any XSS holes.

**Comment by pjuhen** [comment]
Same issue for me
