### ISSUE TITLE
luci-theme-rosy: MAC-Address & IPv4-Address drop down boxes are not visible for the last entries on the Network / DHCP and DNS page

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#2868]
OpenWRT: 19.07-SNAPSHOT

Latest Firefox on MacOS: when adding a new entry to the Static Leases list, the drop down boxes are hidden for MAC & IPv4 are hidden and the only way to use them is to switch the Bootstrap them. My Static leases list is ~50 entries long.
Those drop downs are only fully visible starting for the five row from the bottom.

@rosysong

**Comment by cc5771027** [comment]
Can you provide a screenshot?

**Comment by fantom-x** [comment]
The drop down boxes are covered by the white border.

<img width="725" alt="1" src="https://user-images.githubusercontent.com/5624569/61568516-99262e80-aa51-11e9-83ed-3beda936d555.png">
<img width="1140" alt="2" src="https://user-images.githubusercontent.com/5624569/61568523-9c211f00-aa51-11e9-8fc7-91ebda208c81.png">

**Comment by rosysong** [comment]
@fantom-x  And please tell me your firefox version ? Or update your firefox browser to latest and have a try again.

**Comment by fantom-x** [comment]
68.0.1; there is no later version than this.

**Comment by CCnut** [comment]
what's your luci-theme-rosy version?

**Comment by rosysong** [comment]
@fantom-x  It seems you should bump your source code to latest 19.07 commit.

**Comment by fantom-x** [comment]
luci-theme-rosy - git-19.190.55584-ab90938-1

OpenWrt 19.07-SNAPSHOT r10269-5100629e32 / LuCI openwrt-19.07 branch (git-19.190.55584-ab90938) 

This is from the build from scratch a few hours ago. The issue is still there. Are you saying that it is not present for you?

**Comment by fantom-x** [comment]
It is not happening in Chrome: the bottom whit band drops lower and I can see a few lines of the list and can scroll it.

**Comment by rosysong** [comment]
@fantom-x  @CCnut Strange, below is the screenshot from our firefox browser(68.0.1) on 19.07 branch.

![p1](https://user-images.githubusercontent.com/37688994/62018447-58ff4280-b1ed-11e9-836f-b61d749716dc.jpg)
![p2](https://user-images.githubusercontent.com/37688994/62018449-5997d900-b1ed-11e9-8132-aedeceb91ffa.jpg)

**Comment by fantom-x** [comment]
Try editing in-place. I think you pressed the **Edit** button here. Instead, go back to the list of static IPs and click on the drop down box on the last row.

**Comment by fantom-x** [comment]
Interesting, I do not see the **Edit** button in my 19.07 firmware; only **Delete** is visible on the right side. Either way, click on the arrow to the right of each drop down box on the last row.

It is hard to tell, it looks like the drop down boxes are not present on the screenshots you provided. Is 19.07 build pulling the right source?

<img width="520" alt="dhcp" src="https://user-images.githubusercontent.com/5624569/62048398-cbb2f280-b1da-11e9-8fdf-181e7c6be58d.png">

**Comment by fantom-x** [comment]
My screenshot above is showing the arrows on the right side of the IP drop down box. It is the one that needs to be clicked on on the last row and the dropdown box is hidden under the white ribbon.

**Comment by rosysong** [comment]
@fantom-x  Sorry, there are no drop down box now, only popup window.

**Comment by rosysong** [comment]
> luci-theme-rosy - git-19.190.55584-ab90938-1
> 
> OpenWrt 19.07-SNAPSHOT r10269-5100629e32 / LuCI openwrt-19.07 branch (git-19.190.55584-ab90938)
> 
> This is from the build from scratch a few hours ago. The issue is still there. Are you saying that it is not present for you?

```
git pull --rebase
 ./scripts/feeds update -a
 ./scripts/feeds install -a
rm -rf bin
make clean
make
```

**Comment by jow-** [comment]
The LuCI openwrt-19.07 branch differs from master.

**Comment by fantom-x** [comment]
If LuCI is different in 19.07 and master, then that explains the different behaviour. This is really a cosmetic issue and an annoyance. I can always switch back to Bootstrap or edit the file directly.

**Comment by hnyman** [comment]
The broken theme has been removed.
