### ISSUE TITLE
Luci graphical issues with chrome

### ISSUE THREAD

**Issue by MSC2016** [openwrt/luci#2881]
The best way is to show what i am talking about:
![luciWebInterface](https://user-images.githubusercontent.com/17535858/61450289-a60e2980-a94e-11e9-8586-1472d3fd96db.png)

Is anybody else having problems lik this?

lynksys wrt32x
Powered by LuCI openwrt-18.06 branch (git-19.170.32094-4d6d8bc) / OpenWrt 18.06.4 r7808-ef686b7292

**Comment by jow-** [comment]
Already fixed with https://github.com/openwrt/luci/commit/9c5162d5967a56f2ca1ed6e84169c1b96b35d3ae

You cna run `opkg update; opkg upgrade luci-theme-bootstrap` to resolve this glitch.

**Comment by MSC2016** [comment]
LOL, thank you for your very fast response, you litteraly took less than 20 seconds to answer. SOLVED...
