### ISSUE TITLE
luci-theme-rosy: Network / Firewall / Zones is cut off and can not be scrolled horizontally

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#2887]
OpenWRT: 19.07-SNAPSHOT

Latest Firefox on MacOS: there is more information to the right of the last visible column, but it is hidden.

@rosysong

<img width="1160" alt="3" src="https://user-images.githubusercontent.com/5624569/61568677-2bc6cd80-aa52-11e9-9999-0346b3cd7214.png">

**Comment by rosysong** [comment]
@fantom-x  please try this patch https://github.com/openwrt/luci/pull/2913

**Comment by fantom-x** [comment]
It is now looking like this. A little messier, but all information is visible.

<img width="1139" alt="fw" src="https://user-images.githubusercontent.com/5624569/61813740-7e1e3a80-ae14-11e9-9fa2-f0638f552fc3.png">

**Comment by rosysong** [comment]
@fantom-x Would you please close this issue if it was fixed, thanks!

**Comment by fantom-x** [comment]
I have just re-spun a new firmware image (19.07) by using the image builder and the issue is still present. It is either the package is not rebuilt yet, or 19.07 is not pulling the right sources code.

Yeah, looks like it is five day old at this time.

<img width="1129" alt="rosy" src="https://user-images.githubusercontent.com/5624569/62048832-d621bc00-b1db-11e9-9c33-004369e1999c.png">

**Comment by hnyman** [comment]
The broken theme has been removed.
