### ISSUE TITLE
LUCI installation issue on ubuntu 16.04

### ISSUE THREAD

**Issue by syedumerbukhari** [openwrt/luci#2919]
hi, 
I'm trying to install LUCI application on ubuntu 16.04 by following this tutorial. [install LUCI on Ubuntu](https://www.cnblogs.com/luopeng/p/4678704.html). 

when I run "make runuhttpd" I'm getting this error:
""""""""
root@toor-VirtualBox:/home/Openwrt/luci# svn info svn://svn.openwrt.org/openwrt/branches/backfire/package/uhttpd/src
svn: E170013: Unable to connect to a repository at URL 'svn://svn.openwrt.org/openwrt/branches/backfire/package/uhttpd/src'
svn: E670002: Unknown hostname 'svn.openwrt.org'
""""""""
_________________________
According to this error it means server is not alive. 

is there any way to figure it out.

Urgent request :)

Thanks in advance.

**Comment by hnyman** [comment]
There is no svn server any more.
That external Chinese guide is likely outdated.

I close this issue, as installing LuCI separately from OpenWrt is not intended.
