### ISSUE TITLE
Git status shows unknown binary file modules/luci-base/src/po2lmo

### ISSUE THREAD

**Issue by hnyman** [openwrt/luci#292]
The new build system introduced by https://github.com/openwrt/luci/commit/1bb4822dca6113f73e3bc89e2acf15935e6f8e92 apparently compiles a binary "po2lmo" into the source dir of luci-base:
https://github.com/openwrt/luci/blob/master/modules/luci-base/Makefile#L30
and then the file is copied to the $(STAGING_DIR_HOST)/bin directory:
https://github.com/openwrt/luci/blob/master/modules/luci-base/Makefile#L37

"git status" for luci shows the file as unknown. Should the file be added into .gitignore of luci, so that the leftover file would not be visible in git status?

```
perus@ub1410:/Openwrt/trunk/feeds/luci$ git status --porcelain
M  applications/luci-app-statistics/root/etc/config/luci_statistics
M  modules/luci-base/root/etc/config/luci
M  modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
M  modules/luci-mod-admin-full/luasrc/view/admin_system/flashops.htm
?? modules/luci-base/src/po2lmo
```
Or should the file be removed after being copied to $(STAGING_DIR_HOST)/bin ?

**Comment by jow-** [comment]
Added it to .gitignore, thanks.
