### ISSUE TITLE
[luci-app-vpn-policy-routing] columns are too wide | wasting space and distorting the layout

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#2922]
as described https://github.com/stangri/openwrt_packages/issues/69

happens with different browser flavours such as FF, Edge and Chrome derivates

**Comment by n8v8R** [comment]
For some reason the outer width of the table cells in question compute to 320

![Annotation 2019-07-26 211044](https://user-images.githubusercontent.com/13611490/61975618-e07c6400-afe9-11e9-9e17-7f746b65832a.png)

**Comment by dibdot** [comment]
There is no such app in this repo, please clarify your issues with the developer directly. If you're are not satisfied with the measurements of the default templates, you can change nearly every aspect of your app design with a bit of customization of these.

**Comment by n8v8R** [comment]
the app developer cited

> AFAIK, this is auto-set by Luci, I have no control over this.

**Comment by n8v8R** [comment]
I would appreciate this being reopened. Reason is that the ccs width is set to auto and thus not the app developer's fault that that cell is wasting space and since it happens in other LuCI modules as well

![Annotation 2019-07-27 105611](https://user-images.githubusercontent.com/13611490/61992360-89b07200-b05d-11e9-87a1-f9f776ff91b0.png)

**Comment by jow-** [comment]
Note that you're using an unsupported template. When checking with the default luci-theme-bootstrap, the application looks normal here.

**Comment by n8v8R** [comment]
Thanks for the feedback. Indeed, out of 4 themes (bootstrap| rosy | OpenWrt | material) on the material exhibits the issue,

**Comment by stangri** [comment]
@dibdot @jow : if you can educate me how can I explicitly set the widths of columns, ideally without packaging my own copy of view/cbi/tblsection, I'd be much obliged.
