### ISSUE TITLE
refer to Luci wiki ,i type “make runhttpd",but there is No rule to make target `runhttpd'

### ISSUE THREAD

**Issue by shindowarch** [openwrt/luci#293]
i download the luci-0.12 package,and unzip the package,
then
cd luci
make
but there is No rule to make target `runhttpd'

**Comment by kumarrishav** [comment]
@jow-  any update on this or any other way to build and run Luci?

**Comment by jow-** [comment]
I suggest to build LuCI as part of OpenWrt and then use an SSHFS mount or an SFTP capable editor to edit LuCI directly on the target system.

The environment required to run LuCI (uhttpd, ubus, libubox, rpcd, uci ...) became too huge so its not feasible to simulate it on a desktop anymore.

**Comment by errorcode7** [comment]
the makefile has a target `runuhttpd' ,but wen i run make there is no config.mk file in build dir,s there anything wrong with me?
i just want to run the luci in my archlinux,is that possible?

**Comment by cshoredaniel** [comment]
runuhttpd no longer supported.
