### ISSUE TITLE
[openwrt-19.07] luci-base: list element wont get saved if  save&apply was pressed

### ISSUE THREAD

**Issue by feckert** [openwrt/luci#2938]
- Perceived behavior:
If you do not press explicit the **"+"** button on a list element before **save&apply** the value will not get saved in the configuration and is lost. 

- Expected behavior:
If I add a new element to a list value and do **not** press explicit the **"+"** button before pressing **save&apply** the configuration should be saved anyway.

- Procedure for reproduction:
On the LuCI page go to **/cgi-bin/luci/admin/system/system** and add a new time sync server. without explicit press the **"+"** button before **save&apply**

I do not know since this has changed! But this has worked definitely before. I think this has something todo with javascript but @jow- I am helpless what the problem could be.

**Comment by feckert** [comment]
Thanks @jow- 
That was really quick.
:+1:

**Comment by feckert** [comment]
This also does not work for openwrt-19.06.
There were a lot of changes!
So could you please also fix this for this branch as well?

**Comment by jow-** [comment]
@feckert - done.

**Comment by feckert** [comment]
@jow-  on **openwrt-19.07** and **master** it is working now again as expected thanks :+1: for your work

**Comment by feckert** [comment]
@jow- Apparently, it fit. But when looking more closely it only works when the button **Save** is pressed. When **Save & Apply** is pressed the value is **not** taken over. Sorry for the bad news :-(

**Comment by feckert** [comment]
Thanks now it works as expected :-)
