### ISSUE TITLE
LUCI web interface Login Problem as a root

### ISSUE THREAD

**Issue by syedumerbukhari** [openwrt/luci#2971]
Hi.
I have setup fresh Luci successfully but I can't login as root.

**Comment by jow-** [comment]
Works for me. Make sure that rpcd is running.

**Comment by syedumerbukhari** [comment]
> Works for me. Make sure that rpcd is running.

thanks, brother and sorry for the late reply. Actually, I'm running Luci on ubuntu I think thats why having many issues. 
Let me try your suggestion :)
