### ISSUE TITLE
theme-bootstrap: no space between tab-description and first value

### ISSUE THREAD

**Issue by chris5560** [openwrt/luci#298]
If using a tab description there is not enough space left to the first value.
Have a look on attached picture. Tab description touch start button.

![bildschirmfoto - 18 01 2015 - 20 18 08](https://cloud.githubusercontent.com/assets/8249658/5793744/ada28406-9f4f-11e4-8a97-6d52a8d30aca.png)

**Comment by legendtang** [comment]
The latest `luci-app-privoxy` package added three `<br>` beneath the text. It should works well now.
![h dy0h0k0l 4vm 7 w_pt](https://cloud.githubusercontent.com/assets/1352729/6426189/c4b105dc-bf89-11e4-868b-7ca93915fb57.png)

This issue should close now.

**Comment by chris5560** [comment]
Hi Legend,
I opened this issue because it's only a problem of bootstrap-theme, so of bootstrap.css.
I'm not familiar with css, so I can't fix it.
Inside luci-app-privoxy and luci-app-ddns I build a workaround by inserting three <br />.
It's a workaround not a fix.

**Comment by legendtang** [comment]
Hello chris5560,
Sorry for the misinterpretation. I think I should be able to fix them with a pull request.
That means I should remove those `<br />` in these two luci-apps at the same time. Is that right?

**Comment by chris5560** [comment]
Legend,
if you could fix the bootstrap.css I will modify both apps.
I had some other minor changes for those apps pending for distribution.
So all for those apps could be done at once.
Thanks
Christian

**Comment by legendtang** [comment]
Hi Christian,
I have fixed just now. It's because the `form .cbi-tab-descr` has no definition in CSS.
Please remove those `br` as soon as possible.

Thanks
Legend Tang

**Comment by chris5560** [comment]
Fixed. Thanks.
