### ISSUE TITLE
luci-app-firewall: Source NAT missing

### ISSUE THREAD

**Issue by HBerni** [openwrt/luci#2980]
In current trunk I miss the source nat section in
firewall/traffic rules at all.

I browsed the source code, but cannot find any related
code for it. Is the ability to manage source nat discontinued, or
just not implemented yet, or did I fail to find the code for it.

Thanks,
Bernhard

**Comment by jow-** [comment]
It is not implemented yet.

**Comment by jow-** [comment]
It is now implemented in 19.07 / master
