### ISSUE TITLE
Bug.Single netcard OPENWRT router upload speed very slow

### ISSUE THREAD

**Issue by wood350** [openwrt/luci#2984]
I use a vmware virtual os running openwrt 18.06.4，The physical pc only installed one net card. local area net contains a pc of ip 192.168.1.3,Thers is a ftp server running on it,I just map wan ip port 3939 to 192.168.1.3:21, I found the download speed very slow at wan side,only 60KB/S. I tried a nother physical pc with two netcards runing openwrt 18.06.4, this  issue dispeard. the speed at wan side up to 2MB/S。

**Comment by jow-** [comment]
Not LuCI related.

**Comment by wood350** [comment]
hello,Where should I report this bug message?

________________________________
zrhlmc

**Comment by wood350** [comment]
I have known where to put it.
