### ISSUE TITLE
[BUG] Unbridge Interface leads to bad "ifname" value

### ISSUE THREAD

**Issue by sch-m** [openwrt/luci#2997]
@jow- 
When you Uncheck the "Bridge Interfaces" Feature of a bridge interface with more than one selected physical interfaces, the ifname value is not properly cleaned up after save&apply.

I think this is related to this call to get_interfaces() in the ifname_single.write function
https://github.com/openwrt/luci/blob/2aab85814d0eead5f82ee1c5661f03667ce50b62/modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua#L308
because get_interfaces checks for self:is_bridge(), which is not the case after unchecking the "Bridge Inferfaces" checkbox. Therefore, the old_ifs[] array/list does not include all the "old" interfaces.

BTW: Why are the old_ifs explicitly removed here. And what is this backup_ifnames() good for? :-) Can't we just flush the ifname option and add the new selected interface(s)?

**Comment by jow-** [comment]
> Can't we just flush the ifname option and add the new selected interface(s)?

No because the `get_interfaces()` list might also include special wireless identifiers whose removal must be delegated to the wireless config. Merely flushing `option ifname` will not remove the association of `wifi-iface` entries to the bridge being unbridged.

**Comment by sch-m** [comment]
Ah OK, good point. So next question: why is get_interfaces() checking for is_bridge()? Is this really necessary?

**Comment by jow-** [comment]
Not sure of the implications of removing the bridge type check right now. A quick fix would be adding some kind of `ignore_bridge_state` argument to `get_interfaces()` which makes it skip the bridge check internally.

**Comment by jow-** [comment]
Before investing too much effort into this, can you please check if https://github.com/jow-/luci works as expected? I plan to merge this to the master soon.

**Comment by sch-m** [comment]
I will test it tomorrow. But we also need a fix for openwrt-19.07.

**Comment by sch-m** [comment]
> Before investing too much effort into this, can you please check if https://github.com/jow-/luci works as expected? I plan to merge this to the master soon.

With the new "client side interface configuration pages" it works as expected.

**Comment by jow-** [comment]
@sch-m - thanks for confirming. For openwrt-19.07 can you please try the following fix:
```diff
diff --git a/modules/luci-base/luasrc/model/network.lua b/modules/luci-base/luasrc/model/network.lua
index a36a23f32..c8b62f290 100644
--- a/modules/luci-base/luasrc/model/network.lua
+++ b/modules/luci-base/luasrc/model/network.lua
@@ -1255,8 +1255,8 @@ function protocol.get_interface(self)
        end
 end
 
-function protocol.get_interfaces(self)
-       if self:is_bridge() or (self:is_virtual() and not self:is_floating()) then
+function protocol.get_interfaces(self, ignore_bridge_state)
+       if ignore_bridge_state or self:is_bridge() or (self:is_virtual() and not self:is_floating()) then
                local ifaces = { }
 
                local ifn
diff --git a/modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua b/modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua
index de7b8676e..3893ddb38 100644
--- a/modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua
+++ b/modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua
@@ -305,7 +305,7 @@ if not net:is_floating() then
                if alias then
                        old_ifs[1] = '@' .. alias
                else
-                       for _, i in ipairs(net:get_interfaces() or { net:get_interface() }) do
+                       for _, i in ipairs(net:get_interfaces(true) or { net:get_interface() }) do
                                old_ifs[#old_ifs+1] = i:name()
                        end
                end

```

**Comment by sch-m** [comment]
@jow- Yes, this fixes the problem for openwrt-19.07.

But I've found another problem in openwrt-19.07 related to this one:
When you uncheck the "Bridge Interfaces" checkbox of a bridge interface with proto==static, the
the interfaces dropdown is empty/damaged. You can't select anything.
With proto==ignore or proto==dhcp everything is fine.

This problem also does not exist in the latest master.

Any ideas?

**Comment by jow-** [comment]
No ideas, sorry.

**Comment by sch-m** [comment]
Anyone else? :-)

**Comment by sch-m** [comment]
I've found out that the problem also exists in the other way: When you try to make a bridge out of an Interface with proto=="static". And it is also important that ipaddr and netmask is configured.

Really strange.

In the Firefox "inspector" it seems that in the error case there are no eventListener registered to the cbi-dropdown object.

**Comment by sch-m** [comment]
Thanks for your changes. This will fix this issue.
