### ISSUE TITLE
Dynamic DNS display error

### ISSUE THREAD

**Issue by qiuzi** [openwrt/luci#300]
![image](https://cloud.githubusercontent.com/assets/1689784/5802874/de3fa38e-a033-11e4-8c58-06ce1ad8d6ed.png)

Luci cannot modify the configuration

**Comment by chris5560** [comment]
What "LuCI" theme do you use ?
Which Lua version is installed on your "Xrouter" ?
Please check OpenWrt or Bootstrap theme.
Same problem ?

**Comment by chris5560** [comment]
Would be helpful to get a solution how you fix it.
Thanks

Christian
