### ISSUE TITLE
luci-app-simple-adblock: Not the same option value as the init script

### ISSUE THREAD

**Issue by sotux** [openwrt/luci#3000]
https://github.com/openwrt/luci/blob/2aab85814d0eead5f82ee1c5661f03667ce50b62/applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua#L184

This option value is "dnsmasq.config", but in the init script, the option is "dnsmasq.conf"

**Comment by dibdot** [comment]
@stangri

**Comment by stangri** [comment]
Thank you!
PRs: https://github.com/openwrt/luci/pull/3026 https://github.com/openwrt/luci/pull/3027 https://github.com/openwrt/luci/pull/3028

**Comment by dibdot** [comment]
Quite fast - thanks!
