### ISSUE TITLE
OpenWrt link does not work: it is a #

### ISSUE THREAD

**Issue by Neustradamus** [openwrt/luci#3002]
In LuCI, the OpenWrt link at top left is a # and not a link to the LuCI homepage.

By default, it must be: https://xxx/cgi-bin/luci/

Can you solve it?

**Comment by jow-** [comment]
It is not supposed to be a link to OpenWrt.org

**Comment by Neustradamus** [comment]
@jow-: It will be nice to change the # by the homepage.
