### ISSUE TITLE
attach USB flash device 

### ISSUE THREAD

**Issue by sarwadenj** [openwrt/luci#3006]
I've LG01 gateway runs openWrt system. I want to attach USB flash device for that i followed your article and  https://openwrt.org/docs/guide-user/storage/usb-drives-quickstart artical. 
Now USB flash device is mounted. 
  
root@dragino-1c0b14:~# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                    3.5M    632.0K      2.9M  18% /
/dev/root                11.0M     11.0M         0 100% /rom
tmpfs                    29.8M    484.0K     29.4M   2% /tmp
/dev/mtdblock4            3.5M    632.0K      2.9M  18% /overlay
overlayfs:/overlay        3.5M    632.0K      2.9M  18% /
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/sda1                 7.0G     16.3M      6.6G   0% /mnt/sda1

now i wanted to copy some file to USB flash device. How to do it, which place i've to store it and run .

**Comment by jow-** [comment]
Please use the OpenWrt forums at https://forum.openwrt.org/ for help inquiries.
