### ISSUE TITLE
luci-mod-network: Transmit power always on auto

### ISSUE THREAD

**Issue by CaboBeach** [openwrt/luci#3020]
When Transmit power is set via Luci, Transmit Power will show auto regardless of setting, but correct transmit power will show in Status and config. Edit - after spending a few days with it, it looks like making any setting in Network>Wireless will result in Txpower being reset to auto on all radios. OpenWrt firmware version - OpenWrt SNAPSHOT r10863-e1dcfe02b2.

![Screen Shot 2019-08-27 at 10 45 26 AM](https://user-images.githubusercontent.com/48701904/63786630-067e7800-c8b8-11e9-968b-f49b9f758255.png)

![Screen Shot 2019-08-27 at 12 55 56 PM](https://user-images.githubusercontent.com/48701904/63795732-2fa80400-c8ca-11e9-965b-94b409cefee1.png)

**Comment by jow-** [comment]
This has been reworked in master.
