### ISSUE TITLE
/etc/config/luci missing when installed on snapshot r9256-8be8162d70

### ISSUE THREAD

**Issue by metamodern87** [openwrt/luci#3022]
/etc/config/luci appears to be completely missing on the snapshot image here.

I've gotten myself in way over my head. I wanted to install Openwrt on my Netgear R8000 so that I could configure my Pihole as the DNS server.

I appear to have installed an unstable release. I followed the guide to install Luci, and saw no obvious signs that the installation hadn't worked. 
When i go to the web interface I get 

> /usr/lib/lua/luci/dispatcher.lua:247: /etc/config/luci seems to be corrupt, unable to find section 'main'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:247: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:144: in function </usr/lib/lua/luci/dispatcher.lua:143><

I ssh into the router and browsed to /etc/config , and there doesn't appear to be a luci folder?

Sorry guys, again, in totally over my head. HELP.

**Comment by jow-** [comment]
Please use the OpenWrt forums for general help inquiries. The above error can also happen if the `rpcd` process is not running or crashing. If you installed an `ar71xx` snapshot, install an `ath79` one instead.
