### ISSUE TITLE
Using the latest version of the DDNS error

### ISSUE THREAD

**Issue by qiuzi** [openwrt/luci#303]
![image](https://cloud.githubusercontent.com/assets/1689784/5818529/3a329d1e-a0f1-11e4-8919-e317ef821631.png)
![image](https://cloud.githubusercontent.com/assets/1689784/5818531/3cac65a2-a0f1-11e4-96ce-2b0c7dfecde1.png)

Configure a single service display normal：
![image](https://cloud.githubusercontent.com/assets/1689784/5818592/b03afe48-a0f1-11e4-8a1b-e20da4adb24f.png)

**Comment by chris5560** [comment]
I cannot follow your problem. Description missing.
Hopefully details can be found inside logfile at /var/log/ddns/[sectionname].log
Please send one to me by direct mail (have a look into header of scripts in /usr/lib/ddns)
Please also provide versions of ddns-scripts and luci-app-ddns. (Click on blue "Dynamic DNS" header on overview page).

**Comment by qiuzi** [comment]
How much of your mail?

Luci-app-ddns=2.1.1-0

Ddns-scripts=2.1.0

2015-01-21 2:50 GMT+08:00 Christian Schoenebeck <notifications@github.com>:

**Comment by chris5560** [comment]
@qiuzi
is it fixed with the current version of ddns-scripts ?

**Comment by chris5560** [comment]
Newer versions of ddns-scripts and luci-app-ddns available. Please update and create new issue if problem still exists.
