### ISSUE TITLE
[feafure] option to disable showing "Active DHCP Leases" (both ipv4 and ipv6)

### ISSUE THREAD

**Issue by mistepien** [openwrt/luci#3039]
This request has its origin in issue https://github.com/openwrt/luci/issues/3037.
It would be great to be able to disable showing Active DHCP Leases in overview status page of Luci.

**Comment by jow-** [comment]
It can be disabled by uninstalling dnsmasq, by removing `/etc/config/dhcp` or by removing `/usr/lib/lua/luci/view/admin_status/index/40-dhcp-leases.htm`.
