### ISSUE TITLE
[BUG] udhcpc doesn't work in r10962

### ISSUE THREAD

**Issue by alishchytovych** [openwrt/luci#3043]
Hello,
I've updated from master / r10863-e1dcfe02b2 to r10962-c19b9f9a26 (mvebu/cortexa9, armada-385-linksys-rango) and got an error with DHCP Client - it doesn't discover an address (doesn't work):
root@router:~# udhcpc -i eth1
udhcpc: started, v1.31.0
udhcpc: sending discover
udhcpc: sending discover
...
At the same time downgrade resolves an issue. 
I've tried to look through the changes between 10863 and 10962 but found nothing related to the changes of DHCP (except of grub2 update)... Could you please help me with it / fix it?

**Comment by dibdot** [comment]
Unrelated to LuCI, please open a ticket at bugs.openwrt.org or ask in the forum.
