### ISSUE TITLE
JsonRpc Api does not work?

### ISSUE THREAD

**Issue by melaLetics** [openwrt/luci#3050]
Hey!

I've got a problem consuming the JsonRpc api. 
I've got a VM using Chaos Calmer (15.05, r46767). I use this virtualisation to play around with it before using the "real world application". 
I've installed LuCi -> works fine.
I've installed luci-mod-rpc (git-15.248.30277-3836b45-1) and restarted the uhttpd.

I'm able to get an auth token, sending with Postman a Post statement to 
http://x.x.x.x/cgi-bin/luci/rpc/auth with json-data
{
  "id": 1,
  "method": "login",
  "params": [
    "root",
    "xxxxxxx"
  ]
}

Fine, but using that token, I'm not able to get any response. No matter what library I try to reach.
Sadly, the library links in this Wiki are broken, so I have to Trial & Error :(

First question: do I send a Post or a Get statement? I've tried both, but any response...
So I tried:
http://x.x.x.x/cgi-bin/luci/rpc/fs?auth=f78bf762b59533713db182b45d7fb7e2
with json-data
{
	"jsonrpc": "2.0",
	"method": "dir", 
	"params": ["/"], 
	"id": 1
}

The response is 
_### Could not get any response
There was an error connecting to ._

So how to get the jsonrpc work?
Is there anywhere a running documentation for the exported libraries? All links in https://github.com/openwrt/luci/wiki/JsonRpcHowTo are broken :(

Thanks in advance!

**Comment by jow-** [comment]
Please retry with a current OpenWrt release. Chaos Calmer is not supported anymore and the LuCI version shipped with it contains various breaking bugs in the RPC implementation.
