### ISSUE TITLE
luci-app-statistics: Ping plugin does not display stddev data

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#3053]
19.07

I have noticed that there are **ping_stddev-*.rrd** files generated by the **ping** plugin, but the data is not displayed on the chart like the other two datasets. Can **stddev** be added?

**Comment by feckert** [comment]
I will have a look

**Comment by feckert** [comment]
What does this value mean?

**Comment by feckert** [comment]
I have only done this now for the master. If we need this for 19.07 then we should backport this.
