### ISSUE TITLE
MAC address filter 

### ISSUE THREAD

**Issue by realpandas** [openwrt/luci#3062]
Cannot use the Mac address access filter. The area where it’s supposed to give the option to put in a MAC address is not showing, only a line. This is in openwrt 19.07.

**Comment by jow-** [comment]
Which LuCI version?

**Comment by realpandas** [comment]
It’s still not working. 

LuCI openwrt-19.07 branch (git-19.253.56262-c0f3e3c) / OpenWrt 19.07-SNAPSHOT r10516-e8c5e6177d

**Comment by jow-** [comment]
Indeed, the linked commits actually broke this case. Fixed with commit a357352
