### ISSUE TITLE
unable to dispatch /cgi-bin/luci/admin/uci/changes

### ISSUE THREAD

**Issue by nickberry17** [openwrt/luci#3070]
Running master, but with some custom changes, so I may have broken something.  When I try to view "unsaved changes" I get: `404 Unable to dispatch: /cgi-bin/luci/admin/uci/changes`.  Has this been revamped?

**Comment by jow-** [comment]
This route does not exist anymore in master.

**Comment by nickberry17** [comment]
> This route does not exist anymore in master.

What should we use instead?

**Comment by jow-** [comment]
Current muster uses ubus-rpc to fetch the uci changes. You can look at the ui.js class.

**Comment by nickberry17** [comment]
Same situation in 18.06?
