### ISSUE TITLE
luci-base: Errors on france traduction

### ISSUE THREAD

**Issue by akhiltoor** [openwrt/luci#3073]
Hello,

I find some issues with the FR traduction.

The issues are in the main menu : 

Vue d`&#39;`ensemble
The good one is : Vue d'ensemble
Noms d`&#39;`hôtes
The good one is : Noms d'hôtes

Best regards.

**Comment by feckert** [comment]
There were massive changes in the translation recently.
We moved to weblate https://hosted.weblate.org/projects/openwrt/
See https://github.com/openwrt/luci/issues/3183
Please try again.

Feel free to reopen this issue if this is still an issue.
