### ISSUE TITLE
QMI interfaces do not display  RX TX count

### ISSUE THREAD

**Issue by xewonder** [openwrt/luci#3076]
Hello,

OpenWrt  latest pull  (as of now) and on interfaces QMI does not display the RX / TX bytes count.

Mouse over the icon, display the RX / TX
![sim1-2](https://user-images.githubusercontent.com/14354903/65047191-b05a9d00-d96a-11e9-8ae7-4a3d692efe1b.PNG)
![sim1](https://user-images.githubusercontent.com/14354903/65047192-b05a9d00-d96a-11e9-8bc1-449d7b46df76.PNG)

Any help or fix apreciated.

Thank you very much

**Comment by jow-** [comment]
Please provide the output of `ubus call network.interface dump` and `ubus call network.device status`

**Comment by xewonder** [comment]
root@OpenWrt:~# ubus call network.interface dump
{
        "interface": [
                {
                        "interface": "4G",
                        "up": false,
                        "pending": false,
                        "available": false,
                        "autostart": false,
                        "dynamic": false,
                        "proto": "3g",
                        "data": {

                        }
                },
                {
                        "interface": "lan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 357,
                        "l3_device": "br-lan",
                        "proto": "static",
                        "device": "br-lan",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "192.168.1.1",
                                        "mask": 24
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [
                                {
                                        "address": "fde9:80f9:259a::",
                                        "mask": 60,
                                        "local-address": {
                                                "address": "fde9:80f9:259a::1",
                                                "mask": 60
                                        }
                                }
                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "loopback",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 357,
                        "l3_device": "lo",
                        "proto": "static",
                        "device": "lo",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "127.0.0.1",
                                        "mask": 8
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "sim1",
                        "up": false,
                        "pending": false,
                        "available": true,
                        "autostart": false,
                        "dynamic": false,
                        "proto": "qmi",
                        "data": {

                        }
                },
                {
                        "interface": "sim2",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 209,
                        "l3_device": "wwan0",
                        "proto": "qmi",
                        "updated": [
                                "data"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [

                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {
                                "cid_4": "20",
                                "pdh_4": "-2030522560"
                        }
                },
                {
                        "interface": "sim2_4",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": true,
                        "uptime": 208,
                        "l3_device": "wwan0",
                        "proto": "dhcp",
                        "device": "wwan0",
                        "updated": [
                                "addresses",
                                "routes",
                                "data"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "10.208.147.123",
                                        "mask": 29
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [
                                {
                                        "target": "0.0.0.0",
                                        "mask": 0,
                                        "nexthop": "10.208.147.124",
                                        "source": "10.208.147.123/32"
                                }
                        ],
                        "dns-server": [
                                "212.152.95.56",
                                "62.169.194.48"
                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {
                                "hostname": "OpenWrt",
                                "leasetime": 7200,
                                "zone": "wan"
                        }
                },
                {
                        "interface": "wan",
                        "up": false,
                        "pending": true,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "proto": "dhcp",
                        "device": "eth0.2",
                        "data": {

                        }
                },
                {
                        "interface": "wan6",
                        "up": false,
                        "pending": true,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "proto": "dhcpv6",
                        "device": "eth0.2",
                        "data": {

                        }
                }
        ]
}

**Comment by xewonder** [comment]
root@OpenWrt:~# ubus call network.interface.sim2 status
{
        "up": true,
        "pending": false,
        "available": true,
        "autostart": true,
        "dynamic": false,
        "uptime": 275,
        "l3_device": "wwan0",
        "proto": "qmi",
        "updated": [
                "data"
        ],
        "metric": 0,
        "dns_metric": 0,
        "delegation": true,
        "ipv4-address": [

        ],
        "ipv6-address": [

        ],
        "ipv6-prefix": [

        ],
        "ipv6-prefix-assignment": [

        ],
        "route": [

        ],
        "dns-server": [

        ],
        "dns-search": [

        ],
        "neighbors": [

        ],
        "inactive": {
                "ipv4-address": [

                ],
                "ipv6-address": [

                ],
                "route": [

                ],
                "dns-server": [

                ],
                "dns-search": [

                ],
                "neighbors": [

                ]
        },
        "data": {
                "cid_4": "20",
                "pdh_4": "-2030522560"
        }
}

**Comment by xewonder** [comment]
... Thank you for your attention..

**Comment by xewonder** [comment]
hi, 
I applied the "patch" but id does not change anything...

![image](https://user-images.githubusercontent.com/14354903/65133341-1c8cdd80-da0b-11e9-9f53-4a8a0ef0eea9.png)

Thank you

**Comment by jow-** [comment]
Make sure to clear your browser cache.

**Comment by xewonder** [comment]
oh dear! you are right agin! sorry about that....
THANK YOU!
