### ISSUE TITLE
Backup/Restore.... where is the reset?

### ISSUE THREAD

**Issue by xewonder** [openwrt/luci#3077]
Hello,

OpenWrt latest pull (as of now) and on Backup/Restore there option to reset the router is gone (from previous versions).

Can it be added again?

![backup](https://user-images.githubusercontent.com/14354903/65047505-3971d400-d96b-11e9-83a7-7bfe878997b1.PNG)

Thank you

**Comment by jow-** [comment]
The following condition must be met for the reset option to be offered:
https://github.com/openwrt/luci/blob/master/modules/luci-mod-system/luasrc/controller/admin/system.lua#L93

**Comment by xewonder** [comment]
you are correct! THANK YOU!
