### ISSUE TITLE
Wireless - Icon is crossed if no LAN device is assigned

### ISSUE THREAD

**Issue by xewonder** [openwrt/luci#3078]
Hello,

OpenWrt latest pull (as of now) and if an SSID does not have a network (Valid) device assigned to it, it is "crossed" even though operational...

![image](https://user-images.githubusercontent.com/14354903/65047884-e3e9f700-d96b-11e9-9edc-3483e61f7557.png)

Thank you in advance

**Comment by jow-** [comment]
Please provide the output of `ubus call network.wireless status`

**Comment by xewonder** [comment]
Hi,

please note that "hotspot" i a non-existant interface assigned with uci set at boot.

root@OpenWrt:~# ubus call network.wireless status
{
        "radio0": {
                "up": true,
                "pending": false,
                "autostart": true,
                "disabled": false,
                "retry_setup_failed": false,
                "config": {
                        "hwmode": "11g",
                        "path": "platform/10180000.wmac",
                        "country": "00",
                        "channel": "7",
                        "htmode": "HT40"
                },
                "interfaces": [
                        {
                                "section": "default_radio0",
                                "ifname": "wlan0",
                                "config": {
                                        "mode": "ap",
                                        "encryption": "none",
                                        "wmm": false,
                                        "ssid": "Waveloc Public",
                                        "mode": "ap",
                                        "network": [
                                                "hotspot"
                                        ]
                                }
                        },
                        {
                                "section": "wifinet0",
                                "ifname": "wlan0-1",
                                "config": {
                                        "encryption": "none",
                                        "mode": "ap",
                                        "ssid": "Waveloc2",
                                        "mode": "ap",
                                        "network": [
                                                "lan"
                                        ]
                                }
                        }
                ]
        }
}


Thank you
