### ISSUE TITLE
Missing dependencies on Snapshot 19.07

### ISSUE THREAD

**Issue by dmitrygribenchuk** [openwrt/luci#3079]
Hello! I'm try to build OpenWrt on Snapshot 19.07 for GL.inet ar150 and have problem with satisfy dependencies.

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 * 	libip4tc2
 * 	libip6tc2

**Comment by hnyman** [comment]
You need to clean your build environment. There are probably previously compiled packages that have slightly different versions, causing the dependency to fail.

Do "make clean" before the build.

(I just built 19.07 without problems...)

**Comment by dmitrygribenchuk** [comment]
No. It's doesn't work

**Comment by strasharo** [comment]
Currently hitting the same with https://downloads.openwrt.org/snapshots/targets/ar71xx/tiny/openwrt-imagebuilder-ar71xx-tiny.Linux-x86_64.tar.xz
Has anyone found a solution for this?

**Comment by dmitrygribenchuk** [comment]
> Currently hitting the same with https://downloads.openwrt.org/snapshots/targets/ar71xx/tiny/openwrt-imagebuilder-ar71xx-tiny.Linux-x86_64.tar.xz
> Has anyone found a solution for this?

Yep. My device was moved from ar71xx to ath79 and change profile name (from tl-wr841-v8 to tplink_tl-wr841-v8). Check it.

**Comment by strasharo** [comment]
Thanks a lot @dmitrygribenchuk . Switched to https://downloads.openwrt.org/snapshots/targets/ath79/tiny/openwrt-imagebuilder-ath79-tiny.Linux-x86_64.tar.xz and profile from tl-wr703n-v1 to tplink_tl-wr703n and that dit it for me. Cheers!
