### ISSUE TITLE
Luci - Network - Interfaces - WireGuard TX/RX stats not working

### ISSUE THREAD

**Issue by dk4dk4** [openwrt/luci#3084]
I recently compiled my OpenWRT build to OpenWRT SNAPSHOT r11033-2b342d01a2 
I custom packaged WireGuard via Makefile to latest ver 0.0.20190913-1

The WireGuard interface no longer counts the RX/TX bytes properly:
![image](https://user-images.githubusercontent.com/33904434/65289388-5ef01080-db18-11e9-8c1a-f031a474683f.png)

When the Status - WireGuard Status page reports:
![image](https://user-images.githubusercontent.com/33904434/65289421-89da6480-db18-11e9-9532-1b4648424184.png)

The other non-wireguard interfaces continue to count RX/TX properly.  It is just the new WG ver

**Comment by jow-** [comment]
Please provide the output of `ubus call network.interface dump`

**Comment by dk4dk4** [comment]
root@DKWrt:~# ubus call network.interface dump
{
        "interface": [
                {
                        "interface": "ipvanvpntun",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 28406,
                        "l3_device": "tun0",
                        "proto": "none",
                        "device": "tun0",
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [

                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "lan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 37416,
                        "l3_device": "br-lan",
                        "proto": "static",
                        "device": "br-lan",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "192.168.1.1",
                                        "mask": 24
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [
                                "1.1.1.1"
                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "loopback",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 37416,
                        "l3_device": "lo",
                        "proto": "static",
                        "device": "lo",
                        "updated": [
                                "addresses"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "127.0.0.1",
                                        "mask": 8
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [

                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "mullvad",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 37412,
                        "l3_device": "mullvad",
                        "proto": "wireguard",
                        "updated": [
                                "addresses",
                                "routes"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "10.xx.xx.248",
                                        "mask": 32
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [
                                {
                                        "target": "0.0.0.0",
                                        "mask": 0,
                                        "nexthop": "0.0.0.0",
                                        "source": "0.0.0.0/0"
                                }
                        ],
                        "dns-server": [

                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],
                                "route": [

                                ],
                                "dns-server": [

                                ],
                                "dns-search": [

                                ],
                                "neighbors": [

                                ]
                        },
                        "data": {

                        }
                },
                {
                        "interface": "wan",
                        "up": true,
                        "pending": false,
                        "available": true,
                        "autostart": true,
                        "dynamic": false,
                        "uptime": 37415,
                        "l3_device": "eth1.2",
                        "proto": "dhcp",
                        "device": "eth1.2",
                        "updated": [
                                "addresses",
                                "routes",
                                "data"
                        ],
                        "metric": 0,
                        "dns_metric": 0,
                        "delegation": true,
                        "ipv4-address": [
                                {
                                        "address": "24.xx.xx.79",
                                        "mask": 24
                                }
                        ],
                        "ipv6-address": [

                        ],
                        "ipv6-prefix": [

                        ],
                        "ipv6-prefix-assignment": [

                        ],
                        "route": [
                                {
                                        "target": "0.0.0.0",
                                        "mask": 0,
                                        "nexthop": "24.xx.xx.1",
                                        "source": "24.xx.xx.79/32"
                                }
                        ],
                        "dns-server": [
                                "1.0.0.1",
                                "1.1.1.1"
                        ],
                        "dns-search": [

                        ],
                        "neighbors": [

                        ],
                        "inactive": {
                                "ipv4-address": [

                                ],
                                "ipv6-address": [

                                ],

**Comment by jow-** [comment]
What is the version of LuCI installed?
