### ISSUE TITLE
luci-app-firewall: cherry pick "Covered devices" in 19.07

### ISSUE THREAD

**Issue by bobafetthotmail** [openwrt/luci#3085]
This is the commit that contains this feature (among other things)
https://github.com/openwrt/luci/commit/df77b47badc5ea5aff5cbc341b44c64eeff2ba44#diff-cfa93b92d41c500ad02335dd08a0d799R175

Having it in Luci is important to allow VPN configuration from Luci as described in this wiki article.
https://openwrt.org/docs/guide-user/services/vpn/openvpn/client-luci

Note that only the "Covered devices" interface is needed for this, not the whole commit.

@jow- pretty please?

**Comment by feckert** [comment]
This could only be fixed (cherry-picked) if we move the master branch to 19.07 branch see RFC https://github.com/openwrt/luci/issues/3092

**Comment by jow-** [comment]
All master firewall support gas been merged to 19.07

**Comment by bobafetthotmail** [comment]
thanks
