### ISSUE TITLE
openwrt-theme: XML parsing error

### ISSUE THREAD

**Issue by dibdot** [openwrt/luci#3090]
Fresh image from today, System => Startup is broken in standard theme, e.g.

![owrt1](https://user-images.githubusercontent.com/8061346/65369236-be4e3d80-dc4a-11e9-98d5-6a13dbace8de.png)

**Comment by jow-** [comment]
Which LuCI version?

**Comment by dibdot** [comment]
OpenWrt SNAPSHOT r11083-8cb13f4e6d / LuCI Master (git-19.263.54698-720df98)

**Comment by jow-** [comment]
Hmm, can you check your browser debug console and see if you can obtain a backtrace? I cannot reproduce it here so far. The error is thrown by the `E()` function when some invalid (X)HTML snippets are passed to it. This used to be the case for `Save & Apply` (which must be `Save &amp; Apply` for XHTML) but I fixed these particular cases a few commits back, so something else specific to your setup must be triggering it.

**Comment by dibdot** [comment]
OK, I found the root cause, it depends on special chars in the "Local Startup" (rc.local) textarea, e.g. this breaks the XML-view:
```
# re-enable & start remote ssh tunnel
#
if [ $(/etc/init.d/ssh-tunnel enabled; printf "%u" ${?}) -eq 1 ]
then
    /etc/init.d/ssh-tunnel enable
    /etc/init.d/ssh-tunnel start
fi
```

**Comment by feckert** [comment]
@dibdot i think this could be closed

**Comment by jow-** [comment]
@feckert - nope, we need to fix it. @dibdot thanks for the info.

**Comment by feckert** [comment]
Ok understood I thought this had to do with his adapted rc.local
But this is then a general problem and not only for the luci-theme-openwrt.
So we should change the header to` luci-base: ...`

**Comment by jow-** [comment]
Its actually a problem with the startup and crontab pages specifically as these manually construct HTML containing `<textarea>` elements.
