### ISSUE TITLE
luci-proto-wireguard: Luci - Network - Interfaces - WG - restart broken

### ISSUE THREAD

**Issue by dk4dk4** [openwrt/luci#3098]
Powered by LuCI Master (git-19.263.54698-720df98) / OpenWRT SNAPSHOT r11070-c5b10c8282
WireGuard via Makefile to latest ver 0.0.20190913-1

I'm no longer able to restart a WireGuard interface using the Luci Interface page:

![image](https://user-images.githubusercontent.com/33904434/65380648-acea4d00-dcad-11e9-8837-622510e7c6c2.png)

If I reboot the router the interface comes up no problem.  
When I click restart it fails to restart the interface, and when I check under Status - WireGuard status I get the following error:
![image](https://user-images.githubusercontent.com/33904434/65380658-d30fed00-dcad-11e9-88dc-ef5dc58c43d6.png)

The error says there is no public key but the connection works fine when I reboot?  Something is off there...

I've also noticed the Network - Interface screen (wrong counts) for WG TX/RX stats do not match the real stats coming from the Status - WireGuard Status (correct counts) screen:
![image](https://user-images.githubusercontent.com/33904434/65382473-314fc680-dcd4-11e9-8f6f-e13140caa66b.png)

Network - Interface page for WG shows (wrong):
![image](https://user-images.githubusercontent.com/33904434/65382482-488eb400-dcd4-11e9-86f5-f7ed1bca7025.png)

**Comment by jow-** [comment]
The `Restart` button simply executes `/sbin/ifup mullvad` behind the scenes. Is this working fine when executed via the cli?

**Comment by dk4dk4** [comment]
The cli produces the same results.  The interface does not come back up.  When I check wireguard status page it has the same "Interface does not have a  public key" message.  When I rebooted it came back up ok...

**Comment by jow-** [comment]
This isn't a LuCI bug then but an issue with the wg protocol handler implementation. I didn't track if there's been any recent changes to it.

**Comment by dk4dk4** [comment]
Yes I wasn't sure where to open the ticket really. Can you move it to the
appropriate spot ?

**Comment by jow-** [comment]
Lets leave it open for the time being, I'll see if I can take a look at it during the next days.

**Comment by dibdot** [comment]
In OpenWrt is currently wireguard 0.0.20190702 ... I can't reproduce such restart errors with that version.

**Comment by dk4dk4** [comment]
Correct. I compiled to latest WRT and WG builds and this is new behaviour.
I listed the versions at start.

**Comment by dk4dk4** [comment]
I recently completed another build to:
OpenWRT SNAPSHOT r11159
The Wireguard included was the same ver as I had built before 0.0.20190913-1
WG interface issue persists.  I'm not able to restart the WG interface without the error.  Reboot resolves and WG connects successfully.

**Comment by dk4dk4** [comment]
This seems to be resolved with the latest WG bump to ver 0.0.20191012-1.
I can restart the WG interface again via Luci.

Rebuilt and tested with:
Powered by LuCI Master (git-19.296.33125-a9b680c) / OpenWRT SNAPSHOT r11320-2bc7c519dc
