### ISSUE TITLE
Freifunk overview page broken

### ISSUE THREAD

**Issue by nortobor** [openwrt/luci#310]
since the recent changes (a few days ago) the overview page (http://xxx/cgi-bin/luci/freifunk/) appars to be broken:

/usr/lib/lua/luci/dispatcher.lua:430: Failed to execute function dispatcher target for entry '/freifunk'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:430: Failed to execute template dispatcher target for entry '/freifunk/index'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'freifunk/index'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/openwrt.org/header'.
A runtime error occured: /usr/lib/lua/luci/util.lua:698: Unable to establish ubus connection
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:430: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:171: in function </usr/lib/lua/luci/dispatcher.lua:170>

**Comment by jow-** [comment]
Fixed with 993cf12
