### ISSUE TITLE
luci-app-firewall: MAC address list in Source MAC Address

### ISSUE THREAD

**Issue by ahmar20** [openwrt/luci#3102]
This is not an issue but more like a suggestion. I am using v18.06.4 in my HomeHub 5A.

Under Traffic Rules in Network -> Firewall when you edit or create a new rule, there is a textbox for Source MAC Address line. It's perfect for single MAC address cases but to add multiple addresses you need to go custom and then copy paste the whole MAC addresses from DHCP page or somewhere else adding a space in betwen. Even if you add a list in config file yourself, only the first MAC address shows in the LuCI and rest are not displayed. (Later is a **bug** I think)

Although this could be rather simple if someone implements a list style just like there is for Wireless MAC Filter. Then this should be more simple to add/remove MAC addresses. Thank you.

**Comment by jow-** [comment]
Fixed in master
