### ISSUE TITLE
luci-app-wireless: join network cannot set to zone auto

### ISSUE THREAD

**Issue by ptpt52** [openwrt/luci#3103]
```
scan
joinNetwork
Create / Assign firewall-zone set to wan
join
```
save && apply

after this ops, wireless join OK, but `wwan` is not in zone wan

**Comment by ptpt52** [comment]
okay, I found a fix:

https://github.com/x-wrt/luci/commit/c72e6e5d0a9ce93c246622c1ea471f2810aab398

**Comment by jow-** [comment]
Thank you for the fix @ptpt52, I cherry-picked it into master.
