### ISSUE TITLE
luci-i18n-base-es: "None" does not appear translated.

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3105]
![Captura de pantalla de 2019-09-23 14-19-41](https://user-images.githubusercontent.com/47670442/65448557-77f60b80-de0f-11e9-9c0c-859dd1f986f9.png)

![Captura de pantalla de 2019-09-23 14-26-20](https://user-images.githubusercontent.com/47670442/65448252-c656da80-de0e-11e9-8b63-199c5d9f3c5f.png)

**Comment by castillofrancodamian** [comment]
I have a Master. That is why I say that it is already translated, but not when I choose the translated language.

**Comment by feckert** [comment]
I think that's an established term.
And therefore needs no translation.

**Comment by urbalazs** [comment]
"None" is translatable and available for translation on Weblate. As I see, it is already translated into Spanish. This issue can be closed.

**Comment by castillofrancodamian** [comment]
Yes, I know it is translated. The problem is that it is not displayed in LuCI.

**Comment by feckert** [comment]
I have now taken a closer look.
This cannot be translated, because it is the uci value of the encryption option

`option encryption 'none'`
