### ISSUE TITLE
luci-i18n-base-es: "Master" does not appear translated.

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3106]
![Captura de pantalla de 2019-09-23 14-53-37](https://user-images.githubusercontent.com/47670442/65451083-dc679980-de14-11e9-89b2-fd386fe9e3f8.png)

![Captura de pantalla de 2019-09-23 14-53-42](https://user-images.githubusercontent.com/47670442/65451085-dc679980-de14-11e9-95ed-cd94348428d5.png)

**Comment by feckert** [comment]
I think that's an established term.
And therefore needs no translation.

**Comment by urbalazs** [comment]
"Master" is translatable and available for translation on Weblate. As I see, it is already translated into Spanish. This issue can be closed.

**Comment by castillofrancodamian** [comment]
It is the same as in the other issue.

**Comment by castillofrancodamian** [comment]
Still not solved.
