### ISSUE TITLE
Luci Broken in Snapshots ar71xx

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3108]
**Relevant data:**

Device: TP-Link CPE210v2

Clean image: http://downloads.openwrt.org/snapshots/targets/ar71xx/generic/openwrt-ar71xx-generic-cpe210-v2-squashfs-sysupgrade.bin

`opkg update && opkg install luci`

![Captura de pantalla de 2019-09-23 22-55-13](https://user-images.githubusercontent.com/47670442/65475405-d3e38300-de55-11e9-8a4b-9e422b062224.png)

It also happens in Archer C60v1

**Comment by jow-** [comment]
ar71xx snapshots are discontinued, use ath79 ones instead.

**Comment by castillofrancodamian** [comment]
I just installed Archer C60 ath79 and the same thing happens.

**Comment by jow-** [comment]
I cannot reproduce this, make sure the `rpcd` process is running.

**Comment by castillofrancodamian** [comment]
What should i do with `rpcd`?
