### ISSUE TITLE
With 2 ssids, wlan0-1 interface status is displayed, eth1 expected

### ISSUE THREAD

**Issue by miltador** [openwrt/luci#311]
Configuration:
 - 2 SSIDs, first is wlan0 and second one added, which is wlan0-1
 - Added a new interface 'guest' which is associated with wlan0-1 SSID

What was expected to see:
 - status of eth1 interface on the /admin/status/overview page

What is actually shown:
 - status of wlan0-1 on the /admin/status/overview page

Before I added and configured second ssid there was staus of eth1 interface displayed which is my internet interface.

**Comment by jow-** [comment]
Did you set a "gateway" on your gust interface? If yes, remove it.

**Comment by miltador** [comment]
Yes, there was a gateway. I removed it and now it shows eth1 status. Thanks.
