### ISSUE TITLE
wrong permissions in /www

### ISSUE THREAD

**Issue by dhewg** [openwrt/luci#3110]
I use `umask 027` on my build box, and manually run `umask 022` before doing a openwrt build (as the prereq steps correctly checks).

But even with that the luci install has the wrong permissions:
```
$ ll /rom/www/
drwxr-xr-x    4 root     root            79 Sep 23 08:04 ./
drwxr-xr-x   16 root     root           235 Sep 23 08:04 ../
drwxr-x---    2 root     root            83 Sep 23 08:04 cgi-bin/
-rw-r-----    1 root     root           524 Sep 23 08:04 index.html
drwxr-x---    4 root     root            61 Sep 23 08:04 luci-static/

$ ll /rom/www/cgi-bin/luci 
-rwxr-x---    1 root     root           135 Sep 23 08:04 /rom/www/cgi-bin/luci*
```

All files are `o-rwx`, which breaks the web interface. It used to work, but broke sometime recently.

**Comment by jow-** [comment]
Sounds like an OpenWrt build system issue.
