### ISSUE TITLE
luci-app-firewall: Not show ipv6 addresses from firewall drop-down list

### ISSUE THREAD

**Issue by dianlujitao** [openwrt/luci#3119]
In tab `Firewall - Traffic Rules - (name of rule)`, even with `Restrict to address family` set to `IPv6 only`, no v6 addrs are listed in `{Source,Destination} address`, and select a v4 address will silently fail, the only way is to manually type the desired v6 addr.

**Comment by daym** [comment]
The same happens on librecmc v1.4.9 for me. Manually entering it works.
