### ISSUE TITLE
/feeds/luci/host//usr/lib/lua/luci/model/network.lua:27: module 'ubus' not found:

### ISSUE THREAD

**Issue by dannyrz** [openwrt/luci#312]
hello , my friends. i need your help.

i make runuhttpd on ubuntu and some pages fine and some broken. the following is the page display.

----------------------------------------
Sorry, there is no sysupgrade support present; a new firmware image must be flashed manually. Please refer to the OpenWrt wiki for device specific install instructions.
----------------------------------------
....07/feeds/luci/host//usr/lib/lua/luci/dispatcher.lua:448: Failed to execute firstchild dispatcher target for entry '/admin/network'.
The called action terminated with an exception:
....07/feeds/luci/host//usr/lib/lua/luci/dispatcher.lua:448: Failed to execute arcombine dispatcher target for entry '/admin/network/network'.
The called action terminated with an exception:
.../feeds/luci/host//usr/lib/lua/luci/model/network.lua:27: module 'ubus' not found:
	no field package.preload['ubus']
	no file '/home/zhurizhao/openwrt-14.07/feeds/luci/host//usr/lib/lua/ubus.lua'
	no file '/home/zhurizhao/openwrt-14.07/feeds/luci/host//usr/lib/lua/ubus/init.lua'
	no file './ubus.lua'
	no file '/usr/local/share/lua/5.1/ubus.lua'
	no file '/usr/local/share/lua/5.1/ubus/init.lua'
	no file '/usr/local/lib/lua/5.1/ubus.lua'
	no file '/usr/local/lib/lua/5.1/ubus/init.lua'
	no file '/usr/share/lua/5.1/ubus.lua'
	no file '/usr/share/lua/5.1/ubus/init.lua'
	no file '/home/zhurizhao/openwrt-14.07/feeds/luci/host//usr/lib/lua/ubus.so'
	no file './ubus.so'
	no file '/usr/local/lib/lua/5.1/ubus.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/ubus.so'
	no file '/usr/lib/lua/5.1/ubus.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'assert'
	....07/feeds/luci/host//usr/lib/lua/luci/dispatcher.lua:448: in function 'dispatch'
	....07/feeds/luci/host//usr/lib/lua/luci/dispatcher.lua:195: in function <....07/feeds/luci/host//usr/lib/lua/luci/dispatcher.lua:194>
------------------------------------

**Comment by hnyman** [comment]
With reference to discussion at #293, runuhttpd isn't really supported any more.
Your error messages refer to those external Openwrt modules (like "ubus"), which aren't part of Luci.
