### ISSUE TITLE
luci-app-ddns: should i port ddns to client side implementation?

### ISSUE THREAD

**Issue by Ansuel** [openwrt/luci#3124]
@jow- sorry for the random issue... i notice you are converting all the model to client side implementation... should the app be converted too ?

**Comment by jow-** [comment]
@Ansuel - if you feel like it then yes, it would be a good idea. But its not a strict requirement yet.

**Comment by feckert** [comment]
@Ansuel Are you still planning to change the app to the new Javascript?

**Comment by Ansuel** [comment]
Mh yes but now I'm working on something else.
I need to study the new API to convert all to js... Also it would be good
to "clean" the module...
Why the question?

Il Lun 21 Ott 2019, 17:08 Florian Eckert <notifications@github.com> ha
scritto:

**Comment by feckert** [comment]
I have come up with a few things that I did not like so much with this app. If you rewrite this app we could fix this.
* Link to the openwrt page (should be fixed in a general way)
* General page should be a tab and not a link
* And start/stop should be done on save if the section is enabled

**Comment by Ansuel** [comment]
Yes I notice that too...

There is also some strange thing with general ddns option hided in a link
instead of putting them in a tab...

Il Lun 21 Ott 2019, 17:18 Florian Eckert <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
Anyway i have started the porting of the ddns app... For now i have ported the index page and the global config options

**Comment by Ansuel** [comment]
@feckert https://github.com/openwrt/luci/pull/3267 almost done... i think i just need to implement custom script implementation... I need some hint about the name of the js (overview.js is a bit misleading) and a general review of the code and of the functions... I removed some checks and it would be good to have a second opinion if the extra checks should be reintroduced.

**Comment by feckert** [comment]
@Ansuel see my comments in #3267
