### ISSUE TITLE
luci-mod-network: Removing a single network from a wireless interface (when multiple are present/disabled) removes all other networks attached to that interface

### ISSUE THREAD

**Issue by ethaniel** [openwrt/luci#3127]
Bext explained with this video:
https://www.youtube.com/watch?v=MjEzsoXLIJM&feature=youtu.be

Powered by LuCI openwrt-18.06 branch (git-19.256.41054-c048f23) / OpenWrt 18.06.4 r7808-ef686b7292

**Comment by jow-** [comment]
This has been fixed in master.
