### ISSUE TITLE
match patterns in cbi :depends()

### ISSUE THREAD

**Issue by poranje** [openwrt/luci#313]
CBI provides the :depends() method on option objects that allow to dynamically show or hide the object field depending on the value in some other field.

the method is called as obj:depends( some_other_option, value ) - or with a table of likewise tuples).
When value could be specified as a regular expression pattern, then the dependency condition can cover many values, which is impossible now.

Examples:
o:depends("name", ".+ Oranje")
which would allow the form to include/exclude fields when it of my kinsmen of which there are many
or
o.depends("phonenumber", "(00|+)[%d]+")
which would show option o when the phone number concerns an international number.

**Comment by jow-** [comment]
The problem is that we need to evaluate the pattern on both the server and the client side but JavaScript PCRE patterns are incompatible to Lua patterns, therefor we cannot implement this.
