### ISSUE TITLE
luci-mod-network: Domain whitelist bug in luci "DHCP and DNS"

### ISSUE THREAD

**Issue by rezad1393** [openwrt/luci#3130]
I have this line in dnsmasq config.
list rebind_domain '/.onion/'
and dnsmasq accepts that.
but in luci in page "DHCP and DNS" the "Domain whitelist " doesnt accept that and I cant change that page without removing /.onion/
it seeems the luci config only accepts full domains like /test.com/ and not /.com/ or /.org/
but dnsmasq accepts those.
can this be fixed?

**Comment by feckert** [comment]
This is because we have a data type host https://github.com/openwrt/luci/blob/e13822e7096056ead944d1b7b3ff64864d80ccb5/modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js#L203-L213

**Comment by rezad1393** [comment]
I think this bug is not present in luci.
but maybe you should "fix" the 19.07 and make appear again.

**Comment by feckert** [comment]
So which version (branch)  do you use?

- master
- 19.07
- 18.06

**Comment by rezad1393** [comment]
19.07

**Comment by rezad1393** [comment]
I didnt check completely but it seems that it still doesnt accepts **new** top level suffix but at least the onion one from my dnsmasq config is not stoping luci to save other changes in that page.
