### ISSUE TITLE
Missing error handling if uci:save fails

### ISSUE THREAD

**Issue by sarumpaet** [openwrt/luci#314]
If the user applies config changes using "Save & Apply" in the UI and the action fails (for example, because the filesystem is out of space), there is no error message whatsoever, and the changes are lost, which can be very confusing.

I think the problem is a missing check at https://github.com/openwrt/luci/blob/7a3493b1f7d75a3945279115324cf2ff4da26b7b/modules/luci-base/luasrc/cbi.lua#L360 .

**Comment by cshoredaniel** [comment]
@sarumpaet Is this still a problem with current trunk LuCI?

**Comment by sarumpaet** [comment]
@cshoredaniel Didn't test, but in current master that code seems unchanged: https://github.com/openwrt/luci/blob/61239741d8a6cb9888fb379ac3e00fdb6adcc3c8/modules/luci-base/luasrc/cbi.lua#L392

**Comment by dibdot** [comment]
please re-test against master branch.
