### ISSUE TITLE
luci-nginx: error flashing new firmware with web interface

### ISSUE THREAD

**Issue by jammmet** [openwrt/luci#3140]
Trying to update firmware fails during upload using nginx as the LuCI web server.
Console output attached:

![Screenshot 2019-10-02 at 08 31 37](https://user-images.githubusercontent.com/2951113/66020342-7901f980-e4ef-11e9-81f6-42eb7b7f93e8.png)

**Comment by jammmet** [comment]
That was on Safari.
On Firefox, a different error manifests:

![image](https://user-images.githubusercontent.com/2951113/66022717-891dd700-e4f7-11e9-90e5-af33ad478cb1.png)


And on Chrome:

![image](https://user-images.githubusercontent.com/2951113/66022821-d0a46300-e4f7-11e9-84a7-b7f81669e333.png)

**Comment by jow-** [comment]
This is a bug in the `luci-nginx` package, most likely because it is not configured to execute CGI programs correctly. 

@Ansuel

**Comment by jow-** [comment]
Please follow up on https://github.com/openwrt/packages/issues/10134 - this is not a LuCI bug.
