### ISSUE TITLE
luci-base: form.js titleFn return null when attr is not defined

### ISSUE THREAD

**Issue by ysc3839** [openwrt/luci#3147]
https://github.com/openwrt/luci/blob/90c52a1782ae7727c0a430dcec64d9c1b072e452/modules/luci-base/htdocs/luci-static/resources/form.js#L229-L244
When `attr` is not defined, `s` remains `null`, then it returns `null`, which result in null name in `TableSection`.
![image](https://user-images.githubusercontent.com/12028138/66308469-d2c45280-e939-11e9-9daf-b7bb5440b9c6.png)
@jow-

**Comment by jow-** [comment]
@ysc3839 - the `titleFn()` is supposed to return `null` so this part is fine, the table is not supposed to be rendered with `null` section titles though. Can you provide the exact example .js code you used?

**Comment by ysc3839** [comment]
@jow- Just a TableSection. I found here titleFn returns null, resulting null name in table.
https://github.com/openwrt/luci/blob/90c52a1782ae7727c0a430dcec64d9c1b072e452/modules/luci-base/htdocs/luci-static/resources/form.js#L1032
So I guess it mistakenly return null?

**Comment by jow-** [comment]
Let me check...
