### ISSUE TITLE
luci-base: strange section tabs with client-side view after login

### ISSUE THREAD

**Issue by ysc3839** [openwrt/luci#3150]
#### Reproduce steps:
1. Logout
2. Go to http://192.168.1.1/cgi-bin/luci/admin/services/test
3. Login
4. Result: 
![image](https://user-images.githubusercontent.com/12028138/66397279-0a043380-ea0e-11e9-959f-47ce926103fe.png)

This bug is not always reproducible, and it seems that it only occur after login. It doesn't occur by reloading the page. My browser is Google Chrome Version 77.0.3865.90.
I found it's caused by this code:
https://github.com/openwrt/luci/blob/e459683822925bcdeb552673a4811aa3b4322640/modules/luci-base/htdocs/luci-static/resources/ui.js#L2016-L2045
Sometimes the view is loded before this code execute, so that `document.querySelectorAll('[data-tab]')` selects the tabs.
I guess it's some kind of race condition. There shoule be some restriction to ensure the view is loaded after that.

#### Code:
/usr/lib/lua/luci/controller/test.lua
```
module("luci.controller.test", package.seeall)

function index()
	entry({"admin", "services", "test"}, view("test"), _("test")).dependent = true
end
```
/etc/config/test
```
config test1
	option opt1 'opt1'

config conf common
	option opt2 'opt2'

config conf conf1
	option opt3 'opt3'
```
/www/luci-static/resources/view/test.js
```
'use strict';
'require form';

return L.view.extend({
	render: function() {
		var m, s, o;

		m = new form.Map('test', 'test');

		s = m.section(form.TypedSection, 'test1', 'section');
		s.anonymous = true;

		s.tab('tab1', _('tab1'));
		s.tab('tab2', _('tab2'));

		for (var i = 0; i < 20; ++i) {
			s.taboption('tab1', form.Value, 'opt' + i, 'Opt' + i);
		}


		o = s.taboption('tab2', form.SectionValue, 'common', form.NamedSection, 'common', 'conf', 'tab2');
		s = o.subsection;

		s.option(form.Flag, 'opt', 'opt');

		return m.render();
	}
});
```

**Comment by jow-** [comment]
It was quite hard to debug, whenever I added some debugging code, the race condition stopped occurring but now I'm confident that it is solved.

**Comment by ysc3839** [comment]
@jow- Thanks for solving!
