### ISSUE TITLE
luci-mod-system: broken save mtd function

### ISSUE THREAD

**Issue by Ansuel** [openwrt/luci#3156]
I notice that save mtd function is broken since it does report Invalid characters 

I run this with uhttpd, tell me if it's just a problem on my side.

**Comment by jow-** [comment]
Please provide more details. What is reporting invalid characters where?

**Comment by Ansuel** [comment]
As soon as I click  save mtdblock button in flash page

(It's from cgi-download )

Il Mer 9 Ott 2019, 15:39 Jo-Philipp Wich <notifications@github.com> ha
scritto:

**Comment by hnyman** [comment]
Works for me with ipq806x/R7800 and ath79/WNDR3700v2

LuCI Master (git-19.280.64531-5ccbda5) / OpenWrt SNAPSHOT r11167-273a6cb562

**Comment by jow-** [comment]
Sounds as if your browser is displaying the binary contents inline and not offering them as download. I cannot reproduce this here either using Chrome or Firefox.

**Comment by Ansuel** [comment]
@jow- pls reopen... i modified cgi-io to include some debug output....

Wed Oct  9 18:55:04 2019 daemon.info uwsgi: No-Lag-Router.mtd0.bin
Wed Oct  9 18:55:04 2019 daemon.info uwsgi: Invalid -

By renaming my hostname to "no" 
it does download the file

**Comment by Ansuel** [comment]
```
	for (p = fields[5]; p && *p; p++)
		if (!isalnum(*p) && !strchr(" ()<>@,;:[]?.=%", *p)) {
			fprintf(stderr, "Invalid %c\n", *p);
			return failure(400, 0, "Invalid characters in filename");}

	for (p = fields[7]; p && *p; p++)
		if (!isalnum(*p) && !strchr(" .;=/-", *p))
			return failure(400, 0, "Invalid characters in mimetype");
```

change isalnum to isgraph ?

**Comment by Ansuel** [comment]
Here the file pr 
https://github.com/openwrt/packages/pull/10191
