### ISSUE TITLE
luci-app-mosquitto

### ISSUE THREAD

**Issue by finasfinas** [openwrt/luci#3161]
Can't find it ( current trunk ) on the application list.
I have luci admin full selected.

**Comment by jow-** [comment]
There is no such application in the repos.

**Comment by feckert** [comment]
https://github.com/openwrt/luci/tree/master/applications/luci-app-mosquitto ?

**Comment by jow-** [comment]
Didn't know that this is a thing. Anyway, the original report is far too vague to act upon. My guess is that mosquitto failed to build for some random arch and therefore luci-app-mosquitto isn't available. Either way not a bug we can solve here.

**Comment by finasfinas** [comment]
@jow- 
Sorry for the vagueness. 

What I mean is that when I do a make menuconfig, select luci, and them go to the applications list, I cannot find there the luci-app-mosquitto.
I saw on the code that it depends on luci admin full and on mosquitto and even having those enabled does not make it appear on the list.

**Comment by finasfinas** [comment]
So,
Selecting the package mosquitto-nossl or mosquitto-ssl will make luci-app-mosquitto appear.
Doesn't seem to be the standard way of doing things, namely, all packages are viewable.
