### ISSUE TITLE
luci-app-openvpn: not reachable over IPv6 configured by LUCI

### ISSUE THREAD

**Issue by GFTwrt** [openwrt/luci#3163]
Hi!
in the package "luci-app-openvpn"
OpenWrt 18.06.2 r7676-cddd7b4c77 / LuCI openwrt-18.06 branch (git-19.275.23087-48f58d9) is a configuration problem in the files
/usr/lib/lua/luci/model/cbi/openvpn-advanced.lua and /usr/lib/lua/luci/model/cbi/openvpn-basic.lua

both files contains
ListValue,"proto",{ "udp", "tcp-client", "tcp-server"  }
But need to contain the ipv6 versions too.

So the line needs to be:
ListValue,"proto",{ "udp", "tcp-client", "tcp-server" ,"udp6", "tcp6-client", "tcp6-server" }.

source: https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

> proto indicates the protocol to use when connecting with the remote, and may be “tcp” or “udp”.
> For forcing IPv4 or IPv6 connection suffix tcp or udp with 4/6 like udp4/udp6/tcp4/tcp6.

P.S. maybe the whole cataloge of options needs to be checked for completeness.
P.P.S. The std path of openvpn-easy-rsa gernerated profiles do not match the std setup of luci too.

Br
GFTwrt

**Comment by feckert** [comment]
The missing option are also not applied to 19.07 and master
@GFTwrt please open a pull request
