### ISSUE TITLE
luci-app-wireguard Status frozen at Collecting data...

### ISSUE THREAD

**Issue by carroarmato0** [openwrt/luci#3180]
The status page of WireGuard perpetually remains unchanged while trying to load the collected data.

![wireguard-status](https://user-images.githubusercontent.com/1828645/66760250-ffc8b600-eea1-11e9-89e1-a354ec1eeacb.png)

Relevant wireguard package combination:

- kmod-wireguard | 4.4.196+0.0.20190913-..1-0
- luci-app-wireguard | git-19.175.20344-ad82eac-1
- luci-proto-wireguard | git-19.175.20344-ad82eac-1
- wireguard | 0.0.20190913-1
- wireguard-tools | 0.0.20190913-1

**Comment by dibdot** [comment]
This is not reproducible with current master. You're using a Chaos Calmer based Turris OS 3.x variant, please open a ticket here: https://gitlab.labs.nic.cz/turris/openwrt/issues
