### ISSUE TITLE
no menu shown by luci-proto-vpnc 

### ISSUE THREAD

**Issue by GFTwrt** [openwrt/luci#3207]
luci-proto-vpnc git-19.287.34592-afee71b-1 ( LuCI openwrt-18.06 branch) adds no menu to services nor any other pull down.

**Comment by dibdot** [comment]
That's just a proto handler without own controller/menu in the UI. Typically you'll find the installed protocols under Network => Interfaces => Add new interface, e.g.:
![vpnc](https://user-images.githubusercontent.com/8061346/67117444-00838400-f1e3-11e9-89e3-b8a0ec6aec95.png)
