### ISSUE TITLE
luci-proto-vpnc: Defaultroute settings missing

### ISSUE THREAD

**Issue by GFTwrt** [openwrt/luci#3218]
While in /luci/blob/master/protocols/luci-proto-vpnc/htdocs/luci-static/resources/protocol/vpnc.js
the last entry is "defaultroute"
This is missing in /usr/lib/lua/luci/model/cbi/admin_network/proto_vpnc.lua git-19.287.34592-afee71b-1 so vpnc is forcing the tunel to be the defaultroute in any case.

**Comment by dibdot** [comment]
backported/fixed in 18.06 branch with ceb1f80710007f7b4d805135e849e18622e815ce
