### ISSUE TITLE
luci-app-openvpn: add missing proto param for ipv6 #3179

### ISSUE THREAD

**Issue by GFTwrt** [openwrt/luci#3219]
luci-app-openvpn: add missing proto param for ipv6 #3179

I assume that luci-app-openvpn git-19.287.34592-afee71b-1 should contain the bug fix - but it doesn't. Can't answer to the original issue.

**Comment by dibdot** [comment]
> I assume that luci-app-openvpn git-19.287.34592-afee71b-1 should contain the bug fix
No, the fix is only in master not in 18.06 branch.
