### ISSUE TITLE
Luci is not working properly on port 80

### ISSUE THREAD

**Issue by KnectBis** [openwrt/luci#3220]
I am using the newest snapshot of d2-team Newifi. 
I installed Luci, and found that everything on Luci are "collecting data".
Just like imgs showen below.
But when I changed uhttpd's listening port to 81 or any others, Luci Works fine.
![bad](https://i.loli.net/2019/10/19/xbjgizuY9LZk3SB.png)
![bad](https://i.loli.net/2019/10/19/y4TnowEbvmL2KWX.png)
when port 81
![works fine](https://i.loli.net/2019/10/19/eF8CTNZmqYn1pEb.png)

**Comment by jow-** [comment]
Sounds like a browser cache issue.
