### ISSUE TITLE
LUCI - NoDataError on "luci/admin/system/flash"

### ISSUE THREAD

**Issue by lunzet** [openwrt/luci#3228]
I am having a "nodataerror" on LUCI only on the "luci/admin/system/flash" Interface. All others work fine. Any idea on how to solve it?

I have reflashed already via the cli running "OpenWrt SNAPSHOT r11274" right now.

Any help is appreciated

**Comment by jow-** [comment]
What error do you get exactly? What is shown on the screen? Which action did you perform to see the error?

**Comment by lunzet** [comment]
1) login to luci
2) goto "System" --> "Backup / Flash firmware"
3) see screenshot

![lede - Backup : Flash Firmware - LuCI 2019-10-21 13-38-26](https://user-images.githubusercontent.com/27411098/67202121-2e95dd80-f408-11e9-9660-4ca6cdcd89bb.png)
