### ISSUE TITLE
luci api document a few 404

### ISSUE THREAD

**Issue by laoshaw** [openwrt/luci#3253]
Error: Cannot load https://raw.githubusercontent.com/openwrt/luci/master/documentation/api/modules/luci.http.conditionals.html: 404 Not Found

Error: Cannot load https://raw.githubusercontent.com/openwrt/luci/master/documentation/api/modules/luci.http.date.html: 404 Not Found

etc

**Comment by jow-** [comment]
Should have been fixed by https://github.com/openwrt/luci/commit/d80dd2291ff01d264dfa802b769fa19756f07821
