### ISSUE TITLE
Add JavaScript linting CI

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#3266]
Now that the web interface uses so much JavaScript, there should be some automated style checks.

**Comment by feckert** [comment]
Should this be done on pullrequest creation? So we need first a CI

**Comment by aparcar** [comment]
So we could us GitHub actions and the npm module to install [ESLint](https://eslint.org/docs/user-guide/getting-started) which then gives some report. Probably it's the best to do this rather sooner than later to avoid the establishment of various code styles...

**Comment by Ansuel** [comment]
I think EsLint will report tons of problem... on the order of 10k min

**Comment by jow-** [comment]
Closing this as it never gained traction
