### ISSUE TITLE
Openwrt-19.07 branch sysupgrade doesn't work with nginx 

### ISSUE THREAD

**Issue by hanipouspilot** [openwrt/luci#3270]
After selecting a file and pressing upload nothing happens.
Interface is stuck on uploading 100% and real sysupgrade never starts.

**Comment by jow-** [comment]
Cannot reproduce it. Please open your browser console with F12 and look for errors.

**Comment by hanipouspilot** [comment]
Failed to load resource: the server https://[fdfc:ef25:1ba5::1]/cgi-bin/cgi-upload?1573047203685 responded with a status of 405 (Not Allowed)

Uncaught (in promise) SyntaxError: https://[fdfc:ef25:1ba5::1]/luci-static/resources/luci.js?v=git-19.310.44720-c2be304 Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ClassConstructor.json (https://[fdfc:ef25:1ba5::1]/luci-static/resources/luci.js?v=git-19.310.44720-c2be304:25)
    at eval (https://[fdfc:ef25:1ba5::1]/luci-static/resources/ui.js?v=git-19.310.44720-c2be304:229)

**Comment by hanipouspilot** [comment]
Tried both FF and Chrome. Same result.

**Comment by jow-** [comment]
Is this using uhttpd or an other webserver?

**Comment by hanipouspilot** [comment]
Oops. I forgot to mention. I am testing nginx on this specific device.

**Comment by jow-** [comment]
I think nginx support still requires backporting of the latest master fixes. @Ansuel - do you have an overview over the nginx / fastcgi commits that we need to pick into openwrt-19.07 for cgi-io to work properly?

**Comment by Ansuel** [comment]
This 3 should fix the problem.

https://github.com/openwrt/packages/pull/10173/files
https://github.com/openwrt/packages/pull/10193
https://github.com/openwrt/packages/pull/10263
<https://github.com/openwrt/packages/pull/10263/files>

Il Mer 6 Nov 2019, 15:29 Jo-Philipp Wich <notifications@github.com> ha
scritto:

**Comment by hanipouspilot** [comment]
I cherry-picked those, resolved PKG_RELEASE and HASH conflicts, but still same problem. @Ansuel

**Comment by Ansuel** [comment]
Check if the config file got actually updated

Il Mer 6 Nov 2019, 17:13 Dmitry Tunin <notifications@github.com> ha scritto:

**Comment by hanipouspilot** [comment]
Which one? /etc/nginx/luci-uwsgi.conf did change.

**Comment by hanipouspilot** [comment]
I missed the vassals commit.

**Comment by hanipouspilot** [comment]
Now I am getting "bad gateway". I am not familiar with all this web stuff.

**Comment by Ansuel** [comment]
Did u restart both uwsgi and nginx?

Il Mer 6 Nov 2019, 18:05 Dmitry Tunin <notifications@github.com> ha scritto:

**Comment by hanipouspilot** [comment]
I flashed a new image. So everything was from scratch. I give up for now. Switched to uhttpd for a while.

**Comment by EXSERENS** [comment]
select an upgrade file after upload, in browser console:
```
luci.js?v=git-19.311.41964-489fc4b:59 POST https://xxxxxxxxxx/cgi-bin/cgi-upload?1573176670473 413
(anonymous) @ luci.js?v=git-19.311.41964-489fc4b:59
request @ luci.js?v=git-19.311.41964-489fc4b:40
post @ luci.js?v=git-19.311.41964-489fc4b:64
click @ ui.js?v=git-19.311.41964-489fc4b:228

luci.js?v=git-19.311.41964-489fc4b:25 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ClassConstructor.json (luci.js?v=git-19.311.41964-489fc4b:25)
    at eval (ui.js?v=git-19.311.41964-489fc4b:229)
json @ luci.js?v=git-19.311.41964-489fc4b:25
eval @ ui.js?v=git-19.311.41964-489fc4b:229
Promise.then (async)
click @ ui.js?v=git-19.311.41964-489fc4b:229
```

**Comment by jow-** [comment]
Assuming this works now
