### ISSUE TITLE
Null in wifi overview status

### ISSUE THREAD

**Issue by Ansuel** [openwrt/luci#3272]
![Annotazione 2019-11-07 011134](https://user-images.githubusercontent.com/20289090/68348872-9122f500-00fb-11ea-97f1-d020a47a5a0b.jpg)

**Comment by hnyman** [comment]
Should be Disconnect like this:
![image](https://user-images.githubusercontent.com/7926856/68366502-2645de00-013c-11ea-8fd7-896661b55424.png)

LuCI Master (git-19.310.44530-a8a7697) / OpenWrt SNAPSHOT r11426-80a799125b 
(with the default Bootstrap theme, uhttpd and Firefox 71)
