### ISSUE TITLE
rpcd-mod-luci: cannot build with latest master

### ISSUE THREAD

**Issue by klukonin** [openwrt/luci#3273]
Build error:

> make[6]: Entering directory '/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103'
> Scanning dependencies of target rpcd-mod-luci
> make[6]: Leaving directory '/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103'
> make[6]: Entering directory '/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103'
> [ 50%] Building C object CMakeFiles/rpcd-mod-luci.dir/luci.c.o
> /builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103/luci.c: In function 'rpc_luci_get_iwinfo':
> /builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103/luci.c:904:31: error: 'IWINFO_KMGMT_SAE' undeclared (first use in this function); did you mean 'IWINFO_KMGMT_NAMES'?
>       if (crypto.auth_suites & IWINFO_KMGMT_SAE)
>                                ^~~~~~~~~~~~~~~~
>                                IWINFO_KMGMT_NAMES
> /builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103/luci.c:904:31: note: each undeclared identifier is reported only once for each function it appears in
> /builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103/luci.c:907:31: error: 'IWINFO_KMGMT_OWE' undeclared (first use in this function); did you mean 'IWINFO_KMGMT_SAE'?
>       if (crypto.auth_suites & IWINFO_KMGMT_OWE)
>                                ^~~~~~~~~~~~~~~~
>                                IWINFO_KMGMT_SAE
> make[6]: *** [CMakeFiles/rpcd-mod-luci.dir/luci.c.o] Error 1
> make[5]: *** [CMakeFiles/rpcd-mod-luci.dir/all] Error 2
> CMakeFiles/rpcd-mod-luci.dir/build.make:62: recipe for target 'CMakeFiles/rpcd-mod-luci.dir/luci.c.o' failed
> make[6]: Leaving directory '/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103'
> CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/rpcd-mod-luci.dir/all' failed
> make[5]: Leaving directory '/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103'
> make[4]: *** [all] Error 2
> Makefile:129: recipe for target 'all' failed
> make[4]: Leaving directory '/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103'
> make[3]: *** [/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103/.built] Error 2
> Makefile:55: recipe for target '/builder/openwrt/build_dir/target-mips_24kc_musl/rpcd-mod-luci-20191103/.built' failed
> make[3]: Leaving directory '/builder/openwrt/feeds/luci/libs/rpcd-mod-luci'
> time: package/feeds/luci/rpcd-mod-luci/compile#0.23#0.08#0.55
> make[2]: *** [package/feeds/luci/rpcd-mod-luci/compile] Error 2
> package/Makefile:111: recipe for target 'package/feeds/luci/rpcd-mod-luci/compile' failed
> make[2]: Leaving directory '/builder/openwrt'
> make[1]: *** [/builder/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
> package/Makefile:107: recipe for target '/builder/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
> make[1]: Leaving directory '/builder/openwrt'
> /builder/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
> make: *** [world] Error 2
> ERROR: Job failed: exit code 1

**Comment by jow-** [comment]
Your libiwinfo version is too old. This does not look like latest OpenWrt master.
