### ISSUE TITLE
19.07 wireless "Disconnect" button is gone

### ISSUE THREAD

**Issue by LinuxKernel1** [openwrt/luci#3274]
Is it intended to be like that?

OpenWrt 19.07-SNAPSHOT r10532:
![before](https://user-images.githubusercontent.com/17409024/68404750-4a76de80-017f-11ea-800d-396aa7620e89.png)

OpenWrt 19.07-SNAPSHOT r10648:
![after](https://user-images.githubusercontent.com/17409024/68404743-477bee00-017f-11ea-8faf-9522b644943c.png)

**Comment by jow-** [comment]
Already fixed with https://github.com/openwrt/luci/commit/c00d860981007a74d497f79640c446883bffe0ca, will be part of the enxt RC / final.
