### ISSUE TITLE
luci : realtime graphs show 0 outgoing traffic on bridge and vlan interfaces on traffic menu

### ISSUE THREAD

**Issue by Snotmann** [openwrt/luci#3276]
Hey guys,

in the realtime graphs seems to be a problem. The download traffic on interfaces is shown correctly, the upload shows 0 all the time:

Inbound:
6.05 Kbit/s
(775 B/s)
Average:
112.53 Kbit/s
(14.07 KB/s)
Peak:
751.52 Kbit/s
(93.94 KB/s)
Outbound:
0 bit/s
(0 B/s)
Average:
0 bit/s
(0 B/s)
Peak:
0 bit/s
(0 B/s)

**Comment by feckert** [comment]
Please add a version information (branch)

**Comment by Snotmann** [comment]
OpenWrt 19.07.0-rc1, r10649-c4fdb377a2

**Comment by jow-** [comment]
I suspect numeric overflow. 

@Snotmann - can you please provide the output of `ubus call luci getRealtimeStats '{ "mode": "interface", "device": "br-lan" }'; sleep 10; ubus call luci getRealtimeStats '{ "mode": "i
nterface", "device": "br-lan" }'`

Replace "br-lan" with one of the affected interfaces.

**Comment by Snotmann** [comment]
{
        "result": [
                [
                        1573160963,
                        4186533,
                        46191,
                        91454828,
                        74639
                ],
                [
                        1573160965,
                        4212295,
                        46456,
                        91798417,
                        74945
                ],
                [
                        1573160967,
                        4228606,
                        46570,
                        91965549,
                        75090
                ],
                [
                        1573160969,
                        4229470,
                        46582,
                        91967042,
                        75100
                ],
                [
                        1573160974,
                        4286034,
                        47145,
                        92940340,
                        75883
                ],
                [
                        1573160978,
                        4363771,
                        48245,
                        95550959,
                        77790
                ],
                [
                        1573160982,
                        4432833,
                        48909,
                        97193565,
                        79031
                ],
                [
                        1573161095,
                        5340628,
                        61373,
                        126692901,
                        100990
                ],
                [
                        1573161097,
                        5345641,
                        61455,
                        126956142,
                        101180
                ],
                [
                        1573161098,
                        5351265,
                        61549,
                        127170453,
                        101336
                ],
                [
                        1573161101,
                        5356785,
                        61641,
                        127378098,
                        101488
                ],
                [
                        1573161103,
                        5362288,
                        61732,
                        127619350,
                        101661
                ],
                [
                        1573161106,
                        5375925,
                        61927,
                        128048159,
                        101974
                ],
                [
                        1573161108,
                        5383128,
                        62050,
                        128375589,
                        102207
                ],
                [
                        1573161110,
                        5390449,
                        62157,
                        128649261,
                        102405
                ],
                [
                        1573161113,
                        5399496,
                        62305,
                        128958127,
                        102630
                ],
                [
                        1573161114,
                        5404287,
                        62383,
                        129157054,
                        102778
                ],
                [
                        1573161118,
                        5426596,
                        62589,
                        129694825,
                        103170
                ],
                [
                        1573161120,
                        5433804,
                        62677,
                        129940106,
                        103350
                ],
                [
                        1573161122,
                        5438788,
                        62758,
                        130154300,
                        103504
                ],
                [
                        1573161125,
                        5444486,
                        62852,
                        130402355,
                        103684
                ],
                [
                        1573161126,
                        5444620,
                        62854,
                        130402459,
                        103685
                ],
                [
                        1573161130,
                        5462197,
                        62969,
                        130621380,
                        103888
                ],
                [
                        1573161132,
                        5462197,
                        62969,
                        130622022,
                        103889
                ],
                [
                        1573161134,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161137,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161138,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161140,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161143,
                        5462339,
                        62972,
                        130623048,
                        103894
                ],
                [
                        1573161145,
                        5462339,
                        62972,
                        130623048,
                        103894
                ],
                [
                        1573161148,
                        5462381,
                        62973,
                        130623090,
                        103895
                ],
                [
                        1573161150,
                        5462431,
                        62974,
                        130623090,
                        103895
                ],
                [
                        1573161152,
                        5462431,
                        62974,
                        130623090,
                        103895
                ],
                [
                        1573161155,
                        5462431,
                        62974,
                        130623090,
                        103895
                ],
                [
                        1573161158,
                        5462431,
                        62974,
                        130623486,
                        103898
                ],
                [
                        1573161160,
                        5462663,
                        62978,
                        130624185,
                        103907
                ],
                [
                        1573161163,
                        5462705,
                        62979,
                        130624328,
                        103909
                ],
                [
                        1573161165,
                        5462705,
                        62979,
                        130624328,
                        103909
                ],
                [
                        1573161167,
                        5462705,
                        62979,
                        130624328,
                        103909
                ],
                [
                        1573161169,
                        5462755,
                        62980,
                        130625593,
                        103915
                ],
                [
                        1573161173,
                        5462797,
                        62981,
                        130625960,
                        103917
                ],
                [
                        1573161177,
                        5463123,
                        62986,
                        130626470,
                        103921
                ],
                [
                        1573161181,
                        5463412,
                        62988,
                        130626795,
                        103922
                ],
                [
                        1573161195,
                        5463462,
                        62989,
                        130626795,
                        103922
                ],
                [
                        1573161197,
                        5463462,
                        62989,
                        130626795,
                        103922
                ],
                [
                        1573161200,
                        5463462,
                        62989,
                        130626795,
                        103922
                ],
                [
                        1573161203,
                        5463504,
                        62990,
                        130626837,
                        103923
                ],
                [
                        1573161205,
                        5463504,
                        62990,
                        130626837,
                        103923
                ],
                [
                        1573161206,
                        5463504,
                        62990,
                        130626837,
                        103923
                ],
                [
                        1573161209,
                        5463554,
                        62991,
                        130626837,
                        103923
                ],
                [
                        1573161211,
                        5463554,
                        62991,
                        130626837,
                        103923
                ],
                [
                        1573161213,
                        5463604,
                        62992,
                        130626879,
                        103924
                ],
                [
                        1573161218,
                        5465934,
                        63006,
                        130631067,
                        103935
                ],
                [
                        1573161222,
                        5472966,
                        63025,
                        130634344,
                        103950
                ],
                [
                        1573161224,
                        5473008,
                        63026,
                        130634386,
                        103951
                ],
                [
                        1573161226,
                        5473008,
                        63026,
                        130634386,
                        103951
                ],
                [
                        1573161229,
                        5473058,
                        63027,
                        130634386,
                        103951
                ],
                [
                        1573161231,
                        5473058,
                        63027,
                        130634386,
                        103951
                ],
                [
                        1573161233,
                        5473100,
                        63028,
                        130634428,
                        103952
                ],
                [
                        1573161235,
                        5473100,
                        63028,
                        130634428,
                        103952
                ]
        ]
}
 {
        "result": [
                [
                        1573160982,
                        4432833,
                        48909,
                        97193565,
                        79031
                ],
                [
                        1573161095,
                        5340628,
                        61373,
                        126692901,
                        100990
                ],
                [
                        1573161097,
                        5345641,
                        61455,
                        126956142,
                        101180
                ],
                [
                        1573161098,
                        5351265,
                        61549,
                        127170453,
                        101336
                ],
                [
                        1573161101,
                        5356785,
                        61641,
                        127378098,
                        101488
                ],
                [
                        1573161103,
                        5362288,
                        61732,
                        127619350,
                        101661
                ],
                [
                        1573161106,
                        5375925,
                        61927,
                        128048159,
                        101974
                ],
                [
                        1573161108,
                        5383128,
                        62050,
                        128375589,
                        102207
                ],
                [
                        1573161110,
                        5390449,
                        62157,
                        128649261,
                        102405
                ],
                [
                        1573161113,
                        5399496,
                        62305,
                        128958127,
                        102630
                ],
                [
                        1573161114,
                        5404287,
                        62383,
                        129157054,
                        102778
                ],
                [
                        1573161118,
                        5426596,
                        62589,
                        129694825,
                        103170
                ],
                [
                        1573161120,
                        5433804,
                        62677,
                        129940106,
                        103350
                ],
                [
                        1573161122,
                        5438788,
                        62758,
                        130154300,
                        103504
                ],
                [
                        1573161125,
                        5444486,
                        62852,
                        130402355,
                        103684
                ],
                [
                        1573161126,
                        5444620,
                        62854,
                        130402459,
                        103685
                ],
                [
                        1573161130,
                        5462197,
                        62969,
                        130621380,
                        103888
                ],
                [
                        1573161132,
                        5462197,
                        62969,
                        130622022,
                        103889
                ],
                [
                        1573161134,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161137,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161138,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161140,
                        5462297,
                        62971,
                        130622684,
                        103892
                ],
                [
                        1573161143,
                        5462339,
                        62972,
                        130623048,
                        103894
                ],
                [
                        1573161145,
                        5462339,
                        62972,
                        130623048,
                        103894
                ],
                [
                        1573161148,
                        5462381,
                        62973,
                        130623090,
                        103895
                ],
                [
                        1573161150,
                        5462431,
                        62974,
                        130623090,
                        103895
                ],
                [
                        1573161152,
                        5462431,
                        62974,
                        130623090,
                        103895
                ],
                [
                        1573161155,
                        5462431,
                        62974,
                        130623090,
                        103895
                ],
                [
                        1573161158,
                        5462431,
                        62974,
                        130623486,
                        103898
                ],
                [
                        1573161160,
                        5462663,
                        62978,
                        130624185,
                        103907
                ],
                [
                        1573161163,
                        5462705,
                        62979,
                        130624328,
                        103909
                ],
                [
                        1573161165,
                        5462705,
                        62979,
                        130624328,
                        103909
                ],
                [
                        1573161167,
                        5462705,
                        62979,
                        130624328,
                        103909
                ],
                [
                        1573161169,
                        5462755,
                        62980,
                        130625593,
                        103915
                ],
                [
                        1573161173,
                        5462797,
                        62981,
                        130625960,
                        103917
                ],
                [
                        1573161177,
                        5463123,
                        62986,
                        130626470,
                        103921
                ],
                [
                        1573161181,
                        5463412,
                        62988,
                        130626795,
                        103922
                ],
                [
                        1573161195,
                        5463462,
                        62989,
                        130626795,
                        103922
                ],
                [
                        1573161197,
                        5463462,
                        62989,
                        130626795,
                        103922
                ],
                [
                        1573161200,
                        5463462,
                        62989,
                        130626795,
                        103922
                ],
                [
                        1573161203,
                        5463504,
                        62990,
                        130626837,
                        103923
                ],
                [
                        1573161205,
                        5463504,
                        62990,
                        130626837,
                        103923
                ],
                [
                        1573161206,
                        5463504,
                        62990,
                        130626837,
                        103923
                ],
                [
                        1573161209,
                        5463554,
                        62991,
                        130626837,
                        103923
                ],
                [
                        1573161211,
                        5463554,
                        62991,
                        130626837,
                        103923
                ],
                [
                        1573161213,
                        5463604,
                        62992,
                        130626879,
                        103924
                ],
                [
                        1573161218,
                        5465934,
                        63006,
                        130631067,
                        103935
                ],
                [
                        1573161222,
                        5472966,
                        63025,
                        130634344,
                        103950
                ],
                [
                        1573161224,
                        5473008,
                        63026,
                        130634386,
                        103951
                ],
                [
                        1573161226,
                        5473008,
                        63026,
                        130634386,
                        103951
                ],
                [
                        1573161229,
                        5473058,
                        63027,
                        130634386,
                        103951
                ],
                [
                        1573161231,
                        5473058,
                        63027,
                        130634386,
                        103951
                ],
                [
                        1573161233,
                        5473100,
                        63028,
                        130634428,
                        103952
                ],
                [
                        1573161235,
                        5473100,
                        63028,
                        130634428,
                        103952
                ],
                [
                        1573203786,
                        39387438,
                        388128,
                        644969032,
                        506149
                ],
                [
                        1573203788,
                        39387438,
                        388128,
                        644969032,
                        506149
                ],
                [
                        1573203790,
                        39387480,
                        388129,
                        644969074,
                        506150
                ],
                [
                        1573203792,
                        39387480,
                        388129,
                        644969074,
                        506150
                ],
                [
                        1573203794,
                        39387480,
                        388129,
                        644969074,
                        506150
                ],
                [
                        1573203796,
                        39387530,
                        388130,
                        644969074,
                        506150
                ]
        ]
}

**Comment by jow-** [comment]
Should have been fixed by https://github.com/openwrt/openwrt/commit/aa89bdcd04676b21cbe3e8a7b8df3545a86d947a
