### ISSUE TITLE
Mounted file systems showing wrong info in 19.07.0-rc1

### ISSUE THREAD

**Issue by CaboBeach** [openwrt/luci#3281]
My attached NTFS drive is 3tb with about 1.5tb used, but in Luci>System>Mount Points>Mounted File Systems it's showing as 2.0gb with 0% used, it doesn't appear to affect functionality in any way, so i'm just assuming it's a Luci issue, apologies if it should be reported elsewhere - 

![Screenshot from 2019-11-08 21-04-09](https://user-images.githubusercontent.com/48701904/68522119-3dd0b400-026d-11ea-9cb8-889d907e8c65.png)

**Comment by feckert** [comment]
What is the output of the command ```/sbin/block info```

**Comment by CaboBeach** [comment]
Here's the output - 

```
/sbin/block info
/dev/mtdblock4: UUID="1598287620" VERSION="1" TYPE="ubi"
/dev/mtdblock6: UUID="429114593" VERSION="1" TYPE="ubi"
/dev/ubiblock0_0: UUID="a2304630-82fab1ac-d2ec9479-e8dcb919" VERSION="4.0" MOUNT="/rom" TYPE="squashfs"
/dev/ubi0_1: UUID="0adae7ef-7afd-4dc3-8e04-b6defd017564" VERSION="w4r0" MOUNT="/overlay" TYPE="ubifs"
/dev/sda1: UUID="0000001800000030" MOUNT="/mnt/storage" TYPE="ntfs"
```

**Comment by hnyman** [comment]
Pure guess is some 32-bit integer overflow in the display logic.
(2^32 kB   = 4 TB, so 2 TB would be unsigned 32-bit count of kB.)

**Comment by jow-** [comment]
Fixed by https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=aa89bdcd04676b21cbe3e8a7b8df3545a86d947a
