### ISSUE TITLE
Luci-theme-material Eror openwrt 19.07.0-rc1

### ISSUE THREAD

**Issue by predators46** [openwrt/luci#3292]
I want to report a bug in the Luci-theme-material, 
`No related RPC reply`

![FB_IMG_15736219275333586](https://user-images.githubusercontent.com/31931530/68735069-6988cc80-05d4-11ea-9d70-697d9d9e0d30.jpg)
![FB_IMG_15736219395956063](https://user-images.githubusercontent.com/31931530/68735078-70174400-05d4-11ea-9026-5072a68ace3a.jpg)

**Comment by jow-** [comment]
Do you use nginx?

**Comment by predators46** [comment]
> Do you use nginx?

I don't use nginx, I just install luci and add luci-theme-material

**Comment by jow-** [comment]
See if the issue persists after a reboot.

**Comment by predators46** [comment]
> See if the issue persists after a reboot.

yes after I reboot the problem still exists, I use imagebuilder to make my OpenWrt

**Comment by predators46** [comment]
and there is another problem to change the ip in the luci without success, I have to use puty to change my router's ip

**Comment by jow-** [comment]
Please provide the exact OpenWrt used, as well as the output of `opkg list-installed | grep -E 'luci|rpcd'`
