### ISSUE TITLE
luci-lib-jsonc: INT_MAX issue with 

### ISSUE THREAD

**Issue by lisaac** [openwrt/luci#3293]
Form luci-lib-json switch to luci-lib-jsonc, I found that if number_in_json > INT_MAX, it will return the INT_MAX instead the real value.
```lua
json = require "luci.jsonc"
test ='{"big_number":2147483649}'
-- 2147483649 is INT_MAX + 2
res = json.parse(test)
print(res.big_number)
-- got: 2147483647
```

**Comment by feckert** [comment]
Which branch?
What shall he give back according to your opinion?

**Comment by lisaac** [comment]
im using 18.06.4, and it should return the real value (2147483649), not the INT_MAX(2147483647)

**Comment by lisaac** [comment]
@jow- 
Is there any possible to support int64 in luci.jsonc.stringify ?

```
print(luci.jsonc.stringify({int64=3000000000}))
-- got: {"int64":3000000000.0}
-- This is not an INT
```
I'm using luci-lib-json it works well:
```
print(luci.json.encode({int64=3000000000}))
-- {"int64":3000000000}
```

Thanks

**Comment by jck112** [comment]
Can someone take a look at https://github.com/openwrt/luci/pull/5730? I'm trying to fix some of the issues upstream for aarch64 devices that manufacturers (like FriendlyElec) are currently patching in their builds.
