### ISSUE TITLE
luci-mod-status: shows incorrect swap info when a physical swap partition is mounted.

### ISSUE THREAD

**Issue by prowong** [openwrt/luci#3295]
![20191113151648](https://user-images.githubusercontent.com/8499801/68741558-e8a7f000-0628-11ea-8117-6223035d6eba.jpg)

**Comment by jow-** [comment]
Is the swap larger than 2GB ?

**Comment by prowong** [comment]
> 
> 
> Is the swap larger than 2GB ? Please check whether the issue persists after `opkg update; opkg upgrade rpcd; reboot`.

Yes,rpcd is installed, and my platform is x86_64.

**Comment by jow-** [comment]
Yes, rpcd is always installed by default, but did you *upgrade* it to the latest version?

**Comment by prowong** [comment]
> 
> 
> Yes, rpcd is always installed by default, but did you _upgrade_ it to the latest version?

I compiled the latest version. It happend after the luci-compat was added.

**Comment by jow-** [comment]
Please provide the output of `opkg list-installed rpcd` and `ubus call system info`

**Comment by prowong** [comment]
OpenWrt 19.07-SNAPSHOT, r10675-5e1864d
 -----------------------------------------------------
root@OpenWrt:~# opkg list-installed rpcd
rpcd - 2019-11-10-77ad0de0-1
root@OpenWrt:~# ubus call system info
{
	"localtime": 1573692247,
	"uptime": 161,
	"load": [
		2816,
		1856,
		160
	],
	"memory": {
		"total": 511537152,
		"free": 362319872,
		"shared": 733184,
		"buffered": 20283392
	},
	"swap": {
		"total": 1327489024,
		"free": 1327489024
	}
}

**Comment by jow-** [comment]
This looks like a Kernel level bug. I replicated the problem on a Xiaomi Mir3G by attaching an USB thumb drive and allocating 4GB of swap space. Neither the ubus call, nor the low level `sysinfo(2)` call, no `/proc/swaps` or `free -m` display the correct values. They all cap to ~2GB.
