### ISSUE TITLE
luci-app-statistics: load view is porbably misleading

### ISSUE THREAD

**Issue by feckert** [openwrt/luci#3301]
During my tests and developing with the collectd and so luci-app-statistics I noticed that the values displayed in the Y-axis are misleading, because probably the individual values are added together in each case.

![uhttpd_max_requests_load](https://user-images.githubusercontent.com/553091/68771560-8cdd6700-0628-11ea-8d21-9c9945732156.png)

If I split the three source in individual pictures everything is OK.
![Screenshot_2019-11-13 G3000-LWV - Systemlast - LuCI](https://user-images.githubusercontent.com/553091/68771956-44727900-0629-11ea-8624-c09f29eb26bd.png)

**Comment by feckert** [comment]
@hnyman Do you see it that way?

**Comment by jow-** [comment]
Well, the values are stacked. You can disable that by adding `overlay = false` to the options.

**Comment by feckert** [comment]
Thanks for the feedback.
I am not sure what the problem is, but your suggestion does not work!
I replaced the following lines

> load__shortterm = { color = "ff0000", title = "1 minute", noarea = true },
> load__midterm   = { color = "ff6600", title = "5 minutes", noarea = true },
> load__longterm  = { color = "ffaa00", title = "15 minutes", noarea = true }

in
`application/luci-app-statistics/luasrc/statistics/rrdtool/definitions/load.lua`
with

> load__shortterm = { color = "ff0000", title = "1 minute", noarea = true, overlay = false },
> load__midterm   = { color = "ff6600", title = "5 minutes", noarea = true,overlay = false },
> load__longterm  = { color = "ffaa00", title = "15 minutes", noarea = true, overlay = false }		

but nothing changed. Does I miss something?

Would it not make more sense to split them up into 3 separate diagramms?
To remove the overlap and display the correct value?

**Comment by jow-** [comment]
I might have had the overlay values backwards, try true instead of false.

**Comment by feckert** [comment]
Thanks, that's it. I could have thought of that myself. Damn it! :1st_place_medal: 

I will push a fix.
I do also remove the **noarea** so it looks like.

![load](https://user-images.githubusercontent.com/553091/68843118-e052c200-06c7-11ea-8b25-f2d3fefc5f7b.png)

**Comment by jow-** [comment]
I would keep noarea for the 1 minute load and make it the foremost line, so that it draws above the 5 and 15 minute load areas. Since the 1 minute one is the most important imho it should not be covered by the others.

**Comment by feckert** [comment]
After merge of #3310 the load view looks like 
![load](https://user-images.githubusercontent.com/553091/68854188-d76beb80-06db-11ea-828c-bf20e55bab05.png)

**Comment by hnyman** [comment]
@feckert 
Thanks for looking into this. The new look is nice ;-)
