### ISSUE TITLE
luci-app-statistics: CPU plugin does not display information by CPU

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#3303]
19.07-SNAPSHOT

Here is my config

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5624569/68776676-7de1bf00-05fe-11ea-9ad9-d7281a50d5b8.png">

And the chart displays combined usage instead of "By CPU"

<img width="827" alt="image" src="https://user-images.githubusercontent.com/5624569/68776791-a79ae600-05fe-11ea-8f63-361b4af07680.png">

**Comment by feckert** [comment]
Could you post your generated collectd and uci config?

**Comment by fantom-x** [comment]
From luci_statistics 

config statistics 'collectd_cpu'          
        option enable '1'

**Comment by fantom-x** [comment]
Hah, so once I save it I get these and then two more charts (one per CPU show up). They are empty at this time.I also see "cpu-0" and "cpu-1" folders under the red directory.

config statistics 'collectd_cpu'          
        option enable '1'                               
        option ReportByCpu '1'            
        option ReportByState '1'          
        option ValuesPercentage '0'

**Comment by feckert** [comment]
Ok is this now solved?

**Comment by feckert** [comment]
Assume this works as expected.
If not, feel free to reopen this issue.

**Comment by fantom-x** [comment]
It is gonna be broken on a fresh install again: two configuration parameters are missing in luci_statistics and collectd is not collecting the relevant data. Luci assumes the wrong defaults for the missing values.
It is working for me now, but a greenfield install will be broken until the user saves that page.

**Comment by fantom-x** [comment]
I do not see a way to reopen this issues. It is up to you guys.

**Comment by jow-** [comment]
Fixed in master
