### ISSUE TITLE
luci: Status / Realtime Graphs / Traffic - missing WAN interface and shows double of each wifi interface

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#3304]
19.07-SNAPSHOT

Issue 1.
I am using PPPoE connection and it used to show up on this page, but not any more.

Issue 2.
If I have an WiFi AP called "Guest" and each band has it's own interface name: "guest2" and "guest5", then I will see two tabs "guest2" and two tabs "guest5" on this page.

**Comment by jow-** [comment]
Please provide your /etc/config/wireless as well as the output of `opkg list-installed`. 

Also open your browser's debug console using F12 and paste the following code:
`L.network.getDevices().then(function(d) { s = []; console.debug(JSON.stringify(d, function(k, x) { if (L.isObject(x)) { if (s.indexOf(x) >= 0) return null; else s.push(x); } return x })) })`

Please provide its output as well.

**Comment by fantom-x** [comment]
Do you still need anything from me?

Does it fix "pppoe-wan" interface?

**Comment by jow-** [comment]
No, yes.
