### ISSUE TITLE
[19.07] [bug report] luci-app-ttyd cannot display in luci menu

### ISSUE THREAD

**Issue by Mosney** [openwrt/luci#3319]
![image](https://user-images.githubusercontent.com/22477230/68999296-d7493700-08f9-11ea-85bd-e804d760f6f1.png)

**Comment by castillofrancodamian** [comment]
It is in the "Services" tab.

**Comment by Mosney** [comment]
> It is in the "Services" tab.

![Screenshot_20191117-110234](https://user-images.githubusercontent.com/22477230/69002408-cdd7c300-0929-11ea-9c7d-1296f7bd9dd4.jpg)
services tab look like this.

**Comment by feckert** [comment]
Do you have a configuration file (/etc/config/ttyd)?
See code https://github.com/openwrt/luci/blob/2390e7297601767ddc7f25ab5fb606500117ffea/applications/luci-app-ttyd/luasrc/controller/ttyd.lua#L5-L8

**Comment by ysc3839** [comment]
Nothing wrong here.
Versions: LuCI Master (git-19.314.67968-e8abe15) / OpenWrt SNAPSHOT r11526-f84d6d2f3a
I guess it's 19.07's issue?

**Comment by ysc3839** [comment]
Yes, because ttyd in 19.07 is not updated. luci-app-ttyd should be marked as broken.
https://github.com/openwrt/packages/tree/openwrt-19.07/utils/ttyd

**Comment by hnyman** [comment]
> luci-app-ttyd should be marked as broken.

Better might be to backport the changes in the main ttyd app from master to 19.07

**Comment by jow-** [comment]
Can anybody take care of either backporting ttyd or - if that is rejected - marking luci-app-ttyd as `@BROKEN` ?

**Comment by hnyman** [comment]
The two ttyd commits in master about 1.5.1 and 1.5.2 (and uci config) look so simple that I cherry-picked them into 19.07.

**Comment by Mosney** [comment]
> Do you have a configuration file (/etc/config/ttyd)?
> See code
> 
> https://github.com/openwrt/luci/blob/2390e7297601767ddc7f25ab5fb606500117ffea/applications/luci-app-ttyd/luasrc/controller/ttyd.lua#L5-L8

I don't find this file, so it means I need create a conf file?

**Comment by feckert** [comment]
I do not know how the file `/etc/config/ttyd` does looks like, but I think you need a default config so that the configuration gets shown. This code section checks if the file exists and only then the menu entry is shown.

**Comment by Mosney** [comment]
I think it already been fixed. Just upgrade packages.
![Screenshot_20191118-235500](https://user-images.githubusercontent.com/22477230/69067927-e72e5b80-0a5e-11ea-8590-8b4649262a47.jpg)
