### ISSUE TITLE
[C2600] / [Wi-Fi 5GHz] Some devices on the home network do not have internet access

### ISSUE THREAD

**Issue by shevchenko1987** [openwrt/luci#3324]
- Device problem occurs on TP-Link Archer C2600

- Software version of OpenWrt 19.07-rc1 and older 19.07

- From the first version, which I tested after the release of 19.07, I have a problem with 5GHz radio / Wi-Fi. On two devices: LG OLED B8 55 "OTT and Cyfrowy Polsat STB OTT does not work internet. Both devices connect to the network, but do not have access to the Internet. In the connection diagnostics on the TV, the message pops up that it is a DNS error. On 2.4 GHz Wi-Fi everything is fine.

- I have reverted to the 18.06 to fix the problem for now.

**Comment by jow-** [comment]
Thank you for the report but this is no problem of the LuCI gui. Please consider reporting at https://bugs.lopenwrt.org/
