### ISSUE TITLE
LuCI unable to connect to the internet?

### ISSUE THREAD

**Issue by robman501a** [openwrt/luci#3325]
Here's my setup:
Main router: ASUS RT-AC1900P (Asuswrt-Merlin)
OpenWRT device 1: Netgear WNDR3700v1 (acting as a switch https://openwrt.org/docs/guide-user/network/wifi/dumbap)
OpenWRT device 2: WD MyBookLive NAS
![image](https://user-images.githubusercontent.com/30871515/69014653-81f14200-095a-11ea-9a1c-c898f4e8e1cd.png)
The problem: The NAS is unable to access the internet at all (LAN port connected to main routers LAN port, IP address of NAS changed to 192.168.1.3). The WNDR3700v1 can't access the internet at all through its web interface but connected devices do have internet access.

**Comment by ysc3839** [comment]
I think it's not a bug about luci. You should post this to https://forum.openwrt.org/
By the way, try `traceroute openwrt.org` or ping your main router.

**Comment by robman501a** [comment]
Okay, I'll head over there. Thanks for suggesting that.
By the way, the second router with OpenWRT can ping my main router. :)
