### ISSUE TITLE
iPhone Safari, Port Status is not displayed

### ISSUE THREAD

**Issue by intdev32** [openwrt/luci#3326]
iPhone Safari (or other mobile browser with small display)

Open Luci webpage. -> Go to Network > Switch

Under [VLANs on "switch0"]

Port status is not displayed! (not at all. no port status text, no port icons...)

Desktop webpage is normal. Only happen on mobile page.
And 18.06.1 ~ 18.06.5 Luci's mobile pages are normal.

Luci versions I checked:

19.07.1-rc1 default
19.317.63431-ebd354d

**Comment by intdev32** [comment]
Edit: 19.07.1-rc1 default --> 19.07.0-rc1 default

Add: On iPad 9.7" screen, well displayed.

**Comment by jow-** [comment]
This is intentional, table descriptions are hidden on small screens.
