### ISSUE TITLE
unable to add static dhcp lease through luci

### ISSUE THREAD

**Issue by carck** [openwrt/luci#3341]
OpenWrt SNAPSHOT r11560-e7a96acf1b / LuCI Master git-19.324.23065-4fe16b1

UI just spining forecerwithout any error

**Comment by thoj** [comment]
Same here: 

Openwrt: openwrt-19.07 branch (git-19.323.62987-b23c900) / OpenWrt 19.07.0-rc1 r10649-c4fdb377a2 

Luci: git-19.324.23079-c0b9fbb-1

**Comment by thoj** [comment]
If I add mac aress manually to config/dhcp and click edit i get this:

![image](https://user-images.githubusercontent.com/153440/69372820-c22a2a80-0ca2-11ea-8b24-5250545a8796.png)
