### ISSUE TITLE
luci-proto-qmi is not displaying link informations 

### ISSUE THREAD

**Issue by bgiboudeau** [openwrt/luci#3349]
It would be great if we can have in the status section some details about the link status.
Something a bit like the Wifi status section, it's very helpfull to see quickly where do we stand with the radio interface.

Some informations from the command : uqmi -d "modem" --get-signal-info
   **- Link type : LTE, 3G, GPRS, ...
   - rssi / rsrq / rsrp & snr.**

Some informations from the command : uqmi -d "modem" --get-serving-system
   **- registration
   - plmn_mcc
   - plmn_mnc
   - plmn_description
   - roaming**

Thanks a lot
bgiboudeau

**Comment by jow-** [comment]
Feel free to open a PR adding this functionality. I lack hardware and information to implement this.
