### ISSUE TITLE
proto tayga gets shown as "unsupported protocol type" in Network -> Interfaces

### ISSUE THREAD

**Issue by Schimmelreiter** [openwrt/luci#3353]
Powered by LuCI openwrt-19.07 branch (git-19.326.61751-179c5e8) / OpenWrt 19.07.0-rc1 r10649-c4fdb377a2

I have tayga configured in /etc/config/network like this:
```
config interface 'nat64'
        option proto 'tayga'
        option ifname 'tayga-nat64'
        option ipv4_addr '192.168.64.1'
        option ipv6_addr '2001:470:50ed::1'
        option prefix '64:ff9b::/96'
        option dynamic_pool '192.168.64.0/24'
        option accept_ra '0'
        option send_rs '0'
```
This interface appears as "unsupported protocol type" in luci:
![image](https://user-images.githubusercontent.com/2022025/69482313-bad95d00-0e19-11ea-8a55-18c44abcd680.png)

**Comment by jow-** [comment]
There is no LuCI support for this protocol, hence the message.
