### ISSUE TITLE
[luci.js] invalid XML

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#3357]
* exhibits on Master and 19.07
* exhibits with different browsers
___
Accessing _/cgi-bin/luci/admin/status/processes_ prints (depending on browser)

> Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.

or

> SyntaxError
An invalid or illegal string was specified
___
Browser console points to _luci.js_

`162 else if(children!==null&&children!==undefined){node.innerHTML=''+children;return node.lastChild;}`

**Comment by jow-** [comment]
Which theme?

**Comment by n8v8R** [comment]
OpenWrt theme only, does not exhibit with Bootstrap or Material.

luci-mod-status git-19.329.02080-e3b3653-1.0 (that is on Master).

**Comment by jow-** [comment]
Hm, there is no revision `e3b3653` in the repo. The `1.0` revision looks odd as well. Is this some LuCI fork?

**Comment by n8v8R** [comment]
No fork

`opkg info luci-mod-status`

> Package: luci-mod-status
> Version: git-19.329.02080-e3b3653-1.0
> Depends: libc, luci-base, libiwinfo, libiwinfo-lua
> Status: install user installed
> Section: luci
> Architecture: arm_cortex-a9_vfpv3
> Size: 25498
> Filename: luci-mod-status_git-19.329.02080-e3b3653-1_arm_cortex-a9_vfpv3.ipk
> Description: LuCI Status Pages
> Installed-Time: 1574668515

**Comment by jow-** [comment]
That version is newer than the current LuCI branch tip and newer than whats available on the download server. You must be building from some different source, or with custom commits applied or something.

**Comment by n8v8R** [comment]
A bit strange since the LuCI packages are being pulled straight from the OpenWrt feed (server).

Closing since being a minor issue and exhibiting only OpenWrt theme.
