### ISSUE TITLE
luci-admin: "MSS Clamping" check box is no longer displayed

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#3394]
19.07-SNAPSHOT

Unless, it is intentional, I remember seeing "MSS Clamping" as a second checkbox on this page right after "Masquerading".

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/5624569/70348240-48f90e80-1830-11ea-9784-973cd9c7422f.png">

**Comment by jow-** [comment]
Yes it is intentional, you can still set it in the advanced zone settings.
