### ISSUE TITLE
How to remove /admin/status/overview wireless section?

### ISSUE THREAD

**Issue by Mosney** [openwrt/luci#3396]
I removed wireless card and its drives, but luci still show this section, I want to know how to remove it.
![image](https://user-images.githubusercontent.com/22477230/70458880-049a9680-1aee-11ea-9355-a95066780c41.png)

**Comment by feckert** [comment]
What branch?
* master
* 19.07
* 18.06

**Comment by Mosney** [comment]
Sorry to not note version, I am using 19.07rc2.

**Comment by jow-** [comment]
Removing `/etc/config/wireless` should be enough to disable this.

**Comment by Mosney** [comment]
Thx for your help! It worked.
