### ISSUE TITLE
Menu entry for wifi schedule not purged after package removal

### ISSUE THREAD

**Issue by dim6003** [openwrt/luci#3397]
removed package as it is not (yet?) capable of managing different SSID (I've finally done it with cron & uci). but wifi still present in Services Menu. when clicking on it, I get:
```
Failed to execute cbi dispatcher target for entry '/admin/services/wifi_schedule/tab_from_cbi'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:53: Model 'wifischedule/wifi_schedule' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/cbi.lua:53: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:943: in function </usr/lib/lua/luci/dispatcher.lua:937>
```

Hardware is Zyxel Armor V2, OpenWrt installed 2 days ago (so I guess last version) :
OpenWrt SNAPSHOT r11618-416d2cc71e / LuCI Master git-19.339.73009-ea6d0d2
Kernel : 4.14.156
I did not reboot (yet)

**Comment by feckert** [comment]
A

> rm -rf /tmp/luci-indexcache

 should solve this issue
