### ISSUE TITLE
luci-app-firewall: shouldn't it be the other way around?

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3408]
![1](https://user-images.githubusercontent.com/47670442/70760394-4adb3a00-1d28-11ea-89f7-30c72f0d33a9.PNG)
![2](https://user-images.githubusercontent.com/47670442/70760395-4adb3a00-1d28-11ea-923d-7c2e836bb6dc.PNG)

Which one to believe?

**Comment by jow-** [comment]
Not sure what you mean but there is nothing reversed here.

Source zone should be your upstream, most comonly wan. External port is the port exposed to the upstream network. Destination zone is the network you're forwarding the port to and internal port is the port of the service you're forwarding to.

This also aligns with what the text description is showing. To me it looks as if you simply swapped lan and wan zones when you declared that port forward.

**Comment by castillofrancodamian** [comment]
You are right. I was upside down. Well, actually Firewall areas.
