### ISSUE TITLE
luci-admin: the flash firmware page never refreshes after the router is back up

### ISSUE THREAD

**Issue by fantom-x** [openwrt/luci#3409]
19.07-SNAPSHOT
GL-B1300 & R7800
Firefox & Brave Browser

Luci used to redirect to the login page after a successful flash, but it stopped doing that recently.

**Comment by jow-** [comment]
I just tried it with a sysupgrade from current master to 19.07-SNAPSHOT and vice versa and page refresh worked as expected for me.

**Comment by fantom-x** [comment]
Still does not work for me in master/19.07 in Firefox/Brave in MacOS & Windows. Not a big deal though.
