### ISSUE TITLE
OpenWrt 19.07.0-rc2 Firewall Weekdays Problem

### ISSUE THREAD

**Issue by dfatland** [openwrt/luci#3445]
Device problem occurs on
TP-Link Archer C7 v4

Software versions of OpenWrt/LEDE release, packages, etc.
OpenWrt 19.07.0-rc2 r10775-db8345d8e4 / LuCI openwrt-19.07 branch git-19.334.63023-039ef1f

Steps to reproduce
Luci→Network→Firewall→Traffic Rules→Add/Edit
Set weekdays to Sunday+Saturday.

We get:
/etc/config/firewall

[code]
...
config rule
    option dest 'wan'
    option proto 'tcp udp'
    list weekdays 'Sun'
    list weekdays 'Sat'
    option src_ip '192.168.10.80/28'
    option src 'lan'
    option target 'ACCEPT'
    option start_time '13:00:00'
    option name 'Allow Kids Weekend Afternoon'
    option stop_time '18:00:00'
...
[/code]

fw3 doesn’t allow weekdays to be a list

[code]
root@OpenWrt:/etc/config# fw3 print
Warning: Option @rule[2].weekdays must not be a list
Warning: Section @rule[2] (Allow Kids Weekend Afternoon) skipped due to invalid options
...
[/code]

**Comment by jow-** [comment]
This has been fixed already before you opened this issue. https://github.com/openwrt/luci/commit/18c60968dc9ee280ea8a71bb98653b74a340668a
