### ISSUE TITLE
Luci allows long firewall zone names, fw3 does not support them

### ISSUE THREAD

**Issue by eriktews** [openwrt/luci#345]
There is a problem with the firewall configuration. Luci allows you to configure long firewall zone names, such as averyveryverylongfirewallname. Of course you can do the same by hand by editing the configuration file. Assume you have something like this in '/etc/config/firewall'_

>config zone                   
>        option name 'averyveryverylongfirewallname'
>        option input 'ACCEPT'
>        option forward 'REJECT'
>        option output 'ACCEPT'
>        option network 'averyveryveryverylongname'

When you restart your firewall, you get:

> Warning: Section @zone[2] (averyveryverylongfirewallname) must not have a name longer than 14 characters

fw3 does not support such long names, see:

http://nbd.name/gitweb.cgi?p=firewall3.git;a=blob;f=zones.c;h=2ddd7b44443f3b2714e19ffb2f8b8b29320700d2;hb=HEAD#l195

> 195                 if (strlen(zone->name) > FW3_ZONE_MAXNAMELEN)
> 196                 {
> 197                         warn_elem(e, "must not have a name longer than %u characters",
> 198                                      FW3_ZONE_MAXNAMELEN);
> 199                         fw3_free_zone(zone);
> 200                         continue;
> 201                 }

Currently, FW3_ZONE_MAXNAMELEN is defined as 14 in:

http://nbd.name/gitweb.cgi?p=firewall3.git;a=blob;f=zones.h;h=4205196268f75061280ac13da656ab4362245a06;hb=HEAD#l26

>  26 #define FW3_ZONE_MAXNAMELEN 14

I suggest to limit the length of the input filed in the web interface to 14 characters at most.

**Comment by hnyman** [comment]
Fixed in trunk
