### ISSUE TITLE
luci-app-ddns: wrong outdated warning when using no-ip without no-ip support

### ISSUE THREAD

**Issue by Zokormazo** [openwrt/luci#346]
If I build ddns-scripts without no-ip support and add a no-ip ddns host to dynamic-dns, Status-> Overview complains saying that I have an outdated ddns-scripts package.

Shouldn't warning something different for this case? The package is not outdated, it lacks no-ip support.

**Comment by chris5560** [comment]
It looks like that something went wrong during update from older version.
The current system_status.htm has no js code to display something about old version.
On ddns service->overview there is still a version check done and displayes under "Hints".
When you click on the link "Dynamic DNS" on ddns overview page you will get version information for ddns-scripts and luci-app-ddns.

**Comment by chris5560** [comment]
@Zokormazo 
Is the problem fixed or not ?
Thanks for feedback.
Christian

**Comment by Zokormazo** [comment]
@chris5560 

As you said it was a some kind of garbage problem. I tried with a clean buildroot and reseted router and the problem is gone.

You can close it ;)

**Comment by chris5560** [comment]
Thanks for feedback
