### ISSUE TITLE
make Error

### ISSUE THREAD

**Issue by snakwu** [openwrt/luci#3461]
c1: some warnings being treated as errors                                             
Makefile:1891: recipe for target 'Modules/posixmodule.o' failed                        
make[4]: *** [Modules/posixmodule.o] Error 1                                           
make[4]: Leaving directory '/home/snakwu/openwrt-master/openwrt/build_dir/target-x86_64
_musl/Python-3.8.1'                                                                    
Makefile:358: recipe for target '/home/snakwu/openwrt-master/openwrt/build_dir/target-x
86_64_musl/Python-3.8.1/.built' failed                                                 
make[3]: *** [/home/snakwu/openwrt-master/openwrt/build_dir/target-x86_64_musl/Python-3
.8.1/.built] Error 2                                                                   
make[3]: Leaving directory '/home/snakwu/openwrt-master/openwrt/feeds/packages/lang/pyt
hon/python3'                                                                           
time: package/feeds/packages/python3/compile#2.20#0.12#2.92                            
package/Makefile:111: recipe for target 'package/feeds/packages/python3/compile' failed
make[2]: *** [package/feeds/packages/python3/compile] Error 2                          
make[2]: Leaving directory '/home/snakwu/openwrt-master/openwrt'                       
package/Makefile:107: recipe for target '/home/snakwu/openwrt-master/openwrt/staging_di
r/target-x86_64_musl/stamp/.package_compile' failed                                    
make[1]: *** [/home/snakwu/openwrt-master/openwrt/staging_dir/target-x86_64_musl/stamp/
.package_compile] Error 2                                                              
make[1]: Leaving directory '/home/snakwu/openwrt-master/openwrt'                       
/home/snakwu/openwrt-master/openwrt/include/toplevel.mk:225: recipe for target 'world' 
failed                                                                                 
make: *** [world] Error 2

**Comment by hnyman** [comment]
No connection to LuCI GUI.
```

Makefile:1891: recipe for target 'Modules/posixmodule.o' failed
make[4]: *** [Modules/posixmodule.o] Error 1
make[4]: Leaving directory '/home/snakwu/openwrt-master/openwrt/build_dir/target-x86_64
_musl/Python-3.8.1'
```

You have some error with python 3.8.1 compilation, but that is in the packages feed, not here.

(And as the buildbot has no error with python, you might check and clean your own build env first.)
