### ISSUE TITLE
Change root password

### ISSUE THREAD

**Issue by mamohammadi** [openwrt/luci#3463]
Hi
When I try to change root password via Luci interface I got 'Failed to change the system password.'. I used passwd to change root password but again I got 
failed to crypt password with salt '$6$j16Ty/66IL'. Function not implemented.

**Comment by hnyman** [comment]
That salt '$6$j16Ty/66IL' references to SHA512.

Capability for SHA512 passwords is not a built-in default, so likely you are trying to configure/use something extra. Possibly you have not enabled that in all relevant places.

**Comment by jow-** [comment]
Closing this as this is not related to LuCI at all. It uses libc`s `crypt()` and/or the busybox `passwd` applet.
