### ISSUE TITLE
The changes can not be applied in interface of luci openwrt-19.07 at the same time

### ISSUE THREAD

**Issue by alisaeed** [openwrt/luci#3465]
Hi 
When I change only static IP v4 value in LAN interfaces everything is OK but when I change static IP v4 with other settings such as "IPv4 netmask" , DHCP server start IP value and limit IP value then my settings will not apply.

**Comment by jow-** [comment]
Works as expected for me. Make sure to either use `Apply unchecked` or, when the apply timeout/rollback occurred to force applying.
