### ISSUE TITLE
broken wireless info

### ISSUE THREAD

**Issue by Ansuel** [openwrt/luci#3467]
Think related to recent iwinfo changes
![Annotazione 2020-01-05 204503](https://user-images.githubusercontent.com/20289090/71785129-4b4fb380-2ffc-11ea-9e79-00876b04a8ee.jpg)

**Comment by hnyman** [comment]
Where? With what?
Seems to work ok with r11922-2d80f7e836 using normal uhttpd and bootstrap theme.

![image](https://user-images.githubusercontent.com/7926856/71785615-4abe1980-300a-11ea-9446-2be0c453b85a.png)

**Comment by Ansuel** [comment]
Mvebu

**Comment by hnyman** [comment]
Works for me with my mvebu WRT3200ACM at r11922-2d80f7e836 with uhttpd and bootstrap theme

![image](https://user-images.githubusercontent.com/7926856/71785892-a0e08c00-300d-11ea-8086-9c029946fb83.png)

**Comment by jow-** [comment]
Works fine for me too on a Mir3G. Your screenshot looks like a memory/ABI corruption though, make sure that `libiwinfo` and `libiwinfo-lua` as well as `rpcd-mod-iwinfo` are in sync and all updated / rebuilt to their latest version.

**Comment by Ansuel** [comment]
Aside the fact that is caused by my buildroot... I think there is a problem in detecting abi change by the dependent package. Shouldn't they had to rebuild automatically after a version upgrade?
