### ISSUE TITLE
RPC IP call not working

### ISSUE THREAD

**Issue by jacekpaszkowski** [openwrt/luci#3470]
version: OpenWrt SNAPSHOT r11890-e98e046f06

In latest version i'm not able to call JSONRPC methods, it worked in snapshot version from september 2019.

eg.
http://192.168.x.x/cgi-bin/luci/rpc/ip
```
{"method": "neighbors", "params": [{"family": 4}]}
```

response:
```
{
"id": null,
"error": {
"message": "Parse error.",
"code": -32700
},
"jsonrpc": "2.0"
}
```

http://192.168.x.x/cgi-bin/luci/rpc/sys
```
{
  "method": "exec",
  "params": ["echo 'hello world'"]
}
```
response:
```
{
"id": null,
"error": {
"message": "Parse error.",
"code": -32700
},
"jsonrpc": "2.0"
}
```
Only auth method works correctly.

**Comment by jacekpaszkowski** [comment]
@jow- nice to see that the issue is fixed. When there will be new build available of snapshot version ramips/mt7621/?
Sould i update luci packages or do sysupgrade?

**Comment by jow-** [comment]
Not sure when new builds will be available but when they are, an `opkg update; opkg upgrade luci-base; rm -r /tmp/luci-*` should be enough to get things going again.
