### ISSUE TITLE
UPnP Not Working 19.07+

### ISSUE THREAD

**Issue by willowen100** [openwrt/luci#3471]
I can confirm that UPnP doesn't work. I tried the official stock openwrt firmware version 19.07.0-rc2 and UPnP didn't show any entries. I have also tried compiling from master and that does the same thing. As soon as I flashed 18.06.5 LuCI-App-UPnP worked straight away.

My Router: WRT1900ACSv2
Test devices/software: Sony PS3, Sony PS4, Windows qBitorrent

**Comment by solidus1983** [comment]
Its also not working in Master either. have noticed this with OpenWrt SNAPSHOT r11888-32e4eaef1b

**Comment by jow-** [comment]
I doubt that it is a LuCI issue though. In my local tests I was unable to reproduce the problem in the first place. Entries showed up when using `upnpc` on a Linux box to manually request forwards, and starting `transmission-gtk` also immediately triggered port forwards for Bittorrent.

Maybe the package feed changed the `miniunpd` daemon in way that it became incompatible with certain devices, but that issue should be raised here then: https://github.com/openwrt/packages/issues?utf8=%E2%9C%93&q=miniupnpd+is%3Aissue

Maybe it is also a problem with multicast traffic and mwlwifi...

**Comment by solidus1983** [comment]
Managed to get it working again by deleting the content of upnpd in /etc/config folder and just resetting it all back up. I was mearly point to the person above I had the same issue on the master branch.

But thanks for your input jow.

**Comment by manjuprajna** [comment]
I also have same problem, have to check enable UPnP NAT-PMP service, than it showes active upnp redir again. mine is a WRT32x but I think nothing to do with mwlwifi since I am using utorrent on desktop with ethernet cable.

**Comment by jow-** [comment]
Seems to be a configuration issue.

**Comment by willowen100** [comment]
Sorry for the late reply back. I have empty the entire contents of /etc/config and then restarted the miniupnpnd service. List still empty.

I have noticed that the settings in more recents builds are simply removed when the setting is the default value, rather than keeping the setting in the config and just changing the value

E.g. 
`option enabled '1'
	option enable_upnp '1'
	option enable_natpmp '1'
	option igdv1 '1'`

With this inside the upnpd file if I go back to LuCI and apply changes without actually making any in changes in LuCI straight away UCI removes the parameters.

**Comment by willowen100** [comment]
![Screenshot_20200110-223111_Firefox](https://user-images.githubusercontent.com/8084389/72191192-5c803200-33f9-11ea-8487-b7b0ca813afd.jpg)

**Comment by jow-** [comment]
LuCI removes these options because they're the default value:
https://github.com/openwrt/packages/blob/master/net/miniupnpd/files/miniupnpd.init#L135

**Comment by willowen100** [comment]
I've literally just flashed the new 19.07.0 update compiled by myself with the LuCI-App-UPnP package and tried clearing the /etc/config/upnpd and nothing works. What else can I try?

**Comment by moralrebuild** [comment]
still not work on 19.07.1. Please fix this minor bug ASAP

**Comment by willowen100** [comment]
I can say that I managed to flash the v18.06.1 version of UpNP into v19.07.1 firmware and it works perfectly. There is definitely something up with the new builds of Miniupnpd.
