### ISSUE TITLE
translation: zh_Han{s,t} and zh-{cn,tw} mixture

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#3477]
Hi, we partly have the *old* and new format for Simplified Chinese and Traditional Chinese. Somebody who speaks the languages, please merge them to zh-{cn,tw} as the zh_Han{s,t} format is not compatible with the browser language detection.

Current cases are:
* luci-app-nextdns
* luci-app-vpn-policy-routing

**Comment by jow-** [comment]
There's also `nb_NO` and `pt_BR` which conflict with `no` and `pt-br` respectively.

**Comment by ElonH** [comment]
the script 

https://github.com/openwrt/luci/blob/master/build/i18n-add-language.sh

wasn't updated.
