### ISSUE TITLE
luci.subsignal.org can't access?

### ISSUE THREAD

**Issue by van9ogh** [openwrt/luci#348]
Hello, Recently I find except the index page, the other trac pages are return error.

Please check this Problem, Thx~

![luci error](https://forestgump.me/content/images/2015/03/Internal-Error---LuCI-1.png)

**Comment by hnyman** [comment]
The site is up, but as development is now at Github, not all sections have been enabled.
The wiki shown in above picture, works though: http://luci.subsignal.org/trac/wiki/Documentation
