### ISSUE TITLE
luci-app-bmx7: CSS translate is treated as translate string

### ISSUE THREAD

**Issue by urbalazs** [openwrt/luci#3484]
There are some CSS `translate`, which are handled as translate for strings. Because of this the language files contain program codes, like:

```po
#: applications/luci-app-bmx7/root/www/luci-static/resources/bmx7/js/netjsongraph.js:510
msgid "+ d.x +"
msgstr ""

#: applications/luci-app-bmx7/root/www/luci-static/resources/bmx7/js/netjsongraph.js:173
msgid "+ d3.event.translate +"
msgstr ""
```

What about, if a translator add different translations? Will them be replaced and break the code?

https://github.com/openwrt/luci/blob/master/applications/luci-app-bmx7/root/www/luci-static/resources/bmx7/js/netjsongraph.js#L173

```js
redraw: function() {
    panner.attr("transform",
        "translate(" + d3.event.translate + ") " +
        "scale(" + d3.event.scale + ")"
    );
 },
```

https://github.com/openwrt/luci/blob/master/applications/luci-app-bmx7/root/www/luci-static/resources/bmx7/js/netjsongraph.js#L510

```js
 labels.attr("transform", function(d) {
    return "translate(" + d.x + "," + d.y + ")";
});
```

**Comment by jow-** [comment]
No, it will not break code if translators accidentally translate those msgids.
