### ISSUE TITLE
luci-mod-network: wireless SAE MFP bug

### ISSUE THREAD

**Issue by psyborg55** [openwrt/luci#3486]
selecting WPA3 and optional or require MFP setting works as expected, setting MFP to disabled removes config entry for MFP and luci reverts it to required. from what i read it should be possible to use SAE without MFP.

OpenWrt SNAPSHOT r11895-fba8083 / LuCI Master git-20.004.64129-d60a1a1

**Comment by jow-** [comment]
LuCI follows the OpenWrt implementation here: https://github.com/openwrt/openwrt/blob/master/package/network/services/hostapd/files/hostapd.sh#L328

Currently neither SAE, nor SAE-PSK (mixed) allow disabling MFP.
