### ISSUE TITLE
OpenWRT - Dependency error - libiwinfo20200105

### ISSUE THREAD

**Issue by matadams91** [openwrt/luci#3487]
I'm getting error while installing Luci from package http://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/luci_git-20.008.20448-a8087bd-1_all.ipk.
Before installation I made repo update with opkg update, but it still won't work.

Collected errors: 
* satisfy_dependencies_for: Cannot satisfy the following dependencies for Lucy: 
*      libiwinfo20200105

I also tried to use another package from the other version: http://downloads.openwrt.org/snapshots/packages/mipsel_24kc_24kf/
Same results.
Does anyone have similar issues and found a solution for it?

**Comment by feckert** [comment]
The package libiwinfo is managed in the package feed.
To make the packages fit together you should install a new image for your hardware and then install the Luci from there. Then it should fit together again. In a stable release this should work the way you did it. But the master is very fragile and something changes all the time.

**Comment by jow-** [comment]
Not a LuCI issue.
