### ISSUE TITLE
luci: SORT ORDER for network interfaces & realtime (bandwidth)

### ISSUE THREAD

**Issue by camelcamro** [openwrt/luci#3495]
current trunk: git-20.004.33955-4c4d6e2) / OpenWrt SNAPSHOT r11890-e98e046f06

Hello,
in luci the showing of the interfaces is not very well :(

well, on older versions, the sort order was much more better as currently ...

that is now not ok on:

NETWORK -> ITERFACES (eg. interfaces on firewall can be sorted via GUI)
STATUS -> REALTIME -> TRAFFIC (bandwidth)
STATUS -> MWAN3 -> STATUS + DETAIL

that is currently seems to be not sorted and is different ...
can it be set to be sort by INTERFACE NAME anyhow ?

if i get a hint howto i can test or try, but not familar with that graph sort order stuff

**Comment by jow-** [comment]
Should be fixed with 8199b2ce9a, 37422e891a, 801d4513b2
