### ISSUE TITLE
Connections number (uhttpd / option max_requests)

### ISSUE THREAD

**Issue by y-alexey** [openwrt/luci#3498]
Who are manage uhttpd default config file?

Look like _option max_requests 3_ is terrible choice for interaction with modern browsers.

**Comment by feckert** [comment]
Maybe this file https://github.com/openwrt/openwrt/blob/master/package/network/services/uhttpd/files/uhttpd.config ?

**Comment by jow-** [comment]
The file is maintained in OpenWrt base.
