### ISSUE TITLE
Wireguard interface dialogue

### ISSUE THREAD

**Issue by y-alexey** [openwrt/luci#3499]
Missing network mask configuration option.

That's not matter, if you using only one upstream connection. But in case of multiple income tunnels, or when try to configure interface for bgp, I need to add mask option for this interface manually by _/etc/config/network_ file editing.

**Comment by jow-** [comment]
Which option is missing where exactly?

**Comment by y-alexey** [comment]
Interface mask option
`option netmask '255.255.255.0'` for example.

**Comment by jow-** [comment]
The underlying OpenWrt protocol handler does not specify a netmask option, instead you‘re supposed to use CIDR or address/mask notation, e.g. `192.168.1.1/24` or `192.168.1.1/255.255.255.0`

**Comment by y-alexey** [comment]
Thank you for your time. But I not really understand how to report issue to openwrt.
Wireguard case it's only one.
