### ISSUE TITLE
luci-app-transmission: UI mismatch

### ISSUE THREAD

**Issue by ahmar20** [openwrt/luci#3503]
I have seen this quite a few times when configuring transmission from LuCI but did not find much time to report it. 

The issue is with some or probably all of the config options where for instance you enable an option and it provides you with another option to write something. Now the new option should possibly be under the enabled option but for some reason it shows up under the global config options.

See the screenshot:
![2020-01-14 (2)](https://user-images.githubusercontent.com/18096216/72335625-179e1900-36e1-11ea-9bcb-855ff9b911bc.png)

But then if you save your changes, whether hit Save or Save&Apply the config options align to as they should. Possibly the code that adds them initially has a bug somewhere. Hopefully someone can take a look.

**Comment by jow-** [comment]
Fixed via #3530
