### ISSUE TITLE
luci-base: make cgi-bin entires configurable

### ISSUE THREAD

**Issue by Ansuel** [openwrt/luci#3505]
I notice that all the cgi-bin/cgi-exec entries are hardcoded to a non configurable path. This can cause some problem if someone wants to make the luci ui accessible in a different location than the root directory.
Is it possible to make them configurable like we already do for the luci-static directory? 

Also it would be good to change the index file to a non absolute path.

**Comment by jow-** [comment]
If you feel like working on it, I'll see what you come up with. Personally I lack time, motivation and interest to invest time into it.
