### ISSUE TITLE
When changing WiFi settings LuCI also changes WiFi security settings

### ISSUE THREAD

**Issue by madmalkav** [openwrt/luci#351]
Tried with WNR3500L v1, r44972, kmod-brcm-wl

If you have security configured, i.e. for WPA/WPA2 mixed and auto cypher and you change any other setting in the wifi settings, it will change security to WPA TKIP .

**Comment by cshoredaniel** [comment]
Can you verify this issue exists with current LuCI and openwrt?  It works for me.

**Comment by madmalkav** [comment]
I no longer have that device at hand, so it is impossible for me to test further.
