### ISSUE TITLE
Missing "reload" and "enable" in LuCIs Firewall Custom Rules

### ISSUE THREAD

**Issue by JoeSem** [openwrt/luci#352]
For injecting iptables rules into internal chains the parameter "reload" (section "includes") has to be set to boolean "1" Would be fine if this is possible via checkbox in LuCi Firewall/Custom Rules. 

Also helpful, a checkbox for disabling Custom Rules. With the parameter "enable" and value "0" this is also possible in the section "includes".

**Comment by dibdot** [comment]
please re-test against latest master branch
