### ISSUE TITLE
[19.07] cherry-pick: luci-base: cbi.js: collapse whitespace before language string hashing

### ISSUE THREAD

**Issue by karlp** [openwrt/luci#3523]
Please cherry-pick https://github.com/openwrt/luci/commit/aca2c4ba4e4c847e5ae86e5539537f213678a0f3 into the 1907 branch.

Spoke to jow abotu it on irc
```
10:36 <karlp> jow: can we get that cbi.js translation into 1907 too please?
11:06 <jow> sure
```

Just filing a ticket so we don't forget about it altogether.   No rush.

**Comment by jow-** [comment]
f46357059
