### ISSUE TITLE
Dropbear/SSH Settings missing

### ISSUE THREAD

**Issue by madduci** [openwrt/luci#3528]
I've updated my router to OpenWRT 19.07 stable, following also the [upgrade tutorial](https://openwrt.org/docs/guide-user/installation/ar71xx.to.ath79) to move from ar71xx to ath79.

Since the upgrade, I cannot see in LuCi the dropbear/ssh authentication settings anymore.

Additional information:

* Firmware Version: OpenWrt 19.07.0 r10860-a3ffeb413b / LuCI openwrt-19.07 branch git-20.016.32041-5baeb64
* Router Version: TP-Link Archer C7 v2.0

**Comment by jow-** [comment]
Works for me. The settings are in System -> Administration. If you still can't find them, make sure that your dropbear configuration is not corrupted. Execute `uci show dropbear >/dev/null` on the command line to see potential errors.

**Comment by madduci** [comment]
In Systems->Administration i can only change the root password, but there's no dialog for Dropbear and I cannot login in my router to issue the command, since it is not configured/disabled.

Should I flash the factory image, erasing everything?

**Comment by ysc3839** [comment]
It's here.
![image](https://user-images.githubusercontent.com/12028138/72666077-adbba180-3a49-11ea-808c-b57b55cbf8c9.png)
Also dropbear is enabled by default. If you can't login via SSH, I guess there's something wrong.

**Comment by hnyman** [comment]
@jow- 
Apparently there is no menu tab, if there is no /etc/config/dropbear file at all.
I tested by renaming the file and the "SSH Access" tab is not shown.

![image](https://user-images.githubusercontent.com/7926856/72666234-d7a8a000-3a18-11ea-82a7-0ff465c94c91.png)

**Comment by madduci** [comment]
exactly, there's was no tab after the flashing of the sysupgrade firmware.

I have done a factory reset and now it's there, but the upgrade from 18.06.5 ar71xx to 19.07 ath9 had problems with configuration files.

**Comment by hnyman** [comment]
Just for future reference: 
I figured out how it can be fixed also from LuCI...

* opkg install "luci-app-commands"  (Luci custom commands)
* create three commands that create the dropbear uci config file, enter there the simplest uci content, and commit it:
   * touch /etc/config/dropbear
   * uci add dropbear dropbear
   * uci commit dropbear
* run those custom commands from LuCI

That creates enough good dropbear config file that the LuCI config page gets shown properly.

![image](https://user-images.githubusercontent.com/7926856/72666428-d7a99f80-3a1a-11ea-95bc-019258ed211c.png)
