### ISSUE TITLE
luci-app-firewall: LuCI support for IP Set

### ISSUE THREAD

**Issue by JoeSem** [openwrt/luci#353]
UCI Firewall V3 is supporting IP Set to simplify matching of huge address or port lists without the need for creating one rule per item to match.

Would be great to have this functionality also avaliable li LuCI Firewall.
For more details refer to http://wiki.openwrt.org/doc/uci/firewall#ip_sets

**Comment by jhuebner79** [comment]
+1 - much anticipated feature

**Comment by guidosarducci** [comment]
Let me also chime in that support for both "IP Sets" and "DSCP Marking" are my top wishes for `luci-app-firewall`, and I suspect for others too.

**Comment by hnyman** [comment]
Closing this old feature request, as ipset support for firewall is currently being implemented in PR #6187 

(and for DCSP marking there is already the qosify package, although it is not supported in LuCI).
