### ISSUE TITLE
Can't configure 'switch' in LuCI on Trunk on TP-Link Archer C2 V1

### ISSUE THREAD

**Issue by cvmiller** [openwrt/luci#3535]
Version: OpenWrt SNAPSHOT r12040-8df14c229c / LuCI Master git-20.016.76613-0608ff0

On a TP-Link Archer C2 v1, when using the LuCI menu Network->Switch, the page shows an error at the top: "Cannot read property 'link' of undefined"

Do NOT see switch status or any information about the switch

**Comment by jow-** [comment]
#3534
