### ISSUE TITLE
Real time graphs - load averages (high load when displaying)

### ISSUE THREAD

**Issue by mustangtyson** [openwrt/luci#3537]
When you view the load averages in the [Status->Overview] screen my load averages are all 0.05. But when i turn in the graph of this under [Real time graphs -> load averages] my 1 min load average climbs up to 0.5 and stays there. It seems like the real time graph screen is using putting a lot of load on the system to update this screen.
OS: OpenWRT 19.07
Hardware: Ubiquity Edgerouter X

**Comment by jow-** [comment]
Yes it does produce some load due to the polling. There is no fix to this, especially if you use HTTPS.
