### ISSUE TITLE
Problem with material theme 

### ISSUE THREAD

**Issue by alisaeed** [openwrt/luci#3539]
Hello,
I found two problems in material theme (My branch is 19.07) :

1: Save&Apply drop down menu (both foreground and background are white):
![save applay](https://user-images.githubusercontent.com/3950839/72706890-5ebe5b00-3b74-11ea-948c-ac22c8b483b3.PNG)

2: Save button : 
![save](https://user-images.githubusercontent.com/3950839/72707219-2cf9c400-3b75-11ea-8a83-481a1bf583de.png)

**Comment by jow-** [comment]
@LuttyYang

**Comment by alisaeed** [comment]
We changed cascade.css in material theme as follow:

.cbi-dropdown[open] > ul.dropdown {
	position: absolute;
	z-index: 1100;
	display: block;
	width: auto;
	min-width: 100%;
	max-width: none;
	max-height: 200px !important;
	border: thin solid #918e8c;
	background: #f6f6f6;
	box-shadow: 0 0 4px #918e8c;
	**color: var(--main-menu-color);**
}

Result : 
![save applay](https://user-images.githubusercontent.com/3950839/72719897-05fbbc00-3b8e-11ea-8953-f8dbe25b7386.PNG)

**Comment by feckert** [comment]
Thanks :+1:
fixed with your suggestion see commit https://github.com/openwrt/luci/commit/1c49bda198ef33c0423777a966e6c6ab477da34b will also cherry-pick this to the branch openwrt-19.07

**Comment by feckert** [comment]
Also fixed with https://github.com/openwrt/luci/commit/c395d438074e598d6e51d5ed104f5712f79b63b6 in openwrt-19.07
