### ISSUE TITLE
luci-theme-material: save button problem

### ISSUE THREAD

**Issue by alisaeed** [openwrt/luci#3540]
Hello,
We found problem in material theme (My branch is 19.07):

![72707219-2cf9c400-3b75-11ea-8a83-481a1bf583de](https://user-images.githubusercontent.com/3950839/72732681-71a05200-3bab-11ea-89fc-11c11cc59ce5.png)

We Solved this problem in cascade.css as follow : 

.modal .spinning {
	`/*margin-bottom: 2em;*/`
}

@feckert , @jow-

**Comment by feckert** [comment]
![Screenshot_2020-01-21 G3000-LLW - Interfaces - LuCI](https://user-images.githubusercontent.com/553091/72781315-45bfb380-3c21-11ea-8689-e1737329ac9c.png)

I can not reproduce your problem. What browser do you use?

**Comment by alisaeed** [comment]
When you click save button this happens (save button changes to spinning button and this problem happens).

We Solved this problem in cascade.css as follow :
.modal .spinning {
/*margin-bottom: 2em;*/
}

**Comment by alisaeed** [comment]
> ![Screenshot_2020-01-21 G3000-LLW - Interfaces - LuCI](https://user-images.githubusercontent.com/553091/72781315-45bfb380-3c21-11ea-8689-e1737329ac9c.png)
> 
> I can not reproduce your problem. What browser do you use?

When you click save button this happens (save button changes to spinning button and this problem happens). I've tested this in different browsers.

**Comment by feckert** [comment]
Ok thanks for the explanation. I could reproduce this.
Will remove this section from the css.
https://github.com/openwrt/luci/blob/cc01770fa1cf09b729dd931df77b149d1b20d2ef/themes/luci-theme-material/htdocs/luci-static/material/cascade.css#L1675-L1679

**Comment by feckert** [comment]
Thanks for your fix.
 I have pushed this to master https://github.com/openwrt/luci/commit/71743a7ef69e9ffdf890bf895d704ecc0648548b.
@alisaeed Does we have to push this also to the openwrt-19.07 branch?

**Comment by feckert** [comment]
Thanks for your work
