### ISSUE TITLE
[Bug] luci-app-wireguard: Too many peers results in background not rendering

### ISSUE THREAD

**Issue by Mushoz** [openwrt/luci#3546]
As the screenshot shows, when you have too many peers (4 in this case) the background stops rendering and things are extremely difficult to tell apart.

![Screenshot from 2020-01-21 14-15-52_2](https://user-images.githubusercontent.com/18422243/72808238-702d6300-3c59-11ea-9b12-b350dd72a747.png)

**Comment by jow-** [comment]
Which LuCI version?

**Comment by Mushoz** [comment]
I installed 19.07.0 on this device yesterday. These are the versions currently installed on the device:

luci-ssl-openssl	git-20.016.32041-5baeb64-1
luci	git-20.006.26738-35aa527-1

Functionality is unaffected by the way. All 4 peers work fine.

**Comment by jow-** [comment]
Is the issue persisting after `opkg update; opkg upgrade luci-theme-bootstrap` and browser cache clearing?

**Comment by Mushoz** [comment]
This fixes the issue, thank you! Closing :)
