### ISSUE TITLE
Free memory > Available memory does not make sense

### ISSUE THREAD

**Issue by Juiceman** [openwrt/luci#3551]
![image](https://user-images.githubusercontent.com/77873/72960698-b4655400-3d7c-11ea-9415-45ffa9c42fbd.png)

**Comment by feckert** [comment]
What is the output of `ubus call system info` does this numbers make sense?

**Comment by jow-** [comment]
Works for me.

**Comment by Juiceman** [comment]
I accidentally cropped off the device hardware name. It is WNDR4700 if that helps.
