### ISSUE TITLE
luci-base: "LED Configuration" does not appear translated

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3553]
**Spanish**

![Screenshot_20200123_150328](https://user-images.githubusercontent.com/47670442/73012724-aef82000-3df5-11ea-81af-68e83e4a63ce.png)

**Portuguese**

![2](https://user-images.githubusercontent.com/47670442/73012751-b9b2b500-3df5-11ea-9b80-daacfa30c04e.png)

**French**

![3](https://user-images.githubusercontent.com/47670442/73012962-1f9f3c80-3df6-11ea-93e8-876e528f9f99.png)

**Comment by hnyman** [comment]
Pure hunch, but the reason could be that this menu item has (for some strange reason) a abbreviation structure in the menu string.  That might cause some conflict.

The abbreviation does not even work in the menu item, so it should probably be removed from it.
(but it works in the page header of the .js page)

**Comment by hnyman** [comment]
Likely fixed by 2a1a987

**Comment by castillofrancodamian** [comment]
👍👍👍

**Comment by manjuprajna** [comment]
@hnyman 
under luci zh-cn before 2a1a987, it's good, but after 2a1a987 become like this:
![led](https://user-images.githubusercontent.com/21319864/73117341-345b0c00-3f7f-11ea-958b-9878f6867219.PNG)
so need to do another translate for this?

**Comment by hnyman** [comment]
The string needs to be re-translated into Chinese as there is now a new string for that menu item.

**Comment by castillofrancodamian** [comment]
Ready!

![Sin título](https://user-images.githubusercontent.com/47670442/73123205-3f587100-3f6c-11ea-9866-5994b51edb69.png)
