### ISSUE TITLE
19.07 Cannot login via IP, only http://openwrt/

### ISSUE THREAD

**Issue by Aaron2550** [openwrt/luci#3554]
As the title says, if i try to login via http://192.168.1.1 i get
`Thu Jan 23 20:38:26 2020 daemon.err uhttpd[1139]: luci: accepted login on / for root from 192.168.1.2`
In the Log but nothing happens. The page refreshes and im back at the login screen, ive tried using Chrome and Firefox, tried clearing cache , nothing seems to work

Im using `Powered by LuCI openwrt-19.07 branch (git-20.006.26738-35aa527) / OpenWrt 19.07.0 r10860-a3ffeb413b` On a netgear R6220

**Comment by jow-** [comment]
Sometimes browsers refuse logins after sysupgade when the same IP or host previously had SSL enabled. Either try an incognito tab or clear the site settings (in Firefox: Ctrl+Shift+Del, clear Site Preferences).

From the log line you quoted, everything is fine on the LuCI/uhttpd side but your browser refuses the login cookie.
