### ISSUE TITLE
WOL Services not working using etherwake

### ISSUE THREAD

**Issue by wrtechnopath** [openwrt/luci#3557]
I've upgraded to OpenWrt 19.07.0 r10860-a3ffeb413b / LuCI openwrt-19.07 branch git-20.021.30444-421791d and wanted to utilize the wake-on-lan (WOL) function using LuCI. There are two available programs to execute this, wakeonlan and etherwake. LuCI => Services => Wake on LAN utilizes the etherwake program. It's a clean and simple UI but not functioning correctly.

I broadcast on all interfaces, to my web-server that I want to wake up (the MAC addresses and hostnames are already stored), I've also tried the broadcast address tick box with no luck but a success message.

The wakeonlan command using ssh into the router works.

**Comment by jow-** [comment]
Does it work if you execute `wakeonlan` on the command line?

**Comment by wrtechnopath** [comment]
Yes

**Comment by jow-** [comment]
Which command line do you use exactly that works?

**Comment by wrtechnopath** [comment]
wakeonlan -i 192.168.1.255 MA:CA:DD:RE:SS

**Comment by hmh** [comment]
etherwake seems not to work if you tell it (through LuCI, did not try the CLI) to broadcast to all interfaces.  I use it in broadcast mode all the time from LuCI, but I *must* tell it to send on the correct interface (eth0.1 in my case), and to send to the broadcast address.

**Comment by wrtechnopath** [comment]
Worked using the specific interface

**Comment by hmh** [comment]
I am not sure this should be closed.  Either etherwake needs to be fixed to actually send to all interfaces when that is requested, or the LuCI interface should not show that option when etherwake is the backend...

**Comment by wrtechnopath** [comment]
I agree, etherwake or luci-app-wol has a bug.
