### ISSUE TITLE
Feature request: Display name of file in /etc/config if not parseable

### ISSUE THREAD

**Issue by richb-hanover** [openwrt/luci#3569]
In #3567 I asked about the "uci: Entry not found" message. The problem was that there was an unusual (non-standard) file present in `/etc/config`

Request: I could have solved the problem myself if that error message had included more information, perhaps the file name of the offending file. Thank you.

**Comment by jow-** [comment]
Note that would be a bug report for the OpenWrt base system since the `uci` utility is not maintained in this repository.

**Comment by richb-hanover** [comment]
Thank you - filed: FS#2779
