### ISSUE TITLE
Luci mir3g no WPA2 setting on snapshot

### ISSUE THREAD

**Issue by pulsar1911** [openwrt/luci#3570]
Hello

Device: mir3g with snapshot

I tried snapshot from like a week ago, will try it again soon.
There was no WPA2 setting in WLAN encryption for me in Luci. Only WPA/WEP selectable.
I installed luci, luci relayd and tried different wpad and hostapd packages.

I think tt is only for the mir3g device. Someone else had no problems with another one.

**Comment by jow-** [comment]
Unable to reproduce it on a Mir 3G. Also WPA and WPA2 have the same dependencies so I don't see how you could get only WPA but not WPA2.
