### ISSUE TITLE
samba36-server

### ISSUE THREAD

**Issue by VladyV** [openwrt/luci#3579]
Executing package manager
Installing samba36-server (3.6.25-14) to root...
Downloading http://downloads.openwrt.org/releases/19.07.0/packages/mips_mips32/base/samba36-server_3.6.25-14_mips_mips32.ipk
Errors
Collected errors:
 * opkg_install_pkg: Package size mismatch: samba36-server is 888515 bytes, expecting 892848 bytes
 * opkg_install_cmd: Cannot install package samba36-server.
The opkg install command failed with code 255.

**Comment by jow-** [comment]
You probable need an `opkg update`. Not a LuCI bug.
