### ISSUE TITLE
Different default controller instead of admin?

### ISSUE THREAD

**Issue by zokl** [openwrt/luci#3581]
Is there any way how to use a different default controller instead of admin?

A few months ago we used the same way as is in luci-admin-mini but today, it does not work. Today we use sources from the master branch.

**Comment by jow-** [comment]
Register your alternative controller with a priority < 10 to make it the default before admin.

Example for a global `/test` route which takes precedence over `/admin`:

```
root@OpenWrt:~# cat /usr/lib/lua/luci/controller/test.lua 
module("luci.controller.test", package.seeall)

function index()
	entry({"test"}, view("test"), _("Test"), 1)
end
```

**Comment by votavon1** [comment]
Thanks. Works like a charm.
