### ISSUE TITLE
luci-mod-system: ZRam settings dopdown has dublicated values

### ISSUE THREAD

**Issue by stonerl** [openwrt/luci#3583]
The ZRam settings have a dropdown for the compression algorithm which is prefilled with `lzo`. The problem is that `lzo`is also available as a possible value.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/2091312/73300597-8fa42d00-4211-11ea-89fb-af990ce885b5.png">

This makes it confusing because it is not obvious that the first value is only a placeholder. That also does not disappear when a proper value is selected.

https://github.com/openwrt/luci/blob/6d59a6400ed055d71e0b335679d291c22bbdbd40/modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js#L190

**Comment by feckert** [comment]
Could you please rename this line to `o.default = 'lzo';`?
Maybe this will fix your issue. If so could you pleas report this back so we could fix this in the master branch.

**Comment by stonerl** [comment]
Thank you for the quick fix.
