### ISSUE TITLE
WPS box/option missing in Luci (19.07.0)

### ISSUE THREAD

**Issue by CaboBeach** [openwrt/luci#3584]
Doubt very many use this, so not very important, but i noticed after installing wpad full and hostapd-utils that the WPS box/option was missing in Network>Wireless>Wireless Security in 19.07.0, looked in other sections but couldn't find it anywhere.

![Screenshot from 2020-01-28 14-35-43](https://user-images.githubusercontent.com/48701904/73303480-340b7c80-41dc-11ea-80d3-e4a8a6021339.png)

**Comment by castillofrancodamian** [comment]
Did you try restarting the router?

**Comment by CaboBeach** [comment]
Yes, but now that i think about it i haven't tried resetting or reflashing, so i'll give that a try in the next couple of days.

**Comment by jow-** [comment]
You need to close and reopen your browser tab after installing these packages.

**Comment by CaboBeach** [comment]
Just wanted to mention that the wps box/option is there in 19.07.1.
