### ISSUE TITLE
daemon.err nginx,daemon.err uwsgi

### ISSUE THREAD

**Issue by snakwu** [openwrt/luci#3602]
Wed Feb  5 00:25:58 2020 daemon.err uwsgi[2552]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-cgi_io.ini
Wed Feb  5 00:25:58 2020 daemon.err uwsgi[2552]: Wed Feb  5 00:25:58 2020 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini has been spawned
Wed Feb  5 00:25:58 2020 daemon.err uwsgi[2552]: Wed Feb  5 00:25:58 2020 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is ready to accept requests
Wed Feb  5 00:25:58 2020 daemon.err uwsgi[2552]: Wed Feb  5 00:25:58 2020 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is now loyal
Wed Feb  5 00:26:00 2020 daemon.err nginx[2600]: 2020/02/05 00:26:00 [error] 7339#0: *47 open() "/www/luci-static/resources/protocol/relay.js" failed (2: No such file or directory), client: 192.168.88.5, server: _lan, request: "GET /luci-static/resources/protocol/relay.js?v=git-19.292.31773-cc35206 HTTP/1.1", host: "192.168.88.1", referrer: "http://192.168.88.1/cgi-bin/luci/admin/status/overview"
Wed Feb  5 00:32:00 2020 daemon.err uwsgi[2552]: Wed Feb  5 00:32:00 2020 - [emperor] bringing back instance /etc/uwsgi/vassals/luci-cgi_io.ini to on-demand mode
Wed Feb  5 00:32:00 2020 daemon.err uwsgi[2552]: Wed Feb  5 00:32:00 2020 - [emperor] curse the uwsgi instance /etc/uwsgi/vassals/luci-cgi_io.ini (pid: 20801)
Wed Feb  5 00:32:02 2020 daemon.err uwsgi[2552]: [uwsgi-emperor] /etc/uwsgi/vassals/luci-cgi_io.ini -> back to "on demand" mode, waiting for connections on socket "/var/run//luci-cgi_io.socket" ...
Wed Feb  5 00:32:03 2020 daemon.err uwsgi[2552]: Wed Feb  5 00:32:03 2020 - [emperor] bringing back instance /etc/uwsgi/vassals/luci-webui.ini to on-demand mode
Wed Feb  5 00:32:03 2020 daemon.err uwsgi[2552]: Wed Feb  5 00:32:03 2020 - [emperor] curse the uwsgi instance /etc/uwsgi/vassals/luci-webui.ini (pid: 19678)
Wed Feb  5 00:32:05 2020 daemon.err uwsgi[2552]: [uwsgi-emperor] /etc/uwsgi/vassals/luci-webui.ini -> back to "on demand" mode, waiting for connections on socket "/var/run//luci-webui.socket" ...
Wed Feb  5 00:32:21 2020 daemon.err nginx[2600]: 2020/02/05 00:32:21 [error] 7339#0: *54 open() "/www/favicon.ico" failed (2: No such file or directory), client: 192.168.88.5, server: _lan, request: "GET /favicon.ico HTTP/1.1", host: "192.168.88.1"
Wed Feb  5 00:36:15 2020 daemon.err nginx[2600]: 2020/02/05 00:36:15 [error] 7339#0: *61 open() "/www/luci-static/resources/protocol/relay.js" failed (2: No such file or directory), client: 192.168.88.5, server: _lan, request: "GET /luci-static/resources/protocol/relay.js?v=git-19.292.31773-cc35206 HTTP/1.1", host: "192.168.88.1", referrer: "http://192.168.88.1/cgi-bin/luci/admin/status/overview"
Wed Feb  5 00:37:02 2020 daemon.err nginx[2600]: 2020/02/05 00:37:02 [error] 7339#0: *73 open() "/www/luci-static/resources/protocol/relay.js" failed (2: No such file or directory), client: 192.168.88.5, server: _lan, request: "GET /luci-static/resources/protocol/relay.js?v=git-19.292.31773-cc35206 HTTP/1.1", host: "192.168.88.1", referrer: "http://192.168.88.1/cgi-bin/luci/admin/system/admin/dropbear"
Wed Feb  5 00:37:12 2020 daemon.err nginx[2600]: 2020/02/05 00:37:12 [error] 7339#0: *61 open() "/www/luci-static/resources/protocol/relay.js" failed (2: No such file or directory), client: 192.168.88.5, server: _lan, request: "GET /luci-static/resources/protocol/relay.js?v=git-19.292.31773-cc35206 HTTP/1.1", host: "192.168.88.1", referrer: "http://192.168.88.1/cgi-bin/luci/admin/services/wol"

**Comment by jow-** [comment]
Not LuCI related, the uwsgi stuff is maintained in the packages repository.
