### ISSUE TITLE
Xiaomi router 3g Openwrt V19 problem. Upload very low.

### ISSUE THREAD

**Issue by roberdlv** [openwrt/luci#3605]
Hello, I have xiaomi router 3g, I installed OpenWrt v18 and everything perfect, perfect speed, perfect management (although improvable) etc ...

The problem comes when upgrading to v19 and v19.0.1, the router's upload speed low by half (wired 600mbs v18) v19 300mbs upload speed .... it looks like a bug and it happens to many people , is there any solution to this? Is it possible to improve the router driver and improve the upload and full management of v19? thanks.

**Comment by feckert** [comment]
I would say this is not LuCI related please open a Ticket in https://bugs.openwrt.org/

**Comment by dangowrt** [comment]
For WiFi related issues on that specific device http://github.com/openwrt/mt76 would be the place to go.
