### ISSUE TITLE
Why "Services" and not "Applications"?

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3610]
There is no problem, but it catches my attention. It used to be **Applications**.

**Comment by castillofrancodamian** [comment]
And the applications (or services) are called **luci-app-x**.

**Comment by feckert** [comment]
Can you please explain in more detail what exactly the problem is? I can't make heads or tails of what you're saying.

**Comment by castillofrancodamian** [comment]
There is no problem, but in the LuCI web interface, there used to be "Applications" instead of "Services". I think I remember that this was before modifying luci-app-ddns, since I see that when changing the translation from "Services" to "Applications" but in another language, it is also changed in app ddns.
