### ISSUE TITLE
luci-app-dns  Can not choose URL method to get IP - invalid CGI response !!!

### ISSUE THREAD

**Issue by jsalatiel** [openwrt/luci#3613]
OpenWrt 19.0.1
ddns-scripts - 2.7.8-12
ddns-scripts_no-ip_com - 2.7.8-12
luci-app-ddns - 2.4.9-7

luci-app-ddns Change IP address source to URL on advanced settings will never apply/save. 
Steps to reproduce

    Services > Dynamic DNS
    Choose any instance
    Open Advanced Settings
    Field Ip address source [IPv4] = URL
    Press Save & Apply

![image](https://user-images.githubusercontent.com/5522389/74069498-24124a80-49dd-11ea-9a2e-002e5e1412b2.png)
The process will timeout and never save.
In log i can see:
`Fri Feb  7 19:08:58 2020 daemon.info uwsgi: invalid CGI response !!!`

**Comment by jow-** [comment]
Please retry with uhttpd instead of nginx/uwsgi.

**Comment by jow-** [comment]
Timeout.

**Comment by jsalatiel** [comment]
Sorry  @jow-  i missed the reply notifications. Yes, it works with uhttpd. is this a nginx/uxsgi bug? can it be fixed ? Thanks!

**Comment by regulskimichal** [comment]
Does anyone know how to fix this issue? Alternative DDNS configuration?
