### ISSUE TITLE
Please extend the rollback time from 30 seconds to 5 minutes

### ISSUE THREAD

**Issue by mailinglists35** [openwrt/luci#3628]
I just wasted half an hour of my life with this stupid "feature": https://forum.openwrt.org/t/disabling-auto-rollback/16315

30 seconds is simply not enough when you need to change network configuration. We are humans, not speedy robots.

And the apply unckecked button never appeared, anyway!

**Comment by castillofrancodamian** [comment]
That button is at 19.07 and master. If using an earlier version, change the `option rollback line '30'` to `option rollback '300'` in `/etc/config/luci`.

**Comment by mailinglists35** [comment]
anyway the whole concept is totally wrong, until you extend by default the time to much more than 30 seconds, more new people will waste time because of this.

"apply unchecked" is also not easy to discover.

**Comment by jow-** [comment]
Master and 19.07.1 offer an option to apply unchecked right away.

**Comment by castillofrancodamian** [comment]
Wouldn't it be better to implement in LuCI?
