### ISSUE TITLE
/usr/lib/lua/luci/dispatcher.lua:388: /etc/config/luci seems to be corrupt, unable to find section 'main'

### ISSUE THREAD

**Issue by jorti** [openwrt/luci#3637]
After leaving open for some time Status -> Realtime graphs -> Connections, this message appears:

~~~
/usr/lib/lua/luci/dispatcher.lua:388: /etc/config/luci seems to be corrupt, unable to find section 'main'
~~~

Nothing works until I restart the rpcd service.

OpenWrt SNAPSHOT r12237-d2b8ccb1c0
LuCI Master git-20.047.38617-2fa9885

**Comment by jow-** [comment]
Seems rpcd is crashing. Maybe you run out of memory, nothing we can fix on the LuCI side.
