### ISSUE TITLE
luci-app-snmpd is missing dependency for snmpd

### ISSUE THREAD

**Issue by kbabioch** [openwrt/luci#3640]
`luci-app-snmpd` is not depending on `snmpd` itself. This leads to `luci-app-snmpd` being installed, but the underlying `snmpd` not being available.

https://github.com/openwrt/luci/blob/5de9cd98b01887a1d064d53d8b787fe3fe65af0a/applications/luci-app-snmpd/Makefile#L4

**Comment by kbabioch** [comment]
Addressed by #3641

**Comment by feckert** [comment]
was merged
