### ISSUE TITLE
Header topmenu shown logged out

### ISSUE THREAD

**Issue by johnnytolengo** [openwrt/luci#3653]
On commit r11655-a283b1788a the topmenu "<header>" is shown while no user logged in.

![image](https://user-images.githubusercontent.com/5218298/74883188-b2d57e80-5370-11ea-9e09-ef416931fdb6.png)

Any idea how to solve this issue?
Thank you.

**Comment by jow-** [comment]
This is intentional.

**Comment by castillofrancodamian** [comment]
But it reveals device information. It should be removed or at least able to deactivate

**Comment by feckert** [comment]
If I use the luci-theme-material i do not see the menu if i am not logged in!

**Comment by jow-** [comment]
> But it reveals device information. It should be removed or at least able to deactivate

So does a `curl -v http://192.168.1.1/luci-static/resources/`. With the client side implementation it is not possible to hide what is available anymore, you can simply probe the URLs.

**Comment by johnnytolengo** [comment]
I think it is not good to show that sensible information, the menu reveals what kind packages you have already installed and so on.

**Comment by jow-** [comment]
Even if the menu is hidden you can still obtain that information easily, it provides zero security benefit.

**Comment by johnnytolengo** [comment]
that is true, but I don't undestand what is the benefit/reason to show the menu while you are logged out.

**Comment by jow-** [comment]
See #3563
