### ISSUE TITLE
network interface not deleted

### ISSUE THREAD

**Issue by mailyspamy** [openwrt/luci#3660]
If I delete wireless connection under "Network->Wireless" and want connect to a new one. Why I have to go to "Network->Interface" and delete the interface first. Than "save & apply". And after that I can connect to a new wireless network?

**Comment by jow-** [comment]
Because logical interfaces and wireless networks are different entities in the OpenWrt configuration. Besides that, I don't know what you mean. I can simply delete and recreate wifi interfaces without issues here.

**Comment by mailyspamy** [comment]
I click on remove, than scan, i select new ssid and join network, but "Name of the new network" is "wwan2" and not "wwan". thats why i have to go to interfaces and delete the old wwan first.

**Comment by jow-** [comment]
Ok, I understand. You can simply delete the `2` and reuse the empty `wwan` definition. Will change the logic to automatically reuse empty logical networks.

**Comment by mailyspamy** [comment]
![image](https://user-images.githubusercontent.com/25592998/75070608-e260c400-54f3-11ea-8fb6-89852b9082f8.png)
see picture. it is not possible

**Comment by jow-** [comment]
Yep, noticed that too in my testing. After the linked commit, LuCI will automatically reuse leftover empty wwan interface. I decided against auto-deleting associated interfaces because it might be too dangerous with certain configurations as it would also delete related alias interfaces, routes etc.
