### ISSUE TITLE
BSSID missing

### ISSUE THREAD

**Issue by mailyspamy** [openwrt/luci#3661]
If I select a new network to connect, why is BSSID field empty and I have to manually write it?

**Comment by jow-** [comment]
An option to use BSSID has been added. The rationale for not copying the BSSID is that many public networks are composed of multiple access points sharing the same SSID. Locking to a specific BSSID would break client roaming on such networks.

**Comment by mailyspamy** [comment]
i understand but in that case is possible to manualy delete the bssid, which is less work than search the bssid and write it manually. for example i use public networks in the oposite way. i want to connect to one bssid only. i hope that your option will be a sollution to my problem. thank you
