### ISSUE TITLE
autorefresh

### ISSUE THREAD

**Issue by mailyspamy** [openwrt/luci#3662]
If I scan and search new network, why is it repeatedly refreshing? Because of issue#3661 I have to manually select the BSSID and copy it. But it is almost impossible because of the refresh rate. Can the refresh be disabled?

**Comment by jow-** [comment]
The refresh is required because some radios, especially 5 GHz ones require many scan cycles to discover all neighboring networks.

**Comment by mailyspamy** [comment]
and is it possible to let me decide when i want to refresh the site?

**Comment by jow-** [comment]
Since the linked commit yes.

**Comment by mailyspamy** [comment]
great thank you. i did not see before posting.

**Comment by mailyspamy** [comment]
after pressing "stop refresh" it refreshes once more time and than stops. its like the button stops scheduling refresh, but the last scheduled refresh happens.
