### ISSUE TITLE
wrong encryption

### ISSUE THREAD

**Issue by mailyspamy** [openwrt/luci#3663]
Why is not the encryption overtaken? If I connect to not protected network, than the selected default encryption is "WPA2-PSK" and not "No Encryption".

**Comment by jow-** [comment]
Because `option encryption` is not set in this case and the config form defaulted to WPA2-PSK.

**Comment by mailyspamy** [comment]
why? on previous builds was the encryption overtaken.

**Comment by jow-** [comment]
Because the code has been reworked to support SAE/WPA3 etc. and the "not encrypted" clause was forgotten. The linked commit fixes this.

**Comment by mailyspamy** [comment]
ok so in the next release it will be fixed. thanks
