### ISSUE TITLE
Realtime graphs inbound/outbound swapped

### ISSUE THREAD

**Issue by adiastra** [openwrt/luci#3667]
In the realtime graph for "Traffic" Inbound and Outbound are swapped. not the colors, just the words below the graph.

**Comment by jow-** [comment]
Inbound/outbound figures are relative to the interface being displayed. For the wan interface, "inbound" is "traffic downloaded from the internet", for the lan interface, "inbound" means "traffic uploaded to the internet".

I double checked here and when downloading large files, the "inbound" increases on "wan" and "outbound" increases on "lan", so no swapped here.
