### ISSUE TITLE
19.07.1 - OPKG Configuration isn't loading

### ISSUE THREAD

**Issue by fedor1991** [openwrt/luci#3668]
Go to `System` - `Software`, click on `Configure opkg…` button. 

![image](https://user-images.githubusercontent.com/9825558/75090778-01506c00-556f-11ea-8107-284d38b166ed.png)

`Powered by LuCI openwrt-19.07 branch (git-20.052.76937-657407f) / OpenWrt 19.07.1 r10911-c155900f66`

**Comment by jow-** [comment]
What is the output of `ls -lh /etc/opkg.conf /etc/opkg/` ?

**Comment by fedor1991** [comment]
This 19.07 version was upgraded from latest 18.x with keep settings checkbox. 
But now I made a factory reset and everything is fine, sorry
