### ISSUE TITLE
luci-mod-network: Does not display accurate wireless status

### ISSUE THREAD

**Issue by aaegitt** [openwrt/luci#3670]
When multiple SSIDs are configured on a radio, only the first enabled SSID has the correct information displayed in the Wireless Overview and Associated Station sections.  All other SSIDs show "Wireless is not associated" regardless if any stations are connected.  Using iwinfo  assoclist will show connected stations, but these do not appear in the Associated Station list.

I found others have mentioned this problem in the Openwrt forum:
 https://forum.openwrt.org/t/davidc502-wrt1200ac-wrt1900acx-wrt3200acm-wrt32x-builds/15839

This behavior was not seen in my previous build from 4 months ago.  I am now running:
LuCI Master (git-20.052.76652-4322cae) / OpenWrt SNAPSHOT r12261-d1130ad265

**Comment by jow-** [comment]
Please first test whether the problem persists after

```
make package/rpcd-mod-iwinfo/clean
make package/rpcd-mod-luci/clean
make package/iwinfo/clean
```

**Comment by aaegitt** [comment]
I executed the above as requested with the following modification:

make package/rpcd-mod-iwinfo/clean  - resulted in Error 2
changed to:
make package/rpcd/clean - completed without error

The new build has the same problem with inaccurate info.  I also tried a make dirclean with the same result.  Let me know if you have anymore suggestions.

**Comment by jow-** [comment]
Unfortunately I cannot reproduce the issue locally. Please provide the complete output of `ubus call luci-rpc getWirelessDevices`

**Comment by aaegitt** [comment]
As requested.

[ubus output.txt](https://github.com/openwrt/luci/files/4246352/ubus.output.txt)

**Comment by jow-** [comment]
Please provide the output of `ubus call network.wireless status` as well

**Comment by aaegitt** [comment]
As requested.

[ubus wireless output.txt](https://github.com/openwrt/luci/files/4255874/ubus.wireless.output.txt)

**Comment by jow-** [comment]
The problem seems related to `netifd`. It does not report the ifnames for the second and third VAP, that's why LuCI cannot correlate the iwinfo runtime data to it.

**Comment by kofec** [comment]
I also see this issue XIAOMI MINI hardware for 5G interface(MT76) 
for 2,4GHz it is OK(rt2x00)

**Comment by jow-** [comment]
Seems like a regression in OpenWrt master.

**Comment by aaegitt** [comment]
Problem was resolved by resetting config back to default then manually re-entering information.
