### ISSUE TITLE
19.07.0 and 19.07.1 alaway show"Loading package information…",can not show package list properly

### ISSUE THREAD

**Issue by be-engineer** [openwrt/luci#3671]
My device is tp-link wdr7500(solder 16MB flash). Each time I open the software list does not display properly,click on the Update lists situations remain.
![image](https://user-images.githubusercontent.com/16242748/75103177-4689a200-5632-11ea-846b-17243311af17.png)

**Comment by be-engineer** [comment]
it's my config fault.closed!

**Comment by be-engineer** [comment]
it's my config fault.closed!

**Comment by bordeux** [comment]
@be-engineer what was the problem exactly? Also im affected  with this problem in fresh installation

**Comment by leleb** [comment]
![image](https://user-images.githubusercontent.com/1241802/111880979-af1a8e00-89ae-11eb-9c2c-45ed607f2e31.png)

me too, fresh install in a esxi x86 vm. After "update lists" it is stuck with "loading package information"

**Comment by bordeux** [comment]
Right now i know, it is not backend issue, but Frontend issue :)

![image](https://user-images.githubusercontent.com/784536/111881675-ed657c80-89b1-11eb-86ba-390bcf2c5f4a.png)

**Comment by leleb** [comment]
updated to 19.07.7 now working
