### ISSUE TITLE
One-click wireless mac address filtering

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/luci#3675]
It would be a useful addition, IMHO, to be able to "one click" block MAC addresses from WiFi radios.  Probably a button next to the _Disconnect_ button in the Associated Stations list to add a MAC address to the filter for that radio could be useful.

Or perhaps the existing _Disconnect_ can be a multifunction button, with a drop-down menu arrow on it with an additional _Disconnect and Block_ and/or _Block_ action added to it.

**Comment by ahmadshkt** [comment]
As we are in mesh world, we have certain APs of different brands to get more area coverage. 

Would there be a possibility to have a block/deny/disable button next to leased dhcp address so we can just disable the mac not to be entitled of any ip?
