### ISSUE TITLE
Status Overview free memory

### ISSUE THREAD

**Issue by bjlockie** [openwrt/luci#3682]
The used memory is the white area?

![image](https://user-images.githubusercontent.com/303873/75316133-7acbb100-5832-11ea-8340-ba5f2208fee8.png)

I think it is backwards, the blue should be how much memory is in use.
"Free" should say "Free/In Use" and then have the blue bar be a gauge. :slight_smile:
I don't see a need for "Total Available", one bar can do the job of both.

**Comment by feckert** [comment]
Feel free to open a pullrequest for this change

**Comment by bjlockie** [comment]
Does a pull request mean I change it and then submit it?
How do I test the changes on anything other than my router?

**Comment by feckert** [comment]
> Does a pull request mean I change it and then submit it?

Yes

> Does a pull request mean I change it and then submit it? How do I test the changes on anything other than my router?

Thats the way to go or you could also build a vmdk for virtualbox
