### ISSUE TITLE
RFC: buildinfo in luci-base

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#3690]
Hi, to help supporting users it could be beneficial to know as exactly as possible what they're running. For this the buildinfo files (version, package feeds + hash, build config) could be helpful. With the recent commit https://github.com/openwrt/openwrt/pull/2766 these files are partly available.

Could it make sense to extend the *System* tab to show these files so users can simply copy & paste them for bug reports?

**Comment by jow-** [comment]
I'm not sure about the benefits. The version is enough to see if an image is official, in this case we know its configuration. If the image is custom, one could expect users to be able to run `./scripts/diffconfig.sh` in their buildroot. If the image is custom from an unknown source, the buildinfo files will not help as they do not describe modifications made to the source code.
