### ISSUE TITLE
luci-app-wireguard: ignores parameters if >1 Peers

### ISSUE THREAD

**Issue by 0uro** [openwrt/luci#3692]
Hardware : mtc wr1201 (Strong 1200)
Software : 19.07.1 (up-to-date)
Peer 1 : android client - pubkey begins with MRXOS
Peer 2 : linux client - pubkey begins with zy8fd

Before adding peer 2, peer 1 connects fine.

After adding peer 2:
- peer 2 connects fine
- peer 1 still connects but with no network access at all.

wg connect result (public keys had been shortened of course) : 
```
interface: wg0
  public key: JYe8c[...]=
  private key: (hidden)
  listening port: 51820

peer: MRXOS[...]=
  allowed ips: (none)

peer: zy8fd[...]=
  allowed ips: 18.19.0.0/16
  persistent keepalive: every 25 seconds
```

Although I filled the field "Allowed ips" in the gui it isn't applied

**Comment by dibdot** [comment]
works for me. This is most probably a configuration issue, please ask in the forum.
