### ISSUE TITLE
luci-proto-openconnect created wrong file

### ISSUE THREAD

**Issue by 9yw** [openwrt/luci#3702]
When set interface using openconnect in luci, it create 3 files in /etc/openconnect/, but with wrong filename(The interface called "sz"):
![image](https://user-images.githubusercontent.com/25059561/75621351-f54b5680-5bcd-11ea-8214-00261ce773d6.png)
"openconnect: executing" command didn't get key:
![image](https://user-images.githubusercontent.com/25059561/75621406-d1d4db80-5bce-11ea-8ea2-f13a563ddf0c.png)
After link file with -vpn added in name(which older version has -vpn in filename):
![image](https://user-images.githubusercontent.com/25059561/75621452-70613c80-5bcf-11ea-8c3b-32ad03f26b8a.png)
The command got keys: 
![image](https://user-images.githubusercontent.com/25059561/75621568-05b10080-5bd1-11ea-9df2-61de3f1885e4.png)

**Comment by jow-** [comment]
Fixed by adf0fb1879ffb6bd04984d257484fad0fba1d6a3
