### ISSUE TITLE
luci-app-statistic exec plugin

### ISSUE THREAD

**Issue by avengermsoft** [openwrt/luci#3719]
Luci version - OpenWrt SNAPSHOT r12230-5715b21f80 / LuCI Master git-20.062.71982-95804e5

How to describe exec plugin now?

Previously like this:
luci/statistics/rrdtool/definitions/exec.lua
<pre>
module("luci.statistics.rrdtool.definitions.exec", package.seeall)

function item()
	return luci.i18n.translate("Exec")
end

function rrdargs( graph, plugin, plugin_instance, dtype )
	if "speedtest" == plugin_instance then
		return {
			title = "%H: Internet Speed to P.A.K.T. LLC (speedtest.net)",
			vlabel = "Mbit/sec",
			number_format = "%5.3lf",
			autoscale_max = true,
			data = {
				types = { "speedtest" },
				sources = { speedtest = { "ping", "download", "upload" } },
				options = {
					speedtest__download = { color = "00ff00", title = "Download", overlay = true, noarea = false, total = false }, -- green
					speedtest__upload = { color = "0000ff", title = "Upload", overlay = true, noarea = false, total = false, flip  = true }, -- blue
					speedtest__ping = { color = "ff0000", title = "Ping (ms)", overlay = true, noarea = true, total = false } -- red
				}
			}
		}
	end
end
</pre>

**Comment by jow-** [comment]
### /www/luci-static/resources/statistics/rrdtool/definitions/exec.js

```
'use strict';
'require uci';

return L.Class.extend({
	title: _('Exec'),

	rrdargs: function(graph, host, plugin, plugin_instance, dtype) {
		if (plugin_instance == 'speedtest') {
			return {
				title: "%H: Internet Speed to P.A.K.T. LLC (speedtest.net)",
				vlabel: "Mbit/sec",
				number_format: "%5.3lf",
				autoscale_max: true,
				data: {
					types: [ "speedtest" ],
					sources: { speedtest: [ "ping", "download", "upload" ] },
					options: {
						speedtest__download: { color: "00ff00", title: "Download", overlay: true, noarea: false, total: false }, // green
						speedtest__upload: { color: "0000ff", title: "Upload", overlay: true, noarea: false, total: false, flip : true }, // blue
						speedtest__ping: { color: "ff0000", title: "Ping (ms)", overlay: true, noarea: true, total: false } // red
					}
				}
			};			
		}
	}
});
```
