### ISSUE TITLE
SWAP section in System -> Mount Points not showing properly

### ISSUE THREAD

**Issue by aidvu** [openwrt/luci#372]
SWAP section throws errors.

**Comment by aidvu** [comment]
Fix for the issue. https://github.com/openwrt/luci/pull/371

**Comment by aidvu** [comment]
Screenshot
![openwrt-swap-error](https://cloud.githubusercontent.com/assets/1103398/7335003/8315f172-eba4-11e4-8b5d-f7cadbc80c3c.PNG)

**Comment by jow-** [comment]
Closed with 2243a3f - thanks a lot.
