### ISSUE TITLE
Luci topic list overflows

### ISSUE THREAD

**Issue by qiuzi** [openwrt/luci#3725]
![image](https://user-images.githubusercontent.com/1689784/76041705-ccd8a900-5f8d-11ea-8303-a3702cd8a4a9.png)

**Comment by jow-** [comment]
Sorry, not enough context to work with. Where does it appear and most importantly, can you reproduce it using the default bootstrap theme?

**Comment by qiuzi** [comment]
It will be worse if there is longer content
![image](https://user-images.githubusercontent.com/1689784/76086398-fb3aa080-5fee-11ea-8e38-379132040898.png)

**Comment by jow-** [comment]
Okay, not affecting bootstrap. So yet another material theme bug.
