### ISSUE TITLE
"webadmin.lua file is already provided by package *luci-base"

### ISSUE THREAD

**Issue by intdev32** [openwrt/luci#3726]
I just Installed(Fresh) OpenWrt 19.07.2.

opkg update && opkg install luci-app-ddns (or anything start with luci-app-).

----------------
Collected errors:
 * check_data_file_clashes: Package luci-compat wants to install file /usr/lib/lua/luci/tools/webadmin.lua
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package luci-app-ddns.
---------------

I temporary resolved this issue. Using --force-overwrite option to opkg, problem solved.

**Comment by jow-** [comment]
opkg upgrade luci-base
