### ISSUE TITLE
cannot install luci-app-statistics on 19.07.2

### ISSUE THREAD

**Issue by thatso** [openwrt/luci#3727]
I've just updated to 19.07.2, did opkg update and got this error trying to install luci-app-statistics:

Installing luci-app-statistics (git-20.064.69776-e8c638c-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.2/packages/mips_24kc/luci/luci-app-statistics_git-20.064.69776-e8c638c-1_all.ipk
Installing luci-compat (git-20.064.69776-e8c638c-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.2/packages/mips_24kc/luci/luci-compat_git-20.064.69776-e8c638c-1_all.ipk
Collected errors:
 * check_data_file_clashes: Package luci-compat wants to install file /usr/lib/lua/luci/tools/webadmin.lua
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package luci-app-statistics.

**Comment by jow-** [comment]
#3726
