### ISSUE TITLE
luci-app-mosquitto: rpcd/cgi-io version compatibility

### ISSUE THREAD

**Issue by zyphlar** [openwrt/luci#3730]
I'm unable to install luci-app-mosquitto version: git-20.064.69776-e8c638c-1 because I get this error:

    The installed version of package rpcd is not compatible, require > = 2019-12-10 while 2019-12-10-aaa08366-2 is installed.
    The installed version of package cgi-io is not compatible, require > = 19 while 19 is installed.

Correct me if I'm wrong, but 19 should >= 19, and 2019-12-10-aaa08366-2 should probably >= 2019-12-10. So I'm not sure if there's a version numbering logic issue or what.

**Comment by jow-** [comment]
https://github.com/openwrt/luci/commit/cf18bdde36c40f672415e3b9efb52de005b250bd
