### ISSUE TITLE
Can't upgrade luci-base, rpcd & cgi-io incompatible

### ISSUE THREAD

**Issue by maxedout** [openwrt/luci#3731]
Hello all,

I was just running my updates and getting this error where i can't upgrade luci-base because of 'incompatibilities".

`The installed version of package rpcd is not compatible, require > = 2019-12-10 while 2019-12-10-aaa08366-2 is installed.
The installed version of package cgi-io is not compatible, require > = 19 while 19 is installed.`

Running this on a Linksys WRT32X, OpenWRT v19.07.02

**Comment by jow-** [comment]
https://github.com/openwrt/luci/commit/cf18bdde36c40f672415e3b9efb52de005b250bd
