### ISSUE TITLE
Enhancement:  status/overview/wireless associated stations

### ISSUE THREAD

**Issue by cavanaug** [openwrt/luci#3734]
It would be really nice if the associated stations list would show more than just the IP address for the host.   With ipv6 addresses its sort of hopeless to look at it and ascertain what host it is.

Would it be possible to perform a reverse dns lookup on the ip and include the hostname as well in the status page?   It would help readability significantly...

**Comment by howard0su** [comment]
It is there (19.07). It shows the hostname name with ipv4 and ipv6 address.

**Comment by jow-** [comment]
Same for me.

**Comment by cavanaug** [comment]
I believe the defect may only exhibit itself when using openwrt in AP mode.   I use OpenWrt in AP mode for 3 APs and it never shows the hostname.   It will occasionally show the IP address.   See below

![image](https://user-images.githubusercontent.com/59479/76444916-e27d1280-6381-11ea-9b32-4fb0517cd7b3.png)

**Comment by jow-** [comment]
That information simply isn't available in pure AP mode. Since traffic is bridged, no ARP / IPv6 neighbor discovery ever happens.

**Comment by cavanaug** [comment]
In cases where the IP address is available how is the hostname determined?
  I can do a reverse dns lookup and it gives the name.
