### ISSUE TITLE
Unable to open Diagnostics page

### ISSUE THREAD

**Issue by kudlav** [openwrt/luci#3736]
> Failed to execute template dispatcher target for entry '/admin/network/diagnostics'. The called action terminated with an exception: /usr/lib/lua/luci/template.lua:74: Failed to load template 'admin_network/diagnostics'. Error while parsing template '/usr/lib/lua/luci/view/admin_network/diagnostics.htm': No such file or directory stack traceback: 	[C]: in function 'error' 	/usr/lib/lua/luci/template.lua:74: in function '__init__' 	/usr/lib/lua/luci/util.lua:65: in function 'Template' 	/usr/lib/lua/luci/template.lua:27: in function 'render' 	/usr/lib/lua/luci/dispatcher.lua:920: in function </usr/lib/lua/luci/dispatcher.lua:919>

Model: TP-Link TL-WR1043N/ND v1
Architecture: Atheros AR9132 rev 2
Firmware Version: OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-20.067.35699-cf18bdd
Kernel Version: 4.14.171

**Comment by jow-** [comment]
`rm -f /tmp/luci-indexcache` or reboot.

**Comment by db260179** [comment]
And rm -rf /tmp/luci-modulecache
is required

**Comment by kudlav** [comment]
Reboot solved the problem for me, but it's inconvenience to see the failure.
