### ISSUE TITLE
Error canceling load quickly

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3740]
It appears throughout the LuCI interface when I do I do that action. I have snapshots.

![Sin título](https://user-images.githubusercontent.com/47670442/76365543-46fa8c00-6306-11ea-8719-3503d2a95603.png)

**Comment by jow-** [comment]
Yes, don't do that then :) If you cancel page loading midway, related XHR requests will be aborted as well, no way to change that.

**Comment by dibdot** [comment]
@jow- May I ask why do we report this "error" to the user at all? The popup comes up for a few seconds and then automatically disappears, cause the user already clicked another top level menu option. Maybe there are other use cases where this error popup makes more sense, I don't know.

Thanks!

**Comment by jow-** [comment]
Good question, I guess we can simply hide this particular case.

**Comment by castillofrancodamian** [comment]
That's the problem.  That appears all in time.  I forgot to clarify.
