### ISSUE TITLE
luci-app-statistics: no graphs displayed w/ collectd-mod-apcups

### ISSUE THREAD

**Issue by aaegitt** [openwrt/luci#3743]
When APC UPS tab is selected, nothing is displayed except "Loading data..."  RRD files are being updated every minute.

OpenWrt SNAPSHOT r12458-6e80df5e33 / LuCI Master git-20.064.70038-6c167ea

**Comment by jow-** [comment]
Can you provide me with an XML export of the apcups RRD files?

**Comment by aaegitt** [comment]
As requested.
[charge.xml.txt](https://github.com/openwrt/luci/files/4333665/charge.xml.txt)
[percent-load.xml.txt](https://github.com/openwrt/luci/files/4333666/percent-load.xml.txt)
[timeleft.xml.txt](https://github.com/openwrt/luci/files/4333667/timeleft.xml.txt)
[voltage-battery.xml.txt](https://github.com/openwrt/luci/files/4333668/voltage-battery.xml.txt)
[voltage-input.xml.txt](https://github.com/openwrt/luci/files/4333669/voltage-input.xml.txt)
