### ISSUE TITLE
chrome open Overview page prompt error “Failed to execute 'open' on 'XMLHttpRequest': Invalid URL”

### ISSUE THREAD

**Issue by tty228** [openwrt/luci#3747]
Model: Phicomm K3
Architecture: ARMv7 Processor rev 0 (v7l)
Firmware Version: OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-20.057.55219-13dd17f    （19.07.2 release）
Kernel Version: 4.14.171
chrome Version: Chromium 78.0.3904.108

![微信图片_20200312111310](https://user-images.githubusercontent.com/33397881/76483627-7d452200-6452-11ea-909e-3e85255e22db.png)

Internet Explorer nor Firefox shows this error.

I tried to troubleshoot. I found the reason why JavaScript asynchronous did not wait for a callback. After adding `alert()` or `settimeout()` to JavaScript code, it can run normally. After using the `window.addeventlistener` method, the number of errors decreased, but it still happens occasionally.

Is there any good way to help me?

Original code:
`<script type="text/javascript">L.require('view.status.index').catch(function(err) {`
`	L.dom.content(document.querySelector('#view'), null);`
`	L.error(err);`
`});</script>`

My current code:
`<script type="text/javascript">`
`function downloadJSAtOnload() {`
`	L.require('view.status.index').catch(function(err) {`
`	L.dom.content(document.querySelector('#view'), null);`
`	L.error(err);`
`});;`
`}`

`function load() {setTimeout(function(){downloadJSAtOnload();},200);}`

`	if (window.addEventListener)`
`		window.addEventListener("load",load, false); `
`	else if (window.attachEvent)`
`		window.attachEvent("onload",load);`
`	else `
`		window.onload = load;`
`</script>`

**Comment by jsravn** [comment]
I also noticed this after updating to 19.07.2 from 19.07.2. Chrome can no longer open these pages.

**Comment by tty228** [comment]
> I also noticed this after updating to 19.07.2 from 19.07.2. Chrome can no longer open these pages.

But I don't understand why this problem is rarely discussed. Is it the specific version of chrome that causes this problem.

cgi-bin/luci/admin/system/system    （system pages）
/cgi-bin/luci/admin/network/dhcp    （dhcp  pages）
sometimes have this problem. I can only add `setTimeout ()`,But it's too slow to open.

**Comment by CanadianJeff** [comment]
why was this closed and moved to a chinese thread??? I still see this bug

**Comment by n3gwg** [comment]
I am using Chrome Version 96.0.4664.55 (Official Build) (x86_64) on macOS Big Sur 11.6.1 and upon opening the main webpage of the router running OpenWRT I am experiencing the same issue.

**Comment by jow-** [comment]
This issue has not been closed, a foreign chinese issue report referencing this one has been closed. This report is still open.

**Comment by n3gwg** [comment]
I see it was the dupes not the actual issue that was closed.

**Comment by n3gwg** [comment]
I see it was the dupes not the actual issue that was closed.
