### ISSUE TITLE
Reporting security bugs on openwrt-19.07

### ISSUE THREAD

**Issue by alisaeed** [openwrt/luci#3757]
Hello, hope you are doing well,

We performed a security scan using acunetix and the results show some security issues.  Please see the attachment.
branch: openwrt-19.07
Vulnerability tool: Acunetix.Web.12.0.181218140.Retail

Best Regards.

[report.pdf](https://github.com/openwrt/luci/files/4334059/report.pdf)

**Comment by alisaeed** [comment]
Thanks a lot @jow- 
But yet, there are a few bugs, after your vulnerabilities fixing.
I attached a new report.

[20200316_Developer_https_192_168_1_100_cgi_bin_luci_.pdf](https://github.com/openwrt/luci/files/4337352/20200316_Developer_https_192_168_1_100_cgi_bin_luci_.pdf)

**Comment by jow-** [comment]
Did you validate the claimed CSRF protection issue with a reliable reproducer? I am not going to fix the low and informational issues.
