### ISSUE TITLE
luci-theme-rosy: Fonts not loaded, 19.07.2

### ISSUE THREAD

**Issue by ngerke** [openwrt/luci#3759]
```
Model	Netgear R6250 V1 (BCM4708)
Architecture	ARMv7 Processor rev 0 (v7l)
Firmware Version	OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-20.067.35699-cf18bdd

luci-theme-rosy	git-20.067.35699-cf18bdd-1	~105.1 KB	Rosy Theme
```

The theme fonts are not loaded:

![Untitled](https://user-images.githubusercontent.com/31704359/76741443-d9b88200-676f-11ea-8f76-17d4f8fbdc02.png)

Tested Browsers:

- Chrome
- Chromium
- Brave
- Safari

**Comment by jow-** [comment]
The theme is marked broken since a while and I'll likely drop it from the tree soon if nobody steps up to maintain it.

**Comment by ngerke** [comment]
Oh thats to bad, I'm new to OpenWRT where would I've found the 'broken pkg' notice?

**Comment by jow-** [comment]
The flag wasn't applied to the OpenWrt 19.07 release, I did that now so the package won't be built anymore with the next release.

**Comment by ysc3839** [comment]
Ping @rosysong

**Comment by HashedBrown** [comment]
bummer. it's a nice look and feel. Just the font is too huge.

**Comment by hnyman** [comment]
The broken theme has been removed.
