### ISSUE TITLE
luci-app-banip: Unable to add new rule after deleting last one.

### ISSUE THREAD

**Issue by solevi** [openwrt/luci#3779]
Hello,
After deleting last rule from `country` or `asn` there is no more '+' sign to add new match.
![image](https://user-images.githubusercontent.com/4509531/77302987-9e87f700-6d0b-11ea-9faf-6691411950bf.png)

**Comment by dibdot** [comment]
That's a known issue/limitation of the current lua implementation. It will be fixed whenever I migrate this app to client side JS. Just don't do it for now ...;-)
