### ISSUE TITLE
LuCI dynlist text value overflow when long input value is present

### ISSUE THREAD

**Issue by jamesmacwhite** [openwrt/luci#3795]
A minor visual bug, demonstrated with dnsmasq, when a long value is present in a dynlist, the text can overflow and breakout of the input area.

![image](https://user-images.githubusercontent.com/8067792/77860915-c5619400-7209-11ea-85f9-73760f4c5ac2.png)

A simple fix can be done with CSS targeting the rule `.cbi-dynlist > .item` and applying `overflow: hidden;`, preventing the value in the `<span>` from going outside of the div.

**Comment by jow-** [comment]
Thank your for the suggestion. I added a word wrap in addition to the overflow so that information is not "lost". Looks like this for long strings now:

![image](https://user-images.githubusercontent.com/2528802/78357504-e2071e80-75b1-11ea-90e3-d848c478c663.png)

**Comment by jamesmacwhite** [comment]
@jow- Thanks for looking at this. Good idea, even better with also adding `work-break` , so you can see the whole value in it's entirety!
