### ISSUE TITLE
OpenWrt theme is broken

### ISSUE THREAD

**Issue by YuriPet** [openwrt/luci#3801]
OpenWrt theme is broken in LuCI-20.090.73090-2935b28 and above.
![OpenWrt_Theme](https://user-images.githubusercontent.com/11704993/78016148-1630d400-7353-11ea-9f83-33c41babc45a.png)

**Comment by dibdot** [comment]
Worksforme, OpenWrt SNAPSHOT r12776-437eb41f23 / LuCI Master git-20.091.19624-14c59e0

**Comment by jow-** [comment]
I can reproduce it. It is caused by CSS minification. Investigating it now...
