### ISSUE TITLE
luci-app-ttyd not working with luci-ssl-openssl

### ISSUE THREAD

**Issue by bobafetthotmail** [openwrt/luci#3831]
x86_64 target, compiled from source, master/snapshot
If I go to the ttyd service page, the terminal area in the page does not work and only displays errors.
**On Chrome** "192.168.1.1 sent an invalid response."
**On Firefox** "An error occurred during a connection to 192.168.1.1:7681. SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG"

If I go to http://192.168.1.1:7681/ it's working fine.

**Comment by jow-** [comment]
Looks as if the browser tries to load the HTTP resource as HTTPS.

**Comment by ysc3839** [comment]
Currently it doesn't check if ssl is enabled in ttyd, instead it uses same protocol as luci.
https://github.com/openwrt/luci/blob/e994f8ae31fa3e4143c379ffe4ffa449b949d67a/applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/term.js#L15
I will open a PR to fix this.
