### ISSUE TITLE
luci-app-sqm: bad run_path variable initialization

### ISSUE THREAD

**Issue by dl12345** [openwrt/luci#3860]
On the majority of Openwrt systems, `/var` is a symlink to `/tmp`

However, if the router has a SSD or writeable storage of some form and `/var` is made to be a normal directory in the filesystem instead of a symlink to `/tmp`, the initialization of the run_path variable in sqm-cbi.lua causes breakage of sqm-scripts functionality in the sense thaty only fq_codel is shown as an available qdisc.

run_path is explicitly initialized in sqm-cbi.lua to `/tmp/run/sqm/available_qdiscs` instead of the more correct and portable `/var/run/sqm/available_qdiscs`

```
local wa = require "luci.tools.webadmin"                                             
local fs = require "nixio.fs"                                                    
local net = require "luci.model.network".init()              
local sys = require "luci.sys"                                                                                 
--local ifaces = net:get_interfaces()                          
local ifaces = sys.net:devices()                                  
local path = "/usr/lib/sqm"                                   
local run_path = "/tmp/run/sqm/available_qdiscs"
```

**Comment by hnyman** [comment]
cc @tohojo @moeller0

**Comment by tohojo** [comment]
Yeah, that seems like an odd oversight; let me fix that...
