### ISSUE TITLE
Update all packages in luci

### ISSUE THREAD

**Issue by james-mcguire** [openwrt/luci#3861]
It would be nice to be able to update all packages at once in luci

**Comment by wrtechnopath** [comment]
Would check boxes help?

**Comment by james-mcguire** [comment]
Yes, just about anything would help to make the process go smoother.

Currently, you have to upgrade each package one by one, waiting for the upgrade to complete before moving onto the next package.

**Comment by jow-** [comment]
This is not a recommended practice in OpenWrt. Upgrading all packages introduces a high risk of either bricking the router or filling up all available flash space.

The reason for the current Upgrade functionality to exist is to allow the user to easily install single, important security updates to packages.
