### ISSUE TITLE
Luci web shows menus when user is not logged in

### ISSUE THREAD

**Issue by sanitariu** [openwrt/luci#3862]
Hello,
Luci web shows menus when user is not logged in.
Menus should be visible only if user is logged in.
How to fix this ?

**Comment by hnyman** [comment]
Duplicate of #3653, #3766, #3785, #3837 and original discussion in #3563

**Comment by sanitariu** [comment]
Hi,
This patch is really really bad. You are saying "come wolf eat me" to hackers :)
I know that you can see the menus on other places but i think it is better if the door is not locked but closed instead not closed and widely open ... if you understand what i mean.....
