### ISSUE TITLE
untranslatable strings / grammar constraints

### ISSUE THREAD

**Issue by ce-4** [openwrt/luci#3867]
Hi openwrt devs,

Several strings are build using concatenation following english grammar / word order rules which is incompatible with eg. German word order:

E.g.
`errorTable["errorRestoreCache"] = translate("failed to move") .. " '" .. outputCache .. "' " .. translate("to") .. " '" .. outputFile .. "'"`
Optimal result would look in german like this:
`$FilePathA konnte nicht nach $FilePathB verschoben werden.`

Maybe switch to translating a single string per message and then do placeholder replacement instead of concatenating single parts?

https://github.com/openwrt/luci/blob/master/applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua

Thank you!
Cheers, Chris

**Comment by jow-** [comment]
@stangri - please change the source to translate format string:

`translatef("failed to move '%s' to '%s'", outputCache, outputFile)`

**Comment by ce-4** [comment]
I created https://github.com/openwrt/luci/pull/3875
Please check if all is correct as i only did a syntax check

**Comment by jow-** [comment]
I assume this has been addressed with the various i18n improvements.
