### ISSUE TITLE
luci-app-ddns trunk error

### ISSUE THREAD

**Issue by debiansid** [openwrt/luci#387]
Hints
Software update required
The currently installed 'ddns-scripts' package did not support all available settings.
Please update to the current version!

**Comment by chris5560** [comment]
@debiansid 
Which version of ddns-scripts and luci-app-ddns are you running ?
Which available setting is missing ?
Christian

**Comment by db260179** [comment]
The change of min version in the luci-app-ddns seems to be the cause of this

+DDNS_MIN = "2.4.2-1" -- minimum version of service required

Previously
-DDNS_MIN = "2.2.0-1" -- minimum version of service required
Doesnt show this error

**Comment by debiansid** [comment]
@chris5560 
ddns-scripts - 2.4.2-1 
ddns-scripts_nsupdate - 2.4.2-1 - 
luci-app-ddns - 2.2.2-1

**Comment by chris5560** [comment]
Fixed

**Comment by debiansid** [comment]
2.4.2-1did not fix it here.

**Comment by debiansid** [comment]
luci-app-ddns  2.2.4 I mean

**Comment by debiansid** [comment]
Sorry,reboot openwrt show it correctly finally
