### ISSUE TITLE
Name validation broken in dchp.js

### ISSUE THREAD

**Issue by resadent** [openwrt/luci#3870]
Hi. I realised that I cannot insert manually DNS forwardings in luci  dhcp and dns section, it says `Expecting: valid hostname` every time I try to insert a dns server. I think the problem should be in this function from `modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js`:

`function validateServerSpec(sid, s)`

However my regexp knowledge is not enough to fix it.

Btw this is on luci master.

**Comment by jow-** [comment]
Works for me. What input is failing exactly?

**Comment by resadent** [comment]
> Works for me. What input is failing exactly?
I was trying with 9.9.9.9, 9.9.9.11, 192.168.10.40. None of these seemed to work. I guess Id have to try a new build? Mine is from april 6.

**Comment by jow-** [comment]
Thanks. I was only testing the `/domain/ipaddr` notation, not the IPs directly.

**Comment by resadent** [comment]
> Thanks. I was only testing the `/domain/ipaddr` notation, not the IPs directly.

No problem, happy to help :).
