### ISSUE TITLE
luci-ssl-openssl build fails due to libiwinfo dependency

### ISSUE THREAD

**Issue by TampertK** [openwrt/luci#3871]
I'm trying to build an image from snapshot for the mt7620 target. While building the image the following error occurs:

```
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-ssl-openssl:
 * 	libiwinfo20181126
 * opkg_install_cmd: Cannot install package luci-ssl-openssl.
```

It seems that snapshot has moved to a new version: libiwinfo20200105

**Comment by hnyman** [comment]
You have not update all sources, apparently.
(Or you are using imagebuilder and some package repos still contain old binaries?)

The version mentioned in the dependency is dynamic, and if you build everything from sources, it is quite ok.
