### ISSUE TITLE
Latest RPC error in luci!!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/luci#3895]
![image](https://user-images.githubusercontent.com/45259624/79038328-0b0b5d00-7c0b-11ea-9a35-a30ae0d79fb5.png)
dnsmasq/dhcp:
![}1S)IKDSIH(FR$TPP~{6INT](https://user-images.githubusercontent.com/45259624/79038848-43149f00-7c0f-11ea-9503-bbc3aaed5e01.png)

**Comment by fuqiang03** [comment]
![image](https://user-images.githubusercontent.com/26851715/79043117-c80fb080-7c2f-11ea-95a1-f510c7884115.png)

**Comment by a-kibou** [comment]
![2020-04-12 02-34-00 的螢幕擷圖](https://user-images.githubusercontent.com/52091520/79052264-c4981b80-7c67-11ea-98d0-8a53c1d31548.png)
![2020-04-12 02-34-23 的螢幕擷圖](https://user-images.githubusercontent.com/52091520/79052265-c82ba280-7c67-11ea-835e-882cff77c06c.png)

**Comment by jow-** [comment]
Sorry, I can't read this and you didn't mention the URL it occurs on. I cannot reproduce the DHCP and DNS problem in the initial post. Ubus code 6 means that permission denied. Make sure you run the latest LuCI including https://github.com/openwrt/luci/commit/43e872871a85dce70509c3c97c10e9c61788c378

**Comment by jow-** [comment]
The ubus code 4 issue on the main status display is addressed with 65d673f4671215f2907baebc8d6860f64ba13307, I forgot to test on a unit without wireless. You can work around the problem with `touch /etc/config/wireless`.
