### ISSUE TITLE
luci-app-diskman triggers a luci-theme-openwrt theme internal error

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/luci#3905]
[luci-app-diskman ](https://github.com/lisaac/luci-app-diskman)triggers a luci-theme-openwrt theme internal error, and other theme works fine
![a01b798e-6c9e-4db0-ada7-41726cfc5608](https://user-images.githubusercontent.com/323794/79128981-fb407400-7dd6-11ea-889b-da139f33ea17.jpeg)
![876a2b8e-0e9e-42c3-95be-839f88e807f7](https://user-images.githubusercontent.com/323794/79128986-fd0a3780-7dd6-11ea-8446-eb91babfef34.jpeg)

**Comment by jow-** [comment]
This needs to be fixed in `luci-app-diskman` which is not part of this repository. Apparently the package constructs invalid XHTML somewhere.
