### ISSUE TITLE
ICOM B not connecting to ICOM A NEXT

### ISSUE THREAD

**Issue by vkolarov98** [openwrt/luci#3920]
Hey Guys, I have an ICOM A Next that I purchased about a year ago that i'm starting to do programming with. However, I'm having trouble connecting my ICOM B to it. Every time I plug it in I don't get any led indication on the ICOM B and when I start programming it says my MOST is not connected. I also noticed that the USB port is blue, meaning it's 3.0 I'm guessing. Could the ICOM B not connected be an issue with the fact that I don't have a USB 3.0. Please let me know if anyone has come across this or knows anyway to fix it. Thank you

**Comment by feckert** [comment]
Sorry but this is not related to LuCI. Please ask in the [forum](https://forum.openwrt.org/).
