### ISSUE TITLE
luci-app-statistics: Not showing up in LuCI

### ISSUE THREAD

**Issue by BlueMax** [openwrt/luci#3925]
'luci-app-statistics' is not showing up in LuCI (after full image update). There is no clickable 'graphs' entry (bootstrap theme). Other plugins are working. It was ok 3 weeks ago. Re-installing the plugin doesn't change anything. No errors in log.
Any ideas?

LuCI Master (git-20.108.52006-71e22c1) / OpenWrt SNAPSHOT r13002-02fcbe2f3d
x86

**Comment by BlueMax** [comment]
fixed.

**Comment by jow-** [comment]
What was the problem?

**Comment by hnyman** [comment]
> What was the problem?

Statistics menu item was missing due to wrong ACL declaration in 8f34e105c0
Fixed with d04b8bfc820
