### ISSUE TITLE
luci-app-adblock result[0].trim is not a function

### ISSUE THREAD

**Issue by shuaibird** [openwrt/luci#3931]
<img width="1010" alt="Screen Shot 2020-04-19 at 9 31 51 AM" src="https://user-images.githubusercontent.com/15889112/79677149-a068ab80-8220-11ea-8ce6-234983d0de4a.png">

https://github.com/openwrt/luci/blob/master/applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/overview.js#L125

**Comment by dibdot** [comment]
Just update your luci and rpcd packages.

**Comment by singalen** [comment]
Just happened to me.

```
~# opkg update
...
# opkg upgrade luci rpcd
Upgrading luci on root from git-20.136.49537-fb2f363-1 to git-20.142.51595-0c6fd62-1...
Downloading http://downloads.openwrt.org/releases/19.07.3/packages/arm_cortex-a15_neon-vfpv4/luci/luci_git-20.142.51595-0c6fd62-1_all.ipk
Configuring luci.
```
The package is freshly installed, not even present in the menu. Maybe something is missing in the data?

**Comment by kernc** [comment]
After a fresh install, a _reboot_ seems to be required.

**Comment by spicem** [comment]
same issue. reboot not helping
