### ISSUE TITLE
luci-app-sqm: the "Save & Apply" buttons and so on do not work.

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#3937]
Appears only in this app.
![Sin título](https://user-images.githubusercontent.com/47670442/79717218-57136d00-82af-11ea-8c42-0c5ebbd33926.png)

**Comment by castillofrancodamian** [comment]
Here too
![321](https://user-images.githubusercontent.com/47670442/79718382-4dd7cf80-82b2-11ea-80ea-085c9114a5d7.png)

**Comment by castillofrancodamian** [comment]
Chrome and Firefox.

**Comment by hnyman** [comment]
Possibly due to 74da73b01 missing some pages in SQM app and ffd627f2a1a introducing restrictions.
