### ISSUE TITLE
Feature request: luci-app-https-dns-proxy could add dropdown options for "1.1.1.1 for Families"

### ISSUE THREAD

**Issue by rajasdevel** [openwrt/luci#3940]
Cloudflare has recently added service that blocks malware and adult content: [1.1.1.1 for Families](https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families/).

It would be great if the option to select those services appeared on the "Resolver" drop-down menu, in addition to standard Cloudflare resolver.

**Comment by jow-** [comment]
@stangri

**Comment by stangri** [comment]
I've added these to the luci app, however it doesn't look like the https-dns-proxy service works with those two new cloudflare resolvers. It won't be a quick fix.

**Comment by n-thumann** [comment]
Works fine me: I can select all three CF DNS Services (General, Familiy & Security) and the all work as expected ✌️

**Comment by stangri** [comment]
Sorry, this should have been closed when principal package moved to RFC8484 support.
