### ISSUE TITLE
luci-app-multiwan missing dependency

### ISSUE THREAD

**Issue by wongsyrone** [openwrt/luci#395]
`luci-app-multiwan` depends on `multiwan`, but there's no package named `multiwan` in package feed. Drop this package should be a good idea. Any thoughts?

**Comment by oneru** [comment]
@wongsyrone @jow-  Possibly obsoleted by mwan3 and mwan3-luci, both in the packages feed.

**Comment by wongsyrone** [comment]
better migrate mwan3-luci to this repo.

**Comment by oneru** [comment]
This general issue has been under consideration. There are arguments to be made for keeping all the luci apps in this repo, as well as for putting the 3rd party luci apps in the packages repo where the underlying packages are. So far, it has not become obvious which will be the best option.
