### ISSUE TITLE
Error when connect to 192.168.1.1 

### ISSUE THREAD

**Issue by thienvk** [openwrt/luci#3955]
/usr/lib/lua/luci/dispatcher.lua:315: /etc/config/luci seems to be corrupt, unable to find section 'main'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:315: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:208: in function </usr/lib/lua/luci/dispatcher.lua:207>

**Comment by jow-** [comment]
Works for me. Make sure that the `rpcd` process is running
