### ISSUE TITLE
Theme Lost on Firmware Upgrade (Flash)

### ISSUE THREAD

**Issue by arrmo** [openwrt/luci#3963]
Hi,

Most settings are preserved when a new image is flashed, but it seems the theme (Design) setting is lost. Is this expected?

Thanks!

**Comment by hnyman** [comment]
> the theme (Design) setting is lost. Is this expected?

Theme is not just a setting, but an installable package
Losing is
* expected, if you install a release or snapshot build and you have not used Bootstrap, the default theme.
* unexpected if you have built a personal firmwre image where the theme is built-in.

**Comment by arrmo** [comment]
Hi,

It's a personal build, where the theme is built-in ... so the unexpected case 😆. I agree with you, if an installed packaged, this would / should go away (but in this case, seems it shoudl stay).

Thanks!
