### ISSUE TITLE
Updated Luci -> Status -> Routes :: Repeatable

### ISSUE THREAD

**Issue by jhngrn** [openwrt/luci#3971]
OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-20.115.52331-39a8290
--
Failed to execute template dispatcher target for entry '/admin/status/routes'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:74: Failed to load template 'admin_status/routes'.
Error while parsing template '/usr/lib/lua/luci/view/admin_status/routes.htm':
No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:74: in function '__init__'
	/usr/lib/lua/luci/util.lua:65: in function 'Template'
	/usr/lib/lua/luci/template.lua:27: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:920: in function </usr/lib/lua/luci/dispatcher.lua:919>

**Comment by jow-** [comment]
You need to run `rm -r /tmp/luci-*` or reboot.
