### ISSUE TITLE
TypeError appears in luci-app-nlbwmon of master branch!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/luci#3980]
![image](https://user-images.githubusercontent.com/45259624/80703200-effa8180-8b14-11ea-86a7-7d043371705a.png)

**Comment by LGA1150** [comment]
@jow- 
raw.githubusercontent.com is partially blocked in China.
To workaround this issue, you can use Jsdelivr CDN, which works in China
https://cdn.jsdelivr.net/gh/jow-/oui-database/oui.json

**Comment by LGA1150** [comment]
@dibdot your dnscrypt-proxy uses raw.githubusercontent.com too, please consider replacing that
