### ISSUE TITLE
No translation for Software section

### ISSUE THREAD

**Issue by ptipti23** [openwrt/luci#3984]
No full translation for "Software" section. Everything always in English
![image](https://user-images.githubusercontent.com/47698364/80834003-7f2c9580-8bf8-11ea-898d-485e10d4c228.png)

**Comment by stangri** [comment]
Just to clarify, when you say "everything is in english", do you mean package names and package descriptions?

**Comment by ptipti23** [comment]
Menu item, tabe titles. Not package names

**Comment by stangri** [comment]
It's a community-translated project, you can contribute to translations too: https://hosted.weblate.org/projects/openwrt/luci/ru/

**Comment by ptipti23** [comment]
Thanks for link, but is says that translation completed100%. "Software" section was a part of luci-base module in 18X OpenWRT, but now I cannot find this phrases in pot file.

**Comment by stangri** [comment]
You are right, weblate does show that luci-base is 100% translated to Russian, but according to the String Status on that same page not all of the translations have been approved.

Also, from reading [this](https://github.com/openwrt/luci/issues/3183), I'm not sure if weblate translations are making it into 18.06 tree.

@aparcar could you please advise? 

@aparcar can you please shed some light on the issue?

**Comment by ptipti23** [comment]
In 18.06 translation is OK. I am talking about LuCi 19X an other daily snapshots. In [this POT file](https://github.com/openwrt/luci/blob/master/modules/luci-base/po/templates/base.pot) missins msg about Software not only for Russian, but for all languages

**Comment by stangri** [comment]
Ah, right, I've completely misread your earlier message. I'm guessing it's due to some code being rewritten in javascript. Also, I do see some traces of the resources for that page in [this file](https://github.com/openwrt/luci/blob/master/modules/luci-base/po/en/base.po). Please wait for more seasoned team members to chime in.

**Comment by aparcar** [comment]
All strings seem to be [translated](https://hosted.weblate.org/zen/openwrt/luciapplicationsopkg/ru/), looking at the strings from [luci-app-opkg](https://github.com/openwrt/luci/tree/master/applications/luci-app-opkg). Is it still unavailable in the latest snapshot?

**Comment by ptipti23** [comment]
It seems opkg was translated only 10 hours ago (luci/applications/luci-app-opkg/po/ru/opkg.po)

**Comment by hnyman** [comment]
> It seems opkg was translated only 10 hours ago

I ran the treewide language template sync yesterday after noticing your issue, and that has probably generated the necessary templates.

Ps.
@stangri 
But that i18n-sync got me into major trouble, as weblate didn't like some strings with quoted quotemarks in luci-app-vpn-policy-routing package 

`applications/luci-app-vpn-policy-routing/po/pl/vpn-policy-routing.po | Syntax error on line 287`

Apparently weblate parsing did not like quoted quotemark at the end of a line
```
+"uruchomić następujące pliki użytkownika. Zobacz <a href=\"%s\" target=\""
+"_blank\">README</a> aby uzyskać szczegółowe informacje."
```
It might be better to leave the URL href with quotes outside the translatable string.

**Comment by stangri** [comment]
@hnyman just to confirm, is it choking on `\"%s\"`? I have that in 4 of my luci apps, should I send/merge a single PR for a "tree-wide" change?

**Comment by hnyman** [comment]
I think that weblate actually chke by the escaped " as the last character of the row. Placed there automatically by the gettext line length routines. Pure coincidence, but took a while to clarify, as there was a merge error plus a new "parsing error".

It might be better to have the whole HREF item in %s, so that the translatable string would not have any escaped \" characters. That would simplify the string quite aignificantly.

**Comment by stangri** [comment]
> It might be better to have the whole HREF item in %s, so that the translatable string would not have any escaped " characters. That would simplify the string quite aignificantly.

Thanks, that's what I'm currently testing locally -- moving the opening and closing tags into %s.

**Comment by hnyman** [comment]
That might be the most clear solution

(there are only a few apps that have translated href URLs in LuCI, so I guess we have so far escaped weblate's quirks, but yesterday there happened to be a character combination that it did not like.

**Comment by jow-** [comment]
Did you install `luci-i18n-opkg-ru`?

**Comment by stangri** [comment]
@jow- Would it make sense/be possible to make the `luci-i18n-opkg-xx` a dependency of `luci-i18n-base-xx`?

**Comment by ptipti23** [comment]
if it possible, place include "luci-i18n-firewall-xx"

**Comment by ptipti23** [comment]
> Did you install `luci-i18n-opkg-ru`? The software management is provided by `luci-app-opkg` which is an extra package, it is not covered by the base translations.

Yes, but still missing translation. I'm looking to git source at "https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/", it seems packages updated, I reinstall `luci-i18n-opkg-ru`, but nothing happends. Opkg still in english

**Comment by jow-** [comment]
> Would it make sense/be possible to make the luci-i18n-opkg-xx a dependency of luci-i18n-base-xx?

No, since it would break the modularity.

**Comment by ptipti23** [comment]
Firewall and now opkg is default apps. So if you want your language by default, you have to install 3 language packages? May be you create virtial package, ex. `luci-i18-default-xx` and this would install -base-opkg-firewall?

**Comment by jow-** [comment]
Yes.

**Comment by castillofrancodamian** [comment]
> Firewall and now opkg is default apps. So if you want your language by default, you have to install 3 language packages? May be you create virtial package, ex. `luci-i18-default-xx` and this would install -base-opkg-firewall?

Those apps are default, not their translations.

**Comment by ptipti23** [comment]
Well, so be it.
I already collected po2lmo and autonomously created opkg.ru.lmo, put it in the /usr/lib/lua/luci/i18n folder, reloaded the router ... But again, I don’t see the Russian language. Why?

**Comment by ptipti23** [comment]
Today openwrt snapshots were updated. Every thing is OK, `opkg` now in Russian. Thanks alot, Issue solved
