### ISSUE TITLE
Unable to set Wireless Country code in Luci

### ISSUE THREAD

**Issue by vietanhbui2000** [openwrt/luci#3989]
I'm unable to set Wireless Country code in Luci with recent master build. The only way i can set it is by directly editing /etc/config/wireless. But after editing, if any changes is made in Luci, the Wireless Country code option will get deleted with uci command immediately.
The screenshot below is what happens after i make some changes in Luci.
![Screenshot (175)](https://user-images.githubusercontent.com/26954616/80859687-d7ad7280-8c8c-11ea-84ca-f0be2eeb7231.png)

**Comment by castiel652** [comment]
This also happened to me.

**Comment by zxlhhyccc** [comment]
> 我无法使用最新的主版本在Luci中设置无线国家/地区代码。我可以设置它的唯一方法是直接编辑/ etc / config / wireless。但是，在编辑后，如果在Luci中进行了任何更改，则将使用uci命令立即删除“无线国家/地区代码”选项。
> 下面的屏幕截图是我在Luci中进行一些更改后发生的情况。
> ![截图（175）](https://user-images.githubusercontent.com/26954616/80859687-d7ad7280-8c8c-11ea-84ca-f0be2eeb7231.png)

No problem with mine, please pull...

**Comment by vietanhbui2000** [comment]
> > 我无法使用最新的主版本在Luci中设置无线国家/地区代码。我可以设置它的唯一方法是直接编辑/ etc / config / wireless。但是，在编辑后，如果在Luci中进行了任何更改，则将使用uci命令立即删除“无线国家/地区代码”选项。
> > 下面的屏幕截图是我在Luci中进行一些更改后发生的情况。
> > ![截图（175）](https://user-images.githubusercontent.com/26954616/80859687-d7ad7280-8c8c-11ea-84ca-f0be2eeb7231.png)
> 
> No problem with mine, please pull...

I'm sorry, pull what?
