### ISSUE TITLE
[LuCi-Interface] How can frontend developers better use the Docker development environment?

### ISSUE THREAD

**Issue by ZoZhang** [openwrt/luci#4014]
Hello everyone, I would like to ask, how can front-end personnel develop Luci-Interface based on Docker

For example, if I want to add a menu, I need to map the following two directories.
```
./modules/luci-base/luasrc/controller/admin/
==================>
/usr/lib/lua/luci/controller/admin/
```
What about javascript files? Do I need to find the corresponding relationship one by one?

Is there a more portable way to develop Luci Interface for developer frontend?

best regards
Zhao

**Comment by jow-** [comment]
I usually use sshfs. Install `openssh-sftp-server` on the router / virtual machine, then `sshfs root@ipaddr:/ /somewhere/else` and edit files in `/somewhere/else`.

Since sources are distributed over multiple directories you cannot simply map a single directory.
