### ISSUE TITLE
Error entering interface configuration

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4015]
![2020-05-05_16h49_08](https://user-images.githubusercontent.com/47670442/81115582-522efa00-8efa-11ea-8dca-fa45d23d5965.png)

**Comment by jow-** [comment]
Needs more detail, what did you do to trigger that error?

**Comment by castillofrancodamian** [comment]
I don't remember and it had been fixed when rebooting. I also cannot replay the error. What I remember is that in the terminal it said something like an error in line X, but I do not know what package, and it was when using opkg (I think that I install packages).

**Comment by jow-** [comment]
Okay, closing this now. I assume it was a transient error due to mismatching packages or something.
