### ISSUE TITLE
Question about view with js

### ISSUE THREAD

**Issue by biyun233** [openwrt/luci#4023]
###
I'm new to luci, and I'm developing the newest version of luci.

##
TypeError
"view.quick_setup.quick_setup" factory yields invalid constructor
  http://localhost:8043/luci-static/resources/luci.js?v=git-20.123.78906-cd69c11:178:21
  promiseReactionJob@[native code]

## 
how can I solve this problem?

thanks a lot!

**Comment by jow-** [comment]
Whatever `.js` file you require does not return `baseclass.extend({...})`
