### ISSUE TITLE
luci-theme-openwrt-2020: buttons are not visible

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4024]
![2020-05-06_18h57_51](https://user-images.githubusercontent.com/47670442/81232610-95a56900-8fcb-11ea-9f35-c50b93627be6.png)

![2020-05-06_18h59_29](https://user-images.githubusercontent.com/47670442/81232803-eddc6b00-8fcb-11ea-9068-d6e5b65c5be5.png)

**Comment by jow-** [comment]
Follow up on #3909

**Comment by castillofrancodamian** [comment]
Thank you!
