### ISSUE TITLE
Luci’s menu disappeared

### ISSUE THREAD

**Issue by 9pr19** [openwrt/luci#4040]
Hello,

I’ve lost Luci’s menu in the last few weeks:
![image](https://user-images.githubusercontent.com/25961602/81500849-1bc7f500-92d5-11ea-8ed1-807eae550a79.png)

With web browser network monitoring I’ve noticed the following error:

> 404 Not Found
>
>Sorry, the object you requested was not found.
>Unable to dispatch: /cgi-bin/luci/admin/menu

![image](https://user-images.githubusercontent.com/25961602/81500914-69dcf880-92d5-11ea-934f-b0a0edf616ef.png)

 System:
> OpenWrt 19.07.2, r10947-65030d81f3

Luci packages:
> liblucihttp-lua - 2019-07-05-a34a17d5-1
> liblucihttp0 - 2019-07-05-a34a17d5-1
> luci-app-ddns - 2.4.9-7
> luci-app-firewall - git-20.130.24486-07e6cfa-1
> luci-app-opkg - git-20.130.24486-07e6cfa-1
> luci-app-statistics - git-20.130.24486-07e6cfa-1
> luci-app-uhttpd - git-20.130.24486-07e6cfa-1
> luci-base - git-20.130.24486-07e6cfa-1
> luci-compat - git-20.130.24486-07e6cfa-1
> luci-lib-ip - git-20.130.24486-07e6cfa-1
> luci-lib-ipkg - git-20.130.24486-07e6cfa-1
> luci-lib-iptparser - git-20.130.24486-07e6cfa-1
> luci-lib-jsonc - git-20.130.24486-07e6cfa-1
> luci-lib-nixio - git-20.130.24486-07e6cfa-1
> luci-mod-admin-full - git-20.130.24486-07e6cfa-1
> luci-mod-network - git-20.130.24486-07e6cfa-1
> luci-mod-status - git-20.130.24486-07e6cfa-1
> luci-mod-system - git-20.130.24486-07e6cfa-1
> luci-proto-ipv6 - git-20.130.24486-07e6cfa-1
> luci-proto-ppp - git-20.130.24486-07e6cfa-1
> luci-theme-bootstrap - git-20.130.24486-07e6cfa-1
> rpcd-mod-luci - 20191114

**Comment by tverlaan** [comment]
I'm experiencing the same issue. I see this in my browser console, it might help:
```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ClassConstructor.json (luci.js?v=git-20.130.24486-07e6cfa:32)
    at ClassConstructor.eval (ui.js?v=git-20.130.24486-07e6cfa:215)
```

**Comment by jow-** [comment]
`rm -r /tmp/luci-*` or reboot your router.

**Comment by 9pr19** [comment]
I removed the folders then login into Luci and everything is back.
@jow- thank you.

**Comment by rammstein9910** [comment]
I have tried what @jow- advised, but as a plan B... I used, and it worked `opkg install --force-reinstall luci`

**Comment by olenikolai** [comment]
None of the above worked for me, but this guide at [Techoverflow](https://techoverflow.net/2021/05/04/how-i-fixed-openwrt-luci-error-etc-config-luci-seems-to-be-corrupt-unable-to-find-section-main/) fixedt it for me. The problem was a bad rpcd configuration, fixed it with the commands:
cp /rom/etc/config/rpcd /etc/config/rpcd
service uhttpd restart
