### ISSUE TITLE
RPC call to uci/set failed with ubus code 2: Invalid argument

### ISSUE THREAD

**Issue by biyun233** [openwrt/luci#4064]
I received an error code 2 when I tried to use uci.set().    
and the result of uci.set() is strange.  
<img width="495" alt="截屏2020-05-1716 06 25" src="https://user-images.githubusercontent.com/44998205/82149928-b7b6ab00-9857-11ea-8fca-e77de17705bd.png">  
the part of protocol is seems modified successfully, but the network is not modified.
<img width="642" alt="截屏2020-05-1716 06 43" src="https://user-images.githubusercontent.com/44998205/82149978-c8ffb780-9857-11ea-86c8-b0bacbd91146.png">

could you please tell me where the problem is?
thanks a lot!

**Comment by jow-** [comment]
This error is thrown when section id or option names are invalid.
