### ISSUE TITLE
OpenWrt 19.07.3 | Mount Points missing from System menu in LuCI

### ISSUE THREAD

**Issue by ioanpintican** [openwrt/luci#4067]
OpenWrt 19.07.3 r11063-85e04e9f46 / LuCI openwrt-19.07 branch git-20.138.63234-ccd9d67 on Linksys WRT32X, block-mount (2020-05-12-84269037-1) installed and **Mount Points submenu is missing from System menu in LuCI**.

![Untitled](https://user-images.githubusercontent.com/48879414/82233242-63cfc300-9938-11ea-9aa1-d393d415e4ec.png)

**Comment by jow-** [comment]
Try to log out and in again, see if it appears then.

**Comment by ioanpintican** [comment]
@jow- already tried that (I know that it takes some moving around the menus in order to make new ones appear), but it's not there...

**Comment by jow-** [comment]
So you actually logged out and logged in again by entering your password to obtain a new session id?

**Comment by ioanpintican** [comment]
Yep. Even tried different browsers & clear cache between sessions.
And I rebooted also.

**Comment by jow-** [comment]
Ok, looks broken then.

**Comment by ioanpintican** [comment]
Mounted the usb hdd form ssh session tho... :)
![Untitled2](https://user-images.githubusercontent.com/48879414/82234532-3552e780-993a-11ea-965c-24cc5598e67f.png)

**Comment by pesa1234** [comment]
Same also for me on 19.07.3

**Comment by jow-** [comment]
Works for me after a device reboot.

**Comment by ioanpintican** [comment]
Performed reset to defaults & flashed factory firmware.
Now it works for me too.
Thanks for the response :)

**Comment by XinArkh** [comment]
You need to install `block-mount` package first.
```bash
opkg install block-mount
```
ref: https://forum.openwrt.org/t/no-mount-points-menu-solved/77907
