### ISSUE TITLE
i18n: Implement better translation dependencies

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#4075]
Moved from https://github.com/openwrt/luci/issues/3183#issuecomment-630782884

**There are additional resources in the initial thread.**

> Looking at #3984 I wonder if there is a clean dependency magic that allows to install something like `luci-ru` which automatically pulls other translation dependencies?

@aparcar @hnyman I have played with the idea but unfortunately found no way to make it easy. Has anyone else tried it? I took a look at it in luci.mk and tried to find out if LUCI_LANG_\<XX\> is set to **m** or **y**.

If the value is **y** then this language is add as an dependecy to the package and is installed as an dependency on `opkg install luci-app-<package_name>`

If the value is **m** then nothing is changed the language luci-i18n-\<package_name\>-\<lang\> has an dependency to the package as [before](https://github.com/openwrt/luci/blob/master/luci.mk#L264).

This works only for image generation if you build your own images. If you set the language you want to have in your image **y** on build then this get installed as an dependency of this package. So you do not have to install the default i18n´s for your application anymore this is done by opkg.

**Comment by jow-** [comment]
You need a higher level component (e.g. `luci-app-opkg` or the LuCI system config view where you select the language) which takes care of installing additional i18n resources, depending on the installed LuCI addons.

It is not possible to fix that on a kconfig or opkg metadata level.
