### ISSUE TITLE
ParentalControl/Firewall/Filtering.

### ISSUE THREAD

**Issue by Juno72** [openwrt/luci#4078]
Had an idea about setting up a rule system for various devices to be turned on/off automatically, but also manually.
Looking at 
https://openwrt.org/_media/media/docs/howto/firewall_-_parental_control_settings_via_luci.png
the rules are per device, and to lookup the rules defined for a device one has to iterate all rules.

It would be more practical to have a GUI to enable and disable a set of rules for a device or device group (set of devices). And to do this manually or time based.

The GUI will consist of four sections:
- A list of named rulesets to be applied (to be applied on a device, a set of devices, or all)
- A list of named devicesets the rules should be applied on. A device can be in several sets.
- A list of named timers settings: each timer setting contains a named schedule to turn-on/off
- A matrix of rulesets on one side, and devicesets to the other [row and column headers]. The devicesets can be extended with all (present/known) devices and [all devices].

Now in each matrix cell there is:
- A switch to enable, disable, or have a timer activation to perform a set of rules to a set of devices as indicated by the row and column headers
- A selection box selecting the timer schedule.

My knowledge of iptables, etc is limited, just as how the above GUI should interact with them, how to generate/parse/extend using e.g. comment labels...

But I am curious about this idea/suggestion.

**Comment by dibdot** [comment]
Please ask in the forum if someone is willing to implement such things.
