### ISSUE TITLE
Wi-Fi buttons do weird things

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4083]
It seems to me to see that if I enable or disable one Wi-Fi interface, the other one on the other radio is also disabled.

![1](https://user-images.githubusercontent.com/47670442/82589085-00c97080-9b72-11ea-9882-817b901c6f05.png)
![2](https://user-images.githubusercontent.com/47670442/82589098-045cf780-9b72-11ea-8aaa-1e35896e9823.png)

**Comment by castillofrancodamian** [comment]
In the wireless configuration file I see that the _disabled_ option is at 0 of the two radios, but one is working.

**Comment by jow-** [comment]
That does not sound like a LuCI bug to me, probably an issue in the underlying OpenWrt subsystem

**Comment by jow-** [comment]
Seems to be a bug in OpenWrt: https://forum.openwrt.org/t/wrt1900acsv2-only-one-wifi-radio-is-staying-up/64273
