### ISSUE TITLE
OCSERV - MFA config

### ISSUE THREAD

**Issue by Gustavo-FS** [openwrt/luci#4094]
Hello everyone

I'm trying to enable MFA with Google Authentication on my openvpn server but not work
I found several references on the subject but they are very old 

https://forum.archive.openwrt.org/viewtopic.php?id=38905
https://github.com/openconnect/recipes/blob/master/ocserv-2fa.md#OATH1

can someone help me with a Configuration How-TO?
in all the configurations that I tried to make the ocserv does not go up when changing the method to PAM I need some additional package installed?

**Comment by jow-** [comment]
Not a LuCI issue. Please use the forums or address the maintainer of ocserv directly at https://github.com/openwrt/packages (maintainer @nmav)
