### ISSUE TITLE
Luci not show kernel and system log.

### ISSUE THREAD

**Issue by Dzanar** [openwrt/luci#4098]
Openwrt 19.07.3 (openwrt-19.07 branch (git-20.145.59100-515bd92) / OpenWrt 19.07.3 r11063-85e04e9f46) don't show kernel and system log.

![obraz](https://user-images.githubusercontent.com/8012704/82842659-aa925f80-9eda-11ea-985e-bec8d2ef7052.png)

**Comment by jow-** [comment]
Works for me on a vanilla x86/64 image in Qemu.

**Comment by Dzanar** [comment]
I'm using TP-Link W8970. How can I check why this is not working?
