### ISSUE TITLE
luci-base: "resolve_conffiles: Existing conffile /etc/config/luci is different from the conffile in the new package."

### ISSUE THREAD

**Issue by IeP4nieF** [openwrt/luci#4100]
Every time an update for luci-base is installed (I'm on openwrt 19.07.3) the following error is thrown.

    Collected errors:
     * resolve_conffiles: Existing conffile /etc/config/luci is different from the conffile in the new package. The new conffile will be placed at /etc/config/luci-opkg.

I didn't changed /etc/config/luci. The version in the update-package is (since 20200510), which can be verified [here](https://github.com/openwrt/luci/blob/master/modules/luci-base/root/etc/config/luci).

        config core main
                option lang auto
                option mediaurlbase /luci-static/bootstrap
                option resourcebase /luci-static/resources
                option ubuspath /ubus/

        config extern flash_keep
                option uci              "/etc/config/"
                option dropbear "/etc/dropbear/"
                option openvpn  "/etc/openvpn/"
                option passwd   "/etc/passwd"
                option opkg             "/etc/opkg.conf"
                option firewall "/etc/firewall.user"
                option uploads  "/lib/uci/upload/"

        config internal languages

        config internal sauth
                option sessionpath "/tmp/luci-sessions"
                option sessiontime 3600

        config internal ccache
                option enable 1

        config internal themes

        config internal apply
                option rollback 90
                option holdoff 4
                option timeout 5
                option display 1.5

I copied this version to /etc/config/luci serveral times. But after some days /etc/config/luci changed to:

        config core 'main'
                option lang 'auto'
                option mediaurlbase '/luci-static/bootstrap'
                option resourcebase '/luci-static/resources'
                option ubuspath '/ubus/'

        config extern 'flash_keep'
                option uci '/etc/config/'
                option dropbear '/etc/dropbear/'
                option openvpn '/etc/openvpn/'
                option passwd '/etc/passwd'
                option opkg '/etc/opkg.conf'
                option firewall '/etc/firewall.user'
                option uploads '/lib/uci/upload/'

        config internal 'languages'
                option de 'Deutsch (German)'
                option en 'English'

        config internal 'sauth'
                option sessionpath '/tmp/luci-sessions'
                option sessiontime '3600'

        config internal 'ccache'
                option enable '1'

        config internal 'themes'
                option Bootstrap '/luci-static/bootstrap'

        config internal 'apply'
                option rollback '90'
                option holdoff '4'
                option timeout '5'
                option display '1.5'

        config internal 'diag'
                option dns 'openwrt.org'
                option ping 'openwrt.org'
                option route 'openwrt.org'

I don't know which program made this change, so it is possible that this bug don't belong to lucie-base. The change didn't make any difference. But there should'nt be an error message on every `opkg upgrade`. One solution would be to change [/etc/config/luci](https://github.com/openwrt/luci/blob/master/modules/luci-base/root/etc/config/luci) to the version above.

Btw. I didn't used the web-interface. The file changed on disk without logging in into the web-interface.

best regards

**Comment by jow-** [comment]
Various LuCI packages amend this file, e.g. themes and languages add their respective entries to it, so this behavior is expected.
