### ISSUE TITLE
802.11w Management Frame Protection blocking Bonjour / autoconf

### ISSUE THREAD

**Issue by wojciechczyz** [openwrt/luci#4109]
On  OpenWrt 19.07.3 r11063-85e04e9f46 as soon as I enable 802.11w Management Frame Protection on the interface where bonjour devices connect, bonjour traffic is blocked. I am using Tivoli Audio Art speakers and Raspberry 4 with OMV 5. 

As a consequence I also cannot use WPA3 which requires 802.11w Management Frame Protection to be enabled.

**Comment by hnyman** [comment]
Nothing to do with LuCI GUI.
