### ISSUE TITLE
Applied wireguard configuration have same IPv4 endpoint for all peers

### ISSUE THREAD

**Issue by RussianNeuroMancer** [openwrt/luci#4115]
Hello!

I found pretty odd behavior on one of my OpenWRT VM's. Initially when I didn't found what is going on it looked exactly like described in the title - while I obviously configured luci-app-wireguard with different IPv4 endpoints for each peer (and I also verified /etc/config/network content to confirm that) for some reason both of wg utility and OpenWRT WebUI showed me that WireGuard try to establish connection with all peers via same IPv4. Just to be clear - WireGuard IPv4 endpoints in /etc/config/network is different for each peer, however in wg output all endpoints is the same - exactly same IPv4 address in each peer Endpoint: field.

I tried to reset configuration and re-configure this VM several times and found that issue is not reproducible until I add one specific peer to WireGuard peers list (let's call this peer as "peer33"). Until I do that everything is fine. But as soon as I add this specific peer33 - endopints of other peers in wg output change to this peer IPv4 address.

So it's seems like something about this peer public key and IPv4 endpoint address somehow break luci-app-wireguard (ot some other component underneath). How I can help with debugging this issue?

**Comment by dibdot** [comment]
Sounds not like an LuCI issue at all - please ask in the forum.
