### ISSUE TITLE
A small spelling mistake in English (screen DHCP and DNS)

### ISSUE THREAD

**Issue by mackonsti** [openwrt/luci#4121]
Hello everyone, many warm thanks for your great work and continuous support.

I just installed (converted) OpenWrt **19.07.3** to my Asus RT-AC58U and discovered a small spelling mistake whilst browsing the menus.

In DNS and DHCP there is a tab showng "Resolv" instead of "Resolv**e** and Host Files".

![Spelling Mistake](https://user-images.githubusercontent.com/1313613/83340922-eadc4e00-a2dd-11ea-913a-e1620ec83195.png)

You could perhaps consider writing "Lease file" instead of one single word, too.

Thank you again.

**UPDATE:** Please, a question. I added a local computer as a Static Lease and on the UI I got this displayed:

![Static Lease Result](https://user-images.githubusercontent.com/1313613/83341200-d188d100-a2e0-11ea-8f14-c43e2f4dbb75.png)

Is the first line syntax correct? Perhaps there's a mistake there too? I don't recognise the syntax, so might as well ask you. Thanks again.

**Comment by dibdot** [comment]
The speeling is OK, see https://en.wikipedia.org/wiki/Resolv.conf

**Comment by mackonsti** [comment]
Thank you @dibdot sorry for missing that out.
