### ISSUE TITLE
luci-app-advanced-reboot: Warning: Unable to obtain device information!

### ISSUE THREAD

**Issue by pesa1234** [openwrt/luci#4135]
Hi all,
I have luci-app-advanced-reboot git-20.157.47124-7b4a785 on WRT1900ACS with latest SNAPSHOT SNAPSHOT r13503-050c31fa26 and I get the error on title.
What I have do wrong?

Thanks
![immagine](https://user-images.githubusercontent.com/6216993/83969375-f88e6680-a8cf-11ea-848d-d4dee4e8f4cc.png)

**Comment by stangri** [comment]
Linksys WRT-series devices were recently renamed in master, I have fixed it in this version: https://github.com/stangri/openwrt-repo/blob/master/luci-app-advanced-reboot_git-20.155.55664-f35803e-54_all.ipk if you could test it and let me know I'd appreciate it.

**Comment by pesa1234** [comment]
![immagine](https://user-images.githubusercontent.com/6216993/84195970-be73bf00-aa9f-11ea-8d65-049d700da496.png)
Works perfectly, sorry but I don't see that the name was changed otherwise I was more accurate on bug report.

Thanks

**Comment by 1Jeff1** [comment]
Also fixed on wrt32x

![Screenshot165725](https://user-images.githubusercontent.com/46228800/84198826-20b5cb00-aa72-11ea-8e32-682ffd0de0cf.jpg)
