### ISSUE TITLE
getDHCPLeases: The same device returns different mac address information

### ISSUE THREAD

**Issue by ZoZhang** [openwrt/luci#4143]
Hello everyone, I have a question about getting connected device information through`getDHCPLeases`.

````
var callLuciDHCPLeases = rpc.declare({
	object: 'luci-rpc',
	method: 'getDHCPLeases',
	expect: { '': {} }
});
`````

The above method will return the address information of the connected device, including ipv4 and ipv6.

````
dhcp6_leases: 
{expires: 42891, ip6addr: "fd56:ece5:8cd8::79f", macaddr: "25:A3:30:4C:14:10", duid: "0001000125a3304c14109fe10235", ip6addrs: ["fd56:ece5:8cd8::79f"]}

dhcp_leases: 
{expires: 42894, ipaddr: "192.168.1.145", hostname: "local", macaddr: "00:E0:4C:68:4A:2F", duid: "01:00:e0:4c:68:4a:2f"}
````

But the problem is that the ipv4 and ipv6 information from the same device has different mac addresses.

Is there any way to get the ipv4 and ipv6 information of the same device at the same time ?

In addition, can we get the amount of data transmitted by the device (RX Data / TX Data) through their mac addresses?

Looking forward to your reply, thanks!

**Comment by jow-** [comment]
No, this is not possible.
