### ISSUE TITLE
luci-ssl-nginx: luci-app-opkg not installed

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4148]
I have Snapshots and when installing luci-ssl-nginx to have LuCI, luci-app-opkg is not installed as it is with luci-ssl.

**Comment by hnyman** [comment]
Commit 391e82d in 2018 added luci-app-opkg dependency to
the 'luci' collection and its derivatives, but as nginx collections
do not depend on main 'luci', they did not get the intended change.

I added the dependency to master and 19.07.

**Comment by castillofrancodamian** [comment]
👍👍👍
