### ISSUE TITLE
pull requests: rebase instead of merging

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#4158]
It looks like most pull requests are merged rather than rebased, which somewhat pollutes the git log. Could we make it a policy that pull requests are rebased by the commit person?

I'm assuming everyone with commit rights here know how to do so via git, however this is also possible via the GitHub web interface:
![image](https://user-images.githubusercontent.com/16000931/84322738-79a16400-ab43-11ea-90ac-20c10e07f28a.png)

**Comment by hnyman** [comment]
I feel that doing the traditional PR merge leaves a better track of the possible discussion, in case the PR was larger or contained several commits.

But that "rebase and merge" would be ok for small single fixes. That might be good especially on the packages feed.

(To be honest, I had not even noticed that the feature is now available in GiuHub GUI. Apparently the feature has been introduced a few years back, as it wasn't there when we started using Github)

**Comment by jow-** [comment]
I have no opinion, I usually just hit the big green button. Deferring to the others opinion here.

**Comment by aparcar** [comment]
> I feel that doing the traditional PR merge leaves a better track of the possible discussion, in case the PR was larger or contained several commits.

It wont remove the PR, so it is still possible to backtrack the initial discussion.

> I have no opinion, I usually just hit the big green button. Deferring to the others opinion here.

If you change once to *Rebase and merge* GitHub will remember it without the need of selecting it each time.

Please both give it a try.

**Comment by NeoRaider** [comment]
In Gluon, we recently changed policy to always merge or squash, and never rebase, so we always have a reference to the Github PR in the Git history (in the merge or squashed commit). IMO having proper history instead of a linearized one is one of the advantages of Git. It's also nicer for tooling like CI tests, as the diff between `HEAD` and `HEAD^` will contain the last merge.

**Comment by aparcar** [comment]
I think tracking back the PR works via the following: 
![image](https://user-images.githubusercontent.com/16000931/84546542-4246ca80-ac9d-11ea-8ae8-1e8016932364.png)

For CIs, all CIs I've used so far export some env vars so you can always tell what commits where added. However I see that `HEAD` and `HEAD^` is more generic.

**Comment by dibdot** [comment]
For part time contributors like me, it's less risky to keep the merge strategy - always re-writing project history can be potentially harmful, at least when I'm doing that ... :smile:

**Comment by aparcar** [comment]
> For part time contributors like me, it's less risky to keep the merge strategy - always re-writing project history can be potentially harmful, at least when I'm doing that ... :smile: 

Sorry I don't understand, what is more risky about it? I'm not proposing to force push anything...?

**Comment by aparcar** [comment]
Okay seems like people prefer merge over rebase - closing.
