### ISSUE TITLE
Please add missing sysupgrade options

### ISSUE THREAD

**Issue by zorxd** [openwrt/luci#4160]
Hi

sysupgrade has some interesting options, including the following:

-k : include in backup a list of current installed packages
-u : skip from backup files that are equal to those in /rom

It would be nice if they were added to LuCI as well. Personally, I would always choose these two options when upgrading. If you think adding these options would add to much bloat to the GUI, I think at least -k could be considered safe to add by default, perhaps -u as well. If a user didn't touch a file, it's likely the default one will be good after the upgrade. Maybe -u could even help prevent bugs when keeping configuration files and upgrading to a new major release.

**Comment by shoulders** [comment]
hi

for newbies can someone explain what the following settings do?

-k : include in backup a list of current installed packages
-u : skip from backup files that are equal to those in /rom

![image](https://user-images.githubusercontent.com/319997/142461901-0df83eac-1433-4b78-9edb-38600e726dfc.png)

And just confirm that `Keep settings and retain the current configuration` just preserves the config settings during the upgrade but not any of the binaries/packages installed by users.

My internet searches just bring me back here and these options are not explained anywhere.

thanks

**Comment by zorxd** [comment]
-k creates a file with all packages installed before the update which will be available in installed_packages.txt after the update. So no more "Oh, which package am I missing?" since yes, software update doesn't preserve installed packages.

-u saves some space by not including unmodified configuration files in the backup. It also has the benefit of getting new default options if they changed with the new update, instead of getting stuck with legacy configuration files forever.
