### ISSUE TITLE
luci-proto-ppp and luci-proto-ipv6 - No L2TP

### ISSUE THREAD

**Issue by francisuk1989** [openwrt/luci#4189]
I have tried to install the following L2TP under OpenWrt 19.07.3 ath79, see https://github.com/openwrt/packages/issues/12544 I have also tried another Router with OpenWrt 19.07.3 under ar71xx but still experiencing the same issue.
```
luci-proto-ipv6
luci-proto-ppp
```
When trying to add a new interface iunder luci s not there, Im not trying to setup a VPN as my ISP has given me info to setup L2TP with a Public IP.

**Comment by jow-** [comment]
You need to reboot or restart (not reload) netifd to make it pick up the new l2tp protocol.

**Comment by feckert** [comment]
@francisuk1989 If the suggestion does not help please reopen.
