### ISSUE TITLE
No "shutdown" button

### ISSUE THREAD

**Issue by Kruemmelspalter** [openwrt/luci#4193]
I really miss a shutdown button. Actually you can ssh into it and do `halt` or `poweroff`, but it's not really convenient

**Comment by feckert** [comment]
if this is really needed we could add this to the following page https://github.com/openwrt/luci/blob/master/modules/luci-mod-system/htdocs/luci-static/resources/view/system/reboot.js

**Comment by jow-** [comment]
That only makes sense on x86 if at all. Most other targets do not really offer a proper shutdown possibility. They'll either reboot or move into busy loop, essentially halting the CPU.
