### ISSUE TITLE
luci-app-commands: broken special characters

### ISSUE THREAD

**Issue by koshev-msk** [openwrt/luci#4217]
Hi! I am using luci application commands.
I have to push the command and argument with special characters.
Input Example: mycommand AT+QCSQ
and see in the output answer
"mycommand AT QCSQ"
The next time I enter the argument: AT%2BQCSQ and I see a special character "+" in the response.
Possible fix it?
Thanks.

**Comment by jow-** [comment]
Which LuCI version?

**Comment by koshev-msk** [comment]
Tested on 
luci git-20.064.26341-4fc4c79 OpenWrt 18.06.8
and 
luci git-20.178.63701-ce35d08 OpenWrt 19.07.3

I seen same problem.

**Comment by jow-** [comment]
Cannot reproduce on either 19.07 or master.

19.07:
![grafik](https://user-images.githubusercontent.com/2528802/86521857-427a5600-be56-11ea-8533-310062b30e67.png)
![grafik](https://user-images.githubusercontent.com/2528802/86521868-50c87200-be56-11ea-8b45-dafab3f86745.png)

master:
![grafik](https://user-images.githubusercontent.com/2528802/86521877-650c6f00-be56-11ea-96aa-d0fd6736db5c.png)
![grafik](https://user-images.githubusercontent.com/2528802/86521882-75244e80-be56-11ea-89ba-ddd99609562a.png)
