### ISSUE TITLE
Option to copy passwords between Wifi networks

### ISSUE THREAD

**Issue by ericschultz** [openwrt/luci#423]
When I set up a home router, I want the same password for my 2.4ghz and 5ghz wireless networks. It would be convenient if LuCI had a feature for setting password for all networks at once. This would reduce errors in setting up passwords; my factory firmware had it and it was pretty convenient.

Whether could be implemented via a button or some other setting or what should happen if you have more than two wireless networks is not something I've worked out yet :)

**Comment by feckert** [comment]
This is an very old feature request. And nothing happen so -> closing
