### ISSUE TITLE
LUCI does not show leases from other files

### ISSUE THREAD

**Issue by dMopp** [openwrt/luci#4231]
eG:

-rw-r--r--    1 root     root           603 Jul  4 23:33 /tmp/dhcp.leases --> Showing in the WebUI
-rw-r--r--    1 root     root             0 Jul  4 23:30 /tmp/dhcp.leases.gast --> Ignored
-rw-r--r--    1 root     root           138 Jul  4 23:33 /tmp/dhcp.leases.iot --> Ignored

**Comment by jow-** [comment]
LuCI does not support multiple dnsmasq instances.

**Comment by dMopp** [comment]
Actually not 100% true. After using UCI to Setup this, you can configure it through LuCI, too. So it might be Not 100% supported but it should! (Maybe it’s also a UCI bug...)
