### ISSUE TITLE
CheckBox works not fine

### ISSUE THREAD

**Issue by Aaronwang81** [openwrt/luci#4233]
with luci theme Material,some checkbox works not fine.
looks below.
![image](https://user-images.githubusercontent.com/37022191/86572915-32718c00-bfa6-11ea-853b-aaa64f781d8f.png)

**Comment by jow-** [comment]
Which theme is that?

**Comment by Aaronwang81** [comment]
The **_Material_** theme
by offical package luci-theme-material
version:git-20.186.82389-282dbf8-1

**Comment by jow-** [comment]
@LuttyYang

**Comment by feckert** [comment]
No Reaction
