### ISSUE TITLE
Wifi crashing when i leave home

### ISSUE THREAD

**Issue by andrearizzello** [openwrt/luci#4242]
I have a WRT3200ACM Linksys router with openwrt 19.03 installed
Now the problem is that the wifi crashes and i'm not able to reconnect if i don't reboot the whole router

kernelog:
> [30158.223918] ------------[ cut here ]------------
> [30158.228564] WARNING: CPU: 1 PID: 0 at net/sched/sch_generic.c:320 0xc055f144
> [30158.235649] NETDEV WATCHDOG: wlan2 (mwifiex_sdio): transmit queue 1 timed out
> [30158.242814] Modules linked in: pppoe ppp_async pppox ppp_generic nf_conntrack_ipv6 iptable_nat ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_ecn xt_dscp xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_FLOWOFFLOAD xt_DSCP xt_CT xt_CLASSIFY slhc rfcomm nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack mwifiex_sdio mwifiex iptable_mangle iptable_filter ipt_ECN ip_tables hidp hci_uart crc_ccitt btusb btmrvl_sdio btmrvl btintel bnep bluetooth hid evdev input_core mwlwifi mac80211 cfg80211 compat nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter
> [30158.313829]  ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 tun ecdh_generic kpp ecb cmac gpio_button_hotplug
> [30158.323803] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 4.14.180 #0
> [30158.329922] Hardware name: Marvell Armada 380/385 (Device Tree)
> [30158.335869] Function entered at [<c010ebf8>] from [<c010a8b8>]
> [30158.341726] Function entered at [<c010a8b8>] from [<c063ed54>]
> [30158.347583] Function entered at [<c063ed54>] from [<c0128620>]
> [30158.353440] Function entered at [<c0128620>] from [<c0128674>]
> [30158.359297] Function entered at [<c0128674>] from [<c055f144>]
> [30158.365154] Function entered at [<c055f144>] from [<c01784f0>]
> [30158.371011] Function entered at [<c01784f0>] from [<c01786cc>]
> [30158.376867] Function entered at [<c01786cc>] from [<c0101628>]
> [30158.382724] Function entered at [<c0101628>] from [<c012d2b8>]
> [30158.388581] Function entered at [<c012d2b8>] from [<c01661a4>]
> [30158.394437] Function entered at [<c01661a4>] from [<c0101464>]
> [30158.400294] Function entered at [<c0101464>] from [<c010b54c>]
> [30158.406151] Exception stack(0xdf465f80 to 0xdf465fc8)
> [30158.411225] 5f80: 00000001 00000000 00000000 c01144a0 ffffe000 c0903cb8 c0903c6c 00000000
> [30158.419438] 5fa0: 00000000 414fc091 00000000 00000000 df465fc8 df465fd0 c0107ea8 c0107eac
> [30158.427650] 5fc0: 60000013 ffffffff
> [30158.431152] Function entered at [<c010b54c>] from [<c0107eac>]
> [30158.437009] Function entered at [<c0107eac>] from [<c015ced4>]
> [30158.442866] Function entered at [<c015ced4>] from [<c015d1f0>]
> [30158.448722] Function entered at [<c015d1f0>] from [<0010182c>]
> [30158.454582] ---[ end trace b4335f322e8ebe19 ]---
> [30158.459222] mwifiex_sdio mmc0:0001:1: 2984824 : Tx timeout(#1), bss_type-num = 1-0
> [30164.295990] mwifiex_sdio mmc0:0001:1: 2985408 : Tx timeout(#2), bss_type-num = 1-0
> [30174.229382] mwifiex_sdio mmc0:0001:1: 2986401 : Tx timeout(#3), bss_type-num = 1-0
> [30179.261085] mwifiex_sdio mmc0:0001:1: 2986904 : Tx timeout(#4), bss_type-num = 1-0
> [30189.264495] mwifiex_sdio mmc0:0001:1: 2987904 : Tx timeout(#5), bss_type-num = 1-0
> [30199.277905] mwifiex_sdio mmc0:0001:1: 2988905 : Tx timeout(#6), bss_type-num = 1-0
> [30209.271308] mwifiex_sdio mmc0:0001:1: 2989904 : Tx timeout(#7), bss_type-num = 1-0
> [30209.278916] mwifiex_sdio mmc0:0001:1: tx_timeout_cnt exceeds threshold.	Triggering card reset!
> [30209.311755] mwifiex: Have pending ack frames!
> [30209.317085] mwifiex_sdio mmc0:0001:1: info: shutdown mwifiex...
> [30209.323232] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
> [30209.329180] mwifiex_sdio mmc0:0001:1: Failed to delete mgmt IEs!
> [30209.335223] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
> [30209.341168] mwifiex_sdio mmc0:0001:1: Failed to stop the BSS
> [30209.347420] br-lan: port 2(wlan2) entered disabled state
> [30209.354770] device wlan2 left promiscuous mode
> [30209.359237] br-lan: port 2(wlan2) entered disabled state
> [30209.401445] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
> [30209.407398] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
> [30209.413412] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
> [30209.606117] mwifiex_sdio mmc0:0001:1: WLAN FW already running! Skip FW dnld
> [30209.613162] mwifiex_sdio mmc0:0001:1: WLAN FW is active
> [30219.994960] mwifiex_sdio mmc0:0001:1: mwifiex_cmd_timeout_func: Timeout cmd id = 0xa9, act = 0x0
> [30220.003788] mwifiex_sdio mmc0:0001:1: num_data_h2c_failure = 0
> [30220.009656] mwifiex_sdio mmc0:0001:1: num_cmd_h2c_failure = 0
> [30220.015429] mwifiex_sdio mmc0:0001:1: is_cmd_timedout = 1
> [30220.020850] mwifiex_sdio mmc0:0001:1: num_tx_timeout = 0
> [30220.026187] mwifiex_sdio mmc0:0001:1: last_cmd_index = 2
> [30220.031522] mwifiex_sdio mmc0:0001:1: last_cmd_id: d0 00 b2 00 a9 00 b0 00 b0 00
> [30220.038952] mwifiex_sdio mmc0:0001:1: last_cmd_act: 00 d2 00 00 00 00 01 00 01 00
> [30220.046469] mwifiex_sdio mmc0:0001:1: last_cmd_resp_index = 1
> [30220.052240] mwifiex_sdio mmc0:0001:1: last_cmd_resp_id: d0 80 b2 80 b0 80 b0 80 b0 80
> [30220.060106] mwifiex_sdio mmc0:0001:1: last_event_index = 1
> [30220.065618] mwifiex_sdio mmc0:0001:1: last_event: 43 00 6a 00 55 00 55 00 37 00
> [30220.072959] mwifiex_sdio mmc0:0001:1: data_sent=1 cmd_sent=1
> [30220.078644] mwifiex_sdio mmc0:0001:1: ps_mode=0 ps_state=0
> [30220.084508] mwifiex_sdio mmc0:0001:1: info: _mwifiex_fw_dpc: unregister device

Also on the wireless page it seems like the driver doesn't recognize the radio2 interface anymore as it gives me "Generic"
![image](https://user-images.githubusercontent.com/10348930/86834013-27bf0180-c04f-11ea-9073-01ffa2868114.png)

And after the reboot everything go back normal
![image](https://user-images.githubusercontent.com/10348930/86834414-aa47c100-c04f-11ea-9acc-b86f6416a4f9.png)

Someone is facing this problem?

**Comment by jow-** [comment]
Not a LuCI issue, likely related to the proprietary mwlwifi driver.
