### ISSUE TITLE
ipv6 bug

### ISSUE THREAD

**Issue by 643406834** [openwrt/luci#4252]
environment：
![image](https://user-images.githubusercontent.com/39716940/87156846-e8631000-c2ef-11ea-907d-93e829cb4db7.png)

normal：
![image](https://user-images.githubusercontent.com/39716940/87156329-18f67a00-c2ef-11ea-80d3-1b054bbc7ffb.png)
have ipv6 

bug:
![image](https://user-images.githubusercontent.com/39716940/87156511-59ee8e80-c2ef-11ea-9c1d-42c261575ad2.png)
![image](https://user-images.githubusercontent.com/39716940/87156555-6bd03180-c2ef-11ea-94a7-62eee4dc1ef8.png)
Set up firewall，wait for 30 minute，ipv6 will be disappear

**Comment by jow-** [comment]
IPv6 requires ICMPv6 to function.
