### ISSUE TITLE
adblock How to add ip whitelist？

### ISSUE THREAD

**Issue by snakwu** [openwrt/luci#4254]
This is the local adblock whitelist to always allow certain (sub) domains.
Please note: add only one domain per line. Comments introduced with '#' are allowed - ip addresses, wildcards and regex are not.

#192.168.1.100

Is that so?

**Comment by dibdot** [comment]
what's your point actually?

**Comment by snakwu** [comment]
I want a local area network ip without going through abdlock

**Comment by dibdot** [comment]
This cannot be achieved by a whitelist entry. Configure a separate (adblock free) dnsmasq instance or an unfiltered external dns resolver like 1.1.1.1 or 8.8.8.8.
