### ISSUE TITLE
luci-mod-status: dmesg not found when showing kernel log

### ISSUE THREAD

**Issue by flipreverse** [openwrt/luci#4263]
Hi,
the "Kernel Log" tab in luci-mod-status does not work properly if you switch from the Busybox version of dmesg to the full fledged version. Error message: `Unable to load log data: Executable not found`
Since the path to dmesg is hardcoded in `/www/luci-static/resources/view/status/dmesg.js`, it is obvious why it fails.
The full fledged version of dmesg is located in `/usr/bin/dmesg`. `dmesg.js` expects the binary to be at `/bin/dmesg`.

Cheers,
Alex

**Comment by jow-** [comment]
Sounds like that should be fixed in OpenWrt via alternstives instead.

**Comment by flipreverse** [comment]
@jow- What does that mean? Who is responsible for that?
