### ISSUE TITLE
luci-app-firewall: Firewall status page doesnt load

### ISSUE THREAD

**Issue by albilu** [openwrt/luci#4294]
Environment:
Name OpenWrt
Modele TP-Link Archer C7 v5
Architecture Qualcomm Atheros QCA956X ver 1 rev 0
Firmware Version OpenWrt 19.07.3 r11063-85e04e9f46 / LuCI openwrt-19.07 branch git-20.204.30585-8750495
Kernel Version 4.14.180

Description:
Luci Firewall status stuck and doesnt load:
![Kazam_screenshot_00002](https://user-images.githubusercontent.com/35330562/88489089-75fe5b00-cf92-11ea-9e51-52e6ee7bc782.png)

**Comment by jow-** [comment]
Seems to be a client specific issue, in particular a flaky connection. Make sure your network is functioning properly, that you do not have any IP subnet conflicts, your connection is stable etc.

Also rule out any interfering browser addons, firewalls etc.
