### ISSUE TITLE
luci-app-sysupgrade: XHR request timed out => i Can not upload firmware file

### ISSUE THREAD

**Issue by albilu** [openwrt/luci#4298]
Environment:
Name OpenWrt
Modele TP-Link Archer C7 v5
Architecture Qualcomm Atheros QCA956X ver 1 rev 0
Firmware Version OpenWrt 19.07.3 r11063-85e04e9f46 / LuCI openwrt-19.07 branch git-20.204.30585-8750495
Kernel Version 4.14.180

Description:
Unable to load any firmware file getting XHR request timed out 
![Kazam_screenshot_00008](https://user-images.githubusercontent.com/35330562/88489332-fe313000-cf93-11ea-888a-d38a2e51f5b9.png)

**Comment by jow-** [comment]
Seems to be a client specific issue, in particular a flaky connection. Make sure your network is functioning properly, that you do not have any IP subnet conflicts, your connection is stable etc.

Also rule out any interfering browser addons, firewalls etc.

**Comment by erdoukki** [comment]
> Seems to be a client specific issue
I can confirm that with same behavior on 21.02.2 was resolved by restarting the browser !

**Comment by toboil-features** [comment]
Got this issue on openwrt-24.10.2 kernel, but openwrt-23.05.6 works fine. So, definitely some regression happened around this time.
Restart of browser didn't help. Reproducible on Chromium-based and Firefox browsers.

**Comment by tinkercnc** [comment]
Same issue with OpenWrt 21.02-SNAPSHOT r15812+1082-46b6ee7ffc / LuCI openwrt-21.02 branch git-22.335.71649-0ecaf74
on GL.iNet GL-MT6000.
Tried with different browsers.

**Comment by tinkercnc** [comment]
With this instructions it works.
https://openwrt.org/docs/guide-user/installation/sysupgrade.cli

:)

**Comment by toboil-features** [comment]
@jow- please, reopen the issue
