### ISSUE TITLE
rpcd-mod-luci: only reports active leases from one dnsmasq server

### ISSUE THREAD

**Issue by aaronjg** [openwrt/luci#4303]
If multiple dnsmasq servers are running, only the first lease file is opened by `lease_open` in `libs/rpcd-mod-luci/src/luci.c` will only open the first one that it finds, rather than opening all the lease files from all instances of dnsmasq to find all the dhcp leases that have been issued.

**Comment by socketbox** [comment]
Is this related to https://github.com/openwrt/luci/issues/911 ?

**Comment by aaronjg** [comment]
Wow. This is a really old issue. Yes, this issue is a duplicate of #911. It looks like it was never patched. 

How does P/R #4308 look to fix this?

**Comment by socketbox** [comment]
> How does P/R #4308 look to fix this?

Sorry, I haven't a clue. You might consider linking to the PR from that issue, or communicating with one of the three users in the associated thread.

**Comment by jow-** [comment]
Fixed via 0c7a33523
