### ISSUE TITLE
Make suggested IP editable in DHCP static reservation GUI

### ISSUE THREAD

**Issue by MagmaiKH** [openwrt/luci#4313]
It would be a lot more convenient to just edit the last digit of the IP than scroll to the bottom and type in the whole thing.

**Comment by jow-** [comment]
Such an input would be incompatible with networks using non-/24 masks.

**Comment by MagmaiKH** [comment]
No it's not; the masks are contiguous. Make the whole thing editable or make the digits that are partially masked editable.
You can check the entered data and reject it if it's outside the subnet.
