### ISSUE TITLE
Request: Bulk Update packages or multiselect

### ISSUE THREAD

**Issue by mohitgupta1918** [openwrt/luci#4320]
Hi 
It would be great if we could have an option to upgrade/update all packages or could multiselect to upgrade/update packages. It would really save a lot of effort and reduce friction.

**Comment by hnyman** [comment]
mass-upgrading installed packages is not encouraged.
The upgrade functionality in opkg is meant for upgrading individual packages (e.g. due to security fixes), but the intention is not to encourage for upgrading lots of installed packages.
