### ISSUE TITLE
luci-app-dockerman: Console Panel failure

### ISSUE THREAD

**Issue by zdz2019** [openwrt/luci#4321]
![Snipaste_2020-07-31_22-05-24](https://user-images.githubusercontent.com/50648881/89043105-95bec600-d37a-11ea-940e-240c63560bc8.png)

The command window cannot be displayed normally when the connect button is clicked.
No problem with the previous version.

@feckert

**Comment by feckert** [comment]
I am not quite happy how the ttyd of a docker container is configured and started here.
But for now the [fix](https://github.com/TDT-AG/luci/commit/0b8e768765ad0d6351e0363f208f80dcf17cc128) here should help to get it working again without ssl.

Please let me know if this fix your issue.
I have mention that this only works if you did not redirect any http to https in uhttpd

I'm working on how to do this properly via ssl and so secure connection.

**Comment by zdz2019** [comment]
I just tested your suggestion and it doesn't work, The page is always loading.

**Comment by feckert** [comment]
@zdz2019 did you real tested by last push version of this commit?
If this is what I hear, it could be that you have tested a previous version of the fix, where I forgot that `&` while executing the ttyd command.

**Comment by zdz2019** [comment]
I tested your commit 0b8e768765ad0d6351e0363f208f80dcf17cc128

**Comment by feckert** [comment]
I have update my P/R in the mean time of your test and that was not the final change.
Please try https://github.com/TDT-AG/luci/commit/c851bd2645e32eb3b7146069d5f9012f71b406a4

**Comment by zdz2019** [comment]
I test again,it worked well
