### ISSUE TITLE
Docker cannot be used

### ISSUE THREAD

**Issue by lloyd18** [openwrt/luci#4331]
![Snipaste_2020-08-04_14-51-26](https://user-images.githubusercontent.com/10294460/89262932-f5f78580-d662-11ea-8e97-956f44c3e491.png)

![Snipaste_2020-08-04_14-57-03](https://user-images.githubusercontent.com/10294460/89262941-f98b0c80-d662-11ea-83ee-6510a4f54bfe.png)

@feckert

**Comment by feckert** [comment]
You have to start first the docker service.
With `/etc/init.d/dockerd start`

**Comment by lloyd18** [comment]
> You have to start first the docker service.
> With `/etc/init.d/dockerd start`
> 
> The Service is default enabled.

I tried. It didn't work.
![1](https://user-images.githubusercontent.com/10294460/89263623-2d1a6680-d664-11ea-88d5-8d5622865bad.png)

**Comment by feckert** [comment]
Could you please show me your `/tmp/dockerd/daemon.json` and your `/etc/config/dockerd` and your running docker process with `ps|grep docker` ?

**Comment by lloyd18** [comment]
cat /tmp/dockerd/daemon.json

`{ "data-root": "\/opt\/docker\/", "log-level": "warn", "bip": "172.18.0.1\/24", "registry-mirrors": [ ], "hosts": [ ] }
`

cat /etc/config/dockerd

`
config globals 'globals'
	option data_root '/opt/docker/'
	option log_level 'warn'
	option hosts 'unix://var/run/docker.sock'
	option bip '172.18.0.1/24'
	option remote_endpoint '0'
`

ps|grep docker

` 9342 root      1096 S    grep docker
`

**Comment by feckert** [comment]
Could you please change the /etc/config/dockerd config option hosts to:
`list hosts 'unix:///var/run/docker.sock'`
I think this is the problem.

I have also staged the following [P/R ](https://github.com/TDT-AG/packages/commits/pr/20200804-docker-ce) in my repository and this [commit](https://github.com/TDT-AG/packages/commit/70ecc1a4f08a3a1f4d046e03c7d026edb22122c6) should fix your issue.

**Comment by lloyd18** [comment]
Thank you for your help. I merged your pull requests, and recompiled the firmware, but the problem still exists.
