### ISSUE TITLE
luci Statistics can't display collectd graphs infomation

### ISSUE THREAD

**Issue by angusding** [openwrt/luci#434]
I compiled Chaos Calmer r46542 on ar71xx, but no graphs found in statistics.
That's is configuration:
cat /etc/collectd.conf 
#
# OpenWrt Config file for collectd(1).
# Please read collectd.conf(5) for a list of options.
# ​http://collectd.org/
#
#Hostname "localhost"
#FQDNLookup true
BaseDir "/var/lib/collectd"
PIDFile "/var/run/collectd.pid"
#PluginDir "/usr/lib/collectd"
#TypesDB "/usr/share/collectd/types.db"
Interval 30
ReadThreads 2
#LoadPlugin syslog
#LoadPlugin logfile
#<Plugin syslog>
# LogLevel info
#</Plugin>
#<Plugin logfile>
# LogLevel info
# File STDOUT
# Timestamp true
#</Plugin>
LoadPlugin cpu
LoadPlugin df
LoadPlugin disk
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin network
#LoadPlugin ping
#LoadPlugin processes
#LoadPlugin rrdtool
#LoadPlugin serial
LoadPlugin wireless
#<Plugin df>
# FSType tmpfs
# IgnoreSelected true
# ReportByDevice false
# ReportReserved false
# ReportInodes false
#</Plugin>
#<Plugin disk>
# Disk "/[hs]d[a-f][0-9]?$/"
# IgnoreSelected false
#</Plugin>

#<Plugin interface>
# Interface "eth0"
# Interface "br-lan"
# IgnoreSelected false
#</Plugin>
<Plugin network>
# Server "ff18::efc0:4a42" "25826"
Server "239.192.74.66" "25826"
# Listen "ff18::efc0:4a42" "25826"
# Listen "239.192.74.66" "25826"
# TimeToLive "128"
# Forward false
# CacheFlush 1800
# ReportStats false
</Plugin>
#<Plugin ping>
# Host "host.foo.bar"
# Interval 1.0
# Timeout 0.9
# TTL 255
# SourceAddress "1.2.3.4"
# Device "eth0"
# MaxMissed -1
#</Plugin>
#<Plugin processes>
# Process "name"
#</Plugin>
#<Plugin rrdtool>
# DataDir "/var/lib/collectd/rrd"
# CacheTimeout 120
# CacheFlush 900
#</Plugin>
cat /etc/config/luci_statistics 
config statistics 'rrdtool'
option default_timespan '1hour'
option image_width '600'
option image_path '/tmp/rrdimg'
config statistics 'collectd'
option BaseDir '/var/run/collectd'
option Include '/etc/collectd/conf.d'
option PIDFile '/var/run/collectd.pid'
option PluginDir '/usr/lib/collectd'
option TypesDB '/usr/share/collectd/types.db'
option Interval '30'
option ReadThreads '2'
config statistics 'collectd_ping'
option enable '0'
option TTL '127'
option Interval '30'
option Hosts '127.0.0.1'
config statistics 'collectd_csv'
option enable '0'
option StoreRates '0'
option DataDir '/tmp'
config statistics 'collectd_df'
option enable '0'
option Devices '/dev/mtdblock/4'
option MountPoints '/jffs'
option FSTypes 'tmpfs'
option IgnoreSelected '0'
config statistics 'collectd_disk'
option enable '0'
option Disks 'hda1 hdb'
option IgnoreSelected '0'
config statistics 'collectd_dns'
option enable '0'
option Interfaces 'ffdhcp ff br-lan'
option IgnoreSources '127.0.0.1'
config statistics 'collectd_email'
option enable '0'
option SocketFile '/var/run/collectd/email.sock'
option SocketGroup 'nogroup'
config statistics 'collectd_exec'
option enable '0'
config statistics 'collectd_interface'
option enable '1'
option IgnoreSelected '0'
option Interfaces 'br-lan pppoe-wan'
config statistics 'collectd_iptables'
option enable '1'
config collectd_iptables_match
option table 'nat'
option chain 'luci_fw_postrouting'
option target 'MASQUERADE'
option source '192.168.1.0/24'
option outputif 'br-ff'
option name 'Verkehr LAN-Clients'
config collectd_iptables_match
option chain 'luci_fw_postrouting'
option table 'nat'
option target 'MASQUERADE'
option source '10.61.230.0/24'
option outputif 'br-ff'
option name 'Verkehr WLAN-Clients'
config statistics 'collectd_irq'
option enable '0'
option Irqs '2 3 4 7'
config statistics 'collectd_load'
option enable '1'
config statistics 'collectd_logfile'
option enable '0'
option LogLevel 'notice'
option File '/var/log/collectd.log'
option Timestamp '1'
config statistics 'collectd_netlink'
option enable '0'
option IgnoreSelected '0'
option VerboseInterfaces 'br-lan br-ff'
option QDiscs 'br-lan br-ff'
config statistics 'collectd_network'
option enable '0'
config statistics 'collectd_processes'
option enable '1'
option Processes 'uhttpd dnsmasq dropbear'
config statistics 'collectd_splash_leases'
option enable '1'
config statistics 'collectd_tcpconns'
option enable '1'
option ListeningPorts '0'
option LocalPorts '22 80'
config statistics 'collectd_unixsock'
option enable '0'
option SocketFile '/var/run/collectd/query.sock'
option SocketGroup 'nogroup'
config statistics 'collectd_cpu'
option enable '1'
config statistics 'collectd_rrdtool'
option enable '1'
option DataDir '/tmp/rrd'
option RRARows '100'
option RRASingle '1'
option RRATimespans '1hour 1day 1week 1month 1year'
config statistics 'collectd_memory'
option enable '1'
config statistics 'collectd_conntrack'
option enable '1'
config statistics 'collectd_olsrd'
option enable '1'
option Port '2006'
option Host '127.0.0.1'
config statistics 'collectd_iwinfo'
option enable '1'
list Interfaces 'wlan0'
list Interfaces 'wlan1'
option IgnoreSelected '0'
config statistics 'collectd_nut'
option enable '0'
option UPS 'myupsname'
config statistics 'collectd_uptime'
option enable '1'

**Comment by hnyman** [comment]
Too vague.
Statistics on ar71xx work for me both on trunk and on CC15.05 at r46741.
