### ISSUE TITLE
Disable openwrt luci auto refresh

### ISSUE THREAD

**Issue by mh4nx7net** [openwrt/luci#4348]
maybe it's trivial issues
but, idk where i can get the config for disable/ change refresh interval luci auto refresh persistently
whenever i have refresh luci webUI. it's autorefresh just come up again.

thanks for the attention's
`here what may look like`
![Screenshot from 2020-08-12 10-19-05](https://user-images.githubusercontent.com/33443311/89971518-a0842f80-dc85-11ea-97dc-138b680189e3.png)

`just trying to figure out what an any word that can be possible; LOL 🤣 `

![Screenshot from 2020-08-12 10-22-20](https://user-images.githubusercontent.com/33443311/89971610-f78a0480-dc85-11ea-8d68-f62bd55b4212.png)

**Comment by jow-** [comment]
This all happens in client side code. You would need to edit `luci.js` and modify the behaviour of the [`LuCI.poll` class](http://openwrt.github.io/luci/jsapi/LuCI.poll.html)

**Comment by mh4nx7net** [comment]
thanks, help alot
