### ISSUE TITLE
luci-app-vnstat does not display graphs for interfaces with a "_" in the name

### ISSUE THREAD

**Issue by mamarley** [openwrt/luci#435]
This is already fixed by https://github.com/openwrt/luci/commit/b1b0ba5ba96c0ed3375cd1bf1792bd1548a8fab1 in master but should also be backported to 15.05.

**Comment by hnyman** [comment]
Backported with https://github.com/openwrt/luci/commit/c595f3095bd53e458984e410e24bf4d81a976aea
