### ISSUE TITLE
luci-app-mwan3: Interfaces grid can become mis-aligned on MWAN3 interface status page

### ISSUE THREAD

**Issue by jamesmacwhite** [openwrt/luci#4352]
Depending on the content within each interface block, it can cause the alignment to be broken. I believe this could be due to the variable height on each grid block when the interface uptime changes every few seconds.

![image](https://user-images.githubusercontent.com/8067792/90112869-76477600-dd48-11ea-8bd7-c2efd3af761e.png)

Potentially a CSS tweak is needed, possibly increasing the width slightly or to set a fixed height to avoid it pushing a row further down.

**Comment by feckert** [comment]
I don't like the CSS thing. But it was like that when I took over the code. I tend to be more of a table virw. With the CSS we will always have problems, even if we fix it now. It may look different and destroy the view on another theme!
@jamesmacwhite If you like you can then convert this into a table?

**Comment by aaronjg** [comment]
What if we change the space after the colon to be a non-breaking space, or set a css-property to disable line wrapping?
