### ISSUE TITLE
How to view Active clients on the LAN in OpenWrt?

### ISSUE THREAD

**Issue by guilhermetb** [openwrt/luci#4356]
Hello, I would like help if possible.

I used DD-WRT for a long time and recently switched to OpenWRT.
How can I activate this feature that I am using as an example of the DD-WRT printscreen (Staus -> LAN -> Active Clients) in OpenWRT?

![db6b76ce15effb46a1b9b823af3b262e89ee9987](https://user-images.githubusercontent.com/29417098/90331988-5a81e100-df8f-11ea-8885-c36ea6e4436b.jpeg)

**Comment by guilhermetb** [comment]
192.168.1.1 - TL-WR1043ND v1 - OpenWrt 19.07.3 - XX:XX:XX:XX:7E:86
192.168.1.2 - TL-WA850RE - Repeater tplink - XX-XX-XX-XX-1D-79
![061a8ed17ce89183d4a7455af988e023d71cc065](https://user-images.githubusercontent.com/29417098/90332029-bea4a500-df8f-11ea-9ac2-5dfb25b0aff7.png)

**Comment by guilhermetb** [comment]
I would like information from only the hosts that are exchanging packets on the network at the moment and not the leases granted by dhcp.

Is there any way to install a package through opkg that gets the information below in real time as in dd-wrt?

Host | Ip | Mac | Interface | Cont. | Proportion [4096]

I will give an example of the feature that I miss in relation to DD-WRT, in it through the path "Status -> LAN"

What comes closest to this feature in OpenWRT is through the path "Status -> Realtime Graphs -> Traffic -> br-lan"

However in OpenWRT it does not show the ips and hosts that are using the network in real time.

Can I get this feature in OpenWRT?

![cb3bf51e6a83ffb829c04ea0d109a9c7b42caf96](https://user-images.githubusercontent.com/29417098/90332065-1d6a1e80-df90-11ea-89b1-0c477896304c.png)

**Comment by jow-** [comment]
This is not possible.

**Comment by guilhermetb** [comment]
> This is not possible.

why?
