### ISSUE TITLE
Insufficient permissions to read UCI configuration.

### ISSUE THREAD

**Issue by eliaspizarro** [openwrt/luci#4370]
Steps:
1
![image](https://user-images.githubusercontent.com/8431845/90614233-66acaf00-e1d8-11ea-8e8a-3e2e417ea5c7.png)

2
![image](https://user-images.githubusercontent.com/8431845/90614163-4ed52b00-e1d8-11ea-9b7e-7bce7176d0ae.png)

from fresh install 
![image](https://user-images.githubusercontent.com/8431845/90614345-8cd24f00-e1d8-11ea-9771-5d1c472602e6.png)

**Comment by noyidoit** [comment]
Is there any tutor or docs explained how to write `rpcd/acl.d/xxx.json` ?
My only workaround is revert the `map.html` to a old version, that's so uncivilized.

**Comment by n3gwg** [comment]
Has there been any movement on squashing this bug at all?
What ostensible workarounds have been tested thus far?

I read in a forum a patch was submitted but it was rejected and no explanation given as to why.

**Comment by stangri** [comment]
@n3gwg you may want to test @dibdot's fix: https://github.com/dibdot/luci/commit/d915425c01651f13ab7ba74a72ccbd229433a87b
