### ISSUE TITLE
cant make public access to a menu

### ISSUE THREAD

**Issue by davidea72** [openwrt/luci#4375]
hi , im using luci on owrt 19.07.3 , git-20.229.71287-57456a7
i want to grant access to a page using this method

https://openwrt.org/docs/guide-user/luci/statistics.chart.public

i made this a lot of time on owrt 18.06 with success

but now i have an unwanted behavior , the index page is replaced with my view page and i can't log in anymore

here the file i have placed in a fresh installed router, to reproduce the issue

https://gitlab.com/davidea/test-luci/-/tree/second

lastly, where i can find the documentation about the assign method i've used?

**Comment by jow-** [comment]
This is not supported anymore.
