### ISSUE TITLE
has no parent node

### ISSUE THREAD

**Issue by sundhhy** [openwrt/luci#4385]
在luci中增加了自己的接口，并用postman发送接口请求调试，出现了问题。

The page at 'admin/getting/scanwifi/' has no parent node so the access to this location has been denied.
This is a software bug, please report this message at https://github.com/openwrt/luci/issues
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:302: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:171: in function </usr/lib/lua/luci/dispatcher.lua:170>

**Comment by jow-** [comment]
The quoted path does not belong to any LuCI extension maintained here, so there is nothing we can help with. You need to talk to the author of `getting/scanwifi` to get this fixed.
