### ISSUE TITLE
how to use `. /lib/functions.sh` to load/generate uci configuration 

### ISSUE THREAD

**Issue by mh4nx7net** [openwrt/luci#4388]
i mean, what the right procedures to generate output uci configuration from /etc/config/myconf
right with /lib/function.sh

https://openwrt.org/docs/guide-developer/config-scripting
i have read this document again and again
but still dont know what the exact place for me to start began

in the case, like how can i generate each values of section name
e.g : `/etc/config/myconf`
```
config data
   option var1 'val1'
   option var2 'var2'
config data
   option var1 'val1'
   option var2 'var2'
```
like myconf above, how can i fetch value of autogenerated section name of `config data`
like `uci show myconf.data[*]` then will be output e.g : `cfg0216f4 cfg0316f4` 

how ?
thanks before

**Comment by jow-** [comment]
This is covered in the https://openwrt.org/docs/guide-developer/config-scripting#iterating_config_foreach section. I kindly ask you to please stop opening these kind of tickets here. This is not a support channel for OpenWrt development.
