### ISSUE TITLE
luci-app-mwan3: Check quality of link failure_loss and recovery_loss values do not match defaults in mwan3track

### ISSUE THREAD

**Issue by jamesmacwhite** [openwrt/luci#4389]
@feckert 

I was updating the documentation for mwan3 https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3 as I noticed the interface configuration was missing the check_quality configuration options, I then found the default values used for failure_loss and recovery_loss are mismatched in mwan3track and LuCI.

#### Default values mismatched between mwan3track and LuCI

Defaults used in mwan3track:

https://github.com/openwrt/packages/blob/master/net/mwan3/files/usr/sbin/mwan3track#L151-L152

Defaults in LuCI:

`failure_loss` defaults to 40 in mwan3track, default is 20 in LuCI:

* https://github.com/openwrt/luci/blob/master/applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua#L122

`recovery_loss` defaults to 10 in mwan3track, default is 5 in LuCi:

* https://github.com/openwrt/luci/blob/master/applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua#L143

Should LuCI be updated to be consistent? I guess it's not a major problem.

**Comment by aaronjg** [comment]
Yes. Luci should be updated to use the mwan3track defaults, and if the default is unset in /etc/mwan3/config, luci should not set it unless the user chooses a value.

**Comment by feckert** [comment]
@jamesmacwhite thanks for the hint.
I have fixed this in the last commit of luci-app-mwan3.

**Comment by jamesmacwhite** [comment]
@feckert Thanks. Documentation has been updated to match, as it was missing entirely from the interface configuration table.

https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3#interface_configuration

**Comment by aaronjg** [comment]
@feckert, I think even with this fix, luci will add the default value to mwan3 config if it has not been set. Is that the desired behavior? This seems non standard to me. For example the dnsmasq luci app leaves unset config options unset.

**Comment by feckert** [comment]
As long as we do not enable the option [check_quality ](https://github.com/openwrt/luci/blob/master/applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua#L104) then the depending values are not saved into the running configuration.
