### ISSUE TITLE
luci_statistics =>config wrong

### ISSUE THREAD

**Issue by miniminime** [openwrt/luci#439]
Hi,

I think this is wrong: option 'Include' '/etc/collectd/conf.d'
I think it should read: option 'Include' '/etc/collectd.conf' 

I am also not able to add/change values in the collectd.conf file (I wanted to add 1minute statistics...). It always gets overwritten, but that might be a shortcoming on my side.

Cheers

**Comment by mmunz** [comment]
No, this is Include is correct, additional collectd config files may be placed in /etc/collectd/conf.d/ directory. The reason why  /etc/collectd.conf is overwritten is that it is created by the /etc/init.d/luci_statistics init script. So either add your changes in /etc/config/luci_statistics or /etc/collectd/conf.d (untested by me, but i guess it works).

**Comment by miniminime** [comment]
Cool, many thanks for your reply!
