### ISSUE TITLE
luci-ssl: change the default SSL lib to wolfssl?

### ISSUE THREAD

**Issue by hnyman** [openwrt/luci#4395]
@jow- 

It seems to me that the main OpenWrt has now adopted wolfssl as the default SSL library since commit
https://github.com/openwrt/openwrt/commit/a14f5bb4bd263c21e103f13279d0c2ff03e48fe5

Should we now change also LuCI to use wolfssl be default instead of mbedtls ?

https://github.com/openwrt/luci/blob/5c1f36ceb5c8ccd76bd61e170dd42748d502ba0d/collections/luci-ssl/Makefile#L13

**Comment by hnyman** [comment]
Reference to OpenWrt PR
https://github.com/openwrt/openwrt/pull/3363
"Add px5g WolfSSL version"

**Comment by aparcar** [comment]
Related https://github.com/openwrt/luci/pull/4401

**Comment by hnyman** [comment]
Closing this, as aparcar did the PR #4401, where the issue can be handled.
