### ISSUE TITLE
luci-app-nextdns: Failed to set the 'innerHTML' property on 'Element' when using "Openwrt" theme.

### ISSUE THREAD

**Issue by cybrnook** [openwrt/luci#4423]
I am seeing a failure message when using the NextDNS Luci app in conjunction with the theme "Openwrt". This only appears to happen with bootstrap while material and openwrt-2020 seem to work fine.

This was tested using Chromium Edge Version 85.0.564.51 with no add-ons enabled.

Error Message: "Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document."

![image](https://user-images.githubusercontent.com/22136734/92645420-d0d5e280-f2b2-11ea-9c69-d9daf3243cb6.png)

**Comment by hnyman** [comment]
> with the default theme "Bootstrap".

But your screenshot is from the old OpenWrt theme...
![image](https://user-images.githubusercontent.com/7926856/92683136-c7905880-f33a-11ea-8ab4-d1f3cf5fa429.png)

The old OpenWrt theme uses "strict XHTML" , so it complains more about invalid/not-fully-standard HTML usage (even if the relaxed non-perfect syntax is casually handled by the browsers).

cc author @rs
