### ISSUE TITLE
Process list misses processes with large VSZ

### ISSUE THREAD

**Issue by dsheets** [openwrt/luci#4425]
Busybox `top` outputs an 'm' suffix (for MiB) if the byte size necessary is greater than 100000 KiB. See <https://github.com/brgl/busybox/blob/master/procps/top.c#L698>.

The luci regular expression that matches top output lines is at <https://github.com/openwrt/luci/blob/master/modules/luci-base/luasrc/sys.lua#L382>. Notably, this regex doesn't match a line with a VSZ field having an 'm' suffix.

**Comment by hnyman** [comment]
Sis you test which string would work?

`"^ *(%d+) +(%d+) +(%S.-%S) +([RSDZTW][<NW ][<N ]) +(%d+[m]) +(%d+%%) +(%d+%%) +(.+)"`  ????

**Comment by dsheets** [comment]
I have not yet investigated patching luci or any component of OpenWRT and I have very limited time to pursue OpenWRT/luci hacking. I am not familiar with the regex dialect in use here but I wonder if `[m]` will require one of the singleton set `{'m'}` to be present (i.e. will not match the non-'m' case)? Maybe `m?` would be appropriate?

**Comment by hnyman** [comment]
@jow- 
Would 
`^ *(%d+) +(%d+) +(%S.-%S) +([RSDZTW][<NW ][<N ]) +(%d+m*) +(%d+%%) +(%d+%%) +(.+)` ????
be ok ?

(not sure how that possible "m" should be written.  `m*`   or `[m]*`  or ???)

**Comment by jow-** [comment]
Something like `...(%dm?)...` should do. Question is whether there are other possible units. I suppose theoretically there could be `g` and `e` as well.
