### ISSUE TITLE
Openwrt autorefresh time change? 

### ISSUE THREAD

**Issue by kissmorning** [openwrt/luci#4427]
hello
I want to change the update interval to 1 second ( Openwrt Changes Pool status )
how can I do it?
![2020-09-10_20-36-59](https://user-images.githubusercontent.com/68402414/92797831-18479600-f3bb-11ea-87c2-ca5e1b4c7f09.png)
![2020-09-10_20-37-34](https://user-images.githubusercontent.com/68402414/92797836-1978c300-f3bb-11ea-9069-acab371239e3.png)

**Comment by feckert** [comment]
I think it was possible to configure this in the uci before we moved to Javascript but this was discarded or not ported.
In the source we can set this in the [source]( https://github.com/openwrt/luci/blob/09014e01ab570a7b73d6b3f5d2f1a88bf7a763b4/modules/luci-base/htdocs/luci-static/resources/luci.js#L973) for each poll.

**Comment by jow-** [comment]
As written above, this needs to be [changed in the code](https://github.com/openwrt/luci/blob/master/modules/luci-mod-status/htdocs/luci-static/resources/view/status/load.js#L15).

**Comment by kissmorning** [comment]
In which folder should I make this change? I'm using winscp

**Comment by kissmorning** [comment]
http://192.168.1.1/cgi-bin/luci/admin/status/overview

i need this website overview 1second setting
