### ISSUE TITLE
luci_statistics - dependency and module issues

### ISSUE THREAD

**Issue by miniminime** [openwrt/luci#443]
Hi,

I think there is an issue with dependencies during installation. Further, if you try to install additional modules like mod-sensors or mod-thermal, it doesn't work/show-up in luci.

![image](https://cloud.githubusercontent.com/assets/2270817/9324986/61ea06ba-458f-11e5-8576-85ce5a1f0332.png)

**Comment by jow-** [comment]
The plugin load messages are normal and mod-thermal is not supported in the gui.

**Comment by miniminime** [comment]
Any chance that it could get supported?

**Comment by itrankolov** [comment]
I have it working. Tell me where to send the modified files so you can add it?

**Comment by miniminime** [comment]
@jow- you are a strange maintainer, really. A lot of packages totally outdated and even if someone is offering you the solution you just don't seem to care...but I know the default answer, I'm doing this in my free time and voluntarily, blablabla.

**Comment by jow-** [comment]
@miniminime - I'd gladly accept PRs or patches implementing new plugins but I simply don't have the time to work on it, nor do I have a working test setup to try the thermal plugin. As for the question where to send the working solutions, that is already covered in this repos readme which links to https://github.com/openwrt/luci/blob/master/CONTRIBUTING.md

**Comment by miniminime** [comment]
@jow- call me impressed and I'm sorry for my previous very unfair and provoking comment
@itrankolov could you provide your solution?
