### ISSUE TITLE
https-dns-proxy not show in luci

### ISSUE THREAD

**Issue by hendysama** [openwrt/luci#4431]
help me how to fix... thx

/usr/lib/lua/luci/model/cbi/https-dns-proxy.lua:57: attempt to index local 'value' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/cbi/https-dns-proxy.lua:57: in function 'getProviderName'
	/usr/lib/lua/luci/model/cbi/https-dns-proxy.lua:98: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1340: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1023: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>
![Screenshot from 2020-09-12 06-53-18](https://user-images.githubusercontent.com/27440454/92981598-b83d1680-f4c4-11ea-8130-a55a23cc9abd.png)

**Comment by stangri** [comment]
I believe I need to fix ACL asap. I'll try to submit a patch this weekend.

**Comment by stangri** [comment]
It's not an ACL issue, that was fixed a while ago. Can you walk me thru exact steps how did you arrive to this issue? What is the OpenWrt version? How and where from did you install packages? Is the https-dns-proxy service installed/running?

**Comment by stangri** [comment]
@hendysama did you resolve this issue?

**Comment by stangri** [comment]
Closing due to lack of response.
