### ISSUE TITLE
wirelesss scan failed: iwinfo.scan ubus call failed with latest uhttpd

### ISSUE THREAD

**Issue by srdgame** [openwrt/luci#4464]
With latest uhttpd package (2020-09-18), the wireless scan failed in our MT7688 devices (ramps mt76x8). The original uhttpd (2020-08-05-212f8364) version works before.

The iwinfo.scan is using the nobatch=true flag when calling rpc.declare (luci/modules/luci-base/htdocs/luci-static/resources/network.js:83)

**Comment by thedyerman** [comment]
I can confirm this behavior on both TP-Link Archer C20 v5 (ramps mt76x8 - MediaTek MT7628AN ver:1 eco:2) and TP-Link TL-WR841N v13 (ramps mt76x8 - MediaTek MT7628AN ver:1 eco:2)
unable to scan in Luci for wireless devices. works fine in cli

**Comment by jow-** [comment]
Fixed via b17ec0926d9519da7d5cd22a60c05c93bcc8292c
