### ISSUE TITLE
luci-mod-system: LEDs configuration is not saved

### ISSUE THREAD

**Issue by feckert** [openwrt/luci#4478]
I noticed a problem in the led plugin when I wanted to write an additional application trigger for the LuCI, which also has a uci option named **iface** as another application trigger.

**trigger (multisim: not upstream):**

![multisim-iface](https://user-images.githubusercontent.com/553091/94439347-98823f80-01a0-11eb-962c-71a352b5488a.png)

LuCI code:

```
'use strict';
'require form';
'require tools.widgets as widgets';

return L.Class.extend({
        trigger: _("Multisim selection (hotplug: multisim)"),
        kernel: false,
        addFormOptions(s){
                var o;

                o = s.option(widgets.NetworkSelect, '_multisim-iface', _('Network'));
                o.ucioption = 'ifac';
                o.modalonly = true;
                o.noaliases = true;
                o.depends('trigger', 'multisim');
        }
});
```

The corresponding uci section if everything fits:

```
config led 'led_L1'
        option name 'L1'
        option sysfs 'apu3:green:2'
        option trigger 'multisim'
        option iface 'wwan'
```

**trigger (mwan3: should get upstream):**

![mwan3-iface](https://user-images.githubusercontent.com/553091/94439350-991ad600-01a0-11eb-80df-f0a43f369e55.png)

LuCI code:

```
'use strict';
'require form';
'require tools.widgets as widgets';

return L.Class.extend({
        trigger: _("Mwan3 interface status (hotplug: mwan3)"),
        kernel: false,
        addFormOptions(s){
                var o;

                o = s.option(widgets.NetworkSelect, '_mwan3-iface', _('Network'));
                o.ucioption = 'iface';
                o.modalonly = true;
                o.noaliases = true;
                o.depends('trigger', 'mwan3');
        }
});
```

The corresponding uci section if everything fits:

```
config led 'led_L1'
        option name 'L1'
        option sysfs 'apu3:green:2'
        option trigger 'mwan3'
        option iface 'wwan'
```

**Issue:**

The problem if I select a trigger and set an iface option, then this iface option is never saved, because the other trigger does not have the iface option set and deletes the option. So in the uci configuration no iface option is saved!

**Comment by jow-** [comment]
The old code had extra logic in the `.remove()` callbacks to avoid this very problem (see e.g. https://github.com/openwrt/luci/blob/0731f7e5e43f490c39e364e43988a59ee2be9576/modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js#L112)

You need to replicate this somehow, one possible approach would be to iterate all options, and for each option where name != ucioption add a .remove() callback which implements the required logic. Something like the untested code below:

```javascript
s.addModalOptions = function(s) {
	for (var i = 0; i < plugins.length; i++) {
		var plugin = plugins[i];
		plugin.form.addFormOptions(s);
	}

	// http://openwrt.github.io/luci/jsapi/LuCI.form.AbstractSection.html#getOption
	var opts = s.getOption();

	var removeIfNoneActive = function(original_remove_fn, section_id) {
		var isAnyActive = false;

		// check if any option targeting the same ucioption is active (has its dependencies fulfilled)
		for (var optname in opts) {
			if (opts[optname].ucioption != this.ucioption)
				continue;

			if (!opts[optname].isActive(section_id))
				continue;

			isAnyActive = true;
			break;
		}

		// no option covering this ucioption is active, remove value
		if (!isAnyActive)
			original_remove.call(this, section_id);
	};

	for (var optname in opts) {
		if (!opts[optname].ucioption || optname == opts[optname].ucioption)
			continue;

		opts[optname].remove = removeIfNoneActive.bind(opts[optname], opts[optname].remove);
	}
};
```
