### ISSUE TITLE
luci-app-samba4: Unexpected reply data format

### ISSUE THREAD

**Issue by kongfl888** [openwrt/luci#4479]
Look for help.

Just trying to modify an option and save & apply

![20200929124753](https://user-images.githubusercontent.com/6991229/94513866-64675700-0252-11eb-9473-e166d4937e40.jpg)

the config still is the initial.

![20200929124856](https://user-images.githubusercontent.com/6991229/94513973-a0022100-0252-11eb-921d-f649dbcf25d7.jpg)

--
luci:  git-20.267.56601-1da9df8
openwrt: snapshot

**Comment by kongfl888** [comment]
/$ opkg list-installed luci-base
luci-base - git-20.267.56601-1da9df8
/$ opkg list-installed uhttpd
uhttpd - 2020-09-18-47c34bd6-1

try commenting out option ubus_prefix '/ubus' in /etc/config/uhttpd, restart uhttpd, close and reopen the LuCI browser tab .

it work...
why?
@jow- 

but I have the same problem "XHR request timed out" #4470

**Comment by dibdot** [comment]
I can confirm this bug on latest snapshot and other input areas which are using fs.write functions like "Scheduled tasks" ...
![image](https://user-images.githubusercontent.com/8061346/94606651-1165c200-029b-11eb-996e-f732fffe906d.png)

**Comment by jow-** [comment]
It is most likely an uhttpd regression on the OpenWrt side.

**Comment by wevsty** [comment]
luci-app-adblock page blacklist 
The same problem can be found when saving.

**Comment by borkra** [comment]
It looks like this commit causing the issue:
https://git.openwrt.org/?p=project/uhttpd.git;a=commit;h=11723570af9cb7bd87842e79c85ee99530be9902

Reverting uhttpd to the 2020-08-05 version fixes the problem.

**Comment by kongfl888** [comment]
It works, thank you!
