### ISSUE TITLE
log_proto missing

### ISSUE THREAD

**Issue by andriej** [openwrt/luci#449]
There's a setting of log_proto missing in LuCI interface.
Users can't correctly set 'tcp' protocol without going into ssh settings (which is fully supported).

The other thing is, that 'hostname' setting isn't correctly used by logread init.d script.
There's a reading of parameter missing aswell as -h parameter missing in start-script, but I don't know if it's fully LuCI related so I posted it to OpenWRT ticket also: https://dev.openwrt.org/ticket/20385

**Comment by cshoredaniel** [comment]
No action for over a year; closing
