### ISSUE TITLE
SMART QUEUE MANAGEMENT a little issue

### ISSUE THREAD

**Issue by desigabri** [openwrt/luci#4493]
H, I'll be very fast:

I just to advise you that  this luci package has **inverted** input fields for 
Download speed  and Upload speed , there is the need to  invert the fields or the description in the main page

nice app thanks

**Comment by hnyman** [comment]
Looks quite ok to me. (Assuming that you have correctly set the wan interface for SQM.)

![image](https://user-images.githubusercontent.com/7926856/95126343-01e4ee00-075f-11eb-89db-b329d2bc8665.png)
