### ISSUE TITLE
luci-app-ddns: Time error

### ISSUE THREAD

**Issue by small-5** [openwrt/luci#4506]
The update time displayed by luci-app-ddns of the master branch is incorrect, which is inconsistent with the time displayed in the log file.
Version:git-20.280.43255-6483e80

**Comment by feckert** [comment]
You have to give us more information

**Comment by small-5** [comment]
The system time of my screenshot is 2020-10-08 20:13, but Last Update shows 2020-10-08 20:22.
![1](https://user-images.githubusercontent.com/61473216/95458187-69d84600-09a4-11eb-858d-23d60549ba8f.jpg)

**Comment by feckert** [comment]
That means the time on your windows is different then the time on your router.
Have you set an ntp server?

**Comment by small-5** [comment]
The router time is consistent with the windows time. The problem is not here, the time displayed by luci is not consistent with the updated time in the log file.

**Comment by castillofrancodamian** [comment]
I can attest that the same thing happens here. The time is wrong.

**Comment by Ansuel** [comment]
@feckert in theory the time from luci is taken directly from the script... If there is a bug it should be there. Did you found a way to reproduce this?

**Comment by jow-** [comment]
Maybe a numeric overflow?

**Comment by lorthirk** [comment]
I think that the timezone is calculated twice, somehow:

![Screenshot 2021-05-18 at 09 34 05](https://user-images.githubusercontent.com/8140139/118610656-4be58600-b7bc-11eb-9bdf-7372e7af97a8.png)

According to logs, last check happened at 09:25 and next one is due in 72 minutes, so at 10:37. I am GMT+1 (although with DST now, so it should be GMT+2).
