### ISSUE TITLE
"Use DNS servers advertised by peer" and new added dns servers option not saved after reboot

### ISSUE THREAD

**Issue by juanmafont** [openwrt/luci#4511]
Hi, I'm trying to modify option -> "Use DNS servers advertised by peer' on Lucy to wan1, using Network - Interfaces - Wan1 - edit, all ok, but won't survive router reboot. (like this another user said here -> https://whrl.pl/Rf0AX3)

I try to modify this changes through UCI, adding this parameters:

network.wan1.dns=1.1.1.1 1.0.0.1
network.wan1.peerdns=0

but when try commit changes, I got an error:
uci: I/O error

 How can these permanent modifications remain?

Using TP-Link TL-MR3420 v2 with latest rooter version GoldenOrb_2019-03-10

**Comment by jow-** [comment]
Sounds like your overlay filesystem is corrupted or mounted readonly somehow, not a LuCI issue.
