### ISSUE TITLE
luci-app-wireguard latest handshake calculation wrong

### ISSUE THREAD

**Issue by coelner** [openwrt/luci#4525]
I run `OpenWrt 19.07.4 r11208-ce6496d796 / LuCI openwrt-19.07 branch git-20.247.75781-0d0ab01`
The line from `wg show all dump`
`vpn0	{public key}	(none)	{public ip:port} {local ipv4,local ipv6} 1601203272	5550764	15053724	off`

and the correct print from wg:
`latest handshake: 1 minute, 20 seconds ago`

and the luci status page:
`Latest Handshake: Sun, 27 Sep 2020 10:45:13 GMT (over a day ago)`

I assume that it is not directly a problem of this app, more a problem with the 64bit timestamp at all. 
https://github.com/WireGuard/wireguard-tools/commit/a6e4ec487debf11785b3f82a8c821ae9b7356024

Maybe someone can proove that with the current master?

**Comment by jow-** [comment]
This seems to be solved in current versions.
