### ISSUE TITLE
luci-app-sqm: SQM can't find the interface

### ISSUE THREAD

**Issue by castiel652** [openwrt/luci#4539]
After updated to the new client side implementation the script can't start up anymore it just gives the following error in the system log
user.notice SQM: ERROR: wan does currently not exist, not even trying to start SQM on nothing.

And before the update it used to show the interface pppoe-wan which includes both WAN and WAN_6

Below are my Interface names and related SQM page
![image](https://user-images.githubusercontent.com/14009719/97101336-7b755980-16d7-11eb-9fcd-2694c6ad56b5.png)
![image](https://user-images.githubusercontent.com/14009719/97101353-9e077280-16d7-11eb-8a10-72bcebef6595.png)

**Comment by hnyman** [comment]
cc @tohojo @Ansuel
