### ISSUE TITLE
Error - "No related RPC reply" (with ssl nginx LuCI) - Raspberry Pi 4 snapshot

### ISSUE THREAD

**Issue by robcollins55** [openwrt/luci#4551]
Related to #3259 , the *"No related RPC reply"* error message in LuCI with SSL-Nginx has returned to the LuCI screen when logging into it with the browser.  Along with this error message, no LuCI functions are viewable or usable.  I fresh-install my own build of the snapshot once every week (using the officially supported OpenWrt builder system) and this issue has popped up with my latest install with today's r14793-9f1927173a snapshot (all fine previous to this), so I thought I better report it.  Things I have tried so far with no improvement/resolution:
- Restarting the browser (Firefox v82 64bit for Linux)
- Doing reinstall at ssh : `opkg update; opkg --autoremove remove luci-ssl-nginx; opkg install luci-ssl-nginx`
- Doing switch to nginx without ssl at ssh : `opkg update; opkg --autoremove remove luci-ssl-nginx; opkg install luci-nginx`
- I have also tried a reboot of the RPi4 router and doing so resulted in LuCI being inaccessible in the Firefox browser with a browser error *(Unable to connect - Firefox can’t establish a connection to the server at 192.168.1.1)*.  I then reinstalled LuCI nginx ssl packages using the opkg commands above.  Similar errors result on all other devices/browsers on the Lan whenever I restart the router which is normal in my experience for every snapshot I have used to date.  This is in fact a separate issue that I have not and am not raising here; I guess that will be sorted eventually when the RPi4 gets a stable build?

After all those unsuccessful actions with LuCI nginx (both with and without ssl), I switched to vanilla LuCI by doing at ssh : `opkg update; opkg --autoremove remove luci-ssl-nginx; opkg install luci`.  Everything worked after that with no *RPC reply* error in the browser.  That surely means that the problem is definitely tied to both LuCI nginx and LuCI ssl nginx?

Please be specific and spoon feed me eg what file is of interest if you want an error log as I am a relative noob with helping with bugs :smile: .

Using the OpenWrt builder package from https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2711/, my usual and current package lineup is as follows for building my image:
```console
$ make image PROFILE=rpi-4 PACKAGES="luci-ssl-nginx luci-app-acme acme ca-certificates php7-fastcgi uwsgi luci-theme-openwrt-2020 luci-app-statistics collectd-mod-thermal luci-app-sqm nano bash kmod-usb-net-asix kmod-usb-net-asix-ax88179 kmod-usb-net-cdc-ether kmod-usb-net-ipheth kmod-usb-net-kaweth kmod-usb-net-mcs7830 kmod-usb-net-pegasus kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 kmod-usb-net-sr9700 luci-app-wireguard wireguard-tools wireguard qrencode luci-app-samba4 luci-app-ddns luci-app-adblock arp-scan arp-scan-database netdiscover kmod-fs-exfat kmod-fs-ext4 kmod-fs-ntfs kmod-fuse kmod-usb-storage kmod-usb2 kmod-usb2-pci kmod-usb3 kmod-fs-autofs4 block-mount blockd" FILES=files/
```
The "files" I include as customised are merely a backup from the previous week's build from my router:
/etc/config/ :
ddns
dhcp
firewall
network
samba4
sqm
system
wireless
luci_statistics

/etc/samba/ :
smb.conf
smb.conf.template

/etc/ :
passwd

Any help/attention with this gratefully received :smile:

**Comment by anomeome** [comment]
Should be [fixed](https://github.com/openwrt/packages/pull/13751)

**Comment by robcollins55** [comment]
Thanks for prompt reply @anomeome that sounds awesome and thanks for the link..... I'll build another image next week based on the latest snapshot of that day and report back with yay/nay confirmation of my own experience.

**Comment by robcollins55** [comment]
This issue indeed appears to have been resolved as I was able to install nginx LuCI with no issues.  Closing issue.
