### ISSUE TITLE
Luci errors on master : RPC call to luci/getFeatures failed with error -32000: Object not found

### ISSUE THREAD

**Issue by curtdept** [openwrt/luci#4555]
Fresh master branch build, Luci system rpc seems broken

![Screenshot_20201031-004827_Chrome](https://user-images.githubusercontent.com/23644717/97773140-ef1dc900-1b12-11eb-9ba9-5fcbe10b13c0.jpg)

**Comment by hnyman** [comment]
I see the same with LuCI Master (git-20.304.73778-5a485f8) / OpenWrt SNAPSHOT r14809-37ef2197e6 


```
RPCError

RPC call to luci/getFeatures failed with error -32000: Object not found
  at handleCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:11:3)
```

or

```
RPCError
RPC call to luci/getFeatures failed with error -32000: Object not found
at handleCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:11:3)
at promise callback*parseCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:9:70)
at promise callback*call (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:5:110)
at declare/
```

And Firefox shows the exception/breakpoint as


> 
> Paused on exception
> RPCError: RPC call to luci/getFeatures failed with error -32000: Object not found at handleCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:11:3) at promise callback*parseCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:9:70) at promise callback*call (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:5:110) at declare/</< (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:23:320) at declare/< (https://192.168.1.1/luci-static/resources/rpc.js?v=git-20.304.73778-5a485f8:20:436) at probeSystemFeatures (https://192.168.1.1/luci-static/resources/luci.js?v=git-20.304.73778-5a485f8:188:162) at setupDOM (https://192.168.1.1/luci-static/resources/luci.js?v=git-20.304.73778-5a485f8:199:378) at promise callback*__init__ (https://192.168.1.1/luci-static/resources/luci.js?v=git-20.304.73778-5a485f8:152:362) at ClassConstructor (https://192.168.1.1/luci-static/resources/luci.js?v=git-20.304.73778-5a485f8:11:78) at (https://192.168.1.1/cgi-bin/luci:38:6)

**Comment by ptpt52** [comment]
same problem.

**Comment by peterwillcn** [comment]
same problem.
![Screen Shot 2020-11-01 at 12 19 26 AM](https://user-images.githubusercontent.com/323794/97784222-eb07af00-1bd7-11eb-8897-093c8d9915ee.png)

**Comment by garypang13** [comment]
same problem.
![image](https://user-images.githubusercontent.com/48883331/97784433-88afae00-1bd9-11eb-99f9-81a069916587.png)

**Comment by MartB** [comment]
Can confirm this is indeed broken.

**Comment by curtdept** [comment]
Rofl missing quotation mark, someone didn't run test.

**Comment by jow-** [comment]
Fixed by #4560

**Comment by lynxthecat** [comment]
This is back, right(?):

RPC call to luci.wireguard/getWgInstances failed with error -32000: Object not found
  at ClassConstructor.handleCallReply (http://192.168.1.1/luci-static/resources/rpc.js?v=git-21.226.86205-376af36:11:3)

![image](https://user-images.githubusercontent.com/10721999/134768976-aa0b1b67-2425-4e0d-8342-91cc7af95d76.png)

**Comment by teqlee** [comment]
@lynxthecat 
Confirm issue come back
`RPCError
RPC call to luci.wireguard/getWgInstances failed with error -32000: Object not found
  at ClassConstructor.handleCallReply (https://192.168.16.1/luci-static/resources/rpc.js?v=git-21.267.65414-1d9067b:11:3)`

**Comment by lynxthecat** [comment]
So this needs to be reopened, right? Let us know what extra info if any needed!

**Comment by M95D** [comment]
I think this issue needs to be re-open.
I get the getFeatures error if busybox symlinks are installed in /bin instead of /usr/sbin. The error is caused by missing /usr/bin/env

**Comment by rendiix** [comment]
same problem
![Screenshot_20221110-203709407 (1)](https://user-images.githubusercontent.com/16639978/201106116-f3beb346-eacb-49fe-adc6-34ca0bffc52c.jpg)

**Comment by lynxthecat** [comment]
Actually I have a slight suspicion this could be related to just needing to clean browser cache. Did you try that @rendiix?

**Comment by A1EF** [comment]
I have same error on Xiaomi Redmi AX6S.
![Image](https://github.com/user-attachments/assets/b311bf21-29ee-4b7a-b3c9-d216f10fa86c)

**Comment by systemcrash** [comment]
I recommend clearing your caches or building a new image, because this problem is not endemic to the firmware or code. Probably a cache thing (since you upgraded packages, which can on occasion, break your luci setup). A possible fix is to uninstall luci and reinstall it.

**Comment by jfbvm** [comment]
I need help on this. What exactly is the command to rebuild using image builder?
I already cleared my browser cache, but the error persists.
I'm using the command below, what I need to add to the PACKAGES to make it work?
I'm using OpenWrt version 24.10.5

Command used to build image:
```bash
make image PROFILE="rpi-3" PACKAGES="\
nano \
uhttpd uhttpd-mod-ubus \
rpcd rpcd-mod-luci \
luci luci-ssl luci-mod-network luci-mod-status luci-app-firewall luci-app-opkg \
luci-base luci-mod-rpc luci-mod-network luci-mod-status \
wpad-openssl -wpad-basic-mbedtls \
iwinfo \
kmod-usb-core kmod-usb2 kmod-usb-dwc2 kmod-usb-ohci kmod-usb-ehci \
kmod-usb-net-cdc-ether kmod-usb-net-qmi-wwan kmod-usb-net-cdc-mbim \
kmod-usb-serial kmod-usb-serial-option usb-modeswitch \
uqmi umbim ppp chat \
luci-proto-qmi luci-proto-mbim \
mwan3 luci-app-mwan3 \
sqm-scripts luci-app-sqm kmod-ifb kmod-sched-cake \
ca-bundle ca-certificates \
curl wget-ssl \
tcpdump iperf3"
```

**Comment by systemcrash** [comment]
https://firmware-selector.openwrt.org/
