### ISSUE TITLE
Powered by LuCI Master (git-20.117.60969-420c61a) / OpenWrt R20.5.9 / Mask K3.200516  的密码是多少？

### ISSUE THREAD

**Issue by robin20200222** [openwrt/luci#4556]
Powered by LuCI Master (git-20.117.60969-420c61a) / OpenWrt R20.5.9 / Mask K3.200516

这个版本的密码是多少，感恩！

**Comment by robin20200222** [comment]
在线等，急用

**Comment by hnyman** [comment]
English only, please.

And there is no normal version like "OpenWrt R20.5.9 / Mask K3.200516"
