### ISSUE TITLE
Powered by LuCI Master (git-20.117.60969-420c61a) / OpenWrt R20.5.9 / Mask K3.200516

### ISSUE THREAD

**Issue by robin20200222** [openwrt/luci#4557]
The user name is root, please tell me the password. Thank you.
The secret IP is 192.168.2.1
Urgent, urgent online, etc.

**Comment by hnyman** [comment]
Default IP is 192.168.1.1
And default password for "root" is empty.

You are likely using some tailored private build with modified defaults. Please ask them.

In any case, your question is not a bug

**Comment by robin20200222** [comment]
ooooooo
