### ISSUE TITLE
feature: add channel scan for wifi

### ISSUE THREAD

**Issue by Ansuel** [openwrt/luci#4572]
I notice that with the wifi scanning feature we have all the data to create a graph with that show the wifi channel utilization. (channel and wifi rssi)
So i'm asking @jow- 
Do you think this feature would be useful? I would try to use the same code we use for the traffic graph so no external libs needed.

**Comment by evelikov** [comment]
Fwiw I would greatly appreciate such a feature.

At the moment, one has to the wlan to monitor mode (via aircrack-ng) and use `iwlist scan` to get said data. Something which I had to do just a few moments ago :-)

**Comment by Ansuel** [comment]
Actually this is already possibile using the WiFi join feature. I'm
searching a way to get channel width.

Il Gio 5 Nov 2020, 22:40 Emil Velikov <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
Some WIP
![Immagine 2020-11-09 202627](https://user-images.githubusercontent.com/20289090/98587141-0787a380-22ca-11eb-8f7e-1aa3ceb13d34.png)

**Comment by Ansuel** [comment]
The ""Final"" Result.
A patch is needed for this to work. Now i just need to test this and polish the code. (improve readability since it's very compact 50-60 line)
![Immagine 2020-11-09 202627](https://user-images.githubusercontent.com/20289090/99209677-0079fd00-27c4-11eb-893a-a17d716e728a.png)
![Immagine 2020-11-16 042626](https://user-images.githubusercontent.com/20289090/99209681-01ab2a00-27c4-11eb-9d20-c95f67da3df2.png)

**Comment by jow-** [comment]
Very nice, great work!

**Comment by Ansuel** [comment]
@jow- Where should i put this? Currently is integrated in the wifi scan... Is that right? Was thinking of moving it to the stats page

**Comment by hnyman** [comment]
Statistics sounds wrong,
"scan" is better. 

Maybe create a "channel analysis" button next to "scan" in network/wireless?

**Comment by Ansuel** [comment]
With statistics i mean the normal stats page, the one that show traffic in the interfacae...

Do you think a new button with Channel Analysis that show the graph + wifi (with info related to channel is more appropriate?)

**Comment by hnyman** [comment]
>  With statistics i mean the normal stats page, the one that show traffic in the interfacae...

I got lost with that reference.
Which page you mean?

I see traffic count only on https://192.168.1.1/cgi-bin/luci/admin/network/network that does not have wireless.

Neither 
https://192.168.1.1/cgi-bin/luci/admin/status/overview
or
https://192.168.1.1/cgi-bin/luci/admin/network/wireless
has traffic counters for wifi.

I proposed 
https://192.168.1.1/cgi-bin/luci/admin/network/wireless

Or possibly it might additionally be a new page in main "Status" menu.

**Comment by Ansuel** [comment]
> Or possibly it might additionally be a new page in main "Status" menu.

I was referring to the Realtime graph page in the status menu. A new page in the status menu is also a good idea.

**Comment by hnyman** [comment]
I close this as the discussion can continue in PR #4598
