### ISSUE TITLE
Luci java error on current snapshot

### ISSUE THREAD

**Issue by sages** [openwrt/luci#4576]
With current snapshot LuCI Master (git-20.305.72436-6e4e132) / OpenWrt SNAPSHOT r14856-be09c5a3cd using imagebuilder and using current version of Firefox to view.

On Archer C7v5 and WR842nv1

Following error message on Overview ( and numerous other pages) Luci web page

```
SyntaxError

expected expression, got ')'
  in http://192.168.128.254/luci-static/resources/protocol/grev6.js?v=git-20.305.72436-6e4e132:2
  at compileClass/< (http://192.168.128.254/luci-static/resources/luci.js?v=git-20.305.72436-6e4e132:180:29)
```

**Comment by feckert** [comment]
Already fixed https://github.com/openwrt/luci/commit/37f97b7859c8a601024ae6570e9d481c50ee8897
