### ISSUE TITLE
QMI protocol: introduce option "Use DNS servers advertised by peer"

### ISSUE THREAD

**Issue by Nowaker** [openwrt/luci#4577]
It's not possible to request that "QMI Cellular" interface does not modify /etc/resolv.conf when it gets an IP:

![image](https://user-images.githubusercontent.com/611746/98338093-3ef70700-1fcf-11eb-9613-8709f0d178a4.png)

Other interfaces have a way to enforce that. For example, a generic interface "DHCP" has this option:

![image](https://user-images.githubusercontent.com/611746/98338041-2555bf80-1fcf-11eb-837e-aec017981ca6.png)

**Comment by feckert** [comment]
This is supported by the proto https://github.com/openwrt/openwrt/blob/master/package/network/utils/uqmi/files/lib/netifd/proto/qmi.sh#L330

So we only have to add theme to luci
