### ISSUE TITLE
[luci-mod-status] CONFIG_NF_CONNTRACK_PROCFS being obsoleted in next LTS Kernel

### ISSUE THREAD

**Issue by n8v8R** [openwrt/luci#4580]
If understood correctly `admin/status/realtime/connections` leverages https://github.com/openwrt/luci/blob/5220d4f373ae70037bdf8f4e1934ec9631912e67/modules/luci-mod-status/src/luci-bwc.c#L431

however the next designated LTS Kernel 5.10 obsoletes `CONFIG_NF_CONNTRACK_PROCFS`

![Screenshot 2020-11-06 134114](https://user-images.githubusercontent.com/13611490/98367657-4bfb1100-2036-11eb-9bbb-483644dafae6.jpg)

As a consequence there is no realtime graph for connections

![Screenshot 2020-11-06 134237](https://user-images.githubusercontent.com/13611490/98367479-00486780-2036-11eb-9242-71c0842619e8.jpg)

**Comment by feckert** [comment]
What are the options instead of getting this information from the system?

**Comment by n8v8R** [comment]
Whilst it is obsoleting the kconfig is still present and may still work (did not compile/test with that option)

Else what `conntrack` provides http://conntrack-tools.netfilter.org/conntrack.html

e.g. events with `conntrack -E`

* `conntrack -L` > dumps the connection tracking table in /proc/net/ip_conntrack format 
* `conntrack -L -o extended` > dumps the connection tracking table in /proc/net/nf_conntrack format
* `conntrack -L -o xml` > dumps the connection tracking table in XML 

But that would require the _conntrack package_ as dependency

**Comment by n8v8R** [comment]
Whilst the code is **considered** obsolete it has not been removed yet and still works with the kconfig enabled, thus perhaps nothing to be concerned about for now.

**Comment by fengyang0317** [comment]
Is is possible swith to `conntrack` now? I am trying to use lxc container to run openwrt. `/proc/net/nf_conntrack` is not available.
