### ISSUE TITLE
Luci-app-aria2 very simple fix need

### ISSUE THREAD

**Issue by eduardo010174** [openwrt/luci#4583]
I found bug in luci-app-aria2
I add extra setting but not its write in final file.
in this case add dscp=8

in section list of config, the site write in file in /etc/config/aria2
list extra_setting 'dscp=8'
and this is not write in final config aria2 file.

but this correct is
list extra_settings 'dscp=8'
after i change this config is writted in config aria2 file.

but it's not visible on site.
its it's a simple fix but i don't think how to fix.

**Comment by jow-** [comment]
Already fixed in 6709d3a355e6723b8a2ae4f5354c3e917d1b7ac8 - cherry picked to openwrt-19.07
