### ISSUE TITLE
Tab key not switch directly to confirmation field from password field

### ISSUE THREAD

**Issue by olekstomek** [openwrt/luci#4585]
Tested in verion 19.07.0 and 19.07.2 but probably it's in all verions 19.07.x
 - Steps to reproduce
1. Go to router password in settings.
2. Input password in "Password"
3. Input tab key to switch to "Confirmation"
4. Focus is not in input "Confirmation" (in previous version e.g. 18.06.7 tab key switch directly to input "Confirmation" - one press tab instead of two press)
I added gif to show this impediment.

![password_tab_focus](https://user-images.githubusercontent.com/26818304/98441505-0e15ef80-20ff-11eb-8289-20beda9b6af7.gif)

**Comment by jow-** [comment]
Yes, because the first tab stroke focuses the reveal button. Works as intended.
