### ISSUE TITLE
rpcd-mod-luci: luci hangs loading overview page

### ISSUE THREAD

**Issue by aaronjg** [openwrt/luci#4586]
I updated rpcd-mod-luci with 0c7a33523027e2241d4ff93dc987c97ce233912e, and now the system hangs loading the status page.

rpcd-mod-luci also needs a version bump with the change

cc @jow-

**Comment by jow-** [comment]
Cannot reproduce it here.

**Comment by aaronjg** [comment]
`ubus call luci-rpc getDHCPLeases` worked fine, but something else was causing it to segfault when loading the overview page.

 I just rebuilt it from the SDK rather than installing from the overnight build, and all appears to be working now.
