### ISSUE TITLE
luci-app-adblock: Overview tab hangs

### ISSUE THREAD

**Issue by Christian-Gibbons** [openwrt/luci#4587]
Overview tab never loads and reports a TypeError: "result[0].trim is not a function"

package version git-20.311.84795-abf6950-1

**Comment by Christian-Gibbons** [comment]
Error eventually went away.  Perhaps 'result' was empty over time was filled with something?

**Comment by dibdot** [comment]
Typically an update/caching issue - see #3931 for reference.
