### ISSUE TITLE
Luci front page auto-refresh is CPU heavy for the router

### ISSUE THREAD

**Issue by hnyman** [openwrt/luci#459]
I have felt some sluggishness on the front page every now and then. I have also noticed some forum discussion on "slow Luci" ( https://forum.openwrt.org/viewtopic.php?id=59113 ).

I have also noticed that if the front page is left open on the browser with the default setting "auto refresh on", the CPU load in statistics grows surprisingly high. Even in my rather powerful WNDR3700, the CPU load goes over 20% just by having that front page open in browser...

Below is a graph highlighting this, tested with both Firefox and IE.
- Router is otherwise practically idle when I open the Luci front page and leave that page open. CPU load shoots to 20-25%, while the page updated dynamic content every 5 secs. 
- When moving to another page, the load immediately stops. 
- My front page has three XHR sections: main, DDND and UPNP. So I further tested uninstalling the Luci DDNS and MiniUPNP components, as their data is updated dynamically too. That cut the CPU load into half. So, the main Luci front page already causes rather high load by itself, but having three auto-refreshing sections really kills the CPU.

![cpuloadgraph](https://cloud.githubusercontent.com/assets/7926856/9578347/a9ebce3c-4ff1-11e5-9a0a-98838b77eea8.png)

When profiling the front page with browser tools, the updating looks heavy. 
- When all three components are enabled, even the main data update takes almost 1.2 seconds (every 5 seconds). And there are 2 requests per cycle, main, DDNS and UPNP.
  ![frontpagecapture](https://cloud.githubusercontent.com/assets/7926856/9578401/5c9a4220-4ff2-11e5-95ed-741e3d2deddb.PNG)
- If DDNS and UPNP components are disabled, the update duration decreases to 0.5s. So, having three updating components, slows things downs significantly
  ![frontpagelow_no_ddns_upnp](https://cloud.githubusercontent.com/assets/7926856/9578402/5e367dba-4ff2-11e5-8f08-356c8c10fe3d.PNG)

I have not yet tried to debug which section is the culprit, or if there is something too iterative in the lua script.

Jow, 
would it be ok to decrease the XHR update frequency from 5 secs to 10 secs?
Or any ideas about further debugging?

EDIT:
Increasing update frequency to 15s naturally cuts the CPU utilization to a third, just as expected:
![cpuload2graph](https://cloud.githubusercontent.com/assets/7926856/9578739/3257e1ae-4ff5-11e5-8f11-ea48708422a5.png)

**Comment by jow-** [comment]
Yes, I'm fine with increasing the timeout.

**Comment by chris5560** [comment]
For luci-app-ddns I see no problem to increase the poll time.
If you find a good poll interval I'll implement it in next version.
I'm currently working on an extension of ddns-scripts/luci-app-ddns.

Christian

**Comment by gwlim** [comment]
Can you compared it to BB?
I don't think Poll Interval is the root cause.

**Comment by thesabbir** [comment]
A system/administration setting perhaps? Where we can specify the intervals.
As #483 wants to increase it.

**Comment by hnyman** [comment]
The real-time graph poll interval mentioned in #483 is mostly a separate issue, as that 3 seconds  concerns only the update frequency of the four graphs in Status--> Realtime Graphs. If there would be a config option for the refresh intervals, there should probably be two settings: one for generic status pages, one for dedicated real-time info pages like that "realtime graphs".

And yes, the poll interval is not the root cause, but a small interval increases the visibility of the underlying problem: something in the polling mechanism causes high load.

**Comment by jow-** [comment]
This was likely caused by inefficient status page plugins.
