### ISSUE TITLE
resolve_conffiles: Existing conffile [ luci-proto-sstp]

### ISSUE THREAD

**Issue by predators46** [openwrt/luci#4591]
`  * resolve_conffiles: Existing conffile /home/azurevps46/sp/sp/build_dir/target-mipsel_24kc_musl/root-ramips/etc/ppp/chap-secrets is different from the conffile in the new package. The new conffile will be placed at /home/azurevps46/sp/sp/build_dir/target-mipsel_24kc_musl/root-ramips/etc/ppp/chap-secrets-opkg.  `

**Comment by hnyman** [comment]
You simply have a somewhat changed older config file, which was not overwritten forcibly, and you were notified about that. That usually comes when you install a package to the router with opkg, and here it looks like this surfaced in th ebuild system. That is the streange part.

In any case, this would not be about LuCI GUI, so this is wrong bug tracker.
