### ISSUE TITLE
luci-app-opkg: Add option to upgrade all installed packages at once [FEATURE REQUEST]

### ISSUE THREAD

**Issue by krjdev** [openwrt/luci#4602]
Hi,

Is it possible to add an option (e.g. button) in the web-interface under the tab "Updates" to upgrade all packages at once if there are updates for the specific installed packages available?

Thanks in advance.

**Comment by jow-** [comment]
This functionality is intentionally missing as mass-upgrading packages is discouraged and not reliable yet in OpenWrt. Besides the potential problem of filling up all available overlay space, the opkg package manager does not correctly handle all upgrade situations.

This might change in the future but as of now it is too risky to implement.
