### ISSUE TITLE
modal dialogs should be closeable via ESC key.

### ISSUE THREAD

**Issue by nerdoc** [openwrt/luci#4609]
All dialogs in luci, at least the ones which are modal, should be closeable via ESC, for a better user experience.
![grafik](https://user-images.githubusercontent.com/2955584/99807023-280ff300-2b3f-11eb-9a3a-85d3f4f08b76.png)

Especially when you are upgrading packages via luci-opkg, it's tedious to always find the (only) "Dismiss" button, which is always on another point on the y axis... ;-)

This is no bug, but an feature request/enhancement, which could be done very easily (depending on the codebase of dialogs) - I don't know the internals, am just a user.

And if so, maybe even use something like Enter for the default button (Apply, Ok etc)? This is a bit more complicated, as some elements could use that key as well.

**Comment by jow-** [comment]
This cannot be easily implemented in a generic manner since it is not clear which action `esc` should perform in case there's multiple actions available.

Moving this to to utopia in case osmeone is willing to work on it.

**Comment by tapper82** [comment]
https://edenspiekermann.github.io/a11y-dialog/example/
https://www.w3.org/TR/wai-aria-practices/#dialog_modal

**Comment by tapper82** [comment]
Being able to close the modal with the esk key would be better.

**Comment by systemcrash** [comment]
This one bugs the shit out of me.

**Comment by systemcrash** [comment]
If Dismiss is the only button of a reasonably in-focus form, how about mashing ENTER or whichever key to accept?

**Comment by tapper82** [comment]
This is a bug, an A11y one.
