### ISSUE TITLE
Cannot save changes to time because of blank Design field

### ISSUE THREAD

**Issue by socketbox** [openwrt/luci#4624]
1. Logged in to router because devices that should have been on the network were reporting that no network was available.
  2. Saw that the time, in LuCi interface, was off by a month.
  3. Corrected time and went to save.
  4. Cannot save because the "Design" field in the "Language and Style" tab is empty.
  5. Attempt to enter _any_ value into said field. No joy.
  6. Reboot router like hopeful idiot.
  7. Try again. Fail.
  8. Look for information on this aspect of the web UI online. Hard to disambiguate results having to do with "design" at a lower level.
  
Firmware version: OpenWrt 19.07.3 r11063-85e04e9f46 / LuCI openwrt-19.07 branch git-20.242.67031-c3a0c60

![flameshot-2020-11-27-19-17-59](https://user-images.githubusercontent.com/1593835/100489905-59f7fb00-30e5-11eb-9035-e1ac5e53d998.png)

![flameshot-2020-11-27-19-28-43](https://user-images.githubusercontent.com/1593835/100490108-cb847900-30e6-11eb-9f0f-b267f9938f9a.png)

**Comment by hnyman** [comment]
That field is supposed to contain the selection of available themes..
There should be a section in /etc/config/luci like this:
```
config internal 'themes'
        option Bootstrap '/luci-static/bootstrap'
```
Bootstrap is the default theme, but you might also have others installed.

![image](https://user-images.githubusercontent.com/7926856/100495667-68cac600-3156-11eb-8d1f-ce1426c9848b.png)

**Comment by jow-** [comment]
This is caused by a corrupt /etc/config/luci. Does not happen with a stock image or after installing any theme.
