### ISSUE TITLE
WPS button appears in another interface

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4625]
The button is enabled in the guest interface (Invitados), but appears in the WDS interface.
![Captura de pantalla 2020-11-28 120821](https://user-images.githubusercontent.com/47670442/100518956-a1c56380-3173-11eb-9b32-d64e16ece6f8.png)

**Comment by Ansuel** [comment]
@castillofrancodamian I need some info to fix this.

Can you confirm that you have WPS disabled on all the other interface?

**Comment by castillofrancodamian** [comment]
@Ansuel So is. Only enabled in guests.
