### ISSUE TITLE
banip: bug with luci-theme-openwrt-2020

### ISSUE THREAD

**Issue by olimpiumarius** [openwrt/luci#4627]
Hello all,
This tab is not working in this 
![x](https://user-images.githubusercontent.com/34411358/100530010-9adf3500-31f5-11eb-9cbe-677847ff1e20.PNG)
![Capture](https://user-images.githubusercontent.com/34411358/100530012-9c106200-31f5-11eb-91a2-95410772bcf2.PNG)

**Comment by hnyman** [comment]
You are apparently talking about a specific app, banip

cc author @dibdot

**Comment by hnyman** [comment]
And you are apparently talking about the private derivative fork "swrt", instead of the main OpenWrt.

**Comment by dibdot** [comment]
Well, I "think" this is an CSS issue of this theme with legacy apps. Anyway, currently I'm working on a JS version of this app, therefore I do not plan to do any changes on this old legacy code.

**Comment by olimpiumarius** [comment]
This issue persists only on the new OpenWrt theme, too bad no one wants to solve this problem!
![Capture PNG6](https://user-images.githubusercontent.com/34411358/103451669-821fde80-4ccf-11eb-8597-bd85addb39df.PNG)
![Capture PNG5](https://user-images.githubusercontent.com/34411358/103451670-82b87500-4ccf-11eb-843b-7723f3dd2b4d.PNG)
![Capture PNG4](https://user-images.githubusercontent.com/34411358/103451671-82b87500-4ccf-11eb-98cb-89be6a7d4593.PNG)
![Capture PNG3](https://user-images.githubusercontent.com/34411358/103451672-83510b80-4ccf-11eb-890d-4cb2aa1b46c9.PNG)
![Capture PNG2](https://user-images.githubusercontent.com/34411358/103451673-83510b80-4ccf-11eb-9a39-fcdbc380ca89.PNG)
![Capture PNG1](https://user-images.githubusercontent.com/34411358/103451674-83510b80-4ccf-11eb-9084-2a3721d06ecb.PNG)
![Capture](https://user-images.githubusercontent.com/34411358/103451676-83e9a200-4ccf-11eb-871c-40ed402c8613.PNG)

**Comment by dibdot** [comment]
will be fixed with #4762
