### ISSUE TITLE
Issue: Stuck in loading after login

### ISSUE THREAD

**Issue by Crimlock** [openwrt/luci#4636]
Hi! I’m currently following an education in cyber security and have an assignment to emulate a firmware. I chose the tplink archer ax50, which uses openwrt. I use a donor image which I emulate with qemu and in the image I copied the firmware. I mount some dives and chroot into the firmware. I can run uhttpd, but when I open the browser and login with a password, I keep getting stuck at a loading screen. I think this has something to do with luci :-) the webserver is trying to load index.html and the screen tries to open at the settings tab....

Any idea how I can solve this issue?

**Comment by jow-** [comment]
I suggest to use the OpenWrt forum or IRC channel for such support questions. There are far too many possible reasons and your issue does not affect a normal OpenWrt build, so closing this.
