### ISSUE TITLE
Subversion server self startup failed. The current openwrt version is 19.07, and the subversion server version is 1.12.2-1. What is the problem of self startup failure? Hope it can help me solve this problem?

### ISSUE THREAD

**Issue by caifenglin** [openwrt/luci#4645]
Subversion server self startup failed. The current openwrt version is 19.07, and the subversion server version is 1.12.2-1. What is the problem of self startup failure? Hope it can help me solve this problem?**

**Comment by jow-** [comment]
Not LuCI related.
