### ISSUE TITLE
Insufficient permissions to read UCI configuration. OPENVPN

### ISSUE THREAD

**Issue by SuperKali** [openwrt/luci#4653]
Hello, I have upgraded my raspberry pi to the latest version but I cannot anymore connect to OpenVPN because they give me auth failed, and the luci-app-openvpn give me insufficient permission

how can I fix it? 

![image](https://user-images.githubusercontent.com/19473898/101920482-28466000-3bcc-11eb-9ddb-1d595f88df4b.png)

**Comment by SuperKali** [comment]
hi, this is urgent or please restore the old configuration.

**Comment by dibdot** [comment]
duplicate of #4370
