### ISSUE TITLE
luci-lib-nixio tlsprovider menu missing in chaos_calmer

### ISSUE THREAD

**Issue by sophana** [openwrt/luci#467]
Hi

In barrier breaker, luci-lib-nixio had a configuration menu allowing to change the "TlsProvider" (openssl, cyassl, axssl)
In chaos calmer, it disapeared.
It looks the feature is still in the sources, but it seems that it is a makefile issue.
How can I restore this?

**Comment by cshoredaniel** [comment]
It appears you've got it under test in https://github.com/openwrt/luci/pull/640

**Comment by feckert** [comment]
15.05 has been for a long time EOL
