### ISSUE TITLE
illegal character U+0005 and sysFeatures is null

### ISSUE THREAD

**Issue by Wahjong1974** [openwrt/luci#4700]
Hi,

Got several errors after logging in this morning. 

**SyntaxError**
illegal character U+0005
  in http://*/luci-static/resources/form.js?v=git-20.363.66498-eb2cc80:53
  at compileClass/< (http://*/luci-static/resources/luci.js?v=git-20.363.66498-eb2cc80:178:29)

**TypeError**
sysFeatures is null

Strange errors. Never saw them before. You might want to take a look at it.

Router: Netgear Nighthawk X4S R7800
Firmware: OpenWrt 19.07.5 r11257-5090152ae3 / LuCI openwrt-19.07 branch git-20.363.66498-eb2cc80

![luci](https://user-images.githubusercontent.com/76773332/103343924-7ba22480-4a8d-11eb-83f1-662e69be12ca.png)

**Comment by jow-** [comment]
Looks as if the HTTP backend is replying with garbage data. Is your flash corrupted maybe?

**Comment by Wahjong1974** [comment]
I rebooted the router and the message disappeared. Really a weird error.
