### ISSUE TITLE
Typo in Flash Firmware dialog

### ISSUE THREAD

**Issue by steevithak** [openwrt/luci#4704]
After uploading a new firmware image to be flashed, the dialog says "Click Proceed" but there is no "Proceed" button. The available buttons are "Cancel" and "Continue". So I think the dialog text should be changed to say "Click Continue" here. I noticed this on OpenWrt v19.07.4.

![luci-bug](https://user-images.githubusercontent.com/660193/103427081-f8172f00-4b83-11eb-83a5-0636c618bb3c.png)

**Comment by hnyman** [comment]
Fixed in master with e2ac2e92b

**Comment by jow-** [comment]
Thanks @hnyman
