### ISSUE TITLE
Latest master branch shows no connection wirelessly! And wireless average 2.4G speed!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/luci#4718]
![image](https://user-images.githubusercontent.com/45259624/103893450-4d28e700-5128-11eb-9035-cf0b087413bc.png)

**Comment by jow-** [comment]
Likely caused by iwinfo and rpcd updates in master.

**Comment by jow-** [comment]
Fixed by bc121a5. As a local workaround, you can do:
`ln -s /usr/lib/libiwinfo.so.20210106 /usr/lib/libiwinfo.so`
