### ISSUE TITLE
TP-Link 1043ND V1  xl2tpd

### ISSUE THREAD

**Issue by DasDani** [openwrt/luci#472]
I can't install xl2tpd for TP-Link WR1043ND V1 ( MultiWeb 3.18 2015-03-14 with Load Balancing OpenWRT R44510 from http://ofmodemsandmen.com/download/MultiWe...W2015-03-14.zip)
# opkg install iptables-mod-ipsec kmod-crypto-authenc kmod-crypto-cbc kmod-crypto-deflate kmod-crypto-des kmod-crypto-hmac kmod-crypto-iv kmod-crypto-md5 kmod-crypto-rng kmod-crypto-wq kmod-zlib kmod-ipsec kmod-ipsec4 libopenssl xl2tpd ppp
root@ROOter:~# opkg install xl2tpd
Installing xl2tpd (devel-20150812-1) to root...
Downloading http://downloads.openwrt.org/snapshots/tru...12-1_ar71xx.ipk.
Multiple packages (kmod-ppp and kmod-ppp) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (kmod-pppox and kmod-pppox) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (kmod-ipv6 and kmod-ipv6) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
* satisfy_dependencies_for: Cannot satisfy the following dependencies for xl2tpd:
* kernel (= 4.1.6-1-4353a7f8db42bf7748e0afd51af26276) * kernel (= 4.1.6-1-4353a7f8db42bf7748e0afd51af26276) * kernel (= 4.1.6-1-4353a7f8db42bf7748e0afd51af26276) * kernel (= 4.1.6-1-4353a7f8db42bf7748e0afd51af26276) *
* opkg_install_cmd: Cannot install package xl2tpd.
root@ROOter:~#
Sorry for my eng.

**Comment by hnyman** [comment]
opkg package installation has nothing to do with Luci GUI.
