### ISSUE TITLE
Realtime Wireless graph does not work

### ISSUE THREAD

**Issue by abajk** [openwrt/luci#4721]
Router: TL-WDR4300
LuCI: Master (git-21.008.63257-bc121a5)
OpenWrt: SNAPSHOT r15466-2e590a6364 

It always shows zero.

![obraz](https://user-images.githubusercontent.com/30129889/104095833-4968a200-5299-11eb-9e2d-31a2db3aa6b9.png)

**Comment by hnyman** [comment]
@jow- 
FYI, likely an additional piece broken by the iwinfo changes.

I tested with ath10k ipq806x/R7800 and mwlwifi mvebu/WRT3200ACM and the wireless realtime remains empty.

**Comment by hnyman** [comment]
Likely here the libiwinfo needs modernising, too:

https://github.com/openwrt/luci/blob/master/modules/luci-mod-status/src/luci-bwc.c#L256

```
static void * iw_open(void)
{
	return dlopen("/usr/lib/libiwinfo.so", RTLD_LAZY);
}

```
