### ISSUE TITLE
LuCI: Error: Network device is not present

### ISSUE THREAD

**Issue by DickersonSasha** [openwrt/luci#4738]
Hi, 

Version/Device
----------------------
I'm using OpenWrt 19.07.5 r11257-5090152ae3 / LuCI openwrt-19.07 branch git-20.341.57626-51f55b5
on a Linksys WRT3200ACM.

Brief
--------
After a power outage, the DHCP server in a wireless interface (routed AP) is not working.

History
----------
The standard configuration was previously changed, being the wireless interface separated in a routed AP configuration, using LuCI.
The configuration was applied and saved. It worked correctly, the DHCP in the new created interface was operational.

After the 1st power down wireless clients were unable to get an address.
In the network menu, on the new interface -> Edit -> General Settings: Status: "Error: Network device is not present" was displayed.

Checking /etc/config/wireless as suggested in [1], the wifi-iface section lacks "option network".

Workaround
----------------------

1. Following [2]

    option network <new_wifi_name> 

was added to to /etc/config/wireless -> wifi-iface section.

2. In /etc/config/network

     option ifname was removed from the config interface <new_wifi_name> section.

3. Changes were applied [2]:

    a. ifup <new_wifi_name>
    b. /etc/init.d/firewall restart
    c. /etc/init.d/dnsmasq restart

The clients were able to connect immediatly.
The notice disapeared from the interface status, displaying the correct radio.

Steps to reproduce
---------------------------
1. Separate the wifi from lan, using LuCI.
    Create a new interface, configure DHCP, firewall, etc.
2. Apply and save changes.
3. Clients should be able to connect
4. Power down the router.
5. Power up the router.
6. Clients fail to get address.

References:
[1] https://forum.openwrt.org/t/error-network-device-is-not-present/55493
[2] https://openwrt.org/docs/guide-user/network/wifi/routedap

Thank you.

**Comment by jow-** [comment]
Already fixed in master with https://github.com/openwrt/luci/commit/7b5b7fbcd63af14658ad234cd39c076a823e4629 - backported to 19.07 branch in 6ba9740b61a3ca89355ae1b08f0456617e0ce3c0
