### ISSUE TITLE
luci-app-wireguard: import account like glinet

### ISSUE THREAD

**Issue by predators46** [openwrt/luci#4747]
when does openwrt have a wireguard luci that can import accounts like glinet

**Comment by feckert** [comment]
So far, there are no plans to do so. Besides, you need to give us more information about what it is. Best with pictures and a link where we can look at it, what this exactly is

**Comment by predators46** [comment]
> So far, there are no plans to do so. Besides, you need to give us more information about what it is. Best with pictures and a link where we can look at it, what this exactly is

https://docs.gl-inet.com/en/3/app/wireguard/

**Comment by predators46** [comment]
![WGC1](https://user-images.githubusercontent.com/31931530/105826906-44775280-5ffc-11eb-9804-7c604d5351d4.png)
![configurations1](https://user-images.githubusercontent.com/31931530/105826941-4b9e6080-5ffc-11eb-82cc-390097743962.jpg)

**Comment by predators46** [comment]
I use glinet and use glinet firmware I really like the wireguard account import feature I hope the openwrt devoloper can make it like that

**Comment by predators46** [comment]
> So far, there are no plans to do so. Besides, you need to give us more information about what it is. Best with pictures and a link where we can look at it, what this exactly is

hy. I tried the package file which must overwrite the existing config file. When I installed the file I found an error check_data_file_clashes how can I overwrite an existing config file

**Comment by jow-** [comment]
Current master provides import and export facilities for WireGuard configs.
