### ISSUE TITLE
Luci logins fail after upgrade without cache refresh

### ISSUE THREAD

**Issue by ngaro** [openwrt/luci#4756]
It seems that after a firmware upgrade logging in with luci fails if you do not refresh the browser cache.
Upgrade was done from 19.07.4 to 19.07.6.
Version of Luci used: git-21.018.57536-6ba9740

**Comment by hnyman** [comment]
Has worked quite normally for me with all upgrades and downgrades in 19.07.x and master.  (a few hundred downgrades/upgraded per year)

Likely something specific to your browser, browser add-ons or proxy/antivirus or so.

**Comment by jow-** [comment]
Unable to reproduce here.
