### ISSUE TITLE
LUCI:/luci/admin/system/opkg页面的显示问题

### ISSUE THREAD

**Issue by t0nyt4ng** [openwrt/luci#4769]
这个剩余空间的设计是不是有点反直觉，看第一眼还以为我用了80%的空间
![image](https://user-images.githubusercontent.com/8139781/107102253-db41db80-6854-11eb-8a9f-4b3578c840e0.png)

**Comment by nickberry17** [comment]
我同意有点反直觉，但是所有的status bar在OpenWrt系统里一样的。另外，请您放一个英文翻译，所以大家都可以参加。

English:
I agree that it is a little counterintuitive, but all of the status bars in OpenWrt are the same.  Also, could you please include an English translation so everyone can participate in the discussion?

**Comment by t0nyt4ng** [comment]
All right I think I'll get used to it . tks for your reply.
