### ISSUE TITLE
Wireless Overview - "Remove" button uses two lines if at least one network is configured as "mixed WPA/WPA2 PSK (CCMP)"

### ISSUE THREAD

**Issue by arminfuerst** [openwrt/luci#4776]
The Wireless Overview looks ugly due to the button "Remove" if at least one wireless network uses "mixed WPA/WPA2 PSK (CCMP)" as encryption.
I know that this encryption should not be used, but there are situations you can't avoid it.
I attach a screenshot as an example. As soon as I reconfigure the network to "WPA2 PSK (CCMP)", the buttons all only use one line.
![Wireless Overview](https://user-images.githubusercontent.com/29121472/107156756-826f6180-6980-11eb-93b1-dc6deaef50e1.png)

**Comment by dibdot** [comment]
that has been already fixed in master, see  #4647 for reference.
