### ISSUE TITLE
CDC_NCM module Continously Sends 15 Link Notifications to the Logs Every Minute

### ISSUE THREAD

**Issue by pepbrow** [openwrt/luci#4808]
Plugable 2.5GBE USB Ethernet Adapter installed on an OpenWrt router, version 19.07.6 on a Mini PC (Intel i3, 8gb RAM)

The adapter uses: Realtek 8152.53.56-2.12.0 which is native in kernels greater than 4.15.

Packages Installed:
kmod-usb-net-rtl8152 4.14.215-1
kmod-usb-net-cdc-eem 4.14.215-1
kmod-usb-net-cdc-ether 4.14.215-1
kmod-usb-net-cdc-mbim 4.14.215-1
kmod-usb-net-cdc-ncm 4.14.215-1
kmod-usb-net-cdc-subset 4.14.215-1

The connection appears to be solid (see "ifconfig -a" below). It's been running for a couple of weeks with no obvious problems, except the log issue. As the logs drop off at a point, they are pretty much useless for anything else until this gets figured out.

lsusb: 
Bus 002 Device 002: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8000 Intel Corp. 
Bus 003 Device 002: ID 0bda:8156 Realtek Semiconductor Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

lsmod | grep usb:
compat                -12288  3 rt2800usb,mac80211,cfg80211
mac80211            -409600  3 rt2800lib,rt2x00usb,rt2x00lib
mii                        -12288  2 usbnet,r8152
rt2800lib             -122880  1 rt2800usb
rt2800usb           -24576  0 
rt2x00lib              -36864  3 rt2800usb,rt2800lib,rt2x00usb
rt2x00usb            -16384  1 rt2800usb
usbmon                -24576  0 
usbnet                  -24576  5 cdc_mbim,cdc_subset,cdc_ncm,cdc_ether,cdc_eem

ifconfig -a:
usb0      Link encap:Ethernet  HWaddr 8C:AE:4C:DD:09:D4  
          inet addr:192.168.10.1  Bcast:192.168.10.255  Mask:255.255.255.0
          inet6 addr: fe80::8eae:4cff:fedd:9d4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:103231 errors:0 dropped:0 overruns:0 frame:0
          TX packets:105115 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11780563 (11.2 MiB)  TX bytes:49631469 (47.3 MiB)

modinfo:
module: /lib/modules/4.14.215/cdc_ncm.ko
license: Dual BSD/GPL
depends: usbnet
retpoline: Y

modinfo:
module: /lib/modules/4.14.215/r8152.ko
license: GPL
depends: mii
retpoline: Y

Log sample (also what "dmesg | grep usb" shows):
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5788.970831] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.034831] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.098776] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.162831] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.226832] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.290832] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.354777] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.418776] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.482794] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.546833] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.610832] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.674831] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.738836] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:04 2021 kern.info kernel: [ 5789.802831] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:05 2021 kern.info kernel: [ 5789.866840] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:05 2021 kern.info kernel: [ 5789.930831] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:05 2021 kern.info kernel: [ 5789.994832] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:05 2021 kern.info kernel: [ 5790.058771] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:05 2021 kern.info kernel: [ 5790.122832] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink
Fri Feb 12 09:32:05 2021 kern.info kernel: [ 5790.186833] cdc_ncm 3-2:2.0 usb0: 2500 mbit/s downlink 2500 mbit/s uplink

**Comment by dibdot** [comment]
this is unrelated to LuCI, open a ticket at bugs.openwrt.org
