### ISSUE TITLE
Firewall: Cannot add rules with negative CIDR

### ISSUE THREAD

**Issue by SoniEx2** [openwrt/luci#4812]
fw3 supports dynamic prefix forwarding: https://openwrt.org/docs/guide-user/firewall/fw3_configurations/fw3_ipv6_examples#dynamic_prefix_forwarding

However, LuCI doesn't allow one to input the `/-64` syntax.

**Comment by dibdot** [comment]
A negative CIDR looks invalid, most probably a typo or a range designation in the wiki.

**Comment by SoniEx2** [comment]
It was in one of the release notes at some point. It's definitely not invalid.

**Comment by dibdot** [comment]
The number following the slash is the prefix length ... what describes a negative number in this case? Do you have any implementation references?

**Comment by SoniEx2** [comment]
It's the suffix length.

**Comment by SoniEx2** [comment]
this clearly explicitly supports negative values: https://github.com/gigibox/fw3/blob/a4d98aea373e04f3fdc3c492c1688ba52ce490a9/utils.c#L771

altho ugh, the lack of comments makes it impossible to follow. >.<

**Comment by dibdot** [comment]
Interesting/confusing short-hand notation ... I've found the relevant commit here: https://git.openwrt.org/?p=project/firewall3.git;a=commit;h=bba31cce0521e014109fc805671d4cff7ee9dbf6

**Comment by dengqf6** [comment]
It's `iptables` that does not support this format.
```
ip6tables v1.8.7 (legacy): invalid mask `-64' specified
```
But you can just use `::ffff:ffff:ffff:ffff`

**Comment by SoniEx2** [comment]
but luci is a frontend to fw3, which handles this format.

not only that but editing the raw HTML's hidden fields to force it to send the -64 works fine.
