### ISSUE TITLE
mt7615e wrong wifi-device order with dbdc

### ISSUE THREAD

**Issue by ivanich** [openwrt/luci#4815]
Device: GL.iNet GL-MT1300 added with https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=d89a7f0120db42d4fae1656e1860ef49523acabb

The problem is that luci wireless app configures wifi devices in wrong order. Original description is https://github.com/openwrt/mt76/issues/474

using proper config where radio0 is 11g and radio1 is 11a works with wifi script(wifi up, wifi down) but luci's wifi interface is broken, also wireless doesn't comes up after router reboot until wifi up && wifi down commands.

**Comment by jow-** [comment]
This sounds like a bug in base OpenWrt. LuCI only manages the wireless config. If drivers advertise wrong capabilities and/or the default wireless config is wrongly generated by OpenWrt, there's nothing that can be done on the LuCI side.
