### ISSUE TITLE
Missing releases/19.07.7/packages/mips_24kc/luci/luci-lib-ipkg_git-21.044.30835-34e0d65-1_all.ipk

### ISSUE THREAD

**Issue by datenleck** [openwrt/luci#4820]
Hi,

the package http://downloads.openwrt.org/releases/19.07.7/packages/mips_24kc/luci/luci-lib-ipkg_git-21.044.30835-34e0d65-1_all.ipk  is not available.

It's needed for installing some Luci packages like DDNS and UPNP.

![grafik](https://user-images.githubusercontent.com/47418901/108334527-5484eb00-71d2-11eb-8772-92cd4e83783f.png)

**Comment by jow-** [comment]
Likely a transient issue. Also the repos are not managed by this project.
