### ISSUE TITLE
luci-theme-openwrt-2020: loading animation is not centered

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4824]
I see that it doesn't happen on all LuCI sites where animation is. I could see in the scanner and opkg.

It is a new compilation of OpenWrt, without configuration files and clean browser of cookies.

![1](https://user-images.githubusercontent.com/47670442/108610139-1b0ad600-73b2-11eb-8061-08eaa82229f0.png)
![2](https://user-images.githubusercontent.com/47670442/108610141-1e05c680-73b2-11eb-94b9-980e824db601.png)
![3](https://user-images.githubusercontent.com/47670442/108610185-62916200-73b2-11eb-81b4-e8a387da64c9.png)
![4](https://user-images.githubusercontent.com/47670442/108610186-64f3bc00-73b2-11eb-817f-eea214343da7.png)

**Comment by feckert** [comment]
@castillofrancodamian The way I see it, the spinner is spinning around the wrong center. Unfortunately, I am not a CSS expert, I do not know where to start here. Of course, it may be that this is intentional
