### ISSUE TITLE
luci-mod-network: the correct Wi-Fi status is not displayed

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#4825]
In a clean installation of OpenWrt without configuration files, pressing the WPS button, which activates the wireless radios, does not correctly display their status in LuCI. After a device reboot, it shows the status correctly.

![2](https://user-images.githubusercontent.com/47670442/108610982-d9315e00-73b8-11eb-9c0b-cf54f9ab7756.png)
![3](https://user-images.githubusercontent.com/47670442/108610986-db93b800-73b8-11eb-8dfd-8ba36675e00d.png)

**Comment by castillofrancodamian** [comment]
Someone?

**Comment by Ansuel** [comment]
@castillofrancodamian can you better describe the problem? more details on how to reproduce

**Comment by castillofrancodamian** [comment]
I can no longer reproduce it. At that time, I have tried multiple builds and all were showing the same error.

**Comment by castillofrancodamian** [comment]
They will have already fixed it, so I close this.
