### ISSUE TITLE
The realtime load graph refresh frequency

### ISSUE THREAD

**Issue by intijk** [openwrt/luci#483]
Current the refresh interval is 3 second which is statically programmed in code ( luci/modules/luci-mod-admin-full/luasrc/view/admin_status/load.htm), can we adjust it in the future? I think it is too slow, want to make it 1 sec.

**Comment by cshoredaniel** [comment]
@intijk unless you can find someone to work on it, it's not likely to happen simply due to priorites, time, and interest.

**Comment by feckert** [comment]
The possibly to make the polling interval configurable was added with the following commit https://github.com/openwrt/luci/commit/6475221d54be41dbfa4639c4cef5046b186e296f#diff-2f77d1f564804e66067ff88f8d85e565
