### ISSUE TITLE
luci cbi "arg" variable is now empty (it was working with 14.07)

### ISSUE THREAD

**Issue by ondonadas** [openwrt/luci#4835]
Hi all!

After long time without use LUCI I'm upgrading my app to openwrt 19 (last time I was using 14.07 version). What a surprise about cbi javascript based forms!

The issue appear when I try to use cbi lua form with many tabs, and try to access **arg** variable in order to obtain tab name/index. So in my controller I use something like:

> -- Devices menu option
> page = entry({"admin", "IOT", "devices"}, cbi("IOT/devices"), _("Devices"), 3)
> page.leaf   = true
> page.subindex = true
> -- subitems / tabs
> entry({"admin", "IOT", "devices", "room"}, true, "ROOM", 0)
> entry({"admin", "IOT", "devices", "hall"}, true, "HALL", 1)
> entry({"admin", "IOT", "devices", "door"}, true, "DOOR", 2)

Next, at the begining of devices.lua I try to access **arg** variable to obtain tab name (ROOM, HALL, DOOR) but variable is empty. While this work nicely in openwt 14.07, it doens't work in openwrt 19.

Please, someone with patience to help?

**Comment by feckert** [comment]
Openwrt version 14.07 has been EOL for a long time, please contact the [Openwrt forum](https://forum.openwrt.org/), they will be able to help you with javascript for newer Openwrt versions.
