### ISSUE TITLE
HTML tags rendered in conntrack helpers dropdown menu

### ISSUE THREAD

**Issue by willymilkytron** [openwrt/luci#4845]
LuCI openwrt-19.07 branch (git-21.044.30835-34e0d65)
OpenWrt 19.07.7 r11306-c4a6851c72
Firefox 82.0.2

![Powered by LuCI openwrt-19 07 branch (git-21 044 30835-34e0d65) - OpenWrt 19 07 7 r11306-c4a6851c72](https://user-images.githubusercontent.com/62460473/109396914-3d619e00-7934-11eb-9fe5-a44416da6348.png)

**Comment by hnyman** [comment]
Happens also with master,  (git-21.050.34860-b8d2bcd)

**Comment by dibdot** [comment]
at least it looks OK now ...;-)
![conntrack](https://user-images.githubusercontent.com/8061346/109427056-e79efb80-79f0-11eb-9246-bd964badf4da.png)
