### ISSUE TITLE
Please show full absolute values instead of short form

### ISSUE THREAD

**Issue by saudiqbal** [openwrt/luci#4852]
Short values like 4K interfere in troubleshooting and analysis, please show full values like 4501 Bytes in LUCI.

**Comment by jow-** [comment]
Too vague to act upon

**Comment by lantis1008** [comment]
Context: https://forum.openwrt.org/t/is-it-possible-to-see-absolute-values-in-openwrt/87291
I think OP wants packet counters in the firewall sections of LUCI to show full values (not order of magnitude abbreviations).

**Comment by saudiqbal** [comment]
> Too vague to act upon



> Context: https://forum.openwrt.org/t/is-it-possible-to-see-absolute-values-in-openwrt/87291
> I think OP wants packet counters in the firewall sections of LUCI to show full values (not order of magnitude abbreviations).

That's correct, please reopen this issue.
Thanks.
