### ISSUE TITLE
luci-app-advanced-reboot: Firmware not showing version number

### ISSUE THREAD

**Issue by arrmo** [openwrt/luci#4861]
Hi,

This is a very minor issue, just something I have noticed - and seems to be release / version dependent perhaps (just seems like it). Pics below ... but you can see, the version number is missing from the alternative partition. Assuming this is not as it should be?

![image](https://user-images.githubusercontent.com/8756384/109581613-38325980-7ac2-11eb-916f-b55a79780fd9.png)

![image](https://user-images.githubusercontent.com/8756384/109581623-3c5e7700-7ac2-11eb-9e69-56070c592986.png)

I can capture console info, if that helps.

Thanks!

**Comment by stangri** [comment]
Is this a UBI-based devices? Are there `ubiattach`, `ubiblock` and `mount` binaries on it?

**Comment by arrmo** [comment]
Yes, it is (UBI). And just checked - yes, those 3 binaries are present.

Thanks!

**Comment by stangri** [comment]
Can you post the log of what happens when luci app tries to mount/umount alternative partitions?

**Comment by arrmo** [comment]
Assuming you mean to go to the Advanced Reboot page 😄. Yell if I have this wrong though!

Here is what I see on the console,
```
root@ea7300:/# [ 1952.570496] ubi1: attaching mtd6
[ 1952.942388] ubi1: scanning is finished
[ 1952.963339] ubi1: attached mtd6 (name "rootfs1", size 36 MiB)
[ 1952.969159] ubi1: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[ 1952.976047] ubi1: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[ 1952.982863] ubi1: VID header offset: 2048 (aligned 2048), data offset: 4096
[ 1952.989840] ubi1: good PEBs: 288, bad PEBs: 0, corrupted PEBs: 0
[ 1952.995852] ubi1: user volume: 3, internal volumes: 1, max. volumes count: 128
[ 1953.003078] ubi1: max/mean erase counter: 2/1, WL threshold: 4096, image sequence number: 1614635198
[ 1953.012211] ubi1: available PEBs: 0, total reserved PEBs: 288, PEBs reserved for bad PEB handling: 20
[ 1953.021486] ubi1: background thread "ubi_bgt1d" started, PID 4206
[ 1953.042230] block ubiblock1_0: created from ubi1:0(kernel)
[ 1953.129003] block ubiblock1_0: released
[ 1953.141513] ubi1: detaching mtd6
[ 1953.146368] ubi1: mtd6 is detached
```

**Comment by stangri** [comment]
```sh
mkdir -p /alt/alt_rom
ubiattach -m 6
ubiblock --create "/dev/ubi1_0"
mount -t squashfs -o ro "/dev/ubiblock1_0" /alt/alt_rom
```

Please post the output of this block of commands. From the log you posted it looks like it's the mount which is failing and I can't understand why.

**Comment by arrmo** [comment]
Sure, NP at all. Here is the sequence,
```
root@ea7300:/# ubiattach -m 6
[ 2839.520360] ubi1: attaching mtd6
[ 2839.892453] ubi1: scanning is finished
[ 2839.913266] ubi1: attached mtd6 (name "rootfs1", size 36 MiB)
[ 2839.919076] ubi1: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[ 2839.926002] ubi1: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[ 2839.932822] ubi1: VID header offset: 2048 (aligned 2048), data offset: 4096
[ 2839.939807] ubi1: good PEBs: 288, bad PEBs: 0, corrupted PEBs: 0
[ 2839.945846] ubi1: user volume: 3, internal volumes: 1, max. volumes count: 128
[ 2839.953091] ubi1: max/mean erase counter: 2/1, WL threshold: 4096, image sequence number: 1614635198
[ 2839.962242] ubi1: available PEBs: 0, total reserved PEBs: 288, PEBs reserved for bad PEB handling: 20
[ 2839.971590] ubi1: background thread "ubi_bgt1d" started, PID 4296
UBI device number 1, total 288 LEBs (36569088 bytes, 34.8 MiB), available 0 LEBs (0 bytes), LEB size 126976 bytes (124.0 KiB)
```
```
root@ea7300:/# ubiblock --create "/dev/ubi1_0"
[ 2891.502671] block ubiblock1_0: created from ubi1:0(kernel)
```
```
root@ea7300:/# mount -t squashfs -o ro "/dev/ubiblock1_0" /alt/alt_rom
mount: mounting /dev/ubiblock1_0 on /alt/alt_rom failed: Invalid argument
```

Last step seems to be the gotcha. Thoughts?

Thanks!

**Comment by stangri** [comment]
Did you do `mkdir -p /alt/alt_rom` from the first line? What does `ls -la /alt/alt_rom` say?

**Comment by arrmo** [comment]
> Did you do `mkdir -p /alt/alt_rom` from the first line? What does `ls -la /alt/alt_rom` say?

Yep, I did 😄. Here is the output,
```
root@ea7300:/# ls -la /alt/alt_rom
drwxr-xr-x    2 root     root           160 Mar  1 16:33 .
drwxr-xr-x    3 root     root           224 Mar  1 16:33 ..
```



> Please also try

Sure. Below. And - remove `/alt/alt_rom` now?
```
root@ea7300:/# mkdir -p /var/alt_rom
root@ea7300:/# mount -t squashfs -r "/dev/ubiblock1_0" /var/alt_rom
mount: mounting /dev/ubiblock1_0 on /var/alt_rom failed: Invalid argument
```

Thanks!

**Comment by stangri** [comment]
Is it indeed a squashfs OpenWrt partition?

**Comment by arrmo** [comment]
I believe so 😄. The pics above are booting from the two different partitions ... so both OpenWrt, and I'm pretty sure squashfs. Agreed?

Thanks!

**Comment by stangri** [comment]
I'm out of ideas. I posted a question on the forum: https://forum.openwrt.org/t/script-mount-alternate-nand-firmware-linksys/33588/5.

**Comment by arrmo** [comment]
Thanks! And like I said, it's not a biggie - just wanted to make you aware of it. It is odd, as it detects OpenWrt and the Linux version correctly, so it is seeing the partition ... agreed?

Thanks again.

**Comment by eduperez** [comment]
Could you please post the output of "`mount`" (no parameters)?

**Comment by arrmo** [comment]
> Could you please post the output of "`mount`" (no parameters)?

Sure, NP! Here is the output,
```
/dev/root on /rom type squashfs (ro,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
/dev/ubi0_2 on /overlay type ubifs (rw,noatime,assert=read-only,ubi=0,vol=2)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600,ptmxmode=000)
debugfs on /sys/kernel/debug type debugfs (rw,noatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,noatime,mode=700)
```

Thanks!

**Comment by arrmo** [comment]
Hi,

I was digging in to a different issue (more on that in another post ... 😆), but found something very interesting using ubus (which works great by the way, thanks!).

On the router I was testing (EA3500), if I execute `ubus call luci.advanced_reboot obtain_device_info`, I get,
```
{
        "current_partition": 1,
        "device_name": "Linksys EA3500",
        "partitions": [
                {
                        "state": "Current",
                        "os": "OpenWrt SNAPSHOT r16290 (Linux 5.4.97)",
                        "number": 1
                },
                {
                        "state": "Alternative",
                        "os": "OpenWrt (Linux 5.4.105)",
                        "number": 2
                }
        ],
        "rom_board_name": "linksys,ea3500"
}
```

This is great. But then, I ran `ubus call luci.advanced_reboot toggle_boot_partition` ... simple enough, they should swap. But not quite, here is the check now,
```
{
        "current_partition": 2,
        "device_name": "Linksys EA3500",
        "partitions": [
                {
                        "state": "Alternative",
                        "os": "OpenWrt SNAPSHOT r15750 (Linux 5.4.97)",
                        "number": 1
                },
                {
                        "state": "Current",
                        "os": "OpenWrt SNAPSHOT r16290 (Linux 5.4.105)",
                        "number": 2
                }
        ],
        "rom_board_name": "linksys,ea3500"
}
```

Very odd, agreed? The `current_partition` and `state` changed, as they should - but why do the `os` values change?

Thanks!

**Comment by stangri** [comment]
> Very odd, agreed? The `current_partition` and `state` changed, as they should - but why do the `os` values change?

The `os` not having revision number and only the Linux kernel numer is an indication that on the first run the ubus script failed to mount ubi partitions to fetch the version information from the `/etc/os-release` file in that partition. Why it worked after partitions were switched I don't know and not sure if I can figure out without the access to the device. The ubus script is a shell script, if you can debug the issue and let me know (or send PR), that's the only way to fix that.

**Comment by arrmo** [comment]
That makes sense - and I do see the script file there now. Will try to see where the problem is occurring.

Thanks!

**Comment by arrmo** [comment]
Found the "issue" - it's related to the (wrong) rootfs getting selected ... so mount then fails, as it's going to the wrong alternative partition. Not thinking this is due to luci-app-advanced-reboot, but let me dig more. Not sure why rootfs is not being selected correctly (now - it was before).

Thanks!

**Comment by arrmo** [comment]
OK, will close this out - figured out the (my 😆) issue. If you toggle => don't try to use `obtain_device_info` then (without a reboot) ... it won't work right. I can explain if you want, but from the code I can see what is going on.

Thanks!
