### ISSUE TITLE
Overview page does not work on Safari (macOS)

### ISSUE THREAD

**Issue by oskarirauta** [openwrt/luci#4865]
Overview page has indefinitely spinning spinner on Safari for OS X.
XHR's are not loading either.

Works on Chrome (for macOS) but not on Safari.

**Comment by oskarirauta** [comment]
Issue is with 30_network.js and most likely on it's minifying; I downloaded it's raw version and did not minify it and overview page started working again.

**Comment by jow-** [comment]
I don't have access to any OS X so can't really test. Any hint in the browser debug console?

**Comment by oskarirauta** [comment]
File loading stalled in middle of it. No debug results as file loading did not complete. After a long time, luci reports that browser gave up on request.
 Version without minifying works.

Lähetetty iPhonesta

**Comment by jow-** [comment]
Do you use `luci-ssl` / HTTPS? Does the same happen without HTTPS?

**Comment by oskarirauta** [comment]
Did not try with https. Only plain http was tested.
