### ISSUE TITLE
luci-app-banip: empty string warning

### ISSUE THREAD

**Issue by feckert** [openwrt/luci#4868]
I get the following error on I18N update.

```
Updating applications/luci-app-banip/po/templates/banip.pot ... standard input:126: warning: Empty msgid.  It is reserved by GNU gettext:
                             gettext("") returns the header entry with
                             meta information, not the empty string.
done
```

I think this [line](https://github.com/openwrt/luci/blob/master/applications/luci-app-banip/htdocs/luci-static/resources/view/banip/ipsetreport.js#L126) is the root cause of this mesage. If I remove the line the warning disappears. But I am not familiar with your code, so could you @dibdot please check if it is save to remove the line to fix this warning?

**Comment by dibdot** [comment]
The table row is needed, just remove the translation and fill in a non breaking space instead (see #4869).

**Comment by feckert** [comment]
Fixed with https://github.com/openwrt/luci/pull/4869
