### ISSUE TITLE
RFC: LuCI failed/successful logging to syslog

### ISSUE THREAD

**Issue by ja-pa** [openwrt/luci#4877]
Hi,
I'm not using uhttpd on my router and probably because of that failed/succesfull login for LuCI are not in syslog. (Similar issue is  https://forum.openwrt.org/t/luci-code-that-handles-failed-and-success-login-results-to-syslog/83776)

I fixed that with this patch but I'm not sure if this is would be accepted in upstream because it will result in double error login in syslog.

I'm looking for idea how to improve it and will be glad for any suggestions.

```
--- a/modules/luci-base/luasrc/dispatcher.lua
+++ b/modules/luci-base/luasrc/dispatcher.lua
@@ -565,12 +565,16 @@ local function session_setup(user, pass)
 
 		io.stderr:write("luci: accepted login on /%s for %s from %s\n"
 			%{ rp, user or "?", http.getenv("REMOTE_ADDR") or "?" })
+		nixio.syslog("info","luci: accepted login on /%s for %s from %s\n"
+			%{ rp, user or "?", http.getenv("REMOTE_ADDR") or "?" })
 
 		return session_retrieve(login.ubus_rpc_session)
 	end
 
 	io.stderr:write("luci: failed login on /%s for %s from %s\n"
 		%{ rp, user or "?", http.getenv("REMOTE_ADDR") or "?" })
+	nixio.syslog("info","luci: failed login on /%s for %s from %s\n"
+		%{ rp, user or "?", http.getenv("REMOTE_ADDR") or "?" })
 end

```

**Comment by feckert** [comment]
We could replace the `io.stderr:write` in alle source files with [perror](https://github.com/openwrt/luci/blob/bd40525a69fe591b5ab487df25238401196cb77a/libs/luci-lib-base/luasrc/util.lua#L136) and decide with a config option if we want to log to stderr or syslog or check if we use nginx or uhttpd
