### ISSUE TITLE
luci-ddns writes incorrect service_name when "--custom--" service is chosen

### ISSUE THREAD

**Issue by wonson** [openwrt/luci#4926]
luci-ddns write incorrect service into /etc/config/ddns when "--custom--" service is chosen
`option service_name '-'` where this line should be deleted or commented ( https://openwrt.org/docs/guide-user/services/ddns/client#custom_service1 )

This would result in "No update_url found/defined or no update_script found/defined! - TERMINATE" error when it try to update

**Comment by tavinus** [comment]
I was having a look at the code and I think your solution above is not ideal. From what I can understand, we need to suppress the `service_name='-'` **ONLY** when saving the configuration file.  
  
So, that is when we call the `uci.set` command on `service_name`  
[Here](https://github.com/openwrt/luci/blob/master/applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js#L650)
```javascript
uci.set('ddns',section_id,'service_name',service_value);
```

As it is already done in other parts of the code, we need to check if it is a custom script and then IGNORE the uci.set command for the service_name.  
  
We can do that with
```javascript
if (service_value != '-') { uci.set('ddns',section_id,'service_name',service_value); }
```
  
Was quite the pain to test this in a running OpenWRT router. Browser cache also interfering.  
  
Also, this is done when you select the service type and click `CREATE SERVICE` (pre-creation)
  
You can patch the minified version like I did if you want.   
  
File: `/www/luci-static/resources/view/ddns/overview.js`  
  
Original:
```javascript
return m.save(function(){uci.add('ddns','service',section_id);uci.set('ddns',section_id,'service_name',service_value);uci.set('ddns',section_id,'use_ipv6',ipv6_value);})
```
  
Changed:
```javascript
return m.save(function(){uci.add('ddns','service',section_id);if(service_value!='-'){uci.set('ddns',section_id,'service_name',service_value);}uci.set('ddns',section_id,'use_ipv6',ipv6_value);})
```



Then reload  uhttp
```
/etc/init.d/uhttpd reload
```

Your browser may be stubborn about the Javascript cache though. Try in another browser to be sure (or inspect the source).  
  
I think this is a simple working solution. I probably won't be able to make a PR any time soon.  
  
  
Cheers!  
  
Gus

**Comment by tavinus** [comment]
Sorry to double-post, but this is something else kind of related.  
  
I noticed that when creating the custom service, you will have to select some other service and then select the `-- custom --` service back for it to work. I think there used to be ANOTHER first option with a description before the custom one (am I wrong?). This may be related to removing that? Maybe some code that used to compensate for that?  
  
This is how it behaves
![image](https://user-images.githubusercontent.com/8039413/161182850-b724d5fe-ecee-4288-b989-da26299982cf.png)

Then you click something else
![image](https://user-images.githubusercontent.com/8039413/161182969-7a6320a8-49de-4983-850e-b146899dda76.png)

Then `-- custom --` works
![image](https://user-images.githubusercontent.com/8039413/161183051-15715c28-6570-4c6a-b97a-b14eea943c1c.png)

**Comment by attila-lendvai** [comment]
FWIW, i was bitten by this just now.
