### ISSUE TITLE
luci package missing from release 19.07.7 packages?

### ISSUE THREAD

**Issue by cris-** [openwrt/luci#4927]
Im starting the image builder for 19.07.7 x86-64 with PACKAGES="... luci luci-ssl-openssl..." but it fails with the following error:
`opkg_install_cmd: Cannot install package luci.`
`satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-ssl-openssl:`
` 	luci`
`opkg_install_cmd: Cannot install package luci-ssl-openssl.`

The same build was working yesterday: am I wrong thinking that the luci package is missing from https://downloads.openwrt.org/releases/19.07.7/packages/x86_64/luci/ ?

**Comment by jow-** [comment]
Seems to be an error at the OpenWrt side, nothing we can fix from here.
