### ISSUE TITLE
Problem. In firewoll

### ISSUE THREAD

**Issue by fiduchi** [openwrt/luci#4938]
Problem. In firewoll, when creating a parental control rule for mak time limits, when you check the box and click the save and apply button, the checkbox is removed.

**Comment by jow-** [comment]
Which "box" do you mean exactly? Can you provide a screenshot?

**Comment by fiduchi** [comment]
![IMG_20210323_114610](https://user-images.githubusercontent.com/52358089/112128992-9fc65b00-8bcf-11eb-803b-2d60abf86d0f.jpg)

**Comment by fiduchi** [comment]
This only happens when time limits are enabled.

**Comment by gearhead** [comment]
What goes on here is that Luci cannot turn these time based firewall rules on or off. They are always turned off when any change is made. It is easy to check. Make a couple time dependent rules then try to turn them on. Hit save and apply and they are all cleared (turned off). Luci does not seem to be able to change the '0' to '1' for Enabled for these rules. The workaround is to log in via cli and change the 0 to 1 then reload the firewall rules on the command line. It would be awesome if this worked, though.

**Comment by jow-** [comment]
@fiduchi and @gearhead - thanks for providing the details, it helped me to track down the cause.
