### ISSUE TITLE
luci-app-dawn network overview with openwrt2020 theme is broken

### ISSUE THREAD

**Issue by boecko** [openwrt/luci#4942]
The network overview page from  luci-app-dawn is broken in the openwrt2020 theme, 
because following css-classes are used for table -rendering

- &lt;div class="table"
- &lt;div class="tr"
- &lt;div class="td"

theme bootstrap has these classes/ openwrt2020 not.

openwrt-master: r16317-07c49462ad
packages: 0d25e3869a1c0a859098965d6779d6875b787ac9 (current HEAD)

**Comment by jow-** [comment]
Needs `s/<div class="(table|tr|td)">/<\1>/g`

**Comment by boecko** [comment]
I would leave the css-classes in there because these classes are used in the bootstrap-theme, IMHO.

So `s/<div class="(table|tr|td)">/<\1 class="\1">/g` would be better.
