### ISSUE TITLE
Dispatch issue, /usr/lib/lua/luci/dispatcher.lua:414: Access Violation

### ISSUE THREAD

**Issue by Jstreet432** [openwrt/luci#4950]
Hi there!  This is my first time doing something like this.  Please let me know if I can provide any other details.  I do not have direct access to the source code of the implementation.  I encountered this making a post request to a location that does not exist.  Not sure if this is actually an issue or not.  Omitted is not the actual location. 
EDIT: Markdown language fix

The page at 'admin/omitted/omitted/cgi_firewall.js/' has no parent node so the access to this location has been denied.
This is a software bug, please report this message at https://github.com/openwrt/luci/issues
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:414: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:138: in function </usr/lib/lua/luci/dispatcher.lua:137>

**Comment by jow-** [comment]
Depending on the handlers registered at `admin/omitted/omitted` this behavior might be expected and the error message a bit misleading. In any case there's not much we can fix about it, this needs to be changed in the offending controller.
