### ISSUE TITLE
snappify LuCI "Save & Apply" button

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#4951]
When applying changes in the interface, the first *check* if changes were applied happens after 5 seconds. Can we lower that since changes are likely applied within split seconds? In case it's a more complex change, a recheck can happen again after x seconds, like it's now.

I'd propose a recheck pattern of like second 1,2,5,10,15...

**Comment by hnyman** [comment]
Duplicate of your #4881 ?
Same answer again as I gave there a month ago:

Trying to remember the original discussions from 2018.

I think that it was originally shorter and that caused problems with some apps, so it was made a bit longer (and configurable)

Discussion e.g. here in the original topic about the "new" rollback: #1769 (comment)

**Comment by aparcar** [comment]
Thanks!
