### ISSUE TITLE
Firewall problem time limit

### ISSUE THREAD

**Issue by fiduchi** [openwrt/luci#4952]
The problem persists, Lucy is unable to enable or disable the time-based firewall rules. They always turn off on any change. It's easy to check. Make a couple of time-dependent rules and then try turning them on. Click Save and Apply and they will all be cleared (turned off). Lucy seems unable to change "0" to "1"

**Comment by jow-** [comment]
Works for me after 95b5c6cd6464d11d6baa22bcf2c9469847353813 - make sure that the version you run includes this fix. Also try clearing your browser cache or force reloading the firewall page.
