### ISSUE TITLE
Finnish translations don't seem to be in openwrt builds

### ISSUE THREAD

**Issue by rypervenche** [openwrt/luci#4959]
I'm not sure if this is the right place to be asking this, but I figured I'd start here.

I noticed that the Finnish translations don't seem to be in the openwrt builds, yet I find other languages with less progress there. Is this some misconfiguration in this repository or would it be in the openwrt build process?

My router's version and latest firmware file:
OpenWrt 19.07.7 r11306-c4a6851c72 / LuCI openwrt-19.07 branch git-21.044.30835-34e0d65
openwrt-19.07.7-mvebu-cortexa9-linksys_wrt3200acm-squashfs-sysupgrade.bin

Easy test:
```
opkg update
opkg list luci-i18n-*fi
```

Please let me know if I should be posting this on https://bugs.openwrt.org/ or somewhere else.

Thanks

**Comment by hnyman** [comment]
Finnish translations do exists, in 21.02 and master.

Finnish has been added to OpenWrt in May 2020, one year later than 19.07.x as branch off master. So the translations are not yet in 19.07
