### ISSUE TITLE
luci-theme-openwrt-2020: does not support table view

### ISSUE THREAD

**Issue by feckert** [openwrt/luci#4972]
I fell maybe over the following css problem while testing the next stable branches. It looks like the table css definition is missing with **this** LuCI theme. I noticed thos first during my test for luci-app-dockerman with this theme. The luci-app-command also looks strange with this theme. Can anyone confirm this? @jow- do you have a fix for this?

luci-app-commands (dashboard):
![Screenshot_2021-04-09 st-dev-07 - Konfigurieren - LuCI](https://user-images.githubusercontent.com/553091/114167528-57c56900-992f-11eb-8c8c-f6fb9b1d1674.png)

luci-app-commands (config):
The button thing can be fixed by adding btn to the css class.
![Screenshot_2021-04-09 st-dev-07 - Übersicht - LuCI](https://user-images.githubusercontent.com/553091/114167516-5300b500-992f-11eb-8eb5-b0e9afad90bb.png)

**Comment by hnyman** [comment]
what is "this" in the "this theme"  ?

**Comment by feckert** [comment]
@hnyman no problem :-)

If I add the following to luci-theme-openwrt-2020 cascade.css:

```
diff --git a/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css b/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
index aa811ef6d..b93fd2715 100644
--- a/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
+++ b/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
@@ -270,6 +270,28 @@ body.modal-overlay-active #modal_overlay {
  * table layout
  */

+.table {
+       display: flex;
+       flex-direction: column;
+       width: 100%;
+}
+
+.tr {
+       display: flex;
+       flex-direction: row;
+       flex-wrap: wrap;
+       align-items: flex-end;
+}
+
+.th, .td {
+       flex: 2 2 25%;
+       align-self: flex-start;
+       overflow: hidden;
+       text-overflow: ellipsis;
+       word-wrap: break-word;
+       display: inline-block;
+}
+
 table {
        width: 100%;
        margin: 0 0 1rem 0;
```

Then things look better. But I am not a CSS expert! Maybe there is someone who knows about it ;-)

![Screenshot_2021-04-09 st-dev-07 - Konfigurieren - LuCI(1)](https://user-images.githubusercontent.com/553091/114172880-901c7580-9936-11eb-9ffc-14db6652aa5c.png)

**Comment by jow-** [comment]
Fixed with these commits:

 - f117b7f1e ("luci-app-commands: use <button> elements")
 - c5ff3244e ("luci-theme-openwrt-2020: honor CSS definitions passed by views")
 - 215586817 ("luci-compat: update markup for CBI TableSections")
