### ISSUE TITLE
Luci-Theme-OpenWrt-2020 in the master branch under the interface believe the error!

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/luci#4977]
![image](https://user-images.githubusercontent.com/45259624/114291857-4316db80-9abd-11eb-8611-a3177c28d9c2.png)

**Comment by hnyman** [comment]
Sorry, you need to post that screenshot in English.
And explain what you think is wrong.

**Comment by dibdot** [comment]
No more feedback by TO - closing this by now.
