### ISSUE TITLE
[question] Need reboot after updating an packages?

### ISSUE THREAD

**Issue by userosos** [openwrt/luci#4978]
Hi! Need reboot after updating an packages for correct working an router?

**Comment by hnyman** [comment]
It depends on the package.

(but this is not a bug. The question would be more suitable for the forum)

**Comment by userosos** [comment]
> 
> 
> It depends on the package.
> 
> (but this is not a bug. The question would be more suitable for the forum)

Ok. I think that a feature request. Can you add an mark for packages which request the reboot after update into web opkg? Thx for help!
