### ISSUE TITLE
Privoxy cannot start after sysupgrade to Chaos Calmer

### ISSUE THREAD

**Issue by elgatov** [openwrt/luci#498]
* **Hardware:** TP-Link TL-WR1043N/ND v2
* **System:** OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45) 

The system throws an error when trying to start privoxy through `/etc/init.d/privoxy start`:
```
chgrp: unknown group privoxy
chgrp: unknown group privoxy
chgrp: unknown group privoxy
chown: unknown user/group privoxy:privoxy
2015-09-29 14:03:21.135 77d6f000 Fatal error: Group 'privoxy' not found.
```

Seems like the script was not updated to reflect the changes made in the new privoxy package.

**Comment by hnyman** [comment]
Has that anything to do with Luci GUI?
