### ISSUE TITLE
luci-theme-openwrt partially broken on master

### ISSUE THREAD

**Issue by TimB87** [openwrt/luci#4980]
I recently updated to a self compiled snapshot and noticed that the classic openwrt theme seems broken in certain areas.
The version I am currently using is `SNAPSHOT r16481+8-328546e108 / LuCI Master git-21.100.52667-3b652a7 `
For me, trying to edit LAN settings yields the following error:

```
SyntaxError
Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
```
This won't allow to make any changes.

It doesn't work for LAN (static address and dhcp server) and WAN (pppoe), but it works for WAN6 (DHCPv6).

If I can help with more data please let me know.

**Comment by dibdot** [comment]
fixed with #4989
