### ISSUE TITLE
Home page display error (x86 device name not shown)

### ISSUE THREAD

**Issue by 643406834** [openwrt/luci#4992]
![image](https://user-images.githubusercontent.com/39716940/114808603-33f49e00-9ddb-11eb-8131-c61d6558e10a.png)

**Comment by hnyman** [comment]
I am not OpenWrt with x86 expert, but I think that the x86 builds are not device-specific, and so no device name (like WRT3200ACM) is encoded in the image. So, I am not sure that there is any bug at all.

**Comment by dibdot** [comment]
That's not a LuCI issue at all, we're just parsing /etc/board.json.

**Comment by dibdot** [comment]
No more feedback by TO - closing this for now.

**Comment by stangri** [comment]
BTW, If the model is correctly identified, it is correctly shown in WebUI (at least on 21.02.0-rc1):
![Screenshot 2021-05-03 13 23 21](https://user-images.githubusercontent.com/4768176/116929137-da7dd300-ac12-11eb-9f73-5c9e20dbd7e5.png)
This is definitely not an apropriate repo for this issue.
