### ISSUE TITLE
DynamicList does not show in the GridSection (luci-20.02, js)

### ISSUE THREAD

**Issue by iuncuim** [openwrt/luci#4993]
I made a simple page that used DynamicList and GridSection.
In edit mode, the data is displayed normally, but it is not displayed in tab form.
If I use an "option" in the configuration file instead of "list", it is displayed correct.
LuCI openwrt-21.02 branch (git-21.088.35541-d627abe) 
![Снимок экрана от 2021-04-16 17-37-25](https://user-images.githubusercontent.com/15281352/115040927-a0a29200-9eda-11eb-818e-e1fda545b96e.png)

Config file in this case:
```
config pingcontrol 'pingcontrol'
	option check_period '30'
	option sw_before_modres '3'
	option sw_before_sysres '0'
	option enabled '0'
	option iface 'lan'
	list testip '1.1.1.1'

config pingcontrol 'dddddd'
	option iface 'lan'
	option check_period '60'
	option sw_before_modres '77'
	option sw_before_sysres '0'
	option testip '192.168.1.11 1.1.1.1 2.2.2.2 3.3.3.3 4.4.4.4'
	option enabled '1'
```
Web page:
```
		m = new form.Map('pingcontrol', _('PingControl'));
		m.description = _("Server availability check");

		s = m.section(form.GridSection, 'pingcontrol', _('Settings'));
		s.addremove = true
		s.nodescriptions = true

		o = s.option(form.DynamicList, 'testip', _('IP address of remote servers'));
		o.rmempty = false;
		o.datatype = 'ipaddr';
```
@hnyman I found an old topic about [lua](https://forum.openwrt.org/t/how-do-i-add-list-in-a-config-file-instead-of-option-in-luci-using-cbi/49913). It is now possible for luci (with js frontend) to generate option instead of list?

**Comment by jow-** [comment]
@iuncuim - the underlying bug in form.js is fixed. If you can't wait for the fix (or if you'd like to present the values differently anyway) you could override `textvalue()`, e.g.:

```javascript
o = s.option(form.DynamicList, 'testip', _('IP address of remote servers'));
o.rmempty = false;
o.datatype = 'ipaddr';
o.textvalue = function(section_id) {
	var cval = L.toArray(this.cfgvalue(section_id));
	return cval.length ? '%h'.format(cval.join(', ')) : E('em', _('No IP addresses configured'));
};

```

**Comment by iuncuim** [comment]
@jow- Thank for your fix and example. Nice work!

**Comment by iuncuim** [comment]
@jow- Could you explain this is bug or my mistake?
When I add this construction to gridsection:
```
var callFileList = rpc.declare({
	object: 'file',
	method: 'list',
	params: [ 'path' ],
	expect: { entries: [] },
	filter: function(list, params) {
		var rv = [];
		for (var i = 0; i < list.length; i++)
			if (list[i].name.match(/^tty[A-Z]/) || list[i].name.match(/^com[0-9]/))
				rv.push(params.path + list[i].name);
		return rv.sort();
	}
});
...
		o = s.option(form.Value, 'devicename', _('Port'));
		o.rmempty = false;
		o.load = function(section_id) {
			return callFileList('/dev/')
			.then(L.bind(function(devices) {
				for (var i = 0; i < devices.length; i++)
					this.value(devices[i]);
				this.value(i);
				return form.Value.prototype.load.apply(this, [section_id]);
			}, this));
		};
```
I get this: 
![Снимок экрана от 2021-05-06 12-33-48](https://user-images.githubusercontent.com/15281352/117276494-a18a6c00-ae67-11eb-8b0f-294bd8ca057d.png)
With other type of section I get normal list of ports without iterance
