### ISSUE TITLE
luci add pptp interface mtu option missing

### ISSUE THREAD

**Issue by ptpt52** [openwrt/luci#5009]
I cannot find any web ui for option mtu while adding pptp interface

**Comment by ptpt52** [comment]
I notice that, in file: protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pptp.js
```
                o = s.taboption('advanced', form.Value, 'mtu', _('Override MTU'));
                o.placeholder = dev ? (dev.getMTU() || '1500') : '1500';
                o.datatype    = 'max(9200)';
```
there is code for mtu option, but somehow missing in web ui, why?

**Comment by feckert** [comment]
I can confirm this. If I use a name other than mtu, then the option appears.
I'll have to take a closer look to see if this is related to the default options for all protocols.

**Comment by ptpt52** [comment]
the same situation is when add interface with proto ppp

**Comment by ptpt52** [comment]
it seems mtu option is place on physical tab, but no physical tab for ppp/pptp

**Comment by rmilecki** [comment]
"Override MTU" should be present in the Advanced tab. I did quick test using 21.02-rc2:

![general](https://user-images.githubusercontent.com/452972/121513373-144cb100-c9eb-11eb-93e9-7c102fe08cef.png)

![advanced](https://user-images.githubusercontent.com/452972/121513383-1747a180-c9eb-11eb-8eb3-1945710d0666.png)

Please provide screenshot from you interface

**Comment by ptpt52** [comment]
in the current version, it is fixed.
