### ISSUE TITLE
luci-app-mwan3: Renaming the current Load balancing label in LuCI navigation

### ISSUE THREAD

**Issue by jamesmacwhite** [openwrt/luci#5022]
@feckert @aaronjg 

This is something minor but currently the mwan3 navigation menu label is "Load balancing" in LuCI for both the Status and Network menu. Because of the combination of both load balancing and failover functionality, should the label be renamed to something that is more encompassing of it's feature set e.g. "Multi WAN".

**Examples could include:**

For the status menu:

* Multi WAN Status
* mwan3 Status

For the network menu:

* Multi WAN
* mwan3 Interfaces
* Multi WAN Configuration

Having it labelled as load balancing doesn't seem accurate given it's capabilities and uses. I'd be open to other suggests but I think having it labelled as Load Balancing isn't really accurate.

**Comment by feckert** [comment]
@jamesmacwhite I have had a patch in my patch set for some time that changes this to `MultiWAN Manager`
```
From: Florian Eckert <fe@dev.tdt.de>
Date: Thu, 6 Apr 2017 12:01:34 +0200
Subject: [PATCH]  luci-app-mwan3: change menu entry name

Signed-off-by: Florian Eckert <fe@dev.tdt.de>
---
 applications/luci-app-mwan3/luasrc/controller/mwan3.lua | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/applications/luci-app-mwan3/luasrc/controller/mwan3.lua b/applications/luci-app-mwan3/luasrc/controller/mwan3.lua
index 1fb9083a53c1a4ca639c8bb9b0ed711abdad008f..f45351e3bb147afd7467bd6eb1d8e396114ee93e 100644
--- a/applications/luci-app-mwan3/luasrc/controller/mwan3.lua
+++ b/applications/luci-app-mwan3/luasrc/controller/mwan3.lua
@@ -16,7 +16,7 @@ function index()

        entry({"admin", "status", "mwan"},
                alias("admin", "status", "mwan", "overview"),
-               _("Load Balancing"), 600).acl_depends = { "luci-app-mwan3" }
+               _("MultiWAN Manager"), 600).acl_depends = { "luci-app-mwan3" }

        entry({"admin", "status", "mwan", "overview"},
                template("mwan/status_interface"))
@@ -38,7 +38,7 @@ function index()

        entry({"admin", "network", "mwan"},
                alias("admin", "network", "mwan", "interface"),
-               _("Load Balancing"), 600).acl_depends = { "luci-app-mwan3" }
+               _("MultiWAN Manager"), 600).acl_depends = { "luci-app-mwan3" }

        entry({"admin", "network", "mwan", "globals"},
                cbi("mwan/globalsconfig"),
--
```

**Comment by jamesmacwhite** [comment]
I think that makes sense. More descriptive and accurate.

**Comment by jamesmacwhite** [comment]
@feckert I think it is worth applying your 2017 patch before 21.02 gets a formal release, what do you think?
