### ISSUE TITLE
Luci theme material text overflow

### ISSUE THREAD

**Issue by thecode** [openwrt/luci#5025]
![image](https://user-images.githubusercontent.com/1858925/116778082-88a14580-aa78-11eb-8f67-6e69c2147e84.png)

![image](https://user-images.githubusercontent.com/1858925/116778109-b2f30300-aa78-11eb-8382-44bb0d7f5159.png)

Issue exists both on OpenWRT 19.0.7 with `luci-theme-material` `git-21.096.73306-254083c-1`
And on OpenWRT 21.02.0-rc1 with `luci-theme-material` `git-20.304.74050-01cefed`

**Comment by stangri** [comment]
I'm unable to reproduce on 21.02.0-rc1 even with the page zoom set to 110% in Chrome. What's your device/browser/page zoom?

**Comment by thecode** [comment]
Tested under 2 Windows 10 (on two different machines) with the following browsers:
- Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
- Microsoft Edge Version 90.0.818.51 (Official build) (64-bit)

Tested with 1920x1200 and 1920x1080 monitors, with different display scaling: 100% and 125%
Reproduced on any page zoom between 50% and 250% (e.g. 50, 67, 75, 100, 150, 175)

However it is related to the aspect ratio of the page, see the example bellow when the the page is narrow (how much depends on the device and zoom, it looks ok. Both pictures bellow are using the same zoom (100%) on the same browser (Chrome), but even it is ok on the narrow you can still see the text is on the button side of the border.
Narrow:
![image](https://user-images.githubusercontent.com/1858925/116805487-9f56a380-ab2f-11eb-8714-2fc22f7d3d8d.png)
Wide:
![image](https://user-images.githubusercontent.com/1858925/116805541-dfb62180-ab2f-11eb-937b-db3549f84ffa.png)

Thanks for looking into it.

**Comment by jorgebnunes** [comment]
Hi, I have the same problem.
If you edit /www/luci-static/material/cascade.css, search for 

.cbi-progressbar::after{font-family:monospace;font-size:1.3em;font-weight:700;

and change "1.3em" to "1.0em"

And voilá, problem solved :-)

**Comment by thecode** [comment]
Closing this issue, although this is still not fully fixed (text is still 1-2 pixels off),  text size was reduced (last tested with `git-22.339.35089-7af4a64`) so it no longer overlaps.
![image](https://user-images.githubusercontent.com/1858925/213946183-cb1f5eac-11d5-425e-85a4-3f7075aba519.png)
