### ISSUE TITLE
Compile fail on latest master

### ISSUE THREAD

**Issue by ByteEnable** [openwrt/luci#5027]
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for samba4-libs found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package samba4-libs.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for samba4-server:
 *      libpam
 * opkg_install_cmd: Cannot install package samba4-server.

**Comment by dibdot** [comment]
Not an LuCI issue at all, probably related to that one: http://lists.openwrt.org/pipermail/openwrt-devel/2021-April/034908.html
