### ISSUE TITLE
luci-app-mosquitto

### ISSUE THREAD

**Issue by coelner** [openwrt/luci#5030]
the application ist only visible if the mosquitto package is selected. IMHO it should be the other way round and add a '+'

https://github.com/openwrt/luci/blob/3e5aacd760003ae744f8764f8f5bb069107e4b2a/applications/luci-app-mosquitto/Makefile#L4

**Comment by dibdot** [comment]
@karlp

**Comment by karlp** [comment]
no, it can't be done I'm afraid.  "mosquitto" is a virtual package, provided by either mosquitto-ssl or mosquitto-nossl, and you can't +select that way. sorry!
