### ISSUE TITLE
Can't create/edit any DDNS entry

### ISSUE THREAD

**Issue by Satoscio** [openwrt/luci#5033]
![Capture](https://user-images.githubusercontent.com/58695673/117039872-8d305d00-ad09-11eb-887c-7fbcb5d4e579.PNG)

I receive this error screen every time I try to edit a DDNS entry.
Device: vant-6 (Technicolor TG789vac V2)
OpenWRT 15.05.1

**Comment by dibdot** [comment]
OpenWrt Chaos Calmer 15.05 is unsupported.
