### ISSUE TITLE
LuCI does not offer NFS mounts

### ISSUE THREAD

**Issue by smoe** [openwrt/luci#5036]
I manually mounted a remote drive to my router but this does not seem to be supported from with LuCI. The mount is shown on luci/admin/system/mounts and I am invited to unmount it, but nowhere I saw that I could mount it.

The "why do I want that" is that storage may be more than the single SSD attached via USB or PCIe. A NAS already active on the local network comes to mind. In my experimental setup I am actually tunneling to one via the Internet. Works nicely. This could then be used to share that remote storage locally, to store data (like video or sensor input) or (shameless promotion) for running BOINC without the need to have physical access to the device and a USB stick.

Is the management of NFS mount via LuCI something that would be desirable to have? Where should that be implemented? Extension of the existing mount functionality? Or a separate luci-app-nfs in analogy to luci-app-samba?

Thanks!
Steffen

**Comment by jow-** [comment]
It is a limitation of the underlying `block mount` functionality in OpenWrt. It currently does not support any kind of network volumes, hence no possibility to expose that in LuCI.
