### ISSUE TITLE
Luci theme OpenWrt2020 - Firewall page blank

### ISSUE THREAD

**Issue by cybrnook** [openwrt/luci#5040]
Using latest 21.02 snapshot, current as of today (05/06/2021) the Firewall page just displays as blank. This was tested on latest edge chromium. I have noticed this on the Master branch as well. I have attempted to reload the page, clear cache, none seem to help:

![image](https://user-images.githubusercontent.com/22136734/117362810-b8da5100-ae89-11eb-980b-e6f5c9a78894.png)

Switching to Bootstrap, I have no issues:
![image](https://user-images.githubusercontent.com/22136734/117363019-00f97380-ae8a-11eb-8e7f-9e598ba621da.png)

**Comment by jow-** [comment]
Can you press F12 and look for errors in the browser console?

**Comment by cybrnook** [comment]
Nothing life changing stood out. I took a screenshot of the main page and the firewall page. Unless I am looking at the wrong place, nothing major stood out to me. As a side note, I tested with latest firefox as well, and it's the same behavior.

Main Page:
![Main Page](https://user-images.githubusercontent.com/22136734/117459009-e7533d00-af18-11eb-94d6-67b567e54f60.png)

Firewall Page:
![Firewall Page](https://user-images.githubusercontent.com/22136734/117459034-f0440e80-af18-11eb-89ad-5f90340514b5.png)

**Comment by jow-** [comment]
Seems the issue is triggered when ip6tables is removed from the system.

**Comment by cybrnook** [comment]
That would make sense since I have IPV6 disable in my .config.

**Comment by cybrnook** [comment]
Thanks @jow-
