### ISSUE TITLE
luci-app-lxc: complaining "no templates for your architecture (x86_64)" while running on a x86_64 device.

### ISSUE THREAD

**Issue by hathlife** [openwrt/luci#5044]
![image](https://user-images.githubusercontent.com/19867269/117686551-9037bb80-b1e9-11eb-9178-21d0291cd53f.png)
somehow the app (or lxc backend, maybe?) sent `x86_64` as name of arch instead of the correct one `amd64` to the container image site, which should not happen.

**Comment by dibdot** [comment]
Which container image site/url did you use, e.g. what's configured in /etc/config/lxc?

**Comment by hathlife** [comment]
> Which container image site/url did you use, e.g. what's configured in /etc/config/lxc?

Both`images.linuxcontainer.org` and `repo.turris.cz/lxc` share the same error.

and here's `/etc/config/lxc` details:
```
config lxc 'lxc'
        option ssl_enabled '1'
        option min_space '100000'
        option min_temp '100000'
        option url 'repo.turris.cz/lxc'
```

**Comment by dibdot** [comment]
The turris repo doesn't provide images for x86 or amd64, so your current config is invalid.

I guess (I don't use lxc anymore), that the download url of linuxcontainers has changed or will be redirected or similiar. The current code maps x86_64 to amd64 only for 'images.linuxcontainers.org', see for reference:

https://github.com/openwrt/luci/blob/3c66c5b1651aa25afbff09bee45047da9a0ba43d/applications/luci-app-lxc/luasrc/controller/lxc.lua#L162

To get this working again, you should get a valid download location and change the function in that way, that the mapping only happens, if it does **not** match the turris repo.

**Comment by dibdot** [comment]
No more feedback by TO - closing this.
