### ISSUE TITLE
theme-openwrt-2020: favicon announced a file-type "svg-xml" but is "png"

### ISSUE THREAD

**Issue by SvenRoederer** [openwrt/luci#5051]
The Luci-theme-openwrt-2020 mentions filetype "svg-xml" for the favicon, but the file is "png". This seem to render usually (only tested with firefox) but has potential to cause issues.

https://github.com/openwrt/luci/blob/3c66c5b1651aa25afbff09bee45047da9a0ba43d/themes/luci-theme-openwrt-2020/luasrc/view/themes/openwrt2020/header.htm#L27

I see 3 options:
* change the announces filetype to PNG
* change the favicon-file to svg-type
* drop the file-type property completely and let the browser decide.

**Comment by feckert** [comment]
I would do that uniformly. So that we have that right away for the other themes as well. Make a suggestion with a pullrequest what is the best.

**Comment by SvenRoederer** [comment]
@feckert made PR #5062 for it.

**Comment by jow-** [comment]
Fixed by 184e93d
