### ISSUE TITLE
初始密码不对

### ISSUE THREAD

**Issue by ExternalSD** [openwrt/luci#5052]
我下载了一个openwrt.org官方的linksys wrt1900acs版本，刷完之后web上luci的root密码一直不对，ssh要密码，telnet根本连不上，有大神指点一下么？

**Comment by jjm2473** [comment]
官方的固件没设置密码，luci用户名root，密码空就能登录。如果不能登录，说明你的固件不是官方的，或者以前设置了密码没重置。
