### ISSUE TITLE
In static leases, LUCI shows "none" when multiple MAC adress are used

### ISSUE THREAD

**Issue by Norde** [openwrt/luci#5054]
When multiple MAC addresses are assigned to the same IP, LUCI shows a "none" entry.
(whether the addition of the static lease is done via LUCI or manually)

LUCI rev : git-21.107.58152-c19c716-1

/etc/config/dhcp
>config host
>option mac '00:AA:BB:CC:DD:EE 02:AA:BB:CC:DD:EE'
>option name 'HardwareTEST'
>option dns '1'
>option ip '192.168.1.158'

<br>

In LUCI static leases tab:
![image](https://user-images.githubusercontent.com/6858706/118471101-aa046180-b707-11eb-84c0-dcd3190c432d.png)
(_aucun_ = _none_)

**Comment by jow-** [comment]
Fixed with https://github.com/openwrt/luci/commit/7b931da4779c68f5aef5908286c2ae5283d2dece
