### ISSUE TITLE
[luci-app-ddns] Wrong string for "Domain" tooltip

### ISSUE THREAD

**Issue by lorthirk** [openwrt/luci#5056]
In https://github.com/openwrt/luci/blob/94d35bbaa1e10c579d30125bf13a9c784253ec85/applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js#L734-L736 the "Domain" field is declared, but the tooltip is the one for the "Username" fields. I know there's a Weblate project already, but I think that since the string is actually duplicated from the Username field, it's not currently possible to translate it there in Weblate as the system treats those as the same string. Should this be changed in the source code?

**Comment by feckert** [comment]
Yes please open a pullrequest for this
