### ISSUE TITLE
luci-app-samba4 error on OpenWrt 21.02

### ISSUE THREAD

**Issue by People-11** [openwrt/luci#5080]
luci-app-samba4 will display "Uncaught TypeError: Cannot read property 'split' of undefined" error on OpenWrt 21.02.0-rc1 r16046-59980f7aaf r0-fb18548

**Comment by xcyll** [comment]
![IMG_1157](https://user-images.githubusercontent.com/63227888/120060068-1d06c400-c088-11eb-8377-6f6a2a1654bd.jpg)

**Comment by 1715173329** [comment]
Ping @jjm2473.
