### ISSUE TITLE
cannot change luci network device macvlan device name

### ISSUE THREAD

**Issue by ptpt52** [openwrt/luci#5081]
![image](https://user-images.githubusercontent.com/5331426/120098407-57e02900-c168-11eb-8f55-33acf14cda06.png)

**Comment by ptpt52** [comment]
the device name for macvlan cannot change

**Comment by jow-** [comment]
This is intentional. After creating a device configuration, options changing the device identity cannot be changed anymore. If you really want to change the name, you need to reset the configuration and recreate it.

**Comment by ptpt52** [comment]
@jow-  not really true
I create a new macvlan and name it as `mvlan01`
after I try to edit, it display `eth0.1mac2`, not the `mvlan01`

**Comment by ptpt52** [comment]
it is easy to test
1. create new macvlan and name it to somewhat `xxxx`
2. save and then reopen edit, it display the wrong name.
