### ISSUE TITLE
luci sets ra_mtu by default to 0, which is wrong and breaks DHCPv6 assignment

### ISSUE THREAD

**Issue by infinity0** [openwrt/luci#5082]
When configuring interfaces via luci and setting advanced options, luci fills in options with what it thinks are the default values. This breaks DHCPv6 on all my interfaces.

The issue is fixed immediately when I edit `/etc/config/dhcp` manually, remove `option ra_mtu '0'` and run `/etc/init.d/odhcpd restart`.

The documentation on https://openwrt.org/docs/techref/odhcpd is wrong, the default value for `ra_mtu` is in fact not 0 but - (no default value) as indicated in https://github.com/openwrt/odhcpd

**Comment by hnyman** [comment]
That is a known bug that has already been fixed both in master and the 21.02 branch.
