### ISSUE TITLE
No 5Ghz WiFi Mi Router 4A Gigabit Edition using OpenWrt 21.02 RC2

### ISSUE THREAD

**Issue by zandatsu07** [openwrt/luci#5097]
![Screenshot-6](https://user-images.githubusercontent.com/75350960/120533854-c4cb1b80-c413-11eb-8320-2c08219c66dc.png)

I hope this issue will fix in the Official release

**Comment by stangri** [comment]
Can you elaborate what the issue is? By default both radios are disabled, you need to enable them both.

Also, if the issue is with the actual radio, not the WebUI, this is the wrong repo.

**Comment by jow-** [comment]
You need to report this bug at https://bugs.openwrt.org/ - there is nothing at the LuCI ui side we can do about it.
