### ISSUE TITLE
luci-mod-network: unable to set VLAN (802.1q) device MAC address

### ISSUE THREAD

**Issue by anyuta1166** [openwrt/luci#5102]
I've recently updated my OpenWrt installation from 19.07 to the recent snapshot and found that I cannot set the MAC address of the WAN interface via LuCI anymore.

My WAN configuration is like this:

```
network.wan=interface
network.wan.proto='dhcp'
network.wan.device='eth1.101' <--- VLAN
```

Before update I had "Override MAC address" option in Interfaces - WAN - Advanced settings

After update there is no "Override MAC address" option in Interfaces - WAN - Advanced settings. It seems that such settings has moved to the new Interfaces - Devices section. But the is no "MAC address" option for a VLAN device, this option appears only for physical interfaces and bridges.

As a workaround I can set the MAC address from the command line in the old way via uci set network.wan.macaddr='xx:xx:xx:xx:xx:xx'  but it would be appreciated to bring this option back to LuCI.

**Comment by jow-** [comment]
In the Devices configuration, click "Add device configuration", keep "Device type" set to "Network device", select "eth1.101" as "Existing device" and enter the MAC address you want to set on it.

I'll adjust the devices config screen to make this easier.
