### ISSUE TITLE
luci on lighttpd not working

### ISSUE THREAD

**Issue by DocMAX** [openwrt/luci#511]
i followed the instrucions on

​http://wiki.openwrt.org/doc/howto/luci.on.lighttpd

but it doesnt work:

/usr/lib/lua/luci/dispatcher.lua:526: attempt to index local 'f' (a nil value)
stack traceback:
/usr/lib/lua/luci/dispatcher.lua:526: in function 'createindex'
/usr/lib/lua/luci/dispatcher.lua:534: in function 'createtree'
/usr/lib/lua/luci/dispatcher.lua:202: in function 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:169: in function </usr/lib/lua/luci/dispatcher.lua:168>

**Comment by jow-** [comment]
Make sure that Lighttpd is running as root, otherwise LuCI will nto function properly.

**Comment by cshoredaniel** [comment]
See #734 .  Marking as duplicate as #734 has more information.
