### ISSUE TITLE
Luci displays UCI Boolean values incorrectly

### ISSUE THREAD

**Issue by ngehrsitz** [openwrt/luci#5131]
According to the [UCI Documentation](https://openwrt.org/docs/guide-user/base-system/uci#file_syntax) Boolean values may be  '0', 'no', 'off', 'false' or 'disabled'  or '1' , 'yes', 'on', 'true' or 'enabled'. However if i set a variable to 'on' the checkbox in the webinterface is not correctly set:
```
root@OpenWrt:~# uci get system.ntp.enable_server
on
```
I have traced the issue to the following [code segment](https://github.com/openwrt/luci/blob/6e0af9320474d6c0635b629422278fac7eef1c68/modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js#L269):
```
o = s.taboption('timesync', form.Flag, 'enable_server', _('Provide NTP server'));
o.ucisection = 'ntp';
o.depends('enabled', '1');
```
If i manually replace the '1' with 'on' it works as expected. I think the correct way to handle this would be to have the value parsed to a boolean first. Apparently [get_bool](https://openwrt.github.io/luci/api/modules/luci.model.uci.html#Cursor.get_bool) already exists for that purpose in the lua libary.

**Comment by jow-** [comment]
Yes, a known limitation. I suggest to stick to `0` and `1` values only. A proper fix will be a little bit extensive and unlikely to happen soon.
