### ISSUE TITLE
Problem compiling 'ksmbd' and 'omcproxy'

### ISSUE THREAD

**Issue by Kurruk007** [openwrt/luci#5134]
When trying to compile OpenWRT with my version of LuCI, I can see errors reported against the makefiles:
```
ERROR: please fix feeds/myluci/applications/luci-app-ksmbd/Makefile - see logs/feeds/myluci/applications/luci-app-ksmbd/dump.txt for details
ERROR: please fix feeds/myluci/applications/luci-app-omcproxy/Makefile - see logs/feeds/myluci/applications/luci-app-omcproxy/dump.txt for details
```
The files are showcasing a problem trying to get access to `luci.mk`, ex:
```
Makefile:8: /home/openwrt/feeds/luci/luci.mk: No such file or directory
make[1]: *** No rule to make target '/home/openwrt/feeds/luci/luci.mk'.  Stop.
```

Checking them out, it seems that they try to `include` using direct path:
```
include $(TOPDIR)/feeds/luci/luci.mk
```
instead of relying on the relative one like every other `Makefile`:
```
include ../../luci.mk
```

**Comment by jow-** [comment]
Fixed with 2f0ffd9 for master and d365470 for openwrt-21.02
