### ISSUE TITLE
OLSRD: Changing LQ-Multiplikator is not properly applied (21.02-snapshot)

### ISSUE THREAD

**Issue by Noki** [openwrt/luci#5139]
When changing the OLSRD lq-multiplikator via Luci the changes are not immediately applied. Seems that olsrd is not automatically restarted when the config changes, but the changes are visible in the config file. Manually restarting olsrd / restarting the router solves the issue.

**Comment by feckert** [comment]
I think the following code section is missing in the [olsrd init script](https://github.com/openwrt/routing/blob/master/olsrd/files/olsrd4.init).

```
service_triggers() {
        procd_add_reload_trigger "olsrd" "olsrd6"
}

```

@Noki Could you give theme a try? If this works, please open a P/R.
thanks

**Comment by Noki** [comment]
I tested the trigger as proposed and can confirm that it work. @PolynomialDivision agreed to prepare a commit.

**Comment by PolynomialDivision** [comment]
@feckert Thanks for taking care of that issue! :)

**Comment by Noki** [comment]
@PolynomialDivision thanks for the commit!

**Comment by PolynomialDivision** [comment]
Can be closed. ;)
