### ISSUE TITLE
docker shows no space left while pulling image

### ISSUE THREAD

**Issue by ufoozhenghao** [openwrt/luci#5149]
![1](https://user-images.githubusercontent.com/42081344/123502404-ac4ec980-d67e-11eb-9005-864c2b95ac42.PNG)
using R2s  16gb sd card

can anyone help me?

**Comment by wulfy23** [comment]
normal message that occurs when you run out of space

add more storage

visit forum for further guidance

**Comment by castillofrancodamian** [comment]
It has nothing to do with it, but there are times when I want to download an image and the page reloads, losing progress.
