### ISSUE TITLE
LUCI crash after running for sometime in 15.05 CC release

### ISSUE THREAD

**Issue by joutain** [openwrt/luci#515]
Router model: WD MyNet N750, using the 15.05 final release for about one week, when I tried to login to the router again, it shows the following. but the router is functioning well, i can still get internet now. after reset, it comes to normal, but after another several hours, it happened again. thanks in advance

"/usr/lib/lua/luci/dispatcher.lua:433: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/util.lua:587: Unable to establish ubus connection
stack traceback:
    [C]: in function 'assert'
    /usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>"

**Comment by hnyman** [comment]
Vague. Likely a temprorary problem with ubus. 
Not a Luci issue by itself.
closing this.
