### ISSUE TITLE
Luci shouldn't automatically redirect connections from localhost (e.g. 127.0.0.1) to https

### ISSUE THREAD

**Issue by tim-seoss** [openwrt/luci#5157]
I typically access luci over an ssh tunnel, so my luci urls look like this:

http://127.0.0.1:5678/

As of OpenWRT 21.02.0 rc3, this is automatically redirected to https://127.0.0.1/ - since connections to localhost can't be man-in-the-middled, or eavesdropped (or at least no more so that https connections), it would probably be better to not redirect URLs like http://127.0.0.1/ http://localhost/ http://[::1]/ etc.

If this sounds like a reasonable feature, then I'll be happy to contribute a patch.

**Comment by jow-** [comment]
Not related to LuCI, needs to be done in uhttpd @ OpenWrt base.
