### ISSUE TITLE
Luci-app-nft-qos: Not functioning anymore since r16068 

### ISSUE THREAD

**Issue by Thebroughfamily** [openwrt/luci#5160]
Nft-qos package no longer functions on latest 21.02 snapshot builds, last working build was r16068-4b89b90. Can set limits on the app as normal, no error messages appear but settings have no effect. Timing of issue appears related to the change in the interfaces tab.

**Comment by jow-** [comment]
Problem is the underlying nft-qos scripts being broken since the netifd ifname->device migration. Unrelated to LuCI.

See
