### ISSUE TITLE
PPTP over manually set IP

### ISSUE THREAD

**Issue by ogogon** [openwrt/luci#5178]
If I understand everything correctly, then in the case of choosing the PPTP mode, the IP address of the interface must be set using DHCP.
Meanwhile, I know several providers that do not provide DHCP and require manual setting of the address, mask and default gateway.
In principle, I can set these settings, but without using the luci interface.
Can the PPTP section be supplemented with the ability to manually configure the interface?
I apologize if I missed something and there is such an opportunity in luci. Then tell me how to do it.

**Comment by jow-** [comment]
This is not how the OpenWrt configuration works. You first need to set your wan interface to static, then declare another interface, e.g. wan_pptp and set its device to @wan (Alias of wan) and its protocol to pptp as well as the firewall zone to wan.
