### ISSUE TITLE
luci-app-acl do not work on 21.02-RC3

### ISSUE THREAD

**Issue by erdoukki** [openwrt/luci#5179]
Environment: (mvebu, espressobin-ultra, OpenWrt 21.02-RC3)

https://forum.openwrt.org/t/changing-the-username-root/100678/14

> I have tried on 21.02-RC3, not working, (error on logging).
> I tried the 3 methods, plain password, hash password and shadow (with installing all shadow packages and adding a user...)
> No success...

**Comment by jow-** [comment]
Define what is not working. Account management page crashing, /etc/config/rpcd not updated? Login not working? Login working but blank page displayed?

Also what „error on logging“ exactly? Please paste the relevant lines

**Comment by erdoukki** [comment]
I will retest ASAP, but it was a message in the login page of unknown login... (something like this, will correct the report soon)

**Comment by jow-** [comment]
You might need to manually restart/etc/init.d/rpcd after adding the account.

**Comment by erdoukki** [comment]
```
Invalid username and/or password! Please try again.
```

**Comment by erdoukki** [comment]
```
Invalid username and/or password! Please try again.
```

still issued when trying admin login after a full reboot !

**Comment by jow-** [comment]
It worked for me on 21.02 rc3 after restarting rpcd on the command line. Was able to log in with the newly added user.

**Comment by erdoukki** [comment]
okay for me on 21.02-RC3 with hash password after restarting rpcd service or a manual reboot of OpenWrt.
