### ISSUE TITLE
Blank devices list when setting up bond interface

### ISSUE THREAD

**Issue by elvisimprsntr** [openwrt/luci#5195]
21.02.0rc1,2,3

When attempting to create or edit an aggregated link interface, LuCi brings up a bank list of devices to bond.  ![image](https://user-images.githubusercontent.com/1215508/125943376-75e3c830-9600-4ed1-abcc-668fde6ca7e2.png)

You have to select 1 or more blank interfaces in order to save the interface, then manually edit the /etc/conf/network file to add devices.

@LGA1150

**Comment by LGA1150** [comment]
@he-ma

**Comment by he-ma** [comment]
@LGA1150
This is WIP, waiting to be merged
https://github.com/openwrt/luci/pull/5190

**Comment by jow-** [comment]
Fixed via #5190
