### ISSUE TITLE
Broken dependencies for luci 

### ISSUE THREAD

**Issue by Sabonez** [openwrt/luci#5221]
Hi, couldn't build image with such error:

_Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 *      libubus20191227
 * opkg_install_cmd: Cannot install package luci._

I saw the new version of libubus in repos, but now dependencies are broken. Please, check it.

**Comment by feckert** [comment]
Duplicate https://github.com/openwrt/luci/issues/5219

**Comment by hnyman** [comment]
Wait until also packages have been rebuilt for 19.07.8 or 21.02.0-rc4, and use those revisions, and then build image.  It 1-2 days, probably.
