### ISSUE TITLE
Fire Wall Traffic Rules Time Restrictions - dot v.s. colon

### ISSUE THREAD

**Issue by farmergreg** [openwrt/luci#5225]
I'm running OpenWrt 21.02.0-rc3

In the time restrictions tab, the example time has periods in the example (hh.mm.ss), but the actual text field requires colons. I think it should show (hh:mm:ss) as the example instead of (hh.mm.ss). Here's a screen shot showing the typo:

![image](https://user-images.githubusercontent.com/857809/128204205-638009be-1562-496c-a1c4-22db857f05c9.png)

**Comment by stangri** [comment]
Thanks, should be fixed in master and 21.02 after buildbots build new package.

**Comment by farmergreg** [comment]
thanks, that was fast!!
