### ISSUE TITLE
after upgrade firmware to openwrt cannot login

### ISSUE THREAD

**Issue by adelinodst** [openwrt/luci#5229]
Hi, please help I upgrade firmware of my KIMAX BS-U35WF to Openwrt I cannot login anymore
try username: root pass: blank 
nothing help.
Thank you

**Comment by adelinodst** [comment]
try also to ssh but still cannot login

**Comment by wulfy23** [comment]
read this: https://github.com/openwrt/luci/issues/5202

and best to take this to the openwrt forum... luci is likely and indicator here... and speaks little to the underlying cause... you will get better input on the forum...

**Comment by jow-** [comment]
Sounds unrelated to LuCI
