### ISSUE TITLE
Compile Openwrt v21.02.0-rc4 with passwall error

### ISSUE THREAD

**Issue by izhamcaster** [openwrt/luci#5231]
When compile Openwrt v21.02.0-rc4 with passwall i got this error,please help me.....

make[3]: Leaving directory '/home/shisui/openwrt/package/libs/gmp'
time: package/libs/gmp/compile#233.57#36.77#212.00
make[2]: Leaving directory '/home/shisui/openwrt'
make[1]: *** [package/Makefile:108: /home/shisui/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/shisui/openwrt'
make: *** [/home/shisui/openwrt/include/toplevel.mk:230: world] Error 2
shisui@shisui-HP-430-Notebook-PC:~/openwrt$ 

![image_2021-08-06_22-11-21](https://user-images.githubusercontent.com/83901195/128523619-83c5faf4-9897-470f-a668-801c485e7d9a.png)

**Comment by jow-** [comment]
Looks unrelated to LuCI
