### ISSUE TITLE
Timezone cannot find China, suggest change "Shanghai" to "China"

### ISSUE THREAD

**Issue by RadioOperator** [openwrt/luci#5232]
Hi, refer to attached
![Timezone cannot find China](https://user-images.githubusercontent.com/27762920/128582396-9b90e344-6391-4e9a-a45c-2f3591544804.PNG)

**Comment by stangri** [comment]
This comes from [tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), you should bring it up with [ICANN](https://en.wikipedia.org/wiki/Tz_database) if you want this changed.

**Comment by RadioOperator** [comment]
@stangri Hi, thanks, I hope you/your openwrt could change this in further new release.

**Comment by hnyman** [comment]
Like stangri said, the timezone names come from the globally standardised database, mandated by IANA / ICANN.

https://www.iana.org/time-zones

https://data.iana.org/time-zones/tz-link.html

> Timezones are typically identified by continent or ocean and then by the name of the largest city within the region containing the clocks. For example, America/New_York represents most of the US eastern time zone; America/Phoenix represents most of Arizona, which uses mountain time without daylight saving time (DST);

The standard is to use city names, so there will not be "Asia/China"

**Comment by RadioOperator** [comment]
Copy that, thanks.
