### ISSUE TITLE
Path to autoupdate | Ability to use URL in LuCI for flashing

### ISSUE THREAD

**Issue by BryanQuigley** [openwrt/luci#5238]
I opened this on the [forum](https://forum.openwrt.org/t/path-to-auto-update/103154), but realized that the majority of things initially I want to do are in luci.

My thought is the place to start is with "Ability to use URL in LuCI for flashing".  Are there any concerns with adding that feature?  (or suggestions on a better place to start). Thanks!

**Comment by jow-** [comment]
No concerns adding this feature, feel free to open a PR implementing it.

**Comment by BryanQuigley** [comment]
Quick question on implementation.. I could make a brand new section for it, like:
![image](https://user-images.githubusercontent.com/702754/129284561-b44b46fa-3124-4e73-acd2-e248ad75698c.png)

(This may initially have less options then uploading a file..)

or I could add URL support to the ui:uploadFile function?

Thanks!
Bryan
