### ISSUE TITLE
Feature request: support MFA for login to LuCI

### ISSUE THREAD

**Issue by CAFxX** [openwrt/luci#5244]
I would like to suggest adding opt-in support for MFA to the LuCI login process. 

To cover most possible scenarios, and specifically including those in which the router on which LuCI is running has lost all connectivity to the internet and therefore the clock is not guaranteed to be correct, it would be ideal to support at least two alternatives:

- fallback in case the other methods can't be used (no internet connectivity, incorrect clock, loss of TOTP device, ...): router-generated one-time recovery codes
- TOTP (alternatively: email-based one-time code, but I would argue TOTP is a superior alternative)

The user flow would be something pretty standard like:

1. user is shown user/password prompt (no change)
2. user submits user/password (no change)
3. if user/password is incorrect, go back to 1 and show an error (no change) 
4. if MFA is disabled, go to 8
5. prompt the user to insert the second factor (and offer the option to fallback to the one-time recovery code)
6. user submits second factor
7. if second factor is incorrect, go back to 5 and show an error
8. user is logged in, show full LuCI UI (no change)

---

note: MFA and this feature request is, in general, incomplete without brute-forcing protection: perfection is the enemy of good so to keep this feature request well-scoped I'm not including brute-forcing protection here

**Comment by jow-** [comment]
I have neither plans nor time to implement this. If you come up with an example implementation and open a PR for it, I will consider it.
