### ISSUE TITLE
Who can redesign the bootstrap ui, now the bootstrap ui is really ugly

### ISSUE THREAD

**Issue by JSZMonkey** [openwrt/luci#5245]
Who can redesign the bootstrap ui, now the bootstrap ui is really ugly pls！！！

**Comment by castiel652** [comment]
You can use openwrt-2020 if you want something newer

**Comment by thermochromic** [comment]
Not everyone thinks its _really ugly_ . Just saying.

**Comment by jow-** [comment]
Nothing actionable.
