### ISSUE TITLE
What's the default password?

### ISSUE THREAD

**Issue by Lizhny** [openwrt/luci#5268]
I got a soft-routing. It is" Powered by LuCI Master (git-20.088.29068-cebe120) / OpenWrt R20.4.8". After reset it, I was asked to input the password to login in. But I am a reall rookie, I dont know anything about the password. It here some deafault password? I hava already tried "password","root","admin". Could you plz give me some help. Thank you

**Comment by hnyman** [comment]
There is no official version OpenWrt R20.4.8.
You likely have somebody's private build, which might have non-standard passwords. Ask the author.

The normal default is user "root" and no password.
