### ISSUE TITLE
luci-app-https-dns-proxy: Add [Proxy Server] setting tips or sample

### ISSUE THREAD

**Issue by Sieuno** [openwrt/luci#5274]
There is no any tips or illustration about Proxy Server setting.
And there is nothing about how to set this item on : Openwrt wiki
https://openwrt.org/docs/guide-user/services/dns/doh_dnsmasq_https-dns-proxy
Consider socks4a:// or socks5h:// is not widely known by people. It is necessary add a tips about it.

Original project show the method
https://github.com/aarond10/https_dns_proxy

**Comment by stangri** [comment]
Resolved in updated README via https://github.com/stangri/docs.openwrt.melmac.net/commit/4ba99712bd0f3a0bb9d2a1f732e89d7cf4338465
