### ISSUE TITLE
luci-app-mwan3 missing up/down buttons

### ISSUE THREAD

**Issue by teqlee** [openwrt/luci#5280]
Tested on Nanopi R4S, LuCI Master (git-21.223.61040-6045f58), OpenWrt SNAPSHOT r17337-ed9341dd78,
luci-app-mwan3 - git-21.224.46469-57688b9
mwan3 - 2.10.11-1

The Up/Down buttons for rules, members, policys.... is missing like this:
![image](https://user-images.githubusercontent.com/33137579/129571549-75b98f4b-bb9f-485a-8b3f-a60225cbd1d4.png)
@feckert

**Comment by feckert** [comment]
Thanks for testing.
From my point if view it makes only sense for the rules.
Fixed with https://github.com/openwrt/luci/commit/c700cbc59e052602d0b295e3c08a448b8e6f5e29
