### ISSUE TITLE
 luci-proto-qmi parsing comands to UCI bugs/ missing documentation?

### ISSUE THREAD

**Issue by professor-jonny** [openwrt/luci#5283]
Hi
I'm not sure but I believe the config setting set from luci are written to the network config file incorrectly from luci
for example pdptype has the options as below as found here:
https://openwrt.org/docs/guide-user/network/wan/wwan/ltedongle

`IP (for IPv4), IPV6 (for IPv6) or IPV4V6 (for dual-stack)`

When I set ipv4 in luci it writes IPv4 in to the network config where I believe it should write IP ( for IPv4)

Also the option "auto connect" writes "auto" as an UCI option 

Also the option "delegate" does not seem to be listed in UCI commands or the UQMI documentation.

below is the qmi settings from the network config file:

`config interface 'skinny'
	option proto 'qmi'
	option device '/dev/cdc-wdm0'
	option delegate '0'
	option apn 'skinnybroadband'
	option auth 'none'
	option pdptype 'ipv4'
	option delay '20'
	option auto '0'`

and this is what i believe it should be:

`config interface 'skinny'
	option proto 'qmi'
	option device '/dev/cdc-wdm0'
	option delegate '0'
	option apn 'skinnybroadband'
	option auth 'none'
	option pdptype 'IP'
	option delay '20'
	option autoconect '0'`

In the qmi.js file it has the below which I believe is incorect but I'm not at all skilled in java:

`		o = s.taboption('general', form.ListValue, 'pdptype', _('PDP Type'));
		o.value('ipv4v6', 'IPv4/IPv6');
		o.value('ipv4', 'IPv4');
		o.value('ipv6', 'IPv6');
		o.default = 'ipv4v6';`

I think this here:
`o.value('ipv4', 'IPv4');`
should say:
`o.value('ipv4', 'IP');`

Am I correct in thinking this or am I missing something?

**Comment by jow-** [comment]
These values match the ones expected by the netifd protocol handler here:
https://github.com/openwrt/openwrt/blob/master/package/network/utils/uqmi/files/lib/netifd/proto/qmi.sh#L249
