### ISSUE TITLE
Rosy File Server 'File Server/Administration' button missing 

### ISSUE THREAD

**Issue by arky** [openwrt/luci#5288]
The 'Rosy File Server/ Administration' button fails to appear on the file server views. It only appears in the admin views.

### Default File server view

![3e76f39404b5df720ac3b019f52f81e4637ab000_2_690x205](https://user-images.githubusercontent.com/808895/129936725-79d2863b-3e55-4236-835f-b4de42f90af1.png)

### Admin view 

![955288d13b6f3d98fde8f001c7e6a9496f491a8e_2_690x153](https://user-images.githubusercontent.com/808895/129936909-b9298d1d-cc61-4f01-908f-2c1d05fa92c2.png)

This might be a regression as this seems to be working during the original commit 
https://github.com/openwrt/luci/pull/2404#issue-241254643

**Comment by arky** [comment]
@jow- @hnyman Any ideas how to resolve this regression?

**Comment by MocconaCoffee** [comment]
Upvote, experiencing this issue presently

**Comment by dibdot** [comment]
Maybe we should mark this unmaintained package as broken and remove the base package as well (move to packages-abandoned)?

**Comment by arky** [comment]
@hnyman Could you please point me to where this package now resides in unmaintained packages? Thanks
