### ISSUE TITLE
RPC call to session/access failed with error -32002: Access denied

### ISSUE THREAD

**Issue by yong-ruilin** [openwrt/luci#5302]
I got the following error after logging in：

RPCError

RPC call to session/access failed with error -32002: Access denied
  at handleCallReply (http://192.168.1.234/luci-static/resources/rpc.js:82:7)

![image](https://user-images.githubusercontent.com/81365507/130925700-065a075e-a48a-44e2-b8df-7f7f5e1a2296.png)

Can you help me solve it？

**Comment by jow-** [comment]
Looks as if your ACL definitions are broken or improperly set up. Ensure that files in `/usr/share/rpcd/acl.d/` are well formed, that the login account in `/etc/config/rpcd` references the correct groups (either at least `list read 'luci-base'; list read 'unauthenticated'; list write 'luci-base'` or full access via `list read '*'; list write '*'`) and that `/etc/config/rpcd` itself is free of syntax errors (verify with `uci show rpcd >/dev/null`).

Confirm with `ubus call session list` on the cli, ensure that the login session contains `"session": [ "access", "login" ]` among its effective ACL rules.

The proper definition for the root login account in `/etc/config/rpcd` should read:
```json
config login
	option username 'root'
	option password '$p$root'
	list read '*'
	list write '*'
```

**Comment by yong-ruilin** [comment]
I still haven't solved the problem.

root@OpenWrt:/# cat etc/config/rpcd                                                                                                 
config rpcd                                                                                                                         
        option socket /var/run/ubus/ubus.sock                                                                                       
        option timeout 30                                                                                                           
                                                                                                                                    
config login                                                                                                                        
        option username 'root'                                                                                                      
        option password '$p$root'                                                                                                   
        list read '*'                                                                                                               
        list write '*'                                                                                                              
                            
root@OpenWrt:/# ubus call session list                                                                                              
{                                                                                                                                   
        "ubus_rpc_session": "00000000000000000000000000000000",                                                                     
        "timeout": 0,                                                                                                               
        "expires": 0,                                                                                                               
        "acls": {                                                                                                                   
                "access-group": {                                                                                                   
                        "unauthenticated": [                                                                                        
                                "read"                                                                                              
                        ]                                                                                                           
                },                                                                                                                  
                "ubus": {                                                                                                           
                        "luci": [                                                                                                   
                                "getFeatures"                                                                                       
                        ]                                                                                                           
                }                                                                                                                   
        },                                                                                                                          
        "data": {                                                                                                                   
                                                                                                                                    
        }                                                                                                                           
}                                                                                                                                   
{                                                                                                                                   
        "ubus_rpc_session": "fecff812eae14df54628b8715b893418",                                                                     
        "timeout": 3600,                                                                                                            
        "expires": 3589,                                                                                                            
        "acls": {                                                                                                                   
                "access-group": {                                                                                                   
                        "allow-full-uci-access": [                                                                                  
                                "read",                                                                                             
                                "write"                                                                                             
                        ],                                                                                                          
                        "luci-app-firewall": [                                                                                      
                                "read",                                                                                             
                                "write"                                                                                             
                        ],                                                                                                          
                        "luci-base": [                                                                                              
                                "read",                                                                                             
                                "write"                                                                                             
                        ],                                                                                                          
                        "luci-base-network-status": [                                                                               
                                "read"                                                                                              
                        ],                                                                                                          
                        "unauthenticated": [                                                                                        
                                "read"                                                                                              
                        ]                                                                                                           
                },                                                                                                                  
                "cgi-io": {                                                                                                         
                        "upload": [                                                                                                 
                                "write"                                                                                             
                        ]                                                                                                           
                },                                                                                                                  
                "file": {                                                                                                           
                        "/": [                                                                                                      
                                "list"                                                                                              
                        ],                                                                                                          
                        "/*": [                                                                                                     
                                "list"                                                                                              
                        ],                                                                                                          
                        "/etc/firewall.user": [                                                                                     
                                "read",                                                                                             
                                "write"                                                                                             
                        ],                                                                                                          
                        "/etc/luci-uploads/*": [                                                                                    
                                "write"                                                                                             
                        ]                                                                                                           
                },                                                                                                                  
                "ubus": {                                                                                                           
                        "file": [                                                                                                   
                                "read",                                                                                             
                                "write",                                                                                            
                                "list",                                                                                             
                                "remove"                                                                                            
                        ],                                                                                                          
                        "luci": [                                                                                                   
                                "getConntrackHelpers",                                                                              
                                "getFeatures"                                                                                       
                        ],                                                                                                          
                        "luci-rpc": [                                                                                               
                                "getBoardJSON",                                                                                     
                                "getHostHints",                                                                                     
                                "getNetworkDevices",                                                                                
                                "getWirelessDevices"                                                                                
                        ],                                                                                                          
                        "network": [                                                                                                
                                "get_proto_handlers"                                                                                
                        ],                                                                                                          
                        "network.interface": [                                                                                      
                                "dump"                                                                                              
                        ],                                                                                                          
                        "uci": [                                                                                                    
                                "changes",                                                                                          
                                "get",                                                                                              
                                "add",                                                                                              
                                "apply",                                                                                            
                                "confirm",                                                                                          
                                "delete",                                                                                           
                                "order",                                                                                            
                                "rename",                                                                                           
                                "set"                                                                                               
                        ]                                                                                                           
                },                                                                                                                  
                "uci": {                                                                                                            
                        "*": [                                                                                                      
                                "read",                                                                                             
                                "write"                                                                                             
                        ],                                                                                                          
                        "firewall": [                                                                                               
                                "read",                                                                                             
                                "write"                                                                                             
                        ],                                                                                                          
                        "luci": [                                                                                                   
                                "read"                                                                                              
                        ],                                                                                                          
                        "network": [                                                                                                
                                "read"                                                                                              
                        ],                                                                                                          
                        "wireless": [                                                                                               
                                "read"                                                                                              
                        ]                                                                                                           
                }                                                                                                                   
        },                                                                                                                          
        "data": {                                                                                                                   
                "token": "9b2f13dbaab50b2a831904df29f31629",                                                                        
                "username": "root"                                                                                                  
        }                                                                                                                           
}            

Can you help me see if there is a problem with these two files? Or is there some libraries and modules missing when I compile luci?
