### ISSUE TITLE
yggdrasil GUI

### ISSUE THREAD

**Issue by systemcrash** [openwrt/luci#5306]
If you install yggdrasil e.g. `opkg update; opkg install yggdrasil luci-app-yggdrasil`, the GUI for 21.02 is behind yggdrasil, which is 0.4.0 currently. 

So navigating to the `keys` tab, shows Encryption * and Signing * keys. But the config has only `PublicKey` and `PrivateKey` which is how `luci-app-yggdrasil` is in `master` branch. 

Is it a simple fix of recompile (using master branch)?

**Comment by feckert** [comment]
Please address this question to the forum.
