### ISSUE TITLE
[wireguard] AllowedIPs should be optional, not required

### ISSUE THREAD

**Issue by keith24** [openwrt/luci#5307]
In wireguard, `AllowedIPs` is optional.  Other implementations, like desktop and phone versions of wg do _not_ require any `AllowedIPs`.  All the wireguard tutorials on google fill in this field, so maybe luci devs thought it was required?  Sometimes it _must_ actually be left blank to allow for routing.  

Consider the following configuration, with clients 1 and 2 behind NAT: 

**Myserver**
```
[Interface]
Address = 10.0.0.1/24

[peer]
PublicKey = <client1's pubkey>
AllowedIPs = 10.0.0.2/32

[peer]
PublicKey = <client2's pubkey>
AllowedIPs = 10.0.0.3/32
```

**Client 1**
```
[Interface]
Address = 10.0.0.2/24

[peer]
PublicKey = <myserver's pubkey>
AllowedIPs = 10.0.0.0/24
Endpoint= <myserver's endpoint>

[peer]
PublicKey = <client2's pubkey>
```

**Client 2**
```
[Interface]
Address = 10.0.0.3/24

[peer]
PublicKey = <myserver's pubkey>
AllowedIPs = 10.0.0.0/24
Endpoint= <myserver's endpoint>

[peer]
PublicKey = <client1's pubkey>
```

The two client machines can still ping each other with this setup, because each client will route all traffic for the wg subnet to myserver.  (10.0.0.0/24 as myserver's allowedIPs).  This works if myserver has forwarding wg0 > wg0 enabled in the firewall.  

Now, say client 1 is running OpenWrt, so we are required to give all its peers AllowedIPs: 

**Client 1 (openwrt)**
```
[Interface]
Address = 10.0.0.2/24

[peer]
PublicKey = <myserver's pubkey>
AllowedIPs = 10.0.0.0/24
Endpoint= <myserver's endpoint>

[peer]
PublicKey = <client2's pubkey>
AllowedIPs = 10.0.0.3/32
```

Since the AllowedIPs for client 2 is more specific than for myserver (`/32` vs `/24`), the openwrt client will try to send data to `10.0.0.3` without attempting to route through `10.0.0.1`.  When pinging, this manifests as a "Destination address required" because no endpoint has been set for client 2.  (It wouldn't get through NAT anyway).  

I've gotten this to work by removing the `AllowedIPs` lines from `/etc/config/network` directly and the routing/forwarding does work.  That's why I think this is a luci problem; I think it will work if the wireguard settings form validators allow it.  

That means this should be an easy fix, if I have succeeded in convincing the team that `AllowedIPs` should not be required.

**Comment by stangri** [comment]
@keith24 if you believe it's a luci problem and you can fix it, feel free to send PR to master branch.

**Comment by Leo-PL** [comment]
The reasoning behind this  makes no sense to me. You might as well not add the peers without AllowedIPs and address at all, as whatever was targeted at this interface, would not match peer with empty AlloweIPs, and be encrypted with the key of the "hub". The hub  is then responsible for routing in between the peers, and re-encrypting the packet. This is why you have to have 'wg0->wg0' forwarding enabled. Even without knowing about each other's keys, the peers would still be reachable.

**Comment by keith24** [comment]
I just recently discovered this too, that I can delete any peer that has no AllowedIPs set and still ping it.  And for this exact reason.  So this was never really a bug.

**Comment by Leo-PL** [comment]
Of course, this doesn't really hurt at all - this might indeed be confusing at the first glance, if other clients, like Android leave this check out. OTOH those clients could also introduce such check - @zx2c4, what do you think?

**Comment by zx2c4** [comment]
This was merged.

**Comment by Leo-PL** [comment]
@zx2c4, true, but I'm wondering if reintroducing this check would be beneficial, not only in LuCI but in other GUIs as well, like on Android or iOS.

**Comment by zx2c4** [comment]
You're using an openwrt issue to request that I add a feature I don't really like into things that aren't openwrt.

**Comment by Leo-PL** [comment]
Ok, let's keep it then.

**Comment by keith24** [comment]
Leo was just noting that the merge was probably for nothing.  It's already merged and does no harm so I say keep it.  

It is kind of handy to switch from a direct connection to a hub/spoke model by removing the `AllowedIPs` and `Endpoint` fields.  Then you can switch back by filling those in again without having to paste in the pubkey and psk again.

**Comment by Leo-PL** [comment]
Makes sense. Also, recently merged was option to disable peers per usual "disabled" property in UCI, but I'm not sure if it had it's LuCI counterpart.

**Comment by zx2c4** [comment]
Oh. Sorry. Okay. I thought you were asking me to add that disabled property to Android and iOS. I think I'm still misunderstanding the thrust though?

**Comment by jow-** [comment]
Can anybody *please* clarify if the setting should be optional or not now?

I am following the chatter here as a non-wireguard user and am not any wiser.

**Comment by zx2c4** [comment]
AllowedIPs is an optional field in the sense that having no allowed ips is a valid state. It's a field that takes 0 or more entries.

**Comment by keith24** [comment]
> Also, recently merged was option to disable peers per usual "disabled" property in UCI

Ok, so this pr was _definitely_ in vain.

**Comment by keith24** [comment]
@zx2c4 is there ever a case where you would have a peer with no AllowedIPs?  Doesn't that just disable the peer?

**Comment by zx2c4** [comment]
Yes. If you want persistent keepalive but nothing else, for example. Or if you're going to populate allowedips dynamically with something else later.

It doesn't totally disable the peer. Handshakes can happen still.

**Comment by keith24** [comment]
Ok so there is a use case and it _should_ be optional.  That explains everything; thanks for clarifying.

**Comment by Leo-PL** [comment]
Also totally clear for me. Thanks!
