### ISSUE TITLE
Netlink Bandwidth Monitor - Host not showing when device not on network

### ISSUE THREAD

**Issue by jpkool** [openwrt/luci#5308]
When a device is not on my network the name of the device does not show up on the dashboard.
If you hover on the MAC Address it shows it there, but I would like to know if there is a way to make sure that if it resolves in DNS  then it should always show it in the host column on the dashboard.

**Comment by jow-** [comment]
Doing that would require querying all details for all hosts in order to find the name via reverse DNS lookups. That would not scale well for many entries, therefor we cannot do that.
