### ISSUE TITLE
How to disable root user access in  Luci

### ISSUE THREAD

**Issue by yuvaramachandran** [openwrt/luci#5324]
I want to restrict the root user access in Luci WebUi only. Instead we can use the other user for login

**Comment by jow-** [comment]
Modify /etc/config/rpcd, and map the login section to another user. The `option username` line specifies the expected username, the `option password '$p$root'` line tells LuCI the expected password. Can be either an entry in the form `$p$xxx` where `xxx` refers to an existing UNIX user in `/etc/shadow` or `$1$...` which is an MD5 digest hash. You can generate such a hash using the `uhttpd -m` command, e.g.:

```bash
root@er-x:~# uhttpd -m 'supersecretpassword'
$1$$Yl/b6vvelYaItZ1kMQdHe.
root@er-x:~# 
```

Example to add a login account with username "luci" and password "s3cret":

```
config login
  option username 'luci'
  option password '$1$$9Tf6VJZsz3W4bG2XPMu3T.'
  option read '*'
  option write '*'
```

To disable login via the "root" user, remove the existing login section with username root.
