### ISSUE TITLE
Required dependency package kmod-wireguard is not available in any repository

### ISSUE THREAD

**Issue by Stenfrank** [openwrt/luci#5342]
When updating TP-Link Archer C7 v5 to version 21.02.0 Wireguard stopped working due to package "kmod-wireguard"

![gnome-shell-screenshot-FUS480](https://user-images.githubusercontent.com/15841698/132268137-f3892f83-9279-4b86-903d-31a2793ea6a0.png)

**Comment by alexforencich** [comment]
Just ran in to this issue myself.  Definitely a bug in luci, but if you click "install" it should actually install the package, despite the luci GUI indicating that a piece is missing.

**Comment by jow-** [comment]
The actual bug was within the `cgi-io` helper which truncated the package lists downloaded by LuCI. Once the package has been rebuilt, you can solve the issue using `opkg update; opkg upgrade cgi-io`.

The next maintenance release will contain the fixed version of this package.

**Comment by Stenfrank** [comment]
Thank you very much, manage the update as you indicated and it worked, the only thing I see is that the Status Wireguard menu no longer appears

![gnome-shell-screenshot-Y3Y680](https://user-images.githubusercontent.com/15841698/132780996-b20b9d56-b523-45b5-ab55-a7cdd496c757.png)

**Comment by reporrted** [comment]
> Thank you very much, manage the update as you indicated and it worked, the only thing I see is that the Status Wireguard menu no longer appears
> 
> ![gnome-shell-screenshot-Y3Y680](https://user-images.githubusercontent.com/15841698/132780996-b20b9d56-b523-45b5-ab55-a7cdd496c757.png)

Install luci-app-wireguard

**Comment by Stenfrank** [comment]
> > Muchas gracias, gestiona la actualización como indicaste y funcionó, lo único que veo es que ya no aparece el menú Status Wireguard
> > ![gnome-shell-captura de pantalla-Y3Y680](https://user-images.githubusercontent.com/15841698/132780996-b20b9d56-b523-45b5-ab55-a7cdd496c757.png)
> 
> Instalar luci-app-wireguard

Thanks
