### ISSUE TITLE
auto remove all available mac-address in MAC-FILTER after perform add to blacklist on Luci - Status - Overview

### ISSUE THREAD

**Issue by hongdat1106** [openwrt/luci#5343]
Please correct me if I mean this is a bug when I perform "add to blacklist" in Luci-Status-Overview then UCI will remove all old MAC-Address (all available mac-address) automatically.

`# /etc/config/wireless
uci del wireless.default_radio0.maclist
uci add_list wireless.default_radio0.maclist='00:00:00:00:00:00'`

Model | Linksys WRT1900ACS
Architecture | ARMv7 Processor rev 1 (v7l)
Firmware Version | OpenWrt SNAPSHOT r17471-b6cbbbb6ef / LuCI Master git-21.247.25992-4f7db0e
Kernel Version | 5.4.143

images:
![1](https://user-images.githubusercontent.com/80704502/132704038-32f49f01-ad23-47b2-a6c5-98280f8dbe15.jpg)
![2](https://user-images.githubusercontent.com/80704502/132704064-443f3454-8ba7-40b0-ac21-47caa4fb60f3.jpg)

**Comment by jow-** [comment]
@Ansuel - afair you implemented this feature in ef94c52680ab2743627fb821e16b0bb202f7b35c, please check.

**Comment by Ansuel** [comment]
Tell me if I'm right. When you click add to blacklist, all the other old entry are removed?

**Comment by hongdat1106** [comment]
> @Ansuel - afair you implemented this feature in [ef94c52](https://github.com/openwrt/luci/commit/ef94c52680ab2743627fb821e16b0bb202f7b35c), please check.

Yes, I built firmware for myself on Openwrt github - master

**Comment by hongdat1106** [comment]
> Tell me if I'm right. When you click add to blacklist, all the other old entry are removed?

Yes, correct. All old entries will be deleted after submit.
