### ISSUE TITLE
［RM2100/AC2100］Wrongly seting my openwrt router's lan address to dhcp and make it unreachable

### ISSUE THREAD

**Issue by YIKE2020** [openwrt/luci#5345]
Wrongly seting my router's lan address to dhcp and making the router unreachable for my pc.
Besides,the wifi is unconnected.Then i update(reflash,actually) the openwrt firmware in breed bootloader.But after rebooting it，the condition got worse.
Now,the wifi signal is gone,and my pc can't get ip from my router(169.xxx.xxx.xx).
192.168.2.1（default lan ip for my openwrt edition ） and 192.168.1.1 are both useless.
WHAT CAN I DO？

**Comment by jow-** [comment]
https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset

Besides, use the openWrt forum for further support questions
