### ISSUE TITLE
luci-app-yggdrasil in the 21.02.0 release is outdated and not working correctly

### ISSUE THREAD

**Issue by zhoreeq** [openwrt/luci#5356]
Can we please have an updated luci-app-yggdrasil 3953b1a5b249b09e566ca1ec4ce2fb4e23cdf69e in the next 21.02.1 release?

Currently it is unusable:

![Screenshot_20210911_114350](https://user-images.githubusercontent.com/57254463/132946977-7f15db27-6f4d-4c2c-b1b7-2ee2fe83c13b.png)

**Comment by dibdot** [comment]
cherry-picked to 21.02 branch with https://github.com/openwrt/luci/commit/aae1d349ae5654d52beb8e16ea8a486d3a6e5e19

**Comment by zhoreeq** [comment]
@dibdot thank you!
