### ISSUE TITLE
[RFC] recommended linter settings for JavaScript

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#5362]
Hi, I've tried to lint my LuCI app in the past but it failed since all tools somewhat messed up in awkward ways. So far I've tried `prettier`, `js-beautify` and `clang-format`. No really happy with any of them but now found this [online linter](https://beautifier.io/) with a bunch of options, does anyone have recommendations what to use?

**Comment by feckert** [comment]
If I read this correctly, then this is [js-beautify](https://github.com/beautify-web/js-beautify).
I would prefer if we had a CI that started a linter with every pullrequest.
Of course, we first have to select a linter and also work out the configuration.

**Comment by aparcar** [comment]
Ideally @jow- shares some wisdom here, however I think he doesn't use linters at this point but does things manually.

**Comment by nickberry17** [comment]
Would be nice to standardise this so we can just set our editors up to format on save.

**Comment by jow-** [comment]
I don't use any linter so can't recommend anything
