### ISSUE TITLE
luci-app-nlbwmon: Support for realtime speed/data-transfer-rate per client.

### ISSUE THREAD

**Issue by xavier83** [openwrt/luci#5365]
https://github.com/kiougar/luci-wrtbwmon seems to support it but looks unmaintained :disappointed: 

Seems like it is supposed to be a ui/luci level feature? :slightly_smiling_face: 
https://github.com/jow-/nlbwmon/issues/45

**Comment by jow-** [comment]
The software architecture of nlbwmon does not support this use case. It regularly polls conntrack for accounting information but that information is not real time unfortunately.

**Comment by xavier83** [comment]
@jow- isn't computing _"realtime" speed_ as simple as tracking the _change in bandwidth accounting_ data between every poll over the _interval of polling_? am I missing something?
