### ISSUE TITLE
LuCI spamming DNS server with IPv6 PTR requests even though there is no IPv6

### ISSUE THREAD

**Issue by timkgh** [openwrt/luci#5369]
OpenWrt 21.02.0, r16279-5cc0535800

My LAN does not support IPv6, even though the devices get a `fe80::` local link address.

LuCI keeps trying to resolve these addresses to host names by spamming the LAN DNS server with `*.ip6.arpa` PTR requests **at very high rates**.

Related #5206

**Comment by jow-** [comment]
Attempts to resolve `fe80::` link local and `fc/fd...` ULA ones should be gone after 45a398e1ed86c9706d47ff46be73bdaa303ff661/af4352c07ef33ebb06a0c7f684f3f753b9c23f4f
