### ISSUE TITLE
Root Password

### ISSUE THREAD

**Issue by alandebortolo** [openwrt/luci#5370]
Anyone how what is the default password for this branch:
LuCI openwrt-21.02 branch (git-21.231.26241-422c175) / OpenWrt 21.02.0 r16279-5cc0535800

![image](https://user-images.githubusercontent.com/12910942/133821697-04f0da53-c904-4668-acf8-ded619b1e2f4.png)

**Comment by hnyman** [comment]
Default is empty password.
But if you have somebody's private build, we do not know what he has set there.

But your question is not a LuCI GUI issue/but... Closing.
