### ISSUE TITLE
luci-app-statistics: misconfiguration shipped pointing to non-existent directory

### ISSUE THREAD

**Issue by graysky2** [openwrt/luci#5373]
Maintainer: @jow- @feckert @hnyman 
Description:  A fresh install of luci-app-statistics expects `/etc/collectd/conf.d/` to be created on the file system but the package does not create this target.  You can see output in `logread` to this effect:
```
daemon.err collectd[23674]: configfile: stat (/etc/collectd/conf.d) failed: No such file or directory
```

Related but closed:
https://github.com/openwrt/packages/issues/12138
https://github.com/openwrt/luci/issues/439

**Comment by feckert** [comment]
The application luci-app-statistics does **not** use the uci generation from the [collectd package](https://github.com/openwrt/packages/blob/master/utils/collectd/files/collectd.init).
The collectd configuration is generated by luci-app-statistics it self with the script [stat-genconfig](https://github.com/openwrt/luci/blob/master/applications/luci-app-statistics/root/usr/bin/stat-genconfi).
So I think we have to fix this there.

**Comment by hnyman** [comment]
I beg to differ.

> A fresh install of luci-app-statistics expects /etc/collectd/conf.d/ to be created on the file system

Better explanation would be that collectd daemon itself expects that dir, but our collectd installation in Makefile or init script does not generate it.

Luci-statistics ships a config for collectd from here, but that does not have much role here.
The error is in the unnecessary warning as the collectd package itself does not check for the existence of the directory before looking into its contents.

Collectd init script (or the collectd package installation in Makefile) should probably generate that dir.

Probably here:
https://github.com/openwrt/packages/blob/master/utils/collectd/Makefile#L354-L366

Ps. that error seems to originate from collectd daemon itself, but at the first glance I do not see, from where exactly. (and the error has been there for a decade, I think.)
