### ISSUE TITLE
Make SQM compatible with VPN PBR?

### ISSUE THREAD

**Issue by lynxthecat** [openwrt/luci#5376]
At the moment without some kind of complicated workaround (perhaps employing 'veth' or similar), making use of VPN PBR whilst employing SQM seems impossible. Apply SQM to the VPN interface and the bypassed traffic bypasses the shaper. Apply SQM to the WAN interface and the encrypted traffic breaks CAKE. Might somehow SQM be made to be more compatible with VPN PBR or at least a good solution presented on the wiki?

**Comment by stangri** [comment]
This has nothing to do with luci.

PS. wiki is community-edited, you're welcome to make changes there.
