### ISSUE TITLE
Luci x86_64 network interfaces reset after clicking system/startup

### ISSUE THREAD

**Issue by himekifee** [openwrt/luci#5377]
I'm running OpenWrt 21.02.0 official release image on my PVE qemu q35 virtual machine. Whenever I click system/startup tab, the network interfaces reset and I lost connection. Tried to use squashfs image. Got the same result. However, I had another ipq40xx device and build it from source, it did not trigger the network reset so I suspect something is wrong with the x86_64 image.

**Comment by jow-** [comment]
Please provide the complete output of `ls -lh /etc/init.d/`

**Comment by himekifee** [comment]
Nvm. That was opened by me and somehow it did not sending me any notification so I don't know it is solved there. Again, thank you very much.
