### ISSUE TITLE
[21.02.0] luci-compat cause some openwrt_core packages gone

### ISSUE THREAD

**Issue by scott0122** [openwrt/luci#5382]
Before installing luci-compat: 
![image](https://user-images.githubusercontent.com/39105828/134483548-c1cd6ebd-a69e-4db2-b797-8261e278d15d.png)

Click [Update lists] after luci-compat installed , libatomic1 become unavailable. 
![image](https://user-images.githubusercontent.com/39105828/134485786-9abed0b2-cb56-4c81-aa7c-5cac5a8a8622.png)
![image](https://user-images.githubusercontent.com/39105828/134483592-64d1a834-dac8-46e2-bbbc-2e14d5e5680a.png)

So I try to find libstdcpp6. 
![image](https://user-images.githubusercontent.com/39105828/134484490-0cb36232-4dc9-42c9-812b-d075dbc8c713.png)

But libatomic1 and libstdcpp6 still can install from console.
![image](https://user-images.githubusercontent.com/39105828/134483716-dcb91f75-c36f-4d3f-a767-9c5dc1712758.png)

**Comment by jow-** [comment]
https://github.com/openwrt/luci/issues/5342
