### ISSUE TITLE
problem with images and mass library.

### ISSUE THREAD

**Issue by BuGGReporter** [openwrt/luci#5397]
images are scaled down on large LED's larger than 32 inches [LG OLED 50 inch the one i have tested]. there is no way to zoom view while playing in a sequence. resolution is scaled down to 1024 sometimes even smaller. There should be a way to view them full screen or atleast in their standard resolution not scaled down.

the next problem is if a folder is having large number of files [above 250 files] minidlna won't populate it or at least 2 third of the files are completely missing. this need to be addressed as we have tried many times including removing the database and rebuilding it but that won't help.

**Comment by jow-** [comment]
Not related to LuCI, maybe you meant to open a report at https://github.com/openwrt/packages/issues ?
