### ISSUE TITLE
Status Indicators for DDNS Registration and NTP Updates

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#54]
**Reported by marca56@gmail.com on 20 Mar 2009 04:30 UTC**
LuCI network status page should show DDNS registration status (success or failure, IP address and update time) and next register time; 

LuCI network status page should show NTP registration status (success or failure, update time) and next registration time.

**Comment by hnyman** [comment]
The DNS part is done by the current ddns-scripts, and I think that the NTP part is not easily done. ntpd does not provide any practical way to query for that info.
Closing this.
