### ISSUE TITLE
SyntaxError when attemping to edit Wireguard interface using classic OpenWrt theme

### ISSUE THREAD

**Issue by brentr** [openwrt/luci#5419]
Configure Luci to use the classic OpenWrt theme
Attempts to edit an existing WireGuard interface from:

https://router/cgi-bin/luci/admin/network/network

fail with:
```
SyntaxError
An invalid or illegal string was specified
```
Displayed at the top of the network interface status page.

Switch theme to OpenWrt2020
Now the Wireguard interface can be edited without error.

**Comment by mydogteddy** [comment]
I just tried another browser and it is fixed it must have been my cache in FireFox

**Comment by brentr** [comment]
I'm was also using FireFox.  Clearing Cache Data has your patch fix working for me too.
Thank you!
