### ISSUE TITLE
Misleading scrollbars

### ISSUE THREAD

**Issue by vgaetera** [openwrt/luci#5441]
Misleading scrollbars in luci-theme-bootstrap @ OpenWrt snapshot:

* LuCI > Network > Interfaces > WAN > Edit > Firewall Settings > Create / Assign firewall-zone:
![interface-firewall-settings](https://user-images.githubusercontent.com/20725816/137112971-54667530-9d57-4ece-b890-71cb2eca2883.png)

* LuCI > Network > Routing > Static IPv4/IPv6 Routes > Add > General Settings > Interface:
![route-interface](https://user-images.githubusercontent.com/20725816/137112999-f3c8f5e4-9ea3-43df-96b1-c22224f89845.png)

Chromium 94.0.4606.71 (Official Build) (64-bit) @ Fedora Linux 34

**Comment by jow-** [comment]
This should have been solved as part of 8055acc9be
