### ISSUE TITLE
luci-app-ddns: hotplug script not triggered for pppoe-wan

### ISSUE THREAD

**Issue by moetayuko** [openwrt/luci#5449]
I have a ipv6 pppoe ddns config like this:
```
➜  ~ cat /etc/config/ddns
config service 'myddns_ipv6'
        option use_ipv6 '1'
        option enabled '1'
        option lookup_host '***'
        option service_name 'he.net'
        option domain '***'
        option username '***'
        option password '***'
        option ip_source 'interface'
        option ip_interface 'pppoe-wan'
        option interface 'pppoe-wan'
        option use_syslog '2'
        option check_unit 'minutes'
        option force_unit 'minutes'
        option retry_unit 'seconds'
```
and it does not get triggered after boot at all. Manually start via luci or `/usr/lib/ddns/dynamic_dns_updater.sh -n pppoe-wan -- start` works fine.

`option interface` is the so-called "Event Network" used by the hotplug script and is forced to be the same as `ip_interface` if "ip_source"="network" or "interface":
https://github.com/openwrt/luci/blob/1a0c1b729d597dfb3ce48904b5fc715be9c52754/applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js#L866-L880

However, I'm afraid that `$INTERFACE` of hotplug script can never be `pppoe-wan`. Manually set `option interface 'wan_6'` fixed the issue. Maybe it should be `wan` for ipv4 and `wan_6` for ipv6, at least for pppoe case?

Cc: @Ansuel

**Comment by Ansuel** [comment]
did you test if interface can be pppoe-wan?

**Comment by MoetaYuko** [comment]
> did you test if interface can be pppoe-wan?

wdym? it is pppoe-wan with current luci implementation and doesn't get triggered for me

**Comment by MoetaYuko** [comment]
I added some logging to the hotplug script as follows:
```bash
➜  ~ cat /etc/hotplug.d/iface/95-ddns 
#!/bin/sh

# there are other ACTIONs like ifupdate we don't need
case "$ACTION" in
        ifup)                                   # OpenWrt is giving a network not phys. Interface
                /etc/init.d/ddns enabled && /usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- start
                logger -t ddnsdbg "$ACTION of $INTERFACE ($DEVICE)"
                ;;
        ifdown)
                /usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- stop
                logger -t ddnsdbg "$ACTION of $INTERFACE ($DEVICE)"
                ;;
esac
```
and the logs on boot are:
```
Sun Oct 17 14:17:02 2021 user.notice ddnsdbg: ifup of lan (br-lan)
Sun Oct 17 14:17:02 2021 user.notice ddnsdbg: ifup of loopback (lo)
Sun Oct 17 14:17:03 2021 user.notice ddnsdbg: ifup of wan (pppoe-wan)
Sun Oct 17 14:17:26 2021 user.notice ddnsdbg: ifup of wan_6 (pppoe-wan)
```
It turns out that we should either change `option interface` to `wan_6` or `-n "$INTERFACE"` to `-n "$DEVICE"` (the prior one makes more sense to me since v4 and v6 are not brought up simultaneously).

Cc  @feckert
