### ISSUE TITLE
"Filter useless" sounds too tempting, when it breaks things

### ISSUE THREAD

**Issue by Zash** [openwrt/luci#5456]
https://github.com/openwrt/luci/blob/f4f64b91ca4d443af9e7bc0dfc2565ae0a796ea3/modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js#L385-L387

This option breaks XMPP, SIP and other protocols using SRV records, so it should have a less tempting label, probably a warning. Best if it was just removed completely, especially since it was meant to stop Windows 2000 from triggering automatic dialup, which seems like it should be fairly uncommon these days.

**Comment by selurvedu** [comment]
@jow- could you please reopen this? There's an actionable suggestion above my comment.

**Comment by jow-** [comment]
Please provide a PR implementing the suggestion and I'll review it.
