### ISSUE TITLE
Can Luci support 80211ad?

### ISSUE THREAD

**Issue by NancyLuoYuan** [openwrt/luci#546]
I'm trying to use Openwrt 15.05 release for our 80211ad device, the command line works fine to configure the device to AP, but Luci seems not support 80211ad. Is that possible to add 80211ad support to Luci?

**Comment by jow-** [comment]
Since there is not a single 802.11ad supported driver in OpenWrt I see no point in adding 802.11ad support to LuCI. If you need that in a proprietary OpenWrt fork then you have to do it yourself. You need to modify libiwinfo and wifi.lua
