### ISSUE TITLE
[WIP] convert CBI based apps to JavaScript

### ISSUE THREAD

**Issue by petrov-adg** [openwrt/luci#5461]
We would like to convert all CBI based app like [luci-app-ntpc](https://github.com/openwrt/luci/tree/master/applications/luci-app-ntpc) Right now we have 34 CBI Based apps.

I think we can try to convert luci-app-ntpc to JavaScript. It's really simple app. Any suggestions are welcome.

**Comment by jow-** [comment]
I am closing this as there's nothing actionable here.
