### ISSUE TITLE
OpenWRT: CSS problems

### ISSUE THREAD

**Issue by systemcrash** [openwrt/luci#5464]
OpenWRT 21.02.1

dark mode : 
Text in `*.placeholder` is damned impossible to see, especially when f.lux kicks in. :facepalm: 

Disabling `var(--background-color-high);` makes everything visible. 

In Firefox, the property `zoom` raises an error. I recommend its removal:

> Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

https://caniuse.com/?search=zoom
https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

**Comment by systemcrash** [comment]
![Screenshot 2021-10-30 at 02 01 40](https://user-images.githubusercontent.com/647633/139589973-dfbe85ea-e0dc-4321-bebd-82e9da8e7e87.png)

**Comment by jow-** [comment]
Placeholder contrast was increased in 8055acc9be
