### ISSUE TITLE
Changing wireless settings breaks wireless [X5000R]

### ISSUE THREAD

**Issue by freaksdotcom** [openwrt/luci#5468]
Attempting to change the wireless settings for radio1 (5GHz) breaks the LUCI config, and if applied it breaks wireless.

After changing anything and hitting Save, the dialog is not dismissed and you have to click dismiss. If you look at the pending changes, it shows that it is removing the band and channel.

```
# /etc/config/wireless
uci del wireless.radio1.band
uci del wireless.radio1.channel
uci set wireless.radio1.htmode='HE40'
```

Attempting to edit the wireless settings after this gives an error.
```
TypeError
Cannot read properties of undefined (reading 'value')
```

**Comment by xerofule** [comment]
@freaksdotcom which versions fixed the problem? I'm experiencing it with openwrt-21.02 branch (git-22.025.79177-4ec18ec) and these luci packages:
```
# opkg list-installed | grep luci
liblucihttp-lua - 2021-06-11-3dc89af4-1
liblucihttp0 - 2021-06-11-3dc89af4-1
luci - git-20.074.84698-ead5e81
luci-app-firewall - git-21.312.70727-3eac573
luci-app-opkg - git-21.312.69848-4745991
luci-base - git-22.025.79177-4ec18ec
luci-lib-base - git-20.232.39649-1f6dc29
luci-lib-ip - git-20.250.76529-62505bd
luci-lib-jsonc - git-19.317.29469-8da8f38
luci-lib-nixio - git-20.234.06894-c4a4e43
luci-mod-admin-full - git-19.253.48496-3f93650
luci-mod-network - git-22.007.66044-dd9390c
luci-mod-status - git-21.295.66779-853a128
luci-mod-system - git-22.019.40321-7a37d02
luci-proto-ipv6 - git-21.148.49484-14511e5
luci-proto-ppp - git-21.163.64918-6c6559a
luci-ssl - git-20.244.36115-e10f954
luci-theme-bootstrap - git-21.320.44446-0cee46b
rpcd-mod-luci - 20210614

```

**Comment by freaksdotcom** [comment]
I don't know the exact git hash. 

I tried OpenWRT 21.02.1 and the version of luci it shipped with wasn't working. I updated to the daily around that time and installed the luci daily using `opgk`.

Just updating luci on top of 21.02.1 might be enough to fix it. I think anything after 2778366916f815d4af9534218bef10aa3aad3c01 will work.

**Comment by brozikcz** [comment]
Hi guys, does somebody know how to fix that?

I have the latest version of OpenWrt 21.02.2 r16495-bf0c965af0 with `luci | git-20.074.84698-ead5e81` but I'm still getting the `TypedError` in luci wireless config.

**Comment by brozikcz** [comment]
I have config with the `htmode HE80` because `VHT80` is just for AC mode. Or I'm something overlooking?

**Comment by shansong99** [comment]
X5000R updated to 21.02, same issue here.

**Comment by xerofule** [comment]
I upgraded to 21.02.2 and still affected by the issue.
I removed the interface and rebooted but still occurring:
```
uci del wireless.radio1
uci commit
reboot
```

I've opened a new issue https://github.com/openwrt/luci/issues/5726 to keep track of this issue which seems to not be fully fixed after upgrading.

**Comment by h4de5** [comment]
> same issue on version `openwrt-21.02 branch (git-22.052.50801-31a27f3) / OpenWrt 21.02.2 r16495-bf0c965af0`
> 
> I fixed it successfully by editing `/etc/config/wireless` directly
> 
> ```
> config wifi-device 'radio1'
> 	option type 'mac80211'
> 	option hwmode '11a'
> 	option path '1e140000.pcie/pci0000:00/0000:00:01.0/0000:02:00.0+1'
> 	option htmode 'VHT80'
> 	option channel 'auto'
> 	option cell_density '0'
> 
> config wifi-iface 'default_radio1'
> 	option device 'radio1'
> 	option network 'lan'
> 	option mode 'ap'
> 	option key 'password'
> 	option ieee80211r '1'
> 	option ft_over_ds '1'
> 	option ft_psk_generate_local '1'
> 	option encryption 'psk-mixed'
> 	option ssid 'openwrt'
> ```
> 
> `option channel 'auto'` will somehow disappear causing the error

had the same issue with latest stable 21.02.2 - add this channel option fixed it. 
thanks!
