### ISSUE TITLE
Luci Led Configuration add and edit broken in snapshots

### ISSUE THREAD

**Issue by CaboBeach** [openwrt/luci#5476]
When clicking on Add LED action or the Edit button for a current led there's just a spinning wheel over the button and no pop up dialog box appears to add or edit, works fine in cli and the leds appear in led configuration after adding/editing in cli - 

OpenWrt SNAPSHOT r17883-fd717f54be / LuCI Master git-21.301.66258-0740023

![Screen Shot 2021-10-30 at 10 06 58 PM](https://user-images.githubusercontent.com/48701904/139565612-f2baa8ae-e0c7-4f34-811c-745164f86b5e.png)

![Screen Shot 2021-10-30 at 10 07 24 PM](https://user-images.githubusercontent.com/48701904/139565616-c345d73e-a8c5-4dd0-a7fb-01251f9458c9.png)

**Comment by jow-** [comment]
Please open your browser debug console with `F12` and look for errors.

**Comment by CaboBeach** [comment]
Here's the debug console, it was the same for both add and edit - 

![Screenshot from 2021-10-31 16-41-34](https://user-images.githubusercontent.com/48701904/139602321-80f31716-e6e1-423c-9f17-c9c18e2451e6.png)

**Comment by GqSteve** [comment]
How can I apply this fix?

Copy the 5 files from Git to /www/luci-static/resources/view/system/led-trigger ?

**Comment by jow-** [comment]
You only need to update the `none.js` file.

**Comment by GqSteve** [comment]
I "updated" the content of https://raw.githubusercontent.com/openwrt/luci/fceabd74465f2aafc40edc084429f30837deff2c/modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/none.js in the  /www/luci-static/resources/view/system/led-trigger/none.js, but I still have the same behavior as described in #1: .._.there's just a spinning wheel over the button and no pop up dialog box appears to add or edit..._

I have 21.02.1 installed on Fritz!Repeater 3000. Should I open a new issue?

**Comment by GqSteve** [comment]
I updated all files from fix in the  /www/luci-static/resources/view/system/led-trigger/ directory and worked fine. Thank you! 👍

**Comment by feckert** [comment]
@jow- Thank you for looking at this. It worked for me in my integration test. Very strange.
