### ISSUE TITLE
luci: impossible to delete interface

### ISSUE THREAD

**Issue by HenryGiraldo** [openwrt/luci#549]
I also had the same issue, https://dev.openwrt.org/ticket/20793
using: luciversion = "git-15.319.74171-1106b93"

I'm not sure if this is an issue or a pull request.
The attached patch fix the issue.
[submit_to_button_iface_overview.txt](https://github.com/openwrt/luci/files/35505/submit_to_button_iface_overview.txt)

**Comment by jow-** [comment]
Suggested fix added in 9b176c8d7bd2a635cd5a3a3bdce3149247e66392 - thanks @HenryGiraldo !
