### ISSUE TITLE
How to toggle dark mode

### ISSUE THREAD

**Issue by Marsfan** [openwrt/luci#5492]
I just used attended sysupgrades to update my router to 21.02.1 and found that I was automatically changed to a dark mode in LuCI. I would like to switch back to a light mode, but there does not appear to be a setting to do this. 

Why was a dark mode added without any visible way to switch back to a light mode and how do I switch it back?

**Comment by jow-** [comment]
Once available, install the package upgrade for "luci-theme-bootstrap", then select "BootstrapLight" as theme in the System / System theme selection.
