### ISSUE TITLE
uHTTPd option "Do not follow symlinks outside document root" breaks luci

### ISSUE THREAD

**Issue by M95D** [openwrt/luci#5501]
To reproduce:
- Install luci-app-uhttpd
- Check option "Do not follow symlinks outside document root"
- Observe numerous Luci errors and empty pages that never finish loading.

PS: It would help a lot debugging this kind of errors (and [that](https://github.com/openwrt/luci/issues/4555) kind of errors) if Luci error messages were more detailed and logged!

**Comment by M95D** [comment]
Status / Firewall: Never finishes loading. Browser console shows periodic 404 errors for XHR POST https://<router-ip>/cgi-bin/cgi-exec?<some numbers>
Status / System log: Red message on top of the page: "Unable to load log data: Not Found"
System / Software: Red message on top: "NotFoundError".
Statistics / Graphs: Never finishes loading. Browser console shows error "Uncaught (in promise) NotFoundError: Not Found" and a couple of 404s.
Statistics / Setup: Never finishes loading. Browser console fills up several pages of 404s.

**Comment by jow-** [comment]
Yep, could be a problem. I m not able to reproduce your issue with a default setup.

**Comment by M95D** [comment]
I don't think it's necessary to rebuild the fw image to test this. Just remove the symlink and create a normal /var instead.

I'm rebuilding now an image without permanent /var, but it will take a while...

**Comment by Tabiskabis** [comment]
When i activated "do not follow symlinks outside document root", it broke a few luci pages such as "Administration" and "Software" (can't recall the others, but these were annoying). Exactly the same issue.

**Comment by jow-** [comment]
Ah yes, now I know why. It probably breaks the various cgi-io applets (cgi.-download, cgi-upload, cgi-exec) which symlink to /usr/libexec/cgi-io.

**Comment by M95D** [comment]
Please have a look at that other error I mentioned:
Busybox with CONFIG_BUSYBOX_CONFIG_INSTALL_NO_USR will move /usr/bin/env to /bin/env and that breaks luci too.

**Comment by jow-** [comment]
Yes, it will break LuCI since it expects /usr/bin/env to be available. No way around that

**Comment by M95D** [comment]
Why not create /usr/bin/env symlink (if missing) at the end of package/busybox/install ?
