### ISSUE TITLE
/www/cgi-bin/luci  always returned 403 Forbidden 

### ISSUE THREAD

**Issue by swparkkali** [openwrt/luci#5513]
Hi all, 

I've got some problem when I executed like bellow.

------------------------------------------
root@OpenWrt:/www/cgi-bin# ./luci
Status: 403 Forbidden
X-LuCI-Login-Required: yes
Content-Type: text/html
Cache-Control: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff

<!DOCTYPE html>
...
------------------------------------------

it always returned to 403 Forbidden even though the login session has already been created

is this normal output? if not, how can I get to the 200 OK response?

bellow is system information for more detail.

------------------------------------------
**root@OpenWrt:/www/cgi-bin# ubus call system board
{
        "kernel": "5.10.78",
        "hostname": "OpenWrt",
        "system": "ARMv7 Processor rev 5 (v7l)",
        "model": "8devices Jalapeno",
        "board_name": "8dev,jalapeno",
        "rootfs_type": "squashfs",
        "release": {
                "distribution": "OpenWrt",
                "version": "SNAPSHOT",
                "revision": "r18070-49f615022c",
                "target": "ipq40xx/generic",
                "description": "OpenWrt SNAPSHOT r18070-49f615022c"
        }
}
------**------------------------------------

**Comment by jow-** [comment]
You need to provide the proper CGI environment variables when executing LuCI directly.
