### ISSUE TITLE
Add option to update all packages

### ISSUE THREAD

**Issue by olekstomek** [openwrt/luci#5515]
With LuCI GUI `/cgi-bin/luci/admin/system/opkg` I have to update each package separately. It seems like a convenient option would be to be able to update all or selected ones with one click. For example, I select all items or selected items and choose the update option. Thanks to this, you will not have to update each package separately.
![upgrade package](https://user-images.githubusercontent.com/26818304/141674520-92d887cc-e825-402a-b960-1239b2dc8c7a.JPG)
.

**Comment by jow-** [comment]
This is intentional as mass-upgrades of packages is not properly supported by OpenWrt.
