### ISSUE TITLE
latest changes luci-mod-admin-full - not show other IP, if 2 interfaces to WAN

### ISSUE THREAD

**Issue by build000** [openwrt/luci#552]
eq. /etc/config/network:

```
(...)
config interface 'wan'
    option ifname 'eth0.2'
    option proto 'dhcp'
    option macaddr 'xx:xx:xx:xx:xx:xx'
    option peerdns '0'
    option dns '208.67.222.222 208.67.220.220'
    option mtu '9024'

config interface 'wan6'
    option ifname 'eth0.2'
    option proto 'dhcpv6'

config interface 'wan2'
    option ifname 'wwan0'
    option proto 'ncm'
    option device '/dev/cdc-wdm0'
    option pincode '1234'
    option apn 'vpn'
    option username 'vpn'
    option password 'vpn'
    option ipv6 '0'
(...)
```

bad effect can disable wan (wan6) and enable wan2, like this:

```
ifdown wan && ifdown wan6 && ifup wan2
```

ifconfig (wan disable an wan2 working):

```
(...)
wwan0     Link encap:Ethernet  HWaddr 00:1E:10:1F:00:00  
          inet addr:xx.xx.xx.250  Bcast:xx.xx.xx.251  Mask:255.255.255.252
          inet6 addr: fe80::*********************/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5560 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4450 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3256777 (3.1 MiB)  TX bytes:1587420 (1.5 MiB)
```

see like this:
![Image of Yaktocat](http://i.imgur.com/YVhbrB7.png)
I do not see the IP address and all lines that come with it.

It is connected with the recent amendments to luci-mod-admin-full.
It was previously seen on the second IP interface (wan2).

**Comment by jow-** [comment]
Pastebin the outputs of `ifstatus wan`, `ifstatus wan2` and `ifstatus wan6`

**Comment by build000** [comment]
http://wklej.org/id/1849450/
modem: E3372s-153 (driver ncm)
router: WNDR4300

**Comment by jow-** [comment]
So your ubus ifstatus doesn ot contain any ip addresses at all, this looks more like a bug in the ncm protocol handler to me. I agree that it worked before because we queried the IPs directly from the interface there but I want to get away from that as it introduces various issues.

**Comment by build000** [comment]
So the suggestion from my hand and ask:
when in the end you will see the address for 4G modems, not to mention the use by Luci - it was the only way I could easily see this address with the number of TX / RX without resorting to the console?

**Comment by jow-** [comment]
I'm not saying that I do not want to fix it, just trying to investigate where. Can you provide a complete copy of `ubus call network.interface dump` ? If there are sensitive IPs in it then please replace them with XXX or something but leave the field.

**Comment by build000** [comment]
send email...

**Comment by build000** [comment]
minimal positive progress (probably latest changes to luci-base):
- visible IP adress properly (eq. wwan0) to /cgi-bin/luci/admin/status
- again not visible IP adress to /cgi-bin/luci/admin/network
;)

**Comment by jow-** [comment]
Closing this as this must be solved in OpenWrt
