### ISSUE TITLE
Time Zone setting ignored on Ubiquiti ERLite-3

### ISSUE THREAD

**Issue by glyndon** [openwrt/luci#5529]
Using 21.02.1
Ubiquiti EdgeRouter Lite (ERLite-3)

The timezone setting seems to be ignored in the UI. "Local Time" displays UTC, an all logs are in UTC.

Change TZ setting in UI, notice no effect on displayed time.

What you have already done to workaround/fix the problem: Remember to translate from UTC when reading logs

I'm not sure if this is a Luci problem, or something further down, but am starting here in case it's just a UI issue.

**Comment by jow-** [comment]
This is an OpenWrt side issue, specific to this target. Please follow up on https://bugs.openwrt.org/index.php?do=details&task_id=3944
