### ISSUE TITLE
luci-upnp-adblock Would like to set up to only listen on certain interfaces / VLANs

### ISSUE THREAD

**Issue by james-mcguire** [openwrt/luci#5532]
I have a dedicated interface/VLAN for my IOT.  

I would love to control what servers they can hit with adblock, without impacting the rest of my network.  An easy to use to setting to control which interfaces adblock works on would be amazing.

Thanks for the consideration.

**Comment by dibdot** [comment]
Adblock works per DNS instance, not per interface. Use multiple DNS instances or an IP based approach like banIP.
