### ISSUE TITLE
Sqm settings off center in bootstrap

### ISSUE THREAD

**Issue by CaboBeach** [openwrt/luci#5535]
The sqm settings in bootstrap are 'off center' in Snapshots, settings themselves work fine and it's still readable, just wasn't sure if it was intended or not

OpenWrt SNAPSHOT r18153-617fcd4879 / LuCI Master git-21.324.29356-9cb6bde

![Screen Shot 2021-11-20 at 9 10 50 PM](https://user-images.githubusercontent.com/48701904/142748131-c21748ae-bd4f-4e43-b6b6-59ced5a2622d.png)

![Screen Shot 2021-11-20 at 9 11 18 PM](https://user-images.githubusercontent.com/48701904/142748138-8becbfda-7843-47e8-8852-8cd874a6f7eb.png)

![Screen Shot 2021-11-20 at 9 11 35 PM](https://user-images.githubusercontent.com/48701904/142748140-88cdf30c-5678-4e73-bb5c-306145d36c27.png)

![Screen Shot 2021-11-20 at 9 21 00 PM](https://user-images.githubusercontent.com/48701904/142748203-9f36588b-0569-4970-88e6-b8ac90be2cd6.png)

**Comment by hnyman** [comment]
I noticed the same yesterday with a new master build.
Possibly caused by the recent bootstrap CSS style changes by @jow- and the SQM app's style selections.

**Comment by jow-** [comment]
Fixed with 4720a025e8 - the labels are still far too long imho - the left hand caption should be very short and concise, the extended field descriptions should be used for long explanations
