### ISSUE TITLE
Can't login luci

### ISSUE THREAD

**Issue by 4NobleTruths** [openwrt/luci#5536]
on Raspberry Pi 4 using imagebuilder-21.02.1-bcm27xx-bcm2711
can't login luci “Invalid username and/or password! Please try again.”
logread error: daemon.err uhttpd[3063]: luci: failed login on / for root from 192.168...
Same as this from forum, but those solutions don't work: https://forum.openwrt.org/t/unable-to-logon-via-luci-able-via-ssh/25408

**Comment by jow-** [comment]
Works fine for me with standard images. Make sure your /etc/shadow uses MD5 hashes, delete any existing `sysauth` cookie from your browser.

**Comment by 4NobleTruths** [comment]
Same problem on completely different device GL-e750 using image from imagebuilder-21.02.1-ath79-nand.
Was able to login luci before i set passwd in ssh console.
I didn't change type of shadow hashes, nor do I know how.

**Comment by jow-** [comment]
You likely included something in your image builder invocation which causes problems.

**Comment by 4NobleTruths** [comment]
This  caused that:
https://bugs.openwrt.org/index.php?do=details&task_id=4044
