### ISSUE TITLE
Make the dark bootstrap theme actualy look nice

### ISSUE THREAD

**Issue by ThiefMaster** [openwrt/luci#5537]
Currently it has much lower contrast than the light theme, this is particularly noticeable when it comes to the tab headers and buttons. And it looks like I'm [not the only one](https://forum.openwrt.org/t/21-02-1-dark-mode/110218) who doesn't like it in its current state...

The contrast when saving changes is also very low:

![image](https://user-images.githubusercontent.com/179599/142762178-ef907861-1194-4d47-a51a-d9ba55ffebec.png)

Unfortunately UI design isn't my strength, so I can't make more specific suggestions on improving it, but I'm sure there are others here who can :)

**Comment by jow-** [comment]
Various improvements have already been applied to master.
