### ISSUE TITLE
luci-mod-system reboot

### ISSUE THREAD

**Issue by 5p0ng3b0b** [openwrt/luci#5541]
The module luci-app-advanced-reboot module has a shutdown button. Would it be possible (and practical) to move/add this function to the reboot menu?

**Comment by jow-** [comment]
No, since there is no platform neutral way to offer this. Only a small subset of OpenWrt supported targets offers proper shutdown functionality and we do not want to maintain model lists in the code just to guard this feature.

**Comment by 5p0ng3b0b** [comment]
No worries and thanks for looking into it. I can clean shut down via cli and only need it occasionally. Better to clean shutdown than pulling the plug running transmission server and then having to fsck a 4tb drive afterwards.
