### ISSUE TITLE
Rename Devices 'Reset' button to 'Delete' to better reflect its function

### ISSUE THREAD

**Issue by shoulders** [openwrt/luci#5556]
![image](https://user-images.githubusercontent.com/319997/143691467-e40a77e2-fcf9-4ca8-9801-1ad15cd0821b.png)

**Issue:**
On the page (Network-->Interfaces-->Devices) each device has a button at the end of it called `Reset` however this button actually deletes the device.

When you hover over the button you get the message `Remove related device settings from the configuration`

**Solution:**
Cant this button be renamed to `Delete`

**Comment by jow-** [comment]
See 1b58decdabbbf631c89bdd56b63429b6ccc7fb8d, #5090, #5092 for previous discussions about it.
