### ISSUE TITLE
luci-app-commands: Custom arguments not working with "/"

### ISSUE THREAD

**Issue by KristerLundmark** [openwrt/luci#5559]
When using "Custom arguments" to a created command the resulting parsed command removes custom arguments starting with slash ("/").

The commands works ok if putting the parameters in the command itself, but not as custom arguments.

Examples:

Command: ls /etc/config
=> Works ok

Command: ls
Custom parameter: /etc/config
=> Does not work, the resulting command is: "ls etc"

Command: ls
Custom parameter: /tmp
=> Does not work, the resulting command is: "ls tmp"

Command: ls
Custom parameter: /
=> Does not work, the resulting command is: "ls"

I have tried quoting the custom parameter when entering value in luci, but this doesn't work either, when using double- or single quoting, the parameter is removed:

Command: ls
Custom parameter: "/etc/config"
=> Does not work, the resulting command is: "ls"

Regards,
Krister

**Comment by wulfy23** [comment]
```
%2Fetc%2Fconfig
```

**Comment by KristerLundmark** [comment]
No, that doesn't work (ls as command, %2Fetc%2Fconfig as parameter value):

# ls etc
ls: etc: No such file or directory

**Comment by wulfy23** [comment]
should have tested it first \0/

appears sanitized for good reason...

ttyd or similar are great if you want shell access... or look into libexec+acl.d for more control for integrated functions...

**Comment by KristerLundmark** [comment]
Thats ok, I use ssh (putty) for shell access, but it's more convenient to use app-commands to e.g. quick check all my devices (I have a shell script that loops through all devices). It's not critical, but more like "good-to-have" to not have to create app-commands with hard-coded parameter values.
