### ISSUE TITLE
Set rangelength to SSID (32 characters)

### ISSUE THREAD

**Issue by HenryGiraldo** [openwrt/luci#558]
The standard defines the maximum size is 32 characters. If one more is used, the hostapd no link up the interfaces.

<pre>
--- a/modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
+++ b/modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
@@ -361,7 +361,8 @@ s:tab("encryption", translate("Wireless Security"))
 s:tab("macfilter", translate("MAC-Filter"))
 s:tab("advanced", translate("Advanced Settings"))
 
-s:taboption("general", Value, "ssid", translate("<abbr title=\"Extended Service Set Identifier\">ESSID</abbr>"))
+ssid = s:taboption("general", Value, "ssid", translate("<abbr title=\"Extended Service Set Identifier\">ESSID</abbr>"))
+ssid.datatype = "rangelength(1,32)"
 
 mode = s:taboption("general", ListValue, "mode", translate("Mode"))
 mode.override_values = true
</pre>

**Comment by jow-** [comment]
Fixed with ce04adb38392c07420c30e67b1bb010ee1e0145f
