### ISSUE TITLE
GalanoGrotesque font issue with non-latin symbols (openwrt2020 theme)

### ISSUE THREAD

**Issue by svlobanov** [openwrt/luci#5580]
Openwrt2020 theme uses GalanoGrotesque font and it looks nice for latin alphabets. GalanoGrotesque doesn't support non-latin symbols so sans-serif is used for non-latin words.

If alphabet contains non-latin symbols (e.g. Greek and Russian) it looks not so nice especially if latin and non-latin symbols are mixed together in one page.

It is especially noticeable in "LED Name" string ("Имя LED", "Όνομα LED"). Non-latin symbols looks much more bold that latin symbols. 

Is there any way not to use GalanoGrotesque font for translations with non-latin symbols? Is it possible to change .css file if Language is changed?

LED settings in English
<img width="497" alt="Screenshot 2021-12-05 at 21 37 15" src="https://user-images.githubusercontent.com/10530170/144759285-fb347ad7-6eaa-495d-b02d-3d0df3550c48.png">

LED settings in Greek
<img width="499" alt="Screenshot 2021-12-05 at 21 35 44" src="https://user-images.githubusercontent.com/10530170/144759289-79a33b95-c923-4b67-8bad-49751848a938.png">

LED settings in Russian
<img width="498" alt="Screenshot 2021-12-05 at 21 36 43" src="https://user-images.githubusercontent.com/10530170/144759288-212cef49-a319-4505-8f90-aa8d539e8fde.png">

**Comment by jow-** [comment]
The `<html>` element is rendered with a `lang=".."` attribute to allow adding language specific CSS rules. You could try a change like that:

```diff
diff --git a/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css b/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
index cf320e4aed..a53636d45e 100644
--- a/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
+++ b/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
@@ -10,6 +10,10 @@
        --base-font-size: 16px;
 }
 
+:root[lang="ru"], :root[lang="el"] {
+       --regular-font: "Helvetica";
+}
+
 @font-face {
        font-family: "GalanoGrotesqueW00-Regular";
        src: url("GalanoGrotesqueW00-Regular.woff2") format("woff2");
```

If it works for you (and you can suggest a suitable font), please provide a PR and I'll merge it.

**Comment by svlobanov** [comment]
@jow- 
it works perfectly (first one)

>maybe also just adding specific fallback font families is already enough
GalanoGrotesque is a bit different than Helvetica so this solution is not so perfect as first proposed by you

I'm going to prepare PR. it will be ready in a short time

New screenshots for rus and greek:
<img width="582" alt="Screenshot 2021-12-05 at 23 19 42" src="https://user-images.githubusercontent.com/10530170/144762565-68178ac1-b43a-4568-969e-98674ba4d46b.png">
<img width="453" alt="Screenshot 2021-12-05 at 23 18 40" src="https://user-images.githubusercontent.com/10530170/144762569-cb2a8045-c89c-45e6-b68b-99b276cab6e0.png">

**Comment by svlobanov** [comment]
@jow- PR #5581
