### ISSUE TITLE
Component not present.

### ISSUE THREAD

**Issue by bluemiaomiao** [openwrt/luci#5594]
When I Open the router web dashboard.
```
Component not present.
```

**Comment by stangri** [comment]
You may want to include the following information to prevent this issue from being closed:
* OpenWrt version
* Luci version
* Exact URL you're trying to open in the browser
* Any other relevant information which may be valuable to reproduce this error

**Comment by jow-** [comment]
This happens if none of the `luci-mod-*` packages are installed.
