### ISSUE TITLE
QoS over Nftables : Realtime Rate

### ISSUE THREAD

**Issue by NotANewNick** [openwrt/luci#5595]
Hello,
I have experienced the Realtime Rate of QoS over Nftables not actually showing the Rate and instead accumulating change over time.

![image](https://user-images.githubusercontent.com/77489671/145723111-f2d390e1-909f-46e7-bbc1-95d896710763.png)
![image](https://user-images.githubusercontent.com/77489671/145723125-c4b6851f-8984-44b7-9247-01ee8eafa4f8.png)

nft-qos config:
```
config default 'default'
        option limit_mac_enable '0'
        option priority_enable '0'
        option limit_enable '0'
```

Is anyone able to suggest a fix or perhaps point me to where I might be able to fix it my self?

Output of nft-qos-monitor table after I cleared it and re-populated it:
```
table inet nft-qos-monitor {
        chain upload {
                type filter hook postrouting priority filter; policy accept;
                ip saddr 192.168.2.130 counter packets 5770 bytes 1662725
                ip saddr 192.168.2.133 counter packets 3077 bytes 423946
                ip saddr 192.168.2.128 counter packets 41 bytes 5097
                ip saddr 192.168.2.111 counter packets 9755 bytes 820329
                ip saddr 192.168.2.133 counter packets 2526 bytes 325679
                ip saddr 192.168.2.100 counter packets 2265 bytes 586656
        }
        chain download {
                type filter hook prerouting priority filter; policy accept;
                ip daddr 192.168.2.130 counter packets 6887 bytes 3718503
                ip daddr 192.168.2.133 counter packets 10082 bytes 13001735
                ip daddr 192.168.2.128 counter packets 41 bytes 13285
                ip daddr 192.168.2.111 counter packets 16924 bytes 23939737
                ip daddr 192.168.2.133 counter packets 8995 bytes 11823975
                ip daddr 192.168.2.100 counter packets 11880 bytes 14101632
        }
}

**Comment by wulfy23** [comment]
https://github.com/openwrt/luci/blob/d5385fa93b5d802f780e1e2393cc20dd633cdcd9/applications/luci-app-nft-qos/luasrc/view/nft-qos/rate.htm#L32

**Comment by NotANewNick** [comment]
That seems like an unlikely culprit. From the table I can see multiple values for the same IP which to is telling me that something is not populating the table correctly.

The code you posted seems to be the interface part and not the data processing part.

**Comment by wulfy23** [comment]
yeah... there are duplicate values... that's related to the core package not luci

easy fix pr's for the packages repo are another story... there's a thread on the forum if you'd like a fix for that to check if it helps with your values...

**Comment by NotANewNick** [comment]
Building now. I'll close the ticket in case this works.
Thank you!

**Comment by NotANewNick** [comment]
So far so good. Thank you.

**Comment by wonson** [comment]
Thanks @wulfy23 
Your fix is good, but do you know which repo should we report the issue and get it into official release?

Now we need to apply the patch after every sysupgrade :(
