### ISSUE TITLE
RPC call to luci/getLocaltime failed with error -32002: Access denied

### ISSUE THREAD

**Issue by my1639963** [openwrt/luci#5622]
![image](https://user-images.githubusercontent.com/16329362/147837614-4e6b0a18-3af0-4cd4-b547-dad4ae08dcbf.png)
![image](https://user-images.githubusercontent.com/16329362/147837631-bb3ce2d9-8096-4eb9-8309-cf6fe90d9680.png)

**Comment by jow-** [comment]
The use of `getLocaltime` has been dropped with 68815c88b0ebcfd0116070510a4c43ccff1d0310 - seems you're running an incoherent package selection. Make sure that all LuCI packages, in particular luci-mod-system are updated to the latest version.
