### ISSUE TITLE
howto comile luci 21.02 seperately in  ubuntu using gcc ? 

### ISSUE THREAD

**Issue by lovelypp777** [openwrt/luci#5623]
Hi
    I want to use luci seperately in ubuntu when develop a luci-app plugin. to ease the develop, it's better to ran luci  seperately in ununtu.
I googled and found there is only an doc metioned this, but it is based on old luci version (0.12).
    I found since 18.06, luci compile sytem is changed and there is no Makefile there. I don't know if there is some doc / instrctions to compile luc 21.02 seperately in ubuntu.

    any suggestion is appreciate, thanks!

**Comment by hnyman** [comment]
LuCI can't be run separately It is tightly tied to OpenWrt and the core libraries there.
