### ISSUE TITLE
luci-app-acme: unable to recognize new argument

### ISSUE THREAD

**Issue by terrytw** [openwrt/luci#5624]
Dear Devs,

I found out that acme had added a new function in version 3.0.1 to specify "preferred-chain" as a response to Letsencrypt's expired Root certificate. Acme package of openwrt has been updated and this function is working for me via cli by adding:

`	option preferred-chain "ISRG"`

However if I install the latest luci-app-acme from snapshot, it will not recognize this argument and simply would not load. 

I think it will be an easy fix, just 2-3 lines in 

https://github.com/openwrt/luci/blob/openwrt-21.02/applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js

However I am not a coder, so can someone please fix it? Thanks!

**Comment by jow-** [comment]
The line
```
option preferred-chain "ISRG"
```

is invalid syntax, uci option names may not contain dashes.
