### ISSUE TITLE
Add support for OpenVPN's topology option

### ISSUE THREAD

**Issue by jerry-yuan** [openwrt/luci#5625]
I have tried to add an additional option named topology to config file like these:
![image](https://user-images.githubusercontent.com/13380647/147879751-35d8398f-89b2-4758-a480-4b96a696baf9.png)
It work well after openvpn instance restart even there is no any items displayed in LuCI.

But if I tried to modify any options via LuCI, these additional options will disappear.

The topology option is used to define the tunnel device's mode and will affect the vpn clients to get hostname resolution from dnsmasq service which only support relove hostnames for the request from local subnet by default.

I want to know if there's possible to support those options which has not mapped to LuCI displayed items or make it easy to add some custom options (like advanced configuration edit mode).

**Comment by mrendo** [comment]
Hello,

In advance go to Networking add dev-type and make sure it says tun it should do by default then go back to the drop down menu and topology will be on the bottom of the menu. Hope that helps.

Mr E

**Comment by jerry-yuan** [comment]
> Hello,
> 
> In advance go to Networking add dev-type and make sure it says tun it should do by default then go back to the drop down menu and topology will be on the bottom of the menu. Hope that helps.
> 
> Mr E

Thanks for your reply and with following your suggestions I have successfully added the `topology` option.

By the way, I'd like to know if there is any documents to reference which has explained the dependencies between the options?
(like if option `b` need to be set after `a` has been set to some value)

**Comment by Torbins** [comment]
Wow, that's super counterintuitive.
