### ISSUE TITLE
do not restart automatically after changing dockerman configuration

### ISSUE THREAD

**Issue by qiuzi** [openwrt/luci#5628]
After modifying the configuration and saving the application in the interface, docker did not restart
Need to manually **/etc/init.d/dockerd restart**
@feckert

**Comment by feckert** [comment]
As far as I can remember, the problem was that some users do not want this.
Because if they have many containers, all of them are restarted at once after saving.
This could be a problem in some constellations.
Maybe this can be mentioned explicitly in the LuCI.
Pullrequest are welcome
