### ISSUE TITLE
OpenWrt 21.02.1: Failed to change the system password

### ISSUE THREAD

**Issue by alex9434** [openwrt/luci#5629]
I get the error "Failed to change the system password" on Luci on OpenWrt 21.02.1 on arm64 (Raspberry Pi 4). I use a system that I have compiled using buildroot and that uses NGINX for Luci. Any idea what can cause this
![Capture](https://user-images.githubusercontent.com/8560446/148046162-0140b983-f5af-4d8d-ae9e-490ad9811f91.PNG)
?
logread -f does not show anything.

**Comment by jow-** [comment]
Issue the following command on the cli and provide the output here:
```
ubus call luci setPassword '{ "username": "root", "password": "test" }'
```

**Comment by alex9434** [comment]
I just get the following message: 
```
{
        "result": false
}

```

**Comment by alex9434** [comment]
Connected to this issue is another issue: If I change the root password using passwd on the command line, I can no longer log into LuCI. It will always tell me the password is incorrect. The link between LuCI and the system password seems to be broken.

**Comment by jow-** [comment]
The shadow-passwd applet (`/usr/bin/passwd`) will store blowfish (`$2a$...`) ciphers in `/etc/shadow` which musl libc's `crypt()` implementation does not support by default, hence the failure to log into LuCI. This is nothing that can be fixed on the LuCI side.

I pushed another fix though which will ensure to invoke Busybox `passwd` when changing the system password via LuCI, in this case it is guaranteed that a supported password hash is written to `/etc/shadow`.

**Comment by hmh** [comment]
This isn't a bug in LuCI, but shouldn't the *defaults* in shadow-passwd and musl be kept in sync?  Without doing an in-depth look at the issue, it seems like there's a bug in shadow-passwd packaging if it has defaults that are incompatible with the defaults for the default libc (musl)...

**Comment by jow-** [comment]
Yes, they should be kept in sync, but this outside of the scope of LuCI and this repo.
