### ISSUE TITLE
default password?

### ISSUE THREAD

**Issue by seeY8** [openwrt/luci#5637]
I've installed LuCI openwrt-19.07 branch (git-21.044.30835-34e0d65), and encountered with pre-populated username "root" and cannot login with all my guesses, including leaving the password field blank. Please help/enlighten. Thanks.

**Comment by hnyman** [comment]
There is no separate Luci password. The same root password that you use when logging ssh console.

**Comment by jow-** [comment]
A prexisting `sysauth` cookie might prevent logins due to browser security heuristics.

**Comment by seeY8** [comment]
Thank you for the help, working now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
