### ISSUE TITLE
Error creating interfaces

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#5646]
I have Snapshots and have noticed that when creating an interface, it is not saved when pressing the "Create interface" button. It also does not save the entered data such as IP or any settings. It only lets me exit if I press the "Back" button and go back to the interface to just configure it there.

![1](https://user-images.githubusercontent.com/47670442/149198422-bf2781b3-d632-4c65-bd79-993e356eebd2.png)
![2](https://user-images.githubusercontent.com/47670442/149198456-61e919f5-4581-4bdd-bd2c-c4fd15fac132.png)
![3](https://user-images.githubusercontent.com/47670442/149198474-ec639a91-66b7-415e-9059-e277c770bfbe.png)
![4](https://user-images.githubusercontent.com/47670442/149198483-810e515b-76e8-4f52-9b0b-de5549c93af4.png)
![5](https://user-images.githubusercontent.com/47670442/149198494-fcf6080e-4273-4917-80e8-caf3349b1ae8.png)
![6](https://user-images.githubusercontent.com/47670442/149198505-a431cfa9-8440-428a-b013-3510067bd318.png)

**Comment by jow-** [comment]
Check the browser debug console for errors.

**Comment by castillofrancodamian** [comment]
![7](https://user-images.githubusercontent.com/47670442/149248066-cb890bc7-7f59-4fed-a364-e5f254a3cc96.png)
![8](https://user-images.githubusercontent.com/47670442/149248070-c66aaef2-351f-4129-b4ea-f410b80a1155.png)
![9](https://user-images.githubusercontent.com/47670442/149248076-6f47deba-1997-4d9c-96b3-d9b2ae6cd363.png)

**Comment by castillofrancodamian** [comment]
I have noticed the same error in the DDNS app when creating a new service.
