### ISSUE TITLE
luci-mod-system: the text gets out beyond

### ISSUE THREAD

**Issue by Alexey71** [openwrt/luci#5647]
Firmware update window. The text gets out of the window.
https://github.com/openwrt/luci/blob/e4cab853e4a7d4e1f4428cd180e2af4ad59482b5/modules/luci-base/po/ru/base.po#L3657-L3663

![2022-01-13_003505](https://user-images.githubusercontent.com/10572914/149224892-7a06bbdd-4e56-4e06-a250-4494d2d8f419.jpg)

**Comment by jow-** [comment]
Can you suggest a shorter translation?

**Comment by Alexey71** [comment]
Okay. Changed translation
