### ISSUE TITLE
Drop the lines numbers from .po(t) with i18n sync/scan ?

### ISSUE THREAD

**Issue by hnyman** [openwrt/luci#5655]
@jow- 
Could we drop the line numbers from the .pot and .po files?
They cause constant trouble with PRs, and also cause a bit too much commit spam compared to the benefits, I think.
We could leave the file annotations, even multiple per same source file, so that the amount of string instances could be seen.

Typical example is two-month old PR  #5563 that I just merged, but had to edit the patch due to the changed annotation line numbers (+1 to every one, in this case).

And right now #5654 has lots of (proper by themselves) line number annotation corrections, which may get invalidated before the PR gets committed.

(To be honest, since 901a0821f I can can't even figure out the exact place where the line numbers are added in i18n-scan.pl, so no PR from me :-(

**Comment by jow-** [comment]
No. These source references allow graphical tools like poedit to display source context while translating. They are useful.
