### ISSUE TITLE
luci-app-nlbwmon other options for Commit interval

### ISSUE THREAD

**Issue by ltedone** [openwrt/luci#5656]
Hello,
It would be great if the package luci-app-nlbwmon will allow other options for the Commit interval into the Advanced Settings tab of the Configuration menu, like for example 30 minutes, 1 hour and so on.
In this way it is a better compromise between the 10m option and the 12h option.

**Comment by jow-** [comment]
It does allow other settings, just enter a custom value and press *Enter*.

![image](https://user-images.githubusercontent.com/2528802/151065312-7f1c950d-0fe9-476a-bc8d-8139480db984.png)
![image](https://user-images.githubusercontent.com/2528802/151065400-cba3cedc-b9af-4a83-8e57-3c6d4ed7a7bd.png)
![image](https://user-images.githubusercontent.com/2528802/151065453-92adb560-18db-4dfd-8cdb-4cfce2c87eb2.png)
