### ISSUE TITLE
luci-app-nlbwmon cannot reload data

### ISSUE THREAD

**Issue by ltedone** [openwrt/luci#5657]
Hello,
Sometimes the luci-app-nlbwmon package doesn't show the previously recorded statistics, I think because the file is corrupt. It happened multiple time to me and the only solution is to delete the db file and restart the router. Also clicking the force reload link doesn't do anything.
Is there any solution for this issue?
![Screenshot_2022-01-22-13-44-51-128_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/715588/150849666-6a905eda-8431-481a-9b63-9a014a35668a.jpg)

**Comment by jow-** [comment]
Attach the corrupted database file here the next time you encounter this issue.
