### ISSUE TITLE
luci-app-opkg: add pager at the bottom of listed packages

### ISSUE THREAD

**Issue by instag1b** [openwrt/luci#5671]
While looking through my installed packages I noticed that the [pager](https://github.com/openwrt/luci/blob/df07e6b833e97fde2718a5f74feeaa04ad47c099/applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js#L1059) for the package list is placed at the top of the list only. After reaching the bottom of a page, navigating to the next page requires scrolling all the way back up. An additional pager at the bottom would make navigating between pages more convenient.

Current:
![image](https://user-images.githubusercontent.com/48023919/151883478-1709fd66-4151-4432-a2f5-176e6326007e.png)

Proposed change:
![image](https://user-images.githubusercontent.com/48023919/151883613-a0115f6e-df9a-49fa-8160-7eec9831192b.png)

Making this second pager dependent on the length of the package list would be a nice touch if it doesn't add too much code debt.

I'm open to submitting a PR, although I can't make any promises as to when I'll have some free time to work on this.

Additional information:
- OpenWrt 21.02.1 r16325-88151b8303
- LuCI openwrt-21.02 branch (git-22.025.79177-4ec18ec)
- luci-app-opkg git-21.312.69848-4745991

**Comment by stokito** [comment]
@instag1b see my pr #5915
