### ISSUE TITLE
LuCi Firewall | "Enable NAT Loopback" for "Firewall - Port Forwards" does not work properly, fix identified

### ISSUE THREAD

**Issue by naturalpb** [openwrt/luci#5675]
## Steps to reproduce:

1. Go to: Network → Firewall → Port Forwards
2. Create a Port Forward, such as hosting an externally-facing website on TCP 80
3. On the Advanced tab, check "Enable NAT Loopback" and select Loopback source IP = "internal"
4. Attempt to use loopback service on LAN (on LAN, open domain in a web browser)

## Actual behavior:
Service will not load, saying "Connection Closed"

## Expected behavior:
Service loads

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r18729-8c1d5129ee'
DISTRIB_TARGET='mvebu/cortexa9'
DISTRIB_ARCH='arm_cortex-a9_vfpv3-d16'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r18729-8c1d5129ee'
DISTRIB_TAINTS=''

## Tested fix
I got NAT Loopback to work by adding **option family 'ipv4'** to the config redirect entry in /etc/config/firewall

Generated (not working) entry
```
config redirect               
        option target 'DNAT'
        option name 'HTTP'
        list proto 'tcp'
        option src 'wan'        
        option src_dport '80'
        option dest 'lan'  
        option dest_ip '192.168.1.2'
        option dest_port '80' 
```

Working entry with **option family 'ipv4'** added
```
config redirect               
        option target 'DNAT'
        option name 'HTTP'
        list proto 'tcp'
        option src 'wan'        
        option src_dport '80'
        option dest 'lan'  
        option dest_ip '192.168.1.2'
        option dest_port '80' 
        option family 'ipv4'
```

**Comment by hnyman** [comment]
Not a LuCI bug, but problem in the new firewall4 in the main OpenWrt.

Likely @jow-  is already fixing this and related symptoms with this commit in the firewall4 repo:
https://git.openwrt.org/?p=project/firewall4.git;a=commitdiff;h=b2241a1a70f8c367604ad25dea5b615fd1c8a5a1;hp=3ee6a5c54d5c32a635870fae402420d8c653476c

Related stuff:

* https://forum.openwrt.org/t/issue-with-firewall-rules-port-forwarding/119218
* https://forum.openwrt.org/t/build-for-netgear-r7800/316/3323
 
I close this, as this is not a LuCI bug by nature.
