### ISSUE TITLE
OpenWrt 21.02.1 r16325-88151b8303 on TP-Link TL-WR842N/ND v2 very slow!

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [openwrt/luci#5681]
OpenWrt 21.02.1 r16325-88151b8303 on TP-Link TL-WR842N/ND v2 very slow!
luci gui may freese/crash at any time.

**Comment by hnyman** [comment]
No wonder. It is a 32  MB RAM device. 
Not really supported with 21.02 any more.

Please read
https://openwrt.org/supported_devices/432_warning
