### ISSUE TITLE
[BUG] Configuring both 5GHz Client and 5GHz Access Point will cause 5GHz Wi-Fi "disappear"

### ISSUE THREAD

**Issue by ngjiaxue** [openwrt/luci#5683]
### **Overview**
![image](https://user-images.githubusercontent.com/47715013/153724588-f0b88916-4a2b-4056-b31f-c67789097e00.png)
<br />
### **If there is no 5GHz Client configure (Only 5GHz Access Point & 2.4GHz Access Point)**
![image](https://user-images.githubusercontent.com/47715013/153724312-004c8876-9f64-4563-8f31-c1a7e90a7149.jpg)
<img src="https://user-images.githubusercontent.com/47715013/153724344-3c8e6fc1-3f0e-4df8-b973-4d3c2330acf6.png" width="200" />
<br />
### **If configuring both 5GHz Client and 5GHz Access Point will cause 5GHz Wi-Fi "disappear"**
![image](https://user-images.githubusercontent.com/47715013/153724082-370d855d-4e64-42f5-8a9d-ae61120aa6c1.png)
<img src="https://user-images.githubusercontent.com/47715013/153724132-702601ba-f411-477c-9834-2bbd499df86a.png" width="200" />

**Comment by jow-** [comment]
This does not look like a LuCI issue, the networks appear to be configured correctly as far as LuCI settings are concerned. Maybe a low level driver bug or your phone not properly picking up the beacons of the 5GHz radio or not supporting channel 157 which is restricted in some regions.

Closing this as this cannot be solved in LuCI

**Comment by ngjiaxue** [comment]
Hi,

So, may I know who should I contact regarding to this issue? I really need
help...

Thank you.

Best Regards,
Ng Jia Xue

**Comment by hnyman** [comment]
It might be better to seek help in the Openwrt discussion forum.   https://forum.openwrt.org/
(and you should also provide details from the system log, that which king of error messages are shown)

OpenWrt wifi bugs should currently be reported at the OpenWrt bug tracker:  https://github.com/openwrt/openwrt/issues

There are also similar bugs for the QCA988x wifi chip mentioned in the old bug tracker, so you are not the first to notice the problem with that wifi chip:
https://bugs.openwrt.org/index.php?do=details&task_id=1158
https://bugs.openwrt.org/index.php?do=details&task_id=3569
