### ISSUE TITLE
luci-app-firewall: error in destination zone selection in port forwarding

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#5685]
## Steps to reproduce:

1. go to: Network → Firewall → Port Forwards → Add
2. create a new rule with "wan" for "Source zone" and "unspecified" for "Destination zone". Add any port to test
3. Save & Apply
4. press the "Edit" button to verify that the zone in "Destination zone" changed to "lan".

## Expected behavior:

Let the change be applied.

## Additional Information:

DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r18801-56256259a1'
DISTRIB_TARGET='ath79/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r18801-56256259a1'
DISTRIB_TAINTS=''

**Comment by castillofrancodamian** [comment]
![1](https://user-images.githubusercontent.com/47670442/154125187-636a7de4-f877-42c1-bed1-55a688e903b1.png)
![2](https://user-images.githubusercontent.com/47670442/154125198-a7d6a192-ee7b-4450-9e67-793c3f6cd740.png)
![3](https://user-images.githubusercontent.com/47670442/154125202-b3c79a86-a265-4331-8b80-a0074bb7b459.png)
![4](https://user-images.githubusercontent.com/47670442/154125205-208fc94d-c29f-4bd1-aeee-e0d7832355e2.png)
![5](https://user-images.githubusercontent.com/47670442/154125206-c375ae16-3ab1-45d1-92f5-274fc887bdd0.png)

**Comment by jow-** [comment]
Okay, so it`s _unspecified_ which does not work. I tried selecting a specific zone and that was fine.

**Comment by castillofrancodamian** [comment]
![1](https://user-images.githubusercontent.com/47670442/154130218-c95cdd87-e532-4132-b236-da20da5f58d1.png)
![2](https://user-images.githubusercontent.com/47670442/154130220-03217b16-a002-4723-a8e3-5dd26f8d18a4.png)
![3](https://user-images.githubusercontent.com/47670442/154130224-10e1ba03-e3b6-4fdc-882a-eb9dc270c3e0.png)
![4](https://user-images.githubusercontent.com/47670442/154130225-4f54923e-a0a7-4bb4-9387-4e858e191ddc.png)
![5](https://user-images.githubusercontent.com/47670442/154130228-e9b809f5-7adb-4f81-859b-4d7b61f9fed7.png)
