### ISSUE TITLE
 luci-app-cshark fails to install on OpenWRT-21.02.2

### ISSUE THREAD

**Issue by macherius** [openwrt/luci#5690]
# Issue template:
## Steps to reproduce:

1. Install [openwrt-21.02 branch (git-22.046.85957-59c3392)](https://github.com/openwrt/luci) / OpenWrt 21.02.2 r16495-bf0c965af0
2. Go to "System->Software" menu, or use opkg directly
3. Install luci-app-cshark

Problem:
The install fails with this message:
```
Executing package manager

Installing luci-app-cshark (git-20.110.55046-74da73b) to root...
Downloading https://downloads.openwrt.org/releases/21.02.2/packages/arm_cortex-a9_vfpv3-d16/luci/luci-app-cshark_git-20.110.55046-74da73b_all.ipk
Installing libpcap1 (1.9.1-3.1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.2/packages/arm_cortex-a9_vfpv3-d16/base/libpcap1_1.9.1-3.1_arm_cortex-a9_vfpv3-d16.ipk
Installing libmbedtls12 (2.16.12-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.2/packages/arm_cortex-a9_vfpv3-d16/base/libmbedtls12_2.16.12-1_arm_cortex-a9_vfpv3-d16.ipk
Installing libustream-mbedtls20201210 (2022-01-16-868fd881-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.2/packages/arm_cortex-a9_vfpv3-d16/base/libustream-mbedtls20201210_2022-01-16-868fd881-1_arm_cortex-a9_vfpv3-d16.ipk
Configuring libmbedtls12.
Configuring libpcap1.

Errors

Collected errors:
 * check_data_file_clashes: Package libustream-mbedtls20201210 wants to install file /lib/libustream-ssl.so
	But that file is already provided by package  * libustream-wolfssl20201210
 * opkg_install_cmd: Cannot install package luci-app-cshark.

The opkg install command failed with code 255.
```
## Actual behavior:
Software package fails to install.

## Expected behavior:
Software package installs.

**Comment by jow-** [comment]
Not a LuCI issue.

**Comment by macherius** [comment]
What is the right place to report this, please?

**Comment by jow-** [comment]
The specific issue lies here:
https://github.com/openwrt/packages/blob/master/net/cshark/Makefile#L30

The underlying `cshark` package in the packages repository explicitly selects a non-default ustream provider which will conflict with the default one shipped by OpenWrt. I suppose this has been broken for a quite a while already, likely since OpenWrt switch to ship HTTPS support by default (using wolfssl instead of mbedtls).

**Comment by macherius** [comment]
@jow I was pointed to this tracker by the openwrt.org page itself, you may want to update the link there too
https://openwrt.org/packages/pkgdata/luci-app-cshark
