### ISSUE TITLE
luci-app-attendedsysupgrade: broken

### ISSUE THREAD

**Issue by BabochkaAce** [openwrt/luci#5709]
@aparcar this commit #5704 broke the luci-app-attendysupgrade package

![broken](https://user-images.githubusercontent.com/100963280/156861822-774264f9-57f7-417b-ae82-2830d1038377.png)

**Comment by JulioMC81** [comment]
Hi! Same problem here, snapshot r19043:
![IMG_20220305_081852](https://user-images.githubusercontent.com/79814337/156873091-8e66d061-2906-4bdf-acf5-c552b73521c4.jpg)

Thanks! :)

**Comment by castillofrancodamian** [comment]
![222](https://user-images.githubusercontent.com/47670442/157351699-036f425c-0c6a-4be0-99ca-63df575d6acc.png)

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/luci/commit/65266c490a40e589bde23acb1bcac401813c43ce

Sorry for the delay.

**Comment by JulioMC81** [comment]
> Fixed via [65266c4](https://github.com/openwrt/luci/commit/65266c490a40e589bde23acb1bcac401813c43ce)
> 
> Sorry for the delay.

Thanks @aparcar!!!
