### ISSUE TITLE
luci-mod-freifunk: hostname on front page missing

### ISSUE THREAD

**Issue by FreifunkUFO** [openwrt/luci#571]
on some public freifunk status luci pages the HTML-Title is incorrect: One "?" is printed instead of the Hostname

http://10.61.234.76/cgi-bin/luci/   -> HTML-Title:  ? - Overview - LuCI
http://10.61.234.76/cgi-bin/luci//freifunk/   -> HTML-Title:  ? - Overview - LuCI
http://10.61.234.76/cgi-bin/luci//freifunk/status -> HTML-Title: 234-76 - Status - LuCI

its also a ? on "Overview", "Contact", "Map" & "Services"

happens only on openwrt-trunk since some months..

**Comment by jow-** [comment]
Same cause as #570

**Comment by jow-** [comment]
Please follow up on #570.

**Comment by FreifunkUFO** [comment]
problem is still existing, we also track it here: https://plan.leipzig.freifunk.net/issues/361

**Comment by FreifunkUFO** [comment]
still existing.

but, the hostname (missed in title-header) is mentioned inside the standard-freifunk-text at this index-page correctly
