### ISSUE TITLE
Luci:  boundary/range checking of IPv6 ULA prefix

### ISSUE THREAD

**Issue by ebws-git** [openwrt/luci#5721]
## Steps to reproduce:

1. go to: Network → Interfaces → Global network options → IPv6 ULA-Prefix
2. enter a prefix that does not begin with FC or FD, such as FEED:ABBA:BEEF::/48 or ABBA:DABA:D000::/48
3. Save & Apply

## Actual behavior:
Luci allows invalid address prefixes, saves them, and attempts to apply them to interfaces.
The router applies them to its own IPv6 interfaces.
It may or may not propagate them to DHCP clients; my results seem to vary.

ULA addressing fails silently, with no error or user feedback.

## Expected behavior:
Values outside the range beginning with FC or FD should not be accepted or applied to the configuration.
An error message should explain the problem.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.2'
DISTRIB_REVISION='r16495-bf0c965af0'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 21.02.2 r16495-bf0c965af0'
DISTRIB_TAINTS=''

```

**Comment by jow-** [comment]
The backend code does not impose any specific range limits as far as I know, it processes any valid IPv6 address. Due to that, I'll not make the LuCI validation code stricter.
