### ISSUE TITLE
Luci: support xtables-addons geoip

### ISSUE THREAD

**Issue by PanderMusubi** [openwrt/luci#5722]
This is a feature request, hence the template was not used.

Please support in the web interface a way to block incoming and/or outgoing network traffic for specific countries by using xtables-addons geoip.

For more information, see https://github.com/PanderMusubi/geoipblock/

**Comment by jow-** [comment]
Create a traffic rule and enter `-m geoip --src-cc XX,YY` as extra iptables argument in the advanced options.

**Comment by jow-** [comment]
No, but neither would the linked tutorial.
