### ISSUE TITLE
Changing wireless settings breaks wireless [X5000R] in version 21.02.2

### ISSUE THREAD

**Issue by xerofule** [openwrt/luci#5726]
Same issue as https://github.com/openwrt/luci/issues/5468 that was closed but it looks it still occurs to several users even after upgrading to 21.02.2.

## Steps to reproduce:
1. go to: Network → Wireless → in radio1 click on Add 
2. An error will appear:
TypeError
Cannot read properties of undefined (reading 'value')

**Comment by dfateyev** [comment]
Probably related to openwrt/openwrt#9379.
The maintainer reports that wireless settings show up properly in the master snapshot.

**Comment by jow-** [comment]
Duplicate of https://github.com/openwrt/luci/issues/5468
