### ISSUE TITLE
Type Error due to stale browser cache after LAN address change

### ISSUE THREAD

**Issue by louisheibert** [openwrt/luci#5728]
Archer 1750 A7
OpenWrt 21.02.2 r16495-bf0c965af0 / LuCI openwrt 21.02 branch git-22.052.50801-31a27f3
(with all available updates as of 3/16/2022)

## Steps to reproduce:

1. Install all recommended updates (in LuCI) after the initial bare firmware installation.
2. Change the LAN interface IP address in LuCI, uci, or network config file.
3. Restart network or reboot router
4. click on the "Network > Interface" or "Network > Firewall" menu option

## Actual behavior:
1. A red Type Error "firewall.getZoneColorStyle is not a function" appears
2. Network (or Firewall) screen never opens.

## Expected behavior:
(it works instead of not working)

## Additional Information:
Clearing the browser cache (at least in Firefox) fixes the problem.
I'm not a web app expert by any means... however, I suspect web apps are supposed to poison cache data when necessary.
Perhaps this is just a Firefox problem because nothing from the old ip address should be referenced in cache when using the new ip address.  It should effectively be a completely different web site from the browser's perspective.
In fact it really seems like a security bug on their part.   Still, I thought you should know since I've never had this problem with OpenWRT before.

**Comment by jow-** [comment]
LuCI employs some cache busting techniques (mainly query strings containing the git hash LuCI wath built from). Under some circumstances (some luci packages except luci-base updated or only luci-base updated by opkg) the cache buster string might get updated but the browser fetching old version of classes. If that happened on a device previously using the IP you changed your device to, you might see that behavior.

There's no simple fix to this short of recalculating the cache buster string at runtime, after each package update. I'll close this issue as wontfix as clearing the browser cache usually suffices to solve the issue.
