### ISSUE TITLE
luci-app-openvpn: openvpn config may be corrupted on upload

### ISSUE THREAD

**Issue by anyuta1166** [openwrt/luci#5731]
## Steps to reproduce:
1. Go to VPN - OpenVPN
2. upload OVPN configuration file

## Actual behavior:
Configuration file may be corrupted.

## Expected behavior:
Configuration file should be not modified on upload.

## Additional Information:

In my specific case "-----END OpenVPN **Static key** V1-----" was replaced with "-----END OpenVPN **Statickey** V1-----" and OpenVPN didn't start. I obviously can't share my config file because it contains keys. But it is reproducible on any OpenWRT build since 2018-10-23 when the ovpn file upload support was added.

**Comment by anyuta1166** [comment]
Should be fixed by #5732

**Comment by jow-** [comment]
Fixed by #5775 5732
