### ISSUE TITLE
luci-mod-system: get error in leds.js

### ISSUE THREAD

**Issue by ptpt52** [openwrt/luci#5739]
```
....
                o.onchange = function(ev, section, value) {
                        for (var i = 0; i < plugins.length; i++) {
                                var plugin = plugins[i];
                                if ( plugin.name === value )
                                        this.map.findElement('id', 'cbid.system.%s.trigger'.format(section))
                                                .nextElementSibling.innerHTML = plugin.form.description || '';
                        }
                }
....
```
here 
`this.map.findElement('id', 'cbid.system.%s.trigger'.format(section)).nextElementSibling`
always get `null`
<img width="552" alt="11" src="https://user-images.githubusercontent.com/5331426/159354536-da720b35-cbeb-49da-bd71-8a413dbab10f.png">

**Comment by ptpt52** [comment]
@feckert  hi, need help to fix this

**Comment by feckert** [comment]
I find that strange!
If I understand the error message correctly, it means

 that the value of the variable section is `null` and therefore not set?
![1](https://user-images.githubusercontent.com/553091/159642681-5cf0bdc2-85f3-4cfb-9415-f76bf50a4f5e.png)

**Comment by jow-** [comment]
Well I suppose this happens whenever a trigger is configured initially that has no description. In this case the cbi description div will not be generated and when switching to another trigger later, attempts to change the description div contents will fail.

Solution: always set a description (empty string in case there is none)

```diff
diff --git a/modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js b/modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js
index c0cbd7a4f1..f34a9360c3 100644
--- a/modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js
+++ b/modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js
@@ -97,7 +97,7 @@ return view.extend({
                        for (var i = 0; i < plugins.length; i++) {
                                var plugin = plugins[i];
                                if ( plugin.name === trigger)
-                                       this.description = plugin.form.description || '';
+                                       this.description = plugin.form.description || ' ';
                        }
                        return trigger;
                };
```

**Comment by jow-** [comment]
@ptpt52 @feckert - can you please verify the fix suggested above?

**Comment by ptpt52** [comment]
@jow- ok, I reproduce the issue and the above patch fix it.

**Comment by feckert** [comment]
@ptp52 Thanks for reporting and testing I have now pushed the fix from @jow- into the master.
https://github.com/openwrt/luci/commit/3de544600385ca365c833aec99f89113daa12292

**Comment by jow-** [comment]
@feckert - you fixed the wrong code instance I'm afraid. You do need to fallback to the single-space value when assigning `this.description` in order to render the description div. Setting it via `innerHTML` after the fact will lead to the same issue.

**Comment by feckert** [comment]
@jow- Thank you for pointing this out!. I didn't look properly and edited the wrong line! My mistake sorry.
Hopefully fixed with https://github.com/openwrt/luci/commit/b6fb2b16971f80afcfb7c3dd1d257c60f6cced7f
This proves once again that it does not hurt to open a pullrequest even though it is only a small change!
