### ISSUE TITLE
luci-base/ucitrack: What's the ucitrack 'affects' really means?

### ISSUE THREAD

**Issue by jjm2473** [openwrt/luci#5745]
In this commit https://github.com/openwrt/luci/commit/a72d90faac7ffe815a904d6816159549548e6fab , "/etc/config/system" change triggers dnsmasq reload. So, 'affects' will be reload on config changes.

But in this code:
https://github.com/openwrt/luci/blob/8e09f1833b27e98208472ae44ff4b2ed218fa083/modules/luci-base/root/etc/init.d/ucitrack#L43-L48
'affacts' change will trigger the config reload.

What the hell of 'affacts'?

**Comment by jow-** [comment]
Yeah, looks like the arguments are swapped. The `affected` means "pretend that these configs got changed if the main config got changed in order to trigger a reload of potentially affected services".
