### ISSUE TITLE
Luci Attended-Sysupgrade: Resource not Found error

### ISSUE THREAD

**Issue by t3dium** [openwrt/luci#5756]
Screenshot of error:
![image](https://user-images.githubusercontent.com/83690012/161499795-9961f32c-e07e-43c8-bf0b-70e60b9f2a28.png)
when pinging the sysupgrade domain, no issues there:
![image](https://user-images.githubusercontent.com/83690012/161500032-d7e3d19f-1eb0-487b-817e-dd14fe036749.png)

**Comment by castillofrancodamian** [comment]
Manually update the snapshot.

**Comment by hnyman** [comment]
Not related to LuCI GUI itself. Likely a temporary server problem, missing build or something.
