### ISSUE TITLE
fdisk: (& resize2fs) add an option to automatically use the whole disk

### ISSUE THREAD

**Issue by oittaa** [openwrt/luci#5761]
## Steps to reproduce:

It would be helpful if you could just click a checkbox or something like that and the whole disk would be used automatically.

## Actual behavior:

At the moment you have to follow the manual instructions at https://openwrt.org/docs/guide-user/installation/openwrt_x86#resizing_partitions

## Expected behavior:

Having a possibility to use the whole disk from the web gui.

**Comment by jow-** [comment]
LuCI usually does not introduce such logic by itself. A facility has to be provided by OpenWrt itself which we can then expose in the ui.
