### ISSUE TITLE
Luci: dhcp-range set wrong when using CDIR list for interface setup

### ISSUE THREAD

**Issue by snyderra** [openwrt/luci#5762]
# Issue template:
1. Please make sure that the issue subject starts with `<package-name>:`
2. Issues related to end of life (EOL) releases are not supported or maintained and will be closed
3. Remove lines from top till here and fill in the following questions
***

## Steps to reproduce:
Create interface 
click '...' next to ipv4 address
enter valid info
192.168.1.1
broadcast 192.168.1.255

dhcpsever 
start = 20
limit = 20

save all

## Actual behavior:
**Example: Replace the following lines and remove this**
look at /var/etc/dnsmasq.conf.*
will result in line below
dhcp-range=set:guest,192.168.1.2,192.168.1.0,255.255.255.255,1h

with  inconsistent DHCP range at line 32 of /var/etc/dnsmasq.conf.cfg01411c in system log
## Expected behavior:
**Example: Replace the following lines and remove this**
dhcp-range=set:guest,192.168.1.20,192.168.1.39,255.255.255.0,1h
## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

**Example: Replace the following lines and remove this**
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.2'
DISTRIB_REVISION='r16495-bf0c965af0'
DISTRIB_TARGET='bcm27xx/bcm2710'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 21.02.2 r16495-bf0c965af0'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
By clicking `...` you switched to CIDR notation. In this case you should specify a prefix for your IP address, otherwise `/32` is assumed. Try entering `192.168.1.1/24` instead of `192.168.1.1`.
