### ISSUE TITLE
feature request: sysctl settings backup

### ISSUE THREAD

**Issue by philfry** [openwrt/luci#5778]
Hi all,

it would be nice to have the backup save custom sysctl settings, too, usually located in `/etc/sysctl.d/*`.

Thanks! :)

**Comment by jow-** [comment]
This should be a matter of simply adding `/etc/sysctl.d/` to `/etc/sysupgrade.conf`. Also consider filing a bug against base-files in https://github.com/openwrt/openwrt/, stating it should treat `/etc/sysctl.d/` as conffile directory.
