### ISSUE TITLE
Prevent static DHCP assignment of the same IP address to different hosts

### ISSUE THREAD

**Issue by mgkuhn** [openwrt/luci#5779]
## Steps to reproduce:

1. go to: LuCI / Network / DHCP DNS / Static Leases
3. add the *same* IPv4 address for two different MACs
4. Save & Apply
5. restart

## Actual behavior:

[Observed on TurrisOS:](https://forum.turris.cz/t/suggestion-do-not-get-locked-out-of-omnia-by-a-silly-mistake-or-a-typo/9787)

```
root@turris:~# grep -i dnsmasq /var/log/messages
2019-03-20 22:36:19 notice dnsmasq[]: DNS rebinding protection is active, will discard upstream RFC1918 responses!
2019-03-20 22:36:19 notice dnsmasq[]: Allowing 127.0.0.0/8 responses
2019-03-20 22:36:20 crit dnsmasq[5664]: duplicate dhcp-host IP address 10.0.0.75 at line 29 of /var/etc/dnsmasq.conf
2019-03-20 22:36:20 crit dnsmasq[5664]: FAILED to start up
```

As a result, the DHCP server does not start up and the router becomes difficult to contact from DHCP clients to diagnose and remedy the situation. In other words, a simply typo can almost brick the device.

## Expected behavior:

Show a warning or error message if a user attempts to statically assign the same IP address to two different hosts, because this kind of mistake can render the DHCP server inoperative.

**Comment by jow-** [comment]
Already implemented in recent LuCI versions:
![image](https://user-images.githubusercontent.com/2528802/165097884-b9a74b8e-d8a6-44d8-a08d-644358371bd1.png)

Fixed by commit 7e562895380d6bbe89ed88fe7576272c078f3b59
