### ISSUE TITLE
<system.js> - default language handling is faulty

### ISSUE THREAD

**Issue by EVhonza** [openwrt/luci#5783]
The language selector at fresh installation shows just "auto" - as no specific language is installed. Now is the device locallized to EN.
After installation of local language (luci-i18n-base-cs) shows Czech and "auto". But for both selection device is locallized just to CZ. :-o
After installed second local language (luci-i18n-base-en) shows Czech, English and "auto". Finally you can freely switch CZ and EN. 👍 
Why the installation of locallized version break the ability switch to default english version?

## Steps to reproduce:

1. Take fresh installation OpenWrt 21.02.3
2. install luci-i18n-base-cs
3. go to: System - System - Language and style and select Czech and press Save and apply.

## Actual behavior:
As soon as your computer browser locale setting tell the LUCI: "this user is Czech", the opportunity to switch the LUCI web to EN is currently not possible. The both options "auto" and "Czech" use the same Czech locallization.  You have to install luci-i18n-base-en to be able to do that.

## Expected behavior:
Add some "default - English" option to be able to freely switch EN / CZ just with installed luci-i18n-base-cs.
Necessity of installation of luci-i18n-base-en seems to be some strange option. The software already know english locallization as this is its native language.

**Comment by castillofrancodamian** [comment]
My solution was to install `luci-i18n-base-en`.

**Comment by jow-** [comment]
> My solution was to install luci-i18n-base-en.

That should not be needed anymore. We could in fact drop all the dummy luci-i18n-*-en packages now

**Comment by castillofrancodamian** [comment]
I only had that package installed to have the option to choose "English".
