### ISSUE TITLE
Missing elements/corrupt UI in LuCi

### ISSUE THREAD

**Issue by Hew-ux** [openwrt/luci#5799]
## Issue:
After performing a sysupgrade to 21.02.3, many UI elements in LuCi have gone missing/unrendered, resulting in a buggy appearance.

The login screen:
![0](https://user-images.githubusercontent.com/67527064/166671080-bfd109f5-5704-47b3-9f7b-3e5d8f2c6376.PNG)

The status screen:
![1](https://user-images.githubusercontent.com/67527064/166671140-b569cc08-a2e6-4b8b-b6c2-5473a2a17e49.PNG)

During package installation, text becomes unreadable (this was the point that I understood this is definitely a bug, not a new minimalist UI direction):
![2](https://user-images.githubusercontent.com/67527064/166671151-6ceb1e4b-95ff-46eb-9821-1f95fbc1b877.PNG)

## Steps to reproduce:
 1. Upgrade to 21.02.3
 2. Open LuCi using a browser such as Pale Moon.

## Actual behavior:
The UI appears broken (but still usable).

## Expected behavior:
The UI appears as intended.

## Additional Information:
Behaviour seems inconsistent between browsers, with other elements reappearing. Pale Moon in particular seems to have coped the brunt of it.

**Comment by jow-** [comment]
Did you try to clear the browser cache?

**Comment by jow-** [comment]
Seems to be due to the fact that PaleMoon does not support CSS `calc()` expressions in color functions such as `rgba()`, `hsl()` etc. See also https://repo.palemoon.org/MoonchildProductions/UXP/issues/1826

**Comment by Hew-ux** [comment]
Yes, clearing the cache did not solve the issue.

Using another theme, everything appears fine so thank you for that suggestion. In the meantime, maybe the default theme should not use features that may not be supported by all browsers yet? That's more a subjective topic though, as far as I'm concerned this will no longer be an issue once Pale Moon adds support for it.
