### ISSUE TITLE
luci-app-attendedsysupgrade: allow to reinstall same version

### ISSUE THREAD

**Issue by CAFxX** [openwrt/luci#5809]
Note: this is an enhancement request

## Steps to reproduce:

1. Open the app and check for available updates

## Actual behavior:

Current firmware version is never presented as an option

## Expected behavior:

Current firmware version is presented as an option, at least in the case when the set of currently installed packages (and/or their version) differs from the list of packages in the current base image.

## Additional Information:

This would allow users to rebuild the image of the current firmware version with a different set of installed packages, something that would be especially useful if the user has a small overlay FS as it would provide a good path for users to free up space in the overlay by "baking" into the base image the packages stored in the overlay (a quick search on Google or on the openwrt forums should confirm that the overlay filling up is a rather common problem experienced by users).

Another use case provided by @McGiverGim is to [persist the installed packages in case you need to do a hard reset](https://github.com/openwrt/luci/issues/5809#issuecomment-1123943292).

**Comment by McGiverGim** [comment]
It will help too if you need to do a hard reset, to not loose the packages installed...

**Comment by aparcar** [comment]
Please try https://github.com/openwrt/luci/pull/5833

**Comment by CAFxX** [comment]
@aparcar sorry for the lack of responses, I was away for a few weeks

> Please try https://github.com/openwrt/luci/pull/5833

I'm not terribly familiar with how to run the proposed change on my router. Is there a guide I can follow?

**Comment by CAFxX** [comment]
I just reinstalled the current version without issues using the new functionality. Thanks @aparcar!

**Comment by aparcar** [comment]
Excellent, spread the word

**Comment by CAFxX** [comment]
Updated https://openwrt.org/faq/no_space_left_on_device to mention this
