### ISSUE TITLE
Feature Request: enable random mac address function in LuCI

### ISSUE THREAD

**Issue by Che15ea** [openwrt/luci#5819]
Feature Request:
I think we need a random/stable/specify Mac address spoofing function in LuCI as wifi/ethernet server/client to protect against mac address tracking. The feature is already built in most linux distros.

**Comment by jow-** [comment]
Duplicate of #5819

**Comment by jow-** [comment]
Correction. Duplicate of #5517

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/openwrt/luci/issues/5517
- https://github.com/openwrt/luci/issues/5819
- https://github.com/openwrt/luci/issues/5845
- https://github.com/openwrt/luci/pull/5896
- https://github.com/openwrt/luci/issues/7131
