### ISSUE TITLE
luci-mod-network: "VLAN port state" the '-' is a non-ascii encoded character

### ISSUE THREAD

**Issue by 6ang996** [openwrt/luci#5826]
I found that the WEB page shows that "VLAN port state" the '-' is a non-ascii encoded character, is this intentional?
I added a comment on this commit
https://github.com/openwrt/luci/commit/eeef38d53412a78f185f0bb53153ecb3fe9e8838

**Comment by jow-** [comment]
Yes, it is intentional.
