### ISSUE TITLE
 bytes / s to Bits/ s 

### ISSUE THREAD

**Issue by woudanator** [openwrt/luci#5828]
So this is more of a question then a issue 

At moment interface graphs are showing in bytes/s and i would like to generate the graph images to be in bits/s or Mbits/s rather 
is this at all possible and where would i go to change this or do the conversion

**Comment by hnyman** [comment]
You could edit the graph definitions for those graphs that you want to change, and compile a personal version of luci-app-statistics.  (the editing can be also done in a live router)

Reverse Polish Notation can be used to pass arithmetics for rrdtool that created the graph.

See ping graph for example. (multiplication by 100 for percent display).
https://github.com/openwrt/luci/blob/master/applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/ping.js#L39


https://www.google.com/search?q=rrdtool+rpn
