### ISSUE TITLE
luci-app-samba - Luci doesn't show the services tab after installing luci-app-samba

### ISSUE THREAD

**Issue by Solution40** [openwrt/luci#5829]
# Issue template:
1. Please make sure that the issue subject starts with `<package-name>:`
2. Issues related to end of life (EOL) releases are not supported or maintained and will be closed
3. Remove lines from top till here and fill in the following questions
***

## Steps to reproduce:
Clean install, install the luci-app-samba and no services tab is created, samba configuration through luci is not possible.

## Additional Information:
I tried 2 versions:

1)  OpenWrt 21.02.3
2) OpenWrt SNAPSHOT r19709-4bed263af7 / LuCI Master git-22.137.71281-d6dbedd

Platform TP-LINK 2600

Thanks

**Comment by jow-** [comment]
Logout/login to make it appear. Also just tested installing the package through LuCI here. The menu entry will appear once you change the page.

**Comment by Solution40** [comment]
Hi, I tried again. Installed a fresh openwrt instance on the tp link 2600, installed samba4-server and luci-app-samba4. However, no services tab. Can you inform me howto troubleshoot? Check / enable log?

**Comment by Solution40** [comment]
Hi, I've installed through the gui. However, i did a install with "keep settings"..perhaps that's causing the issue? I rather debug / trace to see why it doesn't work as expected. Would that be possible? Or should i go for a clean install withour "keep settings" and then try to install luci samba?
