### ISSUE TITLE
There is no automatic channel option

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#5837]
This is on both radios.

![Screenshot_20220612_172134](https://user-images.githubusercontent.com/47670442/173252190-40fb4dbb-0de9-4d8b-bedb-bc5c85f94322.png)

When I switch to `auto` on the `option channel` line, I see this in LuCI:

![Screenshot_20220612_172623](https://user-images.githubusercontent.com/47670442/173252326-369ffbf6-bd18-4153-bad9-295edb6c032a.png)

**Comment by jow-** [comment]
The `auto` choice depends on the hostapd acs feature. Hostapd feature detection has been broken in OpenWrt master, follow up at https://github.com/openwrt/openwrt/issues/10036.

Not a LuCI issue.

**Comment by castillofrancodamian** [comment]
It's already [fixed](https://github.com/openwrt/openwrt/commit/f03b20837bf821241acecaf94fc6a26ce49991be).
