### ISSUE TITLE
luci-i18n-*-en: Several Portuguese translations in English language files

### ISSUE THREAD

**Issue by raineth** [openwrt/luci#5860]
A weblate user incorrectly contributed several Portuguese translations as English localizations that were merged in commit 62ee3fbfbf91e41d1260ea7023145fbdd4eb0d86.  It appears that all submissions from viniribeirossa in that commit should be rolled back. Those changes should probably be fixed in Weblate as well -- I don't know whether they have any admin tools to help mass-correct actions from confused users.

**Comment by feckert** [comment]
I've noticed that too!
@hnyman I think we have to fix that in the weblate, otherwise there will be merge conflicts.

**Comment by castillofrancodamian** [comment]
The English "translation" should be removed.

**Comment by hnyman** [comment]
@jow-  already pondered about removing the English translation from the built packages. It serves no function as the untranslated strings are already in English.

Any language (including English) can't be easily disabled in weblate, as it allows casual users to initiate new translation languages. 

Ps. I can't easily do fixes myself in the next few weeks as I am travelling.

**Comment by jellybean13** [comment]
Some "translations" are still wrong despite OpenWrt 22.03-SNAPSHOT r19507-158a5af801 installed.

Language: English
![image](https://user-images.githubusercontent.com/46275808/176989035-e987c6ae-96a6-48d7-8322-fb3c232cce3d.png)

**Comment by hnyman** [comment]
I think that I managed to remove the erroneous Portuguese strings from English .po files.
(The translator had apparently tried to translate luci-app-attended-sysupgrade, and weblate had then propagated the same strings into other packages.)

I backported the fixes from master to 22.03 and 21.02.
