### ISSUE TITLE
luci-theme-openwrt XML Parsing Error On Login Page When Failed SSH Login Attempt In List of Attempts

### ISSUE THREAD

**Issue by jeffpritchard** [openwrt/luci#5862]
***

## Steps to reproduce:

1. Have a SSH login failure in your history. 
Example: `[Tue Jun 28 19:29:14] SSHd[fail] [before auth from <192.168.1.143:59326>: Error reading: Connection reset by peer])`
2. Go to the login page (in this case 192.168.1.1).

## Actual behavior:

1. After a brief load, the page redirects to https://192.168.1.1/cgi-bin/luci with the error:
`XML Parsing Error: not well-formed
Location: https://192.168.1.1/cgi-bin/luci
Line Number 108, Column 53:
[Tue Jun 28 19:29:14] SSHd[fail] [before auth from <192.168.1.143:59326>: Error reading: Connection reset by peer]
----------------------------------------------------^`

## Expected behavior:

The login page should display?

## Additional Information:
I can work around for the time being by hitting "stop" real fast in the browser before the page redirects. Obviously whatever is spitting out the previous login attempts in SSH isn't escaping the characters, though I'm not clear on why the page cares so much it needs to redirect. I tried looking in /www but it wasn't apparent where exactly I would find this.

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.3'
DISTRIB_REVISION='r16554-1d4dea6d4f'
DISTRIB_TARGET='bcm27xx/bcm2711'
DISTRIB_ARCH='aarch64_cortex-a72'
DISTRIB_DESCRIPTION='OpenWrt 21.02.3 r16554-1d4dea6d4f'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
Something is injecting log messages into the LuCI output. This is not a default behavior of LuCI, also the log message format `[Tue Jun 28 19:29:14] SSHd[fail] [...]` looks nonstandard to me.

It appears that you're running a modified version of LuCI or some application/addon/custom code or a nonstandard webserver configuration exhibiting this. A default LuCI installation is completely independent of log messages in syslog.
