### ISSUE TITLE
luci-proto-sstp errror:Network device is not present and connection is not established.

### ISSUE THREAD

**Issue by Bebebe1974** [openwrt/luci#5872]
luci-proto-sstp
Add new interface with name VPNSSTP
SSTP server                            sstp.test.com
PAP/CHAP Username             test
PAP/CHAP password              test
connection is not established with an error:Network device is not present and no messages in system log.

If  replace the domain name (sstp.test.com) with the ip address (195.201.63.43) then there is no error and connection is not established. If you add --cert-warn --tls-ext to the Extra sstpc options field (Tab Advanced settings), then there is still no connection.
Log: 
Thu Jul  7 11:19:19 2022 user.notice URL-DEBUG: hotplug (iface): action='ifdown' interface='VPNSSTP'
Thu Jul  7 11:20:20 2022 daemon.notice netifd: Interface 'VPNSSTP' is setting up now
Thu Jul  7 11:20:21 2022 daemon.notice netifd: VPNSSTP (7483): Command failed: Unknown error
Thu Jul  7 11:20:21 2022 local0.notice sstpc[7548]: Resolved 195.201.63.43 to 195.201.63.43
Thu Jul  7 11:20:23 2022 local0.notice sstpc[7548]: Connected to 195.201.63.43
Thu Jul  7 11:20:31 2022 daemon.notice netifd: VPNSSTP (7483): Command failed: Unknown error
Thu Jul  7 11:20:46 2022 local0.debug sstpc[7548]: Unrecoverable SSL error 0
Thu Jul  7 11:20:46 2022 local0.debug sstpc[7548]: HTTP handshake with server failed
Thu Jul  7 11:20:46 2022 daemon.notice netifd: VPNSSTP (7548): **Error: HTTP handshake with server failed, (-1)
Thu Jul  7 11:20:46 2022 daemon.notice netifd: Interface 'VPNSSTP' is now down

If run sstpc --cert-warn --tls-ext --user test --password test sstp.test.com --log-level 3, then everything works fine, but no data in luci.
## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
ISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.0-rc3'
DISTRIB_TARGET='ramips/mt7621'

**Comment by lexxnsk** [comment]
Usually "Network device is not present" means, that there is no route to reach your server. probably, you should tick default route on your wan connection or manually add route to your routing table

**Comment by feckert** [comment]
I think this is not a LuCI issue.
Please have a look at the [sstpc proto](https://github.com/openwrt/packages/blob/86522d77f1ccf7ed80ef556e0d6621efbd190275/net/sstp-client/files/lib/netifd/proto/sstp.sh#L77).
There you can see how the netifd calls sstpc.
You can try to replay the behavior of netifd and find out which argument is interrupting the call.

**Comment by Neustradamus** [comment]
@enaess: What do you think about it?
