### ISSUE TITLE
LuCi cannot delete Devices

### ISSUE THREAD

**Issue by QA-Manager** [openwrt/luci#5875]
## Steps to reproduce:

1. go to: Network → Interfaces → Devices
2. I have somehow created 4 instances of br-lan.13 (I was attempting to set up a VLAN); all four instances appear on the Devices screen

## Actual behavior:
 - There isn't any way to delete a Device

## Expected behavior:
 - There should be a way to delete Devices (and Interfaces), if for no other reason than you may create one and decide that you don't want it.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

   I was able to fix the problem by rebooting the device; I guess those changes hadn't been saved in /etc/config/network. After rebooting LuCi no longer showed any of the br-lan.13 Devices, and they aren't in the config file.

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.3'
DISTRIB_REVISION='r16554-1d4dea6d4f'
DISTRIB_TARGET='mvebu/cortexa9'
DISTRIB_ARCH='arm_cortex-a9_vfpv3-d16'
DISTRIB_DESCRIPTION='OpenWrt 21.02.3 r16554-1d4dea6d4f'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
You can't delete devices, only unconfigure them. Netifd will eventually garbage collect ephemeral devices.

**Comment by QA-Manager** [comment]
If I create a VLAN 13 and a br-lan.13, and later reconfigure my network and decide that I don't need VLAN 13, LuCi shouldn't force me to leave it in the system as though it is still being used.

**Comment by Arndorferd** [comment]
This makes no sense, please reopen, it shouldnt be forced to stay in the system

**Comment by QA-Manager** [comment]
@Arndorferd, are you asking me to write up this defect again, or are you asking @jow- to reopen it?

**Comment by jow-** [comment]
It is the way it works, you unconfigure the device and it gets garbage collected by the system once it becomes unused. You can reboot or restart the network service to force immediate removal of the kernel device.
