### ISSUE TITLE
GNU tar without gzip support makes backup config fail

### ISSUE THREAD

**Issue by neheb** [openwrt/luci#5893]
## Steps to reproduce:
Compile image with GNU tar and no gzip support

Go to http://openwrt//cgi-bin/luci/admin/system/flash

Download backup and note how the file is broken.

## Actual behavior:
Broken compressed file.

## Expected behavior:
Working compressed file

Recently ran into this with a custom image.

The issue is here: https://github.com/openwrt/luci/blob/master/modules/luci-mod-system/root/usr/share/rpcd/acl.d/luci-mod-system.json#L152

The solution is to pipe tar's output to gzip. No idea if this stuff supports piping.

**Comment by jow-** [comment]
Not going to fix this, any sane system should provide a `tar` command that understands the `z` flag.
