### ISSUE TITLE
luci-proto-ipv6: Request blocklist for domain names

### ISSUE THREAD

**Issue by NatoBoram** [openwrt/luci#5908]
## Steps to reproduce:

1. 

```ash
opkg install 6in4 luci-proto-ipv6
uci set network.wan6.proto="$PROTO"
uci set network.wan6.username="$USERNAME"
uci set network.wan6.peeraddr="$PEERADDR"
uci set network.wan6.ip6addr="$IP6ADDR"
uci add_list network.wan6.ip6prefix="$IP6PREFIX"
uci set network.wan6.tunnelid="$TUNNELID"
uci set network.wan6.password="$PASSWORD"
uci set network.wan6.mtu="$MTU"
uci commit network
/etc/init.d/network restart
```

2. Login to Instagram

## Actual behavior:

You get a "wrong password" message even though the password is correct

## Expected behavior:

It should work

## Additional Information:

Disabling the `wan6` interface solves the issue

Basically, I would like to request a domain blocklist for `network.wan6` accessible via the GUI. I'm not sure how feasible is this.

**Comment by jow-** [comment]
This can be done by adjusting the dnsmasq configuration (also possible via ui), see https://forum.openwrt.org/t/openwrt-dns-only-ipv4-disable-ipv6-dns/82781/6
