### ISSUE TITLE
LuCI doesn't show all active connections

### ISSUE THREAD

**Issue by abajk** [openwrt/luci#5909]
The device is BT Home Hub 5A. An iperf was started between the LAN and WAN interfaces. On the router, active connections were checked using conntrack:
```
root@OpenWrt:/# conntrack -L
tcp      6 7206 ESTABLISHED src=192.168.1.10 dst=10.0.1.1 sport=42978 dport=5201 packets=2 bytes=112 src=10.0.1.1 dst=10.0.1.2 sport=5201 dport=42978 packets=1 bytes=60 [ASSURED] mark=0 use=1
tcp      6 7439 ESTABLISHED src=192.168.1.10 dst=192.168.1.1 sport=40818 dport=80 packets=27 bytes=3416 src=192.168.1.1 dst=192.168.1.10 sport=80 dport=40818 packets=26 bytes=7155 [ASSURED] mark=0 use=1
tcp      6 src=192.168.1.10 dst=10.0.1.1 sport=42984 dport=5201 packets=2 bytes=112 src=10.0.1.1 dst=10.0.1.2 sport=5201 dport=42984 packets=1 bytes=60 [OFFLOAD] mark=0 use=2
conntrack v1.4.6 (conntrack-tools): 3 flow entries have been shown.
```

```
root@OpenWrt:/# cat /proc/net/nf_conntrack
ipv4     2 tcp      6 7208 ESTABLISHED src=192.168.1.10 dst=10.0.1.1 sport=42978 dport=5201 packets=2 bytes=112 src=10.0.1.1 dst=10.0.1.2 sport=5201 dport=42978 packets=1 bytes=60 [ASSURED] mark=0 zone=0 use=2
ipv4     2 tcp      6 7439 ESTABLISHED src=192.168.1.10 dst=192.168.1.1 sport=40818 dport=80 packets=19 bytes=2332 src=192.168.1.1 dst=192.168.1.10 sport=80 dport=40818 packets=18 bytes=4807 [ASSURED] mark=0 zo2
ipv6     10 udp      17 20 src=fe80:0000:0000:0000:f03e:b3ff:fe46:64c4 dst=ff02:0000:0000:0000:0000:0000:0001:0002 sport=546 dport=547 packets=1 bytes=150 [UNREPLIED] src=ff02:0000:0000:0000:0000:0000:0001:00022
ipv4     2 tcp      6 src=192.168.1.10 dst=10.0.1.1 sport=42984 dport=5201 packets=2 bytes=112 src=10.0.1.1 dst=10.0.1.2 sport=5201 dport=42984 packets=1 bytes=60 [OFFLOAD] mark=0 zone=0 use=3
```

LuCI does not show an active iperf connection (port number 42984):
![Screenshot from 2022-07-31 11-48-41](https://user-images.githubusercontent.com/30129889/182020742-92e79410-a658-49ed-b1a5-c78b77863751.png)

Active connections on the host:
![Screenshot from 2022-07-31 11-49-17](https://user-images.githubusercontent.com/30129889/182020765-1bc60d51-f4f3-4e5b-bd76-b73f65f523b3.png)

The most interesting thing is that conntrack shows 3 active IPv4 TCP connections. LuCI shows 3 connections, and only 2 TCP connections are listed below.

I was able to reproduce the same problem on my main router (TP-Link WDR4300) on OpenRT 22.03.

**Comment by abajk** [comment]
Maybe this is due to the fact that software flow offloading is enabled on my devices. Offloaded connections do not have the ESTABLISHED flag.

**Comment by jow-** [comment]
Please share the relevant `/proc/net/nf_conntrack` output, this is what is parsed.

**Comment by abajk** [comment]
@jow- 
I updated the issue description with the contents of `/proc/net/nf_conntrack`. The connection is on this list, but has been filtered out for some reason by LuCI.

**Comment by abajk** [comment]
I confirm that the fix works, however, it incorrectly counts statistics when software flow offload is enabled ([Issue](https://github.com/openwrt/openwrt/issues/10399)).
