### ISSUE TITLE
luci-app-attendedsysupgrade: "packge" should be "package"

### ISSUE THREAD

**Issue by ManuLinares** [openwrt/luci#5925]
https://github.com/openwrt/luci/blob/71017a530473bf52d5fbf507c62be096975f2bfb/applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/configuration.js#L27

` _('Show advanced options like packge list modification'));`

should be

` _('Show advanced options like package list modification'));`

**Comment by stangri** [comment]
@aparcar

**Comment by aparcar** [comment]
Excellent. Could you please create a PR?

**Comment by ManuLinares** [comment]
> Excellent. Could you please create a PR?

https://github.com/openwrt/luci/pull/5931

**Comment by hnyman** [comment]
Fixed by #6019
