### ISSUE TITLE
Some website can't be display.

### ISSUE THREAD

**Issue by NBSOD** [openwrt/luci#5926]
# Issue 
Some website can't be display,and display "Web Page Blocked".Sure this website is ok,when i use 4G it's all right.But throuth a openwrt device it's turn into a wrong status.So is openwrt rom has some module can filter website ?

*** This is the website displayed

Web Page Blocked
Access to the web page you were trying to visit has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.

User: router wan interface ip

URL: my test url

Category: phishing
***

## Additional Information:
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='18.06.4'
DISTRIB_REVISION='r7808-ef686b7292'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 18.06.4 r7808-ef686b7292'
DISTRIB_TAINTS=''
```

**Comment by hnyman** [comment]
Nothing to do with LuCI GUI.

Sounds like the IP that you ISP is currently assigned to you, has been placed on somebody's blacklist. Possibly the previous DHCP leaseholder (some other user at the ISP) has caused the blacklisting (either the address currently assigned to you or the whole ISP's address space).
