### ISSUE TITLE
Does LuCI consider using Angular or React?

### ISSUE THREAD

**Issue by ballzb** [openwrt/luci#5928]
I'm curious about that, and I can't find any useful information through Google. 
So I come here to ask for help, Thanks.

**Comment by feckert** [comment]
There was an attempt by @jow- to develop a [LuCI2 (luci-ng)](https://github.com/jow-/luci-ng) based on angular. But for various reasons, this plan was discarded and it was decided that LuCI should not use a JavaScript framework.
