### ISSUE TITLE
OpenWrt 22.03.0-rc6 r19590-042d558536 / LuCI openwrt-22.03 branch git-22.237.32198-08fb383

### ISSUE THREAD

**Issue by Alkanino** [openwrt/luci#5954]
I just installed OpenWrt version 22.03.0-rc6 r19590-042d558536 / LuCI openwrt-22.03 branch git-22.237.32198-08fb383 on a linksys EA7300 and when I add mesh with wpad-mesh-openssl package in the None encryption part, It may be a presentation failure, all the nodes connect correctly, no error is presented in the log

**Comment by jow-** [comment]
Fixed by https://github.com/openwrt/openwrt/commit/4a4d0bf78ddbbf17508891c5c837e5eb00420b5c
