### ISSUE TITLE
feature: use zxcvbn for password strength estimation

### ISSUE THREAD

**Issue by aparcar** [openwrt/luci#5966]
Currently we're using a [regex based](https://github.com/openwrt/luci/blob/70a749020198367e188369646da9cf5adb767071/modules/luci-mod-system/htdocs/luci-static/resources/view/system/password.js#L25) approach to estimate password strength. I wonder if better estimations could be possible using `zxcvbn` for that.

https://github.com/dropbox/zxcvbn

**Comment by jow-** [comment]
Farr too many external dependencies and too much bloat for too little gain.

**Comment by aparcar** [comment]
Ugh never mind, it's actually 400kB in size.

**Comment by aparcar** [comment]
Hey @github I found a bug:

![image](https://user-images.githubusercontent.com/16000931/189093622-a583e2d9-a75c-4ea5-b708-8b4fe7883ba3.png)
