### ISSUE TITLE
luci-mod-admin-full Add 802.11k/v related configurations

### ISSUE THREAD

**Issue by Headcrabed** [openwrt/luci#5972]
Since openwrt already supports 802.11k/v by using full version of wpad, it would be better if we add configurations for them in luci.
[Here](https://openwrt.org/docs/guide-user/network/wifi/basic#neighbor_reports_options_80211k) is parameter list.

**Comment by hnyman** [comment]
There are already PR #5572 and #5571 for that purpose.
