### ISSUE TITLE
luci: Static Leases not pulled from all files

### ISSUE THREAD

**Issue by arrmo** [openwrt/luci#5973]
## Steps to reproduce:
1. create static DHCP leases - in [`/etc/dnsmasq.conf`](https://openwrt.org/docs/guide-user/base-system/dhcp.dnsmasq#configuration), or [`/etc/ethers`](https://openwrt.org/docs/guide-user/base-system/dhcp#static_leases) (as noted at the links provided ... and confirmed, these do work for DHCP).
2. go to: Network → DHCP and DNS → Static Leases
3. the static leases defined in these two files are not showing => only pulling from `/etc/config/dhcp` it seems?

## Actual behavior:
As above - the static leases are not shown in LuCI

## Expected behavior:
Expect that the static leases (in LuCI) are pulled from all three options.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.0'
DISTRIB_REVISION='r19685-512e76967f'
DISTRIB_TARGET='mvebu/cortexa53'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 22.03.0 r19685-512e76967f'
DISTRIB_TAINTS='no-all busybox'
```

**Comment by hnyman** [comment]
> only pulling from /etc/config/dhcp it seems?

LuCI is mostly about configuring via "uci" with the files in /etc/config. The whole LuCI syntax is based on reading/manipulating uci config files.

LuCI provides support for some external upstream configuration files, but rarely for all features / optional files.

**Comment by jow-** [comment]
Static leases outside of uci are unsupported.

**Comment by arrmo** [comment]
OK, understand - thanks. I made the (bad) assumption that all 3 sources were OK. Appreciate the feedback!

**Comment by arrmo** [comment]
Sorry, hope you don't mind - but with my static leases all in the correct file, I'm getting an error in LuCI now 😞. I'm trying to dig into the code, but perhaps you know ... the Static Leases page, it seems to call an RPC (ubus?) - do you know what function it's calling?

This is the error I receive,
![image](https://user-images.githubusercontent.com/8756384/190470939-e032e281-7fea-4ca3-a4f0-56aaa883b49e.png)

FYI, I think it's caused by the number of static leases I have (~ 130), if I try just a few it works fine.

Thanks!!
