### ISSUE TITLE
nlbwmon: sort is broken -- sorts by the number, not respecting the units

### ISSUE THREAD

**Issue by mikeage** [openwrt/luci#5994]
## Steps to reproduce:

1. Install luci-app-nlbwmon
2. Click on a column to sort by bytes or packets

## Actual behavior:

99 KiB comes before 10 MiB when sorting by descending bytes

## Expected behavior:

99 KiB should come after 10 MiB 

It should be sorting these as 10000000 vs 99000, instead of 10 vs 99

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.0'
DISTRIB_REVISION='r19685-512e76967f'
DISTRIB_TARGET='rockchip/armv8'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_DESCRIPTION='OpenWrt 22.03.0 r19685-512e76967f'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
This has been fixed by 4f4ad9bff5482211695bf564543e4d34de4808d8
