### ISSUE TITLE
System Page Should Show Discovered Peripherals

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#60]
**Reported by marca56@gmail.com on 13 Apr 2009 19:20 UTC**
Currently, System/System shows main CPU and firmware versions loaded, but should also show discovered physically attached peripherals, major configuration and their associated driver versions. 

For example, the System/System screen would be more useful for an administrator if it listed the WLAN chip and driver:

Broadcom 4318 WLAN found (core revision 9)
Broadcom 43xx driver loaded [ Features: PL, Firmware-ID: FW13 ]
Firmware version 478.104 (2008-07-01 00:50:23)
AP mode Up, Channel 11, WPA2-PSK

or for the Ethernet switch chip, driver and configuration:

Broadcom: device eth1 found: BCM5325E
Switch: enabled
Port 0(W): 100FD enabled stp: none vlan: 1 mac: 00:00:00:00:00:00
Port 1(4):  DOWN enabled stp: none vlan: 1 mac: 00:00:00:00:00:00
Port 2(3):  DOWN enabled stp: none vlan: 1 mac: 00:00:00:00:00:00
Port 3(2):  DOWN enabled stp: none vlan: 1 mac: 00:00:00:00:00:00
Port 4(1):  10HD enabled stp: none vlan: 1 mac: 00:00:00:00:00:00
Port 5(C): 100FD enabled stp: none vlan: 1 mac: 00:00:00:00:00:00
VLANs: BCM5325/535x disabled mac_check mac_hash    

Thanks.

**Comment by hnyman** [comment]
outdated old stuff
