### ISSUE TITLE
Luci small visual/functional bug

### ISSUE THREAD

**Issue by Imwithstupid007** [openwrt/luci#6007]
When in Luci (snapshot OpenWrt SNAPSHOT r20813-3968529285 / LuCI Master git-22.260.19132-34dd31a; Belkin RT3200):

1. Goto "System-Software"
2. Select tab "Installed"
3. Scroll down to the bottom of the page
4. The next page button (with >>) doesn't work

![image](https://user-images.githubusercontent.com/38496665/194325296-d1241495-8e74-4fcd-acda-817b8065bc36.png)

It looks like its active but doesn't react to clicks.
Clicking the equivalent button on the top of the page works and shows the next page. After going back to the bottom of first page the button works. 
So it looks like it only malfunctions when the page is first opened.

The equivalent button on the tab "Available" seems to work fine. The tab "Updates" i didn't test.

**Comment by hnyman** [comment]
Seems to work ok for me on
OpenWrt SNAPSHOT r21170-6198eb3e64 / LuCI Master git-22.299.72136-a98e2ea

Still broken for you? (with current LuCI)

**Comment by Imwithstupid007** [comment]
Seems to work fine now (on  SNAPSHOT r21164).

**Comment by Imwithstupid007** [comment]
Hmm.....
Seems to be broken again on OpenWrt SNAPSHOT r21335-e410833bdd / LuCI Master git-22.319.67745-a1ee78f.

**Comment by hnyman** [comment]
Adding also here the explanation from #6156:

The bottom button wants to jump over page 2 and go directly to page 3 with packages 201-300. 
And if you have less than 200 packages (like @Imwithstupid007 screenshot above with only 166 packages), the button probably thinks that there is no possibility to change page and gets disabled.
