### ISSUE TITLE
Can't install luci with yesterdays nightly build 20221010

### ISSUE THREAD

**Issue by bittin** [openwrt/luci#6014]
Hey!

Installed yesterday evenings Nightly build on my Linksys router and Luci won't install

https://pastebin.com/1MUeZ2jN

**Comment by hnyman** [comment]
Temporary package version glitch (that happens with nightly builds).
Wait a day, update package list and try again.
(you already have a newer libnl-tiny that LuCI seems to expect(

**Comment by bittin** [comment]
works again today with todays nightly after a sysupgrade via the CLI
