### ISSUE TITLE
luci-app-https-dns-proxy's missing strings on Weblate

### ISSUE THREAD

**Issue by Matthaiks** [openwrt/luci#6020]
Strings introduced by https://github.com/openwrt/luci/commit/ca9a6d3c7ae0513ca1a5edb823931ffa47c1d68c cannot be translated via Weblate because only the English (Developer) locale has them (6 more strings).

https://hosted.weblate.org/projects/openwrt/luciapplicationshttps-dns-proxy/

Missing strings:
![DNS HTTPS Proxy](https://user-images.githubusercontent.com/3577122/195591475-1b740216-e8de-4a59-a6ea-e463d272c018.png)

**Comment by stangri** [comment]
@hnyman is there anything I can do in the app? The resources are in the pot-file, I don't know Weblate enough to address this.
