### ISSUE TITLE
luci-app-ddns: Incorrect tooltip

### ISSUE THREAD

**Issue by majaha** [openwrt/luci#6028]
If you click `Edit` on a ddns service and open the `Timer Settings` tab, the tooltip under `Error Retry Interval` is duplicated from the `Error Retry Counter` entry.

Probably the tooltip under `Retry Unit` should be moved under `Error Retry Interval`, and the `Retry Unit` tooltip should should read "Units for the Error Retry Interval"

![image](https://user-images.githubusercontent.com/8265836/196061075-5747061d-8d29-467c-9acf-682fde4a20ab.png)

**Comment by systemcrash** [comment]
This issue can be closed.
