### ISSUE TITLE
Ubiquiti AP AC LR - Install luci-mod-rpc

### ISSUE THREAD

**Issue by deanfourie1** [openwrt/luci#6059]
HI, I am having trouble installing the package "luci-mod-rpc" on my OpenWRT 21.

I simply cannot find the package. Can anyone help me find luci-mod-rpc and any dependencies for installation on this device?

Thank you very much! I am stuck without it

**Comment by jow-** [comment]
The package is part of the repository, you can install it with opkg.

**Comment by deanfourie1** [comment]
Could you help with doing this procedure offline as the device has no internet
