### ISSUE TITLE
luci logout cannot redirect to /

### ISSUE THREAD

**Issue by ptpt52** [openwrt/luci#6073]
click logout, and the page(the url) stay on:
http://192.168.1.1/cgi-bin/luci/admin/logout

expected:
redirect to /

ping @jow-

**Comment by ptpt52** [comment]
hmm, seems fixed by https://github.com/openwrt/luci/commit/4b1a074c95a674f2da154ee627e053db550cdd9d

**Comment by jow-** [comment]
Was about to say that, yes. Same root cause.

Fixed by https://github.com/openwrt/luci/commit/4b1a074c95a674f2da154ee627e053db550cdd9d
