### ISSUE TITLE
luci-base: file saving (`fs.write`) saves the file, but fails on unexpected response

### ISSUE THREAD

**Issue by oldium** [openwrt/luci#6074]
## Steps to reproduce:

Tested on master build from yesterday (commit [Merge pull request](https://github.com/openwrt/luci/commit/9ea26a75ed44cde3def5d061a867fa513d365c27) https://github.com/openwrt/luci/pull/6064 [from weblate/weblate-openwrt-luci](https://github.com/openwrt/luci/commit/9ea26a75ed44cde3def5d061a867fa513d365c27)). No LUA installed, just plain ucode.

1. go to: System → Backup/Flash Firmware → Configuration tab
2. click Save

## Actual behavior:

![image](https://user-images.githubusercontent.com/1260936/199688937-d3b7acea-c23e-4aa9-8371-81d4485686af.png)

## Expected behavior:

Success.

## Additional Information:

The JavaScript `fs.write` function gets response from RPC call:

```json
{
    "jsonrpc": "2.0",
    "id": 9,
    "result": [
        0,
        null
    ]
}
```

This does not fit the expected response. Older few months old firmware returns the following:

```json
{
    "id": 12,
    "jsonrpc": "2.0",
    "result": [
        0
    ]
}
```

There was no change to the `fs.js` nor to `rpc.js` JavaScript code for 2 years, so I guess this could be related to the ucode switch.

CC @jow-

**Comment by oldium** [comment]
Another difference is that the response now is nicely formatted, old RPC response was received all in one line.

**Comment by jow-** [comment]
@oldium - fix pused. It only affected installations without uhttpd or uhttpd-mod-ubus.

**Comment by oldium** [comment]
Thanks, I will test it. You are right, I am using lighttpd, so no uhttpd.

**Comment by oldium** [comment]
Works fine, thanks for a quick fix!
