### ISSUE TITLE
Luci status realtime rate: error (nft-qos)

### ISSUE THREAD

**Issue by AntonyFl** [openwrt/luci#6082]
After install luci-app-nft-qos on master branch I get this error in /cgi-bin/luci/admin/status/realtime

![rate-error](https://user-images.githubusercontent.com/104377429/200368306-8f816454-b017-4895-a5d2-8b18da0b276f.png)

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='snapshot'

DISTRIB_REVISION='r21204-f795ecc0dd'
DISTRIB_TARGET='rockchip'
```

**Comment by ManuLinares** [comment]
https://github.com/openwrt/luci/compare/master...ManuLinares:luci:master

Here is a patch https://github.com/openwrt/luci/commit/9b1ee4cc6dfeda5b92711dfa085ac34c462b5e48.patch

You could test it uploading [the entire file rate.htm](https://raw.githubusercontent.com/openwrt/luci/9b1ee4cc6dfeda5b92711dfa085ac34c462b5e48/applications/luci-app-nft-qos/luasrc/view/nft-qos/rate.htm) to your router like this

`scp -O new_rate_file.htm router_ip:/usr/lib/lua/luci/view/nft-qos/rate.htm`
