### ISSUE TITLE
luci-app-attendedsysupgrade: cannot find dependency attendedsysupgrade-common

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/luci#6102]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency ucode-mod-html for luci-base
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-base found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency attendedsysupgrade-common for luci-app-attendedsysupgrade
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-attendedsysupgrade found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-attendedsysupgrade.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 *      ucode-mod-html
 *      attendedsysupgrade-common
 * opkg_install_cmd: Cannot install package luci.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/openwrt/master/openwrt'
make[1]: *** [package/Makefile:111: /home/openwrt/master/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/openwrt/master/openwrt'
make: *** [/home/openwrt/master/openwrt/include/toplevel.mk:231: world] Error 2

**Comment by jow-** [comment]
You probably need to do a `./scripts/feeds update`, `./scripts/feeds install -a -p luci; make defconfig`. In any case not LuCI related.
