### ISSUE TITLE
luci-proto-wireguard status display error.

### ISSUE THREAD

**Issue by zdz2019** [openwrt/luci#6117]
Pull the latest source code and test that the status interface of luci-proto-wireguard is abnormal.

The overview interface displays abnormally.
![Snipaste_2022-11-25_11-01-50](https://user-images.githubusercontent.com/50648881/203892590-b0138a76-e5e5-4956-8c89-17eb6a036e58.png)

The details interface is displayed normally.
![Snipaste_2022-11-25_11-03-33](https://user-images.githubusercontent.com/50648881/203892639-2934a72c-ed27-4603-abd9-5bf855c2625e.png)

**Comment by jow-** [comment]
This looks like https://github.com/openwrt/luci/commit/90a2b1eaeb58b7169b31fdc097c5bfe6f557c778 is missing. Make sure your `ui.js` is current and maybe clear your browser cache.

**Comment by zdz2019** [comment]
you are right thank you!
