### ISSUE TITLE
LuCI MVC framework standalone?

### ISSUE THREAD

**Issue by shuhaowu** [openwrt/luci#612]
I've read that LuCI, in addition to being a web ui for managing OpenWRT routers, is also [supposed to be a MVC framework for embedded development][1]. I see the documentation via github for modules and such. However, it seems to allude to the fact that I have to include at least some of the web ui in if i just write my app with a module (I see files in htdocs in even the luci-base module).

Is there anyway to leverage the existing framework for dealing with things like POST data, URL dispatch, and such without having to include any part of LuCI's web UI?

[1]: http://lua-users.org/lists/lua-l/2008-11/msg00250.html

**Comment by jow-** [comment]
No, the current packaging will always include some ui assets atm.
