### ISSUE TITLE
luci: CONFIG_LUCI_CSSTIDY cause incorrect SVG

### ISSUE THREAD

**Issue by tjjh89017** [openwrt/luci#6145]
## Steps to reproduce:
**Example: Replace the following lines and remove this**

1. enable CONFIG_LUCI_CSSTIDY
2. All Luci checkbox will be invisible.

## Actual behavior:
1. in Luci checkbox will see a V or empty

## Expected behavior:
1. in Luci checkbox will always see empty

## Additional Information:

correct SVG
```
"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='20' height='20'><path d='m2.5 7.4 7.5 7.5-2.5 2.4L0 10Zm15-5L20 4.9 7.5 17.3 5 15Z'/></svg>"
```

after CSSTIDY
```
"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg'  width='20' height='20'><path d='m2.57.47.57.5-2.52.4L010Zm15-5L204.97.517.3515Z'/></svg>"
```

SVG is broken

**Comment by jow-** [comment]
You seem to lack https://github.com/openwrt/luci/commit/69608199973651baf585d24a095edf8c0c42e21f#commitcomment-52088358
