### ISSUE TITLE
luci-mod-dashboard: wireless information is broken/missing

### ISSUE THREAD

**Issue by mistepien** [openwrt/luci#6147]
openwrt 22.03.2

in dashboard wireless section there is some missing information. There is no signal bar and no MAC of client. This information is available in default Overview.

**Comment by DervilRus** [comment]
> openwrt 22.03.2
> 
> in dashboard wireless section there is some missing information. There is no signal bar and no MAC of client. This information is available in default Overview.

 23.05.0. Xiaomi AX3200 All the same. How did you solve the problem?

**Comment by stokito** [comment]
This is a dashboard e.g. a panel for a quick overview.
It's must show only generic inflammation.
You can see details on the Network / Wireless page

http://192.168.1.1/cgi-bin/luci/admin/network/wireless

Here is sources of wifi dashboard for a reference
https://github.com/openwrt/luci/blob/master/modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/30_wifi.js

**Comment by webysther** [comment]
> This is a dashboard e.g. a panel for a quick overview. It's must show only generic inflammation. You can see details on the [Network / Wireless](http://192.168.1.1/cgi-bin/luci/admin/network/wireless) page.
> 
> We may add a link on the bottom of Wifi section but I think that's not needed.
> 
> Please add details of close the issue.

I think what he meant is that the dashboard shows the signal column but it is blank and the information is available in the details. If it is not the objective to show the signal column, then it would be better to remove the column, right? Look the purple selection...

<img width="688" alt="image" src="https://github.com/user-attachments/assets/474b1b6e-fff9-4a20-abb2-e6a301c61931">

**Comment by systemcrash** [comment]
Should look as follows:

![Screenshot 2024-10-07 at 17 12 13](https://github.com/user-attachments/assets/4f95273b-81c8-4594-8ff0-8917d29bf178)
