### ISSUE TITLE
luci-app-sqm: title hierarchy could be improved

### ISSUE THREAD

**Issue by saldry** [openwrt/luci#6161]
## Steps to reproduce:

1. go to: Network → SQM QoS
2. see the web UI

## Actual behavior:

The title of the input box/checkbox is long, and could be transfered into option description.

![pic1](https://user-images.githubusercontent.com/114419832/208387304-443d2ed8-1441-4419-ac24-fe2371d1c91a.png)

It looks bad in Chinese without a proper title hierarchy.

![pic2](https://user-images.githubusercontent.com/114419832/208387908-e05d8fee-728a-4828-9af9-41b1a4b06d16.png)

## Expected behavior:

Proper title hierarchy, brief option name and clear option description, like options in luci-app-watchcat:

![pic3](https://user-images.githubusercontent.com/114419832/208388443-d0d9f792-7095-4644-9bd4-7af9e438961d.png)

## Additional Information:

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03-SNAPSHOT'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
```

**Comment by tohojo** [comment]
Yeah, you're right, that's terrible... will fix :)
