### ISSUE TITLE
luci-base: modal dialogs don't support the escape key

### ISSUE THREAD

**Issue by dhewg** [openwrt/luci#6205]
A little feature request:
Support hitting ESC as a shortcut to the `Discard` button.

On notebooks there're some modal dialogs, where the full height doesn't fully fit on screen. Like the wifi device configuration. Checking some option and just scrolling down for the button is a tad annoying.

**Comment by jow-** [comment]
Fixed with c9939a8

**Comment by dhewg** [comment]
Nice, it works, thanks!
