### ISSUE TITLE
Multicast checkbox-option in Device-tab does not add config entry

### ISSUE THREAD

**Issue by dezza** [openwrt/luci#6219]
### Describe the bug

I'm referring to this forumpost.
https://forum.openwrt.org/t/wireguard-persistent-multicast-option/134575/11

I just tested with 22.03.3, it still does not add it.

I added the `multicast '1'` line myself after trying to toggle/untoggle apply it.

### OpenWrt version

r20028-43d71ad93e

### OpenWrt target/subtarget

ipq806x/generic

### Device

Netgear Nighthawk X4S R7800

### Image kind

Official downloaded image

### Steps to reproduce

visit `luci/admin/network/network`

goto "devices" tab.

Edit a device such as wireguard-interface.

Enable multicast.

### Actual behaviour

`/etc/config/network` is not updated.

### Expected behaviour

`/etc/config/network` should be updated.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Ansuel** [comment]
@dezza thing is that multicast handling is enabled by default so setting the option to 1 should not be needed

**Comment by dezza** [comment]
interesting.. because this was actually not the case for me..

ip link did not show multicast and enabling it with `ip link set WG multicast on` or adding the entry to `/etc/config/network` was the only way to enable it. Now it works persistently even after restarting the device.

**Comment by jow-** [comment]
@Ansuel  This option is complicated (like a lot of other flag options for devices). Netifd itself has no default, it simply does not touch the setting if it is not specified in the config and otherwise sets it to the given value (see https://lxr.openwrt.org/source/netifd/device.c#L402).

We should probably change it from a flag option into a tri-state dropdown with the values:
 - `''` (kernel default)
 - `'0'` (force off)
 - `'1'` (force on)

**Comment by Ansuel** [comment]
@jow- If you want I can take a look and submit a patch. I guess would be overkill to add some kind of checking to understand the current state of multicast.

**Comment by jow-** [comment]
I took a brief look and indeed, checking the current state would be complicated. Problem is that in the end it never is deterministic. Kernel could've changed the value between the ui reading it and eventually storing the config. Behavior of the option (form) on save would flip around based on whatever the ephemeral kernel state would be etc.

The highlighted issue here actually applies to a whole bunch of device options, basically any with the pattern `if (tb[XXX]) { s->flags |= OPT_XXX }` here: https://lxr.openwrt.org/source/netifd/device.c#L298
