### ISSUE TITLE
luci: doesn't work

### ISSUE THREAD

**Issue by castillofrancodamian** [openwrt/luci#6231]
Hi @jow- 

root@archer_c60:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r22020-1c31ca5da9'
DISTRIB_TARGET='ath79/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r22020-1c31ca5da9'
DISTRIB_TAINTS='no-all busybox'

**Comment by castillofrancodamian** [comment]
![Screenshot_20230208_135452](https://user-images.githubusercontent.com/47670442/217598879-f767934f-cf6a-4153-96fd-f7108592d647.png)

**Comment by hnyman** [comment]
Duplicate of #6230

Likely already fixed by 41e9b8d1
