### ISSUE TITLE
/lua/luci/i18n.lua:42: bad argument #1 to 'format' (integer expected, got nil)

### ISSUE THREAD

**Issue by nitdszuj** [openwrt/luci#624]
I am getting from time to time (not regular) when i edit the second wifi interface (virtual) this error.

/usr/lib/lua/luci/dispathcer.lua:449: Failed to execute arcombine dispatcher target for entry '/admin/network/wireless/radio0.network2'.
This called action terminated with an exception:
/usr/lib/lua/luci/i18n.lua:42: bad argument #1 to 'format' (integer expected, got nil)
stack traceback:
[C]: in function 'assert'
/usr/lib/lua/luci/dispatcher.lua:449: in function 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

Everything(luci+openwrt) git from today. Platform ar71xx.

**Comment by jow-** [comment]
Should be fixed with 718466ea762d2fa166c6f32a80e915086216be84 .
