### ISSUE TITLE
Unable to connect clients when WPA3 is enable

### ISSUE THREAD

**Issue by Adgbeta** [openwrt/luci#6242]
OpenWrt SNAPSHOT r22036-1a145ccb0a / LuCI Master git-23.039.28596-41e9b8d
***

## Steps to reproduce:

1. go to: Network → wireless → edit Marvell 88W8864 802.11ac/n → Encryption → Change to sae-mixed
2. Save & Apply
3. Clients can not connect 
4. Change setting back to only WPA2

If changed to only WPA3 unable to save and apply, Marvell 88W8864 802.11ac/n stop working.

**Comment by hnyman** [comment]
Not really related to the LuCI GUI, but to the core wireless drivers.

The Marvell mwlwifi drivers are known to have problems with wpa3 (and mixed wpa2/wpa3) mode. The OEM stopped the closed-source driver/firmware development several years ago, so there is no hope about fixing that. Several bug reports in the mwlwifi opensource part's repository, plus forum discussion.

You need to use wpa2.
