### ISSUE TITLE
DNS Cache size default in UCI not updated in LUCI  default placeholder

### ISSUE THREAD

**Issue by edrikk** [openwrt/luci#6254]
@hnyman and @Ansuel updated the UCI default for DNS Cache to 1000 in [this commit](https://github.com/openwrt/openwrt/commit/a57796b137494fc20e984d0049e8e7430e9ebb25) , however the Luci DHCP page has to have its [default placeholder](https://github.com/openwrt/luci/blob/d0d10630547db7b6049a0bab9fb96c08b962913d/modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js#L558)  updated as a trivial change.

**Comment by hnyman** [comment]
I am travelling the next week, but can change it when I am back
