### ISSUE TITLE
luci-app-firewall's missing string on Weblate

### ISSUE THREAD

**Issue by Matthaiks** [openwrt/luci#6258]
This duplicated string (introduced by https://github.com/openwrt/luci/commit/c54efde71718f6a05b7832f5092e7a7da83d22eb ) is not present on Weblate:

1
![1](https://user-images.githubusercontent.com/3577122/220609463-61a9c769-8ed1-4dd6-95c0-64c864cb682d.png)
2
![2](https://user-images.githubusercontent.com/3577122/220609466-76f0f280-8ed4-4615-b9c5-d018ce66a41d.png)

**Comment by hnyman** [comment]
Fixed by 1b623cbe60
