### ISSUE TITLE
luci-base: Don’t allow unsupported SSH keys to be added

### ISSUE THREAD

**Issue by xrisk** [openwrt/luci#6263]
## Steps to reproduce:

1.  Go to System > Administration > SSH-Keys
2. Add a ECDSA key.

## Actual behavior:

The key is added successfully.

## Expected behavior:

luci should refuse to add the key as it is unsupported by openwrt’s default dropbear configuration https://github.com/openwrt/openwrt/issues/7984#issuecomment-1436273890 

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.0'
DISTRIB_REVISION='r19685-512e76967f'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 22.03.0 r19685-512e76967f'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
LuCI is not aware what kind of keys are supported by the underlying SSH server implementation. Due to that I decided to rather allow unsupported keys instead of restricting key types which might be supported in a later version.
