### ISSUE TITLE
/usr/lib/lua/luci/dispatcher.lua:474,

### ISSUE THREAD

**Issue by babyjeck** [openwrt/luci#6272]
/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute firstchild dispatcher target for entry '/admin'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute function dispatcher target for entry '/admin/status'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute template dispatcher target for entry '/admin/status/overview'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:74: Failed to load template 'admin_status/index'.
Error while parsing template '/usr/lib/lua/luci/view/admin_status/index.htm':
I/O error
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>

**Comment by jow-** [comment]
Broken filesystem / dying flash / Kernel bug. Not fixable here.
