### ISSUE TITLE
luci-proto-wireguard: Use 'lookup_host' instead of 'domain' from DDNS

### ISSUE THREAD

**Issue by Wolfie713** [openwrt/luci#6289]
When using DDNS/Cloudflare, the domain entry has to be in the form of "sub@domain.tld," which is an invalid FQDN and as such highlights the "Connection endpoint" in red until you select something else.  Using 'lookup_host' would work better since that has to be a valid FQDN.

In order to test the issue:
1. Set up a proper/working Cloudflare DDNS service.  Instructions will include setting the "Domain" field to be in a "sub@domain.tld" format.
2. Go to Network/Interface.
3. Edit the Wireguard interface.
4. Select peers tab and choose a peer to edit.
5. Scroll down and click to generate a QR code.
6. The "Connection endpoint" will be red with the invalid entry from the Cloudflare DDNS profile.

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.3'
```

**Comment by jow-** [comment]
Is `lookup_host` a valid choice for all providers?
