### ISSUE TITLE
Channel Analysis doesn't work for 5GHz radio on Archer A7

### ISSUE THREAD

**Issue by RafcioRS** [openwrt/luci#6290]
I'm running OpenWRT (OpenWrt 22.03.3 r20028-43d71ad93e / LuCI openwrt-22.03 branch git-22.361.69894-438c598) on Tp-Link Archer A7 V5 hardware in "dumb" AP mode. I've found a couple of bugs and here is a description of the first of them.

The Channel Analysis in the GUI for radio0 (5GHz) shows only the local interface (the radio channel from the router) and nothing else. There is no issue at all for radio1 (2.4GHz). Lots of SSIDs are shown there. Obviously the issue is visible in the GUI, but most likely is the issue with some underlying module serving the 5GHz radio.

I'm not sure what else I can add here. If there is any helpful logging that needs to be enabled and the logs attached, I'm willing to do that. Just need a little guidance.

**Comment by jow-** [comment]
Make sure you're not sitting on a DFS channel.

**Comment by RafcioRS** [comment]
Well, it is a DFS channel (#100). Does that mean that channel analysis cannot be performed? Or will that take a very long time? I've waited probably 15 minutes and there was no change.

**Comment by castillofrancodamian** [comment]
I have noticed that it is not possible to scan if there is an interface in the same radio and channel in "auto".

**Comment by jow-** [comment]
Active scanning is not allowed on DFS channels, therefore it is impossible to gather survey results.

**Comment by RafcioRS** [comment]
Wait a moment. You're LISTENING for the radios, not sending anything. How come wouldn't that be allowed? Also, I have InSSIDer on my laptop and it picks up all the radios, including DFS frequencies. If it wasn't possible or allowed, they wouldn't be able to do that. Again, you're NOT transmitting anything, only listening. Perhaps you don't have the proper process implemented.

**Comment by jow-** [comment]
I believe the radio/hostapd will not tune into other frequencies to passively listen when being active on a DFS channel. In any case this is not a LuCI specific problem, it merely reuses the OpenWrt scanning infrastructure.

**Comment by RafcioRS** [comment]
Well, if it needs to send some "ping" request, then it could do that on ALL channels EXCEPT DFS ones, if that action is prohibited. At least certain channels would be covered by the discovery. I still believe that the implementation as it is now, is wrong. After all, DFS channels are allowed to be used under certain conditions. In my location other channels are so crowded that DFS ones are the only viable option. This is the main reason why I use third party and not factory firmware, as that one doesn't allow using DFS channels at all. They are simply missing from the selectable channel list.
I guess I need to open this ticket under different subsystem then. What subsystem would that be?
