### ISSUE TITLE
OpenWRT Pass web

### ISSUE THREAD

**Issue by Ayperoz** [openwrt/luci#6292]
Hello everyone, I have a question.
My situation is as follows: I have a MikroTik RouterBOARD 951Ui-2HnD that has OpenWRT installed.
Since I forgot the password, please do a factory reset. My lan gave it an ip (192.168.1.38) and when accessing through the web interface it asks me for a username and password.
The user that completes by default is root, but the password cannot be blank and no matter what I type, it tells me the wrong password and at the bottom of the web page it tells me.
Powered by LuCI openwrt-18.06 branch (git-19.020.41695-6f6641d) / OpenWrt 18.06.2 r7676-cddd7b4c77

OpenWRT has a default password?

![image](https://user-images.githubusercontent.com/87099533/225170747-802d0cbe-046e-4218-a1dc-e4b44c841240.png)

**Comment by hnyman** [comment]
The normal  default password is empty.
As your router also defaults to a non-default IP (192.168.1.38) in reset, it is quite likely that you have a personal firmware that has non-standard  defaults. You better ask the author of the firmware.

Other option might be OpenWrt failsafe mode. Read wiki.

Luci has no separate password.
