### ISSUE TITLE
fs.exec() can't run scripts with '&'

### ISSUE THREAD

**Issue by darwin787** [openwrt/luci#6293]
My old lua luci app runs very good and simple, but when I migrate it to current new app, I can't run scripts with '&' any more, because lua use io.popen() and now must use fs.exec().

with this shcript test.sh:
```
#!/bin/sh
echo hello & 
```
and this luci app code:
```
    handleCommand: function(exec, args) {
		return fs.exec(exec, args).then(function(res) {
			var out = document.querySelector('textarea');

			dom.content(out, [ res.stdout || '', res.stderr || '' ]);
		}).catch(function(err) {
			ui.addNotification(null, E('p', [ err ]))
		})
	},
    myhandle: function(ev, cmd) {
			return this.handleCommand('/root/test.sh',null);
	},
```
It will not return and finally display xhr request time out error. 
It's almost same even change test script to:
```
#!/bin/bash
echo hello &  disown

```

**Comment by jow-** [comment]
The `rpcd` service enforces a strict runtime limit for invoked programs and will kill them if they do not finish in time. Try `nohup` to untangle your subcommand from the process spawned by `rpcd`. If this does not work, you might need to look into `start-stop-daemon` to run your script as background process unaffected by the initiating shell lifetime.

**Comment by remittor** [comment]
Probably related issues:
https://github.com/openwrt/rpcd/issues/26
