### ISSUE TITLE
luci-app-dockerman; overview page error

### ISSUE THREAD

**Issue by Gost6** [openwrt/luci#6300]
Hello,

I have noticed an error on the luci-app-dockerman/overview page, this happen with latest docker bump to 23.0.1.

![docker-overview](https://user-images.githubusercontent.com/83871163/226472319-736a1d93-7d2e-44fb-bfc6-f5e5b1009374.png)

DISTRIB_ID="OpenWrt'
DISTRIB_RELEASE='master'
DISTRIB_REVISION='r22325-00b40ef00d'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
```

**Comment by vbzc** [comment]
same issues

**Comment by kimboslice99** [comment]
Did this fix not make it into the 23.05.3 release? Still an issue in 23.05.3

**Comment by realJustinLee** [comment]
Still existing in 2023.05.3

**Comment by systemcrash** [comment]
Paste a copy of the trace-back text here. Look very closely to see whether they match. This fix is in 23.

**Comment by kimboslice99** [comment]
It is slightly different, here's the full trace... should I open a new issue for this?

```
/usr/lib/lua/luci/ucodebridge.lua:23: ...sr/lib/lua/luci/model/cbi/dockerman/newcontainer.lua:311: attempt to concatenate a nil value

In error(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function [arrow function] (/usr/share/ucode/luci/dispatcher.uc:794:4)
  called from function render ([C])
  called from function render_action (/usr/share/ucode/luci/dispatcher.uc:768:24)
  called from function run_action (/usr/share/ucode/luci/dispatcher.uc:795:4)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:1003:48)
  called from anonymous function (/www/cgi-bin/luci:39:13)

 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^
```

**Comment by systemcrash** [comment]
> It is slightly different, here's the full trace... should I open a new issue for this?

This not being the same issue, yes.

Include your dockerman config, and what you tried to do.
