### ISSUE TITLE
BUG.The page at 'admin/istorex_api/update/' has no parent node so the access to this location has been denied.

### ISSUE THREAD

**Issue by qkmc-rk** [openwrt/luci#6324]
/usr/lib/lua/luci/dispatcher.lua:353: Access Violation
The page at 'admin/istorex_api/update/' has no parent node so the access to this location has been denied.
This is a software bug, please report this message at https://github.com/openwrt/luci/issues
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:353: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>
when install istorex, find this, 
![image](https://user-images.githubusercontent.com/18748765/229015861-4618e206-5027-4434-b695-ce34c2e2e072.png)

**Comment by jow-** [comment]
This path does not belong to any extension maintained by us, please contact the supplier of your firmware build.
