### ISSUE TITLE
`luci-app-opkg:`Software Tab is missing after restoring from the backup

### ISSUE THREAD

**Issue by serdarcloud** [openwrt/luci#6330]
Hi, I have restored OpenWRT from one of the backups taken and I have also faced similar issue where the software tab is missing. 
I have run the below command and it give the below error. opkg update is working without any issue.
`root@OpenWrt:~# opkg install luci-app-opkg`
`Installing luci-app-opkg (git-22.273.29004-9f6876b) to root...`
`Downloading https://downloads.openwrt.org/releases/22.03.2/packages/mips_24kc/luci/luci-app-opkg_git-22.273.29004-9f6876b_all.ipk`
`Collected errors:`
 `* opkg_download: Failed to download https://downloads.openwrt.org/releases/22.03.2/packages/mips_24kc/luci/luci-app-opkg_git-22.273.29004-9f6876b_all.ipk, wget returned 8.`
 `* opkg_install_pkg: Failed to download luci-app-opkg. Perhaps you need to run 'opkg update'?`
` * opkg_install_cmd: Cannot install package luci-app-opkg.`
Kindly asaking for help if anyone knows the reason of the issue.
Thanks

**Comment by serdarcloud** [comment]
One additional note: 
When I try to browse https://downloads.openwrt.org/releases/22.03.2/packages/mips_24kc/luci/luci-app-opkg_git-22.273.29004-9f6876b_all.ipk , it give 404 page. After checking the https://downloads.openwrt.org/releases/22.03.2/packages/mips_24kc/luci folder, I have verified that there is no file such as "luci-app-opkg" in the list.

**Comment by hnyman** [comment]
you need to update your packahe lists wuith "opkg update".
The package has been just rebuilt in the last buildbot build round...

https://downloads.openwrt.org/releases/22.03.2/packages/mips_24kc/luc
It is there now:
https://downloads.openwrt.org/releases/22.03.2/packages/mips_24kc/luci/luci-app-opkg_git-23.093.42303-e16f620_all.ipk


luci-app-opkg_git-23.093.42303-e16f620_all.ipk | 9.8 KB | Tue Apr  4 21:47:25 2023

**Comment by serdarcloud** [comment]
Thank you very much @hnyman for your quick reply. After following your instructions, I was able to download the package and now software tab is showing on the interface. As I am new to OpenWRT, should I do the restore again from the backup or could be that only this package was missing during the restore?

**Comment by hnyman** [comment]
>  should I do the restore again from the backup 

Restoring from backup only restores your settings. 
It has no relation to packages being installed or not.
