### ISSUE TITLE
[Feature] Can you try to synchronize the Lean's luci source

### ISSUE THREAD

**Issue by 8MiYile** [openwrt/luci#6334]
https://github.com/coolsnowwolf/luci/tree/master/applications
Can you try to synchronize some of the plugins in this, I hope to say that the content is similar on both sides

**Comment by 8MiYile** [comment]
and pls add this plugin `luci-app-openclash`
https://github.com/vernesong/OpenClash/tree/master/luci-app-openclash

**Comment by hnyman** [comment]
Feel free to create PRs for importing stuff from there, or better yet, ask the authors themselves to create PRs here.

**Comment by 8MiYile** [comment]
wait
if luci app is lua language
Can it be pushed to pr?
