### ISSUE TITLE
luci-app-babeld: Bug/Feature request: Make interface readable

### ISSUE THREAD

**Issue by marek22k** [openwrt/luci#6337]
## Steps to reproduce:

1. go to: Status → Babeld tab
2. look at the status

## Actual behavior:
A very ugly site. I think the whole thing is supposed to be a table, but it is not.

## Expected behavior:
Something clear - for example, a table.

## Additional Information:

I use the Luci Design OpenWrt2020. I have attached pictures.

OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.3'
DISTRIB_REVISION='r20028-43d71ad93e'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 22.03.3 r20028-43d71ad93e'
DISTRIB_TAINTS=''
```

![You can see a page on which headings are placed one below the other. Below are the values, but one heading/value per line. Nothing is formatted.](https://user-images.githubusercontent.com/46723399/231291925-09de9216-0f7a-4ed0-845e-0df632506424.png)

Ping on maintainers: @JonnyTischbein @PolynomialDivision @aparcar
(I am sorry if I am pinging you and you are not the maintainers, however there is nothing in the files about this and you are in the commit history).

**Comment by marek22k** [comment]
I think https://github.com/openwrt/luci/blob/master/applications/luci-app-babeld/root/www/luci-static/resources/babeld.js#L38 is supposed to be a table. However, div elements are used for this. Maybe that is the reason for the appearance?

**Comment by marek22k** [comment]
For the Bootstrap and OpenWrt themes, a table actually appears.

**Comment by JonnyTischbein** [comment]
At first it was build using the table tag (see https://github.com/openwrt/luci/pull/3927#issuecomment-615781467 ) but changed to the "common div structure" because table appears to be deprecated.

The theme does not seem to support this: https://github.com/openwrt/luci/blob/openwrt-22.03/themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
Maybe @jow- knows something about it ?

**Comment by marek22k** [comment]
Why is table obsolete? As far as I know, the element still exists in HTML5.
