### ISSUE TITLE
LuCI: Inconsistent wording for DHCP lease infinite

### ISSUE THREAD

**Issue by Rexadev** [openwrt/luci#6344]
1. _Setting lease time to 0 give me 0h 1m 58s_
2. When set `infinite` Active DHCP Leases shows `unlimited`
3. When `unlimited `is used instead of `infinite` in Static Lease it doesn't work.
4. OpenWrt should use consistent words

**Comment by jow-** [comment]
LuCI should emit a validation error if "unlimited" is entered as value.
