### ISSUE TITLE
Different speed of download and upload for the same config in V2ray and router !

### ISSUE THREAD

**Issue by rezajpk** [openwrt/luci#6353]
Hi everyone , 
At the same time and same wifi connection you can see the different speed of download and upload , though the configuration of this server in V2ray application has better speed.

![1](https://user-images.githubusercontent.com/112063413/233076599-81969115-44ca-4b8f-aa56-5648f68dbb16.png)
![2](https://user-images.githubusercontent.com/112063413/233076611-3aada873-c282-4ebf-9a3d-ffc3836d87ac.png)

**Comment by jow-** [comment]
Not a LuCI issue.
