### ISSUE TITLE
Nlbwmon bug in showing values .

### ISSUE THREAD

**Issue by 4k3or3et** [openwrt/luci#6388]
Hi All,

after last update of nlbwmon on OpenWRT, it is showing incorrect values:

![image](https://github.com/openwrt/luci/assets/53837030/e3059d34-2953-44b0-bfba-cdf2502f90db)

What is have managed to figure out it is adding number bytes just before conversion to GiB which makes it unreadable. Previous months looks exactly the same.

I have this bug on both of routers I manage.

Can you Guys check if this is the same case for you?

Is there any fix i could apply to fix this?

**Comment by jow-** [comment]
You need to upgrade the `luci-base` package und clear your browser cache.
