### ISSUE TITLE
AUC: Attended System Upgrade fails on snapshot due to missing packages

### ISSUE THREAD

**Issue by dietcoke73** [openwrt/luci#6403]
## Steps to reproduce:
Belkin RT3200 with the following packages installed from SNAPSHOT
adguardhome - 0.107.25-1
attendedsysupgrade-common - 8
auc - 0.3.2-1
base-files - 1531-r23070-8fc2a0f00f
busybox - 1.36.0-1
ca-bundle - 20211016-1
cgi-io - 2022-08-10-901b0f04-21
curl - 8.0.1-1
ddns-scripts - 2.8.2-37
ddns-scripts-godaddy - 2.8.2-37
ddns-scripts-services - 2.8.2-37
dnsmasq - 2.89-4
dropbear - 2022.82-5
firewall4 - 2023-03-23-04a06bd7-1
fstools - 2023-02-28-bfe882d5-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2022-08-13-4c7b720b-2
glib2 - 2.74.0-4
hostapd-common - 2023-03-29-bb945b98-1.2
ip-full - 6.3.0-1
iperf3 - 3.13-1
iw - 5.19-1
iwinfo - 2023-05-17-c9f5c3f7-1
jansson4 - 2.14-3
jshn - 2022-09-27-ea560134-1
jsonfilter - 2018-02-04-c7e938d6-1
kernel - 5.15.112-1-ed1b49286dd765200d54c76e51b64e13
kmod-cfg80211 - 5.15.112+6.1.24-4
kmod-crypto-acompress - 5.15.112-1
kmod-crypto-aead - 5.15.112-1
kmod-crypto-ccm - 5.15.112-1
kmod-crypto-cmac - 5.15.112-1
kmod-crypto-crc32c - 5.15.112-1
kmod-crypto-ctr - 5.15.112-1
kmod-crypto-gcm - 5.15.112-1
kmod-crypto-gf128 - 5.15.112-1
kmod-crypto-ghash - 5.15.112-1
kmod-crypto-hash - 5.15.112-1
kmod-crypto-hmac - 5.15.112-1
kmod-crypto-kpp - 5.15.112-1
kmod-crypto-lib-chacha20 - 5.15.112-1
kmod-crypto-lib-chacha20poly1305 - 5.15.112-1
kmod-crypto-lib-curve25519 - 5.15.112-1
kmod-crypto-lib-poly1305 - 5.15.112-1
kmod-crypto-manager - 5.15.112-1
kmod-crypto-null - 5.15.112-1
kmod-crypto-rng - 5.15.112-1
kmod-crypto-seqiv - 5.15.112-1
kmod-crypto-sha512 - 5.15.112-1
kmod-gpio-button-hotplug - 5.15.112-3
kmod-hwmon-core - 5.15.112-1
kmod-leds-gpio - 5.15.112-1
kmod-lib-crc-ccitt - 5.15.112-1
kmod-lib-crc32c - 5.15.112-1
kmod-lib-lzo - 5.15.112-1
kmod-mac80211 - 5.15.112+6.1.24-4
kmod-mt76-connac - 5.15.112+2023-05-13-969b7b5e-1
kmod-mt76-core - 5.15.112+2023-05-13-969b7b5e-1
kmod-mt7615-common - 5.15.112+2023-05-13-969b7b5e-1
kmod-mt7615e - 5.15.112+2023-05-13-969b7b5e-1
kmod-mt7622-firmware - 5.15.112+2023-05-13-969b7b5e-1
kmod-mt7915-firmware - 5.15.112+2023-05-13-969b7b5e-1
kmod-mt7915e - 5.15.112+2023-05-13-969b7b5e-1
kmod-nf-conntrack - 5.15.112-1
kmod-nf-conntrack6 - 5.15.112-1
kmod-nf-flow - 5.15.112-1
kmod-nf-log - 5.15.112-1
kmod-nf-log6 - 5.15.112-1
kmod-nf-nat - 5.15.112-1
kmod-nf-reject - 5.15.112-1
kmod-nf-reject6 - 5.15.112-1
kmod-nfnetlink - 5.15.112-1
kmod-nft-core - 5.15.112-1
kmod-nft-fib - 5.15.112-1
kmod-nft-nat - 5.15.112-1
kmod-nft-offload - 5.15.112-1
kmod-nls-base - 5.15.112-1
kmod-ppp - 5.15.112-1
kmod-pppoe - 5.15.112-1
kmod-pppox - 5.15.112-1
kmod-slhc - 5.15.112-1
kmod-thermal - 5.15.112-1
kmod-udptunnel4 - 5.15.112-1
kmod-udptunnel6 - 5.15.112-1
kmod-usb-core - 5.15.112-1
kmod-usb-xhci-hcd - 5.15.112-1
kmod-usb-xhci-mtk - 5.15.112-1
kmod-usb3 - 5.15.112-1
kmod-wireguard - 5.15.112-1
libattr - 2.5.1-1
libblobmsg-json20220927 - 2022-09-27-ea560134-1
libbpf710 - 7.1.0-b01941c8-1
libc - 1.2.4-4
libcap - 2.69-1
libcurl4 - 8.0.1-1
libdbi - 0.9.0-5
libelf1 - 0.189-1
libestr - 0.1.11-3
libfastjson - 0.99.8-1
libffi - 3.4.2-2
libgcc1 - 12.3.0-4
libiperf3 - 3.13-1
libiwinfo-data - 2023-05-17-c9f5c3f7-1
libiwinfo20230121 - 2023-05-17-c9f5c3f7-1
libjson-c5 - 0.16-3
libjson-script20220927 - 2022-09-27-ea560134-1
liblua5.1.5 - 5.1.5-10
liblucihttp-lua - 2023-03-15-9b5b683f-1
liblucihttp-ucode - 2023-03-15-9b5b683f-1
liblucihttp0 - 2023-03-15-9b5b683f-1
libmbedtls12 - 2.28.3-1
libmnl0 - 1.0.5-1
libnftnl11 - 1.2.5-2
libnghttp2-14 - 1.51.0-1
libnl-tiny2023-04-02 - 2023-04-02-11b7c5f0-1
libopenssl3 - 3.0.8-9
libpcre - 8.45-5
libpcre2 - 10.42-1
libpthread - 1.2.4-4
librt - 1.2.4-4
libstdcpp6 - 12.3.0-4
libubox20220927 - 2022-09-27-ea560134-1
libubus-lua - 2022-06-15-9913aa61-1
libubus20220615 - 2022-06-15-9913aa61-1
libuci20130104 - 2023-03-05-04d0c46c-1
libuclient20201210 - 2023-04-13-007d9454-1
libucode20220812 - 2023-04-03-51638672-1
libustream-mbedtls20201210 - 2023-02-25-498f6e26-1
libuuid1 - 2.39-2
libxml2 - 2.11.4-1
lua - 5.1.5-10
luci-app-attendedsysupgrade - git-23.132.65998-fa9fb2f
luci-app-ddns - git-23.118.79453-d9dcf98
luci-app-firewall - git-23.095.34229-148759a5
luci-app-opkg - git-23.009.82915-ec3aac4
luci-app-pbr - 1.1.1-7
luci-base - git-23.118.79121-6fb185f
luci-lib-base - git-22.308.54612-9118452
luci-lib-ip - git-20.250.76529-62505bd
luci-lib-jsonc - git-22.079.54693-45f411b
luci-lib-nixio - git-22.222.71555-88b9088
luci-lua-runtime - git-23.119.80867-2a9c3a3
luci-mod-admin-full - git-19.253.48496-3f93650
luci-mod-network - git-23.118.74544-b2476ba
luci-mod-status - git-23.063.40670-8c7c56f
luci-mod-system - git-23.118.78765-58f7b27
luci-nginx - git-22.299.78081-67e4e43
luci-proto-ipv6 - git-21.148.48881-79947af
luci-proto-ppp - git-21.158.38888-88b9d84
luci-proto-wireguard - git-23.073.81399-59a6f06
luci-theme-bootstrap - git-23.085.34270-d94a728
luci-theme-material - git-23.088.30860-f464199
mtd - 26
netifd - 2023-04-17-7de5440a-1
nftables-json - 1.0.7-1
nginx - 1.24.0-2
nginx-mod-luci - 1.24.0-2
nginx-mod-ubus - 1.24.0-2
nginx-ssl - 1.24.0-2
nginx-ssl-util - 1.6-17
nginx-util - 1.6-17
odhcp6c - 2023-05-12-bcd28363-20
odhcpd-ipv6only - 2023-04-05-40ab806b-1
openwrt-keyring - 2022-03-25-62471e69-2
opkg - 2022-02-24-d038e5b6-2
pbr - 1.1.1-7
ppp - 2.4.9.git-2021-01-04-4
ppp-mod-pppoe - 2.4.9.git-2021-01-04-4
procd - 2023-01-16-190f13a7-1
procd-seccomp - 2023-01-16-190f13a7-1
procd-ujail - 2023-01-16-190f13a7-1
resolveip - 2
rpcd - 2023-03-14-d9788300-1
rpcd-mod-file - 2023-03-14-d9788300-1
rpcd-mod-iwinfo - 2023-03-14-d9788300-1
rpcd-mod-luci - 20230123-1
rpcd-mod-rpcsys - 2023-03-14-d9788300-1
rpcd-mod-rrdns - 20170710
rpcd-mod-ucode - 2023-03-14-d9788300-1
rsyslog - 8.2110.0-1
syslog-ng - 4.2.0-1
ubi-utils - 2.1.5-1
uboot-envtools - 2023.04-1
ubox - 2022-08-13-4c7b720b-2
ubus - 2022-06-15-9913aa61-1
ubusd - 2022-06-15-9913aa61-1
uci - 2023-03-05-04d0c46c-1
uclient-fetch - 2023-04-13-007d9454-1
ucode - 2023-04-03-51638672-1
ucode-mod-fs - 2023-04-03-51638672-1
ucode-mod-html - 1
ucode-mod-lua - 1
ucode-mod-math - 2023-04-03-51638672-1
ucode-mod-ubus - 2023-04-03-51638672-1
ucode-mod-uci - 2023-04-03-51638672-1
urandom-seed - 3
urngd - 2020-01-21-c7f7b6b6-1
usign - 2020-05-23-f1f65026-1
usteer - 2022-08-18-7d2b17c9-1
uwsgi - 2.0.20-2
uwsgi-cgi-plugin - 2.0.20-2
uwsgi-luci-support - 2.0.20-2
uwsgi-syslog-plugin - 2.0.20-2
wireguard-tools - 1.0.20210914-2
wireless-regdb - 2023.05.03-1
wpad - 2023-03-29-bb945b98-1.2
zlib - 1.2.13-1

Attended upgrade failing due to missing packages 

auc/0.3.2-1
Server:    https://sysupgrade.openwrt.org
Running:   SNAPSHOT r23070-8fc2a0f00f on mediatek/mt7622 (linksys,e8450-ubi)
Available: SNAPSHOT r23086-3591353f51
Requesting package lists...
 busybox: 1.36.0-1 -> 1.36.1-1
 base-files: 1531-r23070-8fc2a0f00f -> 1531-r23086-3591353f51
installed package uwsgi-cgi-plugin cannot be found in remote list!
 curl: 8.0.1-1 -> 8.1.0-1
installed package uwsgi-luci-support cannot be found in remote list!
 libbpf: 7.1.0-b01941c8-1 -> 1.2.0-1
installed package uwsgi-syslog-plugin cannot be found in remote list!
 libcurl: 8.0.1-1 -> 8.1.0-1
installed package uwsgi cannot be found in remote list!

## Actual behavior:

```
Image cannot be built
```

## Expected behavior:
```
Upgrade of the packages and firmware should be built and installed.
```

## Additional Information:

**Example: Replace the following lines and remove this**
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r23070-8fc2a0f00f'
DISTRIB_TARGET='mediatek/mt7622'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r23070-8fc2a0f00f'
DISTRIB_TAINTS=''

```

**Comment by hnyman** [comment]
Not related to LuCI GUI.

(And likely you just need to wait until buildbot has again built a coherent set of packages. likely a few hours - 1 day)
