### ISSUE TITLE
luci-app-ddns: 'bind network' list doesn't let choosing `wan6` for IPv6 client

### ISSUE THREAD

**Issue by dmig** [openwrt/luci#6405]
## Steps to reproduce:
1. Go to: Service → DynamicDNS
2. Create new service record for: IPv6-Address, no-ip.com
3. Fill all basic settings, go to Advanced settings
4. Set 'IP address source' to 'URL'
5. Set 'URL to detect' to 'http://checkipv6.dyndns.com'
6. In the 'Bind network' list 2 options are available: `lan` and `wan (wan, wan6)` (my case) -- choose `wan` as it assumes both IPv4 and IPv6
7. Save and run client

## Actual behavior:
Service fails:
```
...
092205  info : Starting main loop at 2023-05-28 09:22
 092206       : Detect local IP on 'web'
 092206 ERROR : Can not detect local IP using 'network_get_ipaddr6 wan' - Error: '1' - TERMINATE
 092206  WARN : PID '4527' exit WITH ERROR '1' at 2023-05-28 09:22
```

## Expected behavior:
Service renews IPv6 successfully

## Workaround:
Set 'Bind network' to `wan6` manually or execute:
```
uci set ddns.myddns_ipv6.bind_network=wan6
```

## Additional Information:
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.3'
DISTRIB_REVISION='r20028-43d71ad93e'
DISTRIB_TARGET='ramips/mt7620'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 22.03.3 r20028-43d71ad93e'
DISTRIB_TAINTS=''
```
```
# opkg info luci-app-ddns
Package: luci-app-ddns
Version: git-23.118.79498-4390b4d
```

**Comment by Deeppjp116** [comment]
Hello Deep,

I'm interested in working on this issue. Could you please provide more details about the problem? Additionally, I would like to know how I can set up this repository on my computer.

Thank you!
