### ISSUE TITLE
luci-proto-wireguard: "Error getting PublicKey"

### ISSUE THREAD

**Issue by M95D** [openwrt/luci#6410]
## Steps to reproduce:
Create or edit a Wireguard interface in Luci / Network / Interfaces.
Insert a public and a private key.
Save and close the page.
Enter Luci / Network / Interfaces again and Edit the WG interface.

## Actual behavior:
Instead of the public key, the text input contains an error message: "Error getting PublicKey"

## Expected behavior:
Show the public key.

## Additional Information:
SNAPSHOT r23001
mvebu/cortexa9
Linksys WRT1900AC v1

Thank you.

**Comment by jow-** [comment]
Cannot reproduce on todays snapshot. 

https://github.com/openwrt/luci/assets/2528802/6cd96a65-0870-4470-875d-2eb2ef1d510e
