### ISSUE TITLE
mwan3 双wan口负载均衡，从外网访问高跃点的wan口udp数据没有原路返回，udp数据流向了低跃点wan口导致丢包。

### ISSUE THREAD

**Issue by dongc123** [openwrt/luci#6433]
![微信图片编辑_20230617084846](https://github.com/openwrt/luci/assets/109882914/5dec2197-a410-4705-baef-175fc8121458)
固件版本OpenWrt 23.05.0-rc1 平台x86/64 内核版本5.15.114 mwan3把wan1和wan2做了负载均衡，wan1 ip:175.0.82.xxx 跃点30 wan2 ip:175.0.80.xxx 跃点20 当upd数据包从wan1进入后，从wan2流出没有原路返回，上图是wan1和wan2抓包。

**Comment by feckert** [comment]
Sorry I don't speak Chinese
