### ISSUE TITLE
luci-app-ddns - Parse error on install

### ISSUE THREAD

**Issue by tdandrade** [openwrt/luci#6436]
I'm installing the luci-app-ddns and having this error:

```
root@OpenWrt:~# opkg install luci-app-ddns
Installing luci-app-ddns (git-23.118.79498-4390b4d) to root...
Downloading https://downloads.openwrt.org/releases/22.03.5/packages/mipsel_24kc/luci/luci-app-ddns_git-23.118.79498-4390b4d_all.ipk
Configuring luci-app-ddns.
uci: Parse error (invalid command) at line 17, byte 8
root@OpenWrt:~#
```
The menu appear on the UI, but it throws an RPC error when clicked and never loads.

OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.5'
DISTRIB_REVISION='r20134-5f15225c1e'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 22.03.5 r20134-5f15225c1e'
DISTRIB_TAINTS=''
```

**Comment by hnyman** [comment]
And what are the exact contents of your /etc/config/ddns ?

> Configuring luci-app-ddns.
> uci: Parse error (invalid command) at line 17, byte 8

One of your config files in /etc/config is faulty.
It might be ddns, but it mihgt also be ucitrack, I think.

You could test with "uci show ddns" and also "uci show XXX" for each config file, to find out which config file is problematic.

**Comment by tdandrade** [comment]
Indeed. Thanks @hnyman!
The "uci show ddns" came with the same error.
I truncated the config after the global block and it worked.
I'll try investigating as I'm not sure there was any config file there before, so could it be a vanilla one, coming with the package?
Thanks again for the quick response!

**Comment by hnyman** [comment]
> could it be a vanilla one, coming with the package?

No. The vanilla config file has not change for several years.

Line 17 seems to be password, so I guess that your config was wrong.
` 17         option password         "your_password"`
 
Closing this.
