### ISSUE TITLE
not allowed to add second wireguard device in interfaces

### ISSUE THREAD

**Issue by latumus** [openwrt/luci#6444]
luci-app-wireguard or whichever part of it controls the interfaces option wireguard VPN

adding a second wireguard interface fails
## Steps to reproduce:
1. go to: Network → Interfaces → add new interface → wireguard vpn

## Actual behavior:
if you try to add a second wireguard interface it says the interface name is already used.
name being Wireguard VPN not the field i can fill out

## Expected behavior:
just accept a second device for me to configure 

OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.0-rc1'
DISTRIB_REVISION='r23069-e2701e0f33'
DISTRIB_TARGET='mediatek/filogic'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 23.05.0-rc1 r23069-e2701e0f33'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
Unable to reproduce:

https://github.com/openwrt/luci/assets/2528802/1f20f0cf-e70b-4c0c-bff3-2e286fe86cc4
