### ISSUE TITLE
Switch missing

### ISSUE THREAD

**Issue by jameskimmel** [openwrt/luci#646]
I just freshly installed luci, but the switching section under network ist missing. 
Thanks for any help.
OpenWrt Chaos Calmer 15.05
LuCi git-15.276.51144-8832d53
Linksys WRT1900ACS
Let me know if you need further information. I'm totally new to OpenWrt/LuCI/Linux in general. 

![930d9b4e-d0cc-11e5-906e-931a441cb3e7](https://cloud.githubusercontent.com/assets/17176225/13202612/024eca24-d8a1-11e5-879a-202ee93ae87a.png)

**Comment by jow-** [comment]
Try the following on the console:

    uci add network switch
    uci set network.@switch[-1].name=switch0
    uci set network.@switch[-1].reset=1
    uci set network.@switch[-1].enable_vlan=1
    uci add network switch_vlan
    uci set network.@switch_vlan[-1].device=switch0
    uci set network.@switch_vlan[-1].vlan=1
    uci set network.@switch_vlan[-1].ports="0 1 2 3 4 5"
    uci commit network
    reboot

**Comment by jameskimmel** [comment]
Thank you for your response. I will try that at the weekend. At the moment I already switched back to the original firmware.

**Comment by cshoredaniel** [comment]
No additional comment for 10 months, closing.
