### ISSUE TITLE
Cannot find dependency kmod-ipt-fullconenat or kmod-nft-fullconenat ... with Raspberry Pi 3B+ and OpenWrt 22.03.5

### ISSUE THREAD

**Issue by 505188714** [openwrt/luci#6469]
Hardware:
Raspberry Pi 3 Model B Rev 1.2
ARMv8 Processor rev 4

Firmware:
OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.093.57104-ce20b4a

Command & Errors:

root@OpenWrt:~# opkg upgrade luci
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-ipt-fullconenat for iptables-mod-fullconenat
 * pkg_hash_check_unresolved: cannot find dependency kmod-ipt-fullconenat for ip6tables-mod-fullconenat
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-fullcone for firewall4

root@OpenWrt:~# opkg install luci --force-depends
Package luci (git-23.093.42303-d58cd69) installed in root is up to date.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-ipt-fullconenat for iptables-mod-fullconenat
 * pkg_hash_check_unresolved: cannot find dependency kmod-ipt-fullconenat for ip6tables-mod-fullconenat
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-fullcone for firewall4

**Comment by jow-** [comment]
These packages are not part of the official OpenWrt repository.
