### ISSUE TITLE
Mismatched string in luci-app-uhttpd

### ISSUE THREAD

**Issue by Matthaiks** [openwrt/luci#6481]
Certain string has been modified by https://github.com/openwrt/luci/commit/4d841f2744f55ba78127f1ba19c7cbba0f4c6301, but in PO files it is `msgid "Bind to specific interface:port (by specifying interface address"` (without the closing bracket), so its msgstr strings don't work.

**Comment by hnyman** [comment]
Yeah, #6473 was merged without taking care of the .po files via sed (or just manual edit for those languages that actually do have a translation for that string).

**Comment by feckert** [comment]
Sorry missed it.
Fixed with commit https://github.com/openwrt/luci/commit/faf3e1df3647844d562ddeb13927f78235960676
