### ISSUE TITLE
Luci-mod-status : port status doesn't display all eth ports (x86/64)

### ISSUE THREAD

**Issue by badulesia** [openwrt/luci#6494]
## Steps to reproduce:
Use an x86/64 mini PC with 4 eth ports
go to: Status → Overview → Port status

## Actual behavior:
Only eth0 and eth1 are displayed.

## Expected behavior:
4 eth ports should be displayed (eth0 to eth3)

## Additional Information:

Brand : Qotom
Model | INTEL Corporation Q3XXG4-P
Architecture | Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
Target Platform | x86/64
Firmware Version | OpenWrt SNAPSHOT r23659-e6b72de703 / LuCI Master git-23.158.78004-23a246e
Kernel Version | 5.15.123

Luci-mod-status  | git-23.210.72211-00a941e

NICs are Intel I211 gigabit network

**Comment by jow-** [comment]
Known issue, it only enumerates ports in /etc/board.json, add them there and they will appear.

**Comment by badulesia** [comment]
Understood.
So I assume that /etc/board.json is fed by default with only eth0 and eth1, the strict minimum for a router to operate.

**Comment by badulesia** [comment]
Understood.
So I assume that /etc/board.json is fed by default with only eth0 and eth1, the strict minimum for a router to operate.

**Comment by badulesia** [comment]
I manage to add extra eth ports to /etc/board.json

```
"network": {
		"lan": {
			"ports": ["eth0", "eth1", "eth2"],
			"protocol": "static"
		},
		"wan": {
			"device": "eth3",
			"protocol": "dhcp"
		}
	}
```
