### ISSUE TITLE
[luci-app-openvpn] (incl. fix)  app fails to parse PID if one instance name is equal to others beginning

### ISSUE THREAD

**Issue by x-logLT** [openwrt/luci#650]
if one instance name is equal to others beginning (ie VPN and VPN2) OpenVPN app crashes with error 
`A runtime error occured: /usr/lib/lua/luci/model/cbi/openvpn.lua:87: bad argument #1 to 'signal' (integer expected, got string)`

**Fix:**
Force grep to match whole world only: in file /usr/lib/lua/luci/model/cbi/openvpn.lua change lines
`sys.exec("%s | grep %s | grep openvpn | grep -v grep | awk '{print $1}'" % { psstring,section} )`
to 
`sys.exec("%s | grep -w %s | grep openvpn | grep -v grep | awk '{print $1}'" % { psstring,section} )`

**Comment by Wedmer** [comment]
I think it should be closed as suggested fixes were merged.
