### ISSUE TITLE
luci-base: http.uc: The limit for uploading 100k files is too small！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/luci#6510]
https://github.com/openwrt/luci/blob/master/modules/luci-base/ucode/http.uc#L17

The limit for uploading 100k files is too small，Files exceeding 100k cannot be uploaded under http!  Can you change it to not controlling the size of uploaded files?

**Comment by jow-** [comment]
The entire HTTP message body is held in RAM, hence the limit. Multi-megabyte uploads could easily trigger OOM conditions on the router. Use the cgi-upload applet to implement upload of large payload into temporary files. See the `ui.uploadFile()` implementation for an example on how to use it:

https://openwrt.github.io/luci/jsapi/ui.js.html#line4166
