### ISSUE TITLE
luci-app-openvpn: only route the data from specify port

### ISSUE THREAD

**Issue by ivanchang1988** [openwrt/luci#6516]
I am currently setting up a configuration where I have an SSR server configured in OpenWrt using SSR Plus. For incoming connections, the devices receive the server's IP address. However, I'm trying to make it so that specific SSR traffic on a designated port is then relayed through an OpenVPN connection, acquiring a different IP address.

When I enable the OpenVPN connection, external connections are immediately unable to access the internet. Only devices connected through a cable are able to acquire a different IP address through OpenVPN.

I want to set up my system to forward traffic on a specific port used by SSR to connect to the server through OpenVPN, while the rest of the traffic remains unaffected. How can I set up OpenVPN to forward traffic only on a specific port, while leaving the rest of the connections untouched?

Please note: I've already tried some common solutions involving iptables and routing rules, but so far I haven't been able to get it working. Any assistance in setting up this specific configuration would be greatly appreciated. Thank you!

**Comment by feckert** [comment]
This is more a generic issue/question/problem with openvpn and not with luci-app-openvpn.
Please describe your problem in the  [openwrt forum](https://forum.openwrt.org).
