### ISSUE TITLE
Excuse me, what does this mean?

### ISSUE THREAD

**Issue by boobb** [openwrt/luci#6523]
There are two unsaved configurations in my openwort, but I don't know what they mean, so I started to play. Sorry to interrupt.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

passwall.cfg388b02=subscribe_list
passwall.cfg388b02.enabled=0

**Comment by boobb** [comment]
I don't know if I need to save it or apply it. 
I'm really sorry to bother you.Because I don't know what to do.
I hope you can guide me. Thank you!

**Comment by hnyman** [comment]
Not related to LuCI GUI. 
Not a bug.

**Comment by boobb** [comment]
thanks
