### ISSUE TITLE
luci-mod-status: cannot correctly display port status [23.05]

### ISSUE THREAD

**Issue by missing233** [openwrt/luci#6541]
I checked board.json. If a specific port is set individually, it will work correctly.
{
        "model": {
                "id": "gowin-solution-r86s",
                "name": "GoWin Solution R86S"
        },
        "network": {
                "lan": {
                        "device": "eth0",
                        "protocol": "static"
                },
                "wan": {
                        "device": "eth3",
                        "protocol": "dhcp"
                }
        }
}
![20230825223455](https://github.com/openwrt/luci/assets/18642603/d1e7b6aa-e0d7-45e7-8f23-a8b8ba7e3f12)
However, if all ports are written into board.json, then no port can be displayed.
{
        "model": {
                "id": "gowin-solution-r86s",
                "name": "GoWin Solution R86S"
        },
        "network": {
                "lan": {
                        "device": ["eth0", "eth1", "eth2", "eth4"],
                        "protocol": "static"
                },
                "wan": {
                        "device": "eth3",
                        "protocol": "dhcp"
                }
        }
}
![20230825223410](https://github.com/openwrt/luci/assets/18642603/dc0dd13e-1b31-466d-8f9e-9a4c8b0632d8)

eth0-2 is Intel I226-V
eth3-4 is Mellanox ConnectX-3 CX341A

**Comment by openwrtdiy** [comment]
**try the following**

		"lan": {
			"ports": ["eth0", "eth1", "eth2", "eth4"],
			"protocol": "static"
		},
		"wan": {
			"ports": ["eth3"],
			"protocol": "dhcp"
		}
