### ISSUE TITLE
luci-app-openvpn: Dependency on `openvpn` missing in 23.05.0-rc3.

### ISSUE THREAD

**Issue by dreirund** [openwrt/luci#6564]
In OpenWRT 23.05.0-rc3, the package `luci-app-openvpn` misses dependencies on `openvpn`:

Installing just `luci-app-openvpn` gives a Luci-interface for OpenVPN, but fails to actually start it because openvpn is missing.

**Comment by jow-** [comment]
Duplicate of #5949
