### ISSUE TITLE
Luci client splash not working in offline

### ISSUE THREAD

**Issue by hi3520** [openwrt/luci#657]
In luci client splash worked perfect in online it shows the splash page and redirect to predefined url .But in offline no splash page will appear and no redirect occurred. 
My project is just redirect every wifi user to a localhost eg:http://192.168.1.1**/welcome.html

**Comment by FreifunkUFO** [comment]
that splash redirects http traffic to the splash page.
when you are offline, there will be no http traffic because dns-resolution will fail before any http traffic can start
so, how can we install/configure a dns faker?

**Comment by cshoredaniel** [comment]
For clarification, is this for 'luci-app-splash' ?

**Comment by LipkeGu** [comment]
@cshoredaniel: yes it is

**Comment by LipkeGu** [comment]
@hi3520 What du you mean with offine?

**Comment by FreifunkUFO** [comment]
such an offline dns could go like this:

echo "address=/#/192.168.1.1" > /tmp/dnsmasq.d/spoof2.conf; /etc/init.d/dnsmasq restart

thanks to http://serverfault.com/questions/351108/using-dnsmasq-to-resolve-all-hosts-to-the-same-address

**Comment by cshoredaniel** [comment]
@hi3520 @LipkeGu Does @FreifunkUFO's solution work for you?

**Comment by feckert** [comment]
Very old and I think the solution works because no reaction from issue creator
