### ISSUE TITLE
Adblock - Translation Error for English

### ISSUE THREAD

**Issue by AndrinoLabGit** [openwrt/luci#6573]
I installed "luci-i18n-adblock-en | git-23.222.62173-d7922c4".  It reports "Aktiva källor" instead of "Active Sources".  

![image](https://github.com/openwrt/luci/assets/70484150/7309081f-7a2a-4f40-a259-8031ef3c811a)

The file luci-app-adblock/po/en/adblock.po has that Swedish phrase in it.
https://github.com/openwrt/luci/blob/de65ace24ac574625885640cb7b93fbcbedc3c7c/applications/luci-app-adblock/po/en/adblock.po#L16C1-L21C1

**Comment by hnyman** [comment]
Thanks. I removed the wrong translation in weblate.
The fix will get included at the next translation merge.
