### ISSUE TITLE
The inbound traffic statistics of the LAN interface are incorrect.

### ISSUE THREAD

**Issue by dongc123** [openwrt/luci#6576]
**The inbound traffic statistics of the LAN interface are incorrect.**
![微信截图_20230915160331](https://github.com/openwrt/luci/assets/109882914/6fa736e2-1eb5-4de2-a5b7-7c2d6a5f99d9)

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.0-rc3'
DISTRIB_REVISION='r23389-5deed175a5'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 23.05.0-rc3 r23389-5deed175a5'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
Not a LuCI issue, we merely report what the kernel is reporting.
