### ISSUE TITLE
[nlbwmon] no data recorded yet

### ISSUE THREAD

**Issue by Code-TT** [openwrt/luci#6578]
I need a tool to see which device is producing how much traffic, so I installed luci-app-nlbwmon (Version: git-23.208.37305-01d26bf) on my Xiaomi AX3600 (Firmware: [https://openwrt.admincomps.ru/nss/20230907/](https://openwrt.admincomps.ru/nss/20230907/openwrt-qualcommax-ipq807x-xiaomi_ax3600-squashfs-sysupgrade.bin).

It never shows data, only "No data recorded yet."

In Systemlog I found: 

```
Tue Sep 19 15:49:18 2023 daemon.err nlbwmon[13551]: The netlink receive buffer size of 524288 bytes will be capped to 212992 bytes
Tue Sep 19 15:49:18 2023 daemon.err nlbwmon[13551]: by the kernel. The net.core.rmem_max sysctl limit needs to be raised to
Tue Sep 19 15:49:18 2023 daemon.err nlbwmon[13551]: at least 524288 in order to sucessfully set the desired receive buffer size!

```

So I did: 

```
sysctl -w net.core.rmem_max=524288
sysctl -w net.core.rmem_default=524288
```

And restarted nlbwmon. No new entries in Syslog. But still no data.

In Local Interfaces I've lan, wan, wan6. 
Local subnets I've tried the standart Entries and 192.168.21.0/24 alone, both didn't work. 

![netlink1](https://github.com/openwrt/luci/assets/37022171/61c4ffdb-01a4-4f58-bb8e-5a4e18223c0b)
![netlink2](https://github.com/openwrt/luci/assets/37022171/89af97f3-fb55-4f9c-9af5-88905aeabb38)

My first ideal was, it could be a problem with the installed firmware with nss. But now I remember, that I already tried the last snapshot before and didn't get data with nklbwmon too.
So any idea what could cause this problem and how to fix it?

**Comment by jow-** [comment]
Remove wan and wan6 form your local interfaces. Nlbwmon only counts traffic from local to non.local interfaces and vice versa. If all interfaces are considered "local", no traffic will be counted.
