### ISSUE TITLE
LuCi Backfire is not getting out of router

### ISSUE THREAD

**Issue by vish951111** [openwrt/luci#658]
I have a Linksys WRT 160N v1, with openwrt backfire 14.07. I upgraded from dd-wrt, but now I want to restore it back to dd-wrt. But when I use the GUI to upgrade, it shows me bad gateway error in Mozilla. Can anyone help me as soon as possible

**Comment by jow-** [comment]
You'll find more help in the general OpenWrt forums: https://forum.openwrt.org/
If the DD-Wrt image is not accepted or timing out you likely need to reflash using mtd on the command line.
