### ISSUE TITLE
luci-proto-wireguard: Peer "Generate configuration" incorrectly formats IPv6 Endpoint

### ISSUE THREAD

**Issue by Kasoo** [openwrt/luci#6592]
## Steps to reproduce:

1. Go to Interfaces » vpn » Edit peer » Generate configuration
2. Select IPv6 address on "Connection endpoint"
3. Note generated config uses incorrect form of `Endpoint = fc00::1:51820` instead of `Endpoint = [fc00::1]:51820`
4. Attempt to scan generated QR code using Wireguard app and receive an "Invalid configuration" error.

## Additional Information:
`luci-proto-wireguard` version: `git-23.073.81399-59a6f06`

**Comment by jow-** [comment]
Fixed by #6593
