### ISSUE TITLE
luci-app-ntpc - broken working and visible error when " 'option freq' '0' " to /etc/config/ntpclient

### ISSUE THREAD

**Issue by build000** [openwrt/luci#660]
...as the topic.

**Comment by cshoredaniel** [comment]
Probably ntpc is used very often since sysntpd takes care of what most folks would want.  Most likely if others confirm ntpc is not working in general (rather than specific options) it will get marked BROKEN.

**Comment by build000** [comment]
ok - there is one simple solution, which previously simply did not notice - just enough there do not enter anything - then you can save changes to the luci without error - the question of whether this is the right way to configure NtpClient and whether it actually work? I would add that I use jesj only the bottom of any configuration and correct functionality dnscrypt-proxy.

**Comment by cshoredaniel** [comment]
Seems like you've solved your problem, and it's more of a help issue for the forum or IRC.  Certainly obscure and needs more eyes than the issue tracker.
