### ISSUE TITLE
luci: not updating /var/run/config.md5

### ISSUE THREAD

**Issue by mmohtashamirad** [openwrt/luci#6601]
I'm not sure if this is a bug or it's designed like that, but, after luci saves the uci configs and sends calls the "ubus system event" so the services do the reload step, /var/run/config.md5 will not be updated with the new md5sum of the configs. 
There are two scenarios that you can see issues:
1- Make some changes through UI and hit save. Services will reload. Then go to command line and do "reload_config". The services will reload again. 

2-Make some changes through UI and hit save. Services will reload. Then change the same settings (using UCI command line)  to the values that they had before you change them in the UI and issue reload_config. Now it wouldn't actually call cause services to reload. 

we are using OpenWrt 22.03.5

**Comment by jow-** [comment]
Not a LuCI issue. `/var/run/config.md5` is a private implementation detail of `/sbin/reload_config`
