### ISSUE TITLE
Router is bricked after manual reset

### ISSUE THREAD

**Issue by ArcticCloud** [openwrt/luci#662]
TEW-823dru Trendnet Router  Firmware OpenWrtFW_TEW-823DRU_v1(bb1_23_2-r76177).zip
OpenWrt Chaos Calmer 15.05

Setup and installed the router correctly and it was working for days. I accidently bricked pressing the WPS button for 10 seconds to add a printer and from there on the router is unaccessible. WiFi is visible but unconnectible. Connection to ports 0-3 with Ethernet cable I can ping 192.168.1.1 successfully. In failsafe mode, this IP no longer responds to ping. Telnet does not connect in either mode. WAN connection to through a switch to a router, it pulls an IP from the router but nothing works yet.
** I thought the WPS button might have been also working as the reset button if held down for 10 seconds, but I was wrong. Don't really know what it did. But I visited the user manual for the router and found the real reset button hidden underneath. I never thought to check there. After performing a factory reset, I could access the modem thru Ethernet cable. Right as rain now. Turned on WiFi and set the passwords back up.

**Comment by jow-** [comment]
You'll find general help regarding OpenWrt in the forums at http://forum.openwrt.org/, also read up on the failsafe mechanism.
