### ISSUE TITLE
index can not open

### ISSUE THREAD

**Issue by rongdada12** [openwrt/luci#6624]
![6929a9693fe86cd9947b3593af5c2d9](https://github.com/openwrt/luci/assets/130554607/50ea334e-4432-4062-9cd7-1acad2a02105)

**Comment by jow-** [comment]
This file is not part of the standard LuCI distribution. The error indicates a filesystem corruption or invalid bytecode in the `store.lua` file.

**Comment by rongdada12** [comment]
thank you
