### ISSUE TITLE
everything breaks, everytime

### ISSUE THREAD

**Issue by wp-coin** [openwrt/luci#6630]
why when I change my lan interface to 192.168.2.1 causes openwrt to be unreachable?

every time I make a change in the network interfaces my router (Linksys EA6350v3) becomes unreachable and I have to reset each time, there needs to be a better way

the whole interface is broken, sometimes the changes work, other times it just breaks and my router becomes unreachable

somehow the settings does not save or gets saved in the wrong place, I have to upload the sysupgrade.bin file to wipe out any of the the old settings

 the whole router stops working and I need to do a hard reset to get back tot he login screen

I am sure there is a bug that needs to be fixed

**Comment by raenye** [comment]
There's no information here that can help someone debug your problem, sorry.
Your config files, software versions, whatnot.

Also, luci has a rollback feature -- if the webpage cannot be loaded after 90 seconds, the changes are reverted. So you almost never need reflashing.
