### ISSUE TITLE
PO files for luci-app-https-dns-proxy and luci-app-adblock-fast are outdated

### ISSUE THREAD

**Issue by Matthaiks** [openwrt/luci#6676]
Issue https://github.com/openwrt/luci/issues/6020 is back. `luci-app-https-dns-proxy` (https://github.com/openwrt/luci/commit/dea2f135d7c915d46940e95a49891b945037be29) and `luci-app-adblock-fast` (https://github.com/openwrt/luci/commit/a0574a3ad1c7831705d979ad09b8dcc94bbd4184) have up-to-date POT files but not PO files.

**Comment by jow-** [comment]
We're resynving translations every second week or so, not immediately with each package change.
