### ISSUE TITLE
lib-luci-ip: on big endian systems, cidr:add swaps byte order 

### ISSUE THREAD

**Issue by pony1k** [openwrt/luci#6678]
## Steps to reproduce:
On a big endian system, run
```
lua - <<EOF
ip = require("luci.ip")
addr6 = ip.new("fd43::")        
print(addr6:add(1))
EOF
```

## Actual behavior:
It prints `fd43::100:0`.

## Expected behavior:
Should print `fd43::1`.

## Additional Information:
This happens with both luci-lib-ip version `git-20.146.54255-39d5f2e-1` (very old) and `git-20.250.76529-62505bd` (quite recent). This is how one can check if system is little or big endian:
```
echo -n I | hexdump -o | awk '{ print substr($2,6,1); exit}'
```
It prints 0 for big endian.
Not sure if there is interest in fixing this, given that it is not included any longer in OpenWrt standard installation.

**Comment by jow-** [comment]
Thanks for the report. If updating the library is no option, you can workaround the issue by specifying the add argument as address string instead (which also circumvents the 32bit limit of a numeric operand).

```lua
addr6 = ip.new("fd43::")        
print(addr6:add("::1"))
```
