### ISSUE TITLE
BUG:The Chinese interface servers of 23.05 do not display Chinese.

### ISSUE THREAD

**Issue by Tonkercke** [openwrt/luci#6691]
After the system was updated to openwrt23.05.0 and the system language was switched to Chinese, the servers option did not change and was still in English.

I tried a full reset of the openwrt system settings, but the problem persists.

![luci](https://github.com/openwrt/luci/assets/67683757/e62d4130-d070-4aac-8cb8-6339ee06587c)

**Comment by systemcrash** [comment]
You're welcome to contribute a translation if one does not yet exist today. 
https://hosted.weblate.org/projects/openwrt/luci/zh_Hant/
https://hosted.weblate.org/projects/openwrt/luci/zh_Hans/

**Comment by yurtpage** [comment]
The Sevices menu item is translated for many years: 
https://github.com/openwrt/luci/blob/master/modules/luci-base/po/zh_Hans/base.po#L8294
https://github.com/openwrt/luci/blob/master/modules/luci-base/po/zh_Hant/base.po#L8303

@Tonkercke Please confirm that you still have the problem

**Comment by jow-** [comment]
This should work fine. What is odd about the OP is the lowercase spelling of the "services" menu, the original english menu title is capitalized. Maybe some unofficial 3rd party packaged added this untranslated menu entry.
