### ISSUE TITLE
luci-theme-bootstrap: 32px favicon

### ISSUE THREAD

**Issue by 532910** [openwrt/luci#6716]
Please add bigger favicon for HiDPI screens. I believe 32px will be enough. Right now only 16x16 px is exists and it looks very blurry:
https://github.com/openwrt/luci/blob/master/themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/favicon.png

**Comment by 532910** [comment]
https://github.com/openwrt/luci/pull/6717

**Comment by systemcrash** [comment]
Pixels? Blech! Vector graphixx 😄

**Comment by 532910** [comment]
no safari support: https://caniuse.com/link-icon-svg
