### ISSUE TITLE
dhcpv6.js The three options for requesting ipv6 have not been translated.

### ISSUE THREAD

**Issue by try496** [openwrt/luci#6730]
o = s.taboption('general', form.ListValue, 'reqaddress', _('Request IPv6-address'));
		o.value('try');
		o.value('force');
		o.value('none', 'disabled');
		o.default = 'try';
There are no translation options for these three options on the website. Is there any other reason?

**Comment by systemcrash** [comment]
Would you like to make a PR to remedy this?

**Comment by try496** [comment]
@systemcrash I created a commit. If it's not correct, please ask the developers to fix these translation options.
