### ISSUE TITLE
luci-app-ddns : retry_count does not function anymore

### ISSUE THREAD

**Issue by yurtesen** [openwrt/luci#6752]
Maintainer: Rafał Miłecki <rafal@milecki.pl>
Environment: OpenWRT master

Description:

The DDNS scripts were updated but not relevant LUCI scripts and WIKI https://openwrt.org/docs/guide-user/base-system/ddns

Because this commit:
https://github.com/openwrt/packages/commit/e3292e4c9766e823ed38160390248dbc61f69c82
requires usage of `retry_max_count` in place of `retry_count`

Also DDNS scripts end up in infinite loop if nslookup fails. But that is a different issue:
https://github.com/openwrt/packages/issues/22829

**Comment by systemcrash** [comment]
Fixed in d349181
Wiki also
