### ISSUE TITLE
luci-app-diag-core: wrong filename in translation template

### ISSUE THREAD

**Issue by urbalazs** [openwrt/luci#6753]
Each file uses hyphen in filename except `luci/applications/luci-app-diag-core/po/templates/diag_core.pot` which uses underscore. It should also use hyphen like: `diag-core.pot`

Since the filename pattern is different, I guess that this is the reason why the translation template and the translations are not updated since 4 years and this component is missing in [Weblate](https://hosted.weblate.org/projects/openwrt/).

**Comment by systemcrash** [comment]
@hnyman ?

I don't think that's the case: the html contains no translatable strings. So they're probably not presented as 'translatable' material in weblate. 

Are there any apps that use this component?
