### ISSUE TITLE
There are a simple metodh for add two icon with two link to all page ?

### ISSUE THREAD

**Issue by gioreva** [openwrt/luci#6766]
In the old versions there was an html file where it was easy to add two icons with links, and they appeared on all pages. 
Now there is still an html file but it seems to be ignored. 
Is there a method to do this?

Compiling a new theme is very difficult for me. I am using material in OpenWRT 23.05.2

**Comment by jow-** [comment]
Modify `/usr/share/ucode/luci/template/themes/material/header.ut` - a restart of the `uhttpd` service might be needed if `uhttpd-mod-ucode` is in use.
