### ISSUE TITLE
[help] How to create a new view in luci

### ISSUE THREAD

**Issue by Dzejnieks** [openwrt/luci#6776]
Hi everyone,
I want to create a rather simple UI for passing parameters to bash scripts and executing them. I cannot find any instructions (or by looking at the code) on how to implement a new view in luci. In previous versions there were views and controllers. 
Any guidance on where to start would be much appreciated 🙏

**Comment by stokito** [comment]
Check the example app:
https://github.com/openwrt/luci/tree/master/applications/luci-app-example

Also wiki https://github.com/openwrt/luci/wiki

Same info as in wiki but may be outdated https://github.com/openwrt/luci/tree/master/docs
