### ISSUE TITLE
【23.05】A large amount of untranslated content appears in the dhcp list

### ISSUE THREAD

**Issue by try496** [openwrt/luci#6781]
After comparison testing, it was found that changes in the untranslated text have been found in the main branch. After the latest synchronized translation of the file on 23.05, the relevant text was not updated. The translation file could not find the new text, so the old untranslated text was displayed.

**Comment by try496** [comment]
![屏幕截图 2023-12-23 114816](https://github.com/openwrt/luci/assets/66765024/9fe5d7dd-f39c-41ec-b7be-aae1d5be1ba7)
![屏幕截图 2023-12-24 114952](https://github.com/openwrt/luci/assets/66765024/d64faf9e-03b3-41b7-8318-7629f2bffa52)

**Comment by try496** [comment]
After testing, it was found that some of the previous synchronizations were gone after this synchronization. Some of them existed in the translation file but were not applied.

**Comment by try496** [comment]
After comparing the synchronized files, I found that some directories in the translation files no longer exist after this synchronization. Some are in the translation files but have not been applied.

**Comment by try496** [comment]
![屏幕截图 2023-12-23 13353](https://github.com/openwrt/luci/assets/66765024/201feb4e-ba3d-4970-87ea-213c785a7d5e)
![屏幕截图 2023-12-24 11492](https://github.com/openwrt/luci/assets/66765024/0d5a5162-8e0f-40a0-80eb-e537cddbebd7)
![屏幕截图 2023-12-24 114952](https://github.com/openwrt/luci/assets/66765024/fee39e9b-785e-4802-a24a-71b4bea2a831)

**Comment by try496** [comment]
![屏幕截图 2023-12-24 11492](https://github.com/openwrt/luci/assets/66765024/c00100bb-98d1-42cc-9d64-f9932a0d71ec)

**Comment by try496** [comment]
![屏幕截图 2023-12-24 114952](https://github.com/openwrt/luci/assets/66765024/41284a68-9a19-4a12-a49a-090ae888151f)

**Comment by try496** [comment]
![屏幕截图 2023-12-23 1353](https://github.com/openwrt/luci/assets/66765024/fbe7c6b9-80c7-4e0a-b371-721accfa388b)

**Comment by hnyman** [comment]
Well, like I answered to you in discussion at https://github.com/openwrt/luci/pull/6775#issuecomment-1867651826 , all translations are made by volunteers like you and me.

New strings are not automatically translated, but require manual work. So, it may take a while after changes until you (or somebody else) does the translation and the new strings translations get merged (first into main/master). And then later they get backported into stable 23.05 every few weeks.

There has recently been lots of small string tweaking and string inclusion style changes by @systemcrash , so it is quite possible that there is more than normal amount of untranslated strings.

I just backported all current translations to 23.05, so hopefully at least some of the missing strings now appear also there.
But not all. 
E.g. that string `"Dump cache on SIGUSR1, include requesting IP."` that you are showing as example, is still untranslated in main/master:

https://hosted.weblate.org/translate/openwrt/luci/zh_Hans/?checksum=09746f26e807153a
https://hosted.weblate.org/translate/openwrt/luci/zh_Hant/?checksum=09746f26e807153a
![image](https://github.com/openwrt/luci/assets/7926856/9ced0ca5-c41c-494d-b1bf-aa6e9b7d4c89)

and is then naturally also untranslated in 23.05:

```
+#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js:326
+msgid "Dump cache on SIGUSR1, include requesting IP."
+msgstr ""
```

The strings really need an actual translation by somebody before they can automagically appear on the end-user screen.

**Comment by try496** [comment]
Because the later parts have been abandoned in the main branch, I rolled back to the December 16 version and all translations are normal. Based on the latest main branch, all translations are also normal.---Original---From: "Hannu ***@***.***>Date: Sat, Dec 23, 2023 15:31 PMTo: ***@***.***>;Cc: ***@***.***>***@***.***>;Subject: Re: [openwrt/luci] 【23.05】A large amount of untranslated content appears in the dhcp list (Issue #6781)
Well, like I answered to you in discussion at #6775 (comment) , all translations are made by volunteers like you and me.
New strings are not automatically translated, but require manual work. So, it may take a while after changes until you (or somebody else) does the translation and the new strings translations get merged (first into main/master). And then later they get backported into stable 23.05 every few weeks.
There has recently been lots of small string tweaking and string inclusion style changes by @systemcrash , so it is quite possible that there is more than normal amount of untranslated strings.
I just backported all current translations to 23.05, so hopefully at least some of the missing strings now appear also there.
But not all.
E.g. that string "Dump cache on SIGUSR1, include requesting IP." that you are showing as example, is still untranslated in main/master:
https://hosted.weblate.org/translate/openwrt/luci/zh_Hans/?checksum=09746f26e807153a
https://hosted.weblate.org/translate/openwrt/luci/zh_Hant/?checksum=09746f26e807153a
image.png (view on web)
and is then naturally also untranslated in 23.05:
+#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js:326
+msgid "Dump cache on SIGUSR1, include requesting IP."
+msgstr ""

The strings really need an actual translation by somebody before they can automagically appear on the end-user screen.

**Comment by try496** [comment]
The reason may be that the developer changed the text about translation in dhcp.js, but it was not changed in 22.05, resulting in translation errors after synchronization.

**Comment by try496** [comment]
After simultaneous translation today, I found some letter strings on the translation website, but there are still some letter strings that were not found. Since 23.05 may take quite a long time to be translated, I have rolled back to the officially released version.

**Comment by try496** [comment]
> 好吧，就像我在[#6775（评论）](https://github.com/openwrt/luci/pull/6775#issuecomment-1867651826)的讨论中回答你一样，所有的翻译都是由像你我这样的志愿者完成的。
> 
> 新字符串不会自动翻译，但需要手动操作。因此，更改后可能需要一段时间，直到您（或其他人）进行翻译并且新的字符串翻译被合并（首先合并到 main/master 中）。然后他们每隔几周就会被重新移植到稳定的 23.05。
> 
> 最近有很多小的字符串调整和字符串包含样式更改，因此很可能有超过正常数量的未翻译字符串。
> 
> 我刚刚将所有当前翻译向后移植到 23.05，所以希望至少一些缺失的字符串现在也出现在那里。但不是全部。例如，您作为示例显示的字符串在 main/master 中仍未翻译：`"Dump cache on SIGUSR1, include requesting IP."`
> 
> https://hosted.weblate.org/translate/openwrt/luci/zh_Hans/?checksum=09746f26e807153a https://hosted.weblate.org/translate/openwrt/luci/zh_Hant/?checksum=09746f26e807153a ![image](https://private-user-images.githubusercontent.com/7926856/292614278-9ced0ca5-c41c-494d-b1bf-aa6e9b7d4c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjM2NTAsIm5iZiI6MTcwMzMyMzM1MCwicGF0aCI6Ii83OTI2ODU2LzI5MjYxNDI3OC05Y2VkMGNhNS1jNDFjLTQ5NGQtYjFiZi1hYTZlOWI3ZDRjODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjNUMDkyMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDU0OWNkNGMxMTU5M2I5NjM3MDJkYTA1MmRhYmI0OGMxNTY5ODY0NTFhNzdlMzQ0NjFlN2I5ZmJiZDc5NTFjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xk-FrdF-ZCxQ6Y74UPFkQ1lU1Xfo__1ODaUQNeDxGuI)
> 
> 然后自然也在 23.05 中未翻译：
> 
> ```
> +#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js:326
> +msgid "Dump cache on SIGUSR1, include requesting IP."
> +msgstr ""
> ```
> 
> 这些字符串确实需要有人进行实际翻译，然后才能自动出现在最终用户屏幕上。



> 好吧，就像我在[#6775（评论）](https://github.com/openwrt/luci/pull/6775#issuecomment-1867651826)的讨论中回答你一样，所有的翻译都是由像你我这样的志愿者完成的。
> 
> 新字符串不会自动翻译，但需要手动操作。因此，更改后可能需要一段时间，直到您（或其他人）进行翻译并且新的字符串翻译被合并（首先合并到 main/master 中）。然后他们每隔几周就会被重新移植到稳定的 23.05。
> 
> 最近有很多小的字符串调整和字符串包含样式更改，因此很可能有超过正常数量的未翻译字符串。
> 
> 我刚刚将所有当前翻译向后移植到 23.05，所以希望至少一些缺失的字符串现在也出现在那里。但不是全部。例如，您作为示例显示的字符串在 main/master 中仍未翻译：`"Dump cache on SIGUSR1, include requesting IP."`
> 
> https://hosted.weblate.org/translate/openwrt/luci/zh_Hans/?checksum=09746f26e807153a https://hosted.weblate.org/translate/openwrt/luci/zh_Hant/?checksum=09746f26e807153a ![image](https://private-user-images.githubusercontent.com/7926856/292614278-9ced0ca5-c41c-494d-b1bf-aa6e9b7d4c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjM2NTAsIm5iZiI6MTcwMzMyMzM1MCwicGF0aCI6Ii83OTI2ODU2LzI5MjYxNDI3OC05Y2VkMGNhNS1jNDFjLTQ5NGQtYjFiZi1hYTZlOWI3ZDRjODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjNUMDkyMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDU0OWNkNGMxMTU5M2I5NjM3MDJkYTA1MmRhYmI0OGMxNTY5ODY0NTFhNzdlMzQ0NjFlN2I5ZmJiZDc5NTFjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xk-FrdF-ZCxQ6Y74UPFkQ1lU1Xfo__1ODaUQNeDxGuI)
> 
> 然后自然也在 23.05 中未翻译：
> 
> ```
> +#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js:326
> +msgid "Dump cache on SIGUSR1, include requesting IP."
> +msgstr ""
> ```
> 
> 这些字符串确实需要有人进行实际翻译，然后才能自动出现在最终用户屏幕上。

I saw on the forum that you said that the stable version is based on the secondary development of the main branch. I saw that the stable branch has a lot of untranslated content. I thought there was an error. I solved some based on the latest compilation, but there are still about 10 texts that have not been translated. 23.05 may take quite some time to synchronize. I have switched back to the main branch to use. I just checked the translation website and saw that there are a lot of new content updates.
