### ISSUE TITLE
How to have a night LED mode (timer) for router's led to turn off and on all leds at particular times daily on openwrt firmware?

### ISSUE THREAD

**Issue by blue-pine** [openwrt/luci#6786]
I tried myself and also searched everywhere for setting night led mode feature for OpenWrt firmware but all effort went to no avail for such a simple feature. This feature is already avilable on the stock firmware of my wifi router TP-Link Archer C6 AC1200 v3.2 which is itself based on OpenWrt and for which I have provide all related files from my research here in my repository : https://github.com/blue-pine/openwrt-tplink_archer_c6_v3.2 . Still I have failed to join the led_night_mode library (from stock router firmware) to the OpenWrt firmware for use on the router. So, I ask for everyone's help whatever they can provide for getting this last and only feature lacking on all OpenWrt firmwares. If you need any help then please ask me, you are always welcome.
Thank you

**Comment by systemcrash** [comment]
All components are there, LED config, and cron.

**Comment by blue-pine** [comment]
> All components are there, LED config, and cron.

Thank you, but I am a beginner and dont know how to go forward, so how can I integrate this timer with openwrt ?

**Comment by brada4** [comment]
Forums have more help.
https://github.com/openwrt/openwrt/issues/14279
As a beginner you can quickly test what someone else derives from wifischedule, like cron scripts. Or switch off all leds. Or use electricians tape to hide blinking.

**Comment by blue-pine** [comment]
> Forums have more help. [openwrt/openwrt#14279](https://github.com/openwrt/openwrt/issues/14279) As a beginner you can quickly test what someone else derives from wifischedule, like cron scripts. Or switch off all leds. Or use electricians tape to hide blinking.

Happy new year and thank you for your help. Will explore and check for more help
