### ISSUE TITLE
local time is incorrect

### ISSUE THREAD

**Issue by hiepvq** [openwrt/luci#6787]
i set timezone to Asia/Ho Chi Minh but it always incorrect 1 hour compared to current time of my pc
![image](https://github.com/openwrt/luci/assets/36187674/44c7db6a-562e-4150-a1d8-438b9efaf088)

## Additional Information:
OpenWrt version information 

[Powered by LuCI Master (git-23.346.45702-3e8eb4a)](https://github.com/openwrt/luci) / [ArgonTheme v1.8.3](https://github.com/jerrykuku/luci-theme-argon) / OpenWrt Li [2023] v7.5 Compiled

**Comment by systemcrash** [comment]
Does the timezones file or package need updating, I wonder.

What does your `/etc/TZ` contain?

**Comment by hiepvq** [comment]
switch to other timezone then switch to my timezone, it display is ok but if reboot router, it will get back is incorrect. that time is chinese

![image](https://github.com/openwrt/luci/assets/36187674/389912fc-40ac-4890-8e95-f62a83fff04d)

**Comment by hiepvq** [comment]
vi /etc/config/system
![image](https://github.com/openwrt/luci/assets/36187674/24bdc301-e47c-42ba-b6e8-566f00289e5f)

**Comment by systemcrash** [comment]
Not that file....

**Comment by hiepvq** [comment]
I think config is still works. it only display incorrect local time in System -> system
it still display correct here. my time UTC+7
![image](https://github.com/openwrt/luci/assets/36187674/9c5e8fc6-9298-43f2-8fcf-5a34e57c726a)

**Comment by hiepvq** [comment]
> Not that file....

it is empty, there is no this file

**Comment by brada4** [comment]
/etc/TZ should be a symlink to /tmp/TZ, which hsould be something along lines of `+7`
`date` vs `date -u` should confirm it.
You are using a fork "compiled by li" , probably you should choose between asking li and using real OpenWRT, absent TZ file kind of says Li removed it.

**Comment by hiepvq** [comment]
> /etc/TZ should be a symlink to /tmp/TZ, which contains something along lines of `+7`
> `date` vs `date -u` to confirm it.
> You are using a fork "compiled by li" , probably you should choose between asking li and using real OpenWRT, absent TZ file kind of says Li removed it.

Ok Thank, so i will close this issue
