### ISSUE TITLE
luci-app-https-dns-proxy: AhaDNS editing filters does not work

### ISSUE THREAD

**Issue by arichiardi** [openwrt/luci#6811]
## Steps to reproduce:

1. go to: Services → HTTPS DNS Proxy → Add
2. Select AhaDNS Blitz Provider
3. Save, Save & Apply
4. Click on Edit the newly added AhaDNS Blitz entry
5. Insert Filters "1:1.23" - for instance
6. Save, Save & Apply

## Actual behavior:
Luci does not display the saved filters and `cat /etc/config/https-dns-proxy` does not show the filters under the AhaDNS entry.

## Expected behavior:
To persist (and use) the filters.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.2'
DISTRIB_REVISION='r23630-842932a63d'
DISTRIB_TARGET='mediatek/filogic'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 23.05.2 r23630-842932a63d'
DISTRIB_TAINTS=''
```

**Comment by stangri** [comment]
I can't reproduce, works as expected for me, including proper config file and luci app displaying the filters as well.

```
xg-135r3 in ~ # cat /etc/config/https-dns-proxy

config main 'config'
	option canary_domains_icloud '1'
	option canary_domains_mozilla '1'
	option dnsmasq_config_update '*'
	option force_dns '1'
	list force_dns_port '53'
	list force_dns_port '853'
	option procd_trigger_wan6 '0'
	option update_dnsmasq_config '*'

config https-dns-proxy
	option bootstrap_dns '149.112.121.10,149.112.122.10,2620:10A:80BB::10,2620:10A:80BC::10'
	option resolver_url 'https://private.canadianshield.cira.ca/dns-query'

config https-dns-proxy
	option bootstrap_dns '1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001'
	option resolver_url 'https://cloudflare-dns.com/dns-query'

config https-dns-proxy
	option resolver_url 'https://blitz.ahadns.com/1:1.23'
```

![image](https://github.com/openwrt/luci/assets/4768176/721d9804-adb5-4c30-9912-fa52862b0378)

**Comment by arichiardi** [comment]
Oh that's odd, are you inserting "1:1.23" in the UI and hit Save?
Maybe we are using differenti versions (I will send you mine in a sec).

**Comment by arichiardi** [comment]
Using `luci-app-https-dns-proxy 2023-10-25-5 11.36 KiB`

**Comment by arichiardi** [comment]
![Uploading recording_2024-01-06_153104.gif…](Screen recording)

**Comment by arichiardi** [comment]
![Uploading recording_2024-01-06_153104.gif…](Screen capture)

**Comment by stangri** [comment]
>  The thing that does not work here is when I do not add it initially, then I Edit and modify it later.

I can reproduce that, I'll have a look at it next time I have the time. For now, delete the instance and create it with the params you want.

**Comment by stangri** [comment]
I've figured out what's causing it, may take me a while to come up with the fix.

**Comment by stangri** [comment]
Thanks for the report, the updated/fixed IPK can be downloaded from my own repository and I'll merge the fixes into openwrt/luci tomorrow.
