### ISSUE TITLE
luci-app-mwan3:May I ask about the method of filling in IPv6 when dealing with dynamic IPv6 prefixes?

### ISSUE THREAD

**Issue by bcseputetto** [openwrt/luci#6813]
![image](https://github.com/openwrt/luci/assets/29139573/1dd827ac-7b99-4b41-888a-be5e1df88f13)

When the IPv6 prefix is dynamic, the IPv6 of the firewall can only fill in the suffix in the format shown in the figure. However, in luci-app-mwan3, neither the source IP nor the destination IP of the rule supports this format. If mwan3 itself supports the format like the firewall, could it be that luci limits this kind of format?

![image](https://github.com/openwrt/luci/assets/29139573/454e4659-d7ed-41ef-b1e9-b58b7538f6b5)

luci-app-mwan3 git-23.093.40772-fa4dc75

**Comment by feckert** [comment]
I only use IPv4, so I can't check whether this works. If you change the IPv6 address in the configuration file `/etc/config/mwan3` does the mwan3 work as expected? If so, then the LuCI is the limiting factor and the datatype should be changed.

**Comment by bcseputetto** [comment]
I need some time to test whether mwan3 works after directly modifying the configuration file. If feasible, I will report back here again.

**Comment by bupahaibao** [comment]
> I only use IPv4, so I can't check whether this works. If you change the IPv6 address in the configuration file `/etc/config/mwan3` does the mwan3 work as expected? If so, then the LuCI is the limiting factor and the datatype should be changed.

This does not take effect ，and may also result in the entire configuration file not taking effect

**Comment by feckert** [comment]
This is probably due to the fact that `iptables` or `nftables` does not support this kind of IPv6 address type. If you have a fix, you are welcome to create a pull request. I will therefore close the issue.
