### ISSUE TITLE
firewall weekdays doesn't work

### ISSUE THREAD

**Issue by dfc-d** [openwrt/luci#691]
Hi Jo, others,

It looks like there is a problem with my implementation of the firewall time-based restrictions.  The UCi correctly contains option weekdays 'wed', but rule doesn't fire.  From re-reading the iptables extensions documentation it appears the issue may be that the weekday has  to have an initial capital letter (e.g. Wed).   

Regards,

Daniel

**Comment by jow-** [comment]
Reading libxt_time.c confirmed that, should be fixed in 75b462f - thanks for the report
