### ISSUE TITLE
[luci-proto-wireguard] "Generate configuration" does not update the QR code and config file according to the values in the form

### ISSUE THREAD

**Issue by floatingpurr** [openwrt/luci#6921]
## Steps to reproduce:
0. Create a new Wireguard Network Interface
1. Create e new peer
2. click on "Generate configuration..." next to the key "Configuration Export"
3. Change the values in the "Generate configuration" tab

## Actual behavior:
The QR code and the config file (printed out next to the QR code) are not updated

## Expected behavior:
The QR code and the config file (printed out next to the QR code) should be updated

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r25142-a42075435a'
DISTRIB_TARGET='mediatek/filogic'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r25142-a42075435a'
DISTRIB_TAINTS=''
```
Package version: `luci-proto-wireguard git-23.338.83313-5b26887`

**Comment by systemcrash** [comment]
Perhaps you can propose a fix?

**Comment by jow-** [comment]
@systemcrash - this broke with your commit 5b26887c52097dc9364c9b4f4dfb2d6ba2f08818

**Comment by systemcrash** [comment]
Snap - I was about to add a different fix. Good catch.
