### ISSUE TITLE
luci-mod-network: page extends infinitely horizontally given an arbitrary amount of devices in an interface in interface list page

### ISSUE THREAD

**Issue by vincejv** [openwrt/luci#6922]
## Steps to reproduce:

1. go to: Network → Interfaces
2. See the interface in desktop mode (desktop ui)

## Actual behavior:

1. Result: Restart, Stop, Edit and etc. buttons hidden from view and have to scroll horizontally when there are too many devices, See screenshot
![image](https://github.com/openwrt/luci/assets/1276544/a533d53c-cfcc-44b9-9b12-48ff746e4369)

## Expected behavior:
Should not extend infinitely horizontally to the point that horizontal scrollbars are needed to press the Restart, Stop, Edit and etc. buttons
If there are too many devices shown spit them with a new line like in the following screenshot
![image](https://github.com/openwrt/luci/assets/1276544/2348e831-8fb3-4294-88bd-6722312c3a74)

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
```
NAME="OpenWrt"
VERSION="23.05.2"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 23.05.2"
VERSION_ID="23.05.2"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r23630-842932a63d"
OPENWRT_BOARD="x86/64"
OPENWRT_ARCH="x86_64"
OPENWRT_TAINTS=""
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 23.05.2 r23630-842932a63d"
```

**Comment by systemcrash** [comment]
Perhaps you can propose a PR - this should not be difficult to implement.

**Comment by dannil** [comment]
I've opened #6926 which should fix this.
