### ISSUE TITLE
Luci Error message when viewing routing status

### ISSUE THREAD

**Issue by sirtobi65** [openwrt/luci#6935]
# Issue template:

## Steps to reproduce:

1. go to: Status → Routing
2. Error message is displayed in Browser (Firefox)

## Actual behavior:

SyntaxError

missing ) after argument list
  in http://192.168.0.1/luci-static/resources/view/status/routes.js?v=git-24.048.61449-c66fc92:18
  at require/compileClass/< (http://192.168.0.1/luci-static/resources/luci.js?v=git-24.048.61449-c66fc92:179:29)

## Expected behavior:

display active routes in browser window

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
ISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.2'
DISTRIB_REVISION='r23630-842932a63d'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 23.05.2 r23630-842932a63d'
DISTRIB_TAINTS=''

**Comment by jow-** [comment]
Already fixed with https://github.com/openwrt/luci/commit/752be18d3b95c114225a88de26223e42c805272d
