### ISSUE TITLE
Luci wont let me set DNS6 static entry in "Use custom DNS servers" string

### ISSUE THREAD

**Issue by Mile-Lile** [openwrt/luci#6939]
## Steps to reproduce:
**Example: Replace the following lines and remove this**

1. go to: Network → Interfaces → **wan6** (an interface with a static ipv6 address) → Advanced settings tab 
2. uncheck "Use DNS servers advertised by peer"
3. under "Use custom DNS servers" enter valid DNS6 adress
4. cannot click on green "+" sign and add DNS6 adress - field is red and complains that enry is not valid

## Expected behavior:
LUCI should let me enter DNS6 and should create line in dnsmasq.conf:
**server=2a07:a8c0::75369c**

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r25279-62acd9a2f9'
DISTRIB_TARGET='bcm53xx/generic'
DISTRIB_ARCH='armv7l'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r25279-62acd9a2f9'
DISTRIB_TAINTS='Netgear R8000 (BCM4709)'
```

![Screenshot-from-2024-02-22-22-59-58.png](https://dodaj.rs/images/Screenshot-from-2024-02-22-22-59-58.png)

**Comment by jow-** [comment]
Works for me:
![grafik](https://github.com/openwrt/luci/assets/2528802/c9919fc0-d41a-4a8f-9654-5a1635d4c874)
However I think you simply have a leading space in there, note the different initial space:
![grafik](https://github.com/openwrt/luci/assets/2528802/3b28102e-2d4f-4ee1-990a-00d07dee744a)

**Comment by Mile-Lile** [comment]
ah... ok thx
