### ISSUE TITLE
"Network -> Wifi" should be "Network -> WiFi"?

### ISSUE THREAD

**Issue by roger-** [openwrt/luci#694]
This has always bugged me and  according to [Wikipedia](https://en.wikipedia.org/wiki/Wi-Fi) WiFi or (better yet) Wi-Fi is the correct spelling.

If this is acceptable, could I just submit a pull request to modify [this](https://github.com/openwrt/luci/blob/master/modules/luci-base/po/en/base.po#L3289) translation string?

**Comment by jow-** [comment]
Yes please, I'd appreciate a PR for that.

**Comment by cshoredaniel** [comment]
Closed via https://github.com/openwrt/luci/commit/cc801de89ca4793638099595d7e61e06a7a5cd66
