### ISSUE TITLE
Feature request - add-cpe-id option to dns section

### ISSUE THREAD

**Issue by Mile-Lile** [openwrt/luci#6940]
I would like to see **add-cpe-id** checkbox option in dns section and input field. Checking this option in luci and adding some value, should add this line in **dnsmasq.conf**:

**add-cpe-id=**$somevalue$

from dnsmasq manpage: "Add an arbitrary identifying string to DNS queries which are forwarded upstream" 

basically this option is usefull when you have paid DNS service and your router sends this ID to your provider, enabling different proxy profiles...

**Comment by systemcrash** [comment]
Did you request in the openwrt repo to add this? A GUI option is useless without the init script providing it.
