### ISSUE TITLE
luci-mod-status: IPv4 Neighbours: Some IF names fail to resolve properly in  "Status → Routing" section

### ISSUE THREAD

**Issue by senca23** [openwrt/luci#6956]
***

## Steps to reproduce:
**Example: Replace the following lines and remove this**

1. Create various VLANs on BR interface.
2. Configure individual seperate networks on those interfaces (/24 /28 /29 etc. randomly). 
3. Save & Apply
4. go to: "Status → Routing" section.

## Actual behavior:
Some interfaces under "IPv4 Neighbours" are represented with their physical interface names ( br.xxx as an example) instead of their "virtual luci" interface names (lets say "lan" or "guests" as an axample).
![Screenshot_2024-03-02_18-35-31](https://github.com/openwrt/luci/assets/142660118/f1c445b5-c5f0-4262-a940-912907ddf536)

## Expected behavior:
As with all other pages, interface names should resolve properly. (interface names are resolved properly in other functions as an example interfaces in "Interfaces tab").
![Screenshot_2024-03-02_18-55-19](https://github.com/openwrt/luci/assets/142660118/d681fbd2-9e88-474c-94db-f0bd2e21d480)

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.2'
DISTRIB_REVISION='r23630-842932a63d'
DISTRIB_TARGET='ipq807x/generic'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 23.05.2 r23630-842932a63d'
DISTRIB_TAINTS=''

```

**Comment by jow-** [comment]
Please provide the complete output of `ubus call network.interface dump`

**Comment by jow-** [comment]
The information in both the screenshot and in the ubus dump are too redacted to work with. Logical interfaces are matched by address, the neighbor entries associated IP address has to be contained within one of the logical interface `ipv4-address`, `ipv6-address`, `ipv6-prefix`, `ipv6-prefix-assignment` or `route` arrays and the `device` or `l3_device` property of the logical interface has to match the device value of the neighbor entry. If no logical interface fulfills this condition, the raw netdev is shown in parens. Maybe there‘s a bug in the matching code but that‘s not possible to tell with the data provided

**Comment by jow-** [comment]
Taking the `(br-lan.66)` example, does the IPv4 address shown in the table fall into the `10.xx.xx.1/30` subnet?

**Comment by jow-** [comment]
So which IPv4 address is shown exactly for the broken br-lan.66 entry? And which IPv4 subnet is configured exactly on "seedbox"? Note that is makes little sense to censor RFC1918 IP addresses

**Comment by jow-** [comment]
Please show a screenshot of the affected table row with the device name in parens and the uncensored IP address, not the cli output.

**Comment by jow-** [comment]
Thanks, will try to reproduce tonight. Needed the screenshot to confirm that it is a gui issue.
