### ISSUE TITLE
luci-app-firewall: DNAT Port forwards display "IPv4 and IPv6" but rule is only IPv4. Please add option for "IPv4 and IPv6" (family option 'any')

### ISSUE THREAD

**Issue by joed74** [openwrt/luci#6958]
## Steps to reproduce and Actual behavior:

Add a DNAT forward rule with "automatic":

![grafik](https://github.com/openwrt/luci/assets/61152521/66a34c6a-6bf6-4524-b374-5368c3be328f)

That's what luci displaying:

![grafik](https://github.com/openwrt/luci/assets/61152521/8312e990-d30d-4964-9370-90c151415c25)

That's what actually is setup in the firewall:

![grafik](https://github.com/openwrt/luci/assets/61152521/f34e3edb-8037-45fd-b791-4f776b2cd3d4)

## Additional behavior

With  `option family 'any'` added manually to /etc/config/firewall i can get the desired behavior (DNAT rule for both IPv4 and IPv6). But now i cannot touch the rule with luci again (e.g. changing other stuff). If i do so, `option family 'any'` disappears..

## Expected behavior:
If a firewall rule is IPv4 only in the firewall then show the user IPv4 and not "IPv4 and IPv6"

## Desired Extension:

Please add a option "IPv4 and IPv6" to the dropdown box:

![grafik](https://github.com/openwrt/luci/assets/61152521/89fde926-c611-45aa-9753-1aa5b96b5d00)

which results in `option family 'any'` in /etc/config/firewall

## Additional Information:

OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256

**Comment by dannil** [comment]
This looks to be already added with https://github.com/openwrt/luci/commit/8169f482fd0bb6d711e571e01e565bcc3165469d, right? Try flashing SNAPSHOT and see if it appears, it isn't backported to the 23.05 branch.

**Comment by systemcrash** [comment]
I think I cherry picked that fix to 23. In any case I don’t see this as a
bug: any does mean that both families are permitted, even if that interface
has only a single family configured. If the router has IPv6 configured
somewhere this will likely happen.

**Comment by joed74** [comment]
@dannil 

I installed this SNAPSHOT package: https://downloads.openwrt.org/snapshots/packages/x86_64/luci/luci-app-firewall_git-24.052.52388-42bd2af_all.ipk

Now there is an option "IPv4 and IPv6" and all is working as expected. Sorry for the report!
