### ISSUE TITLE
luci-mod-network: "Network → Interfaces → DHCP Server → General Setup" = Static leases only function (Dynamic DHCP=0)

### ISSUE THREAD

**Issue by senca23** [openwrt/luci#6960]
## Steps to reproduce:

One might wish to have only static leases delegated via DHCP meaning that automatic IP delegation via the predefined pool should be disabled in dnsmasq and that a static lease for a host/hosts inside that subnet is added. 
Currently no documentation anywhere describes on how to properly achieve that.

## Actual behavior:
To do it properly one must:
- set Dynamic DHCP=0 in (DHCP Server → Advanced settings)
AND
- set dhcp option "limit" to 0 (DHCP Server → General Setup)

Dnsmasq logs confirm that auto delegation from dedicated pool is disabled that way.

## Expected behavior:
Please add a function that forces option "limit=0" - WHEN - "Dynamic DHCP=0" in "DHCP Server → Advanced settings"

![image](https://github.com/openwrt/luci/assets/142660118/86bbbbd1-5558-4c82-ae40-816d3307c007)

## Additional Information:

A lot of users have this seting misconfigured due to confussion. Not critical but should be corrected.

OpenWrt version information from system `/etc/openwrt_release`
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.0-rc4'
DISTRIB_REVISION='r16256-2d5ee43dc6'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 21.02.0-rc4 r16256-2d5ee43dc6'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
Sounds like something that should go into the dnsmasq init script instead. Requiring an additional `limit 0` sounds like a bug to me, nothing that should get papered over in the ui.
