### ISSUE TITLE
Fail to open Luci OpenVPN - luci-app-openvpn

### ISSUE THREAD

**Issue by dafresh90** [openwrt/luci#697]
Hey guys, 
openvpn worked fine for me with 15.05 CC. I've updated to 15.05.1 and now the OpenVPN doesn't work. The config was kept after upgrading but the software for OpenSSL and DDNS needed to be installed again. DDNS seems to be working fine, but the OpenVPN GUI does not work with following message:

```
/usr/lib/lua/luci/dispatcher.lua:433: Failed to execute cbi dispatcher target for entry '/admin/services/openvpn'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:311: Unable to read UCI data: openvpn
stack traceback:
    [C]: in function 'assert'
    /usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>
```

thanks in advance ;)

**Comment by hnyman** [comment]
> The config was kept after upgrading but the software for OpenSSL and DDNS needed to be installed again. DDNS seems to be working fine, but the OpenVPN GUI does not work with following message:

Have you installed the openvpn package itself?
(You mention reinstalling just opsnssl and ddns, but not openvpn)
If not, you probably need openvpn-openssl, as you are apparently using the openssl variant of it.

And yes, you need to reinstall all needed software modules after the firmware upgrade. Sysupgrade only preserves the configs, not the binary programs & libraries.

**Comment by dafresh90** [comment]
Hi hnyman, 
thanks for your quick reply. 
I reinstalled the openvpn-luci-app, openvpn-openssl, easy-rsa and ddns. The configfiles seem to be fine like before. DDNS work like a charm and OpenVPN log reveals "sequence complete" but connection could not be established.

I recovered the backup file for 15.05 and 15.05.1 but still the same error. Seems like the other features work well.

**Comment by Wedmer** [comment]
check read-write permissions

**Comment by Wedmer** [comment]
Looks like http://luci.subsignal.org/trac/ticket/344

**Comment by cshoredaniel** [comment]
No reponse for months, closing
