### ISSUE TITLE
luci-app-dockerman: networks page error

### ISSUE THREAD

**Issue by leobsky** [openwrt/luci#6973]
After docker update from 24.0.7 to 25.0.3  the networks page on luci-app-dockerman get error.
https://github.com/openwrt/packages/pull/23482
## Steps to reproduce:

luci-app-dockerman --> networks

## Actual behavior:

![docker-networks](https://github.com/openwrt/luci/assets/122642374/b0430991-40ac-4e15-9e26-ba315bed2ffd)

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r25409-4adba64156'
DISTRIB_TARGET='bcm27xx/bcm2712'
DISTRIB_ARCH='aarch64_cortex-a76'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r25409-4adba64156'
DISTRIB_TAINTS=''
```

**Comment by Joee-D** [comment]
same problem.
https://github.com/openwrt/luci/blob/72173cce92251aa567b0cbbfa769b944778cd3b7/applications/luci-app-dockerman/luasrc/model/cbi/dockerman/networks.lua#L41
it seems that it uses IPAM config value, but there is no IPAM config, so throw a nil value error.
It should check whether it has the IPAM config first.

**Comment by systemcrash** [comment]
Ah, the good old array assumption breakage.
