### ISSUE TITLE
ping lan devices with static ip not works

### ISSUE THREAD

**Issue by denissanga** [openwrt/luci#6978]
Hi, I have a GLinet M300 V2 and I would ping all devices with static ip too connected to lan.
For example the lan until now is 192.168.8.1 and I connect a static ip device with ip 20.0.0.10. I tried add 0.0.0.0/0 in
->interfaces -> General settings -> IPv4 address -> + -> 0.0.0.0/0

but I cannot ping 20.0.0.10. If I add instead of 0.0.0.0/0 the ip 20.0.0.1 it works. But I would like 0.0.0.0/0 to ping all devices I will connect in the future.
many thanks in advance

**Comment by jow-** [comment]
This is a Linux kernel limitation, `0.0.0.0/0` addresses cannot be configured on interfaces.
