### ISSUE TITLE
luci doesn't follow odhcpd's leasefile option

### ISSUE THREAD

**Issue by gareththered** [openwrt/luci#702]
If I change `odhcpd`'s `leasefile` option to a different file, for example:
```
config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/var-ext/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
```
(in my case, `/var-ext` is non-volatile storage so as to keep DHCP leases in-between reboots)

```odhcpd``` uses the file pointed to by the above configuration, but ```luci``` still monitors the original, hardwired file at `/tmp/hosts/odhcpd`

I believe the culprit is at line 51 of `modules/luci-base/luasrc/tools/status.lua`

`local fd = io.open("/tmp/hosts/odhcpd", "r")`

The equivalent code for `dnsmasq` (from line 13) seems to read the config file for the lease file, whereas `odhcpd` simply assumes it is using the one in `/tmp/hosts`.

**Comment by hnyman** [comment]
This should do the trick:
```
--- /usr/lib/lua/luci/tools/status.lua
+++ /usr/lib/lua/luci/tools/status.lua
@@ -48,7 +48,17 @@
                fd:close()
        end

-       local fd = io.open("/tmp/hosts/odhcpd", "r")
+       local lease6file = "/tmp/hosts/odhcpd"
+
+       uci:foreach("dhcp", "odhcpd",
+               function(t)
+                       if t.leasefile and nfs.access(t.leasefile) then
+                               lease6file = t.leasefile
+                               return false
+                       end
+               end)
+
+       local fd = io.open(lease6file, "r")
        if fd then
                while true do
                        local ln = fd:read("*l")
``` 
That seems to work for me and reads the leases also from a non-standard file.
