### ISSUE TITLE
luci-app-openconnect: currently, does not support URL format server address

### ISSUE THREAD

**Issue by ghost** [openwrt/luci#7021]
Hello:
On openconnect official version client, they are support two server address format: IP and PORT or URL format. 

ref: https://www.infradead.org/openconnect/manual.html
--server=[https://]HOST[:PORT][/PATH]

But at openwrt luci, currently, it only support first type. 
So, it can not established a connection for newer server.

I hope luci can support it in the future.

You can check it follow these steps:
1. install openconnect related package.
2. open web luci, network->interface->add a new interface->create a new openconnect type interface
3. now, you will see currently support status.

I use openwrt 23.05.2.

Thanks.

**Comment by dannil** [comment]
Did you mean `luci-proto-openconnect`? There's no package named `luci-app-openconnect`.

I tested with the following strings:
* https://my-vpn.com:80/my/path
* my-vpn.com:80/my/path
* my-vpn.com/my/path
* my-vpn.com

And they were all valid. Could you provide the URL format you tested with? Maybe you hit an edge case with the URL validation.
