### ISSUE TITLE
luci-nginx: non `-ssl` version still enables SSL?

### ISSUE THREAD

**Issue by ysc3839** [openwrt/luci#7024]
## Steps to reproduce:
1. Using latest snapshot image
2. `opkg install luci-nginx`
3. Open `http://<device-ip>` in browser

## Actual behavior:
Redirected to `https://<device-ip>`, and browser warns invalid certificate

## Expected behavior:
Load `http://` page normally.

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r25659-004eac14ab'
DISTRIB_TARGET='armsr/armv8'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r25659-004eac14ab'
DISTRIB_TAINTS=''
```
```
# opkg depends nginx-mod-luci
nginx-mod-luci depends on:
	libc
	uwsgi
	uwsgi-luci-support
	nginx-ssl
	nginx-mod-ubus
```
`nginx-mod-luci` depends on `nginx-ssl`. Is this an expected behavior?

**Comment by dannil** [comment]
`nginx-mod-luci` is actually part of [openwrt/packages](https://github.com/openwrt/packages/blob/master/net/nginx/Makefile#L182) so I guess you should report the issue there instead? If that's what you're suspecting is configured incorrect.

**Comment by jow-** [comment]
Upstream forcibly enables SSL support in nginx, there's no way to provide non-ssl variants of it anymore.
