### ISSUE TITLE
luci-mod-status: Incomplete Port Status display for BCM57810 with PCI Passthrough on Proxmox VE

### ISSUE THREAD

**Issue by missing233** [openwrt/luci#7035]
## Steps to reproduce:

Pass through the BCM57810 to OpenWrt.
![0](https://github.com/openwrt/luci/assets/18642603/ea84db79-470a-4ae7-b531-727ad24d6eb0)

## Actual behavior:
When using Proxmox VE's PCI passthrough feature to assign a Broadcom BCM57810 which has two SFP+ ports to an OpenWrt virtual machine, the LuCI interface only shows the port status for one interface. The second interface, although operational and recognized by the system, does not appear in the Port Status.
![1](https://github.com/openwrt/luci/assets/18642603/b659ae02-2ec5-4590-a966-35e28e7f1a40)
![2](https://github.com/openwrt/luci/assets/18642603/9896e7c5-455b-493a-8047-7e6cc74364a6)
In the `lspci` command, BCM57810 is output normally.
![3](https://github.com/openwrt/luci/assets/18642603/56c9009d-7ec6-4a43-9c62-35e922feebf1)

## Expected behavior:
LuCI should display all ports.

## Additional Information:
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='OpenWrt 23.05.2'
DISTRIB_REVISION='r23630-842932a63d'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 23.05.2 r23630-842932a63d'
DISTRIB_TAINTS='no-all'
```

**Comment by systemcrash** [comment]
Broadcom is garbage. Try something else.

**Comment by dannil** [comment]
I've never worked with Proxmox, so just a random shot in the dark, but is `eth2` listed under `/sys/class/net`? If it is, does `ls -la /sys/class/net/eth2` resolve to the correct PCI device?

**Comment by missing233** [comment]
> I've never worked with Proxmox, so just a random shot in the dark, but is `eth2` listed under `/sys/class/net`? If it is, does `ls -l /sys/class/net/eth2` resolve to the correct PCI device?

Looks fine?
![20240328040221](https://github.com/openwrt/luci/assets/18642603/8201fa79-19cc-46e3-9dce-2714909371e8)

**Comment by missing233** [comment]
> Broadcom is garbage. Try something else.
> 
> Edit: since broadcom has poor opensource support, you might have to emulate instead.



> Broadcom is garbage. Try something else.
> 
> Edit: since broadcom has poor opensource support, you might have to emulate instead.

Looks like only the BCM57810 supports 2.5Gbps SFP.
So sad :(

**Comment by systemcrash** [comment]
Hmm, do each of the sockets have an SFP device inserted? The devices tab shows no specific config for it yet.

**Comment by missing233** [comment]
> Hmm, do each of the sockets have an SFP device inserted? The devices tab shows no specific config for it yet.

Yes. eth1 is used as the WAN interface connected to the ONU, and eth2 is in br-lan, connected to a switch.

**Comment by jow-** [comment]
Well LuCI only displays ports enumerated in /etc/board.json with an additional exception for x86-64 where it also displays all devices starting with "eth" using the same bus as "eth0".

Your passed through devices neither are in /etc/board.json nor do they use the same bus as the already present eth0, so the heuristic does not trigger.

I do not have plans to fix this, you can work around the issue by manually adding the additional eth* devices to /etc/board.json
