### ISSUE TITLE
Please backport luci-theme-material  #7003 to branch 23.05

### ISSUE THREAD

**Issue by DittelHome** [openwrt/luci#7036]
Please backport pull request #7003 also to branch 23.05 ..

**Comment by systemcrash** [comment]
Closed via 835ac7529e5cbd5a855fbc3ae07033b11e8d4ed3

**Comment by systemcrash** [comment]
( thanks for the reminder )

**Comment by DittelHome** [comment]
It's not urgent, I just want to understand it
I thought once the patch is committed I can immediate  install it via software update?
Where is my mistake in thinking?

**Comment by systemcrash** [comment]
If you run master, yes. If you're on v23, or other build, they must be
cherry picked to those branches to land in the package repo.

It's in v23 now. It usually appears after midnight builds.
