### ISSUE TITLE
luci-app-https-dns-proxy: Adguard (Standart-Family) proxy instance doesn't work

### ISSUE THREAD

**Issue by navhawk80** [openwrt/luci#7038]
Hello,
If I add Adguard (Standart) proxy instance by using luci-app-https-dns-proxy on openwrt it doesn't work yet.
I think the reason is that in config the option resolver_url is 'https://dns.adguard.com/dns-query' but it should be 'https://dns.adguard-dns.com/dns-query'. It I manually add correct value all works as expected.
May you look at the issue and correct it?
Thank you.
PS For Adguard family the same issue. In config option resolver_url is 'https://dns-family.adguard.com/dns-query' but it should be https://family.adguard-dns.com/dns-query

Additional Information:

luci-app-https-dns-proxy version 2023.11.19-r1
https-dns-proxy version 2023.11.19-r1

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.3'
DISTRIB_REVISION='r23809-234f1a2efa'
DISTRIB_TARGET='mediatek/mt7622'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 23.05.3 r23809-234f1a2efa'
DISTRIB_TAINTS=''
```

**Comment by stangri** [comment]
Thank you for the report, looks like adguard has drastically changed domains for their DoH servers. 

Are you able to test the IPK with the fix, either by manually downloading it to the router or by adding a repo which contains fixed IPK?

**Comment by stangri** [comment]
@navhawk80 https://github.com/stangri/repo.openwrt.melmac.net/blob/master/luci-app-https-dns-proxy_2023.11.19_all.ipk

It will probably match your existing AdGuard config to the correct one from the list, either way, please let me know in detail how it goes.

**Comment by navhawk80** [comment]
When I try o install it I get the following:

Executing package manager
Errors

Collected errors:
 * pkg_init_from_file: Malformed package file /tmp/upload.ipk.

The opkg install command failed with code 255.

Tried on 2 different openwrt router with latest 23.05.3 version.

**Comment by navhawk80** [comment]
All good now with new ipk. Checked default and family filter.
