### ISSUE TITLE
luci-mod-network: If no interface named "lan" exists, a TypeError will occur Cannot read properties of undefined (reading 'getIPAddrs')

### ISSUE THREAD

**Issue by nasbdh9** [openwrt/luci#7047]
https://github.com/openwrt/luci/assets/26650222/fa8e38f4-1f5e-4655-9051-dcb06075bc53

luci version: 4ca87f6576272d4a4659e995bef00cf34d5746e9

**Comment by jow-** [comment]
@systemcrash - broken by your change 723507231566b61750e32284b49acdae0d0162d3

**Comment by systemcrash** [comment]
Oops. My bad. Should be fixed now :)
