### ISSUE TITLE
luci-mod-admin-full: Add option to set anonymous_identity field

### ISSUE THREAD

**Issue by KevinOConnor** [openwrt/luci#705]
Some EAP type networks require the "anonymous_identity" field be set.  I sent a patch to enhance the openwrt config system to support the field and it was accepted (f28ca8237).

I also sent a patch submission for setting the field in luci via email: https://lists.openwrt.org/pipermail/openwrt-devel/2016-April/040748.html
I have not seen an update on the mailing list for the luci patch.  I'm opening an issue here to further track the request.

**Comment by mmunz** [comment]
would you mind doing a pull request here on github? i'll merge it then.
