### ISSUE TITLE
[luci-app-banip] UI Suggestions

### ISSUE THREAD

**Issue by Rexadev** [openwrt/luci#7067]
1. Empty Space
![image](https://github.com/openwrt/luci/assets/62152714/aae28614-3442-45e8-b766-e57e5aa51cd8)

2. Show Device's Hostname in Logs it's hard to remember IPs I have assigned

3. Show in Table instead as Logs - Show only info and about the info at top

This would turn into 
```
Wed Apr 17 12:51:39 2024 kern.debug kernel: [30012.039716] banIP/fwd-lan/reject/oisdsmallv4: IN=br-lan OUT=wan MAC=00:00:00:00:00:00:00:00:00:00:00:00:00:00 SRC=192.168.1.x DST=xxx.xxx.xxx.xxx LEN=52 TOS=0x00 PREC=0x00 TTL=127 ID=7357 DF PROTO=TCP SPT=49446 DPT=443 WINDOW=64240 RES=0x00 SYN URGP=0 MARK=0x10000
```
```
Wed Apr 17 12:51:39 2024 kern.debug kernel: [30012.039716] banIP/fwd-lan/reject/oisdsmallv4: br-lan wan 00:00:00:00:00:00:00:00:00:00:00:00:00:00 192.168.1.x xxx.xxx.xxx.xxx 52 0x00 0x00 127 7357 DF TCP 49446 443 64240 0x00 SYN 0 0x10000
```

4. Filter by Device (Mac/IP), Destination IP, Destination Zone, Block By List

5. Column with IP on https://www.abuseipdb.com/ https://www.virustotal.com/

6. Use Color - huge wall of grey text is hard to look at

7. Add sort for each column

**Comment by dibdot** [comment]
ad 1) this is theme related 
ad 2 ff.) banIP is using nftables standard logging, if you need more fancy stuff check Grafana as a visualization dashboard
