### ISSUE TITLE
error in luci-proto-vpnc

### ISSUE THREAD

**Issue by dfc-d** [openwrt/luci#710]
This is to track the error reported (but for which I can't find an issue) with luci-proto-vpnc that I pushed a wrong commit and have to fix; I haven't forgotten about it, I just haven't yet had the opportunity make sure that the fix actually works with the current luci tree.  I've gotten bogged down in other things I'm working on at the same time.

**Comment by cshoredaniel** [comment]
Fixed by another member; thanks.
