### ISSUE TITLE
log in security for admin panel.

### ISSUE THREAD

**Issue by userforsource** [openwrt/luci#7111]
Login security like what we have in tp link routers
If you give 5times wrong password it will stop for 10min
![Screenshot_20240507-110219~2](https://github.com/openwrt/luci/assets/162728301/001c5495-c44b-4f11-8c3b-c3ffcbf4b0fa)
This is a nice feature to have

**Comment by systemcrash** [comment]
I thank Zeus that luci does not include 💩 like this, because who would be so smart to expose their router to le Interwebz to necessitate something like this? If you don't want to get brute-forced, don't expose the attack surface.
