### ISSUE TITLE
Headings in bootstrap theme do not support hrefs if they have grandchildren

### ISSUE THREAD

**Issue by sarumpaet** [openwrt/luci#713]
...see https://github.com/openwrt/luci/blob/master/themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm#L119 , but there are several packages that seem to rely on this (luci-mod-freifunk's "Status" page, for example, is linked to directly in the heading).

**Comment by cshoredaniel** [comment]
@sarumpaet Which version of LuCI/OpenWrt, please

**Comment by cshoredaniel** [comment]
Actually material doesn't support href's in headers either; I'm not sure if this should be classed as a theme bug or if it's been more of a use of non-promised functionality that just happened to work and now does and the bug really is in the the apps, etc.

**Comment by feckert** [comment]
This is a very old issue.
