### ISSUE TITLE
mod-status: please add more keywords to view/nftables.js

### ISSUE THREAD

**Issue by brada4** [openwrt/luci#7155]
Status/firewall may need to parse `notrack` - similar to `accept` and `goto` similar to `jump` but ends after called chain.

**Comment by systemcrash** [comment]
Is this something fw4 itself handles also?

**Comment by brada4** [comment]
I have intent to make it do so around handle_reset.

**Comment by brada4** [comment]
After half year of intense translation notrack is still translated in error box
And in 2410 nothing gets parsed.

**Comment by brada4** [comment]
it is vmap there too, it is a bit tricky, it is like true false map but with multiple outcomes in parentheses.

![image](https://github.com/user-attachments/assets/9eddcf2f-7840-426b-9325-38cd6f36b943)

**Comment by brada4** [comment]
I dont get your sarcasm. Please instrument what comes out of this PR
https://github.com/openwrt/firewall4/pull/22
And reopen issue and avoid snarky comments.
