### ISSUE TITLE
Feature Request: luci-app-p910nd:Selecting device features based on VID/PID instead of lpX

### ISSUE THREAD

**Issue by Saxon-Sun** [openwrt/luci#7170]
When rebooting with multiple printers, character device assignments may change on reboot/reboot. But this can be avoided if you use VID/PID as in this luci-app-usb-printer 
[luci-app-usb-printer](https://github.com/immortalwrt/luci/tree/master/applications/luci-app-usb-printer)

![1](https://github.com/openwrt/luci/assets/18494610/30bbf85e-6ba5-4443-a1ee-e0e067947aba)

**Comment by systemcrash** [comment]
> When rebooting with multiple printers, character device assignments may change on reboot/reboot.

I anticipated this in the rewrite of p910nd to js.

Looks like they basically did the same thing I did. 

While p910nd GUI does not reveal these parameters, VID/PID are used internally to match a printer that was previously connected.

**Comment by Saxon-Sun** [comment]
> > 当使用多台打印机重新启动时，字符设备分配可能会在重新启动/重启时发生变化。
> 
> 我在将 p910nd 重写为 js 时预料到了这一点。
> 
> 看起来他们基本上做了和我同样的事情。
> 
> 虽然 p910nd GUI 没有显示这些参数，但 VID/PID 在内部用于匹配之前连接的打印机。

Is this true? Because I see in /etc/config/ that the configuration of option device is /dev/usb/lp0, but also write usbvidpid parameter, is usbvidpid prevailed when actually running? I don't think it's necessary to write the device parameter in config (because the lpx will change when multiple printers are rebooted, right?)
config p910nd
	option device '/dev/usb/lp0'
	option port '0'
	option bidirectional '1'
	option enabled '0'
	option usbvidpid '03f0/3b17'

**Comment by Saxon-Sun** [comment]
> > When rebooting with multiple printers, character device assignments may change on reboot/reboot.
> 
> I anticipated this in the rewrite of p910nd to js.
> 
> Looks like they basically did the same thing I did.
> 
> While p910nd GUI does not reveal these parameters, VID/PID are used internally to match a printer that was previously connected.

Hi 
I've noticed that your script currently requires specifying both the lpx device node and the usbvidpid in the configuration file. While the script itself can manage the lpx assignment dynamically during runtime, having to include lpx in the configuration seems redundant and could potentially confuse users.

I believe it would streamline the configuration process if the script autonomously determined the lpx device node based solely on the usbvidpid. This would make the setup more intuitive and reduce manual configuration errors.

Would it be feasible to enhance the script so that users only need to specify the usbvidpid, allowing the script to handle the lpx assignment automatically?
