### ISSUE TITLE
Fix this single/lone read-only string. And „The project website URL points to a non-existing location:“

### ISSUE THREAD

**Issue by dziugas1959** [openwrt/luci#7171]
I already had mentioned this, but seems like no one paid any attention to it, this single string is read-only. 
![paveikslas](https://github.com/openwrt/luci/assets/53124670/6316ac74-cfc0-412f-92dc-08a4eba569b3)

Other languages do have it translated before it was set like that, others like Russian and Lithuanian don't. 
![paveikslas](https://github.com/openwrt/luci/assets/53124670/034865e1-7eb2-4ced-a0c9-222bb98f8988)

„Weblate“ counts it as another category.
![paveikslas](https://github.com/openwrt/luci/assets/53124670/6d81d950-dce6-4db2-8dcf-af376c30d716)

Such strings should not appear in a translation project if they are not supposed to be translated, but in this case, it should be translated, as in Lithuanian (žr. 2019-11-07 Valstybinės lietuvių kalbos komisijos nutarimą Nr. N-8 (178) „Dėl Lietuvių kalbos skyrybos taisyklių“) it would be:
„Webroot“
And Russian:
«Webroot»

**Comment by dziugas1959** [comment]
P.S. Red ! 
![paveikslas](https://github.com/openwrt/luci/assets/53124670/9a9af0d5-96a3-4f45-97b8-7250f648e6e1)
![paveikslas](https://github.com/openwrt/luci/assets/53124670/09eb6fef-ad55-4bea-bbed-b87e7599ac0f)
![paveikslas](https://github.com/openwrt/luci/assets/53124670/34d6eb99-142a-4efe-ac58-94c20db1f0c9)
Only a couple of components seem to be affected.

**Comment by systemcrash** [comment]
I don't know about weblate, but a manual PR here would work :)

**Comment by dziugas1959** [comment]
> I don't know about weblate, but a manual PR here would work :)

A simple „flag“ removal/edit to editable of the string would work.
![paveikslas](https://github.com/openwrt/luci/assets/53124670/4b1a6032-3d97-4f9e-a9ec-c84ba45707d0)

This can only be done by maintainers.

**Comment by hnyman** [comment]
I removed the read-only flag in weblate from that string in Lithuanian, but no idea how that flag has surfaced there.
