### ISSUE TITLE
<luci-proto-wireguard>Can not click Generate configuration

### ISSUE THREAD

**Issue by ksi1110** [openwrt/luci#7208]
Function path: Network-Interfaces-wg (the WireGuard interface I created)-Edit-Peers-Edit-Generate configuration (cannot click).

I downloaded luci-proto-wireguard and qrencode in the system. After configuring the interface and peers, I cannot click the Generate configuration button; it remains grayed out.

Through troubleshooting, I found that the button is disabled within the element. However, after removing the "disabled" attribute, the Generate configuration button can be clicked.

I'm not familiar with frontend development and cannot determine the cause of this issue. Could someone knowledgeable in this area provide a solution?

![image](https://github.com/user-attachments/assets/ea9f6a9b-c090-4cf4-b0d6-eea34176de1f)
![image](https://github.com/user-attachments/assets/d862f4ce-ebbd-47db-b51f-cc00f62f44ee)

![image](https://github.com/user-attachments/assets/3fcbd139-7e14-46bb-954c-a5185f5dcf41)
![image](https://github.com/user-attachments/assets/f7a5c544-5acf-4825-a2a5-c0ccf437a8db)

![image](https://github.com/user-attachments/assets/7ed84f7e-84ca-4657-9479-362e951457a8)

**Comment by systemcrash** [comment]
You cannot generate a config unless the local config contains private key and optionally PSK.

**Comment by ksi1110** [comment]
> You cannot generate a config unless the local config contains private key and optionally PSK.

Thanks for replay, I was filled private key and pubkey, but still not work, I tried reinstall wireguard, It works finally,...
