### ISSUE TITLE
luci-app-mwan3: luci shouldn't allow configuration of rule names beyond 15 characters

### ISSUE THREAD

**Issue by vincejv** [openwrt/luci#7231]
## Steps to reproduce:

1. Navigate to Network > MultiWAN Manager
2. Navigate to Rule Tab
3. Add a new rule, with a rule name greater than 15 characters example in screenshot is '1234567890123456890' (20 chars)

## Actual behavior:
Luci happily accepts the input and creates a new MWAN3 Rule
![Screenshot_20240807_181826](https://github.com/user-attachments/assets/6077f256-1738-4584-9c96-dcd98d012f4e)
![Screenshot_20240807_181832](https://github.com/user-attachments/assets/db5b0511-4a6a-4880-8e5b-fcd1cb670f8b)

## Expected behavior:
Add a character limit on the text box input OR should prompt an error `Rule XXXXX exceeds max of 15 chars.` based on mwan3 logs

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.4'
DISTRIB_REVISION='r24012-d8dd03c46f'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 23.05.4 r24012-d8dd03c46f'
DISTRIB_TAINTS=''
```

mwan versions
luci-app-mwan3	git-22.181.29827-675a0ea	
mwan3	2.11.8-1

mwan3 does not apply rules that exceed 15 characters, sample log lines here:
```
Wed Aug  7 18:16:33 2024 user.warn mwan3-init[1844833]: Rule fastlane_rule_v4 exceeds max of 15 chars. Not setting rule
Wed Aug  7 18:16:33 2024 user.warn mwan3-init[1844833]: Rule fastlane_rule_v6 exceeds max of 15 chars. Not setting rule
```

**Comment by systemcrash** [comment]
Seems like a better solution would be to increase the limit in mwan3. But I don't know enough about it to comment on that.

**Comment by vincejv** [comment]
15 char limit is generous as ipset chain names are limited to 29 characters only and mwan3 appends a prefix **"mwan3_policy_"** when adding the rule in iptables, each rule has its own chain
![image](https://github.com/user-attachments/assets/c6304a86-7d07-4df6-906d-00d454167db3)

yes mwan3 still uses iptables.. it cant simply be increased as it's a limitation on iptables, unless someone migrates the thing to nftables, which has been in progress for 2 years and counting: https://forum.openwrt.org/t/mwan3-nftables-porting-help/120895

**Comment by vincejv** [comment]
also this seems like a regression?? this was discussed and fixed before: 

- https://github.com/openwrt/luci/commit/678c0b2d5ba77092ca4c422b6a3c3e3eefe86b01
- https://github.com/openwrt/luci/commit/8c19a2e1b8f8bb5f28beadd71bab88d8f892d28d
- https://github.com/openwrt/packages/issues/13499

**Comment by dannil** [comment]
Seems it was left out when migrating the app to JS in [f5f6b3e](https://github.com/openwrt/luci/commit/f5f6b3e4f8e3faed4e9c9926e283c9cf226d4bd8#diff-8f78b991c5a187c3ec8c5adb877ac4849afbb76824acc0635d1c0ea3e804bd2fR29-R32), it needs to have a `validate` function which checks the length.

**Comment by vincejv** [comment]
based on the two commits referenced and Github issue https://github.com/openwrt/packages/issues/13499, yes this character limit only applies to
Policies - https://github.com/openwrt/luci/commit/8c19a2e1b8f8bb5f28beadd71bab88d8f892d28d
Rules - https://github.com/openwrt/luci/commit/678c0b2d5ba77092ca4c422b6a3c3e3eefe86b01
