### ISSUE TITLE
luci-mod-system: missing options for ntpd

### ISSUE THREAD

**Issue by moetayuko** [openwrt/luci#7232]
## Steps to reproduce:

1. install ntpd package (https://github.com/openwrt/packages/tree/master/net/ntpd)
2. goto system -> system

## Actual behavior:

1. missing options for ntpd

## Expected behavior:

show options for ntpd

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.4'
DISTRIB_REVISION='r24012-d8dd03c46f'
DISTRIB_TARGET='mediatek/filogic'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_DESCRIPTION='OpenWrt 23.05.4 r24012-d8dd03c46f'
DISTRIB_TAINTS=''
```

**Comment by jow-** [comment]
LuCI does not supported any non-default ntpd.
