### ISSUE TITLE
luci-mod-network: typo in wireless.js

### ISSUE THREAD

**Issue by efahl** [openwrt/luci#7252]
This is a trivial one for anyone who is already working on wireless.js:

The non-breaking space character in the badge output has its digits transposed, it's `\x0a` and it should be `\xa0`.  This causes the badge to be rendered sometimes as two lines, sometimes as three and the jumpy output is pretty annoying.  (If you scan the file for `\xa0`, you'll see the other strings that are properly formatted.)

Here's the line in question:
```
			value = '---/%d\x0a%s'.format(noiseValue, _('dBm'));
```

Currently at

https://github.com/openwrt/luci/blob/master/modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js#L83

**Comment by Ramon00** [comment]
is this still an issue? Want me to make a PR? That is like 1 min work...

**Comment by systemcrash** [comment]
Yes please 👌

**Comment by systemcrash** [comment]
Fixed. :)

**Comment by Ramon00** [comment]
ah very good!
