### ISSUE TITLE
luci-mod-network: Can't setup static route with "unspecified" interface.

### ISSUE THREAD

**Issue by bienias87** [openwrt/luci#7260]
## Steps to reproduce:
**Example: Replace the following lines and remove this**

1. go to: Network → routing
2. add new
3. try to set interface "unspecified"

## Actual behavior:
There is now option to set  "unspecified" interface. 
The interface we would like to use does not appear on the list, eg. zerotier. 

## Additional Information:
OpenWrt version [OpenWrt 23.05-SNAPSHOT (r24016-f791ec1f6d)]

If we set the route manually from the console, the display in Luci is correct. The interface is undefined, but the route works properly.

**Comment by jow-** [comment]
The interface value is mandatory for uci declared routes. If your interface (zerotier) is not managed by uci, you cannot use uci route declarations for it.

**Comment by bienias87** [comment]
No, you are wrong. Uci accepts a route without an interface, and that's how I set it.

For example:
#uci add network route
#uci set network.@route[-1].target='192.168.115.0'
#uci set network.@route[-1].netmask='255.255.255.0'
#uci set network.@route[-1].gateway='172.16.0.1'
#uci commit network

give us:
![obraz](https://github.com/user-attachments/assets/b26fa683-3303-49c0-89c6-53542acc9402)

**Comment by jow-** [comment]
Ok.
