### ISSUE TITLE
luci-base: TypeError on every page

### ISSUE THREAD

**Issue by a1pha1337** [openwrt/luci#7276]
## Steps to reproduce:

1. Go to any page in LuCI

## Actual behavior:

1. Page loads with red error label with text: "TypeError_(...).format is not a function".  It fixes after several refreshes.

## Expected behavior:

1. Page loads without any errors.

## Additional Information:
LuCI openwrt-23.05 branch (git-24.073.29889-cd7e519) / OpenWrt 23.05.3 (r23809-234f1a2efa)
OpenWrt version information from system `/etc/openwrt_release`
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.3'
DISTRIB_REVISION='r23809-234f1a2efa'
DISTRIB_TARGET='bcm27xx/bcm2711'
DISTRIB_ARCH='aarch64_cortex-a72'
DISTRIB_DESCRIPTION='OpenWrt 23.05.3 r23809-234f1a2efa'
DISTRIB_TAINTS=''
```

![image](https://github.com/user-attachments/assets/29cefcaf-7bca-4376-80ab-5f905df73e22)
![image](https://github.com/user-attachments/assets/67ab71ca-150d-4ed2-b016-3a9af74e57bb)

**Comment by jow-** [comment]
`crypto.randomUUID()`,`page.js` and `injectedScript.bundle.js` do not belong to LuCI. I suspect a browser extension or some intermediate proxy is mangling the markup/scripts.

**Comment by a1pha1337** [comment]
> `crypto.randomUUID()`,`page.js` and `injectedScript.bundle.js` do not belong to LuCI. I suspect a browser extension or some intermediate proxy is mangling the markup/scripts.
> 
> Some cursory internet research hints at a "MetaMask Chrome Extension" which commonly interferes with stuff...

Yeah, you are absolutely right, LuCI without extensions works perfectly. However, diasbling MetaMask extension didn't fix the problem. May be there is another extension that inteferes as well. Thank you!
