### ISSUE TITLE
luci-mod-status: Processes with large command words overlaps the display width

### ISSUE THREAD

**Issue by Waujito** [openwrt/luci#7280]
Hello!
I have a process that operates with a large string considered word by browsers and when the string gets larger and larger, the table starts to grow horizontally like on the screenshot
![image](https://github.com/user-attachments/assets/542dc111-f0d6-49a9-b063-2c82125a0e0d)

The fix for this will be 
```
.td[data-title="Command"] {
  word-break: break-word;
}
```

![image](https://github.com/user-attachments/assets/b318bde5-29a8-4269-9807-8e04b8f7cf44)

**Comment by systemcrash** [comment]
Go ahead and propose a fix in a PR :)

**Comment by Waujito** [comment]
I did it for only Processes table, because if I touch something like theme for all tables, it will break other stuff
