### ISSUE TITLE
luci/network/interfaces/global network options - No checkbox to untick and disable ULA prefix

### ISSUE THREAD

**Issue by Mile-Lile** [openwrt/luci#7312]
luci

## Steps to reproduce:

1. go to: Network → Interfaces → Global network options 
2. try to disable ULA prefix

## Actual behavior:
there is no checkbox like before

## Expected behavior:
I could untick checkbox, Save, Apply and ULA is disabled
now I must do it froum uci:

`uci -q delete network.globals.ula_prefix
uci commit network
/etc/init.d/network restart`

![image](https://github.com/user-attachments/assets/0dc455f1-6bae-4a2f-a5d4-a777beaf8429)

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r27598-603a3c6955'
DISTRIB_TARGET='mediatek/filogic'
DISTRIB_ARCH='ARMv8 Processor rev 4'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r27598-603a3c6955 / LuCI Master 24.264.56398~8449716'
ROUTER_MODEL='Xiaomi Mi Router AX3000T (OpenWrt U-Boot layout)'
```

Browser: Chrome Version 129.0.6668.90 (Official Build) (64-bit)
OS: MS Windows 11

**Comment by systemcrash** [comment]
How about just deleting the contents of the ULA field? That's what you do with `uci -q delete network.globals.ula_prefix`.

When was there a checkbox there?
