### ISSUE TITLE
luci-nginx: rename luci-app-opkg to luci-app-package-manager

### ISSUE THREAD

**Issue by hnyyghk** [openwrt/luci#7345]
## Steps to reproduce:
Compile the firmware with .config file like this
```
CONFIG_PACKAGE_luci-nginx=y
```

## Actual behavior:
compile error with log
```
WARNING: Makefile 'package/feeds/luci/luci-nginx/Makefile' has a dependency on 'luci-app-opkg', which does not exist
```
```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-app-opkg for luci-nginx
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-nginx found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-nginx.
```

## Expected behavior:
compile success

## Additional Information:
none

**Comment by this-username-has-been-taken** [comment]
The issue appeared after `luci-app-opkg` has been renamed to `luci-app-package-manager`: https://github.com/openwrt/luci/commit/bcd13b918e2f30b8d19027a06e3d773a1b0ec4c0
