### ISSUE TITLE
No “software”on ”system”

### ISSUE THREAD

**Issue by evanzing** [openwrt/luci#7352]
How should I do for this？
When I typef  this “opkg update&opkg install luci-app-opkg”
It told me that it was wrong

```
Downloading https://downloads.openwrt.org/snapshots/packages/×86_64/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/×86_64/small/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/×86_64/small/Packages.qz
Downloading https://downloads.openwrt.org/snapshots/packages/×86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/×86_64/telephony/Packages.sig
Signature check passed.
Collected errors:
* opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/×86_64/kenzo/Packages.gz, wet returned 8.
* opkg_download: Failed to download https: //downloads.openwrt.org/snapshots/packages/×86_64/small/Packages.gz, wget returned 8.
root@OpenWrt: ~# opkq install luci-app-opkg
Unknown package 'luci-app-opkg'
Collected errors:
* opkg_install_cm: Cannot install package luci-app-opkg.
root@OpenWrt:~#
```

**Comment by hnyman** [comment]
There are no "small" or "kenzo"directories in the normal download serves, so I have no idea, what firmware you are running.
luci-app-opkg should in x86_64/base directory, but has been renamed a few days ago to luci-app-package-manager

http://downloads.openwrt.org/snapshots/packages/x86_64/luci/luci-app-package-manager_24.297.79519~bcd13b9_all.ipk

**Comment by this-username-has-been-taken** [comment]
`luci-app-opkg` has been renamed to `luci-app-package-manager`: https://github.com/openwrt/luci/issues/7345
Try running `opkg install luci-app-package-manager` instead.

**Comment by systemcrash** [comment]
> `luci-app-opkg` has been renamed to `luci-app-package-manager`: [bcd13b9](https://github.com/openwrt/luci/commit/bcd13b918e2f30b8d19027a06e3d773a1b0ec4c0) Try running `opkg install luci-app-package-manager` instead.

Solution 👍

**Comment by hnyman** [comment]
Probably due to that luci-light thing that in practice removed opkg app from default LuCI in private builds...
