### ISSUE TITLE
luci-proto-wireguard: suggestion to make peers sortable (enable drag and drop)

### ISSUE THREAD

**Issue by this-username-has-been-taken** [openwrt/luci#7354]
Hello!
If a Wireguard interface acts as a server (i.e. has a `listen port` defined), it usually has more than one peer defined. In such cases it might be very convenient to change their order, especially when adding a new peer: put it in "its place".
My suggestion is to enable `sortable` option for the Peers `TabSection`, i.e. allow users to change peers order on the corresponding tab.
***

## Suggested solution
To enable sorting on the Peers tab, it is required to set just one property for the tab, i.e. add one line after line 207 in `luci/protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js` script:
```
ss.sortable = true;
```
I have added this line on the live OpenWrt system, restarted the webserver and rpcd daemons and it worked just fine (see screenshot below).
In fact writing this task took more time than applying the modification :)
![Peers tab with sorting](https://github.com/user-attachments/assets/945e485a-96a7-440d-a87a-eb7522f3d510)
After applying the modification it is now possible to rearrange `Peer 3` and `Peer 4` via the web interface and make those guys with OCD happy!

## Steps to reproduce:
1. Go to: Network → Interfaces → add a new Wireguard interface.
2. Add more than one peer to the interface.
3. Save and apply.
4. Navigate to the Peers tab of a freshly created interface.
5. Observe the issue: it is impossible to rearrange peers in LuCi without deleting them and creating in the right order.

## Actual behavior:
It is impossible to rearrange peers in LuCi without deleting them and creating in the right order.

## Expected behavior:
It is possible to rearrange peers right in LuCi.

**Comment by systemcrash** [comment]
Done 😄

**Comment by this-username-has-been-taken** [comment]
Thank you very much! :)
It is now easier to manage peers. I hope others will also appreciate it as well!
