### ISSUE TITLE
luci-app-opkg: PermissionError after upgrading from git-24.148.43905-2891ca4 to git-24.299.75545-b93fdef version

### ISSUE THREAD

**Issue by krisprols** [openwrt/luci#7357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Actual behaviour

In System > Software menu. 
Click on the "Update Lists..." button.

I get the message "Unable to execute opkg update command: PermissionError: Access to command denied by ACL".

### Expected behaviour

LuCI should run "opkg update" successfully.

### Steps to reproduce

Upgrade luci-app-opkg from git-24.148.43905-2891ca4 to git-24.299.75545-b93fdef version.

Go to System > Software menu. 
Click on the "Update Lists..." button.

### Additional Information

```shell
NAME="OpenWrt"
VERSION="23.05.5"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 23.05.5"
VERSION_ID="23.05.5"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r24106-10cc5fcd00"
OPENWRT_BOARD="ath79/generic"
OPENWRT_ARCH="mips_24kc"
OPENWRT_TAINTS=""
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt 23.05.5 r24106-10cc5fcd00"
```

### What browsers do you see the problem on?

Firefox

### Relevant log output

```shell
Unable to execute opkg update command: PermissionError: Access to command denied by ACL
```

**Comment by systemcrash** [comment]
@Ansuel - it seems that update has extra space or parameters following the keyword 'update'. Maybe `/usr/libexec/opkg-call` actually takes `opkg update <pkgname>` after all?

**Comment by systemcrash** [comment]
Tested on my VM. Upgrade went fine. 
```log
Upgrading luci-app-opkg on root from git-24.148.43905-2891ca4 to git-24.299.75545-b93fdef...
Downloading https://downloads.openwrt.org/releases/23.05.5/packages/x86_64/luci/luci-app-opkg_git-24.299.75545-b93fdef_all.ipk
Configuring luci-app-opkg.
```

**Comment by systemcrash** [comment]
@krisprols  Did you change any of your json files or any custom edits before this?

**Comment by systemcrash** [comment]
> Weirdly, I still see in the RPC calls e.g.:
> 
> ```shell
> /usr/libexec/opkg-call install --force-removal-of-dependent-packages luci-mod-network
> ```

Reboot fixed that :D

**Comment by krisprols** [comment]
> @krisprols Did you change any of your json files or any custom edits before this?

Not at all. I could even reproduce the problem after I reseted my router.

**Comment by krisprols** [comment]
> Tested on my VM. Upgrade went fine.
> 
> ```
> Upgrading luci-app-opkg on root from git-24.148.43905-2891ca4 to git-24.299.75545-b93fdef...
> Downloading https://downloads.openwrt.org/releases/23.05.5/packages/x86_64/luci/luci-app-opkg_git-24.299.75545-b93fdef_all.ipk
> Configuring luci-app-opkg.
> ```

Yes the upgrade goes fine. That's not the problem. The problem is how this upgrade breaks the UI.

**Comment by systemcrash** [comment]
I upgraded the package, rebooted, and could upgrade and install other packages. I repeated the test again just now. Same result. Works fine for me. Is your memory full or something?

**Comment by Ansuel** [comment]
@systemcrash yes my bad i forgot to add the extra line from my testing env to the pr
the acl.d require to both handle single opkg update and opkg update *

**Comment by systemcrash** [comment]
When I run opkg I get:
```
	update			Update list of available packages
	upgrade <pkgs>		Upgrade packages
```

update = No parameters 🤷

**Comment by Ansuel** [comment]
What about update scenario? For an updated package? Is install called?

**Comment by systemcrash** [comment]
> What about update scenario? For an updated package? Is install called?

That's surely

```
	upgrade <pkgs>		Upgrade packages
```

**Comment by systemcrash** [comment]
Propose an edit for @krisprols to test first. See whether that fixes his problem?

**Comment by krisprols** [comment]
> I upgraded the package, rebooted, and could upgrade and install other packages. I repeated the test again just now. Same result. Works fine for me. Is your memory full or something?

No, not a memory issue. 
![Screenshot 2024-10-26 194105](https://github.com/user-attachments/assets/6ee64fc0-a3e0-4593-855d-aa86011a7aaf)

**Comment by krisprols** [comment]
FYI the problem only occurs for the  "Update Lists..." button. The "opkg update" command still works fine from command line. Installs and upgrades through GUI are fine as well. It looks like only the "opkg update" through the  "Update Lists..." button of the UI is impacted by this bug.

**Comment by Ansuel** [comment]
Did you by chance cleared cache of the webpage? Tried incognito?

**Comment by systemcrash** [comment]
Hmm. Is that json parameter something that sneaks in also?

**Comment by Ansuel** [comment]
@systemcrash the parameter are generated by the .js page... If the old version is used then opkg-call update --force-removal-of... is still called...

**Comment by systemcrash** [comment]
Yeah clear the browser cache. Delete all the cache for that router and reload. See whether that helps.

**Comment by krisprols** [comment]
@Ansuel @systemcrash cleaning up the cache actually fixed the problem ! Thanks for the help. Sorry I haven't done that in the first place. I didn't bother trying as It looked like a server-side issue to me.

**Comment by krisprols** [comment]
@Ansuel @systemcrash cleaning up the cache actually fixed the problem ! Thanks for the help. Sorry I haven't done that in the first place. I didn't bother trying as It looked like a server-side issue to me.

**Comment by Ansuel** [comment]
@systemcrash well.... I think just to handle these sort of problem I would add the entry anyway just to catch these cache problem...
No idea what @jow- thinks about it.

(IN SHORT for jow:
we changed acl.d and we limit it to single opkg-call update but the .js might be cached and still forward additional args)

**Comment by Silun** [comment]
I am getting the same issue: `Unable to execute opkg update command: PermissionError: Access to command denied by ACL`

I can confirm that the update is faulty. Not running out of cache or anything like that. Rebooting does not fix the issue. I cannot update my list any more via Luci after the update. I am on OpenWrt 23.05.5 r24106-10cc5fcd00 / LuCI openwrt-23.05 branch git-24.264.56413-c7a3562, router is AX3000T.

**Comment by Deci8BelioS** [comment]
> I am getting the same issue: `Unable to execute opkg update command: PermissionError: Access to command denied by ACL`
> 
> I can confirm that the update is faulty. Not running out of cache or anything like that. Rebooting does not fix the issue. I cannot update my list any more via Luci after the update. I am on OpenWrt 23.05.5 r24106-10cc5fcd00 / LuCI openwrt-23.05 branch git-24.264.56413-c7a3562, router is AX3000T.

The same thing happens to me, I get the error when I try to update the packages from the LuCi interface.

**Comment by Silun** [comment]
I just downloaded and installed the generic older version still available in the repo [here](https://downloads.openwrt.org/releases/packages-23.05/aarch64_generic/luci/luci-app-opkg_git-24.148.43905-2891ca4_all.ipk) via SSH:

`wget https://downloads.openwrt.org/releases/packages-23.05/aarch64_generic/luci/luci-app-opkg_git-24.148.43905-2891ca4_all.ipk` to download the latest working version of the package, it might be different for your router, check carefully.

`opkg remove luci-app-opkg --force-depends` to force uninstall the current, broken version of the package.

`opkg install luci-app-opkg_git-24.148.43905-2891ca4_all.ipk` to install the working version from right before.

Et voila, it works again. If there's a better way, please do tell.

**Comment by Deci8BelioS** [comment]
> I just downloaded and installed the generic older version still available in the repo [here](https://downloads.openwrt.org/releases/packages-23.05/aarch64_generic/luci/luci-app-opkg_git-24.148.43905-2891ca4_all.ipk) via SSH:
> 
> `wget https://downloads.openwrt.org/releases/packages-23.05/aarch64_generic/luci/luci-app-opkg_git-24.148.43905-2891ca4_all.ipk` to download the latest working version of the package, it might be different for your router, check carefully.
> 
> `opkg remove luci-app-opkg --force-depends` to force uninstall the current, broken version of the package.
> 
> `opkg install luci-app-opkg_git-24.148.43905-2891ca4_all.ipk` to install the working version from right before.
> 
> Et voila, it works again. If there's a better way, please do tell.

Clearing the browser cache will fix it.

**Comment by Silun** [comment]
Okay, yes, that worked. 🙈

**Comment by goppinath** [comment]
I got the same [issue](https://forum.openwrt.org/t/unable-to-execute-opkg-update-command-permissionerror/214015), clearing the cache or accessing LuCi in the private window helps.

**Comment by wlkmanist** [comment]
So, how it may be fixed without clearing the cache? Can't find an older version in packages.

**Comment by rogovogor** [comment]
NOTE: You need to delete the cache, not the cookies

**Comment by Ansuel** [comment]
@systemcrash Just to stop the ""flood"" I just reverted the commit for 23.xx and 22.xx. It's so minor it's not worth to partially revert and this won't happen on master or on the next release as we renamed the package (aka cache invalidated)

**Comment by pawol** [comment]
I confirm that browser cache clearing helped to me with 3 openwrt devices
