### ISSUE TITLE
routes.js  The translation is not displaying 

### ISSUE THREAD

**Issue by try496** [openwrt/luci#7401]
### How can we otherwise help?

I can see that Simplified Chinese and Polish are provided, but the translation is not displaying. This is after a fresh compilation and installation.

#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js:96
#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js:173
msgid ""
"A numeric table index, or symbol alias declared in %s. Special aliases local "
"(255), main (254) and default (253) are also valid"
msgstr "数值表索引，在 %s "
"中声明的符号别名。特殊别名local（255）、main（254）和default（253）是有效的"

#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js:96
#: modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js:173
msgid ""
"A numeric table index, or symbol alias declared in %s. Special aliases local "
"(255), main (254) and default (253) are also valid"
msgstr ""
"Indeks tablicy numerycznej lub alias symbolu zadeklarowany w %s. Specjalne "
"aliasy local (255), main (254) i default (253) są również prawidłowe"

![屏幕截图 2024-11-16 212912](https://github.com/user-attachments/assets/30d25945-1ee1-4f5f-b3ab-dc8848e18819)
![屏幕截图 2024-11-17 150110](https://github.com/user-attachments/assets/5d4e6b5b-d095-4fb6-a9fc-2c380adfb1f0)

**Comment by try496** [comment]
Using OpenWrt 24.10 for the build.

**Comment by hnyman** [comment]
It may be a coding error in 
https://github.com/openwrt/luci/blob/09e8d5108ed678db5b940b1eb51dff2b9b6af189/modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js#L96

The translate function "_" has parentheses that cover also the contents of .format ...
The closing parentheses might need to be before .format

I am not sure if that is right, or should that just be split into three parts, two translated strings and untranslated code in between.

**Comment by hnyman** [comment]
Yeah, looks like a recent error from @systemcrash in a9e1685

I will change the place of the erroneous parentheses:
`_('A numeric table index, or symbol alias declared in %s. Special aliases local (255), main (254) and default (253) are also valid'.format('<code>/etc/iproute2/rt_tables</code>'))`
-->
`_('A numeric table index, or symbol alias declared in %s. Special aliases local (255), main (254) and default (253) are also valid').format('<code>/etc/iproute2/rt_tables</code>')`
