### ISSUE TITLE
luci-base (LuCI.form.AbstractValue): Empty formvalue won't call write()

### ISSUE THREAD

**Issue by Try2079** [openwrt/luci#7409]
## Is there an existing issue for this?

- [X] I have searched the existing issues

## Actual behaviour

I overridden the cfgvalue and write methods of form.Value,
After modifying the value of the input box, the write method will be called when you click save;
--- ---
But if you **clear the value in the input box** and click save, the write method will **not** be called.
It seems that the framework does not detect that the value of the input box has changed at this time.

## Expected behaviour

**clear the value in the input box** and click save, automatically call the write method.

## Steps to reproduce

```
o = s.option(form.Value, 'test', _('Hello Input Box'));
o.cfgvalue = function(section_id) { return 'here is value, not empty!' };
o.write = function(section_id, formvalue) { uci.set('foo', 'bar', 'abc', formvalue) };
```
Go to LuCI Web Page, clear the value in "Hello Input Box";
Hit 'Save' or 'Save & Apply' button;
o.write function will **not** be called!
--- ---
And I found these in luci-base, form.js line 2000 ~ 2035:
```
1. parse: function(section_id) {
2. 		var active = this.isActive(section_id);
3. 
4. 		if (active && !this.isValid(section_id)) {
5. 			var title = this.stripTags(this.title).trim(),
6. 			    error = this.getValidationError(section_id);
7. 
8. 			return Promise.reject(new TypeError(
9. 				_('Option "%s" contains an invalid input value.').format(title || this.option) + ' ' + error));
10. 		}
11. 
12. 		if (active) {
13. 			var cval = this.cfgvalue(section_id),
14. 			    fval = this.formvalue(section_id);
15. 
16. 			if (fval == null || fval == '') {
17. 				if (this.rmempty || this.optional) {
18. 					return Promise.resolve(this.remove(section_id));
19. 				}
20. 				else {
21. 					var title = this.stripTags(this.title).trim();
22. 
23. 					return Promise.reject(new TypeError(
24. 						_('Option "%s" must not be empty.').format(title || this.option)));
25. 				}
26. 			}
27. 			else if (this.forcewrite || !isEqual(cval, fval)) {
28. 				return Promise.resolve(this.write(section_id, fval));
29. 			}
30. 		}
31. 		else if (!this.retain) {
32. 			return Promise.resolve(this.remove(section_id));
33. 		}
34. 
35. 		return Promise.resolve();
36. 	},

```

**Can you guys change 'else if' to if?
I mean line 27 (or line 2026 in form.js)
`else if (this.forcewrite || !isEqual(cval, fval)) {` to `if (this.forcewrite || !isEqual(cval, fval)) {`**

**Comment by jow-** [comment]
Either implement `remove()` in addition to `write()` or set `.forcewrite = true` on your option.
