### ISSUE TITLE
Watchcat install and update package errors

### ISSUE THREAD

**Issue by swvalenti194** [openwrt/luci#7421]
Watchcat throws errors "uci invalid argument" Anyone have a way to fix this?  Also getting package update errors when trying to update lists.  Thanks!

```
apk add watchcat

(1/1) Installing watchcat (1-r17)
Executing watchcat-1-r17.post-install
OK: 82 MiB in 520 packages

Errors
uci: Invalid argument
uci: Invalid argument
uci: Invalid argument
```

![Error](https://github.com/user-attachments/assets/4a963b5a-caa0-4a39-89ae-982e651fb2f6)

**Comment by systemcrash** [comment]
Not enough info provided
