### ISSUE TITLE
luci-base: form.js  so.depends(foo != '0' && bar == '0');

### ISSUE THREAD

**Issue by Try2079** [openwrt/luci#7429]
## How do I make depends (foo != '0' && bar == '0') effective?

When the `parentoption` of `ss` is hidden due to unsatisfied dependencies, `so` is still in the active state.

Although we **can't see** `so` at this point, we **can't save** the configuration if `so` has `rmempty = false` or other attributes that cause it to be `invalid`

Here is an example:
```javascript
m = new form.Map('foo', _('Form_Name'));

s = m.section(form.NamedSection, 'bar', 'type', _('Hello'));

o = s.option(form.Flag, 'switch', _('Switch'));

o = s.option(form.SectionValue, '__abc', form.NamedSection, 'name', 'type', _('Sub Section'));
o.depends('switch', '1');

ss = o.subsection;

so = ss.option(form.ListValue, 'list', _('More Option'));
so.value('a', 'A');
so.value('b', 'B');
so.value('c', 'C');
so.value('d', 'D');
so.value('e', 'E');

so = ss.option(form.Value, 'bad_ass', _('You Can\'t Save'));
so.rmempty = false;
so.datatype = 'ip4addr("nomask")';
so.depends({
    // (list != 'a' && 'foo.bar.switch' == '1')
});

```

**Comment by systemcrash** [comment]
The `depends` text could do with a few more illuminating examples. I know I've squinted at them over the years.

https://openwrt.github.io/luci/jsapi/LuCI.form.FlagValue.html#depends

**Comment by Try2079** [comment]
I looked at the source code of [isDependencySatisfied()](https://openwrt.github.io/luci/jsapi/form.js.html#line738).
Because `!reverse` will reverse the result of the entire object (final NOT gate), we may not be able to implement `so.depends(foo != '0' && bar == '0');` with just one `depends` function.

**In fact, the focus of this issue is that when `ss` does not meet the dependency conditions, although `so` is hidden along with `ss`, if `so` is invalid, an error will still be reported when pressing the save key.**

**Comment by systemcrash** [comment]
Your analysis seems correct. In which case, one must take an alternative approach, unless you can see a suitable way to handle various logic conditions necessary. E.g. adding multiple objects instead of just the first object?

Otherwise you likely cannot directly do `(foo != '0' && bar == '0')` but multiple other `(foosomethingelse = '0' && bar == '0')`
