### ISSUE TITLE
luci-proto-wireguard: potentical code injection (vulnerability)

### ISSUE THREAD

**Issue by this-username-has-been-taken** [openwrt/luci#7452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Actual behaviour

Thanks to @jow- : a vulnerability has been detected in recent `luci-proto-wireguard` code which allows execute random code.
The vulnerability exists in `checkPeerHost` method: `configHost` variable is passed into `popen` command without sanitizing. Thus an attacker can define peer with 'option endpoint_host '$({any code here})` and it will be executed.

To fix this issue `const ips = popen(`resolveip ${configHost} 2>/dev/null`);` should be changed to `const ips = popen(`resolveip ${shellquote(configHost)} 2>/dev/null`);` i.e. the sanitizing function `shellquote` should be introduced.

Without this fix if a user defines peer for example with `option endpoint_host '$(logger injection)'` variable and navigates to `Status -> Wireguard` page then message `ingection` will be put in log, i.e. code will be executed

### Expected behaviour

If a user defines peer with `'option endpoint_host '$(logger injection)'` variable and navigates to `Status -> Wireguard` page then nothing happens, i.e. `logger injection` code won't be executed

### Steps to reproduce

1. Go to Network -> Interfaces.
2. Create a new Wireguard interface: put random, but correct values into private and public addresses as well as IP address. Do not put anything into listen port variable.
3. Create a Peer for the freshly defined Wireguard interface: put random, but correct values into public key, allowed IPs, endpoint host, endpoint port.
4. Save and apply.
5. Edit `/etc/config/network` file and change `option endpoint_host` variable for the peer defined in step 3 to `option endpoint_host '$(logger injection)'`.
6. Restart the interface created in step 2.
7. Run `logread -f` command in terminal.
8. Navigate to Status -> Wireguard.
9. Observe `injection` string in log.

### Additional Information

```shell
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r28245-3ba6737f2f"
OPENWRT_BOARD="mediatek/filogic"
OPENWRT_ARCH="aarch64_cortex-a53"
OPENWRT_TAINTS="no-all"
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt SNAPSHOT r28245-3ba6737f2f"
OPENWRT_BUILD_DATE="1733232401"
```

### What browsers do you see the problem on?

Firefox, Chrome

### Relevant log output

```shell
Wed Dec  4 21:07:56 2024 user.notice root: injection
```

**Comment by systemcrash** [comment]
Closed by ff6460ccf122358e97ecb7e2c4abb7740d4f626c
