### ISSUE TITLE
the cbi.js doesn't support the self define template 

### ISSUE THREAD

**Issue by happybeta** [openwrt/luci#746]
for example, I write a resp_value.html to instand of value.html .

`<%+cbi/resp_valueheader%>
    <% if self.password then %><div class="input-group"> <% end %>
    <input data-update="change"<%=
        attr("id", cbid) ..
        attr("name", cbid) ..
        attr("type", self.password and "password" or "text") ..
        attr("class", self.password and "resp-input-password form-control preview-password" or "resp-input-text form-control beautify") ..
        attr("value", self:cfgvalue(section) or self.default) ..
        ifattr(self.size, "size") ..
        ifattr(self.placeholder, "placeholder") ..
        ifattr(self.readonly, "readonly") ..
        ifattr(self.maxlength, "maxlength") ..
        ifattr(self.datatype, "data-type", self.datatype) ..
        ifattr(self.datatype, "data-optional", self.optional or self.rmempty) ..
        ifattr(self.combobox_manual, "data-manual", self.combobox_manual) ..
        ifattr(#self.keylist > 0, "data-choices", { self.keylist, self.vallist })
    %> />
    <% if self.password then %></div> <% end %>
<%+cbi/resp_valuefooter%>
`

this issue was existed on the cc until the trunk version

**Comment by jow-** [comment]
... and what is the actual problem?

**Comment by pxnj63** [comment]
this issue will generate wrong html structure. and let some js does not work. for example the select depend relation.

**Comment by jow-** [comment]
Its up to your template to implement those. Can you provide a minimal, complete testcase?

**Comment by pxnj63** [comment]
I have to modify the cbi.js , it is a difficult work for me . is there design documents for the cbi.js ?

**Comment by cshoredaniel** [comment]
@pxnj63 No such documents.  This is very much a case of reading the source code and figuring out how it works yourself, or with the help of forums.

**Comment by jow-** [comment]
Not LuCI upstream related.
