### ISSUE TITLE
Need to change LUCI Global Object path

### ISSUE THREAD

**Issue by raihanhbh** [openwrt/luci#747]
Hi,
I am playing with LUCI for last couple of months. I have prepared unique LUCI UI then conventional UI that are available on the web. As part of my explore, I have prepare two LUCI work space in same router.
They will share same config & other common resources. I am using uhttpd. Two Luci work spaces are separated through port.

I can access first LUCI work space smoothly but I can reach upto **cgi.lua** in the 2nd LUCI work space ( **/usr/lib/lua/luci1**). My problem is, After accessing 2nd **cgi.lua** ( **/usr/lib/lua/luci1**), controls back to the first LUCI ( **/usr/lib/lua/luci**) as Global LUCI is pointed to first LUCI ( **/usr/lib/lua/luci**) work space.

I need to change the Global LUCI object pointing to /usr/lib/lua/luci1 instead of /usr/lib/lua/luci when I will access the LUCI1.

I have tried to explain my problem. Please let me know if something still un clear.

 Thank in advance.

**Comment by cshoredaniel** [comment]
@raihanhbh I'm afraid this is a completely unsupported usage and unless you can find others interested in to same problem (for example on the forums), you'll have to rethink your design.
