### ISSUE TITLE
Switch configuration page should show associated network

### ISSUE THREAD

**Issue by nwf** [openwrt/luci#755]
When configuring an ethernet switch, Luci just shows the VLAN IDs.  It would be very helpful if it put the network name next to them, as it can do when displaying physical settings for interfaces.

**Comment by cshoredaniel** [comment]
@nwf The suggestion is interesting, but unlikely to be implemented in the forseeable future (although of course patches are welcome).

**Comment by cshoredaniel** [comment]
Actually I lied; it does this in LuCI trunk already.
