### ISSUE TITLE
luci-app-wol not appear in the network menu

### ISSUE THREAD

**Issue by zhangguangtong** [openwrt/luci#757]
I installed luci-app-wol, however it didn't appear in network menu.

After compare other lua file the controller. I come with a fix.

Append '.dependent = true' to the two line start with entry.
```
module("luci.controller.wol", package.seeall)

function index()
        entry({"admin", "network", "wol"}, cbi("wol"), _("Wake on LAN"), 90).dependent = true
        entry({"mini", "network", "wol"}, cbi("wol"), _("Wake on LAN"), 90).dependent = true
end

```

**Comment by jow-** [comment]
It should work without that change too after `rm /tmp/luci-indexcache` - can you please test?

**Comment by zhangguangtong** [comment]
@jow- 

Thanks, I tested in my side. ```rm /tmp/luci-indexcache``` does works.

I am not clear how ```.dependent = true``` works . Would it better if we add this?

**Comment by jow-** [comment]
No, its an obsolete property which should not affect things. I'm closing this PR as the original issue was a stale menu cache.
