### ISSUE TITLE
luci-app-aria2 unable save other methode

### ISSUE THREAD

**Issue by hostkit** [openwrt/luci#760]
@kuoruan can you fix this? 
when i want to other method rpc-scret, luci-app-aria2 said this
![capture](https://cloud.githubusercontent.com/assets/3790389/16897130/57f17252-4bd2-11e6-975a-76353f358158.PNG)

**Comment by kuoruan** [comment]
OK, I will fix it. Please wait.

**Comment by kuoruan** [comment]
Please try the new version, and give me a feed back. thx

**Comment by hostkit** [comment]
no authentication unable to save, user and password luci-app-aria2 stuck when click save

**Comment by kuoruan** [comment]
Everything works well in my device.

**Comment by hostkit** [comment]
![capture](https://cloud.githubusercontent.com/assets/3790389/17175410/9a2e7d10-5431-11e6-9ca8-48a577320089.PNG)

**Comment by hostkit** [comment]
can you build for me :) maybe such as aria2 :smile:

**Comment by kuoruan** [comment]
https://soft.kuoruan.com/openwrt/ar71xx/packages/luci/luci-app-aria2_git-16.206.66468-6f5c466-1_all.ipk

**Comment by hostkit** [comment]
ok work again :+1: 

suggestion: add download schedule option (start download at ... and stop download at ... )
cat it posible? until now im using manual cronjob using curl

https://github.com/ziahamza/webui-aria2/issues/126 
:smile:
