### ISSUE TITLE
trunk version 15/7/2016 ,lenovo y1 only when wifi encryption is none, wireless can work

### ISSUE THREAD

**Issue by 523860169** [openwrt/luci#762]
if change encryption to others, can't enable wireless, show Wireless is disabled or not associated
but I can't find the AP

**Comment by 523860169** [comment]
trunk version 17/7/2016 ,lenovo y1 wifi encryption is recovered, but wan can't work, pppoe、dhcp、none of them can work well

**Comment by cshoredaniel** [comment]
Please reopen with the following information if you are still having issues:

1) What you expected to happen
2) What actually happened
3) Steps you can reliably follow to produce the same result
4) Steps you tried to resolve the issue.
