### ISSUE TITLE
Luci-app-aria schedule download

### ISSUE THREAD

**Issue by hostkit** [openwrt/luci#767]
@kuoruan i want to add menu shedule download but i dont understand how to read from luci-app-aria config.

**Comment by kuoruan** [comment]
* https://github.com/openwrt/luci/blob/master/documentation/CBI.md
* https://wiki.openwrt.org/doc/devel/luci
* https://wiki.openwrt.org/doc/uci

**Comment by cshoredaniel** [comment]
Doc request, not a bug.
