### ISSUE TITLE
Status > Overview page shows LAN details for WAN Status 

### ISSUE THREAD

**Issue by patricktokeeffe** [openwrt/luci#771]
The Status>Overview page displays LAN details in the "IPv4 WAN Status" section. Instead of describing the WAN interface, `eth1`, it describes `br-lan` instead.

![luci-status-page](https://cloud.githubusercontent.com/assets/1348834/17571592/bf069c2e-5f05-11e6-96a2-63c4706bcdd1.png)

To be clear, I wouldn't mind seeing LAN details (if they were properly labeled). But the real issue here is the lack of genuine WAN details. 

Probably related: #332

**Comment by jow-** [comment]
Remove the gateway option from lan.
