### ISSUE TITLE
LuCI-SSL vulnerable to bettercap sslstrip attack

### ISSUE THREAD

**Issue by gnuowned** [openwrt/luci#801]
I audit my network with bettercap to find that LuCI-SSL is vulnerable to SSLTRIP attacks. I was able to get my username and password if somebody access the router in the network.

**Comment by jow-** [comment]
We cannot fix this on the LuCI side. If someone is able to perform a man-in-the-middle within your own LAN you have bigger issues. You can try to partially mitigate the problem by disabling plain HTTP in uhttpd - remove the port 80 listener for that.
