### ISSUE TITLE
luci-app-tinyproxy: Allowed connect ports description “A single value 0”

### ISSUE THREAD

**Issue by yydcool** [openwrt/luci#803]
Based on the man page https://linux.die.net/man/5/tinyproxy.conf: 
"ConnectPort
This option can be used to specify the ports allowed for the CONNECT method. If no ConnectPort line is found, then all ports are allowed. To disable CONNECT altogether, include a single ConnectPort line with a value of 0."

So a single ConnectPort line with a value of 0 is to disable all port.

However, the description of "Allowed connect ports" is wrong:"List of allowed ports for the CONNECT method. A single value "0" allows all ports"

**Comment by hnyman** [comment]
You are referring to this GUI item, right?

https://github.com/openwrt/luci/blob/master/applications/luci-app-tinyproxy/luasrc/model/cbi/tinyproxy.lua#L133
```
o = s:taboption("filter", DynamicList, "ConnectPort", translate("Allowed connect ports"),
translate("List of allowed ports for the CONNECT method. A single value \"0\" allows all ports"))
```

**Comment by yydcool** [comment]
yes

**Comment by hnyman** [comment]
You are probably right, it is defined that way also in the tinxyproxy package's config file here:

https://github.com/openwrt/packages/blob/master/net/tinyproxy/files/tinyproxy.config#L184
```
# This is a list of ports allowed by tinyproxy when the CONNECT method
# is used.  To disable the CONNECT method altogether, set the value to 0.
# If no ConnectPort line is found, all ports are allowed (which is not
# very secure.)
```

**Comment by hnyman** [comment]
cc to tinyproxy package maintainer: @jow- 

Any view on this? Just a typo in Luci? (or alternatively in tinyproxy default config?) Or is there something in the uci handling that changes the behaviour?

**Comment by M95D** [comment]
Can we fix this, please? It's just a typo in the description.

**Comment by M95D** [comment]
That was fast. Thanks!
