### ISSUE TITLE
How can I add an unauthenticated page

### ISSUE THREAD

**Issue by HoffmannP** [openwrt/luci#804]
I currently writing a StreamSelector Application and wuld like to know, how I can ad an unauthenticated page // entry to LuCI.

(see [HoffmannP/LuCI-streamer](https://github.com/HoffmannP/LuCI-streamer))

**Comment by HoffmannP** [comment]
It's actually pretty straightforward. Just add a page that has an entry that does not start with admin

    entry({"streamer"}, alias("streamer", "show"), _("Stations"), 90)

    entry({"admin", "streamer"}, alias("streamer", "show"), _("Stations"), 90)

while the first on is unauthenticated, the second one is behind the login page.

**Comment by cshoredaniel** [comment]
User figured it out for himself, closing.
