### ISSUE TITLE
luci-app-firewall: Add date/time config to Firewall 'Port Forwards', as already done with 'Rules'

### ISSUE THREAD

**Issue by build000** [openwrt/luci#818]
@jow- , @hnyman and other developers to LuCI/other packages.
In connection with the idea of adding another application https://github.com/openwrt/luci/pull/802 (this time I think it unnecessary) Please modify what is already present in the system.
I have written about the amendments to the firewall/LuCI LEDE, you can go a step further and simply enter the same funcionality in the [address]/cgi-bin/luci/admin/network/firewall/forwards - ie. identical to that which occurs in the [address]/cgi-bin/luci/admin/network/firewall/rules - the effect will be exactly the same as the word suggests additional application https://github.com/openwrt/luci/pull/802, which made it by creating and adding to the repository packages unnecessary.
Possible discomfort with the limitations of modules in the kernel regarding the UTC probably also be bypassed scripted this function at the level of the luci/luci-app-firewall.

**Comment by jow-** [comment]
This is implemented in master.
