### ISSUE TITLE
luci.model.network not documented

### ISSUE THREAD

**Issue by karlp** [openwrt/luci#837]
The autogenerated API is missing all evidence of the luci.model.network package.

**Comment by cshoredaniel** [comment]
There are no luadoc comments in https://github.com/openwrt/luci/blob/master/modules/luci-base/luasrc/model/network.lua.  As the plan is to move to luci-ng, old style luci documentation is unlikely to get a lot of attention unless a community member submits a PR.

**Comment by jow-** [comment]
The Lua class is more or less deprecated and has no active users anymore afair. The Javascript counterpart is documented at http://openwrt.github.io/luci/jsapi/LuCI.network.html

**Comment by karlp** [comment]
well, grep for luci.model.network still shows plenty of references, even in master, let alone 21.02, but yeah, I know it's on it's way out.  :)
