### ISSUE TITLE
Table breaks out of layout (cbi/tblsection)

### ISSUE THREAD

**Issue by danrl** [openwrt/luci#838]
Working on luci-proto-wireguard. Unfortunately, the peers require quite some options. Too many for the table, so the table breaks out of the layout. Am I doing it wrong or is this an issue that needs to be adressed by e.g. breaking the rows somehow? I don't think there is an easy fix for that. Browser don't support automatic wrapping/breaking of TRs and teaching LUA how and when to split long TRs into multiple TRs seems tedious. Also, how to split the TH row so that the columns still match the corresponding TDs in TBODY? Ideas?

See the ugliness here :)

<img width="1261" alt="screen shot 2016-10-30 at 11 50 28" src="https://cloud.githubusercontent.com/assets/859656/19836088/1ab91f6c-9e97-11e6-8be0-919da8f0c03b.png">

**Comment by cshoredaniel** [comment]
@danrl Likely some of the fields in the table have fixed sizes instead of based on the size of the browser window (e.g. public key, my address, etc entry fields) which cause the table to be unable to resize to the browser window.  Might be theme-specific issue too.

**Comment by danrl** [comment]
This has been resolved (for me). I chose a more relaxed design approach in `luci-proto-wireguard` eventually.
