### ISSUE TITLE
OpenVPN interfaces doesn't show ip addresses

### ISSUE THREAD

**Issue by etomm** [openwrt/luci#845]
In the Interfaces page all the interfaces tied to tun/tap devices doesn't show any ip address. This was not the case with CC 15.05.

![lede trunk](https://cloud.githubusercontent.com/assets/6109631/20160541/ead7efd6-a6e7-11e6-96c9-0e26e5a4843a.png)
![openwrt cc 15 05 archer c7](https://cloud.githubusercontent.com/assets/6109631/20160540/ead49f20-a6e7-11e6-8e4d-b78d57da1fc7.png)

As you can see in the first image there is nothing, instead in the second there are ip (the second is CC 15.05).

My /etc/config/network:
```
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'XXXX:XXXX:XXXX::/48'

config interface 'lan'
	option force_link '1'
	option type 'bridge'
	option ifname 'eth0.1'
	option proto 'static'
	option netmask '255.255.255.0'
	option ip6assign '64'
	option igmp_snooping '0'
	option metric '0'
	option stp '1'
	option ipaddr '192.168.0.1'

config device 'lan_dev'
	option name 'eth0.1'
	option macaddr 'XX:XX:XX:XX:XX:XX'

config interface 'wan'
	option ifname 'eth0.2'
	option _orig_ifname 'eth0.2'
	option _orig_bridge 'false'
	option proto 'pppoe'
	option username 'XXX'
	option password 'XXX'
	option ipv6 'auto'
	option metric '1'
	option peerdns '0'
	option dns '127.0.0.1'
	option keepalive '20 4'

config device 'wan_dev'
	option name 'eth0.2'
	option macaddr 'XX:XX:XX:XX:XX:XX'

config interface 'wan6'
	option ifname 'eth0.2'
	option proto 'dhcpv6'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option ports '1 2 3 4 0t'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option ports '5 0t'

config interface 'bridgetcp'
	option proto 'none'
	option auto '1'
	option ifname 'tun1'
	option igmp_snooping '0'

config interface 'vpn'
	option _orig_ifname 'tun2'
	option _orig_bridge 'false'
	option ifname 'tun2'
	option proto 'none'
	option auto '1'
	option delegate '0'
	option defaultroute '1'
	option metric '100'

config interface 'P2P'
	option proto 'none'
	option ifname 'tun3'
	option auto '1'
	option delegate '0'
	option defaultroute '1'
	option metric '90'

config interface 'bridgeudp'
	option ifname 'tun-br-vpnudp'
	option proto 'none'
	option auto '1'
	option igmp_snooping '0'

config interface 'setup'
	option proto 'static'
	option delegate '0'
	option ipaddr '192.168.254.1'
	option netmask '255.255.255.0'
```

**Comment by bol-van** [comment]
Guys, the thing that is very wrong with openvpn is that it does not intergrate with netifd. I created my own netifd helpers so that its possible to ifup/ifdown openvpn interface. I find this approach much more compliant and comfortable.

**Comment by cshoredaniel** [comment]
@bol-van Have you got them published (and what license?) anywhere?  It would be good to get openvpn into the modern age from the point of view of openwrt.

**Comment by bol-van** [comment]
I can share my work but I dont pretend it to be the best quality and decisions made was perfect. I done it for myself.

**Comment by jscinoz** [comment]
@bol-van Are you still willing to share your netifd helpers for openvpn? The lack of netifd integration is causing additional issues (openwrt/openwrt#220, openwrt/packages#3486).

**Comment by bol-van** [comment]
No problem. I'll share my work. But I will not take part in making it clean and compliant, i've finished with programming and do it only for myself and dont share my code because it can be dirty and does not meet clean standards. Take it as is and do whatever you want.
https://www.sendspace.com/file/9vmqh4

My code relies on standard uci openvpn config in /etc/config/openvpn  but requires to make section "enabled 0" to stop it from launch by /etc/init.d/openvpn.
This approach leaves luci-app-openvpn working
Add proto section to /etc/config/network as in example

**Comment by dibdot** [comment]
not a LuCI issue at all.

**Comment by brianjmurrell** [comment]
> https://www.sendspace.com/file/9vmqh4

Is 404 unfortunately.
