### ISSUE TITLE
What is ltn12.pump.all and what does it do ?

### ISSUE THREAD

**Issue by mirjafarabedi** [openwrt/luci#849]
Can anybody help me about Luci.ltn12.pump.all ? I am new to Luci and in one of my projects i should use ltn12.pump.all but i don't know anything about it .
Thanks in advance

**Comment by hnyman** [comment]
This is a bug tracker, not for generic help requests.
You should discuss the topic on the forums:
https://forum.openwrt.org/
https://forum.lede-project.org/
