### ISSUE TITLE
/usr/lib/lua/luci/dispatcher.lua:253: Access Violation

### ISSUE THREAD

**Issue by jow-** [openwrt/luci#85]
**Reported by reporter on 27 Sep 2009 11:30 UTC**
On the LuCI SIP Device Information site, if I press "Configure scan" Ive got an Access Violation

```
/usr/lib/lua/luci/dispatcher.lua:253: Access Violation
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:253: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>
```

Kamikaze (r17736) / LuCI 0.9+svn5349-1

**Comment by hnyman** [comment]
Report from 2009 is related to really ancient 0.9 branch with Kamikaze r17736.
Closing as a stale report.
