### ISSUE TITLE
Keep values of dependent fields

### ISSUE THREAD

**Issue by mguerreiro** [openwrt/luci#853]
Hello,
I use a `Flag` that allows me to enable/disable a whitelist, and this whitelist is stored using a `DynamicList`.
Thing is, when I disable the flag the list is lost. I've tried using `.rmempty = false` on my list, without success.

Sample code : 
```
use_whitelist = s:option(Flag, "use_whitelist","Use whitelist")
use_whitelist.enabled = "on"
use_whitelist.disabled = "off"
use_whitelist.default = use_whitelist.enabled
use_whitelist.rmempty = false

whitelist = s:option(DynamicList, "whitelist", "The list")
whitelist.optional = false
whitelist.datatype = string
-- whitelist.rmempty = false
whitelist.placeholder = "me"
whitelist:depends("use_whitelist", "on")
```

Is this the expected behavior, and is there a way to bypass it? I assume the list is removed here, but won't change it until this matter is discussed. https://github.com/openwrt/luci/blob/6a11f71/modules/luci-base/luasrc/cbi.lua#L1333

For now I have commented out the `depends`.
Thanks! :smile:

**Comment by cshoredaniel** [comment]
I seem to recall that using tracking_missing ( https://github.com/openwrt/luci/blob/6a11f71/modules/luci-base/luasrc/cbi.lua#L1301 ) in an option leaves the setting in the UCI config, but I could be remembering that wrong.

**Comment by cshoredaniel** [comment]
@mguerreiro Have you the opportunity test 'tracking_missing'?

**Comment by mguerreiro** [comment]
Hello. Sorry for the delay and thanks for pinging me.

Using `tracking_missing`, this behavior still occurs: the list is hidden from the web interface and not sent in the POST /config, so it gets removed server-side

**Comment by cshoredaniel** [comment]
@mguerreiro thanks, will keep this open then and hopefully it can be looked into (I don't have time myself at the moment).

**Comment by jow-** [comment]
This is by design. The best solution is to use both `.rmempty = false` and a custom `.write()` implementation that refuses to write empty data.
