### ISSUE TITLE
problem with delete interface

### ISSUE THREAD

**Issue by palat** [openwrt/luci#868]
HI 

i've build opewrt and luci with src from your repo everything work perfectly but when i delete the interface
just got this message on my browser

it happend after apply configuration and jump back to network page

please see messgage below

how can i fix this problem

No page is registered at '/admin/network/network'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file

thank you and sorry for my poor english

maverix

**Comment by hnyman** [comment]
works for me.
Please explain more closely the details, which Openwrt version, how/where you are deleting the interface, what kind of interface you are deleting, etc.

(When I delete an interface from the Network/Interfaces overview page, there is no need to separately "apply configuration")

**Comment by jow-** [comment]
No response after a month
