### ISSUE TITLE
SSH password different from the web interface password in Luci

### ISSUE THREAD

**Issue by mirjafarabedi** [openwrt/luci#881]
Excuse me i ask my question here, because you may think this is not an issue.
The problem in my mind is that why Luci web user interface and ssh passwords are the same ?
I don't want to allow any body that has access to my Luci web user interface with root password , can access to ssh too !
I am aware of that there is a multiuser Luci but i don't want to use it.

Is it good to set a different password to each one (ssh and web gui) from /etc/config ?
Do i have to use multi user Luci ?
Or may you help me to solve this problem ?

**Comment by cshoredaniel** [comment]
Please check the forums or IRC for this type of question.  Ask about how to use only public key encryption with dropbear and make SSH use public/private keys and not password based access.
