### ISSUE TITLE
in order to display this page, you must send the data will repeat the previous action (such as search or order)

### ISSUE THREAD

**Issue by licannlfj** [openwrt/luci#888]
Button class, in order to display this page, you must send the data will repeat the previous action (such as search or order)

**Comment by cshoredaniel** [comment]
Unfortunately this has insufficient to make a useful bug report.  If the issue persists please reopen with the information on what page you are trying to access and what you clicking or what have you, as well the version string LuCI web page, OpenWrt or LEDE and customer build, snapshot, or release.,
