### ISSUE TITLE
No luci-mod-admin-mini / luci-light

### ISSUE THREAD

**Issue by kawk** [openwrt/luci#893]
The luci-mod-admin-mini doesn't seem to be supported anymore. What exactly has to be done to revive it? I'd like to use OpenWrt on a device where only basic networking setup and firmware upgrade functionality are needed.

**Comment by cshoredaniel** [comment]
@kawk It needs a) someone to test b) someone to work on fixes found because of a).  Jo-Philip used to do the majority of the LuCI work and he's gotten busy with life.
