### ISSUE TITLE
Android devices being disconnected.

### ISSUE THREAD

**Issue by zangyedits** [openwrt/luci#900]
The LuCi inteno(client) constantly disconnects android devices, have tried on sony xperia z2, LG G5(H850), and several others, if it's android, your connection does not last long until disconnect. 
Powered by LuCi Trunk (inteno-1.1.19) and Barrier Breaker (r45951)

**Comment by hnyman** [comment]
LuCI has no role in Wifi connectivity. It is only a GUI. All wifi connectivity is handled by the core Openwrt.

Additionally, inteno-1.1.19 sounds quite strange. 

Ps. Barrier Breaker is not actively supported any more. You should use Chaos Calmer 15.05.1 (or newer).
