### ISSUE TITLE
Active leases not working with mutliple dnsmasq instances

### ISSUE THREAD

**Issue by kbabioch** [openwrt/luci#911]
With the recent inclusion of a patch with support for multiple dnsmasq instances (see [this](https://github.com/lede-project/source/pull/408)), the `Active DHCP Leases` table on the `DHCP and DNS` (`admin/network/dhcp`) no longer works correclty. When defining leasefiles (i.e. `option leasefile /tmp/dnsmasq1.leases` vs `option leasefile /tmp/dnsmasq2.leases`), only leases from the first file are displayed. When using the same file for both dnsmasq instances, there seems to be a race condition and only leases of the last instance that writes to this file are displayed.

Hence LUCI needs to be patched, so it supports multiple leasefiles by iterating over all available leasefiles.

**Comment by cshoredaniel** [comment]
@jow- patch for this backported to 17.01 after testing in trunk?

**Comment by aaronjg** [comment]
Fixed by https://github.com/openwrt/luci/pull/4308
