### ISSUE TITLE
Allow to set dhcpv4 disabled

### ISSUE THREAD

**Issue by bastien-roucaries** [openwrt/luci#915]
Hi,

I wish to disable dhcpv4 on some aliased (using @syntax) interface. Could be possible to add a check box and in this case disable the ipv4 panel

**Comment by jow-** [comment]
Such an option already exists:
![disable-dhcp](https://cloud.githubusercontent.com/assets/2528802/21644470/e3eb5c86-d28d-11e6-9478-a7f28d9ff0a7.png)

**Comment by bastien-roucaries** [comment]
No this set option ignore '1' that disable dhcpv6 and dhcpv4. I want to
disable only dhcp for v4 and use ra for v6.

Bastien

**Comment by jow-** [comment]
Option ignore currently only disables dhcpv4 (assuming a standard setup with dnsmasq + odhcpd).

**Comment by bastien-roucaries** [comment]
On Wed, Jan 4, 2017 at 3:27 PM, Jo-Philipp Wich <notifications@github.com>
wrote:

> Option ignore currently only disables dhcpv4 (assuming a standard setup
> with dnsmasq + odhcpd).
>

​Thanks documentation is really bad in this case...​
