### ISSUE TITLE
Linksys WRT1900ACS LuCi opkg packages adresses

### ISSUE THREAD

**Issue by fnnf1** [openwrt/luci#921]
i search for the right opgk config with adresses for my Linksys WRT1900ACS 

best is the complett config like thisWRT1900ACS 

> dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
option check_signature 0
src/gz chaos_calmer_base http://openwrtmirror.example.com/chaos_calmer/15.05/ar71xx/generic/packages/base
src/gz chaos_calmer_packages http://openwrtmirror.example.com/chaos_calmer/15.05/ar71xx/generic/packages/packages 
src/gz chaos_calmer_luci http://openwrtmirror.example.com/chaos_calmer/15.05/ar71xx/generic/packages/luci              
src/gz chaos_calmer_routing http://openwrtmirror.example.com/chaos_calmer/15.05/ar71xx/generic/packages/routing    
src/gz chaos_calmer_telephony http://openwrtmirror.example.com/chaos_calmer/15.05/ar71xx/generic/packages/telephony
src/gz chaos_calmer_management http://openwrtmirror.example.com/chaos_calmer/15.05/ar71xx/generic/packages/management

>

**Comment by hnyman** [comment]
Not related to LuCI.

opkg config is the same in console and in LuCI.
The correct update address for your build gets installed to the firmware as /etc/opkg.conf and/or /etc/opkg/distfeeds.conf depending your software version. With WRT1900ACS I guess it should be in /etc/opkg/distfeeds.conf  (If you have deleted that file, a copy should be in  /rom/etc/opkg/distfeeds.conf )
