### ISSUE TITLE
Could not add source nat on luci

### ISSUE THREAD

**Issue by bastien-roucaries** [openwrt/luci#924]
When I click to add it  do:
firewall.cfg353837=redirect
firewall.cfg353837.enabled=1

But it does not show in snat section of luci...

**Comment by bastien-roucaries** [comment]
I use git-17.007.54272-95d3f26

**Comment by cshoredaniel** [comment]
Did you remember to actually defines the IPs etc (it looks like you added the new section but didn't populate it).  Can you do a screenshot?

**Comment by HyP3r-** [comment]
I have the same error. I use git-17.290.79498-d3f0685.
Here are some screenshots:
![firefox_2017-11-08_15-13-12](https://user-images.githubusercontent.com/8094242/32553589-9cc67d70-c497-11e7-8f39-266387247d91.png)
![firefox_2017-11-08_15-13-22](https://user-images.githubusercontent.com/8094242/32553592-9de227b8-c497-11e7-82c8-031d0ebf0892.png)
![firefox_2017-11-08_15-13-36](https://user-images.githubusercontent.com/8094242/32553594-9f003130-c497-11e7-9df4-35711aabd6d5.png)
![firefox_2017-11-08_15-13-46](https://user-images.githubusercontent.com/8094242/32553595-a0332314-c497-11e7-8ae3-af6e3b2bff33.png)

**Comment by systemcrash** [comment]
Same for me - I run

Powered by LuCI lede-17.01 branch (git-17.298.45605-07e7ff0) / LEDE Reboot 17.01.4 r3560-79f57e422d

I go to Firewall rules ( /cgi-bin/luci/admin/network/firewall/rules ) , and cannot add an SNAT rule, no matter what combination I set there.  I click add and.... Nothing, it just redirects to the rules page.

But if I go to ( /cgi-bin/luci/admin/status/iptables ) I can see that there are some SNAT rules added based on the external WAN port -> LAN port forward rules I added.

**Comment by reiffert2** [comment]
I'm on LuCI Master (git-18.039.58622-76f9f5e) / OpenWrt SNAPSHOT r6021-0219138

Clicking on "Add" below "SOURCE NAT" does not change a thing but instead adds the any any rule on the 2nd image.

Do you need more details? Please let me know.

<img width="1085" alt="screen shot 2018-02-18 at 22 33 05" src="https://user-images.githubusercontent.com/29665021/36357299-52d43c06-14fc-11e8-9809-628483d5141e.png">
<img width="1156" alt="screen shot 2018-02-18 at 22 33 19" src="https://user-images.githubusercontent.com/29665021/36357302-55e0b19a-14fc-11e8-95d5-a654ceafc1d3.png">

**Comment by wallcreeper** [comment]
I encounter exactly the same problem as reiffert2 describes. Also I don't have the wan zone.
Is there a way to configure SNAT by console in the mean time the LUCI UI does not provide this funcionality?

I'm on LuCI lede-17.01 branch (git-17.290.79498-d3f0685)

**Comment by jow-** [comment]
Master / 19.07.1 gained support for `config nat` sections.
