### ISSUE TITLE
DHCPv6: Static IP assignment should also offer to write DUID

### ISSUE THREAD

**Issue by dev-zero** [openwrt/luci#940]
I tried to assign a static IPv6 suffix to my hosts and failed.
Based on the hint given in https://apuntesderootblog.wordpress.com/2014/09/07/static-dhcpv6-leases-in-openwrt/ it started working after I manually added the DUID for the respective hosts (read from `/var/hosts/odhcpd`).
Based on https://en.wikipedia.org/wiki/DHCPv6 I would say this is not a shortcoming of odhcp but rather how it is supposed to work.
luci should therefore offer another field to select one of the DUIDs (possibly giving the currently assigned suffix as a hint for the user).

**Comment by feckert** [comment]
That seems to be fixed.
