### ISSUE TITLE
Build fails: modules/luci-base/Makefile uses "$(1)" instead enviroment variable

### ISSUE THREAD

**Issue by grumbler66rus** [openwrt/luci#941]
I try build the OpenWRT today and build failed.
In the modules/luci-base/Makefile (commit 61fa65f2f99ab05302911cab9527411d3132ba61) at the lines 40-42  used the 1st positional parameter but in the host-build.mk (openwrt/include/host-build.mk) the "Host/Install" called without parameters. At result, script try install files to the "/bin" directory.

In this case I simple replace "$(1)" with the real path, because I don't known what variable should be used here. After this, build proceed continued success.

**Comment by cshoredaniel** [comment]
@grumbler66rus @hnyman @jow- I've confirmed this isn't the case for LEDE; must be a different build in OpenWrt.

**Comment by cshoredaniel** [comment]
@grumbler66rus silly question; what version of OpenWrt (trunk; 15.05?)

**Comment by hnyman** [comment]
On 2017-01-14 13:35, Daniel Dickinson wrote:
> @grumbler66rus [1] silly question; what version of OpenWrt (trunk;
> 15.05?)

I suspect 15.05 build trying to use Luci master. And that is 
unsupported.

**Comment by grumbler66rus** [comment]
@cshoredaniel, OpenWRT trunk. (And I updated post.)

**Comment by hnyman** [comment]
Where are you fetching Openwrt sources?
What is the commit hash of the last commit in Openwrt?

Git.openwrt.org is stale and should not be used
Github.com/openwrt/openwrt has the current sources.

That function call parameter was added in October 2016 and both Openwrt 
trunk and LEDE were fixed to do like OK. Compilation works ok with 
up-to-date sources from github. Or at least worked 2 days ago. But 
git.openwrt.org sources will fail.

See discussion in 
https://github.com/openwrt/luci/commit/4d97a9f6986fb37ce7e69a1ca3f4743334495654

**Comment by grumbler66rus** [comment]
@hnyman , you rigth! I used outdated instruction at russian page of OpenWRT Wiki. Today i will fix this wiki page.
