### ISSUE TITLE
luci wireless overview list wrong ssids for "disabled" interfaces

### ISSUE THREAD

**Issue by dibdot** [openwrt/luci#949]
Hi,
on my travel router I'm using the following setup:

- one configured/active AP interface
- many configured STA interfaces, but only one is active - all other interfaces are "disabled"

In the wireless overview LUCI now populates the ssid of the active STA interface to all other (disabled) STA interfaces, it's hardly possible to maintain the wireless interfaces anymore - see below ... 

Thanks for looking into that!

![luci-wireless](https://cloud.githubusercontent.com/assets/8061346/21960816/424d306c-daf7-11e6-888e-a00d07ae5891.png)

**current wireless status:**
<pre><code>
root@adb2go:~# ubus -S call network.wireless status
{"radio0":{"up":true,"pending":false,"autostart":true,"disabled":false,"retry_setup_failed":false,"config":{"hwmode":"11g","path":"platform\/ar933x_wmac","txpower":18,"country":"00","htmode":"HT20","channel":"1","disabled":false},"interfaces":[{"section":"@wifi-iface[0]","ifname":"wlan0-1","config":{"mode":"ap","ssid":"adb2go","encryption":"psk2+ccmp","key":"xxx","network":["lan"],"mode":"ap","disabled":false}},{"section":"@wifi-iface[1]","ifname":"wwan1","config":{"mode":"sta","ssid":"blackhole","ifname":"wwan1","encryption":"psk2+ccmp","key":"xxx","network":["wwan"],"mode":"sta","disabled":false}}]}}
</pre></code>
**wireless config:**

<pre><code>
root@adb2go:~# uci show wireless
wireless.radio0=wifi-device
wireless.radio0.type='mac80211'
wireless.radio0.hwmode='11g'
wireless.radio0.path='platform/ar933x_wmac'
wireless.radio0.txpower='18'
wireless.radio0.country='00'
wireless.radio0.htmode='HT20'
wireless.radio0.disabled='0'
wireless.radio0.channel='1'
wireless.@wifi-iface[0]=wifi-iface
wireless.@wifi-iface[0].device='radio0'
wireless.@wifi-iface[0].network='lan'
wireless.@wifi-iface[0].mode='ap'
wireless.@wifi-iface[0].ssid='adb2go'
wireless.@wifi-iface[0].encryption='psk2+ccmp'
wireless.@wifi-iface[0].key='xxx'
wireless.@wifi-iface[0].disabled='0'
wireless.@wifi-iface[1]=wifi-iface
wireless.@wifi-iface[1].device='radio0'
wireless.@wifi-iface[1].network='wwan'
wireless.@wifi-iface[1].mode='sta'
wireless.@wifi-iface[1].ssid='blackhole'
wireless.@wifi-iface[1].ifname='wwan1'
wireless.@wifi-iface[1].encryption='psk2+ccmp'
wireless.@wifi-iface[1].key='xxx'
wireless.@wifi-iface[1].disabled='0'
[...]
wireless.@wifi-iface[4]=wifi-iface
wireless.@wifi-iface[4].device='radio0'
wireless.@wifi-iface[4].network='wwan'
wireless.@wifi-iface[4].mode='sta'
wireless.@wifi-iface[4].ssid='WIFIonICE'
wireless.@wifi-iface[4].ifname='wwan4'
wireless.@wifi-iface[4].encryption='none'
wireless.@wifi-iface[4].disabled='1'
[...]
</pre></code>

**Comment by cshoredaniel** [comment]
@jow- Do you think a fix for this should go in 17.01 after testing in trunk?

**Comment by dibdot** [comment]
this has been fixed.
