### ISSUE TITLE
TL-WA830RE V2

### ISSUE THREAD

**Issue by Wyrobnik2011** [openwrt/luci#987]
Hi,
I used your firmware from page and now i cant flash back my Extender to oryginal software can you give me a tip how to do it? Im using firmware from tp-link page and your uploader dosent recognize it

best regards
Wyrobnik

**Comment by hnyman** [comment]
Not related to LuCI user interface itself.

You might ask on Openwrt or LEDE forums, depending on which firmware you installed.

**Comment by Wyrobnik2011** [comment]
https://wiki.openwrt.org/toh/tp-link/tl-wa830re#installation
